### ISSUE TITLE
cmd is executable: false 

### ISSUE THREAD

**Issue by mayankdutta** [neovim/nvim-lspconfig#1002]
No matter what i install this message wont go away, `cmd is executable: false`
This is my [Repo](https://github.com/mayankdutta/neovim_lsp)

`Operating system`
```
macOS big sur
Version 11.2.3
```

`terminal`
```
alacritty
```

`nvim -v`

    NVIM v0.5.0-dev+nightly-347-gbdf3df402
    Build type: Release
    LuaJIT 2.1.0-beta3
    Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210626-3873-1sz0s1q/build/config -I/tmp/neovim-20210626-3873-1sz0s1q/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210626-3873-1sz0s1q/build/src/nvim/auto -I/tmp/neovim-20210626-3873-1sz0s1q/build/include
    Compiled by info@Mayanks-MacBook-Air.local
    
    Features: +acl +iconv +tui
    See ":help feature-compile"
    
       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-bdf3df4_2/share/nvim"

I have tried `tsserver`, `pyright`, in both of them i am getting the same msg. 
 installed them by using this command `npm install -g typescript typescript-language-server`
<br> <br>
![Screenshot 2021-06-27 at 4 24 03 PM](https://user-images.githubusercontent.com/33067129/123541880-42a8eb00-d764-11eb-840c-ba099eb654c0.png)
![Screenshot 2021-06-27 at 4 24 29 PM](https://user-images.githubusercontent.com/33067129/123541882-4472ae80-d764-11eb-91a1-47d6afe07a9e.png)

<br> <br> Please tell where i am going wrong.

**Comment by mayankdutta** [comment]
`Update`, I just tried [LunarVim](https://github.com/ChristianChiarulli/LunarVim) just to see how that works, issue still same. Same `cmd executable` : `false` error

**Comment by mjlbach** [comment]
Seems like tsserver isn't executable :) did you read the readme? Probably it's not on your path. You should follow the debugging instructions

**Comment by mayankdutta** [comment]
yess exactly 
solution: 
```
Looks like you haven't added .npm-global to your path. That is done in the .profile file by convention. You can add the folder to your path.

Either place this in ~/.profile or edit the cmd variable with the exact path.

export PATH=/Users/info/.npm-global/bin:$PATH
The output of the npm global install command shows the location of the typescript language server: /Users/info/.npm-global/bin/typescript-language-server That's the path for your cmd variable
```
