### ISSUE TITLE
Make cssls and html talk to each other

### ISSUE THREAD

**Issue by weeman1337** [neovim/nvim-lspconfig#1004]
I am not sure if that works nor how to do that.

My use cases:
- complete CSS classes from CSS files in HTML documents
- complete CSS classes/ids from HTML files in CSS documents

In my current setup I have just included both language servers as described in the CONFIG.md.

If anyone has a hint about that it would really improve the LSP setup.

**Comment by mjlbach** [comment]
This is an upstream issue for CSS/HTML language servers, there isn't anything we can do client-side to make them "talk to each other", I would suggest filing an issue on their repos if you have suggestions.

**Comment by harrisonmg** [comment]
@weeman1337 Did you ever solve this problem?

Supposedly https://github.com/hrsh7th/vscode-langservers-extracted is simply the vscode language servers, which do work correctly in this regard. Issues can't be made on that repo though.

**Comment by harrisonmg** [comment]
> @weeman1337 / @harrisonmg, have you had any luck with the subj?

Nope, just moved passed it ¯\_(ツ)_/¯
