### ISSUE TITLE
lsp server not attached on BufNewFile, nor after saving it

### ISSUE THREAD

**Issue by svenXY** [neovim/nvim-lspconfig#1006]
- `nvim --version`: NVIM v0.5.0-dev+1455-gf83c25942
- nvim-lspconfig version(commit hash): latest (48e47b4d26e45977d27c06dc1bc116416ca9276d)
- What language server (If the problem is related to a specific language server): gopls, pyright
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): not tested, not relevant
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): see above
- Is the problem isolated to a particular language server: nope
- Operating system/version: macos 11.14

### How to reproduce the problem from neovim startup

nvim existing.go
:lua print(vim.inspect(vim.lsp.buf_get_clients())) # => is attached
:e nonexsting.go
:lua print(vim.inspect(vim.lsp.buf_get_clients())) # => {}
:w # write the file
:lua print(vim.inspect(vim.lsp.buf_get_clients())) # => {}
:wq
nvim nonexisting.go
:lua print(vim.inspect(vim.lsp.buf_get_clients())) # => is attached

### Actual behaviour

see above

### Expected behaviour

LS is also attached for new buffers

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: gopls: configuration checked.

</details>

### LSP log

<details>
<summary>Log file</summary>
no logs for the new buffer
</details>

**Comment by svenXY** [comment]
running :LspStart after having written the new file works, though, but this is not what I am after

**Comment by mjlbach** [comment]
You can also just do `:e` to trigger attaching to a newly created file.

**Comment by bamboozila** [comment]
Same problem here!

**Comment by mjlbach** [comment]
Technically closed in https://github.com/neovim/nvim-lspconfig/pull/955, it's not more lenient (will try to resolve root for files not written to disk). This may cause issues with certain language servers that expect the file to be on disk.
