### ISSUE TITLE
why is snippetSupport not enabled by default?

### ISSUE THREAD

**Issue by irl-segfault** [neovim/nvim-lspconfig#1007]
Hi all!

When testing out the `gopls` NeoVim integration, I noticed that there was no default support for snippets returned from the language server.  For instance, given `var s *pkg.MyTpe`, when typing `s = &p...`, I would expect that as soon as the `p` is written, the snippet for `pkg.MyType{}` is offered as a completion candidate. 

After much searching, I realized this was missing from my config:

```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true;
require'lspconfig'.gopls.setup{
capabilities = capabilities
}

Why is the snippetSupport capability not supported out of the box?  Surely it's not just me that finds this feature extremely useful and if a Language Server returns these, they should work out of the box without needing explicit enablement.

Thoughts?

**Comment by mjlbach** [comment]
We can't enable snippet support by default, because we don't support snippets in core. If we did, and you did not have a snippet plugin, omnifunc based completion would not be reliable.

**Comment by irl-segfault** [comment]
Thanks for the explanation!  For my benefit, can you help me understand what it means that you don't support snippets in core?  Also, I don't even think I have a snippet plugin (only `nvim-lspconfig` and `nvim-compe`), yet the aforementioned config change enables these snippets for me.  What am I missing?

**Comment by irl-segfault** [comment]
Also, what is an omnifunc?

**Comment by lithammer** [comment]
> Also, what is an omnifunc?

See `:help omnifunc`.

**Comment by irl-segfault** [comment]
@lithammer thank you!!
