### ISSUE TITLE
Add support for official Robot Framework language server

### ISSUE THREAD

**Issue by Hubro** [neovim/nvim-lspconfig#1015]
Robocorp has recently created an official LSP implementation for Robot Framework! :tada: 

https://github.com/robocorp/robotframework-lsp/tree/master/robotframework-ls

Let's add support for it in `nvim-lspconfig`!

I very recently moved back from VSCode to vim, so I haven't really looked into language servers yet. I intend to read up on it this weekend, and if it's within my abilities I will attempt to make a pull request for this.

**Comment by mjlbach** [comment]
Should be pretty easy to copy/paste this and create a config, we don't take language server requests but happy to answer questions on a PR :)
