### ISSUE TITLE
Jump to Vsplit?

### ISSUE THREAD

**Issue by andyl** [neovim/nvim-lspconfig#1016]
Coc provides functions that jump to definition in a split window, vsplit and tab.  Here's my current configuration:

```
nmap <silent> \ge :call CocAction('jumpDefinition')<CR>
nmap <silent> \gs :call CocAction('jumpDefinition', 'split')<CR>
nmap <silent> \gv :call CocAction('jumpDefinition', 'vsplit')<CR>
nmap <silent> \gt :call CocAction('jumpDefinition', 'tabe')<CR>
```

AFAIK, nvim-lsp only gives an option to jump in the current pane.

`vim.lsp.buf.declaration()` - Jumps to the declaration of the symbol under the cursor.

Is there a way with nvim-lsp to jump-to-definition in a split window??

**Comment by justinmk** [comment]
This can be done with basic vimscript. 

For questions about usage/configuration, try 
- http://discourse.neovim.io/ 
- https://vi.stackexchange.com
- https://neovim.io/#chat
The issue tracker is for bugs and feature requests.
