### ISSUE TITLE
Make a website like lsp-mode (emacs)

### ISSUE THREAD

**Issue by mjlbach** [neovim/nvim-lspconfig#1027]
I think we should have a website like emacs lsp-mode does. It's very clear, easy to search through, and much more readable than CONFIG.md

Please reach out to me if you have web development experience and are interested in working on this.

https://emacs-lsp.github.io/lsp-mode/
https://github.com/emacs-lsp/lsp-mode/tree/gh-pages
https://squidfunk.github.io/mkdocs-material/

**Comment by marcushwz** [comment]
Hi @mjlbach , is anyone working on this yet? I can contribute to this if you still need help. Maybe we can do this with [Jekyll](https://jekyllrb.com) with theme like [this](https://idratherbewriting.com/documentation-theme-jekyll/index.html) and host it with github pages.

**Comment by mjlbach** [comment]
No one yet! I just had this idea after the release stream yesterday (thinking about making lsp as easy/accesible as possible).

I'm totally cool with whatever stack makes sense, I think so long as the content is in markdown/pulled automatically from CONFIG.md or modified dump of our docgen it's fine. The other main static site generators I'd consider would be [hugo](https://gohugo.io/) and [zola](https://www.getzola.org/). My main concern would be the search functionality, as I think Jekyll's is limited to tags/headers, which might be fine. I think of the three I lean towards zola (I use hugo for my website and it can be kind of a headache with the templating system), but not dead set on anything!

**Comment by justinmk** [comment]
> It's very clear, easy to search through, and much more readable than CONFIG.md

is it easier than a single markdown file? bootstrapping another stack will require maintenance. And the UI will be different than github, which maintains the UI (and nice features such as markdown TOCs, verioning, full text search) for us. 

neovim.io itself actually could use help with maintenance. So it really seems like a misallocation to create another website (or subdomain/subpage tree), while we don't have anyone giving much attention to the existing one.

**Comment by mjlbach** [comment]
There shouldn't be much of a maintenance burden as it would be auto-generated from CONFIG.md using a static site generator which would continue to work so long as we don't make major formatting changes to our documentation. 

We could have a more general conversation about improving the website (and the display of documentation on it), I think having an indexed/searchable portion of the website for language server at least would be valuable, CONFIG.md is getting very large.

**Comment by andersevenrud** [comment]
With some minor changes to the markdown templates and splitting out the file generation I managed to very easily set up a MkDocs (and material theme as suggested) page. Ex: https://andersevenrud.github.io/nvim-lspconfig-web/languages/pyls/

**Comment by mjlbach** [comment]
@andersevenrud wow, that looks extremely good (even moreso for it being done in less than a day!). I think this would be a good place to start iterating on  (we should add some of the wiki links, clean up the docs, figure out a better solution for details> as some of the lists can be long). It can be an unofficial thing for now until we figure out what to do with re: neovim.io.

**Comment by andersevenrud** [comment]
@mjlbach I'm not sure if these long lists are much of a problem if they're always placed in the bottom of the document like in my pyls example :thinking:

**Comment by andersevenrud** [comment]
Here's the changes I made to docgen: https://github.com/andersevenrud/nvim-lspconfig/tree/feature/web-docgen . NOTE: it's not pretty!

**Comment by mjlbach** [comment]
I don't think that's that bad, we can discuss docgen changes to support this too on a PR. I'm going to be less active for a couple weeks in this post-0.5 phase (other than bugfixes), and there's still some discussions on the neovim.io website to be had, but I don't want that to come across as me not being actively invested/interested.

**Comment by andersevenrud** [comment]
@mjlbach I just made some slight improvements to the generated documents so that the "Commands and default values" section no longer is just a block of markdown. I think this looks a bit nicer.

>  I'm going to be less active for a couple weeks

Okay. I just started my summer vacation with zero plans for the first week, so I'll probably go over this and tidy it up and make a PR that includes the web codebase from the repo I linked.

**Comment by marcushwz** [comment]
> > It's very clear, easy to search through, and much more readable than CONFIG.md
> 
> is it easier than a single markdown file? bootstrapping another stack will require maintenance. And the UI will be different than github, which maintains the UI (and nice features such as markdown TOCs, verioning, full text search) for us.
> 
> neovim.io itself actually could use help with maintenance. So it really seems like a misallocation to create another website (or subdomain/subpage tree), while we don't have anyone giving much attention to the existing one.

Hi @justinmk , how do I reach out if I want to help contribute to `neovim.io`?

**Comment by kutsan** [comment]
There's also this https://docusaurus.io/ if anyone is interested.

**Comment by andersevenrud** [comment]
> There's also this https://docusaurus.io/ if anyone is interested.

This was the first thing I tried out (and then VuePress), but I found it very slow to work with.

**Comment by kutsan** [comment]
@andersevenrud Hmm, I'm not sure what went wrong but the project is backed by Facebook developers and used in leading libraries like Redux, React Native, Jest etc. in production. So, I'm pretty sure it's not going to fade away soon and will continue to get updates. So, it could be a better future investment.
Don't get me wrong, it's just my opinion of course, your demo page looks really awesome. Well done.

**Comment by andersevenrud** [comment]
@kutsan The build performance was pretty good when it hit the cache, but in a cold state it was quite sluggish -- at least on my system (25s vs 2s). Also it requires 260M of dependencies vs 12M for mkdocs :sweat_smile:

Not that performance is super important here as this most likely will be an automated job, but mkdocs is way faster and greener.

**Comment by mjlbach** [comment]
@andersevenrud Sorry, I figured out internally how I want to do this, let's move it out from the official neovim banner. I created a nvim-lsp organization that we can host the website under (possibly on GH pages). Sorry for the delay, life stuff :/

**Comment by andersevenrud** [comment]
@mjlbach No worries. I honestly forgot about this :slightly_smiling_face:

**Comment by mjlbach** [comment]
For now, we're going to manage this separately from the neovim organization/lspconfig. We can discuss integrating with core documentation at some point.
