### ISSUE TITLE
#1022 breaks `powershell_es`

### ISSUE THREAD

**Issue by uyha** [neovim/nvim-lspconfig#1031]
- `nvim --version`: 0.5
- nvim-lspconfig version(commit hash): 5e41f4a7b84a26d57d7eda5c91396bccb1752f57
- What language server (If the problem is related to a specific language server): `powershell_es`
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): not tried
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): not tried
- Is the problem isolated to a particular language server: `powershell_es`
- Operating system/version: Windows 10 Build 19043

After #1022, the check for `cmd` being not `nil` is incorrect for `powershell_es` since it sets `cmd` based on the `bundle_path` variable.

### How to reproduce the problem from neovim startup
Config `powershell_es` with `bundle_path` as indicated in `CONFIG.md`.
### Actual behaviour
Issue error: `E5113: Error while calling lua chunk: ...ck\packer\start\nvim-lspconfig\lua\lspconfig\configs.lua:34: cmd: expected table, got nil`
### Expected behaviour
`powershell_es` is loaded as normally without error

**Comment by mjlbach** [comment]
Should be fixed by #1032. Sorry about that, we should probably change how powershell works to modify a cmd string or something, I would like to implement stricter validation for our configs.
