### ISSUE TITLE
Error executing vim.schedule lua callback: [string ":lua"]:47: attempt to call f ield 'nvim_multiline_command' (a nil value)

### ISSUE THREAD

**Issue by 3301n** [neovim/nvim-lspconfig#1033]
- `nvim --version`:0.5
- nvim-lspconfig version(commit hash):
- What language server (If the problem is related to a specific language server):pyright
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):it occurs on pyright
- Is the problem isolated to a particular language server:
- Operating system/version:kali linux 

### How to reproduce the problem from neovim startup
Opening a python file using nvim
### Actual behaviour
showing error sign 
Error executing vim.schedule lua callback: [string ":lua"]:47: attempt to call field 'nvim_multiline_command' (a nil value)

### Expected behaviour
I dont want this error to show in the status line
### Health check
<details>
<summary>Checkhealth result</summary>
## Checking language server protocol configuration
    4   - ERROR: rust_analyzer: The given command "rust-analyzer" is not executable.
    5   - INFO: pyright: configuration checked.
    6   - ERROR: gopls: The given command "gopls" is not executable.

</details>

### LSP log

<details>
<summary>Log file</summary>

</details>

**Comment by mjlbach** [comment]
Are you on a recent commit? Those were removed a long time ago...

https://github.com/neovim/nvim-lspconfig/commit/6076721c2cbe17b67d8cedc4f0b5694c35bca16f
