### ISSUE TITLE
Cursor enters into LSP hover buffer

### ISSUE THREAD

**Issue by Tinku10** [neovim/nvim-lspconfig#1037]
- `nvim --version`: 0.5
- nvim-lspconfig version(commit hash): 625017d
- What language server (If the problem is related to a specific language server): All
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): Tried in both angularls and clangd
- Is the problem isolated to a particular language server: I guess no
- Operating system/version: Ubuntu 20.04

The cursor enters into the completion buffer if I use the below mentioned command by mistake twice. And if I go to insert mode in that buffer there is error which is desirable as that buffer is read only.

**The command to get the hover buffer**

```lua
buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
```

**How to reproduce**
1. Press ```<S-k>``` on an item to bring the hover buffer.
2. Again press ```<S-k>```, and this time the cursor enters into the hover buffer.

**Expected behavior**
I think it is safe to not enter into the hover definition buffer (even if I try to enter into it, maybe by mistake) as it does not make any sense to do so.

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: groovyls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: denols: configuration checked.
  - INFO: html: configuration checked.
  - INFO: tailwindls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: vuels: configuration checked.
</details>

**Comment by clason** [comment]
This is intended; the rationale is that you might wish to yank something from the hover window to paste somewhere else.

**Comment by mjlbach** [comment]
You're also free to override the built-in hover handler to set the option `focusable` to false

**Comment by edg-l** [comment]
For anyone wondering how to do that:

```lua
vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(
  vim.lsp.handlers.hover, { focusable = false }
)
```
