### ISSUE TITLE
Prisma LSP fails

### ISSUE THREAD

**Issue by petertriho** [neovim/nvim-lspconfig#1043]
- `nvim --version`: v0.5.0 and 
```
NVIM v0.6.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-RfWiLA/neovim-0.5.0+ubuntu2+git202107051758-f515baedc-d569569c9=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-RfWiLA/neovim-0.5.0+ubuntu2+git202107051758-f515baedc-d569569c9/build/config -I/build/neovim-RfWiLA/neovim-0.5.0+ubuntu2+git202107051758-f515baedc-d569569c9/src -I/build/neovim-RfWiLA/neovim-0.5.0+ubuntu2+git202107051758-f515baedc-d569569c9/.deps/usr/include -I/usr/include -I/build/neovim-RfWiLA/neovim-0.5.0+ubuntu2+git202107051758-f515baedc-d569569c9/build/src/nvim/auto -I/build/neovim-RfWiLA/neovim-0.5.0+ubuntu2+git202107051758-f515baedc-d569569c9/build/include
Compiled by buildd@lgw01-amd64-029

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
- nvim-lspconfig version(commit hash): `4e8a6bb35f80e5e37c14b92b5db9abaf2dc6605f`
- What language server (If the problem is related to a specific language server): `prismals` https://github.com/neovim/nvim-lspconfig/pull/919/files
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): Nope
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): Nope
- Is the problem isolated to a particular language server: Yes (prismals)
- Operating system/version: Ubuntu 20.04.2 LTS, MacOS 11

### How to reproduce the problem from neovim startup
1. Start typing in .prisma file
2. Errors
### Actual behaviour
Error message (:messages)
```
prisma-fmt error'd during linting.
SyntaxError: Unexpected end of JSON input

Request Actions:
Type number and <Enter> or click with the mouse (q or empty cancels):
```
### Health check
<details>
<summary>Checkhealth result</summary>

health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v14.17.1 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - python         ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - json           ✓ ✓ ✓ ✓ . 
  - typescript     ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - regex          ✓ . . . . 
  - c              ✓ ✓ ✓ ✓ ✓ 
  - bash           ✓ ✓ ✓ . ✓ 
  - yaml           ✓ ✓ ✓ ✓ ✓ 
  - html           ✓ ✓ ✓ ✓ ✓ 
  - tsx            ✓ ✓ ✓ ✓ ✓ 
  - fish           ✓ ✓ ✓ ✓ ✓ 
  - dockerfile     ✓ . . . ✓ 
  - rust           ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 
  - scss           ✓ . . ✓ . 
  - javascript     ✓ ✓ ✓ ✓ ✓ 
  - jsonc          ✓ ✓ ✓ ✓ ✓ 
  - graphql        ✓ . . ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

health#compe#check
========================================================================
## compe:snippet
  - OK: snippet engine detected.

## compe:mapping
  - OK: `compe#complete` is mapped: (`i  <C-Space>   * compe#complete()`)
  - OK: `compe#confirm` is mapped: (`i  <CR>        * compe#confirm('<CR>')`)
  - OK: `compe#close` is mapped: (`i  <C-C>       * compe#close()`)
  - OK: `compe#scroll` is mapped: (`i  <C-B>       * compe#scroll({ 'delta': -4 })`)

health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"o"**, lhs: **"i"**
  - INFO: rhs: `targets#e('o', 'i', 'i')`
  - WARNING: conflicting keymap exists for mode **"o"**, lhs: **"a"**
  - INFO: rhs: `targets#e('o', 'a', 'a')`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"sr"**
  - INFO: rhs: `<Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"sd"**
  - INFO: rhs: `<Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"[x"**
  - INFO: rhs: `<Plug>unimpaired_xml_encode`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"[y"**
  - INFO: rhs: `<Plug>unimpaired_string_encode`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"[u"**
  - INFO: rhs: `<Plug>unimpaired_url_encode`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>kommentary_motion_default`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"]x"**
  - INFO: rhs: `<Plug>unimpaired_xml_decode`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"]y"**
  - INFO: rhs: `<Plug>unimpaired_string_decode`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"]u"**
  - INFO: rhs: `<Plug>unimpaired_url_decode`
  - WARNING: conflicting keymap exists for mode **"c"**, lhs: **"<Esc>"**
  - INFO: rhs: `<SNR>45_esc()`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **" "**
  - INFO: old rhs: `<Nop>`
  - INFO: new rhs: `<cmd>lua require("which-key").show(" ", {mode = "n", auto = true})<cr>`

health#targets#check
========================================================================
  - WARNING: Conflicting mapping found:
    ab → <Plug>(textobj-sandwich-auto-a)
    b → {'pair': [{'c': ')', 'o': '('}, {'c': ']', 'o': '['}, {'c': '}', 'o': '{'}]}
  - WARNING: Conflicting mapping found:
    ib → <Plug>(textobj-sandwich-auto-i)
    b → {'pair': [{'c': ')', 'o': '('}, {'c': ']', 'o': '['}, {'c': '}', 'o': '{'}]}

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tailwindcss: configuration checked.
  - INFO: html: configuration checked.
  - INFO: typescript: configuration checked.
  - INFO: bash: configuration checked.
  - INFO: dockerfile: configuration checked.
  - INFO: yaml: configuration checked.
  - INFO: json: configuration checked.
  - INFO: lua: configuration checked.
  - INFO: go: configuration checked.
  - INFO: python: configuration checked.
  - INFO: css: configuration checked.
  - INFO: graphql: configuration checked.
  - INFO: rust: configuration checked.
  - INFO: terraform: configuration checked.
  - INFO: efm: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /home/peter/.asdf/shims/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/home/peter/.asdf/shims/python3"
  - INFO: Executable: /home/peter/.asdf/shims/python3
  - INFO: Python version: 3.9.5
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v14.17.1
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for bash: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for dockerfile: ABI version 13
  - OK: Loaded parser for fish: ABI version 13
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for graphql: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for jsonc: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for regex: ABI version 13
  - OK: Loaded parser for rust: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13
</details>

### LSP log

<details>
<summary>Log file</summary>

[ START ] 2021-07-06T16:16:52+1000 ] LSP logging initiated
[ WARN ] 2021-07-06T16:16:53+1000 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server prismals triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ ERROR ] 2021-07-06T16:17:10+1000 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ]	"prisma-fmt error'd during linting.\n"
[ ERROR ] 2021-07-06T16:17:10+1000 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:402 ]	{}

</details>

**Comment by mjlbach** [comment]
Seems like there's an issue with prisma-fmt? I'm guessing this is an upstream issue. You should try running it locally on your codebase.

**Comment by petertriho** [comment]
Thanks for your help. How do I run the language server locally? Also tried using the same language server version as https://github.com/pantharshit00/coc-prisma (2.17) and also get the same errors

**Comment by mjlbach** [comment]
I don't use prisma, but the issue is prisma-fmt needs to be pointed to by prismaFmtBinPath, the empty string in the default config will lead to this error.

```lua
 settings = {
      prisma = {
        prismaFmtBinPath = "";
}
};
```

**Comment by petertriho** [comment]
I've tried building and providing the path to the prisma-fmt binary from https://github.com/prisma/prisma-engines to the config, and it gives the same error.
```
prisma-fmt error'd during linting.
SyntaxError: Unexpected end of JSON input
```

I also believe installing the prisma lsp through npm (`npm install -g @prisma/language-server`) already comes with its own prisma-fmt binary.

**Comment by timcole** [comment]
Personally experiencing the same issue if anyone has any ideas.

https://user-images.githubusercontent.com/6754577/126883703-e4f544c9-f443-4411-a4dc-5d15cf7c12b5.mp4

**Comment by maxmx03** [comment]
> Personally experiencing the same issue if anyone has any ideas.
> 
>  prismalsp.mp4

I fixed with

```
Default Values:
    cmd = { "prisma-language-server", "--stdio" }
    filetypes = { "prisma" }
    root_dir = root_pattern(".git", "package.json")
    settings = {
      prisma = {
        prismaFmtBinPath = ""
      }
    }
```

`prismaFmtBinPath = "node_modules/@prisma/engines"`

how i find the solution: https://www.prisma.io/docs/concepts/components/prisma-engines


my config:

```
   local servers = { 'html', 'pylsp', 'tsserver', 'vimls', 'cssls', 'graphql', 'prismals'}
    
   for _, lsp in ipairs(servers) do
           require('lspconfig')[lsp].setup {
                  -- You will probably want to add a custom on_attach here to locally map keybinds to buffers with an active client
                 -- on_attach = on_attach,
                  capabilities = capabilities,
                  settings = {
                         prisma = {
                                 prismaFmtBinPath = "node_modules/@prisma/engines"
                                  }
                         }
 }
 end
```

**Comment by maxmx03** [comment]
I fix by modifing prisma/language-server

![Captura de tela de 2021-08-18 08-38-52](https://user-images.githubusercontent.com/50273941/129892132-ab391914-ca2c-4cb0-b139-46be9c0e8e66.png)

inside function lin has a try catch, only you have to do is deleted the lines inside catch

**Comment by maxmx03** [comment]
i tried to fix manually but the server stop running.

![Captura de tela de 2021-08-18 09-09-05](https://user-images.githubusercontent.com/50273941/129904800-bc519c66-767f-43af-a34b-126503df9781.png)
![Captura de tela de 2021-08-18 10-11-45](https://user-images.githubusercontent.com/50273941/129904808-377b80cd-2e3c-4c68-816c-3d28f2a540b5.png)

**Comment by Jacob87** [comment]
Same issue here this unusable :( I need to open VScode every time I want to edit a prisma file lol.

**Comment by mjlbach** [comment]
I'm going to be unable to fix this,so I recommend reaching out to the prisma authors.

**Comment by petertriho** [comment]
This issue appears to be fixed for me now with `@prisma/language-server@3.1.103`

**Comment by vuki656** [comment]
For me it's still broken on `3.1.103`. Anyone else?

**Comment by petertriho** [comment]
I'm also following `HEAD`

**Comment by maxime50** [comment]
> For me it's still broken on `3.1.103`. Anyone else?

still broken for me too :(

**Comment by ThongNLM** [comment]
> I don't use prisma, but the issue is prisma-fmt needs to be pointed to by prismaFmtBinPath, the empty string in the default config will lead to this error.
> 
> ```lua
>  settings = {
>       prisma = {
>         prismaFmtBinPath = "";
> }
> };
> ```

Just simply remove the prismaFmtBinPath you guys :smile:
