### ISSUE TITLE
Warning/Error line if too long, can't be read

### ISSUE THREAD

**Issue by sonic182** [neovim/nvim-lspconfig#1046]
There is any doc for make better the errors display? in this example, I cant read all the error line

![imagen](https://user-images.githubusercontent.com/4070466/124735235-25b7a900-df16-11eb-844c-3d1510f51745.png)

this is using elixir-ls as language server

**Comment by mjlbach** [comment]
`:help vim.lsp.diagnostic.show_line_diagnostics() `

**Comment by sonic182** [comment]
> `:help vim.lsp.diagnostic.show_line_diagnostics() `

Ahh thanks!! sorry for my dummy bug, the `<space>e` keymap displays it also...

**Comment by mjlbach** [comment]
Yes, the  `<space>e` keymap is mapped to that function :)

**Comment by vincentqb** [comment]
This was the first page recommended by google, so I'll drop a quick note for others that may land here :) The `show_line_diagnostic` command has been deprecated (as mentioned in the help page and in neovim/neovim#16057), so the new way to set @mjlbach's `<space>e` shortcut is to add this to `init.vim`:
```vimscript
map <space>e :lua vim.diagnostic.open_float(0, {scope="line"})<CR>                                                      
```

**Comment by miratcan** [comment]
> vim.lsp.diagnostic.show_line_diagnostics()

It does nothing?

**Comment by josephchai01** [comment]
If you happen to use LunarVim, use the "gl" keybinding.

https://github.com/LunarVim/LunarVim/issues/1770

**Comment by pewpewnor** [comment]
For those of you who are still looking for the answer,
mapping a key for the function `vim.diagnostic.open_float` works well.

`vim.lsp.diagnostic.show_line_diagnostics()` which was suggested by one of the replies here appears to have been deprecated.

**Comment by gavinmorrow** [comment]
If you use LazyVim, `<space>cd` should work.
(just adding this because it's one of the first results on google)

**Comment by Underday** [comment]
> If you use LazyVim, `<space>cd` should work. (just adding this because it's one of the first results on google)
this probably solves a lot of people's problems, good addition

**Comment by Suamppa** [comment]
> This was the first page recommended by google, so I'll drop a quick note for others that may land here :) The `show_line_diagnostic` command has been deprecated (as mentioned in the help page and in [neovim/neovim#16057](https://github.com/neovim/neovim/pull/16057)), so the new way to set [@mjlbach](https://github.com/mjlbach)'s `<space>e` shortcut is to add this to `init.vim`:
> 
> map <space>e :lua vim.diagnostic.open_float(0, {scope="line"})<CR>

Popping in like the others to add that if you use `init.lua`, the following works:

```lua
vim.keymap.set('n', '<leader>e', vim.diagnostic.open_float, { desc = '[E]xpand diagnostic message' })
```
