### ISSUE TITLE
nvim-lspconfig code action not work with eslint rule

### ISSUE THREAD

**Issue by nnphong1904** [neovim/nvim-lspconfig#1047]
I try to use code action to solve the eslint rule `react-hooks/exhaustive-deps`, but the nvim-lspconfig show message `No code action found`. I don't know if I make any mistake when integrate eslint with nvim-lspconfig. I also cannot use code_action to disable the eslint like what I do in VSCode

**Comment by mjlbach** [comment]
Hi,

Please dont' ede
Please don't delete the issue template. This sounds like a usage questions so I'll direct you to ask our on [discourse](https://neovim.discourse.group/c/7-category/7).

**Comment by entropitor** [comment]
@nnphong1904 For what it is worth, you can have those things with the eslint language server: https://github.com/neovim/nvim-lspconfig/pull/1273
