### ISSUE TITLE
Q: is sumneko_lua configuration example

### ISSUE THREAD

**Issue by maxdevjs** [neovim/nvim-lspconfig#1055]
Is the whole

https://github.com/neovim/nvim-lspconfig/blob/e5e06b4254ccf720c981cbfc4c2733548b4d88c5/CONFIG.md#L6155-L6164

example referred to the deprecated `:LspInstall` method? 

At the end, for the server, all I need is:

`cmd = {"lua-language-server", };`

**Comment by mjlbach** [comment]
`cmd` needs to be either:

1. a wrapped script that starts sumneko with the appropriate arguments ('lua-language-server' if you were using, say, the version I packaged for nix)
2. as it is in the current example, where `sumneko_root_path` points to the directory in which you compiled sumneko
