### ISSUE TITLE
How can I see overloads methods?

### ISSUE THREAD

**Issue by LeeProkhor** [neovim/nvim-lspconfig#1057]
hi all, I use neovim + nvim-lspconfig and nvim-compe plugins in C++ coding, they work OK,
but if method has several overloads (say 3 overloads as on picture below) I can't expand them.

![overloads](https://user-images.githubusercontent.com/86493671/125195481-7f91d900-e25e-11eb-856a-890da9cb17bf.png)
I added this code:
```
require'lspconfig'.clangd.setup {
  cmd = { "clangd", "--completion-style=detailed" } 
}
```
to my ~/.config/nvim/init.lua file, but it looks like there isn't any effect and I can't expand overloaded methods.
How can I expand all overloads methods?

**Comment by mjlbach** [comment]
Did you enable the snippets capability as described in the wiki? 

https://github.com/neovim/nvim-lspconfig/wiki/Snippets

**Comment by LeeProkhor** [comment]
> Did you enable the snippets capability as described in the wiki? Your example above is not passing the correct capabilities.
> 
> https://github.com/neovim/nvim-lspconfig/wiki/Snippets

Yes, I enabled it but the result is same

**Comment by mjlbach** [comment]
I think this is more of a compe issue than an us issue, since your completion results are managed by compe. I would file an issue there :)
