### ISSUE TITLE
exit code 134 when telling pyls-ms to use python3

### ISSUE THREAD

**Issue by dajohans** [neovim/nvim-lspconfig#1073]
- `nvim --version`: v0.6.0-dev(updated today)
- nvim-lspconfig version(commit hash): No idea how to find this
- What language server (If the problem is related to a specific language server): pyls-ms
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No. I have used regular Vim with the plugin vim-lsp and and Emacs with the package lsp-mode and with the same language server. In Vim and Emacs I don't have this issue, only in Neovim with nvim-lspconfig.
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): I have not bothered trying to reproduce it in other python language servers.
- Is the problem isolated to a particular language server: The issue comes when I specify python3 as the interpreter to pyls-ms. Naturally, this is only relevant for python language servers and not when I use clangd or texlab(the only other LSPs I use).
- Operating system/version: Ubuntu Mate 20.04.2(fresh install)

### How to reproduce the problem from neovim startup
Open a python file. It seems like behaviour differs a little depending on the content on the file. I explain a little bit more below.

### Actual behaviour
The client is activated and attached, which I verify by doing `:LspInfo`. Sometimes I'm able to get an autocomplete going with results from the language server just to see that the server really works when it is active. Sometimes it doesn't want to autocomplete, but this is normal for pyls-ms so shortly after launch as it hasn't finnished its code analysis yet. Shortly thereafter(a few seconds), Neovim gives the message "Client 1 quit with exit code 134 and signal 0". After that, `:LspInfo` says that there is no longer any LSP active or attached and if any autocompletion worked initially then it no longer works.

I tested a bit more. I tested with two python files. One file only contains print("Hej") and the other file includes a bit of numpy and matplotlib stuff. On the file with a single print statement, the language server stays active but keeps getting unattached. It reattaches and gets unattached again and this repeats. On the second file, with numpy and matplotlib, the language server doesn't even stay active after it is unattached. The first paragraph under "Actual behaviour" describes what happens for this "numpy+matplotlib"-file. So I guess the error code 134 comes from the language server crashing(maybe this is obvious to you. But from my point of view the error might as well have come from nvim-lspconfig because I don't know how it works).

If I don't set the interpreter to python3 then the language server activates and stays connected, but then it seems that it uses the interpreter named python which is python2. Likewise, if I set the interpreter specifically to python or to python2 then the language server also stays activated and attached. But I of course don't want to use python2 so I'm not satisfied with this.

### Expected behaviour
Language server should stay active and attached.

### Minimal init.vim or init.lua and code sample
I named the file init.log since github didn't want to accept the filetype vim. But this is my init.vim.
<
[init.log](https://github.com/neovim/nvim-lspconfig/files/6819371/init.log)
>

### Health check
I mentioned two behaviours above. This is the health check when opening the file with numpy and matplotlib. The result appears to be the same both before and after the error code 134.
<
[healthcheck.log](https://github.com/neovim/nvim-lspconfig/files/6819376/healthcheck.log)
>

### LSP log
This is the log file from when I opened the file with numpy and matplotlib, that is, when it resulted in error code 134.
<
[lsp.log](https://github.com/neovim/nvim-lspconfig/files/6819381/lsp.log)
>

**Comment by mjlbach** [comment]
`pyls_ms` is borderline abandoned by microsoft (in favor of pyright), I would recommend switching to `pyright` or `pylsp` (`pyls is also abandoned)

I'll probably remove `pyls_ms` shortly
