### ISSUE TITLE
CSS completions from LSP no longer appearing in vim-compe (possible regression)

### ISSUE THREAD

**Issue by benfrain** [neovim/nvim-lspconfig#1076]
- `nvim --version`:
v0.5.0-dev+1436-g510ed996d
- nvim-lspconfig version(commit hash):
(updated to latest)
- What language server (If the problem is related to a specific language server):
CSS/SCSS
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
No, works fine in VSCode and Sublime
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
No
- Is the problem isolated to a particular language server:
Seems to be. TypeScript seems unaffected
- Operating system/version:
macOS 11.4
### How to reproduce the problem from neovim startup
Open a CSS/SCSS file and try and start adding a property such as `wid`.

### Actual behaviour
No completion occurs via nvim-compe (was fine before updating plugins inc. nvim-lspconfig). LSP warnings appear in the file, it is just completions that don't show in nvim-compe

### Expected behaviour
The compe completion should show language completions from the LSP such as `width`

### Health check
<details>
<summary>Checkhealth result</summary>

</details>

### LSP log

<details>
<summary>Log file</summary>
[lsp.log](https://github.com/neovim/nvim-lspconfig/files/6822055/lsp.log)
</details>

**Comment by gegoune** [comment]
Are you sure you have snippet capability enabled? CSS completions are provided as snippets.

**Comment by benfrain** [comment]
Hi @gegoune I can check but my config hasn’t changed. It was working before upgrading my plugins and isn’t anymore. Is the requirement you mention a recent addition (as in last couple of weeks)?

**Comment by benfrain** [comment]
The solution was here: https://github.com/hrsh7th/nvim-compe/issues/480
