### ISSUE TITLE
Unreliable vim.lsp.buf.rename() with gopls in Go project

### ISSUE THREAD

**Issue by jurisbu** [neovim/nvim-lspconfig#1089]
- `nvim --version`:
```
NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.0/build/config -I/build/neovim/src/neovim-0.5.0/src -I/usr/include -I/build/neovim/src/neovim-0.5.0/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.0/build/include
Compiled by builduser

Features: +acl +iconv +tui
```
- nvim-lspconfig version(commit hash): 38e0003d0c40d506e9e46ff55978b78220a76b71
- What language server (If the problem is related to a specific language server): gopls
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): Cannot reproduce on VS Codium.
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): have not tried
- Is the problem isolated to a particular language server: maybe
- Operating system/version: Manjaro Linux

### How to reproduce the problem from neovim startup
Given a simple golang project with `main` and one other package:
```
$ tree
.
├── a.go
├── go.mod
└── mypackage
    └── b.go
```
```
// go.mod
module mymod

go 1.16
```

```
// a.go

package main

import (
	"fmt"
	"mymod/mypackage"
)

func main() {
	var x mypackage.MyData
	fmt.Printf("%v", x)
}
```

```
// mypackage/b.go
package mypackage

type MyData struct{}
```

When I try to rename `MyData` structure in `b.go` with `vim.lsp.buf.rename()` it works first time. But usually does not work consecutive times. Meaning `MyData` is not properly renamed in places it is used, in samle project context it is not updated to new name in `a.go` file.

### Actual behaviour
Consecutiove attempts to rename symbol fail.

### Expected behaviour
Consecutive rename should work reliably.

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: gopls: configuration checked.
</details>

### LSP log

<details>
<summary>Log file</summary>

[lsp.log](https://github.com/neovim/nvim-lspconfig/files/6839422/lsp.log)

</details>

**Comment by mjlbach** [comment]
I can't reproduce this.

**Comment by jurisbu** [comment]
@mjlbach I appreaciate your effort! For now I moved to a different setup to get work done. Maybe will reevaluate nvim + nvim-lspconfig somewhere in future when things stabilize.

**Comment by mjlbach** [comment]
It's stable, nothing is going to change around the renaming functionality as it's implemented correctly client side.

For others, here is a complete gopls container which you can use to verify renaming works as designed:
https://github.com/mjlbach/lsp-containers/tree/master/gopls
