### ISSUE TITLE
elaborate one solution to "how to go_to_definition in new split window"

### ISSUE THREAD

**Issue by haolian9** [neovim/nvim-lspconfig#1092]
with helps of @mjlbach in gitter, I figured out the following solution;
then he suggested i add it to the nvim-lspconfig's wiki, as i am not a native english speaker, and the code seems not fine, i hestated to do it;
so i just put it in here

```lua
local function goto_definition(split_cmd)
  local util = vim.lsp.util

  local handler = function(_, method, result)
    -- stolen from $VIMRUNTIME/lua/vim/lsp/callbacks.lua

    if result == nil or vim.tbl_isempty(result) then
      local _ = log.info() and log.info(method, "No location found")
      return nil
    end

    if split_cmd then
      vim.cmd(split_cmd)
    end

    if vim.tbl_islist(result) then
      util.jump_to_location(result[1])

      if #result > 1 then
        util.set_qflist(util.locations_to_items(result))
        api.nvim_command("copen")
        api.nvim_command("wincmd p")
      end
    else
      util.jump_to_location(result)
    end
  end

  return handler
end

vim.lsp.handlers["textDocument/definition"] = goto_definition('split')
```

**Comment by mjlbach** [comment]
Thanks! I added it to the wiki.

**Comment by damnskippy** [comment]
@mjlbach This was working fine all along until I updated to the latest nightly and it no longer works.
Any thoughts on what might have changed?  It looks like the custom handler is not getting invoked at all.
Thanks.

**Comment by lithammer** [comment]
Probably this:

- https://github.com/neovim/neovim/pull/30982

**Comment by damnskippy** [comment]
Thank you, that seems like it.
Not sure if there is a fix needed in lspconfig to handle this change, or if I should rework how I'm using this.

Previously I was setting handlers:
```
local handlers = {
    ["textDocument/definition"] = goto_definition('split'),
}
```
and passing `handlers` into `require('lspconfig').SERVER.setup()`

**Comment by lithammer** [comment]
I think what you actually what is to use the default "jump to definition" mappings. So in nightly, `tagfunc` is set to to `vim.lsp.tagfunc`. So you should just be able to use `<c-]>` to jump to definition, or `<c-w><c-]>` to jump to definition in a split. See `:help CTRL-]` and `:help CTRL-W_]`.

Otherwise your best bet is probably to create your own `vim.lsp.buf.definition()` function. Wrap it. Or see if there's anything you can do with `vim.lsp.buf.definition({ on_list = function(opts) ... end })`.

**Comment by lithammer** [comment]
See `:help 'splitright'` and `:help 'splitbelow'` as well.
