### ISSUE TITLE
json executable not found

### ISSUE THREAD

**Issue by ashincoder** [neovim/nvim-lspconfig#1095]
- `nvim --version`:
- nvim-lspconfig version(commit hash):
- What language server (If the problem is related to a specific language server):
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
- Is the problem isolated to a particular language server:
- Operating system/version:

### How to reproduce the problem from neovim startup
`LspInstall json` 
Enter a json file

### Actual behaviour
In entering the json file you will get a error saying vscode-json... not found

### Expected behaviour
Don't show anything work out of the box

### Health check
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: lua: configuration checked.
  - INFO: python: configuration checked.
  - INFO: bash: configuration checked.
  - INFO: typescript: configuration checked.
  - ERROR: jsonls: The given command "vscode-json-language-server" is not executable.
  - INFO: json: configuration checked.

### LSP log
nothing crazy
[ START ] 2021-07-22T20:13:17+0530 ] LSP logging initiated
[ START ] 2021-07-22T20:57:37+0530 ] LSP logging initiated

**Comment by lithammer** [comment]
You forgot to fill in a single thing from the issue template. The "json executable not found" in the title is not enough.

**Comment by ashincoder** [comment]
What is it 🤔?

**Comment by lithammer** [comment]
As you can see from the current issue description you haven't filled in any of the questions. Like "How to reproduce the problem from neovim startup", "Actual behaviour", "Expected behaviour" and "Minimal init.vim or init.lua and code sample".

**Comment by ashincoder** [comment]
What do you mean by code sample

**Comment by ashincoder** [comment]
I had to rewrite the issue template twice. Cause I pressed ctrl-w accidently xD. Ok so 
Edited the template

**Comment by mjlbach** [comment]
We don't support installation via lspinstall. If you follow the installation instructions in config.md, and the server still doesn't work, you can file an issue

**Comment by ashincoder** [comment]
Oh sorry My bad.
