### ISSUE TITLE
update imports typescirpt

### ISSUE THREAD

**Issue by JS-junky** [neovim/nvim-lspconfig#1099]
Hi there, i just switched from coc to lsp and everything has been working perfectly until i tried to change a filename... what i was expecting was to see all my imports being updated but nothing happened.

I used the config provided in the repo README and used the typesricpt-language-server installed from npm

**Comment by David-Else** [comment]
You might need to look into https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
