### ISSUE TITLE
NeoVim LSP start error if shell outputs text at start

### ISSUE THREAD

**Issue by supetronix** [neovim/nvim-lspconfig#1100]
Hi,

I am new to VIM and LSP so not sure if it is expected behavior or there is already a solution for it - I looked online and didn't find any help. Only noticed one other person reported it in past on LunarVim but no further discussion.

**Steps to reproduce:**

1. Arch OS and Alacritty Terminal
2. NeoVim 0.5 or Nightly - both have issue
3. Install Rust Analyzer
4. Install and setup LSP plugin in NeoVim:

`Plug 'neovim/nvim-lspconfig'`

and simple setup:
`nvim_lsp.rust_analyzer.setup({})`

5. Now open a simple Rust file to make sure everything is working fine as expected
6. Modify your shell config file (tested on zsh and fish) - edit fish.config to add "neofetch" or "cowsay" to ouput some text before "prompt" appears in new terminal window
7. Open new terminal window to ensure you can see this text
8. Open same Rust file, you will get below error:

`Error detected while processing FileType Autocommands for "rust":
E5108: Error executing lua Vim:E474: Unidentified byte:`

9. Opening any other file besides rust or just opening blank nvim doesn't return this error so I think issue is with LSP loading it or with Rust Analyzer LSP.

Thanks for reviewing.

**Comment by mjlbach** [comment]
1. This isn't an lspconfig problem, lspconfig does not call uv_spawn, which starts the server. That is implemented in neovim core.
2. We're calling uv_spawn to open servers, if your shell files are disrupting the functionality of uv_spawn, you'll need to adjust your shell files.

**Comment by nikp123** [comment]
Unfortunately, even with a blank fish shell this issue still occurs. And from what I see, it's Arch Linux specific.

**Comment by mjlbach** [comment]
If you have a non-standard shell configuration, you're going to have to self-debug. We can ll uv_spawn, that's it. If your shell configuration breaks a core libuv, that's not something we can workaround.

**Comment by nikp123** [comment]
Sorry for asking, but how would I self-debug this? As in what commands or functions I should run. Any guidance would be more than helpful!

**Comment by mjlbach** [comment]
Try not using fish, then see if the problem goes away. Then try setting a default shell for neovim that isn't fish.

**Comment by nikp123** [comment]
Already tried changing the shell, it just broke my setup lol...

Though the 2nd suggestion worked. Thanks.

**Comment by mjlbach** [comment]
If it broke your setup that's probably a good indicator there is a problem, glad changing neovim's shell worked for you. Fish is a pain in my experience.

**Comment by nikp123** [comment]
Not to drag this too further, but essentially all my macros were gone, that's why my system was behaving weirdly.

But yeah, fish doesn't lead to a "predictable" setup though I prefer it's syntax over anything.
