### ISSUE TITLE
Pyright langserver binary name incorrect

### ISSUE THREAD

**Issue by TamaMcGlinn** [neovim/nvim-lspconfig#1104]
Following the instructions for installing pyright, i.e.:

```
sudo npm install -g pyright
```

I get this error from `:checkhealth` :

```
  - ERROR: pyright: The given command "pyright-langserver" is not executable.
```

**Comment by TamaMcGlinn** [comment]
I found the problem. I had previously installed a pip3 package called pyright, which evidently made the above not work. I'm not sure why. But the solution was:

```
pip3 uninstall pyright
sudo npm install -g pyright
```

Hope this helps someone in future.

**Comment by AKS2346** [comment]
It helped me.  Thank you.
