### ISSUE TITLE
Julia LanguageServer.jl lsp throws Missing reference Warning

### ISSUE THREAD

**Issue by SirLukeSchande** [neovim/nvim-lspconfig#1106]
- `nvim --version`:
`NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/include
Übersetzt von brew@BigSur`
- nvim-lspconfig version(commit hash): `b8ab3b84e9ebff631136b5c3e0f5ed3a17c1f3ca`
- What language server (If the problem is related to a specific language server): julials
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): no
- Is the problem isolated to a particular language server: yes
- Operating system/version: macos big Sur

After startup of the julia language server I get a Missing Reference Warning for every Package I import including Standard Library packages like Dates.jl. I tried it both in the current stable as well as neovim nightliy v0.6. 

The problem first emerged after updating Julia to version 1.6.2. Both the standard configuration and a manual configuration using a dedicated run.jl file together with dedicated Project.toml and Manifest.toml. 

Everything else including the SymbolServer works flawlessly.

**Comment by mjlbach** [comment]
I'm using Julia 1.62, opened LanguageServer.jl, and cannot reproduce this issue on the minimal config. The only thing I changed was removing the custom `cmd`, added `julials` instead of pyright, installed `JuliaEditorSupport/julia-vim` as an additional plugin and installed julia language server via `julia -e 'using Pkg; Pkg.add("LanguageServer"); Pkg.add("SymbolServer")`

Can you try to reproduce following these steps?

**Comment by SirLukeSchande** [comment]
I tried to follow your steps. I think I configured the minimal config correctly. 
I still don't get any hover or go to definition for imported Packages. Unfortunately, no warning messages are shown with the minimal config.

**Comment by mjlbach** [comment]
Oh I think I see what you mean, you mean the diagnostics show missing references .

@fredrikekre this seems like a regression from #1079 ?

**Comment by SirLukeSchande** [comment]
I believe so as well. I tried to go through the steps outlined in #1079 and the discourse page linked but had no luck.

**Comment by fredrikekre** [comment]
Can you show your config? I don't know how to reproduce your problem.

Can you show the output of this log statement: https://github.com/neovim/nvim-lspconfig/blob/316a9e824bb0bdc8252a77ba4d4bcbf70861517f/lua/lspconfig/julials.lua#L31 . It should be in the lsplog file.

**Comment by mjlbach** [comment]
I can repro too: 

https://paste.sr.ht/~mjlbach/69e1cab593aa208765e51208e7d8258aa8d4e07d

```
Running language server" VERSION pwd() project_path depot_path\n    server = LanguageServer.LanguageServerInstance(stdin, stdout, project_path, depot_path)\n    server.runlinter = true\n    run(server)\n  ' },  cmd = "julia",  extra = {}}
```

**Comment by SirLukeSchande** [comment]
I hope this is the correct log statement:
`[ ERROR ] 2021-07-26T23:35:26+0200 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]  "rpc"   "julia" "stderr"        '┌ Info: Running language server\n│   VERSION = v"1.6.2"\n│   pwd() = "/Users/sirlukeschande/.config/nvim"\n│   project_path = "/Users/sirlukeschande/.julia/packages/LanguageServer/jiDTR/src"\n└   depot_path = ""\n'`

**Comment by fredrikekre** [comment]
> project_path = "/Users/sirlukeschande/.julia/packages/LanguageServer/jiDTR/src

Well, that certainly looks wrong.

Btw, I believe you need to override `on_new_config` too https://github.com/neovim/nvim-lspconfig/blob/316a9e824bb0bdc8252a77ba4d4bcbf70861517f/lua/lspconfig/julials.lua#L41 because https://github.com/neovim/nvim-lspconfig/blob/316a9e824bb0bdc8252a77ba4d4bcbf70861517f/lua/lspconfig/julials.lua#L42 is wrong. I planned to change that part of the default config in a follow up PR but have not found the time to finish that up yet.

**Comment by mjlbach** [comment]
Overriding to remove `on_new_config` doesn't fix the missing references issue. I'm not familiar enough with how LanguageServer.jl detects the active environment/installed packages to fix this.

**Comment by SirLukeSchande** [comment]
I should have clarified that 

>  [ ERROR ] 2021-07-26T23:35:26+0200 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ] "rpc" "julia" "stderr" '┌ Info: Running language server\n│ VERSION = v"1.6.2"\n│ pwd() = "/Users/sirlukeschande/.config/nvim"\n│ project_path = "/Users/sirlukeschande/.julia/packages/LanguageServer/jiDTR/src"\n└ depot_path = ""\n'

is the log for the minimal config. 
I noticed the wrong project path as well. Since I first noticed it after updating to julia 1.6.2, wonder if the wrong project path is due to https://docs.julialang.org/en/v1/NEWS/#Command-line-option-changes

Using a dedicated run.jl I get the following log:
`[ ERROR ] 2021-07-27T09:44:35+0200 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]  "rpc"   "julia" "stderr"        '┌ Info: Running Julia language server\n│   VERSION = v"1.6.2"\n│   project_path = "/Users/sirlukeschande/.           julia/environments/v1.6"\n└   depot_path = ""\n'`

**Comment by fredrikekre** [comment]
I'll try to submit a PR with the rest of my changes in the coming days.

**Comment by urbainvaes** [comment]
Did you manage to fix this issue? I've been trying as well, but no luck so far... The `missing reference` warnings disappear when I add a `Project.toml` in the root directory of my project, but so do all the other diagnostics...

**Comment by ReneganRonin** [comment]
> > project_path = "/Users/sirlukeschande/.julia/packages/LanguageServer/jiDTR/src
> 
> Well, that certainly looks wrong.
> 
> Btw, I believe you need to override `on_new_config` too
> 
> https://github.com/neovim/nvim-lspconfig/blob/316a9e824bb0bdc8252a77ba4d4bcbf70861517f/lua/lspconfig/julials.lua#L41
> because
> 
> https://github.com/neovim/nvim-lspconfig/blob/316a9e824bb0bdc8252a77ba4d4bcbf70861517f/lua/lspconfig/julials.lua#L42
> is wrong. I planned to change that part of the default config in a follow up PR but have not found the time to finish that up yet.

i noticed this issue just now. i fixed the `server_path` issue. it is just one line see PR #1123

**Comment by SirLukeSchande** [comment]
I don't think this worked. The missing reference warning persists.

**Comment by ReneganRonin** [comment]
> I don't think this worked. The missing reference warning persists.

yeah as it seems, before it is the modules that are showing missing reference, now it is the other stuff and not the modules.
![image](https://user-images.githubusercontent.com/66054069/128387881-ef2920f3-bddb-435c-86ba-2e3d31b98f9e.png)

**Comment by mjlbach** [comment]
@fredrikekre if you summarize what change needs to be done, I can probably do it.

**Comment by mjlbach** [comment]
I'm actually not sure there is an issue @SirLukeSchande 

1. `git clone https://github.com/julia-vscode/LanguageServer.jl && cd LanguageServer.jl`
2. `julia`
3. `]`
4. `instantiate`
5. exit julia
6. make sure cwd is Languageserver.jl (this is important) and run `nvim src/LanguageServer.jl`

The references import fine for me. The important part is instantiating the project passed to project_path, and ensuring that project_path points to the directory containing your project, which should happen if neovim is launched inside the directory.

That being said, I think the current "updated" julia project detection we added is not robust enough, and should copy the logic we use for root directories (traverse up from the current file until we hit a root directory marker).

**Comment by SirLukeSchande** [comment]
When following these steps I don't get the warnings anymore. You are right. 

But I don't understand how to establish this without starting nvim from the LanguageServer.jl folder.

**Comment by mjlbach** [comment]
You can't right now, the current julia script uses the cwd to start the search for the project.toml

**Comment by mjlbach** [comment]
@fredrikekre I think there's a bit of a conflict here in terms of what (julia vs lspconfig) is setting the project path. We're basically doing this twice when we don't need to since lspconfig handles "finding" the project root. If this is more reliable via julia in the server startup, we should probably set the PWD used for julia to the containing directory of the file so it's not dependent on the directory that neovim is opened from.

We can also remove the --project setting from on_new_config.
