### ISSUE TITLE
NVIM detects omnisharp, but doesn't believe it to be executable

### ISSUE THREAD

**Issue by mhegreberg** [neovim/nvim-lspconfig#1107]
- `NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/mark/neovim/build/config -I/home/mark/neovim/src -I/home/mark/neovim/.deps/usr/include -I/usr/include -I/home/mark/neovim/build/src/nvim/auto -I/home/mark/neovim/build/include
Compiled by mark
`
- nvim-lspconfig version(commit hash): 316a9e824bb0bdc8252a77ba4d4bcbf70861517f
- What language server (If the problem is related to a specific language server): Omnisharp
- Operating system/version: debian 10 WSL on win10 1909

I can run omnisharp/run from the terminal, however neovim doesn't seem to believe that it's executable:

![image](https://user-images.githubusercontent.com/11844475/127060227-4f77506e-9e41-42b1-b7c1-375f133d6cb5.png)
![image](https://user-images.githubusercontent.com/11844475/127060324-8a7bf88b-18df-47f6-b619-0de0e85ede36.png)

I'm using the release version of omnisharp, and the mono-devel package from debian's repo. 

I must be doing something wrong, but I can't seem to figure it out. I've gotten all the other LSPs I've tried working with WSL

### Health check
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - ERROR: omnisharp: The given command "~/LSP/Omnisharp/run" is not executable.
  - INFO: pyright: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: powershell_es: configuration checked.

```

**Comment by mjlbach** [comment]
Did you mark all files executable? chmod +x `~/LSP/Omnisharp/run`

**Comment by mhegreberg** [comment]
Aabsolute path fixed the issue, thanks!

Is this documented somewhere that I missed? If not I'd be happy to make a PR to add it to the documentation

**Comment by mjlbach** [comment]
It is :) 

https://github.com/neovim/nvim-lspconfig/blob/48d0782318de64f9487ef73059a28945d7961975/lua/lspconfig/omnisharp.lua#L25

**Comment by mhegreberg** [comment]
thank you! I read that section a bunch of times, I must have missed it.

Glad things are working now.
