### ISSUE TITLE
sourcekit lsp doesn't start for nested Package.swift files in git repos

### ISSUE THREAD

**Issue by keith** [neovim/nvim-lspconfig#1111]
- `nvim --version`:

```
NVIM v0.6.0-dev+81-gc642f3ac2
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210727-93530-i09bz6/build/config -I/tmp/neovim-20210727-93530-i09bz6/src -I/opt/homebrew/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/opt/homebrew/opt/gettext/include -I/tmp/neovim-20210727-93530-i09bz6/build/src/nvim/auto -I/tmp/neovim-20210727-93530-i09bz6/build/include
Compiled by ksmiley@m1.local.lyft-corp.net

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-c642f3a/share/nvim"

Run :checkhealth for more info
```

- nvim-lspconfig version(commit hash): da176608296c7d29d6d8976d5c1ba852cccec43d
- What language server (If the problem is related to a specific language server): sourcekit
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): seems to work fine in VS Code
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): no, other LSPs work fine
- Is the problem isolated to a particular language server: Yes
- Operating system/version: macOS 11.5.1 (m1 macbook pro)

### How to reproduce the problem from neovim startup

1. Open a Swift file from a directory that has a Package.swift file, but isn't the root of the git repo (example repo [nested.zip](https://github.com/neovim/nvim-lspconfig/files/6890141/nested.zip))

Using the same Package.swift file, if it's the root of the `.git` repo works fine.

### Actual behaviour

- `:mes` shows `Client 1 quit with exit code 0 and signal 6`
- the LSP doesn't launch
- the debug LSP log shows:

```
[ ERROR ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]  "rpc"   "xcrun" "stderr"        "Fatal error: Attempted to read an unowned reference but object 0x15400f2f0 was already deallocated"
```

### Expected behaviour

The LSP launches

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: sourcekit: configuration checked.
  - INFO: terraformls: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: rust_analyzer: configuration checked.

</details>

### LSP log

<details>
<summary>Log file</summary>
[ START ] 2021-07-27T20:38:42-0700 ] LSP logging initiated
[ INFO ] 2021-07-27T20:38:42-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:316 ]	"Starting RPC client"	{  args = { "sourcekit-lsp" },  cmd = "xcrun",  extra = {}}
[ DEBUG ] 2021-07-27T20:38:42-0700 ] ...w/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:827 ]	"LSP[sourcekit]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    window = {      showDocument = {        support = false,        <metatable> = <table 1>      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workDoneProgress = true,      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" },        <metatable> = <table 1>      },      workspaceFolders = true,      <metatable> = <table 1>    }  },  clientInfo = {    name = "Neovim",    version = "0.5.0"  },  initializationOptions = vim.empty_dict(),  processId = 92055,  rootPath = "/private/tmp/nested/DrString",  rootUri = "file:///private/tmp/nested/DrString",  trace = "off",  workspaceFolders = { {      name = "/private/tmp/nested/DrString",      uri = "file:///private/tmp/nested/DrString"    } }}
[ DEBUG ] 2021-07-27T20:38:42-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      window = {        showDocument = {          support = false,          <metatable> = <table 1>        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false,            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workDoneProgress = true,        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      }    },    clientInfo = {      name = "Neovim",      version = "0.5.0"    },    initializationOptions = vim.empty_dict(),    processId = 92055,    rootPath = "/private/tmp/nested/DrString",    rootUri = "file:///private/tmp/nested/DrString",    trace = "off",    workspaceFolders = { {        name = "/private/tmp/nested/DrString",        uri = "file:///private/tmp/nested/DrString"      } }  }}
[ DEBUG ] 2021-07-27T20:38:42-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      codeActionProvider = vim.empty_dict(),      colorProvider = true,      completionProvider = {        resolveProvider = false,        triggerCharacters = { "." }      },      definitionProvider = true,      documentHighlightProvider = true,      documentSymbolProvider = true,      executeCommandProvider = {        commands = { "semantic.refactor.command" }      },      foldingRangeProvider = true,      hoverProvider = true,      implementationProvider = true,      referencesProvider = true,      textDocumentSync = {        change = 2,        openClose = true,        save = {          includeText = false        },        willSave = true,        willSaveWaitUntil = false      },      workspaceSymbolProvider = true    }  }}
[ DEBUG ] 2021-07-27T20:38:42-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-07-27T20:38:42-0700 ] ...w/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:854 ]	"LSP[sourcekit]"	"server_capabilities"	{  codeActionProvider = {},  colorProvider = true,  completionProvider = {    resolveProvider = false,    triggerCharacters = { "." }  },  definitionProvider = true,  documentHighlightProvider = true,  documentSymbolProvider = true,  executeCommandProvider = {    commands = { "semantic.refactor.command" }  },  foldingRangeProvider = true,  hoverProvider = true,  implementationProvider = true,  referencesProvider = true,  textDocumentSync = {    change = 2,    openClose = true,    save = {      includeText = false    },    willSave = true,    willSaveWaitUntil = false  },  workspaceSymbolProvider = true}
[ INFO ] 2021-07-27T20:38:42-0700 ] ...w/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:855 ]	"LSP[sourcekit]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = {},    code_lens = false,    code_lens_resolve = false,    completion = true,    declaration = false,    document_formatting = false,    document_highlight = true,    document_range_formatting = false,    document_symbol = true,    execute_command = true,    find_references = true,    goto_definition = true,    hover = true,    implementation = true,    rename = false,    signature_help = false,    signature_help_trigger_characters = {},    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = {      includeText = false    },    text_document_save_include_text = false,    text_document_will_save = true,    text_document_will_save_wait_until = false,    type_definition = false,    workspace_folder_properties = {      changeNotifications = false,      supported = false    },    workspace_symbol = true  }}
[ DEBUG ] 2021-07-27T20:38:42-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "swift",      text = "import DrStringCore\n\nrun(arguments: Array(CommandLine.arguments.dropFirst()))\n",      uri = "file:///private/tmp/nested/DrString/Sources/DrStringCLI/main.swift",      version = 0    }  }}
[ DEBUG ] 2021-07-27T20:38:42-0700 ] ...neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:434 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 1,  params = {    diagnostics = {},    uri = "file:///private/tmp/nested/DrString/Sources/DrStringCLI/main.swift"  }}
[ ERROR ] 2021-07-27T20:38:43-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"xcrun"	"stderr"	"Fatal error: Attempted to read an unowned reference but object 0x128906fc0 was already deallocated"
[ ERROR ] 2021-07-27T20:38:43-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"xcrun"	"stderr"	"Fatal error: Attempted to read an unowned reference but object 0x128906fc0 was already deallocatedFatal error: Attempted to read an unowned reference but object 0x128906fc0 was already deallocated"
[ INFO ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:316 ]	"Starting RPC client"	{  args = { "sourcekit-lsp" },  cmd = "xcrun",  extra = {}}
[ DEBUG ] 2021-07-27T20:38:45-0700 ] ...w/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:827 ]	"LSP[sourcekit]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    window = {      showDocument = {        support = false,        <metatable> = <table 1>      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workDoneProgress = true,      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" },        <metatable> = <table 1>      },      workspaceFolders = true,      <metatable> = <table 1>    }  },  clientInfo = {    name = "Neovim",    version = "0.5.0"  },  initializationOptions = vim.empty_dict(),  processId = 92055,  rootPath = "/private/tmp/nested/DrString",  rootUri = "file:///private/tmp/nested/DrString",  trace = "off",  workspaceFolders = { {      name = "/private/tmp/nested/DrString",      uri = "file:///private/tmp/nested/DrString"    } }}
[ DEBUG ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      window = {        showDocument = {          support = false,          <metatable> = <table 1>        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false,            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workDoneProgress = true,        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      }    },    clientInfo = {      name = "Neovim",      version = "0.5.0"    },    initializationOptions = vim.empty_dict(),    processId = 92055,    rootPath = "/private/tmp/nested/DrString",    rootUri = "file:///private/tmp/nested/DrString",    trace = "off",    workspaceFolders = { {        name = "/private/tmp/nested/DrString",        uri = "file:///private/tmp/nested/DrString"      } }  }}
[ DEBUG ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:496 ]	"decoded"	{  id = 1,  jsonrpc = "2.0",  result = {    capabilities = {      codeActionProvider = vim.empty_dict(),      colorProvider = true,      completionProvider = {        resolveProvider = false,        triggerCharacters = { "." }      },      definitionProvider = true,      documentHighlightProvider = true,      documentSymbolProvider = true,      executeCommandProvider = {        commands = { "semantic.refactor.command" }      },      foldingRangeProvider = true,      hoverProvider = true,      implementationProvider = true,      referencesProvider = true,      textDocumentSync = {        change = 2,        openClose = true,        save = {          includeText = false        },        willSave = true,        willSaveWaitUntil = false      },      workspaceSymbolProvider = true    }  }}
[ DEBUG ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "initialized",  params = {    [true] = 6  }}
[ DEBUG ] 2021-07-27T20:38:45-0700 ] ...w/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:854 ]	"LSP[sourcekit]"	"server_capabilities"	{  codeActionProvider = {},  colorProvider = true,  completionProvider = {    resolveProvider = false,    triggerCharacters = { "." }  },  definitionProvider = true,  documentHighlightProvider = true,  documentSymbolProvider = true,  executeCommandProvider = {    commands = { "semantic.refactor.command" }  },  foldingRangeProvider = true,  hoverProvider = true,  implementationProvider = true,  referencesProvider = true,  textDocumentSync = {    change = 2,    openClose = true,    save = {      includeText = false    },    willSave = true,    willSaveWaitUntil = false  },  workspaceSymbolProvider = true}
[ INFO ] 2021-07-27T20:38:45-0700 ] ...w/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:855 ]	"LSP[sourcekit]"	"initialized"	{  resolved_capabilities = {    call_hierarchy = false,    code_action = {},    code_lens = false,    code_lens_resolve = false,    completion = true,    declaration = false,    document_formatting = false,    document_highlight = true,    document_range_formatting = false,    document_symbol = true,    execute_command = true,    find_references = true,    goto_definition = true,    hover = true,    implementation = true,    rename = false,    signature_help = false,    signature_help_trigger_characters = {},    text_document_did_change = 2,    text_document_open_close = true,    text_document_save = {      includeText = false    },    text_document_save_include_text = false,    text_document_will_save = true,    text_document_will_save_wait_until = false,    type_definition = false,    workspace_folder_properties = {      changeNotifications = false,      supported = false    },    workspace_symbol = true  }}
[ DEBUG ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:395 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didOpen",  params = {    textDocument = {      languageId = "swift",      text = "import DrStringCore\n\nrun(arguments: Array(CommandLine.arguments.dropFirst()))\n",      uri = "file:///private/tmp/nested/DrString/Sources/DrStringCLI/main.swift",      version = 0    }  }}
[ DEBUG ] 2021-07-27T20:38:45-0700 ] ...neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/handlers.lua:434 ]	"default_handler"	"textDocument/publishDiagnostics"	{  client_id = 2,  params = {    diagnostics = {},    uri = "file:///private/tmp/nested/DrString/Sources/DrStringCLI/main.swift"  }}
[ ERROR ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"xcrun"	"stderr"	"Fatal error: Attempted to read an unowned reference but object 0x15400f2f0 was already deallocated"
[ ERROR ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"xcrun"	"stderr"	"Fatal error: Attempted to read an unowned reference but object 0x15400f2f0 was already deallocated"
[ ERROR ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"xcrun"	"stderr"	"Fatal error: Attempted to read an unowned reference but object 0x15400f2f0 was already deallocated"
[ ERROR ] 2021-07-27T20:38:45-0700 ] ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"rpc"	"xcrun"	"stderr"	"Fatal error: Attempted to read an unowned reference but object 0x15400f2f0 was already deallocated"
[ START ] 2021-07-27T20:38:49-0700 ] LSP logging initiated
[ INFO ] 2021-07-27T20:40:12-0700 ] ...w/Cellar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp.lua:1214 ]	"exit_handler"	{}
</details>

**Comment by keith** [comment]
I realized after I submitted this that sourcekit-lsp itself is crashing. I'm not sure why it's not happening with VS Code, but that makes me skeptical that it's a nvim-lspconfig bug

**Comment by mjlbach** [comment]
It does seem from the log that sourcekit is having some internal errors. Perhaps vscode downloads/bundles a different version.

Re: your original question, the root directory pattern for sourcekit is pretty primitive, it will assign the first package.swift it fines as the project root, searching up the filesystem hierarchy for package.swift and subsequently .git at each level. I'm not familiar with swift development, but for rust we were able to use cargo to determine the true root pattern for multi-crate projects. Is there an equivalent for swift?

https://github.com/neovim/nvim-lspconfig/blob/59bc16aa2c9cfc6f8c2a67ae01635eeea1d43943/lua/lspconfig/sourcekit.lua#L8

**Comment by keith** [comment]
I think this configuration is valid for discovering these projects. I ended up testing with the Xcode 13 beta and it does seem like it works there, still not sure what differs in VS Code but I guess that means it's not this config, sorry for the noise!

**Comment by mjlbach** [comment]
Ok! Please let me know if there is anything to improve or document (or file a PR). I don't think we have many swift users yet.
