### ISSUE TITLE
It is not very clear how to pass configs to pylsp

### ISSUE THREAD

**Issue by bastienboutonnet** [neovim/nvim-lspconfig#1116]
I have recently started using this plugin and it was super clear how to set up pyright.

However, I am struggling with how to feed configs for `pylsp`. By configs I mean those options here: https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md

When I asked on their repo, the answers were that the IDE feeds those configs one way or another so they suggested to ask this question on the client side (https://github.com/python-lsp/python-lsp-server/issues/61)

Do you have some pointers I could try?

**Comment by mjlbach** [comment]
Those correspond to the "settings" key, you translate it a nested lua table like so:
```lua
require('lspconfig').setup{
   settings = {
       pylsp = {
           plugins = {
                 flake8 = {
                     config = ...
                 }
            }
        }
    }
}
```

**Comment by bastienboutonnet** [comment]
@mjlbach Awesome, would you feel ok if I opened a PR to beef up the pylsp config markdown with this, I'm sure it could be helpful to other people. Le me know :)

**Comment by mjlbach** [comment]
I think it should be put somewhere, but I'd rather not duplicate the logic for each langauge server, so it would probably be referenced in CONFIG.md as the first section, I haven'ted decided yet (there's an open issue asking for this)

**Comment by bastienboutonnet** [comment]
@mjlbach ah ok I had not seen the issue. No worries, thought I'd help and make sure the answer in this didn't go unseen but makes sense to think about it yes no rush. Thanks for your help it works now :)

**Comment by Balrrach** [comment]
Hello, Im trying to configure the maximum line legth of pylsp. My configuration is:
```lua
require('lspconfig').pylsp.setup{
   settings = {
       pylsp = {
           plugins = {
                 pycodestyle = {
			 maxLineLength = 200,
                 }
                 flake8 = {
			 maxLineLength = 200,
                 }
            }
        }
    }
}
```
And it's not working. Also, 
```lua 
require('lspconfig').setup
```
throws error. Am I doing something wrong?

**Comment by mjlbach** [comment]
> require('lspconfig').setup

This is not a thing.

```
> require('lspconfig').pylsp.setup{
   settings = {
       pylsp = {
           plugins = {
                 pycodestyle = {
			 maxLineLength = 200,
                 }
                 flake8 = {
			 maxLineLength = 200,
                 }
            }
        }
    }
}
```

You'll need to be more specific than not working. Those options appear to require additional system dependencies in your active environment (flake8 and pycodestyle). Is it working but just not respecting those settings? Ensure you are not overwriting your setup with a subsequent call. This question is also better asked on discourse.

**Comment by nyngwang** [comment]
@Balrrach The missing comma between the `pycodestyle` and `flake8`.

**Comment by Balrrach** [comment]
I ended up removing flake8 line. But thanks for taking the time to catch that error!
