### ISSUE TITLE
LSP vs EFM

### ISSUE THREAD

**Issue by jrock2004** [neovim/nvim-lspconfig#1117]
I did not see discussions enabled so I thought I would just open an issue. So what I am not grasping is what is the difference between this plugin and EFM? Should you use both? I have 2 of them and when I hit save I see the following message. So it seems like they are competing against each other. It might be I am just not grasping what both of these do?

![image](https://user-images.githubusercontent.com/655716/127749119-7e2964b3-5c6a-4651-ad6c-d7057f74bc0d.png)

**Comment by mjlbach** [comment]
You should read the README, as it states that discussions are to take place on the discourse. I also answered you questions on a discord channel, but for others, EFM and jsonls are alternative language servers that can both operate on json (EFM operates on a bunch of different  filetypes by wrapping linters/formatters)

**Comment by jrock2004** [comment]
Yes @mjlbach I forgot to come close this after you answered. Sorry
