### ISSUE TITLE
Pyright auto-imports should be code actions

### ISSUE THREAD

**Issue by uninhm** [neovim/nvim-lspconfig#1122]
[![asciicast](https://asciinema.org/a/cDQWD2P810MSnjFxscHVmeMmO.svg)](https://asciinema.org/a/cDQWD2P810MSnjFxscHVmeMmO)

**Comment by uninhm** [comment]
If this is the expected behavior, we should know that option is an auto-import and not just a completion.

**Comment by mjlbach** [comment]
Why do you think this should be code actions? Did you read something in the pyright documentation to suggest otherwise?

Pyright does not implement code actions, it's a minimal language server meant to support pylance.

**Comment by uninhm** [comment]
@mjlbach did you read my second message?

**Comment by mjlbach** [comment]
What menu? We don't offer autocompletion.

**Comment by uninhm** [comment]
> We don't offer autocompletion.

Oh, I forgot that, I'll open an issue in `compe`

**Comment by AckslD** [comment]
@mjlbach Do you have any pointers on how to use pyrights auto-import feature (without using an autocomplete plugin)? I'm a little lost and not even sure where to start looking. Thanks in advance! :)
