### ISSUE TITLE
[Enhancement] LspInfo - Show the source code location where a LSP setting is defined/overwritten

### ISSUE THREAD

**Issue by pidgeon777** [neovim/nvim-lspconfig#1126]
Actually, through `LspInfo` we have information about:

- # clients attached to buffer
- # active clients
- clients that match the current filetype

It would be great to add:
- Source file location(s) where the current LSP settings have been defined/overwritten.

Use case:

When installing a new LSP based plugin, a preexisting LSP client definition (i.e. setting) could be overwritten by it (for example, the settings for `clangd` LSP).

It would be great to understand where the LSP settings are defined/overwritten for a given client.

Moreover, in Vim there is a way to see the source code location where a mapping gets overwritten (for example, by a certain plugin).

**Comment by mjlbach** [comment]
This is not feasible.
