### ISSUE TITLE
[Enhancement] LspInfo - Show all of the capabilities of the currently active LSP server

### ISSUE THREAD

**Issue by pidgeon777** [neovim/nvim-lspconfig#1127]
It would be nice for LspInfo to also display some info about the LSP capabilities of the currently attached server. E.g.:

- Hover
- GoTo definition
- Look for references
- Call hierarchy
- ...

**Comment by mjlbach** [comment]
We already discussed this in https://github.com/neovim/nvim-lspconfig/pull/810 and I decided against it, unless it's implemented with folds in a way that doesn't already overpopulated the (already crowded) :LspInfo window.
