### ISSUE TITLE
Html and htmldjango LS is not working in nvim

### ISSUE THREAD

**Issue by Johan-Palacios** [neovim/nvim-lspconfig#1145]
- `nvim --version`:NVIM v0.6.0-dev
- nvim-lspconfig version(commit hash): 47d80fa
- What language server (If the problem is related to a specific language server):HTML
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): No
- Is the problem isolated to a particular language server: No
- Operating system/version:Ubuntu 20.04 WLS

Hi the problem is that Html lsp is not working, but the server is running, this issue is reproduced in html and htmldjango files, 

![image](https://user-images.githubusercontent.com/77251405/129456469-a5768180-6584-4c12-9b2d-240393457415.png)

The other language servers work well

**Comment by mjlbach** [comment]
Did you enable snippets as mentioned in config.md?

**Comment by Johan-Palacios** [comment]
Yes, I have snippets capability enable in my config

![image](https://user-images.githubusercontent.com/77251405/129635044-5658b6f3-ad00-4b62-ad72-01f2f220ab8a.png)

**Comment by mjlbach** [comment]
Yes, but is that capabilities used? it has to be passed to the `setup{}` call for htmlls

**Comment by Johan-Palacios** [comment]
of course 

![image](https://user-images.githubusercontent.com/77251405/129647241-473ec202-d2c8-4afd-b6f9-a3bcd40dfad2.png)

**Comment by Johan-Palacios** [comment]
of course 

![image](https://user-images.githubusercontent.com/77251405/129647241-473ec202-d2c8-4afd-b6f9-a3bcd40dfad2.png)

**Comment by mjlbach** [comment]
Seems to be working fine for me, you can diff against this container/setup to see what is wrong in your config

https://github.com/mjlbach/lsp-containers/tree/master/htmlls

**Comment by Johan-Palacios** [comment]
Hey i tried your config, and in this it works

![image](https://user-images.githubusercontent.com/77251405/129777133-ae25a9d5-1cc0-4846-bf03-d5597c5200a8.png)


It's probably that is an issue in my config, Here is my [config](https://github.com/Johan-Palacios/Nvim-config/blob/master/lua/lsp/init.lua)

**Comment by mjlbach** [comment]
Glad to hear it :) Unfortunately, I don't know what could be wrong on your system/setup, so I hope the docker container will be a useful debugging tool.

As this isn't an issue with lspconfig, I'm closing. You can ask questions about your configuration/usage of the built-in language server client on our [discourse](https://neovim.discourse.group/c/7-category/7).

**Comment by Johan-Palacios** [comment]
oh OK thanks I will try to solve the problem

**Comment by Johan-Palacios** [comment]
I solve the problem XDDDDDDDDD

![image](https://user-images.githubusercontent.com/77251405/129787150-47df2dca-8663-4f05-b947-c20e84f64349.png)

**Comment by mjlbach** [comment]
What was the issue?

**Comment by Johan-Palacios** [comment]
Is a bug with npm, only i uninstalled and installed this, and it works is very crazy
