### ISSUE TITLE
Introduce override_default_config(config) API in lieu of setup(config) for server-specific configuration

### ISSUE THREAD

**Issue by YodaEmbedding** [neovim/nvim-lspconfig#1152]
It might be nice to introduce `configure()`:

```lua
require"lspconfig".sumneko_lua.configure {
  on_attach = on_attach,
  ...
}
```

That can be used instead of `setup()`.

This way, the less bulky iteration setup style remains the same:

```lua
local servers = {
  "sumneko_lua",
  "pyright",
}

for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup { on_attach = on_attach }
end
```

...and one can easily modify the iteration loop:

```lua
for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup(coq.lsp_ensure_capabilities {
    on_attach = on_attach,
  })
end
```

...without having to manually specify:

```lua
require"lspconfig".sumneko_lua.setup(
  coq.lsp_ensure_capabilities {
    on_attach = on_attach,
    ...
  }
)
```

...for each customized language server.

---

A related issue is that there does not seem to be a way to easily access and override the `default_config`s from within the API for each language server.

**Comment by justinmk** [comment]
are you asking for a way to set "default" or global values? that could be useful, but should not use a similar-yet-different function name (configure vs setup). maybe it could be a setup() function that lives on lspconfig module directly.

**Comment by YodaEmbedding** [comment]
Yes. Perhaps another name is `override_default_config`.

**Comment by mjlbach** [comment]
We already have this 

https://github.com/neovim/nvim-lspconfig/blob/master/ADVANCED_README.md#example-override-default-config-for-all-servers

**Comment by YodaEmbedding** [comment]
That applies the same configuration to all servers. This is intended for server-specific configuration, just like `server_name.setup()`.

The problem with using `setup()` directly for server-specific configuration is that one can't use the `for` loop style shown above. The intended goal of this feature request is to decouple configuration from any other things that `setup()` does.

**Comment by mjlbach** [comment]
I still don't see the utility, the setup{} call is effectively this, with the only side effect being adding the filetype watcher which can be disabled with `autostart  = false`

**Comment by YodaEmbedding** [comment]
I suppose one could maintain their own config table instead, so the proposed API isn't as useful as I imagined initially:

```lua
local servers = {
  "sumneko_lua",
}

local configs = {
  sumneko_lua = { ... },
}

for _, lsp in ipairs(servers) do
  local config = configs[lsp] or {}
  config.on_attach = on_attach
  nvim_lsp[lsp].setup(config)
end
```

Perhaps something like this could be added to the ADVANCED_README.md, but other than that, the issue may be closed.

**Comment by mjlbach** [comment]
Closing as resolved
