### ISSUE TITLE
Clangd only supports 'file' URI scheme for workspace files

### ISSUE THREAD

**Issue by Szymzal** [neovim/nvim-lspconfig#1154]
I am trying set lspconfig for c++ language. So I installed into my computer llvm with clang version 11.0.0 on windows.
But I looked into lsp.log file and I have many errors like this:
`Clangd only supports 'file' URI scheme for workspace files: C:\\dev\\C++\\main.cpp`

In my understanding I need the uri look like this:
`file:///C:/dev/C++/main.cpp`
but it is looking like this:
`C:\\dev\\C++\\main.cpp`

I could not find any information about it.
Is there any fix for this?
If I made any errors, sorry for my english.

**Comment by mjlbach** [comment]
There is a tracking issue for this already in neovim https://github.com/neovim/neovim/issues/15261

This isn't a problem in lspconfig. You can use the 0.5 neovim release instead of nightly until this is fixed.
