### ISSUE TITLE
error on configuring keybindings

### ISSUE THREAD

**Issue by barkanido** [neovim/nvim-lspconfig#1157]
- `nvim --version`:
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/ido-barkan/code/neovim/build/config -I/home/ido-barkan/code/neovim/src -I/home/ido-barkan/code/neovim/.deps/usr/include -I/usr/include -I/home/ido-barkan/code/neovim/build/src/nvim/auto -I/home/ido-barkan/code/neovim/build/include
Compiled by ido-barkan@ido-barkan-ubuntu

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
- nvim-lspconfig version(commit hash):
62902d21fae90f2b008913074246debec850f2ae
- What language server (If the problem is related to a specific language server):
nothing specific I suspect
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
yes
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
yes
- Is the problem isolated to a particular language server:
no
- Operating system/version:
Linux ubuntu 20.04 kernel 5.4.0-81-generic
### Actual behavior
the lua script given in the example designed to enable key bindings after server is attached is broken?

```lua
require'lspconfig'.rust_analyzer.setup{}
require'lspconfig'.clojure_lsp.setup{}
require'lspconfig'.gopls.setup{}
require'lspconfig'.pyright.setup{}

local nvim_lsp = require('lspconfig')

-- Use an on_attach function to only map the following keys
-- after the language server attaches to the current buffer
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  --Enable completion triggered by <c-x><c-o>
  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }

  -- See `:help vim.lsp.*` for documentation on any of the below functions
  buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  -- buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  -- buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  -- buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<leader>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<leader>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  -- buf_set_keymap('n', '<space>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
  buf_set_keymap('n', '<leader>u', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  -- buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  -- buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  buf_set_keymap('n', '<leader>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)

end

-- Use a loop to conveniently call 'setup' on multiple servers and
-- map buffer local keybindings when the language server attaches
local servers = { 'pyright', 'rust_analyzer', 'go', 'java', 'clojure' }
require 'pl.pretty'.dump(nvim_lsp) -- <--debug print
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup { -- <-- this is the part that breaks
    on_attach = on_attach,
    flags = {
      debounce_text_changes = 150,
    }
  }
end
```
the error:
`E5108: Error executing lua [string ":lua"]:46: attempt to index a nil value`
the debug print: shows no such keys as 'pyright' or 'rust_analyzer` etc.
the language servers above work btw, but not the key bindings
### Expected behavior
no errors

### Minimal init.vim or init.lua and code sample
see above
### Health check
```

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: clojure_lsp: configuration checked.
  - INFO: gopls: configuration checked.
```

### LSP log
https://paste.ubuntu.com/p/pj4PR66Wr6/

**Comment by lithammer** [comment]
Why are you calling `.setup()` twice? Once at the top, then again at the bottom? Just remove the top ones.

**Comment by barkanido** [comment]
oh right! thanks a lot
