### ISSUE TITLE
Clangd c++  - iostream not found

### ISSUE THREAD

**Issue by bscuron** [neovim/nvim-lspconfig#1162]
I am just learning c++ and I am having trouble setting up the lsp.

<img width="587" alt="Screen Shot 2021-08-19 at 8 38 06 PM" src="https://user-images.githubusercontent.com/29784485/130161229-368dc43a-c2b1-4920-98eb-79836f972c88.png">

Is there a way to point the lsp to the correct location so that it can locate the iostream file?

Thank you for your help in advance!

**Comment by mjlbach** [comment]
See: https://github.com/neovim/nvim-lspconfig/issues/1120

You need to generate a compile_commands.json as described in config.md

**Comment by nepta1998** [comment]
I add this: export CPLUS_INCLUDE_PATH=/usr/include/c++/11:/usr/include/x86_64-linux-gnu/c++/11
and works on Linux
https://stackoverflow.com/questions/54521402/locating-iostream-in-clang-fatal-error-iostream-file-not-found

**Comment by holasoymas** [comment]
@mjlbach what should i write on that file and where to put that file , I am also experiencing that issue , I use Linux mint 21.2

**Comment by mjlbach** [comment]
I don't use neovim anymore.

Add to your cmakelists.txt, see: https://stackoverflow.com/a/45781334

**Comment by tianyibigdata** [comment]
@bscuron Without generating compile.json file, you can install  sudo apt install libstdc++-12-dev assuming you are on ubuntu, to solve this problem.

**Comment by Adarsh-Roy** [comment]
> [@bscuron](https://github.com/bscuron) Without generating compile.json file, you can install sudo apt install libstdc++-12-dev assuming you are on ubuntu, to solve this problem.

is there any alternative of this on windwos ? I am facing the same issue but on windows.

**Comment by captainspeedy68** [comment]
facing the same problem with macos on neovim
