### ISSUE TITLE
Can't get rust-analyzer working

### ISSUE THREAD

**Issue by jsatk** [neovim/nvim-lspconfig#1164]
- `nvim --version`: NVIM v0.5.0
- nvim-lspconfig version(commit hash):
- What language server (If the problem is related to a specific language server): rust-analyzer
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): No
- Is the problem isolated to a particular language server: rust-analyzer
- Operating system/version: macOS 11.5.2

### How to reproduce the problem from neovim startup

1. Put `require'lspconfig'.rust_analyzer.setup{}` in your `init.lua`.
2. Follow instructions here https://rust-analyzer.github.io/manual.html#rust-analyzer-language-server-binary
3. Open any rust project in `nvim`.
4. You'll see the error `cmd ["rust-analyzer"] is not executable.` upon opening your first rust file.
5. Try running `chmod a+x /PATH/TO/rust-analyzer`
6. Re-open any rust project in `nvim`
7. Open a rust file and see the error:
```
Error detected while processing FileType Autocommands for "rust":
E5108: Error executing lua ...llar/neovim/0.5.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:384: start `rust-analyzer` faile
d: Unknown system error -86: Unknown system error -86
```

### Actual behaviour

I see an error.

### Expected behaviour

The rust lsp doesn't throw an error and works :)

### Minimal init.vim or init.lua and code sample

Simply install nvim-lspconfig and put `require'lspconfig'.rust_analyzer.setup{}` in your `~/.config/nvim/init.lua`.

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: dockerls: configuration checked.
  - ERROR: gopls: The given command "gopls" is not executable.
  - INFO: graphql: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: bashls: configuration checked.
</details>

### LSP log

It is unfortunately empty even with debug turned on.

**Comment by mjlbach** [comment]
Usage questions should be posted on our [discourse](https://neovim.discourse.group/c/7-category/7).

I cannot reproduce your issue in a container, so it must be something with your system configuration/setup. Here is a container you can diff against your system/neovim configuration.

https://github.com/mjlbach/lsp-containers/tree/master/rust-analyzer

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/cant-get-rust-analyzer-with-lsp-config/1028/1

**Comment by jsatk** [comment]
I figured it out. I'd installed the wrong Apple version. I grabbed the M1 and not the Intel. 🤦‍♂️
