### ISSUE TITLE
Pyright: `attempt to call field 'find_git_ancestory ' (a nil value)`

### ISSUE THREAD

**Issue by wizard-28** [neovim/nvim-lspconfig#1179]
- `nvim --version`: `NVIM v0.6.0-dev`
- nvim-lspconfig version(commit hash): `38eb8ea`
- What language server (If the problem is related to a specific language server): `pyright`
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): I am using `pyright`
- Is the problem isolated to a particular language server: Yes
- Operating system/version: Pop!_OS 20.04 (Ubuntu based)

### How to reproduce the problem from neovim startup

1. Open any `.py` file

### Actual behaviour

Prints this error:
```
Error detected while processing FileType Autocommands for "python"
:
E5108: Error executing lua ...pack/packer/opt/nvim-lspconfig/lua/l
spconfig/pyright.lua:31: attempt to call field 'find_git_ancestory
' (a nil value)
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/
lua/packer/load.lua:78: Vim(lua):E5108: Error executing lua ...pac
k/packer/opt/nvim-lspconfig/lua/lspconfig/pyright.lua:31: attempt
to call field 'find_git_ancestory' (a nil value)
Please check your config for correctness
```

### Minimal init.vim or init.lua and code sample
`minimal_init.lua`:
```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'pyright'
  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

Code sample:
```py
import os
```

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: python: configuration checked.
  - INFO: lua: configuration checked.

</details>

### LSP log

<details>
<summary>Log file</summary>
[ START ] 2021-08-24T20:50:23+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:50:36+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:54:28+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:54:39+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:54:57+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:57:17+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:57:20+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:57:27+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:57:31+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:00:05+0530 ] LSP logging initiated
[ START ] 2021-08-24T20:58:48+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:01:16+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:01:54+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:03:27+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:03:33+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:04:59+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:05:14+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:05:37+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:03:21+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:14:51+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:22:44+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:13:35+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:12:17+0530 ] LSP logging initiated
[ START ] 2021-08-24T21:24:20+0530 ] LSP logging initiated
[ INFO ] 2021-08-24T21:24:23+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:1216 ]	  "exit_handler"	{}
</details>

PS: I've reset my system and installed this using [`:LspInstall`](https://github.com/kabouzeid/nvim-lspinstall) for the second time today, the language server worked for the first time, but now it's not working anymore.

**Comment by mjlbach** [comment]
Sorry about that, it's fixed. https://github.com/neovim/nvim-lspconfig/pull/1180/files

**Comment by wizard-28** [comment]
Thanks for the quick fix!
