### ISSUE TITLE
change default keybind for `vim.lsp.buf.implementation()`

### ISSUE THREAD

**Issue by chebro** [neovim/nvim-lspconfig#1181]
## description:
`gi` is configured by default to take the cursor back to the most recent insert position, but the default binding for `implementation()` method conflicts with this.

## from the readme:
```
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
```

**Comment by mjlbach** [comment]
There are no default keybindings, this is just a recommendation. Do you want us to remove the recommendation from the readme or add a disclaimer that the recommended bindings overwrite some things?

**Comment by chebro** [comment]
> There are no default keybindings, this is just a recommendation.

true! however, imo it is better to not recommend a remap that overwrites a default vim binding.

> Do you want us to remove the recommendation from the readme or add a disclaimer that the recommended bindings overwrite some things?

yes! replacing it would be the best, but a disclaimer would work too :)

**Comment by justinmk** [comment]
the docs need to assume some level of knowledge on the reader's part. mentioning stuff like this everywhere is too verbose.

**Comment by G-Rowell** [comment]
I hope it's okay for me to comment here,
@justinmk @chebro 

I do think there is a really valid point to not overriding existing bindings, if there is no notice then the user would have to memorize every single binding to know which conflicts and doesn't right?

I do agree the docs need to assume a level of knowledge, but surely not to the point of knowing every single existing binding?


Either way, I greatly appreciate the work you've all done. It's amazing stuff!
