### ISSUE TITLE
Pyright server slow with the new updates

### ISSUE THREAD

**Issue by Trid-collab** [neovim/nvim-lspconfig#1182]
I am using Neovim latest nightly with latest updates from lspconfig, compe and luasnip.

Have noticed that the pyright lsp autocompletion documentation on  with persistent option =always in compe has become very sluggish after the last couple of updates.  I don't face this issue with lua or vim or tservers.

Also an old issue which was resolved earlier with pyright lsp - that is it started even if it did not have a .git or requirement.txt/pyproject.toml file in the root dir. Now I notice it gone back to the state where it requires those files in the root dir - this was resolved earlier and I could use pyright lsp even without those files in the root for my scratch projects. 

Is there something I need to do

**Comment by mjlbach** [comment]
What is the newest update? Have you bisected lspconfig, compe, luasnip, and core to figure out which commit caused the performance regression?

From our side, we have changed nothing that should affect lspconfig or neovim core with respect to performance. I would try with nvim-cmp, the new completion manager. Also ensure you are editing a python project in a "real" project (not in your home directory for instance, and that you're using the `debounce_text_changes` flag as suggested in our readme.

This repo does not handle anything performance related with the language servers (we just start and send settings to the language servers for you), so I'm closing the issue.
