### ISSUE TITLE
Sumneko_lua doesn't show diagnostics inside git submodule

### ISSUE THREAD

**Issue by echasnovski** [neovim/nvim-lspconfig#1192]
When using 'sumneko_lua' inside git submodule, diagnostics is not shown properly. This seems to be because root directory isn't appropriate when working inside submodule. It is because submodule doesn't always have '.git' directory in favor of '.git' file.

Both following edits fix the issue:
- Replace [sumneko_lua's `root_dir`](https://github.com/neovim/nvim-lspconfig/blob/7c5ce01c20adb707ca9f13f3a60d1d3915905bc3/lua/lspconfig/sumneko_lua.lua#L10) with `return util.root_pattern('.git')(fname) or util.path.dirname(fname)`.
- Update [`lspconfig.util.find_git_ancestor()`](https://github.com/neovim/nvim-lspconfig/blob/7c5ce01c20adb707ca9f13f3a60d1d3915905bc3/lua/lspconfig/util.lua#L304) with `if M.path.exists(M.path.join(path, '.git')) then`.

Info:
- `nvim --version`: 0.5.0
- nvim-lspconfig version(commit hash): 7c5ce01
- What language server (If the problem is related to a specific language server): sumneko_lua
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): didn't try
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): didn't try
- Is the problem isolated to a particular language server: maybe
- Operating system/version: Ubuntu 18.04.2

### How to reproduce the problem from neovim startup
First, create a git repository with pulled submodule. For example:

```bash
mkdir nvim-lspconfig_test; cd nvim-lspconfig_test
git init; git commit --allow-empty -m 'Initialize test repo'
git submodule add https://github.com/neovim/nvim-lspconfig.git nvim-lspconfig
git commit -m 'Add submodule'
```
Second, setup 'sumneko_lua' language server using 'minimal_init.lua' with the following change:
```lua
  -- Add the server that troubles you here
  local name = 'sumneko_lua'

  -- Change to your 'lua-language-server' path
  local sumneko_root = vim.fn.expand('$HOME/nvim-lspconfig_test/lua-language-server')
  local sumneko_binary = sumneko_root .. '/bin/Linux/lua-language-server'
  local cmd = {sumneko_binary, '-E', sumneko_root .. '/main.lua'}
```
Third, try to edit two files using `nvim -u minimal_init.lua`: 'minimal_init.lua' itself and 'nvim-lspconfig/lua/lspconfig.lua'.

### Actual behaviour
When editing 'minimal_init.lua' (which is placed inside "true" git repo), diagnostics is automatically shown.
When editing 'nvim-lspconfig/lua/lspconfig.lua' (which is placed inside submodule), diagnostics is not shown.

### Expected behaviour
Diagnostics should be automatically shown both times.

### Minimal init.vim or init.lua and code sample
<details><summary>Minimal 'init.lua'</summary>

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]

local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = install_path .. '/plugin/packer_compiled.lua',
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'sumneko_lua'

  local sumneko_root = vim.fn.expand('$HOME/nvim-lspconfig_test/lua-language-server')
  local sumneko_binary = sumneko_root .. '/bin/Linux/lua-language-server'
  local cmd = {sumneko_binary, '-E', sumneko_root .. '/main.lua'}

  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

</details>

### Health check
<details>
<summary>Checkhealth result</summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: sumneko_lua: configuration checked.
```

</details>

**Comment by mjlbach** [comment]
Yes, they will be stable.

**Comment by echasnovski** [comment]
Great to hear!

For other people who might experience problems with diagnostics not showing in some files but showing in others. This might be due to some files situated in git submodules and by default `nvim-lspconfig` will not recognize submodule as root. To change this, make your LSP setup respect submodules root by adding this first-level `root_dir` option to your language's `setup()` call:
```lua
root_dir = function(fname)
  return require('lspconfig').util.root_pattern('.git')(fname) or
    require('lspconfig').util.path.dirname(fname)
end
```

**Comment by nyngwang** [comment]
Sorry for mentioning this. I did try the solution, but since this is an upstream issue, it doesn't help.
