### ISSUE TITLE
Lsp not working even with proper config in CONFIG.md

### ISSUE THREAD

**Issue by pynvimdev** [neovim/nvim-lspconfig#1196]
- `nvim --version`:0.6
- This is my init.vim
 

```vim
set cursorline
set completeopt=menu,menuone,noinsert
set nu
set termguicolors
set autoindent
map ; :
map <tab> <C-w><C-w>
set laststatus=2
call plug#begin('~/.config/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'folke/lsp-colors.nvim'
Plug 'glepnir/lspsaga.nvim'
Plug 'nvim-lua/diagnostic-nvim'
Plug 'mbbill/undotree'
Plug 'frazrepo/vim-rainbow'
Plug 'kien/ctrlp.vim'
Plug 'nvim-lua/plenary.nvim'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}  " We recommend updating the parsers on update
Plug 'nvim-treesitter/playground'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
colorscheme neosolorised
source ~/.config/nvim/lsp.rc.vim
colorscheme neosolorised
```
- This is my lsp.rc.vim
```vim
colorscheme neosolorised
lua << EOF
require'lspconfig'.pyright.setup{}
EOF
colorscheme neosolorised

```
- Details
I couldnt get LSP to work even after installing it, following steps in CONFIG.md and also checking wether LSP was working with 

This happened first in my windows machine followed by my WSL machine. 
I have tried 
```vim
:LspStop 
:LspInfo
:LspStop pyright 
:LspStart
:LspResatrt
``` 
None of them could get LSP to  work. I have also tried uninstalling and reinstalling the plugins. Here are some screen shots. Please help! I really want to continue to use LSP with Neovim for autocomplete. But now I am forced to use COC.nvim. Please help. You effort would be appreciated
- Screenshots
![problem](https://user-images.githubusercontent.com/86599386/131150788-98444786-4cf1-4628-ba48-2607dd013e39.png)
![details](https://user-images.githubusercontent.com/86599386/131151080-76dd540c-f36b-45e0-af86-e3f381ff14d0.png)

**Comment by Sreehariqwerty** [comment]
I expected completion and error messasges

**Comment by WangggggggZC** [comment]
me too!

**Comment by mjlbach** [comment]
Don't necro old issues with support questions. You can ask on discourse. We provide a [minimal config](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua) and [dockerfiles](https://github.com/nvim-lsp/try.nvim).
