### ISSUE TITLE
LSP not providing completions or error messages

### ISSUE THREAD

**Issue by Sreehariqwerty** [neovim/nvim-lspconfig#1198]
- `nvim --version`:0.6(dev build)
- What language server (If the problem is related to a specific language server): pyright
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):No(pyls worked)
- Is the problem isolated to a particular language server:Yes
- Operating system/version: WSL(windows) also same error in windows  

### Actual behaviour
No autompletion or error messages
### Expected behaviour
To provide autocompletion and error messages
### Minimal init.vim or init.lua and code sample
```vim
set cursorline
set completeopt=menu,menuone,noinsert
set nu
set termguicolors
set autoindent
map ; :
map <tab> <C-w><C-w>
set laststatus=2
call plug#begin('~/.config/nvim/plugged')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'folke/lsp-colors.nvim'
Plug 'glepnir/lspsaga.nvim'
Plug 'nvim-lua/diagnostic-nvim'
Plug 'mbbill/undotree'
Plug 'frazrepo/vim-rainbow'
Plug 'kien/ctrlp.vim'
Plug 'nvim-lua/plenary.nvim'
Plug 'kyazdani42/nvim-web-devicons'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}  " We recommend updating the parsers on update
Plug 'nvim-treesitter/playground'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'nvim-telescope/telescope.nvim'
call plug#end()
colorscheme neosolorised
source ~/.config/nvim/lsp.rc.vim
colorscheme neosolorised

- `nvim --version`:0.6
- This is my init.vim
 


```
- This is my lsp.rc.vim
```vim
colorscheme neosolorised
lua << EOF
require'lspconfig'.pyright.setup{}
EOF
colorscheme neosolorised

```
- Details
I couldnt get LSP to work even after installing it, following steps in CONFIG.md and also checking wether LSP was working with 

This happened first in my windows machine followed by my WSL machine. 
I have tried 
```vim
:LspStop 
:LspInfo
:LspStop pyright 
:LspStart
:LspResatrt
``` 
None of them could get LSP to  work. I have also tried uninstalling and reinstalling the plugins. Here are some screen shots. Please help! I really want to continue to use LSP with Neovim for autocomplete. But now I am forced to use COC.nvim. Please help. You effort would be appreciated
- Screenshots
![problem](https://user-images.githubusercontent.com/86599386/131150788-98444786-4cf1-4628-ba48-2607dd013e39.png)
![details](https://user-images.githubusercontent.com/86599386/131151080-76dd540c-f36b-45e0-af86-e3f381ff14d0.png)

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyright: configuration checked.

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion sources are valid

## snippet source
  - ERROR: Your snippet source is not available! Possible values are: UltiSnips, Neosnippet, vim-vsnip, snippets.nvim

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `tree-sitter` found  0.20.0 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v12.22.5 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - c              ✓ ✓ ✓ ✓ ✓ 
  - css            ✓ . ✓ ✓ ✓ 
  - python         ✓ ✓ ✓ ✓ ✓ 
  - go             ✓ ✓ ✓ ✓ ✓ 
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - vim            ✓ ✓ . . ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          python not found in search path or not executable.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.9.2
  - INFO: pynvim version: 0.4.2 (outdated; from /usr/lib/python3/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.3

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v12.22.5
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for go: ABI version [13](url)
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for vim: ABI version 13

</details>

# pyls
I was able to get error messages and autocomplete while using pyls.So I think the problem is with pyright
- Screen shot of pyls working
![Screenshot 2021-08-28 115500](https://user-images.githubusercontent.com/86599386/131208614-e0e7c844-79c8-4a74-9fb6-b9c8befbf793.png)

**Comment by mjlbach** [comment]
Hi, that isn't our recommended minimal init.lua. I would recommend starting with that, and asking on discourse (as the issue tracker is for issues. For something more batteries included, you can try [defaults.nvim](https://github.com/mjlbach/defaults.nvim/) which has autocompletion and snippets set up for you.

**Comment by Sreehariqwerty** [comment]
Thank you. I will try the defaults.nvim
