### ISSUE TITLE
html root dir 

### ISSUE THREAD

**Issue by pedro757** [neovim/nvim-lspconfig#1199]
I'm making a pull request to solve this issue but I want to know what you think about this,

I don't think this should be the default root directory, why html language server config searches for home directory?

https://github.com/neovim/nvim-lspconfig/blob/7c5ce01c20adb707ca9f13f3a60d1d3915905bc3/lua/lspconfig/html.lua#L13-L15

I think that should be something like this:

```lua
root_dir = function(fname)
  return root_pattern('.git/', 'package.json') or vim.loop.cwd()
end,
```

Do you agree with this?

**Comment by mjlbach** [comment]
I think it should be even stricter, I dont' think we should have vim.loop.os_homedir() or vim.loop.cwd()

**Comment by pedro757** [comment]
Do you mean something like **buffer directory**, like the `sumneko_lua` config?
```lua
local util =  require 'lspconfig/util'

root_dir = function(fname)
  return root_pattern('.git/', 'package.json') or util.path.dirname(fname)
end,
```

**Comment by mjlbach** [comment]
You can try https://github.com/neovim/nvim-lspconfig/pull/1200

**Comment by pedro757** [comment]
That works! Thank you

**Comment by oblitum** [comment]
@pedro757 fyi, it should be neither of this when there isn't an workspace configured. See https://github.com/neovim/neovim/pull/15430#issuecomment-906179810.
