### ISSUE TITLE
Please clarify this: "Create a project, this project must contain a file matching the root directory trigger"

### ISSUE THREAD

**Issue by leet0rz** [neovim/nvim-lspconfig#1208]
Title. What are you referring to? Where am I suppose to cd into to type the following commands?:
```
mkdir test_python_project
cd test_python_project
git init
touch main.py
```
Can I do this anywhere on my computer?

**Comment by mjlbach** [comment]
You can type those command anywhere on your computer, it's just creating an example "project" to get you started quickly.
