### ISSUE TITLE
Can I have an option to give different rootUri argument to language server when I open a directory?

### ISSUE THREAD

**Issue by comiluv** [neovim/nvim-lspconfig#1219]
I'm using sumneko-lua to edit lua files.
If I open a file ```nvim (filename)``` like this, the language server gets the current working directory as the rootUri.
But if I open a directory like this ```nvim .``` (to open current working directory) and use Netrw to browse to that file, the language server gets the parent directory of current working directory as rootUri.
I want to give the language server the current working directory as rootUri even if I opened neovim with ```nvim (directory name)``` command.
Is this possible?

**Comment by mjlbach** [comment]
You should can root_dir in your setup{} call. Sumneko always defaults to `.git` or parent directory of the file for the root pattern.

https://github.com/neovim/nvim-lspconfig/blob/2f026f2177bff7c9599d8dc561a4bdb30626ad9c/lua/lspconfig/sumneko_lua.lua#L9-L11
