### ISSUE TITLE
multiple filetype fails

### ISSUE THREAD

**Issue by Luis-omega** [neovim/nvim-lspconfig#1220]
- `nvim --version`:
    NVIM v0.5.0
    Build type: Release
    LuaJIT 2.0.5
- nvim-lspconfig version(commit hash):
    2f026f2177bff7c9599d8dc561a4bdb30626ad9c
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): lhs and texlab
- Is the problem isolated to a particular language server: no
- Operating system/version: archlinux

### How to reproduce the problem from neovim startup
:LspStop
:setfiletype text.lhaskell
:LspStart

### Actual behaviour
No lsp started.
UI remarks both fileytpes as detected
```
 Language client log: /home/omega16/.cache/nvim/lsp.log
 Detected filetype:   tex.lhaskell
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: texlab, hls

```

### Expected behaviour
Run at least one of lhs or texlab

### Minimal init.vim or init.lua and code sample
```
require'lspconfig'.texlab.setup{
  settings = {
    texlab = {
      auxDirectory = ".",
      bibtexFormatter = "texlab",
      build = {
        args = { "-pdf", "-interaction=nonstopmode", "-synctex=1", "%f" },
        executable = "lualatex",
        forwardSearchAfter = false,
        onSave = false
      },
      chktex = {
        onEdit = false,
        onOpenAndSave = false
      },
      diagnosticsDelay = 300,
      formatterLineLength = 80,
      forwardSearch = {
        args = {}
      },
      latexFormatter = "latexindent",
      latexindent = {
        modifyLineBreaks = false
      }
    }
  }
}




require'lspconfig'.hls.setup{default_config = {
    cmd = { 'haskell-language-server-wrapper', '--lsp' },
    filetypes = { 'haskell', 'lhaskell'},
    root_dir = require('lspconfig/util').root_pattern('*.cabal', 'stack.yaml', 'cabal.project', 'package.yaml', 'hie.yaml')
  }
}
```

### Health check
<details>
<summary></summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: texlab: configuration checked.
  - INFO: hls: configuration checked.
```
</details>

I'm attempting to write pandoc markdown, latex and lhaskell in the same file. 
Both texlab and lhs work if I set the filetype to tex or lhaskell.

As a side note: Thanks to all of you, having an easy way to config all my lsp in neovim is pretty nice!

**Comment by mjlbach** [comment]
If you want both language servers, modify the filetypes of the language servers in setup{} to operate on both filetypes

**Comment by Luis-omega** [comment]
I append 
`tex.lhaskell, lhaskell.tex`

 if I open "some.latex" and set 
`:setfiletype tex.lhaskell`

it just starts texlab 
```

 Language client log: /home/anon/.cache/nvim/lsp.log
 Detected filetype:   tex.lhaskell
 
 0 client(s) attached to this buffer: 
 
 Configured servers list: texlab, hls
```


Same if i run
`:setfiletype lhaskell.tex`

Now if i just run 
`:setfiletype lhaskell`

both of them start
```
 Language client log: /home/anon/.cache/nvim/lsp.log
 Detected filetype:   lhaskell
 
 2 client(s) attached to this buffer: 
 
 Client: texlab (id: 1, pid: 18765, bufnr: [1, 1])
 	filetypes:       tex, tex.lhaskell, lhaskell.text
 	autostart:       true
 	root directory:  /home/anon/projects/anon
 	cmd:             texlab
 
 Client: hls (id: 2, pid: 18859, bufnr: [1])
 	filetypes:       haskell, lhaskell
 	autostart:       true
 	root directory:  /home/anon/projects/anon
 	cmd:             haskell-language-server-wrapper --lsp
 	version:   haskell-language-server version: 1.3.0.0 (GHC: 8.10.4) (PATH: /home/anon/.ghcup/bin/haskell-language-server-wrapper-1.3.0) (GIT hash: e7c5e90b6df5dff2760d76169eddaea3bdd6a831)
 
 Configured servers list: texlab, hls
```

**Comment by Luis-omega** [comment]
To be clear, in the lat response i added `tex.lhaskell, lhaskell.tex` to both configs.

`  filetypes = {'tex','tex.lhaskell', 'lhaskell.tex'},`

`    filetypes = { 'haskell', 'lhaskell', 'tex.lhaskell', 'lhaskell.tex' },`

**Comment by liskin** [comment]
@mjlbach Are you sure nvim-lspconfig shouldn't split the filetype automatically? Both https://github.com/nvimtools/none-ls.nvim and https://github.com/dense-analysis/ale do this, (n)vim does this for syntax, ftplugins, etc. as well, it's just nvim-lspconfig that for some reason can't handle this…
