### ISSUE TITLE
No diagnostics for html/css

### ISSUE THREAD

**Issue by bragjo** [neovim/nvim-lspconfig#1226]
Hi,

This is probably not a bug but Im wondering If there is possibility to get diagnostics working? If so how? Do I need something extra? I got the hmtl and CSS lsp working aswell as js/ts, but only js/ts provide diagnostics when errors occur, not html/CSS.

Am I doing something wrong? Cheers.

**Comment by mjlbach** [comment]
As far as I can tell, diagnostics aren't supported by the servers (diagnostic messages are all blank in the logs, no implementation details in the upstream repository, vscode)

You can try:

https://github.com/bmatcuk/stylelint-lsp (which is supported in lspconfig)
https://github.com/jose-elias-alvarez/null-ls.nvim/issues/153 (this issue might be of use to you, using an adapter server to bridge a cli linter)
