### ISSUE TITLE
LspRestart creates duplicate rust-analyzer

### ISSUE THREAD

**Issue by theduke** [neovim/nvim-lspconfig#1229]
- `nvim --version`: `NVIM v0.5.0`
- nvim-lspconfig version(commit hash): `71c241425fd7a84f0ae33ea1eb7c071f20499bcd`
- What language server (If the problem is related to a specific language server): rust-analyzer
- Is the problem isolated to a particular language server: can't say
- Operating system/version: Linux (NixOS)

### How to reproduce the problem from neovim startup

Open a Rust file. Use `:LspRestart`.

**Note:** I can't reproduce this reliably. It seems to only happen sometimes, but on a regular basis.

### Actual behaviour

A second `rust-analyzer` client is started. (as confirmed by `:LspInfo`)

Neither of the two clients is attached to the current buffer!

Workaround/fix is to do `:LspStop` and `:LspStart`.

### Expected behaviour

The old client stops, a new client is started.

**Comment by mjlbach** [comment]
Should be closed by #1234, my mistake :)

**Comment by theduke** [comment]
Thanks for the fix.
