### ISSUE TITLE
Show source in line diagnostics

### ISSUE THREAD

**Issue by JA-Bar** [neovim/nvim-lspconfig#1232]
I noticed that in the Wiki page for "UI customization" -> "Show source in diagnostics" it's now recommended to not alter the original diagnostics, but to modify the deepcopy instead. This correctly shows the formatted diagnostics in virtualtext.
![image](https://user-images.githubusercontent.com/57547764/132294270-6d671492-c54c-427c-8686-91fef27ee2c3.png)

But not when calling `vim.lsp.diagnostic.show_line_diagnostics()`
![image](https://user-images.githubusercontent.com/57547764/132294341-9e4a1c09-a643-4df4-9882-34e1dd5954d7.png)

Is there a way to achieve this behavior?

**Comment by mjlbach** [comment]
Please don't delete the issue template. This sounds like a usage questions so I'll direct you to ask our on [discourse](https://neovim.discourse.group/c/7-category/7).

**Comment by JA-Bar** [comment]
Apologies, the template seemed specifically for bug reports, and as you mentioned, this is more of a usage question. Thanks for the reference.
