### ISSUE TITLE
ClangdSwitchSourceHeader causes lua error on Nvim 0.6.x due to signature change of vim.lsp.buf_request

### ISSUE THREAD

**Issue by Oddegamra** [neovim/nvim-lspconfig#1239]
- `nvim --version`: NVIM v0.6.0-dev+227-gc1f573fbc
- nvim-lspconfig version(commit hash): 01153c5
- What language server (If the problem is related to a specific language server): clangd
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): -
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): -
- Is the problem isolated to a particular language server: vim.lsp.buf_request also appears in rust_analyzer and texlab, so I imagine the same problem exists there.
- Operating system/version: Linux

### How to reproduce the problem from neovim startup
- Go to a directory containing a C++ project with two files, test.h and test.cpp
- Open test.h
- When the language server has successfully attached, run `:ClangdSwitchSourceHeader`

### Actual behaviour
The error `Error executing vim.schedule lua callback: .../tools/neovim/install/share/nvim/runtime/lua/vim/uri.lua:96: attempt to call method 'match' (a nil value)` is raised

### Expected behaviour
The file test.cpp is opened for editing.

### Minimal init.vim or init.lua and code sample
```
require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use {
    'neovim/nvim-lspconfig',
    config = function()
      local lspconfig = require('lspconfig')
      lspconfig.clangd.setup({
        cmd = { 'clangd', '--background-index'},
      })
  }
end)
```

### Health check
<details>
<summary>Checkhealth result</summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
```
</details>

### LSP log
I'll skip this.

## Diagnosis
Apparently, the signature of `vim.lsp.buf_request` has changed from the 0.5.x release to the current 0.6.x nightly build. In particular, the function handler signature is now `function(err, result, ctx, config)` (see `:help lsp-handler`), while it was `function(err, method, result, client_id, bufnr, config)` in 0.5.x.

As a result, the function `switch_source_header` in `clangd.lua` passes the `ctx` param to `vim.uri_to_fname` instead of the intended `result` param, which leads to aforementioned error.

**Comment by matu3ba** [comment]
The linked bisect shows which commit in neovim broke it.
