### ISSUE TITLE
lsp is taking more than 30 seconds to display intellisense

### ISSUE THREAD

**Issue by webmandman** [neovim/nvim-lspconfig#1244]
How do I debug nvim and lspconfig to figure out whats causing this very slow tsserver lsp startup?

**Comment by mjlbach** [comment]
typescript-language-server is extremely slow, we don't use the same server as coc/vscode do, we have to use a wrapper which implements the protocol on top of this server (https://github.com/typescript-language-server/typescript-language-server)

**Comment by bnchi** [comment]
> typescript-language-server is extremely slow, we don't use the same server as coc/vscode do, we have to use a wrapper which implements the protocol on top of this server (https://github.com/typescript-language-server/typescript-language-server)

The server is super slow on my codebase, and i don't want to use coc. 

I would love to contribute if you don't have the time to fix the issue.
