### ISSUE TITLE
How to override default mapping in lspinfo?

### ISSUE THREAD

**Issue by uga-rosa** [neovim/nvim-lspconfig#1252]
https://github.com/neovim/nvim-lspconfig/blob/1344a859864d4e6d23d3f3adf56d49e6386ec0d2/lua/lspconfig/ui/lspinfo.lua#L201

I have mapped `nnoremap <esc><esc> <cmd>noh<cr>`, so I would like to add `<nowait>` to above mapping. `au FileType lspinfo` seems to be too fast, cannot be overwritten.

**Comment by clason** [comment]
This is not a bug report but a usage question; these are off-topic here and should be asked on https://neovim.discourse.group.
