### ISSUE TITLE
typescript-language-server: LSP snippet completions aren't working after upgrading to 4.4.3

### ISSUE THREAD

**Issue by sphaugh** [neovim/nvim-lspconfig#1259]
### Description

According to the following:

https://github.com/microsoft/TypeScript/pull/43149
https://github.com/microsoft/vscode/issues/48562

`tsserver` should support snippet completion items. The initialization options for `typescript-language-server` includes
```typescript
interface UserPreferences {
    /**
     * Enables auto-import-style completions on partially-typed import statements. E.g., allows
     * `import write|` to be completed to `import { writeFile } from "fs"`.
     */
    includeCompletionsForImportStatements: boolean;
    /**
     * Allows completions to be formatted with snippet text, indicated by `CompletionItem["isSnippet"]`.
     */
    includeCompletionsWithSnippetText: boolean;
}
```
but setting
```lua
local lsp = require('lspconfig')

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

lsp.tsserver.setup {
  capabilities = capabilities,
  on_attach = on_attach,
  init_options = {
    preferences = {
      includeCompletionsWithSnippetText = true,
      includeCompletionsForImportStatements = true,
    },
  },
}
```
doesn't seem to do anything.

### Neovim version

NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

974d15fa2809dff691d6a50a6759bf2c8bf39b4a

### Operating system and version

Debian GNU/Linux 11 (bullseye)

### Affected language servers

tsserver

### Steps to reproduce

1. Download `init.lua` here: https://gist.github.com/8512ea367796cef5c1569411bd4a467f
2. Run `:PackerInstall`
3. Try completing a function name as in https://github.com/microsoft/TypeScript/issues/25207

### Actual behavior

Only the name of the function is completed.

### Expected behavior

The function is expanded with placeholders for its arguments.

### Minimal config

```Lua
https://gist.github.com/8512ea367796cef5c1569411bd4a467f
```

### Health check

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: clangd: configuration checked.
```

### LSP log

n/a

**Comment by mjlbach** [comment]
This is a bug that should be filed against nvim-cmp, as it's what is setting the overridden capabilities that we send to the server.
