### ISSUE TITLE
lsp can't find Volar

### ISSUE THREAD

**Issue by DvrDania** [neovim/nvim-lspconfig#1261]
### Description

I installed Volar globally but lsp can't find it

### Neovim version

NVIM v0.5.0
Build type: Release
LuaJIT 2.0.5

### Operating system and version

Arch linux , kernel v5.14

### Affected language servers

Volar

### Steps to reproduce

install @volar/server globally `npm install -g @volar/server`
require lua/config.lua file in init.vim
create a local variable and require lspconfig
`local lsp = require'lspconfig'`
enable language server `lsp.volar.setup{}

### Actual behavior

returns an error that says volar is a nil value

### Minimal config

```Lua
require'lspconfig'.volar.setup{}
```

### Health check

health#lspconfig#check
  2 =================================================================    =======
  3 ## Checking language server protocol configuration
  4   - INFO: tsserver: configuration checked.
  5   - INFO: html: configuration checked.

note: all lang server protocols before volar are working

### LSP log

https://gist.github.com/DvrDania/346ec5fcbe5a1cf55f2420a72d1f7fb5

**Comment by 3nuc** [comment]
1. The binary name for volar changed recently from `vue-server` to `volar-server`. Are you sure your @volar/server version is at least 0.27.14? You can check with `npm list -g @volar/server` If not, please run `npm i -g @volar/server` again.
2. Are you sure that you have typescript available in your project? I'm talking within the local node_modules of the folder. A global typescript installation doesn't matter here. As you can see, the default configuration looks for typescript **in the local node_modules of your project that you opened nvim in**, not in a global typescript install folder.

**Comment by DvrDania** [comment]
Okay I didn't know that it matters cuz my other lsps work without any problem, I put my lua require line after my plugin manager stuff and it works now, Thanks
