### ISSUE TITLE
Volar lsp client crashed

### ISSUE THREAD

**Issue by lukerHhy** [neovim/nvim-lspconfig#1265]
### Description

Volar lsp server attached to the buffer and then detach.

@volar/server version: 0.27.21

### Neovim version

NVIM v0.6.0-dev+296-g1f49268c4
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 10.13.6

### Affected language servers

volar

### Steps to reproduce

1. open *.vue file
2. wait a few seconds
3. volar client detached

### Actual behavior

volar client detached

![image](https://user-images.githubusercontent.com/17514078/133869694-78483e37-be79-4168-b08b-668bdf889c7d.png)

### Minimal config

```Lua
local nvim_lsp = require('lspconfig')
local servers = {"html", "cssls", "volar", "tsserver"}

for _, lsp in ipairs(servers) do
   nvim_lsp[lsp].setup {}
end
```

### Health check

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: cssls: configuration checked.
  - INFO: volar: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: null-ls: configuration checked.
  - INFO: html: configuration checked.

### LSP log

https://gist.github.com/lukerHhy/3ebaad6216b1ce3226975079d4ed5ffb

**Comment by mjlbach** [comment]
If the server crashes, you should file an issue with the upstream issue tracker.
