### ISSUE TITLE
"Show source in diagnostics" from wiki needs updating.

### ISSUE THREAD

**Issue by dsully** [neovim/nvim-lspconfig#1267]
### Description

The "Show source in diagnostics" snippet from the [wiki](https://github.com/neovim/nvim-lspconfig/wiki/UI-customization#show-source-in-diagnostics-neovim-05106-only) no longer works with Neovim at HEAD after the change in https://github.com/neovim/neovim/pull/15585

It appears given the current state of which functions in vim.diagnostic and vim.lsp.diagnostic are public vs private that showing the LSP source isn't possible right now.

The default `on_publish_diagnostics` in `vim.lsp.diagnostic` calls `vim.diagnostic.set(namespace, bufnr, diagnostic_lsp_to_vim(diagnostics, bufnr, client_id), config)` however `diagnostic_lsp_to_vim` is marked private.

I'd love to update the wiki, but unsure how to proceed.

Thanks

### Neovim version

NVIM v0.6.0-dev+1772-g8ef2b56ca
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

all

### Affected language servers

all

### Steps to reproduce

Attempt to use the `textDocument/publishDiagnostics` handler as show on the wiki.

### Actual behavior

`Error executing vim.schedule lua callback: [string "..."]:0: attempt to call field 'display' (a nil value)`

### Minimal config

```Lua
N/A
```

### Health check

N/A

### LSP log

N/A

**Comment by mjlbach** [comment]
The wiki is community contributed, so feel free to update, but it's not an issue with lspconfig :)

**Comment by dsully** [comment]
Right - I'm not sure what it should be updated to, which is the reason I opened this issue.

**Comment by mjlbach** [comment]
For onlookers, you can follow the following PR https://github.com/neovim/neovim/pull/15717
