### ISSUE TITLE
Request LSP Documentation via a search, or split window ability alongside hover.

### ISSUE THREAD

**Issue by Shadorain** [neovim/nvim-lspconfig#1271]
### Requested feature

# Why?

So what my original feature need was for the Hover window to have configurable keybinds to scroll up or down without having to focus that hover buffer (sort of how `nvim-cmp` has this ability). (Disclaimer: this would be incredibly useful!)
But then I thought, what about having a settable keybind sort of how you can set: `buf_set_keymap('n', 'K',  '<cmd>lua vim.lsp.buf.hover()<CR>', opts)` 
that would open a split instead with the documentation that the hover window opens which you can actually go in and scroll through etc. (another useful feature to add)
My problem with a focusable hover windows is that it focuses it 90% of the time when I do not want it to even though it is only supposed to when you press the bind twice (this would be a good fix).

Then that led me to the thought that when you use the hover bind, it probably is taking in the word that the cursor is sitting on and searching for documentation somewhere then displaying it in a floating window. That means there has to be a way to have like a search command/function to search the lsp documentation `:lsplookup "Keywords"` or something like it. This would be very useful as well.

## Bullets

- Keybinds to scroll hover window (how nvim-cmp has it)
- Hover Split window (opens split with documentation)
- Fix `focusable` setting for existing hover windows
- A searcher / lookup command to search lsp documentation

**Comment by mjlbach** [comment]
Please do not file composite issues like this

* Keybinds to scroll hover window (how nvim-cmp has it)
This should be filed against core, but my gut feeling is this is a key bind you should map in your own config. We don't map any keybindings by default.

* Hover Split window (opens split with documentation)
I don't think we'll do this, we don't want to add multiple interfaces to the same utility, and you're free to override handlers to get the exact behavior you want.

* Fix focusable setting for existing hover windows
This is still unclear to me, you should file a *separate* issue on core if focusable `true` and `false` are not behaving as they should.

* A searcher / lookup command to search lsp documentation
Why should LSP be any different than any other help documentation? `:help lsp` `:help vim.buf.lsp` all work, and if you want more search ability you can install a plugin like telescope and use `:Telescope help tags`


None of these issues apply to lspconfig, you should file independent (separate) issues against neovim core.

**Comment by Shadorain** [comment]
My bad, I wasn't planning to but it was how my brain played out. It was fair to close this. 

The main feature I was requesting was the last bullet which you seemed to have misunderstood by my poor wording. 
I meant having an lspconfig function that you can lookup keywords sort of how the hover window does it. Like if you are hovering over `String` for example in rust, it will bring up the rust documentation for String. I meant a function that you can look those up without having that be a hover command. Not sure if this makes sense still, I can't think of a better way to ask this though...

**Comment by mjlbach** [comment]
I don't really follow this, lspconfig has no functions for hover, that is implemented in core. What you are asking for does not seem like something which is in the lsp specification, so I'm confused what role it serves.
