### ISSUE TITLE
attempt to index field 'arduino_language_server' (a nil value)

### ISSUE THREAD

**Issue by PaoGon** [neovim/nvim-lspconfig#1284]
### Description

I always get this error when I am sourcing the lspconfig command for the arduino language server

E5113: Error while calling lua chunk: /home/gon/.config/nvim/lua/arduino_config.lua:1: attempt to index field 'arduino_language_server' (a nil value)

### Neovim version

NVIM v0.5.0
Build type: Debug
LuaJIT 2.1.0-beta3

### Operating system and version

Ubuntu 20.04

### Affected language servers

Arduino language server

### Steps to reproduce

1. go get -u github.com/arduino/arduino-language-server
2. go build 
3. ./arduino-language-server -cli-config $HOME/.arduino15/arduino-cli.yaml (nothings happen here)
4. 

### Actual behavior

E5113: Error while calling lua chunk: /home/gon/.config/nvim/lua/arduino_config.lua:1: attempt to index field 'arduino_language_server' (a nil value)

### Minimal config

```Lua
`require'lspconfig'.arduino_language_server.setup({ 
    cmd =  { 
        -- Required
        "arduino-language-server",
        "-cli-config", "$HOME/.arduino15/arduino-cli.yaml"
    }
})
`
```

### Health check

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: html: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: cssls: configuration checked.

### LSP log

https://gist.github.com/PaoGon/a22a6c358f3763ee40f40a1c60cbf88b

**Comment by mjlbach** [comment]
I can't reproduce with the minimal config.

> E5113: Error while calling lua chunk: /home/gon/.config/nvim/lua/arduino_config.lua:1: attempt to index field 'arduino_language_server' (a nil value)

`/home/gon/.config/nvim/lua/arduino_config.lua` implies the issue is not in fact with a minimal config, as `arduino_config.lua` is on rtp. This is an issue local to your setup.
