### ISSUE TITLE
Reconfigure servers

### ISSUE THREAD

**Issue by BiserStoilov** [neovim/nvim-lspconfig#1285]
### Language server

all

### Requested feature

1. Configure server:

`
require"lspconfig".tsserver.setup {
     ...
}
`

2. I have option LspStop but 

`Detected filetype:   javascript
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: javascript
 
 Config: tsserver
 	filetypes:         javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	root directory:    /home/biserstoilov/test/js2
 	cmd:               /home/biserstoilov/.local/share/nvim/lspinstall/typescript/node_modules/.bin/typescript-language-server --stdio
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   textDocument/publishDiagnostics
 
 Configured servers list: tsserver`

3. How can I remove configured server to reconfigure for other `cwd`

Thanks in advance!

**Comment by mjlbach** [comment]
This isn't a feature request. Please follow the issue template if you're having an issue. As it stands, I don't know what "How can I remove configured server to reconfigure for other cwd" means. 

If your question is why is typescript language server not starting, you didn't include the log or confirm you're using a minimal config (which is in the issue template). Please reopen the issue following those steps.
