### ISSUE TITLE
Omnisharp language server does not terminate after closing vim and uses 100% cpu

### ISSUE THREAD

**Issue by quantum-booty** [neovim/nvim-lspconfig#1298]
### Description

![image](https://user-images.githubusercontent.com/28958399/136691377-78778f46-de5d-4d5a-83ae-4828e82b5760.png)

### Neovim version

NVIM v0.6.0-dev+445-ga36c6e5df
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

66659884c36dadd1f445f9012fcf4e7600286d3e

### Operating system and version

Arcolinux

### Affected language servers

omnisharp

### Steps to reproduce

Open a .cs file, then close it.

### Actual behavior

omnisharp server doesn't shut down

### Minimal config

```Lua
minimal init.lua

require('packer').startup({function()
	-- Packer can manage itself
	use 'wbthomason/packer.nvim'
	-- use 'lewis6991/impatient.nvim'

	-- prerequists for lua plugins
	use 'nvim-lua/plenary.nvim'
	use 'nvim-lua/popup.nvim'
	use 'kyazdani42/nvim-web-devicons'

	use { 'neovim/nvim-lspconfig', config = function()

		local nvim_lsp = require('lspconfig')
		local pid = vim.fn.getpid()
		local omnisharp_bin = "/home/henryw/omnisharp/run"
		require'lspconfig'.omnisharp.setup{
			cmd = { omnisharp_bin, "--languageserver" , "--hostPID", tostring(pid) }
		}

	end
}
end,
}
)
```

### Health check

![image](https://user-images.githubusercontent.com/28958399/136691752-f471d57e-a19a-40cd-8124-49c818e40941.png)

### LSP log

https://gist.github.com/quantum-booty/879f4a44ba15d78b6c6fbd7215377b43

**Comment by justinmk** [comment]
Report to omnisharp.
