### ISSUE TITLE
Ability to easily load default config of an LSP

### ISSUE THREAD

**Issue by strayer** [neovim/nvim-lspconfig#1302]
### Requested feature

I install JS-based LSPs in specific subdirectories, not globally, so they are not in the PATH of the nvim process. To allow nvim to find those executables I need to override the first entry of `cmd`, just like [nvim-lspinstall](https://github.com/kabouzeid/nvim-lspinstall/blob/471603f/lua/lspinstall/servers/bash.lua#L2) does. It seems pretty complicated to load and modify the default config ([see here](https://github.com/kabouzeid/nvim-lspinstall/blob/471603f786c6b2aa9f667da99fc3dfef43de3e12/lua/lspinstall/util.lua#L5-L22)).

My current workaround is to duplicate the default cmd set in my config, but this means I'll always have to check if the parameters besides the executable path may have changed when updating lspconfig.

I'd like to be able to easily require/get the LSP default config to modify the LSP cmd to have the correct path prefixed.

Note: I tried setting `cmd_env = { PATH = "...:" .. vim.env.PATH }` but as far as I can see this won't be utilized when neovim tries to find the cmd executable, only when launching the actual process later.

**Comment by strayer** [comment]
That's what I'm currently doing, but for this I need to have an actual mapping to executable name and parameters: (excuse my noobish lua 👼🏻)

```lua
local function yarn_custom_install_path(install_dir)
  return vim.env.HOME .. "/.config/nvim/lsp-servers/" .. install_dir .. "/node_modules/.bin/"
end

local function server_custom_cmd(server_name)
  if server_name == "bashls" then
    return {yarn_custom_install_path(server_name) .. "bash-language-server", "start"}
  elseif server_name == "diagnosticls" then
    return {yarn_custom_install_path(server_name) .. "diagnostic-languageserver", "--stdio"}
  elseif server_name == "dockerls" then
    return {yarn_custom_install_path(server_name) .. "docker-langserver", "--stdio"}
  elseif server_name == "pyright" then
    return {yarn_custom_install_path(server_name) .. "pyright-langserver", "--stdio"}
  elseif server_name == "tsserver" then
    return {yarn_custom_install_path(server_name) .. "typescript-language-server", "--stdio"}
  elseif server_name == "cssls" then
    return {yarn_custom_install_path("vscode-extracted") .. "vscode-css-language-server", "--stdio"}
  elseif server_name == "html" then
    return {
      yarn_custom_install_path("vscode-extracted") .. "vscode-html-language-server", "--stdio"
    }
  elseif server_name == "yamlls" then
    return {yarn_custom_install_path(server_name) .. "yaml-language-server", "--stdio"}
  elseif server_name == "vuels" then
    return {yarn_custom_install_path(server_name) .. "vls"}
  else
    return nil
  end
end

[...]

local function setup_servers()
  local tablex = require("pl.tablex")

  local servers = {
    "bashls", "diagnosticls", "dockerls", "sumneko_lua", "pyright", "tsserver", "cssls", "jsonls",
    "html", "vuels", "yamlls", "solargraph", "efm", "terraformls"
  }

  for _, server in ipairs(servers) do
    local config = make_config()
    local custom_cmd = server_custom_cmd(server)

    -- install path overrides
    if custom_cmd then
      config = tablex.merge(config, {
        cmd = custom_cmd
      }, true)
    end

    -- language specific config
    if server == "diagnosticls" then config = tablex.merge(config, diagnosticls_config, true) end
    if server == "efm" then config = tablex.merge(config, efm_config, true) end
    if server == "typescript" then
      config.on_attach = function(client)
        on_attach(client)

        -- formatting handled by prettier
        client.resolved_capabilities.document_formatting = false
      end
    end

    require"lspconfig"[server].setup(config)
  end
end
```

I'd like to get the executable name and (especially) the parameters from the default config and only prepend the command with my custom path. This would allow me to benefit from potential parameter changes in the default lspconfig.

**Comment by mjlbach** [comment]
Just to clarify, you can just call `setup{}` individually per server with the modified `cmd` as this selectively overrides the default config. All of the other entries in the table (settings, root_dir, on_new_config) etc. will follow along as neovim updates.

**Comment by polyzen** [comment]
Another option is to add them to your `PATH` using symlinks.

**Comment by mjlbach** [comment]
I'm going to close this in favor of the roadmap, which lists exposing configurations in this way (and so does #1331)
