### ISSUE TITLE
Eslint lsp pnp configuration

### ISSUE THREAD

**Issue by NICHTJ3** [neovim/nvim-lspconfig#1326]
### Language server

eslint

### Requested feature

The current settings for the eslint language server do not account for projects that use yarn2/pnp and as such the eslint lsp cannot resolve eslint in those projects.

The solutions discussed in [this issue](https://github.com/microsoft/vscode-eslint/issues/601) do not seem to work but I was able to work around it in [this PR](https://github.com/williamboman/nvim-lsp-installer/pull/163) to nvim-lsp-installer but ideally this would be handled here instead, I'm unsure if my solution in that PR will work here since we don't want to execute the lsp with an absolute path.

**Comment by mjlbach** [comment]
I don't understand the issue, this seems trivial for users to address in their own configs via an override to setup no?

**Comment by mjlbach** [comment]
Please file a PR if the documentation needs to be updated.
