### ISSUE TITLE
A way to change settings after setup

### ISSUE THREAD

**Issue by Diegovsky** [neovim/nvim-lspconfig#1340]
### Requested feature

<details>
<summary>Why I came up with this (just context, not important)</summary>
I spent an evening trying to do "Project local settings" like the wiki suggests trying to patch my workflow but it does not work properly.

My "old" neovim workflow:
1. `init.lua` calls `setup` on all the LSPs I have installed;
2. Open a project (a.k.a `cd` into it);

I needed to add custom `settings` to an LSP client, which the wiki recommended creating a vimscript file which contains a customized `setup` function for `sumneko_lua`;

I'm not sure why, but calling `setup` again (with overriden `settings`) is not working. However, I made it work by removing the code that setups all the LSPs in my `init.lua` script and then running the custom `setup` function.
</details>

Anyways, I think it would be better to do something like VSCode does (which is reloading settings when the `config.json` file changes). 

To do that with `lspconfig`, I propose a new property for the client, called `settings` that contains the current settings. Changing a field could trigger a `workspace/didChangeConfiguration` event to notify the client.

Something like this:
```lua
require'lspconfig'.sumneko_lua.setup{cmd='<...>',
  settings = { 
    Lua = {
      diagnostics = {
        globals = {'vim'}
      }
    }
  }
} 

print(require'lspconfig'.sumneko_lua.settings.Lua.diagnostics.globals[1]) -- Output: 'vim'
require'lspconfig'.sumneko_lua.settings.Lua.diagnostics.globals = {'vim', 'love'} -- The client is now aware of the change
```

If sending the event for every change is too much, just having access to the client's `settings`  is good enough and provides a lot of scriptability anyway :)

What do you think?

**Comment by mjlbach** [comment]
As mentioned, this is implemented already with the above snippet.

**Comment by Diegovsky** [comment]
Oh, sorry to leave you hanging. Yes, your suggestion worked fine for me. Also, I understand that's a technical incompatibility with how nvim's lsp work and that's ok :)

**Comment by mjlbach** [comment]
I'm not sure what the technical incompatibility is?
```
local client = vim.lsp.get_client_by_id(1)
client.notify('workspace/didChangeConfiguration', {
    settings = client.config.settings,
 })
```

I could add metatable magic so client.settings invokes the function, but I talked with @mfussenegger about it and we didn't think it was worth it given the consistency of the current interface.

**Comment by mjlbach** [comment]
> I meant sending the event to every server attached to a given filetype.

Unfortunately, settings are not standardized per server. You still need to send the appropriate settings to the appropriate server (not an lspconfig/nvim thing, just a general thing)

**Comment by Diegovsky** [comment]
Yeah, I can see this being a problem with javascript and eslint just like you said.

**Comment by Diegovsky** [comment]
> Can you give an example on when the above would be insufficient?
Nope, I actually got it working using that snippet.
