### ISSUE TITLE
Getting error `matching root directory not detected` when opening a file with netrw

### ISSUE THREAD

**Issue by mister-coded** [neovim/nvim-lspconfig#1359]
### Description

If I open a file through netrw, I get the error `Autostart for <server> failed: matching root directory not detected` while trying to start a lsp server. 

I've tried opening the file with `nvim <file>`, `:e <file>` and with [telescope.nvim file finder](https://github.com/nvim-telescope/telescope.nvim/wiki/Showcase#find-files) and this error does not occur.

I'm not sure if this might be a bug with either lspconfig or netrw though.
Note: I've only tested this with tsserver and denols.

### Neovim version

NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

dd7a616b8d778c195fe7ec9fffa32ce1b0fc9da7

### Operating system and version

Windows 10 21H1

### Affected language servers

tsserver, denols

### Steps to reproduce

1. `nvim .`
3. Select the file
4. Type command `:LspStart tsserver` or `:LspStart denols` (both show the same output)

### Actual behavior

When I try to start the server (either denols or tsserver), I get an error message saying `Autostart for <server> failed: matching root directory not detected`.

Here is a preview:

https://user-images.githubusercontent.com/67773205/139600223-e5d3baa2-dfbc-44f1-b69a-2f3396370c1d.mp4

### Expected behavior

Open the file with netrw and start the lsp server successfully.

### Minimal config

```Lua
local nvim_lsp = require('lspconfig')

-- Use a loop to conveniently call 'setup' on multiple servers and
local servers = { 'tsserver', 'denols', 'jsonls' }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    autostart = false
  }
end
```

### Health check

```
health#nvim_treesitter#check
========================================================================
## Installation
  - WARNING: `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
  - OK: `node` found v16.4.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `gcc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl" }
  - OK: Neovim was compiled with tree-sitter runtime ABI version 13 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - lua            ✓ ✓ ✓ ✓ ✓ 
  - toml           ✓ ✓ ✓ ✓ ✓ 

 Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: jsonls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: denols: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Users\pedro\AppData\Local\Programs\Python\Python39\python.EXE is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Users\pedro\AppData\Local\Programs\Python\Python39\python.EXE
  - INFO: Other python executable: C:/Users/pedro/AppData/Local/Programs/Python/Python39/python
  - INFO: Python version: 3.9.7
  - INFO: pynvim version: 0.4.3
  - WARNING: Could not contact PyPI to get latest version.
  - ERROR: HTTP request failed: error: curl error with https://pypi.python.org/pypi/pynvim/json: 35

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.4.0
  - INFO: Nvim node.js host: C:\Users\pedro\AppData\Roaming\npm\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

## Perl provider (optional)
  - WARNING: No usable perl executable found

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for toml: ABI version 13
  - OK: Loaded parser for c: ABI version 13

```

### LSP log

https://gist.github.com/mister-coded/14c751a56fd43364634cc9c95de8d553

**Comment by mjlbach** [comment]
Is this actually using the minimal config? I cannot reproduce.

**Comment by mjlbach** [comment]
I think I know the issue. We print the "autostart failed" warning when we can't detect a matching root directory for a project (if single_file_mode is not enabled). Since deno and tsserver both operate on the same filetypes, if you have both enabled on your config, then you will see the warning error that we can't start whichever server does not match the project structure determined by root directories.

There's nothing special about opening a (local) file via netrw. The lspconfig attach/start logic is governed by a filetype autocmd.

**Comment by m4h4d3v** [comment]
I have nvim-lsp setup with lspconfig and `williamboman/nvim-lsp-installer`. I am still a noob on lsp and lua and nvim, so please bear with me. But I get this same error when I installed `haskell-language-server` with `:LspInstall`. Usually any server that I've tried out so far works just out of the box but `hls` is giving me this error. Is this because I haven't configured it?

**Comment by clason** [comment]
Sorry, this is not a forum for getting help on your config; hijacking closed issues is particularly bad form. Use the Discourse or Matrix for such questions.
