### ISSUE TITLE
Serve-d fails

### ISSUE THREAD

**Issue by rempas** [neovim/nvim-lspconfig#1373]
### Description

When I open a D language file and trying to use the "serve-d" language server, I'm getting the following error message:

```
Client 1 quit with exit code 0 and signal 11
```

I use the Linux Neovim appimage v0.5.1 and I downloaded "serve-d" from the official [github](https://github.com/Pure-D/serve-d) versions section.

### Neovim version

NVIM v0.5.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

7dee6a7c07e1c99361c1e1cec51622ccb3fc21ef

### Operating system and version

Linux Lite 5.6

### Affected language servers

serve-d

### Steps to reproduce

1. Open neovim
2. The error pops up...

### Actual behavior

I'm getting the error message

### Expected behavior

To not get the error message and have the server working

### Minimal config

```Lua
I'm going to use the `LSP log` option below
```

### Health check

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: serve_d: configuration checked.
  - INFO: ccls: configuration checked.

### LSP log

https://gist.github.com/rempas/45024d479326ad85cf2fe9120c4c80fa

**Comment by lithammer** [comment]
Sounds like a problem with your installation of serve-d. What happens if you start it manually?

**Comment by rempas** [comment]
WHAT??? How are you this fast??? I post it like 5 minutes ago....

Now I suppose that you mean `:LspStart`. In this case, nothing happens until I press I key, then I'm getting the following error message:

```
Client 2 quit with exit code 0 and signal 11
LSP[id=2] client has shut down after sending the message
```

It is mostly the only the first line (with the number 2 been changed every time to a bigger one). 

When it comes to my installation of serve-d, I did the following:

1. Downloaded the file (linux version) from [here](https://github.com/Pure-D/serve-d/releases/tag/v0.6.0)
2. Extracted it (it contains the binary)
3. Move the binary on "/usr/local/bin" so it's on the path?

What do you suggest?

**Comment by lithammer** [comment]
> Now I suppose that you mean `:LspStart`.

No I meant just start it on the command-line outside of Neovim:

    $ serve-d

> What do you suggest?

It might be worth trying the latest beta (e.g. v0.7.0-beta.7) since v0.6.0 is almost 2 years old.

**Comment by rempas** [comment]
I'm sorry for the late answer but I'm at work and I couldn't answer. Ok so starting "serve-d" from the terminal runs the program normally and stops there waiting for input (the classic cursor blinking).

Anyways, trying the latest beta release fixes the problem! Thanks a lot for the help!!
