### ISSUE TITLE
powershell_es bad argument when using cmd without -Stdio parameter

### ISSUE THREAD

**Issue by ParkHost** [neovim/nvim-lspconfig#1376]
### Description

Am trying out powershell_es without the parameter: `-Stdio` as it has more features with [Named Pipes](https://github.com/PowerShell/PowerShellEditorServices#named-pipesunix-domain-sockets-recommended) and is recommended.
When am running **with** -Stdio param it is functioning as expected but without i get the error:

```
Error executing luv callback:
/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:601: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:161: bad argument #1 to 'sub' (number expected, got nil)

Error executing luv callback:
/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:601: cannot resume dead coroutine

```

I know it is possilbe in (neo)vim cause other extension `coc.nvim` is also using the PowerShell Editor Services with the named pipes as you can see here: https://github.com/coc-extensions/coc-powershell/blob/master/src/client/process.ts#L65-L83

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

6224c54a9945a52bf43a8bc1a42a112084590c0b

### Operating system and version

Arch Linux x86_64

### Affected language servers

powershell_es

### Steps to reproduce

1. config lspconfig with powershell_es
2. set cmd in lspconfig without -Stdio (as shown below in minimal config)

### Actual behavior

Error when opening powershell file in neovim:

```
Error executing luv callback:
/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:601: /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:161: bad argument #1 to 'sub' (number expected, got nil)

Error executing luv callback:
/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:601: cannot resume dead coroutine

```

### Expected behavior

successful client connection to LSP

### Minimal config

```Lua
require'lspconfig'.powershell_es.setup{
      filetypes = { "ps1", "psm1", "psd1" },
      on_new_config = function(new_config, _)
        new_config.cmd = {"/usr/bin/pwsh", "-NonInteractive", "-NoProfile", "-Command", "/home/test/PowerShellEditorServices/PowerShellEditorServices/Start-EditorServices.ps1 -BundledModulesPath /home/test/PowerShellEditorServices -LogPath /home/test/.cache/nvim/powershell_es.log -SessionDetailsPath /home/test/.cache/nvim/powershell_es.session.json -FeatureFlags @() -AdditionalModules @() -HostName nvim -HostProfileId nvim -HostVersion 1.0.0 -EnableConsoleRepl -LogLevel Diagnostic" }
      end,
      root_dir = util.root_pattern(".git", vim.fn.getcwd())
    }
```

### Health check

  - INFO: powershell_es: configuration checked.

### LSP log

https://gist.github.com/ParkHost/a4f5b18fa56db081b972ca2f1635773b

**Comment by mjlbach** [comment]
We only support launching server over stdio, and there's already a tracking issue in neovim core for allowing non stdio connections.
