### ISSUE TITLE
Pyright unable to resolve imports that are in my PYTHONPATH

### ISSUE THREAD

**Issue by jfly** [neovim/nvim-lspconfig#1387]
### Description

Sorry for the cross post, but I asked about this a while ago, and didn't get any responses: https://neovim.discourse.group/t/pyright-unable-to-resolve-imports-that-are-in-my-pythonpath/1289

Thanks in advance!

**Comment by mjlbach** [comment]
We explicitly have in our issue template that the issue tracker is not for usage questions for individual servers. Your post on the discourse is just as visible as the issue is here.

**Comment by jfly** [comment]
Sorry again for the cross post, and thanks for responding to my discourse thread!

**Comment by jfly** [comment]
For the record, this was resolved in https://github.com/neovim/nvim-lspconfig/pull/1407
