### ISSUE TITLE
`vscode-langservers-extracted` servers are not loading on Windows

### ISSUE THREAD

**Issue by adrianiy** [neovim/nvim-lspconfig#1397]
### Description

vscode related servers are not being attached at least on Windows.

Healthcheck says everything is fine but in logs only `Starting RPC client` are registerd

### Neovim version

NVIM v0.6.0-dev+558-g3ba800f15
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 11

### Affected language servers

vscode-langservers-extracted, html, css

### Steps to reproduce

1. Add html or css servers
2. open `.html` or `.css` file 
3. Check lsp logs

### Actual behavior

vscode servers are hanging before initialization

### Expected behavior

vscode servers should load or at least throw an error

### Minimal config

```Lua
vim.lsp.set_log_level 'debug'
if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
end
local nvim_lsp = require 'lspconfig'

-- nvim-cmp supports additional completion capabilities
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)
capabilities.textDocument.completion.completionItem.snippetSupport = true

local function config(_config)
	return vim.tbl_deep_extend("force", {
		capabilities = capabilities
	}, _config or {})
end

-- Enable the following language servers
local servers = {'html', 'tsserver', 'yamlls', 'cssls', 'eslint' }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup(config())
end

---- Example custom server
local sumneko_root_path = 'C:/Users/NyUser/.vscode/extensions/sumneko.lua-2.4.7/server'
local sumneko_binary = sumneko_root_path .. '/bin/Windows/lua-language-server'

-- Make runtime files discoverable to the server
local runtime_path = vim.split(package.path, ';')
table.insert(runtime_path, 'lua/?.lua')
table.insert(runtime_path, 'lua/?/init.lua')

nvim_lsp.sumneko_lua.setup {
  cmd = { sumneko_binary, '-E', sumneko_root_path .. '/main.lua' },
  on_attach = on_attach,
  capabilities = capabilities,
  settings = {
    Lua = {
      runtime = {
        -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
        version = 'LuaJIT',
        -- Setup your lua path
        path = runtime_path,
      },
      diagnostics = {
        -- Get the language server to recognize the `vim` global
        globals = { 'vim' },
      },
      workspace = {
        -- Make the server aware of Neovim runtime files
        library = vim.api.nvim_get_runtime_file('', true),
      },
      -- Do not send telemetry data containing a randomized but unique identifier
      telemetry = {
        enable = false,
      },
    },
  },
}
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: tsserver: configuration checked.
  - INFO: html: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: eslint: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: yamlls: configuration checked.

### LSP log

https://gist.github.com/adrianiy/7f8e0b72fc288ec1fcee9fba6b88e303

**Comment by adrianiy** [comment]
My fault 😢 

Windows needs to append `.cmd` in commands

**Comment by bryant-the-coder** [comment]
How do you solve this problem? I am encountering the same issue

**Comment by TobiasDev** [comment]
Same situation here. What do I need to do to fix this?
