### ISSUE TITLE
gopls no longer works as of 86abe8db3ad48271d7295b08cdbb923aa705644b

### ISSUE THREAD

**Issue by indeedhat** [neovim/nvim-lspconfig#1409]
### Description

Since the `86abe8db3ad48271d7295b08cdbb923aa705644b` commit (3 hours ago as of time of writing) lspconfig can no longer attach gopls to buffers (or so it seems)
![image](https://user-images.githubusercontent.com/2787027/141368616-adee22e0-a682-4f9e-aab0-ec1b631bcfb3.png)

reverting back to any earlier commit fixes the issue

### Neovim version

NVIM v0.6.0-dev+566-g4174244d8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

86abe8db3ad48271d7295b08cdbb923aa705644b

### Operating system and version

Endevour OS (Arch Linux)

### Affected language servers

gopls

### Steps to reproduce

1) update to any commit after the above commit ref
2) open vim in a go project directory (i have both go.mod and .git)
3) open the go.mod file or any .go file in the current or sub directories

### Actual behavior

no files get attached to the language server

### Expected behavior

.go and go.mod files should be recognized and handled by gopls

### Minimal config

```Lua
-- Set completeopt to have a better completion experience
vim.o.completeopt = 'menu,menuone,noselect'

-- Shared LSP settings
local nvim_lsp = require 'lspconfig'

local on_attach = function(_, bufnr)
    local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
    local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', '<leader>o', '<cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', '<Leader>K', '<cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<Leader>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<Leader>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<Leader>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<Leader>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<Leader>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', '<Leader>ca', '<cmd>lua vim.lsp.buf.code_action()<CR>', opts)
    buf_set_keymap('v', '<Leader>ca', '<cmd>lua vim.lsp.buf.range_code_action()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<Leader>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<Leader>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
    buf_set_keymap('n', '<Leader>f', '<cmd>lua vim.lsp.buf.formatting()<CR>', opts)
    vim.cmd [[ command! Format execute 'lua vim.lsp.buf.formatting()' ]]
end


-- nvim-cmp supports additional completion capabilities
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

-- Enable the following language servers
local servers = { 'gopls', 'rust_analyzer', 'pyright', 'phpactor', 'tsserver', 'solargraph' }
for _, lsp in ipairs(servers) do
    nvim_lsp[lsp].setup {
        on_attach = on_attach,
        capabilities = capabilities,
    }
end
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - ERROR: omnisharp: The given command "/usr/bin/omnisharp" is not executable.
  - INFO: sumneko_lua: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: phpactor: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: solargraph: configuration checked.

### LSP log

https://gist.github.com/indeedhat/ac91400acde47acb06d6cb6afe7080fb

**Comment by mjlbach** [comment]
I temporarily reverted until I have time to diagnose exactly what went wrong here.

**Comment by indeedhat** [comment]
that was extremely fast, much appreciated :)

**Comment by mjlbach** [comment]
Don't close the issue though, because the new behavior should be more correct, and if possible I'd like to ping you to test the PR again.

**Comment by indeedhat** [comment]
Yeah that is totally fine by me, i can confirm that everything is working again after a :PackerSync

**Comment by indeedhat** [comment]
I was curious so i did a little digging:

The issue seems to be that `go_mod_hierarchy` contains the paths to the go.mod files, not the directories that contain them.

So in my example the previous version was returning `/home/indeedhat/Documents/github/grobi` and the new version returned `/home/indeedhat/Documents/github/grobi/go.mod`

i hacked together a fix for my specific use case:
```lua
  -- First, search for go.work
  local primary_root = util.root_pattern 'go.work'(fname)
  if primary_root then
    return primary_root
  end

  -- Then, search up the filesystem for go.mod direcrory
  local go_mod_hierarchy = {}
  if primary_root then
    return primary_root
  end
  for path in util.path.iterate_parents(fname) do
    for _, p in ipairs(vim.fn.glob(util.path.join(path, 'go.mod'), true, true)) do
      if util.path.exists(p) then
        table.insert(go_mod_hierarchy, p)
      end
    end
  end

  -- Take the top level go.mod
  if #go_mod_hierarchy > 0 then
    return util.path.dirname(go_mod_hierarchy[#go_mod_hierarchy])
  end

  -- Fallback to the git root
  return util.find_git_ancestor(fname)
```

As far as i can tell the `primary_root` and git fallback both return the directory path already so this "should" be all that is needed.

**Comment by mjlbach** [comment]
Resolved via the revert, will unrevert with the fix soon
