### ISSUE TITLE
Disable diagnostics for pyright in favor of pylsp

### ISSUE THREAD

**Issue by and3rson** [neovim/nvim-lspconfig#1417]
### Description

It doesn't seem like it's possible to disable the diagnostics for Pyright.

I'm fairly sure this might be some dumb mistake from my end so I'm sorry in advance.

### Neovim version

NVIM v0.6.0-dev+527-ga141f6e92
Build type: Debug
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

98db21bbd4ef6f2bcd30903e32529976c1db33c5

### Operating system and version

ArchLinux

### Affected language servers

pyright

### Steps to reproduce

Use configuration from "minimal config" section

### Actual behavior

Diagnostics from Pyright should not be shown

### Expected behavior

Diagnostics from Pyright are shown

### Minimal config

```Lua
-- Attempt to set typeCheckingMode as per https://github.com/microsoft/pyright/blob/main/docs/configuration.md#main-pyright-config-options
lspconfig.pyright.setup{
    on_attach=on_attach,
    capabilities=capabilities,
    settings = {
        typeCheckingMode = 'off', -- no effect here...
        python = {
            analysis = {
                typeCheckingMode = 'off', -- and here...
            },
        },
        pyright = {
            disableDiagnostics = true, -- Used to work in coc
        }
    }
}
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: ccls: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: eslint: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: pylsp: configuration checked.
  - INFO: null-ls: configuration checked.
  - INFO: html: configuration checked.

### LSP log

https://gist.github.com/and3rson/8241e680c18acce741f00655d4a6c51a

**Comment by mjlbach** [comment]
This isn't a bug, in the issue template it is clear that questions about server configuration are meant to be asked on the discourse.

`disableDiagnostics` is not a pyright setting https://github.com/microsoft/pyright/blob/main/docs/settings.md

I'll answer your question though, in the future, please use the discourse.

```
lspconfig.pyright.setup{
    on_attach=on_attach,
    capabilities=capabilities,
    -- the next 3 lines are important
    handlers = {
        ['textDocument/publishDiagnostics'] = function(...) end
    },
    settings = {
        typeCheckingMode = 'off', -- no effect here...
        python = {
            analysis = {
                typeCheckingMode = 'off', -- and here...
            },
        },
        pyright = {
            disableDiagnostics = true, -- Used to work in coc
        }
    }
}
```

**Comment by and3rson** [comment]
@mjlbach Thank you for your attention! Sorry for using the wrong place to bring this up, I'll use discourse in the future.

**Comment by mbrochh** [comment]
I must say, I'm very glad that this question was asked here on github, as this helped me, more than a year later. I'd never have found the answer on discourse.
