### ISSUE TITLE
Can't use ccls with lsp

### ISSUE THREAD

**Issue by rzksobhy78** [neovim/nvim-lspconfig#1435]
### Description

Its works fine with other languages servers ( I tried clangd, cmake, pyright ) but when I try to use ccls
it gives me this error

### Neovim version

NVIM v0.5.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim/src/neovim-0.5.1/build/config -I/build/neovim/src/neovim-0.5.1/src -I/usr/include -I/build/neovim/src/neovim-0.5.1/build/src/nvim/auto -I/build/neovim/src/neovim-0.5.1/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Arch Linux

### Affected language servers

ccls

### Steps to reproduce

downloaded it to my lua file
and required it
commented all my other required files and tested it then copied lsp.log
and pasted it

### Actual behavior

Auto start for ccls failed: matching root directory not detected

### Minimal config

```Lua
[ERROR][2021-11-17 13:34:54] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:34:54.118] <-- textDocument/didOpen\n"
[ERROR][2021-11-17 13:34:54] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:34:54.118] Failed to find compilation database for /home/pc/dev/cmake-learn/src/main.hpp\nI[13:34:54.118] ASTWorker building file /home/pc/dev/cmake-learn/src/main.hpp version 0 with command clangd fallback\n[/home/pc/dev/cmake-learn/src]\n/usr/bin/clang -resource-dir=/usr/lib/clang/13.0.0 -- /home/pc/dev/cmake-learn/src/main.hpp\n"
[ERROR][2021-11-17 13:34:54] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:34:54.156] --> textDocument/publishDiagnostics\n"
[ERROR][2021-11-17 13:34:59] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:34:59.572] <-- textDocument/formatting(34)\n"
[ERROR][2021-11-17 13:34:59] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:34:59.618] --> reply:textDocument/formatting(34) 46 ms\n"
[ERROR][2021-11-17 13:35:00] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:00.557] <-- textDocument/formatting(35)\n"
[ERROR][2021-11-17 13:35:00] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:00.557] --> reply:textDocument/formatting(35) 0 ms\n"
[ERROR][2021-11-17 13:35:08] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:08.896] <-- textDocument/definition(36)\n"
[ERROR][2021-11-17 13:35:08] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:08.897] --> reply:textDocument/definition(36) 0 ms\n"
[ERROR][2021-11-17 13:35:10] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:10.568] <-- textDocument/definition(37)\n"
[ERROR][2021-11-17 13:35:10] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:10.583] --> reply:textDocument/definition(37) 14 ms\n"
[ERROR][2021-11-17 13:35:17] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:17.616] <-- textDocument/definition(38)\n"
[ERROR][2021-11-17 13:35:17] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:17.617] --> reply:textDocument/definition(38) 0 ms\n"
[ERROR][2021-11-17 13:35:18] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:18.816] <-- textDocument/definition(39)\n"
[ERROR][2021-11-17 13:35:18] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:18.817] --> reply:textDocument/definition(39) 0 ms\n"
[ERROR][2021-11-17 13:35:45] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:45.016] <-- textDocument/definition(40)\n"
[ERROR][2021-11-17 13:35:45] .../vim/lsp/rpc.lua:462    "rpc"   "clangd"        "stderr"        "I[13:35:45.030] --> reply:textDocument/definition(40) 13 ms\n"
[START][2021-11-17 13:54:55] LSP logging initiated
[START][2021-11-17 13:55:30] LSP logging initiated
[START][2021-11-17 13:56:21] LSP logging initiated
[START][2021-11-17 13:58:42] LSP logging initiated
[START][2021-11-17 13:56:50] LSP logging initiated
[START][2021-11-17 14:11:17] LSP logging initiated
[START][2021-11-17 14:13:01] LSP logging initiated
[START][2021-11-17 14:15:27] LSP logging initiated
[START][2021-11-17 14:16:35] LSP logging initiated
[START][2021-11-17 14:16:48] LSP logging initiated
[INFO][2021-11-17 14:16:59] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:17:05] LSP logging initiated
[INFO][2021-11-17 14:17:41] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:17:42] LSP logging initiated
[INFO][2021-11-17 14:17:49] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:17:53] LSP logging initiated
[INFO][2021-11-17 14:17:57] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:18:02] LSP logging initiated
[INFO][2021-11-17 14:18:16] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:18:17] LSP logging initiated
[INFO][2021-11-17 14:18:49] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:18:57] LSP logging initiated
[INFO][2021-11-17 14:21:52] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:21:55] LSP logging initiated
[INFO][2021-11-17 14:22:01] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:22:02] LSP logging initiated
[INFO][2021-11-17 14:22:04] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
[START][2021-11-17 14:22:09] LSP logging initiated
[INFO][2021-11-17 14:23:01] .../lua/vim/lsp.lua:1226    "exit_handler"  {}
```

### Health check

health#telescope#check
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - WARNING: nvim-treesitter not found. 

## Checking external dependencies
  - ERROR: rg: not found. `live-grep` finder will not function without [BurntSushi/ripgrep](https://github.com/BurntSushi/ripgrep) installed.
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: ccls: configuration checked.
  - INFO: cmake: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - ERROR: Locale does not support UTF-8. Unicode characters may not display correctly.
    $LANG=C $LC_ALL= $LC_CTYPE=
    - ADVICE:
      - If using tmux, try the -u option.
      - Ensure that your terminal/shell/tmux/etc inherits the environment, or set $LANG explicitly.
      - Configure your system locale.

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.9.7
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v16.11.1
  - INFO: Nvim node.js host: /usr/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

health#treesitter#check
========================================================================
## Checking treesitter configuration
  - INFO: Runtime ABI version : 13

### LSP log

https://gist.github.com/rzksobhy78/455441841e910fe81493f528a58e618d

**Comment by mjlbach** [comment]
The error message is explicit. I suggest you read the debugging section of readme.md, and `:help lspconfig-root-dir`

https://github.com/neovim/nvim-lspconfig/blob/84823995b7c62468a339df423ce6d85a2173f605/lua/lspconfig/ccls.lua#L8

**Comment by lithammer** [comment]
Your project is missing a compilation database as hinted by the error log:

> Failed to find compilation database for /home/pc/dev/cmake-learn/src/main.hpp
