### ISSUE TITLE
denols: consider removing "package.json" references, as `deno` ignores this file?

### ISSUE THREAD

**Issue by jokeyrhyme** [neovim/nvim-lspconfig#1438]
### Language server

denols

### Requested feature

Howdie! Thanks so much for sharing this work!

denols has default configuration that includes references to "package.json":

- https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/denols.lua#L119
- https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/denols.lua#L165

However, upstream `deno` doesn't seem use package.json at all:

- https://deno.land/manual#comparison-to-nodejs
- https://deno.land/manual@v1.16.2/linking_to_external_code#it-seems-unwieldy-to-import-urls-everywhere

Perhaps the default configuration for the denols integration should drop these reference?

**Comment by mjlbach** [comment]
Sure, the main denols user I know of is @David-Else, maybe he has thoughts. Go ahead and file the PR.

**Comment by David-Else** [comment]
@mjlbach This looks good to me!
