### ISSUE TITLE
ltex-ls support local dictionaries

### ISSUE THREAD

**Issue by kierun** [neovim/nvim-lspconfig#1443]
### Language server

ltex-ls

### Requested feature

`ltex-ls` correctly highlights some words as not spelled correctly. Sometimes, it is wrong and the word is correctly spelled such as a name for example. Neovim spell checker is fine since the weird word is in a spelling file…

`ltex-ls` has a system for [adding multiple spelling errors at the same time](https://valentjn.github.io/ltex/faq.html#how-can-i-fix-multiple-spelling-errors-at-the-same-time) but I could not figure out if the bindings are available in neovim. In any case, should we really have to define them twice? 

Can we have a default of `ltex-ls` respecting vim spelling files?

### Other clients which have this feature

N.A.

**Comment by clason** [comment]
For questions about server-specific configurations, ask on the server repo or the Neovim Discourse.

**Comment by mjlbach** [comment]
To clarify, ltex-ls uses off-spec commands that must be implemented client-side. We're not going to add off-spec commands to lspconfig, so you can follow (or PR) support to a plugins like grammarguard.nvim (which hopefully one day will)

**Comment by vigoux** [comment]
Reviving this, and for the record, looking at ltex options [here](https://valentjn.github.io/ltex/settings.html) it seems that we can add some dictionnaries.

Interestingly, I can't get the "external file" support described [here](https://valentjn.github.io/ltex/vscode-ltex/setting-scopes-files.html#external-setting-files) to work, which bothers me a bit.
Here is my config so far for external dictionnaries (does not work):
```lua
{
  ltex =
  -- redacted
    settings = {
      ltex = {
        -- redacted 
        dictionary = (function ()
          local files = {}
          for _, file in ipairs(vim.api.nvim_get_runtime_file("dict/*", true)) do
            local lang = vim.fn.fnamemodify(file, ":t:r")
            local fullpath = vim.fn.fnamemodify(file, ":p")
            files[lang] = { ":" .. fullpath }
          end

          if files.default then
            for lang,_ in pairs(files) do
              if lang ~= "default" then
                vim.list_extend(files[lang], files.default)
              end
            end
            files.default = nil
          end
          return files
        end)(),
      -- redacted
      },
    },
  },
}
```

It basically queries neovim for the list of existing dict files and adds them to the config.
I wonder why it does not work, but I am no LSP expert.

Do you think we have a reasons to open this issue again ?

Furthermore, we could set the `dictionnaries` to something matching Vim when `spellpath` is set ?

**Comment by vigoux** [comment]
So, apparently, the "external files" are client-specific.
My question is then whether a command like `ClangdSwitchSourceHeader` or a custom handler for this server would be appreciated ?

**Comment by vigoux** [comment]
Finally, for the record, here is the docs for custom command / extensions for ltex:
https://valentjn.github.io/ltex/ltex-ls/server-usage.html#commands
https://valentjn.github.io/ltex/ltex-ls/server-usage.html#custom-lsp-extensions

I am working on implementing handlers for various things in my config, and for now I already have `addToDictionary` working.

**Comment by krissen** [comment]
> I am working on implementing handlers for various things in my config, and for now I already have addToDictionary working.

Is it described anywhere? Did browse through your dotfiles repo, but not thoroughly enough to find this.

**Comment by melkster** [comment]
> for now I already have addToDictionary working

@vigoux Would you like to share how you got this working please? Have you considered turning it into a Neovim plugin? 🙂

**Comment by vigoux** [comment]
@mawkler: There you go !

https://github.com/vigoux/ltex-ls.nvim

**Comment by mawkler** [comment]
@vigoux Awesome! Thank you!

**Comment by briandipalma** [comment]
Can anyone explain why the dictionary doesn't work here?

```lua
settings = {
	ltex = { dictionary = { ["en-GB"] = { ":~/.config/nvim/spell/en.utf-8.add" } }, language = "en-GB" },
},
```

`language` works fine...

**Comment by vigoux** [comment]
From what I remember, the dictionnaries are actually an untold extension that has to be handled on the client side.

I don't remember extactly though, sorry.

**Comment by briandipalma** [comment]
Right, I see. ltex-ls [doesn't support external files, it's only the VSCode extension that does](https://github.com/valentjn/ltex-ls/issues/157#issuecomment-1048887854). Not that clear from the documentation.

**Comment by marcelarie** [comment]
@kierun Finally how did you get to work the "Add all unknown words in selection to dictionary" action with `nvim`?

**Comment by kierun** [comment]
@marcelarie I did not. I stopped using `ltex-ls` because of this.

**Comment by mjlbach** [comment]
https://github.com/vigoux/ltex-ls.nvim
________________________________

**Comment by marcelarie** [comment]
> @marcelarie I did not. I stopped using `ltex-ls` because of this.

What are you using?

**Comment by ygworldr** [comment]
> > @marcelarie I did not. I stopped using `ltex-ls` because of this.
> 
> @kierun What are you using?

The default Neovim spelling. Nothing else. My grammar and spelling just naturally suck because I am dyslexic. ¯\\\_(ツ)\_/¯

**Comment by kierun** [comment]
> > @marcelarie I did not. I stopped using ltex-ls because of this.
> 
> @kierun What are you using?

The default Neovim spelling. Nothing else. My grammar and spelling just naturally suck because I am dyslexic. ¯\_(ツ)_/¯

**Comment by briandipalma** [comment]
I add my spellings file to the ltex one using this code: https://github.com/briandipalma/ansible/blob/main/roles/common/files/nvim/lua/plugins/nvim-lspconfig.lua#L28-L41

**Comment by burnettk** [comment]
@briandipalma configs have totally changed since his comment (probably switched from neovim to notepad or something), but as long as the repo still exists, here is the working link: https://github.com/briandipalma/ansible/blob/2b7619ec6aa28722c12ef4cff4cce58f535c460a/roles/common/files/nvim/lua/plugins/nvim-lspconfig.lua#L28-L41

**Comment by DominikOcsofszki** [comment]
I was working with mason-lspconfig and found this Workaround:

require("mason-lspconfig").setup_handlers {

```lua
                ["ltex"] = function()
                    -- alternative: absolute path to file
                    -- local path_spelling = "/Users/NAME/.config/nvim/spell/spell-de.utf-8"
                    local path_spelling = vim.fn.stdpath("config") .. "/spell/spell-de.utf-8"
                    vim.keymap.set('n', '<leader>aw', ':!echo <c-r><c-w> >> /Users/NAME/.config/nvim/spell/spell-de.utf-8', {})
                    local spell_de = {}
                    for word in io.open(path_spelling, "r"):lines() do
                        table.insert(spell_de, word)
                    end

                    local lspconfig = require("lspconfig")
                    lspconfig.ltex.setup {
                        capabilities = capabilities,
                        on_attach = on_attach,
                        settings = {
                            ltex = {
                                language = "de-DE",
                                dictionary = {
                                    ['de-DE'] = spell_de
                                }
                            },
                        },
                    }
                end,
```

`<leader>aw` => add word under courser to spell-de.utf-8
Inside "/Users/name/.config/nvim/spell/spell-de.utf-8":
word1
word2
word3
...
`sort u` => can be used inside spell-de.utf-8 to make entries unique

**Comment by SichangHe** [comment]
Lazy loading, for future reference: https://github.com/SichangHe/.config/blob/30d0efa976ea5f9a9fa65f4da47194db0d9f7244/nvim/lua/plugins/lsp.lua#L33
