### ISSUE TITLE
filename getting passed as nil on windows 

### ISSUE THREAD

**Issue by Adictya** [neovim/nvim-lspconfig#1467]
### Description

Getting the following error when trying to start most servers

```
E5108: Error executing lua C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:97: filename: expected string, got nil
stack traceback:
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:97: in function 't'
        vim/shared.lua:541: in function 'is_valid'
        vim/shared.lua:559: in function 'validate'
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:220: in function 'validate_client_config'
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:644: in function 'start_client'
        ...\pack\packer\start\nvim-lspconfig\lua\lspconfig\util.lua:287: in function 'add'
        ...ck\packer\start\nvim-lspconfig\lua\lspconfig\configs.lua:218: in function 'try_add'
        [string ":lua"]:1: in main chunk
```

### Neovim version

NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 -DNVIM_TS_HAS_SET_MATCH_LIMIT /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-786

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

2e6c94069e92cb4a43416b3ac0267e941b3fd47e

### Operating system and version

Windows 10 Pro 19044.1348

### Affected language servers

all (tested pyright, sumneko, clang ) except few (tested html)

### Steps to reproduce

1. `nvim -nu minimal.lua` foo.py

### Actual behavior

Get an error on startup 
```
Error detected while processing FileType Autocommands for "python":
E5108: Error executing lua C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:97: filename: expected string, got nil
stack traceback:
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:97: in function 't'
        vim/shared.lua:541: in function 'is_valid'
        vim/shared.lua:559: in function 'validate'
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:220: in function 'validate_client_config'
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:644: in function 'start_client'
        ...\pack\packer\start\nvim-lspconfig\lua\lspconfig\util.lua:287: in function 'add'
        ...ck\packer\start\nvim-lspconfig\lua\lspconfig\configs.lua:218: in function 'try_add'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

And same when trying to manually start via `:LspStart`

```
E5108: Error executing lua C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:97: filename: expected string, got nil
stack traceback:
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:97: in function 't'
        vim/shared.lua:541: in function 'is_valid'
        vim/shared.lua:559: in function 'validate'
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:220: in function 'validate_client_config'
        C:\Program Files\Neovim\share\nvim\runtime\lua\vim\lsp.lua:644: in function 'start_client'
        ...\pack\packer\start\nvim-lspconfig\lua\lspconfig\util.lua:287: in function 'add'
        ...ck\packer\start\nvim-lspconfig\lua\lspconfig\configs.lua:218: in function 'try_add'
        [string ":lua"]:1: in main chunk
```

### Minimal config

```Lua
No changes
```

### Health check

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - WARNING: Can't find any config.
  - INFO: pyright: configuration checked.

### LSP log

https://gist.github.com/Adictya/594258d90ebd5f0bcd8b5b3d82a0fbd4

**Comment by mjlbach** [comment]
Update to 0.5.1

**Comment by Adictya** [comment]
Yes that fixed it, thank you
