### ISSUE TITLE
Could not find a valid tsserver version when using typescript-language-server@0.8.0 

### ISSUE THREAD

**Issue by hood** [neovim/nvim-lspconfig#1472]
### Description

After upgrading typescript-language-server to v0.8.0 via 
```npm install global typescript-language-server```
I'm getting a
```Could not find a valid tsserver version```
error when trying to open typescript buffers.

### Neovim version

NVIM v0.6.0-dev+622-gfd6df748

### Nvim-lspconfig version

a2863027c809127aca44e7519ec63a23ec0f1655

### Operating system and version

5.15.4-arch1-1

### Affected language servers

tsserver

### Steps to reproduce

Install typescript-language-server v0.8.0 then open NeoVim in a TypeScript codebase, opening a TypeScript buffer.

### Actual behavior

Getting the following error:
```
Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp.lua:877: RPC[Error] code_name = InternalError, message
 = "Request initialize failed with message: Could not find a valid tsserver version. Exiting."
stack traceback:
        [C]: in function 'assert'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:877: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```

### Expected behavior

Handling TypeScript buffers flawlessly.

### Minimal config

https://paste.ofcode.org/dmHAupVaWSaUqApriL8AbK

### Health check
```
lsp: health#lsp#check
========================================================================
  - ERROR: Failed to run healthcheck for "lsp" plugin. Exception:
    function health#check[24]..health#lsp#check, line 2
    Vim(lua):E5108: Error executing lua [string ":lua"]:1: attempt to call field 'check_health' (a nil value)
    stack traceback:
    [string ":lua"]:1: in main chunk

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: gopls: configuration checked.
  - INFO: dockerls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: tailwindcss: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: graphql: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: rust_analyzer: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 10
  - INFO: Checking stuff
  - WARNING: `focus-events` is not enabled. |'autoread'| may not work.
    - ADVICE:
      - (tmux 1.9+ only) Set `focus-events` in ~/.tmux.conf:
          set-option -g focus-events on
  - INFO: $TERM: screen-256color
```

### LSP log

-

**Comment by clason** [comment]
That is _not_ a minimal config... Please use the provided [minimal.lua](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua) and add (only!) what is necessary.

**Comment by clason** [comment]
(You can reopen the issue or comment again when you have adapted the config.)

**Comment by hood** [comment]
@clason config updated.

**Comment by mjlbach** [comment]
The minimal config you posted is for pyright... this seems like a server/environment error since we don't version check tsserver. I would wipe your global tsserver/typescript/typescript-language-server packages and reinstall

**Comment by clason** [comment]
In the new config
1. you're not configuring `tsserver` at all
2. you're still using unrelated plugins (treesitter, plenary, astronauta -- and above all, `lspUtil`)

Especially point 2. suggests that this is not an issue with any Neovim project but with that plugin...
