### ISSUE TITLE
Changes to expose config broke "null-ls"

### ISSUE THREAD

**Issue by bellini666** [neovim/nvim-lspconfig#1488]
### Description

Hi,

Changes from https://github.com/neovim/nvim-lspconfig/pull/1479 broke [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) from loading. Setting packer to the specific commit just before it (`10ad0cca1b83713ed98ed4cb7ea60f2ea8e55c49`) makes it work again.

I saw that this was documented as a [breaking change](https://github.com/neovim/nvim-lspconfig/issues/1075#issuecomment-979217514) but don't know if the author needs to do something to support the change or lspconfig needs to workaround cases like it.

cc: @mjlbach

### Neovim version

NVIM v0.6.0-dev+635-ga31e7523f
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

b2d302f1609a8267f4b855d8853fba65669aa8e5

### Operating system and version

Debian Unstable

### Affected language servers

null-ls

### Steps to reproduce

1. Use the latest (as of right now) lspconfig
2. Install and use [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) as described in its README page
3. Try to open neovim

### Actual behavior

A lot of `Cannot access configuration for null-ls. Ensure this server is listed in `server_configurations.md` or added as a custom server.` messages

### Expected behavior

No errors and `null-ls` working

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            "neovim/nvim-lspconfig",
            "jose-elias-alvarez/null-ls.nvim",
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

_G.load_config = function()
    vim.lsp.set_log_level("trace")
    if vim.fn.has("nvim-0.5.1") == 1 then
        require("vim.lsp.log").set_format_func(vim.inspect)
    end
    local nvim_lsp = require("lspconfig")
    local on_attach = function(_, bufnr)
        local function buf_set_keymap(...)
            vim.api.nvim_buf_set_keymap(bufnr, ...)
        end
        local function buf_set_option(...)
            vim.api.nvim_buf_set_option(bufnr, ...)
        end

        buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

        -- Mappings.
        local opts = { noremap = true, silent = true }
        buf_set_keymap("n", "gD", "<Cmd>lua vim.lsp.buf.declaration()<CR>", opts)
        buf_set_keymap("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", opts)
        buf_set_keymap("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", opts)
        buf_set_keymap("n", "gi", "<cmd>lua vim.lsp.buf.implementation()<CR>", opts)
        buf_set_keymap("n", "<C-k>", "<cmd>lua vim.lsp.buf.signature_help()<CR>", opts)
        buf_set_keymap("n", "<space>wa", "<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>", opts)
        buf_set_keymap("n", "<space>wr", "<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>", opts)
        buf_set_keymap("n", "<space>wl", "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>", opts)
        buf_set_keymap("n", "<space>D", "<cmd>lua vim.lsp.buf.type_definition()<CR>", opts)
        buf_set_keymap("n", "<space>rn", "<cmd>lua vim.lsp.buf.rename()<CR>", opts)
        buf_set_keymap("n", "gr", "<cmd>lua vim.lsp.buf.references()<CR>", opts)
        buf_set_keymap("n", "<space>e", "<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>", opts)
        buf_set_keymap("n", "[d", "<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>", opts)
        buf_set_keymap("n", "]d", "<cmd>lua vim.lsp.diagnostic.goto_next()<CR>", opts)
        buf_set_keymap("n", "<space>q", "<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>", opts)
    end

    -- Add the server that troubles you here
    local name = "null-ls"
    if not name then
        print("You have not defined a server name, please edit minimal_init.lua")
    end
    if not nvim_lsp[name].document_config.default_config.cmd then
        print([[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]])
    end

    require(name).config({
        sources = {
            require("null-ls").builtins.formatting.stylua,
            require("null-ls").builtins.completion.spell,
        },
    })
    nvim_lsp[name].setup({
        on_attach = on_attach,
    })

    print(
        [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
    )
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
    vim.cmd([[autocmd User PackerComplete ++once lua load_config()]])
else
    load_plugins()
    require("packer").sync()
    _G.load_config()
end
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: pyright: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: eslint: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: dockerls: configuration checked.
  - INFO: yamlls: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: html: configuration checked.

obs. null-ls not displayed here but before the change it was showing as "configuration checked"

### LSP log

n/a

**Comment by clason** [comment]
Yes, that's an issue with null-ls, see https://github.com/jose-elias-alvarez/null-ls.nvim/issues/378

**Comment by max397574** [comment]
no ig it's not an issue with null-ls

my personal setup broke and lspmanager also broke

**Comment by mjlbach** [comment]
it 100% is and was fixed by https://github.com/jose-elias-alvarez/null-ls.nvim/commit/f3a4a14652c85f5bf637d9f3c6dfde2eb5e3d7fc

**Comment by clason** [comment]
If other plugins (and configs) made use of internal implementation details that should not be considered public API, these of course could _also_ be broken and need to be adapted.

**Comment by max397574** [comment]
I don't know what's the problem, what you changed and what was with null-ls

I only know I don't use null-ls and I get an error

**Comment by mjlbach** [comment]
Well, if it's a separate issue than null-ls (which is what this issue is about), you should examine your config.

**Comment by max397574** [comment]
it always worked before updating nvim-lspconfig

**Comment by max397574** [comment]
and I get exactly the same error
```
Cannot access configuration for ls_emmet. Ensure this server is listed in `server_configurations.md` or
 added as a custom server.
 ```

**Comment by mjlbach** [comment]
the error message is extremely explicit, replace `ls_emmet` with `emmet_ls`

**Comment by max397574** [comment]
```
packer.nvim: Error running config for nvim-lspconfig: ...pack/packer/opt/nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil value)
```

**Comment by clason** [comment]
Come on, don't hijack unrelated issues. Ask on chat or open your own.
