### ISSUE TITLE
Full windows support for all applicable servers

### ISSUE THREAD

**Issue by mjlbach** [neovim/nvim-lspconfig#1500]
### Description

I want to delete [this section](https://github.com/neovim/nvim-lspconfig#windows) from the readme. So lets test all the language servers on windows and update the cmd [like this](https://github.com/neovim/nvim-lspconfig/blob/8c9962bae5ac3b1f8b3d84c18314325f2d8df7fd/lua/lspconfig/server_configurations/pyright.lua#L3-L6)

Please list servers that need to be updated (better yet file PRs)

**Comment by williamboman** [comment]
As I've been going through https://github.com/williamboman/nvim-lsp-installer/pull/283 I've identified the following server configurations that might have to be revisited for Windows:

- erlangls
- ccls
- codeql
- solang

I will probably check these myself once I get around to merging it, just a heads up
