### ISSUE TITLE
config_def is nil

### ISSUE THREAD

**Issue by paopaol** [neovim/nvim-lspconfig#1502]
### Description

nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil value)

i only update the lspconfig and restart nvim. i got the error

### Neovim version

0.5

### Operating system and version

linux

### Affected language servers

all

### Steps to reproduce

require('lspconfig').clangd.setup({}) 

### Actual behavior

nvim-lspconfig/lua/lspconfig/configs.lua:10: attempt to index local 'config_def' (a nil value)

### Expected behavior

works

### Minimal config

```Lua
require('lspconfig').clangd.setup({})
```

### Health check

good

### LSP log

none

**Comment by mjlbach** [comment]
https://github.com/neovim/nvim-lspconfig/issues/1075#issuecomment-980801779
