### ISSUE TITLE
Regenerating helptags dirties the repo

### ISSUE THREAD

**Issue by perrin4869** [neovim/nvim-lspconfig#1507]
### Description

This was introduced in  #1497
Whenever you run `helptags` on `nvim-lspconfig`, the geterated tags file will differ from the one checked into the repo.
I think a lot of people might be generating their helptags on their own as well.
Since I have `nvim-lspconfig` as a subrepo [here](https://github.com/perrin4869/dotfiles/tree/master/home/.local/share/nvim/site/pack/default/start), my own repo becomes dirty after generating the tags

### Neovim version

NVIM v0.6.0-dev
Build type: Release
LuaJIT 2.0.5
Compiled by root@landau.julian.dotcore.co.il

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

d9aa848d

### Operating system and version

slackware64-current

### Affected language servers

none

### Steps to reproduce

Running `helptags ALL` inside neovim with `nvim-lspconfig`.

### Actual behavior

`nvim-lspconfig` repo becomes dirty

### Expected behavior

`nvim-lspconfig` files do not change from the committed versions

### Minimal config

```Lua
Not relevant?
```

### Health check

Not relevant?

### LSP log

not relevant

**Comment by mjlbach** [comment]
I'm open to suggestions, but I think having the markdown file directly indexed as a tag is an invaluable feature (cc @muniter)

**Comment by perrin4869** [comment]
Is there no way to have it added there by `helptags` automatically?

**Comment by perrin4869** [comment]
The other thing is that if someone is running `helptags` on their own as well, the markdown file will not be indexed, defeating the purpose of the feature altogether

**Comment by muniter** [comment]
So there's a few options as I mentioned in matrix. 

1. Rename `tags` to `tags-en` which `helptags` won't overwrite since there's no `lapconfig.enx` and in my testing (my machine) `:help` always searches `tags-en`.

2. Symlink `servers_configuration.md` to `servers_configuration.txt` and add a comment at the top of the file with the tag name. Making `helptags` find it and generate it always. The downside is i don't think symlinks work out of the box from a repo in windows 🪟

    2.1. Ugly: duplicate the markdown file as txt and md extension and it will work anywhere. 

    2.2 Rename `server_configurations.md` to `server_configurations.txt` and provide a modeline saying is a markdown file. According to [this link it works](https://github.com/github/markup/issues/1069#issuecomment-460056003). So GitHub displays it as markdown. Vim sees as `txt` because the extension and generates the proper tag!!!


So 2.2 sound like the best solution. What do you think @mjlbach your call.

**Comment by mjlbach** [comment]
Leaning towards 1
