### ISSUE TITLE
Provide json schemas by default

### ISSUE THREAD

**Issue by budimanjojo** [neovim/nvim-lspconfig#1513]
### Language server

jsonls

### Requested feature

COC have this json schemas by default: https://github.com/neoclide/coc-json/blob/master/src/catalog.json
So the users usually don't need to do anything and it just works.

**Comment by budimanjojo** [comment]
Actually there is a plugin just for this: https://github.com/b0o/SchemaStore.nvim

**Comment by mjlbach** [comment]
Sorry, that's out of scope. If someone wants to make a jsonls.nvim that does all that by default, that's great, and we'll link to it in the docs.
