### ISSUE TITLE
Root for ErlangLs is not always detected correctly

### ISSUE THREAD

**Issue by filmor** [neovim/nvim-lspconfig#1523]
### Description

Rebar3 umbrella projects allow for `rebar.config` files in sub-projects, but lsp config uses this to derive the project root (wrongly, in this case).

### Neovim version

NVIM v0.5.1
Build type: Gentoo
LuaJIT 2.0.5

### Operating system and version

Linux

### Affected language servers

erlangls

### Steps to reproduce

Create an umbrella project with a nested `rebar.config`:

```
rebar3 new umbrella
touch apps/myapp/rebar.config
```

### Actual behavior

When opening the file `myapp/apps/myapp/src/myapp_app.erl`, lsp-config will see the first `rebar.config` and treat `myapps/apps/myapp` as the project root.

### Expected behavior

The project root is `myapp`.

### Minimal config

```Lua
-/-

Can't get this to work with the "minimal_init".
```

### Health check

health#lspconfig#check
===============================================================================
## Checking language server protocol configuration
   - INFO: erlangls: configuration checked.

### LSP log

-/-

**Comment by mjlbach** [comment]
Our root directory detection is best guess, it mostly works, sometimes it doesn't. You can always override locally in your config

**Comment by lithammer** [comment]
> Our root directory detection is best guess, it mostly works, sometimes it doesn't. You can always override locally in your config

Seems like it's quite common for languages to have some kind of nested workspace support. Maybe it would make sense to revive some version of GH-652 with a depth-first search utility function that can used to find a top-level/umbrella workspace file?

That would make it easier to support these scenarios.

**Comment by filmor** [comment]
I could implement a special case for this one as well, it doesn't have to be generic. As far as I know, `rebar3` only supports a single level, so it should be enough to see, whether `parent = 'apps'` and `grandparent contains rebar.config`.

**Comment by mjlbach** [comment]
Where is the documentation on the conventions around rebar3.config?

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.

**Comment by filmor** [comment]
I am not really sure what you have achieved by closing this issue. The issue persists until it is fixed. Nested workspaces, as mentioned before, are a common setup nowadays, so it might be useful to be aware of the different LSPs that could profit from a generic implementation here.
