### ISSUE TITLE
Bashls not supporting code action but asked to

### ISSUE THREAD

**Issue by JosefLitos** [neovim/nvim-lspconfig#1534]
### Description

some inner command seems to do `autocmd CursorHold *` or something like that (I don't understand it that much really), because whenever I open a bashscript it gives me an error on any keypress

### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.0.5

### Nvim-lspconfig version

382712c4ecba5816f398379dd9d8c8200b025ca3

### Operating system and version

Archlinux 1.0

### Affected language servers

bashls

### Steps to reproduce

1. install `bash-language-server`
2. add to your config `require("lspconfig").bashls.setup({})
3.  open a bashscript

### Actual behavior

after opening a baschript, this error message pops up after any key pressed:
```
Error when executing CursorHold automatic commands for "*":
method textDocument/codeAction is not supported by any of the servers registered for the current buffer
```

### Expected behavior

no errors popping up on a keypress

### Minimal config

https://github.com/JosefLitos/dotfiles/.config/nvim
it may be connected to Lspsaga, but
I tried disabling all unnecessary plugins except lspconfig and only launching command `require("lspconfig").bashls.setup({})` but the result is identical.

### Health check

![obrazek](https://user-images.githubusercontent.com/54900518/144709743-cff4e035-93d7-4c0c-aba7-e324eef39fbe.png)

### LSP log

https://gist.github.com/JosefLitos/52551d2da6cd8ece967a15a22f1c3139

**Comment by clason** [comment]
Please verify using the _minimal_ config provided. There are _no_ `CursorHold` autocommands in lspconfig.

**Comment by mjlbach** [comment]
Bashls doesn't support code actions, you get this error because something is mapping an autocommand that calls the code action request before checking if the client supports code actions.
