### ISSUE TITLE
Updated instructions for lua-language-server unclear

### ISSUE THREAD

**Issue by heygarrett** [neovim/nvim-lspconfig#1538]
### Description

The updated instructions in https://github.com/neovim/nvim-lspconfig/pull/1537 specify to use `cmd = { "/path/to/lua-language-server" };`, but doing so gives me an error whenever I attempt to open a Lua file in Neovim:

```  
Spawning language server with cmd: `/Users/garrett/.local/src/lua-language-server` failed with error
message: EACCES: permission denied
```

Comparing it to the previous config, I tried using the path to the binary:

```
cmd = { vim.env.HOME .. '/.local/src/lua-language-server/bin/macOS/lua-language-server' },
```

and that *does* work, but I'm not sure if that's the correct way to set it up based on it not being specified in the new instructions.

### Neovim version

NVIM v0.7.0-dev+nightly-1194-g76af219e3
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

fe9f2a5c45df35d9d1ea9688b9c805a74ac5254d

### Operating system and version

macOS 12.0.1

### Affected language servers

sumneko lua-language-server

### Steps to reproduce

1. Install sumneko lua-language-server  
2. Configure nvim-lspconfig using instructions for lua-language-server
3. Open a Lua file in Neovim

### Actual behavior

```
Spawning language server with cmd: `/Users/garrett/.local/src/lua-language-server` failed with error
message: EACCES: permission denied
```

From `:LspInfo`:

```
 Language client log: /Users/garrett/.cache/nvim/lsp.log
 Detected filetype:   lua
 
 0 client(s) attached to this buffer: 
 
 Other clients that match the filetype: lua
 
 Config: sumneko_lua
 	filetypes:         lua
 	root directory:    /Users/garrett/.config
 	cmd:               /Users/garrett/.local/src/lua-language-server
 	cmd is executable: Unable to find executable. Please check your path and ensure the server is installed
 	autostart:         true
 	custom handlers:   
```

### Expected behavior

No error, and lua-language-server would attach to the buffer.

### Minimal config

```Lua
vim.api.nvim_command('autocmd BufWritePost packer.lua source <afile> | PackerCompile')

local packer_bootstrap
local install_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
	packer_bootstrap = vim.fn.system {
		'git', 'clone', '--depth', '1',
		'https://github.com/wbthomason/packer.nvim',
		install_path
	}
end

require('packer').startup {
	function(use)
		use {
			'wbthomason/packer.nvim',
			'neovim/nvim-lspconfig',
		}

		if packer_bootstrap then
			require('packer').sync()
		end
	end,
}

local runtime_path = vim.split(package.path, ';')
table.insert(runtime_path, 'lua/?.lua')
table.insert(runtime_path, 'lua/?/init.lua')

require('lspconfig').sumneko_lua.setup {
	on_attach = require('utils/on-attach'),
	capabilities = vim.lsp.protocol.make_client_capabilities(),
	cmd = { vim.env.HOME .. '/.local/src/lua-language-server' },
	settings = {
		Lua = {
			runtime = {
				version = 'LuaJIT',
				path = runtime_path,
			},
			diagnostics = {
				globals = { 'vim' },
			},
			workspace = {
				library = vim.api.nvim_get_runtime_file('', true),
			},
			telemetry = {
				enable = false,
			},
		},
	},
}
```
```


### Health check


lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: jsonls: configuration checked.
  - INFO: sumneko_lua: configuration checked.
  - INFO: eslint: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: sourcekit: configuration checked.


### LSP log

I don't know how, or specifically where, to do this.

**Comment by clason** [comment]
It's the path to the _binary_ -- which is also called `lua-language-server`.

**Comment by mjlbach** [comment]
I guess we could make this more obvious.

**Comment by clason** [comment]
added a comment to the docs

**Comment by heygarrett** [comment]
The instructions previously located the binary for the user (eg, checking the system name and creating the binary path). Although some of the command arguments are no longer necessary, why remove this aspect of the instructions? I honestly would've had a hard time locating the binary myself if I didn't have the previous configuration to work off of.

**Comment by mjlbach** [comment]
It assumed a harcoded path from the old lspinstall feature (which was removed a year ago), there's upstream documentation in the lua-language-server repo anyways.

**Comment by clason** [comment]
Previously, you _couldn't_ just install `lua-language-server` with a package manager and just call the command. Since this has changed, such an installation is now the preferred way. 

We _cannot_ cover all possible ways of installing each language server; some familiarity with their installation instructions and documentation has to be assumed.

**Comment by clason** [comment]
@mjlbach should we just remove the `cmd` key from the docs, since the default should work in most cases?

**Comment by mjlbach** [comment]
We could note it needs to be on PATH (assumption for all of lspconfig's defaults) and remove the old PATH notice.

**Comment by clason** [comment]
Yes, there is more from the old documentation that is now obsolete and can be removed.

**Comment by heygarrett** [comment]
> Previously, you couldn't just install lua-language-server with a package manager and just call the command. Since this has changed, such an installation is now the preferred way.

Oh, I didn't realize! Which package manager is it available from?

**Comment by clason** [comment]
Macports has it, for example.

**Comment by mjlbach** [comment]
macprots, nixpkgs, and the AUR
