### ISSUE TITLE
Skip attaching to buffers such as fugitive:// 

### ISSUE THREAD

**Issue by kting28** [neovim/nvim-lspconfig#1540]
### Language server

clangd

### Requested feature

Basically clangd configured through lspconfig attaches to [fugitive buffers](https://github.com/neovim/neovim/issues/16523) which results in clangd complaining that that non file URI is passed. Can the settings skip these buffers automatically?

### Other clients which have this feature

vim-lsp

**Comment by mjlbach** [comment]
This is a regression, I added handling for this previously.

**Comment by thecontinium** [comment]
I am having the same problem on buffers from [gina](https://github.com/lambdalisue/gina.vim/issues/294)

**Comment by kting28** [comment]
For now I added the following in on_attach to skip any mappings:
```
local on_attach = function(client, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end
  -- skip buffers with special URI, e.g. fugitive://...
  if vim.api.nvim_buf_get_name(bufnr):match "^%a+://" then
    return
  end
```
This is the only place apparent to me that has `bufnr` access to check the buffer name. I think LSP still attaches but at least none of the autocmds or keys are mapped. No the best solution of course

**Comment by thecontinium** [comment]
Adding some sort of additional check whether the buffer name actually is a path to file before trying to find it's root directory seems to be missing, or not picking up these cases.

There must be a better more generic solution but adding this 

``` lua
if vim.api.nvim_buf_get_name(bufnr):match "^%a+://" then
    return
end
```

[here](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#L208) would at least solve the problem of auto starting servers trying to find the root from a the buffer with a name like this.

**Comment by typon** [comment]
confirm that this works for me locally, thanks for the fix @thecontinium

**Comment by mjlbach** [comment]
Do you want to test #1598?

**Comment by thecontinium** [comment]
Fixes the problem I was having with gina buffers - thanks.

**Comment by j-krl** [comment]
Anyone else experiencing a regression on this? I know this is an old issue but I'm currently getting LSPs attaching to my fugitive buffers

**Comment by Frederick888** [comment]
@j-krl See https://github.com/neovim/neovim/issues/33225 https://github.com/neovim/neovim/issues/32074
