### ISSUE TITLE
Newlines appear as "^M" for tsserver

### ISSUE THREAD

**Issue by harrisoncramer** [neovim/nvim-lspconfig#1545]
### Description

I'm seeing the carriage return displayed inside of LSP's suggestions. I've attached a screenshot for reference.

<img width="925" alt="Screen Shot 2021-12-05 at 5 38 58 PM" src="https://user-images.githubusercontent.com/32515581/144766738-2f886420-7bf0-424c-9052-0688642c1368.png">

### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

### Operating system and version

macOS 12.0.1

### Affected language servers

tsserver

### Steps to reproduce

This occurs whenever I open a JS/TS file with my current configuration, which is online here https://github.com/harrisoncramer/nvim/tree/work

### Actual behavior

See the screenshot.

### Minimal config

```Lua
With minimal typescript configuration.
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: sumneko_lua: configuration checked.
  - INFO: vuels: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: clojure_lsp: configuration checked.

### LSP log

https://gist.github.com/harrisoncramer/454bbad6e1c1645bbe72822b7ec7c8a8

**Comment by mjlbach** [comment]
From the issue template:
> Note that this repository implements configuration and initialization of language servers. **Implementation of the language server spec itself is located in the neovim core repository.**
