### ISSUE TITLE
No tag for v0.5

### ISSUE THREAD

**Issue by suy** [neovim/nvim-lspconfig#1547]
### Requested feature

In 622b155fb608d5366658de12a08b3050f5ca5772, it was said:

> Use a commit or tag for compatibility with previous releases.

That is fine, but no such tag is provided. ;-) Now it's easy to track the list of recent commits and see which one might have changed the requirements, but later on it will be harder.

Hopefully a tag and/or release for 0.5 compatibility can still be pushed.

Thank you!

**Comment by mjlbach** [comment]
There's still no breaking changes. I'll make a tag when it's ready.
