### ISSUE TITLE
No error/warning, still showing empty column

### ISSUE THREAD

**Issue by nachiketkanore** [neovim/nvim-lspconfig#1548]
### Description

- lsp diagnostics working correctly but there is always an extra diagnostics column (on the left with yellow straight line, see images) even though there are no errors / warnings

- Also this happens only for "rls" language server, I have tried with clangd and python and they work perfectly as expected.

![correct](https://user-images.githubusercontent.com/44920607/144895764-863bd785-d335-4aa1-959a-391e32beaabb.png)
![wrong](https://user-images.githubusercontent.com/44920607/144895769-77371721-8c4f-4d14-9d8e-75a2b1d37569.png)
![Screenshot from 2021-12-06 23-22-05](https://user-images.githubusercontent.com/44920607/144896659-40226941-9484-4340-a955-3d72feab8810.png)
expected (works properly with c++ clangd)
![Screenshot from 2021-12-06 23-37-40](https://user-images.githubusercontent.com/44920607/144898829-e64d6f2b-ee5d-48cf-8342-a10804ce2ba3.png)

### Neovim version

NVIM v0.7.0-dev

### Operating system and version

ubuntu 20

### Affected language servers

rls

### Steps to reproduce

1. nvim-lspconfig setup with rls server
2. start rust cargo project

### Actual behavior

whenever there is no error / warning, i don't want that extra empty leftmost column (with yellow line), as it works for different language servers (except rls)
![wrong](https://user-images.githubusercontent.com/44920607/144896801-11712ae7-bd72-4e68-9362-3865b6b2d3e4.png)

### Minimal config

```Lua
local servers = { 'rls', 'bashls', 'pyright', 'clangd', 'html', 'tsserver' }

Plugins:
require('settings')
require('keymaps')
require('plugins/packer')
require('plugins/nvim-tree')
require('plugins/feline')
require('plugins/nvim-cmp')
require('plugins/nvim-lspconfig')
require('plugins/nvim-treesitter')
require('plugins/alpha-nvim')
require('plugins/neoscroll')
require('plugins/auto-pairs')

settings.lua file:
https://gist.github.com/nachiketkanore/b0d6f59f19845cdce89a9125265f380b
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - ERROR: html: The given command "vscode-html-language-server" is not executable.
  - INFO: rls: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: tsserver: configuration checked.
  - ERROR: bashls: The given command "bash-language-server" is not executable.

### LSP log

https://gist.github.com/nachiketkanore/3740a8e6c59aa4acca20c6fdf0db761f

**Comment by clason** [comment]
There is no "diagnostic column"; diagnostic signs are drawn via the standard sign function of Neovim  (`:h 'signcolumn'). In any case, this has nothing to do with lspconfig.

**Comment by nachiketkanore** [comment]
Thanks for clarification!
@clason Any idea what this might be related to?

**Comment by clason** [comment]
No, sorry. I suggest you check your config for plugins. (Or ask on Discourse or Matrix.)

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/no-error-warning-still-showing-empty-column-using-nvim-lspconfig-with-rls/1642/1
