### ISSUE TITLE
Populate Tag Stack When Using Goto Reference

### ISSUE THREAD

**Issue by holmanb** [neovim/nvim-lspconfig#1553]
### Language server

No

### Requested feature

After calling Goto definition, one can use `<C-t>` to "go back to where I was when I called goto definition", using the tag stack. It would be great if a tag was also added to the tag stack when using "go to reference" for consistent navigation behavior. Currently if I do "go to definition", followed by "go to references", and then `<C-t>` (go back), I would expect to be taken to the definition, but I'm taken back to the location I was at before "go to definition". I would expect a tag to be added when calling at "go to references", which would cause `<C-t>` to bring me back to the definition.

**Comment by mjlbach** [comment]
Please read the issue template, this is not the correct repo to file feature requests for the neovim built-in language server client.

**Comment by holmanb** [comment]
> Please read the issue template, this is not the correct repo to file feature requests for the neovim built-in language server client.

My apologies. I did read the template, however I didn't realize this request was specific to the neovim built-in language server client.

**Comment by mjlbach** [comment]
Its ok, this repository *only* provides the configurations for the server and launches the server. All of the built-in language server client code (including go-to definition) is provided by neovim core.

**Comment by holmanb** [comment]
> Its ok, this repository _only_ provides the configurations for the server and launches the server. All of the built-in language server client code (including go-to definition and goto-references) is provided by neovim core.

Thanks! Good to know.
