### ISSUE TITLE
vim segfaults when deleting text

### ISSUE THREAD

**Issue by jasoneveleth** [neovim/nvim-lspconfig#1554]
### Description

When I open the attached file seg.c, and delete from the line 54 to the bottom of the file (ex. '54GdG'), this crashed nevoid and reports this error message:

vi(3764,0x106494e00) malloc: *** set a breakpoint in malloc_error_break to debug                                                                                                                                                         dG 
     zsh: abort      vi ~/seg.c
                               %

### Neovim version

NVIM v0.6.0-dev+nightly-764-gacd5e831b6
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by jason@*******

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-acd5e83/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

1996c4e

### Operating system and version

macOS 11.6

### Affected language servers

clangd

### Steps to reproduce

1. `nvim -nu ~/.config/nvim/init.vim seg.c`
2. `54GdG`

Get seg.c from https://gist.github.com/jasoneveleth/567fcb91e185e1664688ee63f160c409

### Actual behavior

nvim crashed.

### Expected behavior

I expect it to delete the text like normal.

### Minimal config

```Lua
With: lspconfig in pack/minpac/start/nvim-lspconfig
With init.vim:

lua require'lspconfig'.clangd.setup{}
lua vim.lsp.set_log_level('debug')
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: clangd: configuration checked.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.9.8
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v17.0.1
  - INFO: Nvim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.10.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/jason/.cache/nvim/lsp.log
  - WARNING: Log size: 203256 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 13

### LSP log

https://gist.github.com/jasoneveleth/567fcb91e185e1664688ee63f160c409

**Comment by clason** [comment]
This repo contains only configs for language servers (and some glue code); if Neovim segfaults, this is an issue with the editor itself and should be reported there.
