### ISSUE TITLE
Supporting multi maven projects.

### ISSUE THREAD

**Issue by blmhemu** [neovim/nvim-lspconfig#1558]
### Language server

jdtls

### Requested feature

I am trying to use neovim for a multi maven project similar to https://github.com/gama-platform/gama
But when I open a buffer, only that specific sub-maven project is considered and shows some errors.
Is it possible to add support for multi maven projects or am I missing anything?

I see that gradle is supported (but maven is not ?) https://github.com/neovim/nvim-lspconfig/blob/e6d95863a336b7e52c92b38c62aa60b469254d14/lua/lspconfig/server_configurations/jdtls.lua#L90

### Other clients which have this feature

Don't know

**Comment by mjlbach** [comment]
Please follow the issue template. I'm assuming the root directory is not correct for your project (which you can override manually).

Refile an issue following the full template.
