### ISSUE TITLE
How to configure File Associations for Intelephense LS

### ISSUE THREAD

**Issue by danshumaker** [neovim/nvim-lspconfig#1561]
### Language server

intelephense

### Requested feature

I was not able to find how to configure lspconfig to set the file.associations structure for php files that drupal uses.

In here: https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#intelephense

There is an example of setting filetypes.  
``` lua
filetypes = { "php" }
```

In here: https://github.com/bmewburn/vscode-intelephense  They mention what the structure might look like:

```lua
"files.associations": { "*.module": "php" }
```

So for drupal development, inside my nvim-lspconfig.lua  I think I would want something like this
```lua
local files_associations = {}
files_associations["*.install"] = "php"
files_associations["*.theme"] = "php"
files_associations["*.module"] = "php"
files_associations["*.inc"] = "php"

for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
    files.associations = files_associations,
    ts_settings = ts_settings,
    flags = {
      debounce_text_changes = 150,
    }
  }
end
```

But that does not work.

I also see this structure proposed for Coc  ( https://webschneider.org/post/intelephense-drupal7/ )

```lua
{
  "intelephense.environment.documentRoot": "/home/user/git/drupal",
  "intelephense.environment.includePaths": ["/home/user/git/drupal/includes"],
  "intelephense.files.associations": ["*.php", "*.phtml", "*.module", "*.inc"]
}
```

I see that for the ts_server there is a function delared that sets internal settings so I tried this:

```lua
-- Set settings for language servers below
--
-- tsserver settings
local ts_settings = function(client)
  client.resolved_capabilities.document_formatting = false
  ts_settings(client)
end

local file_settings = function(client)
  files.associations = { '*.install', '*.theme', '*.module', '*.inc' }
  file_settings(client)
end

-- local files_associations = { '*.install', '*.theme', '*.module', '*.inc' }

for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
    files_settings = file_settings,
    ts_settings = ts_settings,
    flags = {
      debounce_text_changes = 150,
    }
  }
end
```
But that did not work either.

Has anyone gotten file.associations to work with Intelephense LS?

**Comment by clason** [comment]
Usage questions should be asked on https://neovim.discourse.group; the issue tracker is for actual bugs!

**Comment by clason** [comment]
(You need to use the `settings` key for passing options to the server; the `filetypes` key is to indicate the file types (according to Neovim) to which the server should attach.)
