### ISSUE TITLE
emmet_ls single file support

### ISSUE THREAD

**Issue by RaafatTurki** [neovim/nvim-lspconfig#1570]
### Language server

emmet_ls

### Requested feature

I'm seeing all other language servers getting this and I figured it would be nice to have for this server as well.
in fact why is it bound to git root in the 1st place? emmet is more of a snippet engine than a language server.

**Comment by mjlbach** [comment]
these are all user contributed configurations, so you should test that emmet works with single_file_support = true, test it, and then file a PR.

**Comment by RaafatTurki** [comment]
well that looks cleaner than my
```lua
root_dir = function() return '.' end
```
and yes it works, PR incoming
