### ISSUE TITLE
Neovim errors out when there are two signs on the same line

### ISSUE THREAD

**Issue by ram02z** [neovim/nvim-lspconfig#1576]
### Description

I have only managed to replicate this behaviour using ESLint. The error doesn't happen when I comment out the lines with multiple signs.  The two signs are the error sign and the lightbulb sign from https://github.com/kosayoda/nvim-lightbulb.

I have attempted to disable the lightbulb module and even then the error persists but commenting out the line fixes the issue.

### Neovim version

NVIM v0.7.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

193a799861960c2505dceea4077da589ee954380

### Operating system and version

Linux 5.15.8_1 

### Affected language servers

ESLint (maybe others)

### Steps to reproduce

1. Launch ESLint file that has a code action and error on the same line
2. Error pops up

### Actual behavior

![image](https://user-images.githubusercontent.com/59267627/146280220-f3ceab64-e335-403e-8bdc-1ea58c4f7be9.png)

This is line 33:
```lua
  -- sanity check
  if start[2] < 0 or finish[1] < start[1] then return end
```

I simply changed it to the following. The error went away and the highlights were correct.
```lua
if not start[2] or start[2] < 0 or finish[1] < start[1] then return end
```

I am using custom diagnostic logic:
https://github.com/ram02z/dotfiles/blob/master/dot_config/nvim/lua/modules/diagnostic.lua
https://github.com/ram02z/dotfiles/blob/master/dot_config/nvim/plugin/40-autocommands.vim#L57-L62

However, disabling the custom diagnostic logic doesn't fix the error.

### Expected behavior

No error

### Minimal config

```Lua
Will try later, just wanted to post the issue before I forget

Here is the file I get the errors on for now:

// playwright.config.js
// @ts-check
import { devices } from "@playwright/test";

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  use: {
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"] },
    },
  ],
};

export default config;
```

### Health check

```
lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: html: configuration checked.
  - INFO: eslint: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: lean3ls: configuration checked.
  - INFO: pyright: configuration checked.
  - INFO: cssls: configuration checked.
```

### LSP log

https://gist.github.com/ram02z/b11a3bbd53211d0199a13b32ad1e7a81

**Comment by mjlbach** [comment]
Lspconfig does not implement the language server client in neovim. Please read the issue template.

**Comment by ram02z** [comment]
> Lspconfig does not implement the language server client in neovim. Please read the issue template.

Alright my bad. Im abit tired, should I report this to neovim or is this an eslint issue?

**Comment by mjlbach** [comment]
Probably both presuming you can rerpoduce without nvim-lightbulb with the minimal config. It's a flaw in the diagnostic subsystem not handling what I presume is a missing diagnostic range. You can file an issue in neovim.
