### ISSUE TITLE
`:LspRestart` throws error when using non-supported language server

### ISSUE THREAD

**Issue by jose-elias-alvarez** [neovim/nvim-lspconfig#1582]
### Description

When called without arguments in a buffer attached to a non-supported language server, `:LspRestart` throws the following error:
 
```
Error executing vim.schedule lua callback: .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:58: attempt to index a nil value
stack traceback:
        .../site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:58: in function ''
        vim.lua: in function ''
        vim.lua: in function <vim.lua:0>
```

### Neovim version

NVIM v0.7.0-dev+732-g80210c189

### Nvim-lspconfig version

64bd3b95345f2dbedc83a3d9a472662c48b3e940

### Operating system and version

macOS 12.1

### Affected language servers

All

### Steps to reproduce

1. `nvim --clean -u minimal_init.lua test.py`
2. `:LspRestart`

### Actual behavior

The error from the description is thrown.

### Expected behavior

No error is thrown.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
    local path_sep = on_windows and "\\" or "/"
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv("TEMP")
else
    temp_dir = "/tmp"
end

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
    require("packer").startup({
        {
            "wbthomason/packer.nvim",
            "neovim/nvim-lspconfig",
        },
        config = {
            package_root = package_root,
            compile_path = compile_path,
        },
    })
end

_G.attach_buffer = function()
    local client_id = vim.lsp.start_client({ cmd = { "pylsp" } }) -- cmd is irrelevant
    vim.lsp.buf_attach_client(vim.api.nvim_get_current_buf(), client_id)
end

_G.load_config = function()
    -- filetype is irrelevant but should be consistent with language server
    vim.cmd("autocmd FileType python lua attach_buffer()")
end

if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
    load_plugins()
    require("packer").sync()
    vim.cmd([[autocmd User PackerComplete ++once lua load_config()]])
else
    load_plugins()
    require("packer").sync()
    _G.load_config()
end
```

### Health check

```
lspconfig: require("lspconfig.health").check()
========================================================================
  - WARNING: Can't find any config.
```

### LSP log

Probably not relevant

**Comment by jose-elias-alvarez** [comment]
The following trivial patch fixes the issue as well as a related issue where a config is defined but `setup` has not yet been called, meaning that `launch` is not yet defined. I didn't yet submit a PR in case I'm missing something but am happy to do so if this is the right fix.

```diff
diff --git a/lua/lspconfig.lua b/lua/lspconfig.lua
index 8404632..685b166 100644
--- a/lua/lspconfig.lua
+++ b/lua/lspconfig.lua
@@ -54,9 +54,11 @@ function M._root._setup()
       function(cmd_args)
         for _, client in ipairs(M.util.get_clients_from_cmd_args(cmd_args)) do
           client.stop()
-          vim.defer_fn(function()
-            configs[client.name].launch()
-          end, 500)
+          if configs[client.name] and configs[client.name].launch then
+            vim.defer_fn(function()
+              configs[client.name].launch()
+            end, 500)
+          end
         end
       end,
       '-nargs=? -complete=customlist,v:lua.lsp_get_active_client_ids',
```

**Comment by mjlbach** [comment]
I think a cleaner "fix" would be to expose the table of client ids managed by lspconfig, and make these methods only restart those clients.

**Comment by jose-elias-alvarez** [comment]
Sure, that makes sense. Does this table already exist somewhere in the code, or is it something that would need to be created?

**Comment by kylo252** [comment]
> I think a cleaner "fix" would be to expose the table of client ids managed by lspconfig, and make these methods only restart those clients.

How about using the docs tag? or maybe add a special marker in the client config. Otherwise, how would you know which ones are managed? just because `tsserver` is active, doesn't mean it's managed by lspconfig.

**Comment by mjlbach** [comment]
Because lspconfig tracks internally which clients it starts... Please read the code and evaluate the solution I suggested before theorycrafting alternatives.

**Comment by jose-elias-alvarez** [comment]
I took another look, and I can see that the active client IDs are available via `manager.clients()`. Does something like this make sense?

```lua
local get_lspconfig_clients = function()
    local clients = {}
    for _, config in pairs(require("lspconfig.configs")) do
        if config.manager then
            vim.list_extend(clients, config.manager.clients())
        end
    end
    return clients
end
```

If so, using that [here](https://github.com/neovim/nvim-lspconfig/blob/c018b1e92e66b3429a2f167d59211846774f1e3b/lua/lspconfig/util.lua#L391) instead of `vim.lsp.get_active_clients()` would solve this specific issue.

**Comment by mjlbach** [comment]
Yup
