### ISSUE TITLE
Language server for grammar with word meanings

### ISSUE THREAD

**Issue by zim0369** [neovim/nvim-lspconfig#1587]
### Language server

no

### Requested feature

Grammarly is a writing tool. I was searching for something similar and ended up using `null-ls` plugin with `write_good`. I do not know if `write_good` is a language server or linter but it works well. It does not do much but
makes same kind of correction suggestions.

I would like a robust language serveZr. It should also show me the word meaning when it suggests me words and advanced grammar corrections.

### Other clients which have this feature

none

**Comment by mjlbach** [comment]
This isn't an issue, it doesn't belong on our issue tracker. I'll answer this once but please do not use the issue tracker as google.

`ltex-ls` is already available in lspconfig (see server_configurations.md and grammarly (see #1562) is PR'd.
