### ISSUE TITLE
Error attaching server when opening file via NetRW, dirvish...

### ISSUE THREAD

**Issue by d9d6ka** [neovim/nvim-lspconfig#1590]
### Description

I'm facing the same problem as #1524.
Proposed fixes #1525 and #1581 solve problem with setting filetype.
But the problem with opening files via NetRW, dirvish (and other tools maybe) is still there.

### Neovim version

NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 10 21H2

### Affected language servers

checked on sumneko_lua and pyright

### Steps to reproduce

1. open nvim
2. open NetRW or dirvish
3. Try to open any file with LSP-server installed

### Actual behavior

Обнаружена ошибка при обработке FileType Автокоманды для "lua":
E5108: Error executing lua ...oop\apps\neovim\0.6.0\share\nvim\runtime/lua/vim/lsp.lua:239: cmd_cwd: expected directory, got C:/Users/vadim/AppData/Local/nvim/init.lua
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        ...oop\apps\neovim\0.6.0\share\nvim\runtime/lua/vim/lsp.lua:239: in function 'validate_client_config'
        ...oop\apps\neovim\0.6.0\share\nvim\runtime/lua/vim/lsp.lua:688: in function 'start_client'
        ...\pack\packer\start\nvim-lspconfig/lua/lspconfig/util.lua:267: in function 'add'
        ...ck\packer\start\nvim-lspconfig/lua/lspconfig/configs.lua:221: in function 'try_add'
        [string ":lua"]:1: in main chunk
E5108: Error executing lua ...oop\apps\neovim\0.6.0\share\nvim\runtime/lua/vim/lsp.lua:239: cmd_cwd: expected directory, got C:/Users/vadim/AppData/Local/nvim/init.lua
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        ...oop\apps\neovim\0.6.0\share\nvim\runtime/lua/vim/lsp.lua:239: in function 'validate_client_config'
        ...oop\apps\neovim\0.6.0\share\nvim\runtime/lua/vim/lsp.lua:688: in function 'start_client'
        ...\pack\packer\start\nvim-lspconfig/lua/lspconfig/util.lua:267: in function 'add'
        ...ck\packer\start\nvim-lspconfig/lua/lspconfig/configs.lua:221: in function 'try_add'
        [string ":lua"]:1: in main chunk

### Expected behavior

Successfully attached LSP-server.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir
if on_windows then
  temp_dir = vim.loop.os_getenv 'TEMP'
else
  temp_dir = '/tmp'
end

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'pyright'
  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: pyright: configuration checked.
  - ERROR: hls: The given command "haskell-language-server-wrapper" is not executable.
  - INFO: sumneko_lua: configuration checked.

### LSP log

used minimal_init.lua

**Comment by mjlbach** [comment]
This is more of a general windows path handling issue than anything specific to netrw/dirvsih.
