### ISSUE TITLE
Plugin Errors on Load

### ISSUE THREAD

**Issue by SmashMineGame** [neovim/nvim-lspconfig#1600]
### Description

Whenever I load up nvim, I get an error from a file in the plugin.

### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

428f785c55996ac336534d299daac9209dd96e79

### Operating system and version

macOS 12.0.1

### Affected language servers

all

### Steps to reproduce

1. `nvim`

### Actual behavior

<img width="1433" alt="Screen Shot 2021-12-23 at 5 10 39 PM" src="https://user-images.githubusercontent.com/32280917/147304029-7c54220f-ec95-4baf-800a-b0a12c8ab517.png">

### Expected behavior

No error and just opening neovim.

### Minimal config

```Lua
no config necessary, it errors on load.
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - WARNING: Can't find any config.

### LSP log

no log due to plugin not loading at all

**Comment by mjlbach** [comment]
You need to reproduce with the minimal config. I cannot reproduce.

**Comment by mjlbach** [comment]
Feel free to open a new issue after reproducing with the minimal config (which ensures a clean installation of the lspconfig plugin). I can't reproduce in docker/a VM on windows/linux/mac.

**Comment by SmashMineGame** [comment]
While reproducing with the minimal config, I somehow managed to get it working again. I'm not sure what the issue I had before was but all of the lsp functionality is working correctly now.
