### ISSUE TITLE
LSP is configured to only attach to "c" filetypes, yet .h files are detected as type "cpp"

### ISSUE THREAD

**Issue by leitdeux** [neovim/nvim-lspconfig#1601]
### Description

When I open an .h file (i.e. C header), `clangd` does not attach because it unexpectedly detects the filetype as `cpp` instead of `c`. Though in my lspconfig config I have explicitly set the "filetypes" field to only attach to "c" files, it will detect the .h file as "cpp".

Note: `clangd` does correctly detect .c files and attaches as expected. Also, I do have a `compile_flags.txt` file in my project root directory as well as `.clangd`, which specify that the project files should be compiled as C99:

compile_flags.txt:
```
-xc
-I
myProjectHeaders
```

.clangd:
```
CompileFlags:
  Add: [-std=c99]
```

### Neovim version

NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

428f785c55996ac336534d299daac9209dd96e79

### Operating system and version

macOS 12.0.1

### Affected language servers

clangd (v13.0.0)

### Steps to reproduce

1. Setup minimal config for clangd, setting the `filetypes` field to `{ "c" }`
2. nvim someHeader.h

### Actual behavior

Once having opened an .h file, typing `:LspInfo` will claim that the file is of filetype `cpp` and that `clangd` has not attached.

### Expected behavior

The LSP should recognize the .h file as a filetype of `c` and attach accordingly.

### Minimal config

```Lua
local nvim_lsp = require("lspconfig")

nvim_lsp.clangd.setup {
  filetypes = { "c" },
  cmd = {
    "clangd",
    "--background-index",
    "--header-insertion=never",
    "--completion-style=detailed",
  }
}
```

### Health check

lspconfig: require("lspconfig.health").check()
========================================================================
  - INFO: clangd: configuration checked.

### LSP log

No log appears, since clangd doesn't attach

**Comment by mjlbach** [comment]
The "LSP" does not recognize filetypes. That is the job of vim, specifically here: https://github.com/mjlbach/neovim/blob/0d7a97224f28cdf47d7ecc80b6d300c8c67c0b29/runtime/autoload/dist/ft.vim#L110-L124

You can see the rules are extremely naive. You can set `vim.g.c_syntax_for_h = true` if you would like, which will `set ft = c` for header files.

**Comment by leitdeux** [comment]
Thanks for the generous reply and explanation. I set  `vim.g.c_syntax_for_h = true` as you suggested and clangd is now attaching to the file as expected. Thanks again for taking the time to answer my question and happy holidays!

**Comment by mjlbach** [comment]
No worries :) I do agree it's not intuitive behavior. I'm not sure what the alternative would be (for the neovim's filetype plugins), I guess it could scan the parent directory of the header for c/cpp files with matching names.

**Comment by DavidePatria** [comment]
In my case the trick doesn't seem to quite solve the issue. this is most likely clangd fault, but has been described here isn't enough in my case.

I have a problem with a `.h` file which is recognised has a cpp file, therefore I get some strange errors when using `complex.h`

![immagine](https://user-images.githubusercontent.com/28001136/149654730-d01cf408-1e0a-4da3-b60c-e08c55148971.png)

The thing is that I without `vim.g.c_syntax_for_h = true` using `:LspInfo` shows

![immagine](https://user-images.githubusercontent.com/28001136/149654787-5976d042-1c72-4d50-a6a7-8f0d8e50e0a6.png)

when using the option instead 

![immagine](https://user-images.githubusercontent.com/28001136/149654831-12b35403-7547-4c0a-8f7b-06c4a6522b24.png)

and the errors are still present in both cases. 
changing the extension to `.c` works fine.
