### ISSUE TITLE
How to setup clangd so that it can recognize C++20 keyword, like `consteval`?

### ISSUE THREAD

**Issue by nyngwang** [neovim/nvim-lspconfig#1602]
### Language server

clangd

### Requested feature

as title.

**Comment by mjlbach** [comment]
The issue tracker is for bug reports. This usage question belongs on our discourse.

**Comment by nyngwang** [comment]
@mjlbach Yes I did post it there but no one is interested in my question, https://neovim.discourse.group/t/how-to-setup-clangd-for-c-20/1744, __And I cannot upload image there :/__

**Comment by mjlbach** [comment]
You posted it 2 hours ago, give it time.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/how-to-setup-clangd-for-c-20/1744/1

**Comment by mjlbach** [comment]
Apparently time ~= 30 seconds after I posted that :) zeertzjq's answer is correct.

**Comment by nyngwang** [comment]
@mjlbach Thanks for you and him!

**Comment by Anonym234** [comment]
what version of `clangd` are you using ?

**Comment by nyngwang** [comment]
@jackywu Neovim with [this](https://github.com/AlessandroYorba/Alduin) colorscheme. Or if you would mean the terminal emulator that's Alacritty with tmux.
