### ISSUE TITLE
config parameter is a nil value

### ISSUE THREAD

**Issue by ruanyouxing** [neovim/nvim-lspconfig#1609]
### Description

nvim-lspconfig/lua/lspconfig/configs.lua:35: attempt to index local 'config' (a nil value)

after that bug, LSP started normally
If I open a .lua file, it shows "Client 1 exited with return code 1 and signal 0" 

### Neovim version

0.6.0

### Operating system and version

Arch Linux

### Affected language servers

all

### Steps to reproduce

require('lspconfig').sumenko_lua.setup()

### Actual behavior

nvim-lspconfig/lua/lspconfig/configs.lua:35: attempt to index local 'config' (a nil value)

### Expected behavior

It started without errors

### Minimal config

```Lua
require('lspconfig').sumneko_lua.setup()
```

### Health check

good

### LSP log

none

**Comment by mjlbach** [comment]
You need to call setup with `{}` not `()`, the former is an empty table.

**Comment by ruanyouxing** [comment]
but when i called it again and it shows "Client 0 exited with exit code 1 and signal 0" despite i typed the syntax correctly

**Comment by mjlbach** [comment]
That's a separate issue, your server is crashing. It's likely a server installation issue. You would need to post on our discourse with more details.
