### ISSUE TITLE
The ^M character appears when I format the file - Windows 11

### ISSUE THREAD

**Issue by maxmx03** [neovim/nvim-lspconfig#1621]
### Description

When I use the language server format the ^M character appears at the end of the line, I've tried some solutions as shown below and it still didn't work

![Captura de tela 2021-12-29 150712](https://user-images.githubusercontent.com/50273941/147692311-841d986f-1c9f-4ac9-9419-c37c44be06ba.png)

![Captura de tela 2021-12-29 150636](https://user-images.githubusercontent.com/50273941/147692318-cbef107d-d3e2-47e1-acc8-7b1316e76b1c.png)

![Captura de tela 2021-12-29 150833](https://user-images.githubusercontent.com/50273941/147692323-46ba789b-2101-409b-a1ec-5c1086d34248.png)

### Neovim version

NVIM v0.7.0-dev+761-g0d7a97224
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

commit 5b8bea1b7177d7ced74bb0fd501cbe682f13b370 (HEAD -> master, origin/master, origin/HEAD)

### Operating system and version

Windows 11

### Affected language servers

vue, js, php etc...

### Steps to reproduce

format on save

### Actual behavior

When i format on save using the language server formatter appear the ^M character.

### Minimal config

```Lua
https://github.com/maxmx03/dotfiles/tree/main/.config/nvim-windows
```

### Health check

```lua
  
   lspconfig: require("lspconfig.health").check()
   ========================================================================
    - INFO: html: configuration checked.
    - INFO: pyright: configuration checked.
    - INFO: tsserver: configuration checked.
    - INFO: sumneko_lua: configuration checked.
    - INFO: cssls: configuration checked.
    - INFO: jsonls: configuration checked.
    - INFO: eslint: configuration checked.
    - INFO: intelephense: configuration checked.
    - INFO: vuels: configuration checked.
```

### LSP log

https://gist.github.com/maxmx03/2d1b697c803b68a37045257b00a592c8

**Comment by mjlbach** [comment]
This isn't implemented in lspconfig. You can file an issue against neovim core.

**Comment by maxmx03** [comment]
> This isn't implemented in lspconfig (see, the issue template and README.md). You can file an issue against neovim core.

But when i use https://github.com/mhartington/formatter.nvim everything works fine.

**Comment by mjlbach** [comment]
Like I said, lspconfig is not a language server client. Neovim has a language server client. This plugin is not that.

**Comment by maxmx03** [comment]
solution

```lua
vim.api.nvim_command [[ set ff=unix ]] 
```

**Comment by tristone13th** [comment]
> ```lua
> vim.api.nvim_command [[ set ff=unix ]] 
> ```

doesn't work for me.

**Comment by mjlbach** [comment]
You shouldn't force the encoding. The client is supposed to account for different line endings. Someone send me a minimal reproduction with our minimal init.lua and an example file to be formatted and I'll look at this on windows next time I have access to a windows computer. This isn't an lspconfig bug though.

**Comment by SuperCuber** [comment]
> You shouldn't force the encoding. The client is supposed to account for different line endings. Someone send me a minimal reproduction with our minimal init.lua and an example file to be formatted and I'll look at this on windows next time I have access to a windows computer. This isn't an lspconfig bug though.

Making sure you're notified since you asked: https://github.com/neovim/neovim/issues/17053

**Comment by maxmx03** [comment]
> 



> > ```lua
> > vim.api.nvim_command [[ set ff=unix ]] 
> > ```
> 
> doesn't work for me.

here my [dotfiles](https://github.com/maxmx03/dotfiles), you can see my solution here: dotfiles/.config/nvim-windows/after/plugin/lspconfig.rc.lua.
