### ISSUE TITLE
Feature: Add support for solc's brand new LSP

### ISSUE THREAD

**Issue by OliverNChalk** [neovim/nvim-lspconfig#1622]
### Language server

solc

### Requested feature

**Which server would you like to request to be added?**

-   Server name: `solc` LSP
-   Server homepage (e.g., GitHub page): https://github.com/ethereum/solidity/releases/tag/v0.8.11

**Which languages does this server target?**

-   Languages: `solidity`

**How is this server distributed?**

-   Is the server distributed through a standardized channel (such as release files, npm, pip, etc.)? (leave empty if unknown): there are [js bindings](https://github.com/ethereum/solc-js) but that introduces overhead. If possible it'd be preferable to pull a system-dependent release from their github releases channel.

**Comment by mjlbach** [comment]
This was added in #1623
