### ISSUE TITLE
Java does not recognize classes or files from the same package

### ISSUE THREAD

**Issue by JjersaR** [neovim/nvim-lspconfig#1647]
### Description

I started using all the configuration of lsp for tasks, c++, python and java, but in java I can not have "organized" classes in different files, I have everything in a file to run, I tried to import the path of the files, and it does not work, with the path that gives me the same autocomplete package.archive; and nothing works, I don't know if it's my mistakes or something really happens.

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

### Operating system and version

Arch Linux 5.15.13-arch1-1 

### Affected language servers

Jdtls

### Steps to reproduce

├── src
│   ├── dominio
│   │   └── Persona.java
│   └── test
│       └── PersonaPrueba.java
if you use this line in the PersonaPrueba.java (import dominio.Persona;), give this error:
[error](https://imgur.com/a/6tZ5EbP)

### Actual behavior

[error](https://imgur.com/a/6tZ5EbP)

### Expected behavior

[this is expected](https://imgur.com/a/SYwmie6)

### Minimal config

```Lua
https://youtu.be/94IU4cBdhfM
```

### LSP log

Using the video configuration should work on the first try.

**Comment by mjlbach** [comment]
A youtube video is not a minimal config. If you want support for a specific server, you can ask on their support channels or on our discourse. Many servers require specific project files, etc., to provide diagnostics (see compile_commands.json for C).
