### ISSUE TITLE
I found a qml languageserver

### ISSUE THREAD

**Issue by chen244** [neovim/nvim-lspconfig#1650]
### Language server

qml

### Requested feature

https://invent.kde.org/cblack/qew-em-el-el-ess-pee

If it can be used? A qml languageserver

**Comment by mjlbach** [comment]
`:help lspconfig-adding-servers`

**Comment by wlh320** [comment]
For people who reached this page when searching for how to add a custom server without fork and PR, `:help lspconfig-adding-servers` has been renamed to `:help lspconfig-new` in [this commit](https://github.com/neovim/nvim-lspconfig/commit/4f94bf5ba90e97a9718e5a2eb57b0737e1bdd176).
