### ISSUE TITLE
Error executing luv callback on editing file with curl request

### ISSUE THREAD

**Issue by f-squirrel** [neovim/nvim-lspconfig#1653]
### Description

Lua server is trying to execute a curl request in a markdown file while editing the file.

### Neovim version

```
nvim --version
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az65-618

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info
```

### Nvim-lspconfig version

c7081e00fa8100ee099c16e375f3e5e838cbf1db 

### Operating system and version

Ubuntu 20.04

### Affected language servers

grammarly

### Steps to reproduce

The problematic file `test.md`:
```
curl "https://some_api.io/submit" \
  -X POST \
  -H "Content-Type: application/json" \
  --data-binary @./data
```
1. Open it in neovim
2. Press O to add a line

### Actual behavior

Error message:
```
Error executing luv callback:
...unt_vimIFYOQR/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:556: cannot resume dead coroutine
stack traceback:
        [C]: in function 'request_parser'
        ...unt_vimIFYOQR/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:556: in function <...unt_vim
IFYOQR/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:545>
```

### Expected behavior

I do not expect neovim lsp to try to execute a request in the file.

### Minimal config

```Lua
The issue is not reproducible with the default configuration.
This is the link to my init.vim
https://github.com/f-squirrel/scripts/blob/master/dotfiles/vim/init.vim
```

### LSP log

https://gist.github.com/f-squirrel/59e2106b1a1934ed8b2bba2c4c40b80a

**Comment by mjlbach** [comment]
These are *server* requests to the client, report the bug to the upstream repo.

**Comment by f-squirrel** [comment]
@mjlbach , thank you for the quick reply, do you mean the lsp server, i.e. `grammarly` ?

**Comment by mjlbach** [comment]
It's a bug in the wrapper, at first glance it seems to crash on an unanswered request which is off-spec 

The repo is here: https://github.com/emacs-grammarly/unofficial-grammarly-language-server

**Comment by jdhao** [comment]
Same issue here with a slightly different error message:

> Error executing luv callback:
.../tools/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:559: .../tools/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:74: invalid header line "content/test.md\
Content-Length: 46"
stack traceback:
        [C]: in function 'request_parser'
        .../tools/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:559: in function <.../tools/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:548>

It seems that if I put markdown file under a directory where `content` is part of the pathname, I will see this error.
