### ISSUE TITLE
Optimize default root_dir and on_new_config

### ISSUE THREAD

**Issue by MikaelElkiaer** [neovim/nvim-lspconfig#1658]
### Language server

omnisharp

### Requested feature

In case of having multiple sln files, lsp will start a language server for each. In my case I have a repo with a sln, as well as a submodule with a sln.

I currently circumvent this by changing `root_dir` in my config:
```lua
root_dir = function(fname)
    return vim.fn.getcwd()
end
```
However, I'm sure there's a better approach, and that this one has its issues.

Another interesting issue I discovered was that `:LspRestart` resulted in appending the same `-s ROOT_PATH` to the omnisharp command. It doesn't seem to have any practical effect, but perhaps the `on_new_config` can be optimized as well in this regard.

Keep up the good work!

**Comment by askfiy** [comment]
some

**Comment by KiLLeRRaT** [comment]
In my case if I have multiple sln files in my current working directory, I just get nothing.  I get no completion etc.
