### ISSUE TITLE
BufDelete doesn't detach the buffer from the LSP client

### ISSUE THREAD

**Issue by entropitor** [neovim/nvim-lspconfig#1659]
### Neovim version (nvim -v)

v0.7.0-dev+nightly-1466-g08616571f

### Language server name/version

any

### Operating system/version

MacOS

### Steps to reproduce using "nvim -u minimal_init.lua"

Open a buffer
Delete the buffer
:LspInfo

-> Buffer is still attached to the client

### Expected behavior

After deleting the buffer, the buffer should also be detached from the client

This seems to do the trick but I expect this to be in neovim core:
```lua
function DetachBufferFromClients(bufnr)
  local clients = vim.lsp.buf_get_clients(bufnr)
  for client_id, _ in pairs(clients) do
    vim.lsp.buf_detach_client(bufnr, client_id)
  end
end
autocmd BufDelete <buffer> lua DetachBufferFromClients(tonumber(vim.fn.expand("<abuf>")))
```

### Actual behavior

It doesn't detach the buffer from the client on BufDelete

**Comment by glepnir** [comment]
@entropitor  does this problem still exists?

**Comment by entropitor** [comment]
@glepnir yes, this issue still exists for me

**Comment by glepnir** [comment]
I can reproduce with an error throw out.

**Comment by glepnir** [comment]
closed. open in https://github.com/neovim/neovim/issues/20025

**Comment by entropitor** [comment]
For me, the work-around works just fine (not erroring). The problem I was raising was that I'd expect it to be part of this repo / neovim-core. Not something every user would have to do themselves...

**Comment by glepnir** [comment]
@entropitor  right . it not remove the buffer from on_detach callback.

**Comment by glepnir** [comment]
on my test both not work 

```vim
set rtp+=~/Workspace/nvim-lspconfig/

lua << EOF
local lspconfig = require('lspconfig')
lspconfig.sumneko_lua.setup{}

function DetachBufferFromClients(bufnr)
  local clients = vim.lsp.buf_get_clients(bufnr)
  for client_id, _ in pairs(clients) do
    vim.lsp.buf_detach_client(bufnr, client_id)
  end
end
EOF

autocmd LspAttach * autocmd BufDelete <buffer> lua DetachBufferFromClients(tonumber(vim.fn.expand("<abuf>")))
```

```lua
vim.opt.runtimepath:append('~/Workspace/nvim-lspconfig/')

local lspconfig = require('lspconfig')
lspconfig.sumneko_lua.setup{}
lspconfig.tsserver.setup{}

vim.api.nvim_create_autocmd('LspAttach',{
  callback = function()
    vim.api.nvim_create_autocmd('BufDelete',{
      buffer = vim.api.nvim_get_current_buf(),
      callback = function(opts)
        local bufnr = opts.buf
        local clients = vim.lsp.buf_get_clients(bufnr)
        for client_id, _ in pairs(clients) do
          vim.lsp.buf_detach_client(bufnr, client_id)
        end
      end
    })
  end

})

```

**Comment by entropitor** [comment]
I have the following snippet in my local config and that seems to remove the buffer just fine (according to `:LspInfo`)

```lua
local lspconfig = require('lspconfig')

local function buffer_augroup(group, bufnr, cmds)
  vim.api.nvim_create_augroup(group, { clear = false })
  vim.api.nvim_clear_autocmds({ group = group, buffer = bufnr })
  for _, cmd in ipairs(cmds) do
    local event = cmd.event
    cmd.event = nil
    vim.api.nvim_create_autocmd(event, vim.tbl_extend("keep", { group = group, buffer = bufnr }, cmd))
  end
end

local function on_attach(client, bufnr)
  local detach = function()
    vim.lsp.buf_detach_client(bufnr, client.id)
  end
  buffer_augroup("entropitor:lsp:closing", bufnr, {
    { event = "BufDelete", callback = detach },
  })
end

lspconfig.sumneko_lua.setup{on_attach=on_attach}
```

**Comment by glepnir** [comment]
print current buffer lsp client check the attach buffer after `:bd` . does buffer still exists?
`:lua=print(vim.inspect(vim.lsp.get_active_clients()))`

**Comment by entropitor** [comment]
But the issue remains that we need some code, right? I created this original issue as I don't think everyone should be adding this but it should be part of the core LSP implementation

**Comment by glepnir** [comment]
yup .I will add this support .

**Comment by doronbehar** [comment]
I got something working at https://github.com/neovim/nvim-lspconfig/issues/2626#issuecomment-2117022664 .
