### ISSUE TITLE
golangci-lint lsp defaults to `enable-all`, ignoring a project's configuration file

### ISSUE THREAD

**Issue by jzelinskie** [neovim/nvim-lspconfig#1661]
### Description

The default command for this language server ignores any project-level configuration in the `.golangci.yaml` file and instead explicitly runs all linters.

https://github.com/neovim/nvim-lspconfig/blob/89eda6c9ba3ded27ecd38dfcee811c11c91eae05/lua/lspconfig/server_configurations/golangci_lint_ls.lua#L8

I think this command could just be reduced to the following

```lua
command = { 'golangci-lint', 'run', '--out-format', 'json' },
```

I'm not sure if this is intended behavior, but it seems like a more sane default to use the golangci-lint defaults rather than forcing all linters.

### Neovim version

N/A

### Nvim-lspconfig version

89eda6c9ba3ded27ecd38dfcee811c11c91eae05

### Operating system and version

N/A

### Affected language servers

golangci_lint_ls

### Steps to reproduce

1. Install nvim-lspconfig
2. Enable golangci-lint lsp without overriding any default configuration
3. Open any file in Go project with a `.golangci.yaml` and see that the configuration is ignored

### Actual behavior

Linting errors from all linters appear in the editor

### Expected behavior

Only linting errors should appear in the editor that are configured in `golangci.yaml`

### Minimal config

```Lua
N/A
```

### LSP log

N/A

**Comment by mjlbach** [comment]
All configuration are community contributed, so PR welcome :)
