### ISSUE TITLE
Vue "vetur.experimental.templateInterpolationService" seems to be not working

### ISSUE THREAD

**Issue by eckon** [neovim/nvim-lspconfig#1663]
### Description

When setting the experimental option for the "templateInterpolationService" in vetur, nothing is happening.

Sadly I am not sure if this problem is relevant to this repository or another, because the feature works in VSCode (meaning it should not be for vetur) but it does not work for me in neovim.

I tried different ways of setting this option:
- `vetur.config.js`
- in setup of lspinstall
- in setup of lspconfig
- with init_options
  - `opts.init_options = {config = {vetur = { experimental = { templateInterpolationService = true }}}}`
- with settings
  - `opts.settings = {vetur = { experimental = { templateInterpolationService = true }}}`

Next to neovim I also used the `vetur.config.js` (and also direct option) in VSCode which both worked.

### Example of my setup (with flag):

No completion in template
![image](https://user-images.githubusercontent.com/40291209/149792005-0c676792-aaea-4ac6-abf1-b7475467a667.png)

No definition jump / diagnostics in template
![image](https://user-images.githubusercontent.com/40291209/149792150-16fda68e-6053-470f-a954-db0e14d7954b.png)

### Comparison to the same settings in VSCode:

Completion in template
![image](https://user-images.githubusercontent.com/40291209/149792437-d14971d9-0998-4ab3-9cc2-6a34a8c92d62.png)

Definition jump / diagnostics in template
![image](https://user-images.githubusercontent.com/40291209/149792573-9a507ad0-904d-4555-8ebf-f6884319f7d4.png)

### Neovim version

NVIM v0.7.0-dev+755-g1062ea2cc
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Pop!_OS 21.10

### Affected language servers

vuels

### Steps to reproduce

1. use vuels lsp
2. configure it to use the `vetur.experimental.templateInterpolationService` option
3. try editing a vue file

### Actual behavior

No code jumps / diagnostics / completion available

### Expected behavior

Code jumps / diagnostics / completion available

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'vuels'
  local cmd = {'vls'} -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
    settings = {
      vetur = {
        experimental = {
          templateInterpolationService = true
        }
      }
    }
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

minimal config given

**Comment by gegoune** [comment]
Try:
```lua
    init_options = {
      config = {
        vetur = {
          experimental = {
            templateInterpolationService = true,
          },
        },
      },
    },
```

**Comment by eckon** [comment]
@gegoune I already tried `init_options` but I just tried it again, to be sure:

```lua
require'lspconfig'.vuels.setup({
    capabilities = cmp_capabilities,
    init_options = {
      config = {
        vetur = {
          experimental = {
            templateInterpolationService = true,
          },
        },
      },
    },
})
```

Sadly it did not do anything else, so when opening another project, I still do not have any completions etc:

![image](https://user-images.githubusercontent.com/40291209/149796263-12035832-6e59-4fc0-af4f-b630da7d3fba.png)

it just uses the text in the buffer sadly.

**Comment by mjlbach** [comment]
Nothing we can do, you can file a bug upstream.

This blog post on the implementation might be useful https://blog.matsu.io/generic-vue-template-interpolation-language-features.
