### ISSUE TITLE
clangd

### ISSUE THREAD

**Issue by MyBlackHole** [neovim/nvim-lspconfig#1668]
### Description

[ERROR][2022-01-18 17:23:51] .../vim/lsp/rpc.lua:420    "rpc"   "clangd"        "stderr"        "I[17:23:51.203] --> reply:textDocument/documentHighlight(280) 1 ms\n"

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Operating System: Ubuntu 21.10           Kernel: Linux 5.13.0-25-generic     Architecture: x86-64  Hardware Vendor: Gigabyte Technology Co., Ltd.

### Affected language servers

clangd

### Steps to reproduce

#include "DuLinkList.h"
Status ListEmpty(DuLinkList L);

DuLinkList.c
Status ListEmpty(DuLinkList L) {
  if (L != NULL && L->next == L && L->prior == L) {
    return TRUE;
  } else {
    return FALSE;
  }
}

#include "SLinkList.h"
Status ListEmpty(SLinkList space, int S);

SLinkList.c
Status ListEmpty(SLinkList space, int S) {
  if (S != 0 && space[S].cur == 0) {
    return TRUE;
  } else {
    return FALSE;
  }
}

compile_commands.json
  {
    "directory": "/media/black/Data/Documents/Code/C/C_learn/out",
    "command": "gcc -MMD -MF obj/DataStruct_learn/List/DuLinkList/libDuLinkList.DuLinkList.o.d  -I../DataStruct_learn/Status   -c ../DataStruct_learn/List/DuLinkList/DuLinkList.c -o obj/DataStruct_learn/List/DuLinkList/libDuLinkList.DuLinkList.o",
    "file": "../DataStruct_learn/List/DuLinkList/DuLinkList.c",
    "output": "obj/DataStruct_learn/List/DuLinkList/libDuLinkList.DuLinkList.o"
  },
  {
    "directory": "/media/black/Data/Documents/Code/C/C_learn/out",
    "command": "gcc -MMD -MF obj/DataStruct_learn/List/DuLinkList/DuLinkList-main.DuLinkList-main.o.d  -I../DataStruct_learn/Status   -c ../DataStruct_learn/List/DuLinkList/DuLinkList-main.c -o obj/DataStruct_learn/List/DuLinkList/DuLinkList-main.DuLinkList-main.o",
    "file": "../DataStruct_learn/List/DuLinkList/DuLinkList-main.c",
    "output": "obj/DataStruct_learn/List/DuLinkList/DuLinkList-main.DuLinkList-main.o"
  },

main.c
#include "DuLinkList.h"
ListEmpty(xxxx) (lua vim.lsp.buf.definition() get to SLinkList.c::ListEmpty )

### Actual behavior

There is a C function with the same name that the jump is abnormal

### Expected behavior

ListEmpty(xxxx) (lua vim.lsp.buf.definition() get to DuLinkList.c::ListEmpty )

### Minimal config

```Lua
No configuration is added, the default is used , lvim
```

### LSP log

https://gist.github.com/MyBlackHole/d94ca8c4fb5a62e14f7f7bebe2e58c53

**Comment by rollschild** [comment]
Hi @MyBlackHole  I'm having the same error. Did you by any chance solve/fix this issue? I'm curious. Thanks!

**Comment by MyBlackHole** [comment]
> 

At present, it is only for project separation

**Comment by MyBlackHole** [comment]
@rollschild maybe you can separate him
