### ISSUE TITLE
[utils] path bug on Windows

### ISSUE THREAD

**Issue by Lopi-py** [neovim/nvim-lspconfig#1684]
### Description

`require("lspconfig.util").path.dirname()` seems to fail on windows, `dirname()` is not handling `\\` on Windows.

### Neovim version

NVIM v0.7.0-dev+922-g1b6ae2dbb
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

c51096481dc13193991571b7132740d762902355

### Operating system and version

Windows 10

### Affected language servers

all (I guess)

### Steps to reproduce

`nvim .`
`:lua print(require("lspconfig.util").path.dirname(vim.fn.stdpath("config") .. "\\init.lua"))`

### Actual behavior

`C:\Users\HP\AppData\Local\nvim\init.lua`

### Expected behavior

`C:\Users\HP\AppData\Local\nvim`

### Minimal config

```Lua
N/A
```

### LSP log

N/A

**Comment by mjlbach** [comment]
This isn't a bug, you need to call the normalize function first. Our path utilities always assume forward delineated paths now.
