### ISSUE TITLE
Hover + SignatureHelp Transparent Background

### ISSUE THREAD

**Issue by axieax** [neovim/nvim-lspconfig#1690]
### Requested feature

Hi,
Not too sure if it's possible to customise pseudo-transparency of the ["textDocument/hover"] and ["textDocument/signatureHelp"] floating windows from the [UI-Customization Wiki](https://github.com/neovim/nvim-lspconfig/wiki/UI-Customization). 

I'm currently using a transparent Neovim background, with borders configured as per the Wiki's instructions. Here is what I have so far:

![image](https://user-images.githubusercontent.com/62098008/151655176-7c330e43-2a9f-47f5-b4de-167d16bd7af1.png)

I want to achieve something like in the image below, which is possible with [lsp_signature.nvim](https://github.com/ray-x/lsp_signature.nvim), featuring a transparency value of 20. From the source code, it seems like setting the `winblend` value may be what is required, but I'm not sure if there even is a way to set this externally. 

![image](https://user-images.githubusercontent.com/62098008/151655198-2825dd88-aa11-4a85-80d0-e789056dd5bd.png)

**Comment by mjlbach** [comment]
Usage questions belong on our discourse https://neovim.discourse.group/c/language-server-protocol-lsp/7

> it seems like setting the winblend value may be what is required, but I'm not sure if there even is a way to set this externally.?

Not sure what you mean by externally. `vim.opt.winblend = 10`

**Comment by axieax** [comment]
By externally, I meant being able to configure it without changing the source code manually (i.e. from available API's). AFAIK, this is not possible, which makes this a feature request, rather than a usage question.

**Comment by mjlbach** [comment]
it's a usage question.

```lua
local handlers = {
  ['textDocument/hover'] = function(...)
    local buf, winnr = vim.lsp.handlers.hover(...)
    if buf then
      vim.api.nvim_buf_set_keymap(buf, 'n', 'K', '<Cmd>wincmd p<CR>', { noremap = true, silent = true })
      vim.api.nvim_win_set_option(winnr, "winblend", 90)
    end
  end,
}

local servers = {
  'rust_analyzer',
}
for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    handlers = handlers,
  }
end
```

I wish you had asked on discourse like I requested.

**Comment by axieax** [comment]
Apologies for the confusion and thanks for your quick response and help! I assumed this repo was concerned with UI customisations since the Wiki discusses this in depth, my bad :(

**Comment by mjlbach** [comment]
I only added the wiki because people were asking UI/customization questions in the issue tracker :)
