### ISSUE TITLE
Solhint linting for solidity files

### ISSUE THREAD

**Issue by pmdaly** [neovim/nvim-lspconfig#1694]
### Requested feature

The standard for linting Solidity files is solhint, which is currently not available as an lsp.

https://github.com/protofire/solhint

I'd be happy to add this feature I would just need some help.  I have a rough config but I don't think solhint works in the same way eslint does for example (based the config on it).  

```lua
 local util = require'lspconfig.util'

local bin_name = 'solhint'
if vim.fn.has 'win32' == 1 then
  bin_name = bin_name .. '.cmd'
end

return {
  default_config = {
    cmd = { bin_name, 'stdin' },
    filetypes = { 'solidity' },
    root_dir = util.root_pattern('.git', 'package.json'),
  },
  docs = {
    description = [[
npm install -g solhint
solhint is a linting utility for solidity
]],
    default_config = {
      root_dir = [[root_pattern(".git", "package.json")]],
    },
  },
}
```

**Comment by mjlbach** [comment]
As far as I understand, solhint is a linter, not a language server. You could consider adding this to [nvim-lint](https://github.com/mfussenegger/nvim-lint)

**Comment by pmdaly** [comment]
ESLint is a linter as well but is included b/c it's also an lsp? I don't understand this.

**Comment by mjlbach** [comment]
What's included is the language server provided by [vscode-lint](https://github.com/Microsoft/vscode-eslint). `solhint` does not implement the language server protocol, you can't open a daemon and communicate over `json-rpc`. Likewise, why we support [solidity language server](https://github.com/neovim/nvim-lspconfig/blob/66b8702ffc3f6be6f317bee0a022a79cab14b09d/lua/lspconfig/server_configurations/solidity_ls.lua) but not solhint.
