### ISSUE TITLE
Error executing lua - filename: expected string, got nil

### ISSUE THREAD

**Issue by briankosw** [neovim/nvim-lspconfig#1697]
### Description

I'm having trouble setting `pyright`. I've read through dozens of issues in this repo trying to debug this problem, but most of the issues are concerned with neovim not being on the latest version - my neovim is up to date.

### Neovim version

NVIM v0.6.0-dev+132-g7d2233fad
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 10.15.7

### Affected language servers

pyright

### Steps to reproduce

1. Install `neovim/nvim-lspconfig` as a neovim plugin using `vim-plug`
2. Install `pyright`: npm i -g pyright`
3. Add [suggested configuration](https://github.com/neovim/nvim-lspconfig#suggested-configuration)

I even modified the suggested configuration by changing autorestart to `false` and manually started the `pyright` config by running `:LspStart pyright`.

### Actual behavior

This is the error message I receive:
```
Error detected while processing FileType Autocommands for "python":
E5108: Error executing lua ...r/neovim/HEAD-7d2233f/share/nvim/runtime/lua/vim/lsp.lua:97: filename: expected string, got nil
stack traceback:
        ...r/neovim/HEAD-7d2233f/share/nvim/runtime/lua/vim/lsp.lua:97: in function 't'
        vim/shared.lua:547: in function 'is_valid'
        vim/shared.lua:565: in function 'validate'
        ...r/neovim/HEAD-7d2233f/share/nvim/runtime/lua/vim/lsp.lua:220: in function 'validate_client_config'
        ...r/neovim/HEAD-7d2233f/share/nvim/runtime/lua/vim/lsp.lua:640: in function 'start_client'
        ...share/nvim/plugged/nvim-lspconfig/lua/lspconfig/util.lua:278: in function 'add'
        ...re/nvim/plugged/nvim-lspconfig/lua/lspconfig/configs.lua:239: in function 'try_add'
        [string ":lua"]:1: in main chunk
```

This is what I get when I run `:LspInfo`:
```
Language client log: $HOME/.cache/nvim/lsp.log
Detected filetype:   python

0 client(s) attached to this buffer:

Other clients that match the filetype: python

Config: pyright
filetypes:         python
root directory:    NA
cmd:               pyright-langserver --stdio
cmd is executable: true
autostart:         true
custom handlers:
Configured servers list: pyright
```

### Expected behavior

Expected pyright to correctly run.

### Minimal config

```Lua
Error detected while processing $HOME/.nvim/init.vim:
line    7:
E5108: Error executing lua ./minimal_init.lua:35: attempt to call field 'set_format_func' (a nil val
ue)
```

### LSP log

https://gist.github.com/briankosw/50696f5fe346910264c6e2fb081fd916#file-lsp-log

**Comment by mjlbach** [comment]
`NVIM v0.6.0-dev+132-g7d2233fad` is not up to date.
