### ISSUE TITLE
Add highlight group in README

### ISSUE THREAD

**Issue by tristone13th** [neovim/nvim-lspconfig#1699]
### Requested feature

It's really difficult to find the highlight groups of this plugin, so it's better to add them to the README file for customization.

**Comment by mjlbach** [comment]
....what highlight groups.

**Comment by tristone13th** [comment]
> ....what highlight groups.

For example, the border of the floating window, the front and back color of the text... I think all the highlight groups used in this plugin should be clarified.

**Comment by mjlbach** [comment]
`lspconfig` only opens a single floating window, which is the exact same as every other floating window in neovim. There are no custom highlight groups.

**Comment by tristone13th** [comment]
> `lspconfig` only opens a single floating window (for `:LspInfo`), which is the exact same as every other floating window in neovim. There are no custom highlight groups.

Got it, does the floating window has a border?

**Comment by mjlbach** [comment]
no
