### ISSUE TITLE
Allow Lua patterns as root pattern

### ISSUE THREAD

**Issue by glacambre** [neovim/nvim-lspconfig#170]
Note: this isn't a bug but the issue template selection menu doesn't offer anything else.

As far as I can tell, `util.root_pattern()` expects a string rather than a pattern:
https://github.com/neovim/nvim-lsp/blob/56a9268de428acee307f67fc11c08b575e96004c/lua/nvim_lsp/util.lua#L270-L282
Because the `exists()` function it calls uses fs_stat, which I believe expects a string:
https://github.com/neovim/nvim-lsp/blob/56a9268de428acee307f67fc11c08b575e96004c/lua/nvim_lsp/util.lua#L112-L115

Being able to use lua patterns would be nice, I'm trying to add a support for the Ada Language Server and one way to detect the root directory of a project is to look for `*.gpr` or `*.adc` files.

**Comment by justinmk** [comment]
this PR sneaked the use of `vim.fn.glob()` in : https://github.com/neovim/nvim-lspconfig/commit/28a39821be3a79b5887da5822ce6167d42c44a6d#diff-e23e94d10ef42d80a01f1577ed178ce9R293

I think that solved this issue, lmk if not.

**Comment by justinmk** [comment]
though we need documentation update to mention that root_pattern allows glob. also some examples:

```
    filetypes = {"cs", "vb"};
    root_dir = util.root_pattern("*.csproj", "*.sln");
