### ISSUE TITLE
`sumneko_lua` asks about working environment on every startup

### ISSUE THREAD

**Issue by teenjuna** [neovim/nvim-lspconfig#1700]
### Description

I have set up the `sumneko_lua` as [shown](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sumneko_lua) in the docs.

Every time I open Lua file this thing shows me this prompt:
```
Do you need to configure your work environment as `OpenResty`?

Request Actions:
1. Apply and modify settings
2. Apply but do not modify settings
3. Don't show again
Type number and <Enter> or click with the mouse (q or empty cancels):
```

I don't really understand anything about `OpenResty` and `sumneko_lua`'s work environments but tt seems like it doesn't save chosen settings.

### Neovim version

NVIM v0.7.0-dev+1004-g6bee2bf79
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

2008c5cebf2b84c5e5f8a566480b022ab2e7ebab

### Operating system and version

macOS 12.0.1

### Affected language servers

sumneko_lua

### Steps to reproduce

Install `sumneko_lua` as shown in the docs and open any Lua file.

### Actual behavior

As described in the description

### Expected behavior

The prompt must not be shown every time I open the file

### Minimal config

```Lua
local runtime_path = vim.split(package.path, ';')
table.insert(runtime_path, 'lua/?.lua')
table.insert(runtime_path, 'lua/?/init.lua')
require('lspconfig').sumneko_lua.setup {
  on_attach = function()
    on_attach()
    vim.cmd [[autocmd BufWritePre <buffer> lua require'stylua-nvim'.format_file()]]
  end,
  settings = {
    Lua = {
      runtime = {
        version = 'LuaJIT',
        path = runtime_path,
      },
      diagnostics = {
        globals = { 'vim' },
      },
      workspace = {
        library = vim.api.nvim_get_runtime_file('', true),
      },
      telemetry = {
        enable = false,
      },
    },
  },
}
```

### LSP log

https://gist.github.com/teenjuna/9c5e6cea368d0a889d204950b6161884

**Comment by mjlbach** [comment]
In the future, server usage questions should be asked on our discourse: https://neovim.discourse.group/c/language-server-protocol-lsp/7.

What you're seeing is a feature of `lua-language-server`:

```
require('lspconfig').sumneko_lua.setup {
  on_attach = function()
    on_attach()
    vim.cmd [[autocmd BufWritePre <buffer> lua require'stylua-nvim'.format_file()]]
  end,
  settings = {
    Lua = {
      runtime = {
        version = 'LuaJIT',
        path = runtime_path,
      },
      diagnostics = {
        globals = { 'vim' },
      },
      workspace = {
        library = vim.api.nvim_get_runtime_file('', true),
        checkThirdParty = false, -- THIS IS THE IMPORTANT LINE TO ADD
      },
      telemetry = {
        enable = false,
      },
    },
  },
}
```
```

**Comment by natdm** [comment]
> In the future, server usage questions should be asked on our discourse

For what it's worth, not everyone uses discourse, and it's appreciated that I can find the answer in the repository issues.

Thanks for posting the fix!

**Comment by dbaynard** [comment]
Would a PR be welcome, adding this to the (otherwise great) documentation?
