### ISSUE TITLE
Allow to configure borders for popup window

### ISSUE THREAD

**Issue by aryzing** [neovim/nvim-lspconfig#1717]
### Requested feature

Expose floating window config through setup. 

With my current theme, the borders aren't visible, making it hard to read the window's contents. Thanks to [this snippet](https://github.com/williamboman/nvim-lsp-installer/issues/475#issuecomment-1037222808), I've enabled rounded borders. Would feel less of a hack if it was officially supported at setup.

**Before**

![borders-invisible](https://user-images.githubusercontent.com/4924405/153713923-26d7fa88-3f9f-4afb-b429-1064a2a3facc.png)

**After**

![borders-visible](https://user-images.githubusercontent.com/4924405/153713947-7582710b-ffcc-4c67-abed-2dfad745f1b8.png)

**Comment by seblj** [comment]
Not exactly what you are looking for, but a way that's probably less hacky than overriding is creating a file `after/ftplugin/lspinfo.lua` and have this inside it `vim.api.nvim_win_set_config(0, { border = 'rounded' })`

**Comment by RaafatTurki** [comment]
@justinmk this is ridiculous, you can't just [hardcode user preferences](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/ui/windows.lua#L37-L53) and call it out of scope.

The moment a UI window was introduced this plugin stopped being just a "collection of quickstart configs"

**Comment by paul-hansen** [comment]
I was able to configure this using:
```lua
-- Fix :LspInfo not having a border
require('lspconfig.ui.windows').default_options.border = 'rounded'
-- Fix :LspInfo border being wrong color after the above fix
vim.cmd(":hi! link LspInfoBorder NormalFloat")
```
I put this in my `after/plugin/lsp.lua` file, but it should be able to go anywhere that lspconfig would be loaded before it runs.

It should be noted that the top of the `lspconfig.ui.windows` module warns that it is unstable and may change, so it may break in future updates to lspconfig.
https://github.com/neovim/nvim-lspconfig/blob/d0467b9574b48429debf83f8248d8cee79562586/lua/lspconfig/ui/windows.lua#L1-L2
