### ISSUE TITLE
There is no `local omnisharp_bin = "/path/to/omnisharp-repo/run"` anymore

### ISSUE THREAD

**Issue by nyngwang** [neovim/nvim-lspconfig#1719]
### Description

I just installed omnisharp via nvim-lsp-installer. And follow the setup:

```
local pid = vim.fn.getpid()
-- On linux/darwin if using a release build, otherwise under scripts/OmniSharp(.Core)(.cmd)
local omnisharp_bin = "/path/to/omnisharp-repo/run"
-- on Windows
-- local omnisharp_bin = "/path/to/omnisharp/OmniSharp.exe"
require'lspconfig'.omnisharp.setup{
    cmd = { omnisharp_bin, "--languageserver" , "--hostPID", tostring(pid) };
    ...
}
```

But there is no `.../run/` folder/executable anymore.

### Neovim version

NVIM v0.7.0-dev+1082-g046950f63
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

0da0023

### Operating system and version

macOS 12.2

### Affected language servers

omnisharp

### Steps to reproduce

1. `:LspUninstall omnisharp`
2. `:LspInstall omnisharp`

### Actual behavior

```
Spawning language server with cmd: `/Users/foo/.local/share/nvim/lsp_servers/omnisharp/omnisharp/run` failed. The language server is either not installed, missing from PATH, or not executable.
```

### Minimal config

```Lua
The same as wiki.
```

### LSP log

[START][2022-02-14 05:45:18] LSP logging initiated [START][2022-02-14 05:47:18] LSP logging initiated [START][2022-02-14 05:49:04] LSP logging initiated [START][2022-02-14 05:59:20] LSP logging initiated [START][2022-02-14 05:59:27] LSP logging initiated [START][2022-02-14 06:02:02] LSP logging initiated [START][2022-02-14 06:03:19] LSP logging initiated [START][2022-02-14 06:09:26] LSP logging initiated [START][2022-02-14 06:10:51] LSP logging initiated [START][2022-02-14 06:11:13] LSP logging initiated [START][2022-02-14 06:12:13] LSP logging initiated

**Comment by mjlbach** [comment]
nvim-lsp-installer is an unsupported 3rd party plugin

**Comment by nyngwang** [comment]
@mjlbach: Yes. I did change the prefix to my path. There is no `.../run` under the path.

**Comment by mjlbach** [comment]
Are you asking how to set up omnisharp with or without nvim-lsp-installer?

**Comment by nyngwang** [comment]
@mjlbach: with nvim-lsp-installer. Sorry I was creating a new issue there due to I forgot I was initially asking about `csharp_ls`.

**Comment by mjlbach** [comment]
> with nvim-lsp-installer

Then I can't help you

**Comment by nyngwang** [comment]
@mjlbach: OK, never mind. Let me try to install it manually.
