### ISSUE TITLE
Question about LSP formatting

### ISSUE THREAD

**Issue by fakeYanss** [neovim/nvim-lspconfig#1738]
### Description

When I using formatting, it will appear `^M` behind each line. Ho to solve it? 

<img width="1324" alt="Screen Shot 2022-02-26 at 00 37 20" src="https://user-images.githubusercontent.com/30440198/155752805-84e3373e-5fb3-4b5f-ab8b-63ec9ef722ce.png">

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

### Nvim-lspconfig version

470569379d708e6c8f33f082497e0374067c6fee

### Operating system and version

macOS 12.1

### Affected language servers

all

### Steps to reproduce

1. open a file using nvim
2. command `lua vim.lsp.buf.formatting()` 

### Actual behavior

appear `^M` behind each line

### Expected behavior

formatting as usual, no `^M`

### Minimal config

```Lua
*
```

### LSP log

*

**Comment by mjlbach** [comment]
Pretty sure I fixed this on the nightly, so you can update. Also this is not an issue for lspconfig, and before filing an LSP related issue you should check the latest neovim nightly, as that is what actually implements the language server client.

**Comment by fakeYanss** [comment]
Thanks a lot. Using nvim nightly can solve it.
