### ISSUE TITLE
Documentation generation broken for asm_lsp

### ISSUE THREAD

**Issue by cafce25** [neovim/nvim-lspconfig#1742]
### Description

The documentation generated for asm_lsp contains an erroneous `end)` or is missing the
```lua
function(startpath)
  return M.search_ancestors(startpath,
```
parts.

### Nvim-lspconfig version

8b33d456

### Affected language servers

asm_lsp, possibly more

### Steps to reproduce

1. go to the documentation of asm_lsp

### Actual behavior

```lua
    root_dir = function(path)
        -- Support git directories and git files (worktrees)
        if M.path.is_dir(M.path.join(path, '.git')) or M.path.is_file(M.path.join(path, '.git')) then
          return path
        end
      end)
    end
```

### Expected behavior

default like in 'asm_lsp.lua':
```lua
  root_dir = util.find_git_ancestor,
```
or maybe with an expanded `util.find_git_ancestor`
```lua
  root_dir = function (startpath)
    return M.search_ancestors(startpath, function(path)
      -- Support git directories and git files (worktrees)
      if M.path.is_dir(M.path.join(path, '.git')) or M.path.is_file(M.path.join(path, '.git')) then
        return path
      end
    end)
  end
```

**Comment by mjlbach** [comment]
It's the fallback auto scraping that uses the debug module to get the lines:
https://github.com/mjlbach/nvim-lspconfig/blob/f84f592816a6b0c55e2a655b56c480683ad92c63/scripts/docgen.lua#L126-L149

**Comment by mjlbach** [comment]
I decided to remove the use of the debug module, it's too unreliable for fetching the text of the root resolving function.
