### ISSUE TITLE
TailwindCSS autocomplete is not working

### ISSUE THREAD

**Issue by dheerajd5** [neovim/nvim-lspconfig#1752]
### Description

There is no autocomplete suggestions for tailwind classes.

I have just installed nvim and my setup on a new laptop and now the tailwindcss auto complete isn't working. It used to work at my previous pc but now with the same config and steps it doesn't seem to work here.

Looking at looks it seems to find both the tailwind.config.js file and its required modules but the auto complete doesn't seem to be working.

### Neovim version

NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az152-430

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

### Operating system and version

Windows 11

### Affected language servers

tailwindcss

### Steps to reproduce

I have installed tailwindcss using lsp-installer.

### Actual behavior

![image](https://user-images.githubusercontent.com/22520440/156308608-f7cd96ca-8606-411f-8c0b-d326a6dc3f9e.png)
This is my project file, and below is the LspInfo, i have installed the node modules too.
At the time of this issue, my neovim and lspconfig are both up to date.
 I have tried reinstalling tailwindcss but the same problem occurs.
![image](https://user-images.githubusercontent.com/22520440/156308641-9df81a75-5e0f-4d21-b722-80d1fc599d1c.png)

### Minimal config

```Lua
This is the same config from lsp-installer/tailwindcss.lua.
```

### LSP log

https://gist.github.com/dheerajd5/9c8d8aede3f74529c0473dea6edd1ffc

**Comment by mjlbach** [comment]
1. nvim-lsp-installer is unsupported
2. this plugin does not offer autocompletion, nor provide any language server utilties apart from launching language servers
3. this is a usage question, and belongs on discourse
