### ISSUE TITLE
Give some interface to retrieve the root dir of a client as a string

### ISSUE THREAD

**Issue by embeddedpenguin** [neovim/nvim-lspconfig#1753]
### Requested feature

I've looked through this code for a few days. I've got no clue what's going on. I suck at lua. Everything is a function. Does anything actually exist? Consider me filtered.

My request is to give the client a variable named root_dir or something similar so when the lsp client attaches, I can get the root_dir and use it to create a bunch of nvim-dap configurations. Something like this:

```
M.on_attach = function(client, bufnr)
  if client.name == "clangd" then
    local util = require('lspconfig.util')
    print(client.config.root_dir)
  end
  lsp_keymaps(bufnr)
  lsp_highlight_document(client)
end
```

The `client.config.root_dir` currently gives me a function. I don't actually even know how this function works because when I looked in the source, it looks like it's simply a name for another function, and that function is the name for another function, and *that* function is the name for another function... and so on. If this request is too ridiculous, I understand--any advice on turning client.config.root_dir into a string I can use is welcome.

**Comment by mjlbach** [comment]
```
:lua =vim.lsp.get_active_clients()[1].workspace_folders  
```

```
{ {                                                                                                                                                                        
    name = "/home/michael/Repositories/neovim",                                                                                                                               
    uri = "file:///home/michael/Repositories/neovim                                                                                                                          
  } }
```

What you want is the URI

**Comment by embeddedpenguin** [comment]
> ```
> :lua =vim.lsp.get_active_clients()[1].workspace_folders  
> ```
> 
> ```
> { {                                                                                                                                                                        
>     name = "/home/michael/Repositories/neovim",                                                                                                                               
>     uri = "file:///home/michael/Repositories/neovim                                                                                                                          
>   } }
> ```
> 
> What you want is the URI

I could be interpreting what you're saying wrong, but I ran this and it didn't work out. Here's my LspInfo:

```
 Language client log: /home/penguin/.cache/nvim/lsp.log
 Detected filetype:   c
 
 1 client(s) attached to this buffer: 
 
 Client: clangd (id: 1, pid: 13836, bufnr: [1])
 	filetypes:       c, cpp, objc, objcpp
 	autostart:       true
 	root directory:  /storage/Shared/Projects/Embedded-Graphics-Learning/software/firmware/oracle_same54n19a
 	cmd:             clangd --query-driver=/usr/bin/arm-none-eabi-gcc --compile-commands-dir=/storage/Shared/Projects/Embedded-Graphics-Learning/software/firmware/oracle_same54n19a/gcc --pch-storage=memory --background-index -j=4 --header-insertion-decorators=0 --log=verbose
 
 Configured servers list: jdtls, sumneko_lua, clangd, rust_analyzer, taplo, pyright
```
Running `:lua =vim.lsp.get_active_clients()[1].workspace_folders` gives me:
`E5107: Error loading lua [string ":lua"]:1: unexpected symbol near '='`

**Comment by mjlbach** [comment]
`:lua =` will only work on neovim 0.7, it's equivalent to

`:lua print(vim.inspect(vim.lsp.get_active_clients()[1].workspace_folders))`

**Comment by embeddedpenguin** [comment]
Thank you very much!
