### ISSUE TITLE
Reference buffer not closing on file open

### ISSUE THREAD

**Issue by robbienohra** [neovim/nvim-lspconfig#1763]
### Description

I am using the following keymap

```
map("n", "<space>r", "<cmd>lua vim.lsp.buf.references()<CR>")
```

The reference buffer opens without a problem. However, when I click on a given reference file, the file opens but the reference buffer remains open.

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/28514482/157319329-36fa79bf-720b-437f-99b4-8c10e144bed4.png">

<img width="1740" alt="image" src="https://user-images.githubusercontent.com/28514482/157319344-378ddaa6-d1bf-413d-aa7d-e474a1083423.png">

### Neovim version

0.6.1

### Nvim-lspconfig version

ea29110765cb42e842dc8372c793a6173d89b0c4

### Operating system and version

macOS 12.0.1

### Affected language servers

all

### Steps to reproduce

1. open a file of your choice (with references outside of the given file)
2. enter the key map for going to a reference
3. select a file
4. note that buffer remains open

### Actual behavior

Reference buffer remains open even after selecting a file

### Expected behavior

Buffer should close upon selection of a file

### Minimal config

[nvim/init.lua](https://github.com/robbienohra/dotfiles/blob/main/nvim/.config/nvim/init.lua)
[lsp/init.lua](https://github.com/robbienohra/dotfiles/blob/main/nvim/.config/nvim/lua/user/lsp/init.lua)
[keymaps.lua](https://github.com/robbienohra/dotfiles/blob/main/nvim/.config/nvim/lua/keymaps.lua)

### LSP log

https://gist.github.com/robbienohra/04ede334433267816cf5c0bb68f37707

**Comment by mjlbach** [comment]
This is as designed, references populates the quickfix list, nothing more. If you want, you can enable a ++once autocommand to close the quickfix list upon bufenter, but we won't change the default behavior.

**Comment by robbienohra** [comment]
🤔 
apologies for posting here, I presumed from the [suggested configs](https://github.com/neovim/nvim-lspconfig#suggested-configuration) here that it may be related to `nvim-lspconfig`

what would be the correct repo to inquire about the `lua vim.lsp.buf.references()` command?

I'll give the auto-command approach a spin now, thanks!

**Comment by mjlbach** [comment]
As it's a usage question, the appropriate place is the [neovim discourse](https://neovim.discourse.group/)

**Comment by robbienohra** [comment]
For posterity, this is what ended up working for me:

```
local autocmd = vim.api.nvim_create_autocmd

autocmd(
  { "BufLeave" },
  { pattern = { "*" }, command = "if &buftype == 'quickfix'|q|endif" }
)
```
