### ISSUE TITLE
Add support for cl-lsp

### ISSUE THREAD

**Issue by muppi090909** [neovim/nvim-lspconfig#1767]
### Language server

cl-lsp

### Requested feature

Add support for [cl-lsp](https://github.com/cxxxr/cl-lsp).

### Other clients which have this feature

vim-lsp

**Comment by mjlbach** [comment]
This server hasn't seen an update in over a year, I'd rather not add servers to lspconfig that are not actively developed. Furthermore I tested this and the server will not initialize.

**Comment by glyh** [comment]
Hello, I see cl-lsp is removed, but the above customizing setup code is not working as well, is there a way for me to workaround it? Thanks.

**Comment by slowpuke** [comment]
Sorry to resurrect an old issue, but is there any chance to add cl-lsp support?

**Comment by cxwx** [comment]
蹲一个后续
