### ISSUE TITLE
Documentation: Inverse Search

### ISSUE THREAD

**Issue by f3fora** [neovim/nvim-lspconfig#1772]
### Language server

texlab

### Requested feature

Inverse Search is possible in texlab. However there is no documentation about it and I cannot use it.

[Texlab documentation](https://github.com/latex-lsp/texlab/blob/master/docs/previewing.md) is about vscode only.

**Comment by mjlbach** [comment]
This isn't the texlab repo, you can contribute documentation to that repo, or ask on the neovim discourse for someone to help you. The issue tracker is not for usage questions.
