### ISSUE TITLE
Apply `:LspStop` and `:LspRestart` to current buffer only

### ISSUE THREAD

**Issue by rish987** [neovim/nvim-lspconfig#1781]
### Requested feature

Currently, `:LspStop` and `:LspRestart` require knowing the specific ID of a client, or running them without arguments applies to *all* clients. It seems more likely that you would want these commands to only apply to the current buffer. We could do this either by creating buffer-specific commands (e.g. `:LspBufStop` or `:LspBufRestart`) or using the argument `0` to indicate the current buffer (as client indexing starts with `1`).

**Comment by mg979** [comment]
Documentation says these commands should only stop/start clients on current buffer, but it's obviously not true.

https://github.com/neovim/nvim-lspconfig/blob/63efd6ed156ae578c7e23278ec0a82776802106b/doc/lspconfig.txt#L472-L476

So it happens that `LspStop` stops everything on all buffers, but `LspStart` only restart in the current buffer. So if you do `LspStop` you have to do `LspStart` on all other buffers...
