### ISSUE TITLE
Add autoimport from tsconfig custom paths

### ISSUE THREAD

**Issue by javeoff** [neovim/nvim-lspconfig#1786]
### Description

I have a plugin `tsconfig-path` in my project, that works with webstorm autoimport, but in neovim autoimport has only relative paths. 

<img width="249" alt="image" src="https://user-images.githubusercontent.com/62588539/158759529-7d24409d-86ea-4852-8f3a-1067570f3859.png">

I tried to set tsconfig plugin in a configuration of server, but it no works. I think, local tsconfig plugins of project does not set up in config of lsp. What the problem?

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system and version

macOs 12.0.1

### Affected language servers

tsserver

### Steps to reproduce

You can see the example in my project
https://github.com/javeoff/nest-next-boilerplate/blob/master/tsconfig.json

### Actual behavior

Import subject from any other file of subject and see relative import `import ... from '../../path/to`

### Expected behavior

Must be `import '@common/path/to'`

### Minimal config

```Lua
lspconfig["tsserver"].setup({
        root_dir = lspconfig.util.root_pattern("package.json"),
        init_options = ts_utils.init_options,
        on_attach = function(client, bufnr)
            client.resolved_capabilities.document_formatting = false
            client.resolved_capabilities.document_range_formatting = false
            on_attach(client, bufnr)

            ts_utils.setup(ts_utils_settings)
            ts_utils.setup_client(client)
        end,
        flags = {
            debounce_text_changes = 150,
        },
        plugins = {
            {
                name = 'tsconfig-paths',
                location = '~/node_modules/tsconfig-paths',
            }
        },
        capabilities = capabilities,
    })
```
```


### LSP log

https://github.com/javeoff/dotfiles

**Comment by mjlbach** [comment]
`plugins` is not an allowed key, it needs to be under initialization options, see: https://github.com/typescript-language-server/typescript-language-server#initializationoptions

In the future, please use discourse for support questions.
