### ISSUE TITLE
Handle Diagnostic.tags

### ISSUE THREAD

**Issue by baltitenger** [neovim/nvim-lspconfig#1788]
### Language server

pyright

### Requested feature

Pyright uses the [Diagnostic.tags](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticTag) parameter to indicate unnecessary function parameters (see microsoft/pyright#2307), and the LSP standard advises clients to render them as faded out. However, neovim shows them as regular diagnostics, which can be really annoying as all unused function arguments are reported and there's no way to turn it off (pyright doesn't have a setting for this).

**Comment by mjlbach** [comment]
wrong repo, please reread the issue template.

**Comment by bavalpey** [comment]
> wrong repo, please reread the issue template.

Where exactly in the neovim pipeline should this be addressed?
Right now, using pyright with this lsp-config causes a bunch of silly things to appear in diagnostics with virtual text, etc that really _shouldn't_ be there by default (or should at least be configurable).

I understand that this repo is for default configurations for specific LSPs.  What, then, is responsible for tweaking how things reported by the LSP are shown/handled in nvim?
What needs to be changed to, for instance, stop having "UnusedVariable" appear in the list of diagnostics?

**Comment by gpanders** [comment]
Diagnostic tags are supported in Neovim 0.9: https://github.com/neovim/neovim/pull/22747
