### ISSUE TITLE
JDTLS not Launching Properly

### ISSUE THREAD

**Issue by Balrrach** [neovim/nvim-lspconfig#1789]
### Description

JDTLS doesn't seem to be launched correctly on first instance.

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

### Operating system and version

5.10.105-1-MANJARO

### Affected language servers

JDTLS

### Steps to reproduce

`nvim file.java`

### Actual behavior

1. None of the language server features like autocompletion, goto defition... will work
2. Some errors among the following may popup:
- The declared package "route.file" does not match the expected package "". [Link](https://stackoverflow.com/questions/6997524/the-declared-package-does-not-match-the-expected-package)
- file.java is not on the classpath of project, only syntax errors are reported. [Link](https://stackoverflow.com/questions/67279650/java-vscode-file-java-is-not-on-the-classpath-of-project-only-syntax-errors-ar)
- The import core cannot be resolved. [Link](https://stackoverflow.com/questions/4322893/eclipse-error-the-import-xxx-cannot-be-resolved)
Some of these errors are known to be related to the language server directly and not related to the project and, in fact, can be often solved by just executing a cleaning or relaunching the editor(Eclipse often). In my case I know these errors are related to JDTLS because there is a way to fix it that has nothing to do with the project. To fix it, it is enough with executing:
1. `:LspStop`
2. `:LspStart`
Those two commands solve all problems and the language server is correctly launched. `:LspRestart` get's rid of the errors but doesn't seem to launch the language server since no features work. 

### Expected behavior

JDTLS to be launched correctly

### Minimal config

```Lua
No configuration was done. The server was installed with `williamboman/nvim-lsp-installer`.
```

### LSP log

https://gist.github.com/Balrrach/8595b7a8340a5e90e8bb56fc533ef75b

**Comment by mjlbach** [comment]
> No configuration was done. The server was installed with `williamboman/nvim-lsp-installer`.

unsupported

**Comment by Balrrach** [comment]
Installed the standard way and works correctly. Will contact nvim-lsp-installer maintainer.
