### ISSUE TITLE
How to run auto format on save?

### ISSUE THREAD

**Issue by Moncheeta** [neovim/nvim-lspconfig#1792]
### Description

The formatters runs exactly when I return to Normal mode(from insert mode). I would like to set it to run on the file save. Is there any way to do that? How can I turn off the auto formatters?

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Manjaro Linux on the 5.16 Kernal

### Affected language servers

clangd

### Steps to reproduce

1. Open a file and edit and make a mistake on purpose.
2. Go back to normal mode.

### Actual behavior

The file gets formatted right when you get back to normal mode.

### Minimal config

```Lua
call plug#begin()
Plug 'ms-jpq/coq_nvim', {'branch': 'coq'} " for autocomplete
Plug 'neovim/nvim-lspconfig'
call plug#end()

" Lang Server Conf
lua << END
local coq = require "coq"
local servers = { 'clangd', 'rust_analyzer', 'tsserver', 'pyright', 'sumneko_lua', 'golangci_lint_ls', 'kotlin_language_server', 'bashls' }
for _, lsp in pairs(servers) do
    require('lspconfig')[lsp].setup(coq.lsp_ensure_capabilities {
    on_attach = on_attach,
    flags = {
      debounce_text_changes = 150,
    }
  })
end
vim.lsp.set_log_level('debug')
END
```

### LSP log

https://gist.github.com/Moncheeta/3c9a4f33621d9f8ccaf15a425b2e1b9d

**Comment by mjlbach** [comment]
That's not a minimal config, you'll need to reproduce with our minimal config as indicated in the issue template. I can assure you the issue is in your configuration, as neovim does not automatically format, ever.

**Comment by Moncheeta** [comment]
My bad. After further investigation, I found out that a plugin was doing it. Sorry!

**Comment by robinmoussu** [comment]
> My bad. After further investigation, I found out that a plugin was doing it. Sorry!

It would have been nice to tell which one and what you did change.

**Comment by Moncheeta** [comment]
It was a long time ago. I remember that I removed some sort of auto save plugin.

**Comment by robinmoussu** [comment]
I also had a similar issue, and I realized that I had in my config this autocommand:

```lua
    vim.api.nvim_create_autocmd("BufWritePre", {
        buffer = buffer,
        callback = function()
            vim.lsp.buf.format { async = false }
        end
    })
```
