### ISSUE TITLE
Add Ability to add Custom Formatters

### ISSUE THREAD

**Issue by Moncheeta** [neovim/nvim-lspconfig#1793]
### Requested feature

I would like there to be an option to override or supply a lsp with a command that runs a formatter. At the moment, sumneko_lua doesn't have a built in formatter, so I would like to use Koihik/LuaFormatter. I would like to be able to run the correct formatter with one command(``vim.lsp.buf.formatting()``).

**Comment by mjlbach** [comment]
`vim.lsp.buf.formatting()` does exactly what it says, it runs a formatter via the language server. I'm not planning on overloading this function (which, by the way, as mentioned in the issue template is not implemented in this repository). If you want, map a key in on_attach to call [formatter.nvim](https://github.com/mhartington/formatter.nvim) with the args to luaformatter instead.

**Comment by Moncheeta** [comment]
Thanks!
