### ISSUE TITLE
Re-document root patterns

### ISSUE THREAD

**Issue by mjlbach** [neovim/nvim-lspconfig#1800]
I removed the feature in our docgen that automatically extracted the root patterns and added it to the documentation, these should now be manually documented as before. The full changelist:

https://github.com/neovim/nvim-lspconfig/commit/733fe92baafb23cb413300571e31cb1fec962b1a

**Comment by justinmk** [comment]
Seems a bit like using a shotgun to kill a mosquito. 

I have opened https://github.com/neovim/nvim-lspconfig/issues/2011
