### ISSUE TITLE
HLS consumes huge memory

### ISSUE THREAD

**Issue by LC0117** [neovim/nvim-lspconfig#1805]
### Description

As is described above and shown in the following pictures, haskell-language-server paired with neovim consumes abnormally large memory compared to vscode.

neovim:
<img width="727" alt="01" src="https://user-images.githubusercontent.com/77481149/159523327-3be31cfb-3a06-4e2b-8fd8-6c67cde21295.png">

vscode(both using haskell-language-server):
<img width="727" alt="02" src="https://user-images.githubusercontent.com/77481149/159523531-6323c747-4613-4fee-b760-83894c9e0d60.png">

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
(It's installed from homebrew)

### Nvim-lspconfig version

733fe92baafb23cb413300571e31cb1fec962b1a

### Operating system and version

macOS 12.3 arm64

### Affected language servers

hls (haskell-language-server)

### Steps to reproduce

1. config neovim like `require("lspconfig").hls.setup()` paired with `nvim-cmp` plugin
2. open a haskell project template using `stack --resolver ghc-8.10.7 new <project_name>`
3. open a `.hs` file and check the memory usage
4. open this project in vscode with haskell extension installed (which uses haskell-language-server)

### Actual behavior

lsp attach to neovim consumed huge memory while this didn't happened in vscode (I've made sure that all hls process was killed before opening in vscode)

### Expected behavior

HLS attached to neovim shouldn't consume so much memory.

### Minimal config

```Lua
As described in `Step to Reproduce`
```

### LSP log

https://gist.github.com/LC0117/1b851694a492abdb4b1f92ef1cc78715

**Comment by mjlbach** [comment]
I cannot reproduce this.

**Comment by LC0117** [comment]
Ok, then this has to be something wrong with my configuration or machine or luck. Closing...
