### ISSUE TITLE
"Invalid buffer number" when calling ":lua vim.lsp.buf.definition()" when using clangd on C code.

### ISSUE THREAD

**Issue by tristone13th** [neovim/nvim-lspconfig#1806]
### Description

"Invalid buffer number" when calling ":lua vim.lsp.buf.definition()" when using clangd on C code.

### Neovim version

NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Ubuntu 20.04

### Affected language servers

clangd-15

### Steps to reproduce

Open a kernel repo with neovim with lspconfig installed.
Compile the kernel to generate compile_commands.json.
Move cursor on any "printf" function, then ":lua vim.lsp.buf.definition()".

### Actual behavior

Error executing vim.schedule lua callback: ...pack/paqs/start/nvim-lspconfig/lua/lspconfig/configs.lua:185: Vim(autocmd):E680: <buffer=31>: invalid buffer number
stack traceback:
[C]: in function 'nvim_command'
...pack/paqs/start/nvim-lspconfig/lua/lspconfig/configs.lua:185: in function 'cb'
vim.lua:285: in function vim.lua:285

### Expected behavior

Go to definition.

### Minimal config

```Lua
lsp_cfg.clangd.setup({})
```

### LSP log

https://gist.github.com/tristone13th/a97694018336af3844c6fe00ef0ded29

**Comment by mjlbach** [comment]
That's not a minimal configuration... You need to use the included one I wrote.

**Comment by tristone13th** [comment]
> That's not a minimal configuration... You need to use the included one I wrote.

I have found the root cause, not a problem of lspconfig, thanks for the reply, keep on your great work!

**Comment by mjlbach** [comment]
No worries, glad you figured it out :)
________________________________
