### ISSUE TITLE
With rust-analzer > 2022.2.28 no inlay hints any more

### ISSUE THREAD

**Issue by getreu** [neovim/nvim-lspconfig#1820]
### Description

The last checked working version of Rust-analyzer was 2022.2.28.
With later versions there are no inlay hints are displayed. 

```vim
autocmd CursorHold,CursorMoved,InsertLeave,TabEnter,BufWritePost *
\ lua require'lsp_extensions'.inlay_hints{
\     prefix = '',
\     highlight = "Comment",
\     prefix = "  ",
\     aligned = false,
\     only_current_line = true,
\     enabled = {"TypeHint", "ChainingHint", "ParameterHint"}
\ }
```

### Neovim version

NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az87-780

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

### Nvim-lspconfig version

3d1baa811b351078e5711be1a1158e33b074be9e

### Operating system and version

Debian 11

### Affected language servers

rust-analyzer

### Steps to reproduce

Open Rust file.

### Actual behavior

No inlay hints are shown.

### Expected behavior

Inlay hints.

### Minimal config

```Lua
See above.
```

### LSP log

-

**Comment by mjlbach** [comment]
You'll have to file an issue with that plugin, or rust-tools.nvim (which also provides inlay hints). This repo just launches rust analyzer for you with some default settings, nothing more..
