### ISSUE TITLE
Cannot setup custom server configuration for the LSP server `astro-ls`

### ISSUE THREAD

**Issue by smithbm2316** [neovim/nvim-lspconfig#1823]
### Description

I'm trying to run the [Astro language server](https://github.com/withastro/language-tools/tree/main/packages/language-server) with `.astro` files on my local machine. I have used it in the past with success (it's been a few months), and all of the sudden the custom server configuration that I have does not seem to be working. Would appreciate any help that y'all can offer 🙂. Thank you for the amazing plugin and your help!

Here is the output of `:LspInfo` when I'm *not* using the `minimal_init.lua` setup:
![Screen Shot 2022-04-04 at 3 03 48 PM](https://user-images.githubusercontent.com/37027883/161639646-a00a8f63-99af-40f5-935e-751951db74f7.png)

No errors occur with my personal setup, only the errors happen when running the `minimal_init.lua` setup. But even when running `:LspStop` and `:LspStart` to try and re-run the server, it still won't attach to the buffer. I've got a `ftdetect/astro.vim` file that has the following command in it: `au BufRead,BufNewFile *.astro setfiletype astro` (I have also tried `au BufRead, BufNewFile *.astro set filetype=astro` to no avail) so that Neovim is aware of the `astro` filetype.

### Neovim version

NVIM v0.7.0-dev+1392-gdaa8ac051
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by `redacted username and computer name`

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-daa8ac0/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

3d1baa811b351078e5711be1a1158e33b074be9e

### Operating system and version

macOS 11.6.2

### Affected language servers

astro-ls (custom server)

### Steps to reproduce

1. `nvim -nu minimal_init.lua`
2. `:e src/pages/index.astro`

### Actual behavior

Error received after running `nvim -nu minimal_init.lua` followed by `:e src/pages.index.astro`
```
Error executing vim.schedule lua callback: ...r/neovim/HEAD-daa8ac0/share/nvim/runtime/lua/vim/lsp.lua:955: RPC[Error] code_name = InternalError, message = "Request initializ
e failed with message: Cannot read property 'astro' of undefined"
stack traceback:
        [C]: in function 'assert'
        ...r/neovim/HEAD-daa8ac0/share/nvim/runtime/lua/vim/lsp.lua:955: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Output of `:LspInfo` after running `nvim -nu minimal_init.lua`  followed by `:e src/pages.index.astro`:
```
Language client log: /Users/smithbm/.cache/nvim/lsp.log
Detected filetype:   astro

0 client(s) attached to this buffer:

Other clients that match the filetype: astro

Config: astro
filetypes:         astro
root directory:    /Users/smithbm/code/astro-beta-portfolio
cmd:               astro-ls --stdio
cmd is executable: true
autostart:         true
custom handlers:

Configured servers list: astro
```

### Expected behavior

`astro-ls` attaches to the buffer automatically and doesn't throw an error

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir
if on_windows then
  temp_dir = vim.loop.os_getenv 'TEMP'
else
  temp_dir = '/tmp'
end

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

-- set filetype for astro
vim.cmd 'au! BufRead,BufNewFile *.astro set ft=astro'

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local configs = require 'lspconfig.configs'

  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'astro'
  local cmd = { 'astro-ls', '--stdio' }
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not configs[name] then
    configs[name] = {
      default_config = {
        autostart = true,
        cmd = cmd,
        filetypes = { 'astro' },
        root_dir = nvim_lsp.util.find_git_ancestor,
        -- No luck with `util.find_node_modules_ancestor` or `util.root_pattern('package.json', 'tsconfig.json')` either
        -- I have verified that there is a `.git` folder in the root dir, `tsconfig.json` file and `package.json` file in the root dir, and a `node_modules` folder in the root dir
        settings = {},
      },
    }
  end

  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

https://gist.github.com/smithbm2316/e7de7fc245cd57bd5fa7c0daab3eb663

**Comment by mjlbach** [comment]
The error is: 

```

[DEBUG][2022-04-04 14:50:04] .../vim/lsp/rpc.lua:454	"rpc.receive"	{
  error = {
    code = -32603,
    message = "Request initialize failed with message: Cannot read property 'astro' of undefined"
  },
  id = 1,
  jsonrpc = "2.0"
}
````

Try:
```
  if not configs[name] then
    configs[name] = {
      default_config = {
        autostart = true,
        settings = {},
        cmd = cmd,
        filetypes = { 'astro' },
        root_dir = nvim_lsp.util.find_git_ancestor,
        // No luck with `util.find_node_modules_ancestor` or `util.root_pattern('package.json', 'tsconfig.json')` either
        // I have verified that there is a `.git` folder in the root dir, `tsconfig.json` file and `package.json` file in the root dir, and a `node_modules` folder in the root dir
        settings = {},
      },
    }
  end
```

**Comment by smithbm2316** [comment]
Isn't the `settings` key defined twice as an empty table in the suggestion you've provided? In my `minimal_init.lua` setup I have the `settings` key set to an empty table already. Perhaps I'm misunderstanding what you were suggesting. I appreciate the assistance in debugging this, thank you for your help!

**Comment by mjlbach** [comment]
Oh whoops (sorry long day):


``
  if not configs[name] then
    configs[name] = {
      default_config = {
        autostart = true,
        cmd = cmd,
        filetypes = { 'astro' },
        root_dir = nvim_lsp.util.find_git_ancestor,
        // No luck with `util.find_node_modules_ancestor` or `util.root_pattern('package.json', 'tsconfig.json')` either
        // I have verified that there is a `.git` folder in the root dir, `tsconfig.json` file and `package.json` file in the root dir, and a `node_modules` folder in the root dir
        settings = { astro = {} }, -- This is the main difference.
      },
    }
  end
```

**Comment by smithbm2316** [comment]
I am unfortunately still getting the same exact error in my `lsp.log` file 😕. Is there any chance there's some server-specific settings I might have to check their docs for to pass to the `settings = { astro = {} }` table?

**Comment by mjlbach** [comment]
I'm not familiar with the server at all, I just briefly looked at their source code and saw they were checking for an astro attribute on the settings table

**Comment by smithbm2316** [comment]
I'll take a look at their source code myself later this week and see if i can't figure out the issue. Again, appreciate the help very much 🙂

**Comment by smithbm2316** [comment]
I figured out the issue! It looks like there needs to be a `configuration` table first that _then_ has the child of `astro = { enabled = true }`, and these need to be passed to the `init_options` table in the `default_config` as it was an `initialize` error that I was running into. I took a look at the source code for their VSCode extension and found the extra table of `configuration` there that was missing. Here is the working update for anyone else who might need it:

```lua
if not configs[name] then
  configs[name] = {
    default_config = {
      cmd = { 'astro-ls', '--stdio' },
      filetypes = { 'astro' },
      root_dir = util.root_pattern('package.json', 'tsconfig.json', 'jsconfig.json', '.git'),
      docs = {
        description = 'https://github.com/withastro/language-tools',
        root_dir = [[root_pattern("package.json", "tsconfig.json", "jsconfig.json", ".git")]],
      },
      init_options = {
        configuration = {
          astro = {},
        },
      },
      settings = {},
    },
  }
end
```

I will look into making a PR with the configuration for this server soon so people don't have to configure manually 🙂. Thanks again for your help Michael and your dedicated work to this whole plugin!
