### ISSUE TITLE
:help lspconfig-server-configurations doesn't actually exist

### ISSUE THREAD

**Issue by anahata0108** [neovim/nvim-lspconfig#1824]
### Description

The help tag `lspconfig-server-configurations` doesn't actually exist in the documentation

### Neovim version

Not relevant

### Nvim-lspconfig version

f183d35725264d6184146eebcef1ba8338ddbc83

### Operating system and version

Not relevant

### Affected language servers

Not relevant

### Steps to reproduce

1. Browse https://github.com/neovim/nvim-lspconfig/tree/master/doc
2. Try to find lspconfig-server-configurations mentioned in the docs as a help tag

### Actual behavior

lspconfig-server-configurations is not listed

### Expected behavior

lspconfig-server-configurations is listed in the documentation

### Minimal config

```Lua
Not relevant
```

### LSP log

Not relevant

**Comment by mjlbach** [comment]
Yes, it does. Try `:help lspconfig-server-configurations`. We use some trickery to get it to refer to the `txt` file.

**Comment by anahata0108** [comment]
I did, and it says it's not found. I wouldn't have filed the bug otherwise. Your response is extremely dismissive and discourages me from wanting to help further.

**Comment by mjlbach** [comment]
![image](https://user-images.githubusercontent.com/13316262/162101848-303929a3-d79b-4eed-9f2c-0776b233e0af.png)
![image](https://user-images.githubusercontent.com/13316262/162101863-0a3038c0-3b5e-4c50-9703-f064c136e217.png)

**Comment by mjlbach** [comment]
And it wasn't dismissive, because your reproduction steps:

>   Browse https://github.com/neovim/nvim-lspconfig/tree/master/doc
>  Try to find lspconfig-server-configurations mentioned in the docs as a help tag

Do not involve `:help` at all. If you want the raw URL to the file its https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt.
