### ISSUE TITLE
Go to definition does not work in monorepo

### ISSUE THREAD

**Issue by RyanzpLee** [neovim/nvim-lspconfig#1830]
### Description

When I use the minimal config and press `gd` to go to definition of a React JSX component, it does not go to the file, but only goes the line with the import within the same file.

### Neovim version

NVIM v0.7.0-dev+1387-gd73bf3138
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

fd7843ad04cbc8ee2181bed9c3e83839b0d0b285

### Operating system and version

macOS 12.3

### Affected language servers

tsserver 0.9.7

### Steps to reproduce

1. [Setup a minimal config](https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua)
2. Have tsserver installed npm install -g typescript typescript-language-server
3. [Clone this repo](https://github.com/RyanzpLee/test-monorepo-lsp) and rename test_node_modules to `node_modules` to simulate a global node modules that gets shared across all apps in `apps/`
4. Go to apps/app1/src/page1.jsx and put your cursor on <NiceComponentOverlay />
5. Use <cmd>lua vim.lsp.buf.definition()<CR> which should be mapped to gd
6. it will only jump to line 2 where it is imported.
7. Expected behaviour is to jump to apps/app1/src/pages/page1/components/NiceComponentOverlay/NiceComponentOverlay.jsx
8. Remove test-monorepo-lsp/node_modules/typescript
9. Repeat steps 4 - 5 for desired behaviour

When using coc.nvim or vscode and going to definition, it works straight away and I want this function to be working the same.

### Actual behavior

Jumps to the line 2 where the component is imported. Pressing `gd` on this line again does not take it to the file either.

When looking for references with `<cmd>lua vim.lsp.buf.references()<CR>` the file definition does show up, so this is a potential workaround but not the expected workflow.

### Expected behavior

Expect to jump to the correct file defintion in `apps/app1/src/pages/page1/components/NiceComponentOverlay/NiceComponentOverlay.jsx`

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'tsserver'
 -- local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

https://gist.github.com/RyanzpLee/2eb5621b8b84d2c673460ffb8b584fa4

**Comment by mjlbach** [comment]
Yep, you'll need to override the root pattern to support whatever logic you want. One option for your config, just use the git directory:

```lua
local util = require 'lspconfig.util'

require('lspconfig').tsserver.setup{
   root_dir = util.root_pattern('.git')(fname)
}
```

**Comment by RyanzpLee** [comment]
Hi @mjlbach, could you explain what `fname` is please? I tried replacing `nvim_lsp[name].setup...` the custom root_dir but the go to definition still does not work. When I set the root_dir do I want it to be at the monorepo root, or the root of the individual app?
```lua
local util = require 'lspconfig.util'

nvim_lsp.tsserver.setup{
    root_dir = util.root_pattern('.git')(fname),
    cmd = cmd,
    on_attach = on_attach,
  }
```

**Comment by mjlbach** [comment]
Copy/paste error `root_dir = util.root_pattern('.git')`, fname is an argument that is passed to the function reference. You can write it explicitly if you want, but it's equivalent

local util = require 'lspconfig.util'

```
nvim_lsp.tsserver.setup{
    root_dir = util.root_pattern('.git'),
    cmd = cmd,
    on_attach = on_attach,
  }
```

or 
```
nvim_lsp.tsserver.setup{
    root_dir = function(fname)
        return util.root_pattern('.git')(fname)
    end,
    cmd = cmd,
    on_attach = on_attach,
  }
```

**Comment by RyanzpLee** [comment]
Ahh makes sense. So that seems to set the root directory to the monorepo root (as well as find_git_ancestor(), but the 'go to definition' function still does not work properly as you can see here in this recording. It only works if I remove the typescript module from the node modules folder. Any ideas why this is still the case?
https://streamable.com/5mp81j

**Comment by RyanzpLee** [comment]
@mjlbach Just attaching this asciinema recording showing that the 'go to definition' functionality works when the root node_modules folder is removed(renamed).
https://asciinema.org/a/vAn6bmxHSaE2j8asE5F5hC41D

**Comment by mjlbach** [comment]
You can try reporting it upstream to https://github.com/typescript-language-server/typescript-language-server, it's not expected that coc/vscode will behave the same as neovim's built in client, as they are able to use tsserver directly whereas we need to go through the wrapper. This seems like language server behavior rather than anything we are doing clientside.

**Comment by RyanzpLee** [comment]
Hmmm that's interesting to know then thank you for your help! I'll try reporting it upstream like you say and see what can be done about it. 

At the end of the day I suppose I can just continue to use nvim-lsp for side projects and use coc for this particular project.

**Comment by rchl** [comment]
> it's not expected that coc/vscode will behave the same as neovim's built in client

Sure, there can always be differences due to there being an LSP layer used but generally it's still the same tsserver API that is used in all cases. So I would generally expect those things to work the same in all editors.

I haven't investigated this case yet BTW.

**Comment by rchl** [comment]
I think it's just a matter of using different Typescript version.

VSCode uses bundled version of Typescript by default which is typically the latest version at the time the VSCode was released.

When using workspace version of Typescript, you are using older version of Typescript which doesn't work as expected in that case.

You can force VSCode to use the workspace version of Typescript in which case you should also be able to reproduce your issue there:

![Screenshot 2022-04-11 at 11 55 38](https://user-images.githubusercontent.com/153197/162714305-73202eb3-5b8f-4169-8b26-af54bf6b3233.png)

**Comment by RyanzpLee** [comment]
@rchl Interesting! I didn't know you could force the version of Typescript in vscode. I recreate the issue with 4.4.3 in VSCode as you say, so from the sounds of it I just need to bump the version up a more recent version, which hopefully I can do.

Thank you for investigating that!

**Comment by rchl** [comment]
You can specify the which server you want to use with [--tsserver-path](https://github.com/typescript-language-server/typescript-language-server/blob/master/README.md#cli-options) but ideally you would use the same version of typescript within your project and for your IDE so that you don't end up with different behavior between the two.

**Comment by faileon** [comment]
Sorry to revive this thread, but I am having similar issue with `tsserver` LSP. 

My `go to definition` works fine, but `go to reference` only works if I have previously opened up the file (very similarly to this issue https://github.com/typescript-language-server/typescript-language-server/issues/271). I am also using monorepo (nx) that uses ts path mappings. 

So when I try to `gr` on the `foo` here:
```ts
// libs/core/foo.ts
export const foo = 'bar';
```

that is somewhere else used for example as:
```ts
// apps/someapp/main.ts
import { foo } from "@myorg/core"
console.log(foo)
```

the LSP fails to find the reference unless I have previously opened the `apps/someapp/main.ts` file...



Did anyone manage to make it work right?

**Comment by Tantol** [comment]
> Sorry to revive this thread, but I am having similar issue with `tsserver` LSP.
> 
> My `go to definition` works fine, but `go to reference` only works if I have previously opened up the file (very similarly to this issue [typescript-language-server/typescript-language-server#271](https://github.com/typescript-language-server/typescript-language-server/issues/271)). I am also using monorepo (nx) that uses ts path mappings.
> 
> So when I try to `gr` on the `foo` here:
> 
> ```ts
> // libs/core/foo.ts
> export const foo = 'bar';
> ```
> 
> that is somewhere else used for example as:
> 
> ```ts
> // apps/someapp/main.ts
> import { foo } from "@myorg/core"
> console.log(foo)
> ```
> 
> the LSP fails to find the reference unless I have previously opened the `apps/someapp/main.ts` file...
> 
> Did anyone manage to make it work right?

I fallen in same problem. Go to reference for tsserver LSP works only when I open all libs in my monorepo (nx) setup. In VsCode all works out of the box and I can't solution how to setup LSP in neovim.

**Comment by faileon** [comment]
> > Sorry to revive this thread, but I am having similar issue with `tsserver` LSP.
> > My `go to definition` works fine, but `go to reference` only works if I have previously opened up the file (very similarly to this issue [typescript-language-server/typescript-language-server#271](https://github.com/typescript-language-server/typescript-language-server/issues/271)). I am also using monorepo (nx) that uses ts path mappings.
> > So when I try to `gr` on the `foo` here:
> > ```ts
> > // libs/core/foo.ts
> > export const foo = 'bar';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > that is somewhere else used for example as:
> > ```ts
> > // apps/someapp/main.ts
> > import { foo } from "@myorg/core"
> > console.log(foo)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > the LSP fails to find the reference unless I have previously opened the `apps/someapp/main.ts` file...
> > Did anyone manage to make it work right?
> 
> I fallen in same problem. Go to reference for tsserver LSP works only when I open all libs in my monorepo (nx) setup. In VsCode all works out of the box and I can't solution how to setup LSP in neovim.

Check out this thread https://github.com/pmizio/typescript-tools.nvim/issues/124#issuecomment-2118117142
