### ISSUE TITLE
Client 1 quit with exit code 1 and signal 0 jdtls

### ISSUE THREAD

**Issue by JjersaR** [neovim/nvim-lspconfig#1837]
### Description

Yesterday I upgraded my computer (Bedrock base fedora and installed arch), after a while I tried to check a .java file when I did it before it started jdtls but now it only detects null-ls, this last one I only use it for formatting, but now it gives me this "error": "Client 1 quit with exit code 1 and signal 0".

Before upgrading the system jdtls was working fine, but after that it does not start anymore.
I followed the debugging instructions for lsp and when I got to :lua vim.cmd('e'..vim.lsp.get_log_path()), I get this
![image](https://user-images.githubusercontent.com/86206596/163268369-816ea108-4308-41dd-b148-899d8b0fe005.png)

I have jdtls in the path and java installed.
![image](https://user-images.githubusercontent.com/86206596/163268501-76aaa8dd-83dc-44d2-9f5e-779bcfe96490.png)

The service is activated but simply does not start
![image](https://user-images.githubusercontent.com/86206596/163268641-8303202d-6b73-4e0b-87df-16580c9ad1c1.png)

### Neovim version

NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Bedrock Linux 0.7.27 Poki x86_64. Kernel: 5.17.2-300.fc36.x86_64 

### Affected language servers

Jdtls

### Steps to reproduce

I don't know, I just updated and it doesn't start anymore.
but if it works, I downloaded jdtls and all the jdk stuff from yay, since fedora is the base system.

### Actual behavior

This is the "error" I get
![image](https://user-images.githubusercontent.com/86206596/163271314-014e1903-9439-475a-83e9-d3ba9c836b29.png)
![image](https://user-images.githubusercontent.com/86206596/163268760-d53968c5-d0d4-4be7-afb5-a242ef859dda.png)

### Expected behavior

I hope it will start and show this
![image](https://user-images.githubusercontent.com/86206596/163271140-4195b0a9-5a75-4f4f-9222-6ee163938747.png)

### Minimal config

```Lua
https://github.com/JjersaR/nvim/blob/main/lua/java.lua
Inside the plugins configuration folder
```

### LSP log

https://gist.github.com/JjersaR/0758a0a19c834308da13798dd98913f1

**Comment by mjlbach** [comment]
Nothing in lspconfig or neovim has changed pertinent to jdtls, so you're going to have to debug your setup.

**Comment by JjersaR** [comment]
I tried to leave a version behind JDK by default and got an error that I could not access ~/ JDTLS /plugins/org.eclipse.equinox.launcher\_1.6.400.v20210924-0641.jar, but there is no such path, it only exists from /usr/share/java/, could that be it?
Or how can I debug it?

**Comment by mjlbach** [comment]
I would use https://github.com/mfussenegger/nvim-jdtls and re-follow the installation instructions from scratch.

**Comment by JjersaR** [comment]
Okay, thank you very much, I'll

**Comment by JjersaR** [comment]
It worked, deleted jdk and jdtls, cleared the cache, turned off the computer, turned it on, downloaded openjdk 17.0.2, and jdtls, entered a java file and everything is fine.
Thank you very much.
![image](https://user-images.githubusercontent.com/86206596/163433703-edf50674-2ce2-4f27-93b1-a6e7645d4424.png)

**Comment by yesiddev** [comment]
@JjersaR Thanks very much, works for me

**Comment by matthewgapp** [comment]
> 

I'm running into a similar issue. What "cache" did you clear? Also what version of openjdk were you running before?

**Comment by JjersaR** [comment]
On that occasion I had to delete jdtls that I downloaded by yay, clear the system cache, and that solved it, but I found an installer for jdtls.
[launcher](https://github.com/eruizc-dev/jdtls-launcher)

**Comment by TirtharajPramanik** [comment]
<img width="1080" alt="Screenshot 2023-05-07 at 9 04 03 PM" src="https://user-images.githubusercontent.com/81750507/236687381-0eb745ac-f932-4ca2-964d-d383217caea6.png">

We are using the same wallpaper and having the same issue. May be it's all a lie and the wallpaper playing pranks???

**Comment by sjakk** [comment]
> ### Description
> 
> Yesterday I upgraded my computer (Bedrock base fedora and installed arch), after a while I tried to check a .java file when I did it before it started jdtls but now it only detects null-ls, this last one I only use it for formatting, but now it gives me this "error": "Client 1 quit with exit code 1 and signal 0".
> 
> Before upgrading the system jdtls was working fine, but after that it does not start anymore. I followed the debugging instructions for lsp and when I got to :lua vim.cmd('e'..vim.lsp.get_log_path()), I get this ![image](https://user-images.githubusercontent.com/86206596/163268369-816ea108-4308-41dd-b148-899d8b0fe005.png)
> 
> I have jdtls in the path and java installed. ![image](https://user-images.githubusercontent.com/86206596/163268501-76aaa8dd-83dc-44d2-9f5e-779bcfe96490.png)
> 
> The service is activated but simply does not start ![image](https://user-images.githubusercontent.com/86206596/163268641-8303202d-6b73-4e0b-87df-16580c9ad1c1.png)
> ### Neovim version
> 
> NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3
> ### Nvim-lspconfig version
> 
> _No response_
> ### Operating system and version
> 
> Bedrock Linux 0.7.27 Poki x86_64. Kernel: 5.17.2-300.fc36.x86_64
> ### Affected language servers
> 
> Jdtls
> ### Steps to reproduce
> 
> I don't know, I just updated and it doesn't start anymore. but if it works, I downloaded jdtls and all the jdk stuff from yay, since fedora is the base system.
> ### Actual behavior
> 
> This is the "error" I get ![image](https://user-images.githubusercontent.com/86206596/163271314-014e1903-9439-475a-83e9-d3ba9c836b29.png) ![image](https://user-images.githubusercontent.com/86206596/163268760-d53968c5-d0d4-4be7-afb5-a242ef859dda.png)
> ### Expected behavior
> 
> I hope it will start and show this ![image](https://user-images.githubusercontent.com/86206596/163271140-4195b0a9-5a75-4f4f-9222-6ee163938747.png)
> ### Minimal config
> 
> ```lua
> https://github.com/JjersaR/nvim/blob/main/lua/java.lua
> Inside the plugins configuration folder
> ```
> 
> ### LSP log
> 
> https://gist.github.com/JjersaR/0758a0a19c834308da13798dd98913f1

it happens when you have an external installation of lsp-server binary set in path and other installation(mason for example) both enters in conflict.  or you have an lsp-server binary in workspace i did theses two methods to reproduce this error

**Comment by sureshsaragadam** [comment]
Client 1 quit with exit code 1 and signal 0

In my case when i am setting up LSP for front-end environment, i got the same error, later i update the node -v to v18.17.0 this  error has been solved in neovim automatically after updating Node Version from NVM. 

I guess such any error may be related to version conflict also.
