### ISSUE TITLE
How can i setup typescript-lit-html-plugin for the tsserver?

### ISSUE THREAD

**Issue by lluar** [neovim/nvim-lspconfig#1839]
### Description

Is it possible to use tsserver plugin?

https://github.com/microsoft/typescript-lit-html-plugin
I tried the installation in the project but it does not work. 

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

arch linux

### Affected language servers

tsserver

### Steps to reproduce

-

### Actual behavior

-

### Minimal config

```Lua
-
```

### LSP log

-

**Comment by mjlbach** [comment]
You'll have better luck posting on our [support forum](https://neovim.discourse.group/c/language-server-protocol-lsp/7), as this is more of a usage question then an issue/bug with lspconfig.
