### ISSUE TITLE
server_configuration.md does not match jsonls.lua

### ISSUE THREAD

**Issue by pluma9** [neovim/nvim-lspconfig#1840]
### Language server

jsonls

### Requested feature

The content of the jsonls section in server_configuration.md does not match the content of jsonls.lua

**Comment by mjlbach** [comment]
Can you be more specific?

<img width="1124" alt="image" src="https://user-images.githubusercontent.com/13316262/163685399-f491fb0a-d797-4e6e-9b6f-cb383a0418dd.png">
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/13316262/163685413-3c6286cb-83ef-42ce-84cc-e7a900700f06.png">

**Comment by mjlbach** [comment]
Please file a new issue showing the difference between what is in server_configurations.md and jsonls.lua, preferably by linking the relevant urls on github.
