### ISSUE TITLE
lua commands remain undefined on Windows

### ISSUE THREAD

**Issue by jwmng** [neovim/nvim-lspconfig#185]
- `nvim --version`:
```
NVIM v0.5.0-418-g87d892afa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```
- nvim-lsp version(commit hash): Not sure, latest from `vim-plug` as per today

- `:checkhealth` result
```
health#nvim_lsp#check
========================================================================
  - ERROR: Failed to run healthcheck for "nvim_lsp" plugin. Exception:
    function health#check[21]..health#nvim_lsp#check, line 2
    Vim(lua):E5108: Error executing lua ...pData\Roaming\nvim\plug\nvim-lsp\lua\nvim_lsp/health.lua:7: attempt to call field 'make_config' (a nil value)

(snipped the rest, python 2 and 3 providers present and working)
```

- What language server(If the problem is related to a specific language server): I tried only  `pyls_ms` as the others require npm/mkdir
- Operating system/version: Windows 10 build 1809
- Terminal name/version: I'm using nvim-qt
- `$TERM`: n/a

### How to reproduce the problem from neovim startup
- Install nvim-lsp through vim-plug
- Install dotnet core runtime
- `:LspInstall pyls_ms`
- `:LspInstallInfo`

### Actual behaviour

See screenshot, it tries to find/install the DLL in a temorary location. This directory remains empty. 
![image](https://user-images.githubusercontent.com/10427132/78356671-47f2a680-75b0-11ea-9e56-e6c3c624bebc.png)

I can pass settings and call `nvim_lsp#setup()` but it seems it remains undefined:
`E117: Unknown function nvim_lsp#setup()`.

`scriptnames` shows that the plugin is loaded:
![image](https://user-images.githubusercontent.com/10427132/78356829-a1f36c00-75b0-11ea-91ee-6fe8e0a9dd8d.png)

### Expected behaviour
Installs the pyls_ms language server

**Comment by jwmng** [comment]
So I did some extra tests.
Apparently the `:LspInstall` is not completely working for windows.
Also, I cannot call `nvim_lsp#setup()` from `init.vim`, which seems to be normal (as the docs recommend using the lua configuration).

Added this to `init.vim`:
```vim
lua<<
    require'nvim_lsp'.pyls_ms.setup{}
.
```
When I now open a python file I get the same error message as in #136 .

**Comment by mjlbach** [comment]
I added the microsoft python language server, as I mainly develop on linux/mac we agreed at the time to merge without windows support. I can help debug this a bit; essentially all LspInstall does is fetch the nupkg with curl and extract it. If you check in the cache directory you listed, do you see the files propely extracted? The other thing to check is if dotnet exec MicrosoftPythonLanguageServer.dll works in that directory.

**Comment by jwmng** [comment]
Hi,

The install dir remains empty. I tried to run some of the commands in the script by hand and it seems like the `curl` call is failing because windows' curl command is a wrapper for `Invoke-Webrequest` that takes very different (non-unix) arguments,
In this order:
1. `get_latest_pyls()` returns `nil` as the plain `curl` call returns a status rather than data.
  `(curl %s).Content` seems to give the right output in powershell, but somehow when I pass this to `io.popen` in the script, it doesn't return any content. I guess my lua isn't good enough to find out why.
2. The `curl` command to get the nupkg fails as `-fLo` is unrecognized and should be `curl %s -Outfile %s`
3. `Expand-Archive` fails because it will only take files with `.zip` extension and uses `-DestinationPath` instead of `-d`. Renaming to a zip file works.

I can make it work like this if I supply the version by hand:
```powershell
curl https://pvsc.azureedge.net/python-language-server-stable/Python-Language-Server-win-x64.0.1.80.nupkg -Outfile C:\Users\***\AppData\Local\Temp\nvim\nvim_lsp\pyls_ms/pyls_ms.zip
Expand-Archive -Force C:\Users\***\AppData\Local\Temp\nvim\nvim_lsp\pyls_ms\pyls_ms.zip -DestionationPath C:\Users\***\AppData\Local\Temp\nvim\nvim_lsp\pyls_ms\
dotnet exec C:\Users\***\AppData\Local\Temp\nvim\nvim_lsp\pyls_ms\Microsoft.Python.LanguageServer.dll
```

It would all be much easier and probably succeed at once if the 'unix' `curl` command, but it seems that in PowerShell, there isn't a convenient way to override this.

**Comment by mjlbach** [comment]
Thanks for the detailed writeup, I just added get_latest_pyls() recently but didn't test it on Windows. For now, I can manually add separate download/extracting logic under the windows option. Once you've added manually downloaded and extracted it, is everything else working?

**Comment by jwmng** [comment]
Yes it works fine with the following config:
```
lua<<
    require'nvim_lsp'.pyls_ms.setup{
    cmd = {"dotnet", "exec", "C:/Users/jwy/AppData/Local/Temp/nvim/nvim_lsp/pyls_ms/Microsoft.Python.LanguageServer.dll"}
}
.
```
