### ISSUE TITLE
Support standalone files for rust-analyzer

### ISSUE THREAD

**Issue by EJammy** [neovim/nvim-lspconfig#1854]
### Language server

rust-analyzer

### Requested feature

Rust-analyzer added support for standalone files in https://github.com/rust-lang/rust-analyzer/pull/8955. However, this requires "`detachedFiles` with the absolute paths to the standalone files passed as a field of the initialization options". Given my limited experience and lack of knowledge on LSP, I couldn't figure out what this means or how to do this. I assume this can be configured, so it'll be great if someone can make this work.

### Other clients which have this feature

coc.nvim with coc-rust-analyzer

**Comment by mjlbach** [comment]
I would recommend using rust-tools, lspconfig is not going to add support for something specific to rust analyzer, we send NULL for workspaceFolders which should accomplish the same thing.
