### ISSUE TITLE
`vim.lsp.diagnostic.goto_prev()`, `vim.lsp.diagnostic.goto_next()`, and `vim.diagnostic.open_float()` are not working for `julials`

### ISSUE THREAD

**Issue by tapyu** [neovim/nvim-lspconfig#1856]
### Description

The `vim.diagnostic.*` functionalities of the `jullials` are not working. In the [`minimal.init` template](https://github.com/neovim/nvim-lspconfig/blob/fe69f8b808dc677ba35772a85508a805f53a2dc6/test/minimal_init.lua#L61-L64), theses functions are mapped with `vim.lsp.diagnostic.*` functions, which prompts a deprecated warning when I try to use them.

In the `:h deprecated`, I could see what is the actual function that should me called, and I noticed some errors/inconsistencies.

### Neovim version

```
NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

### Nvim-lspconfig version

fe69f8b808dc677ba35772a85508a805f53a2dc6

### Operating system and version

x86_64 Linux 5.15.32-1-MANJARO

### Affected language servers

julials

### Steps to reproduce

1. install packer
2. Download the [`minimal_julials_init.lua`](https://gist.github.com/tapyu/fd96f5977e311eb8caabd008a209865f#file-minimal_julials_init-lua) config file
3. Install `julials` with
   ```
   julia --project=~/.julia/environments/nvim-lspconfig -e 'using Pkg; Pkg.add("LanguageServer")'
   ```
   as described in the [documentation](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#julials). [See here](https://github.com/julia-vscode/LanguageServer.jl/wiki/Vim-and-Neovim#languageclient-neovim) for more info
5. open `nvim -w minimal_julials_init.lua test.jl`, where `test.jl` is any `julia` file
6. run `:LspInfo` to check if `julials` is attached to the opened file. If is not, run `:LspStart julials`.
7. May it is necessary to wait a couple of seconds until `lspconfig` download all the cache data :)
8. Check the basic functionalities of this LSP.

### Actual behavior

- :warning: `<Cmd>lua vim.lsp.buf.declaration()`  (mapped to `gD`): It prompts an error:
  ```
  method textDocument/declaration is not supported by any of the servers registered for the current buffer
  ```
  It is not out fault. As far as I know, it is a limitation of [LanguageServer.jl](https://github.com/julia-vscode/LanguageServer.jl) that do not provide such capability
- :heavy_check_mark: `lua vim.lsp.buf.definition()`  (mapped to `gd`): worked
- :heavy_check_mark: `lua vim.lsp.buf.hover()`  (mapped to `K`): worked
- :warning: `lua vim.lsp.buf.implementation()` (mapped to `gi`): Not supported, let it go.
- :heavy_check_mark: `vim.lsp.buf.signature_help()` (mapped to `<C-k`): worked
- :heavy_check_mark: `vim.lsp.buf.add_workspace_folder()` (mapped to `<space>wa`): worked
- :heavy_check_mark: `vim.lsp.buf.remove_workspace_folder()` (mapped to `<space>wr`): worked
- :heavy_check_mark:  `print(vim.inspect(vim.lsp.buf.list_workspace_folders()))` (mapped to `<space>wl`): worked
- :warning:  `vim.lsp.buf.type_definition()` (mapped `<space>D`): Not supported, let it go.
- :heavy_check_mark: `lua vim.lsp.buf.rename()` (mapped to `<space>rn`): worked
- :heavy_check_mark: `vim.lsp.buf.references()` (mapped to `gr`): worked, even though some references is not found, I do not know why
- :x: `lua vim.lsp.diagnostic.show_line_diagnostics()` (mapped to `<space>e`): A warning prompts showing "vim.lsp.diagnostic.show_line_diagnostics is deprecated. See :h deprecated". In the documentation I could notice that
  ```
  The following have been replaced by vim.diagnostic.open_float().
  vim.lsp.diagnostic.show_line_diagnostics()
  vim.lsp.diagnostic.show_position_diagnostics()
  ```
  When I try to run `:lua vim.diagnostic.open_float()`, nothing happens...
- :x: `vim.lsp.diagnostic.goto_prev()` and `vim.lsp.diagnostic.goto_next()` (mapped to `[d` and `]d`, respectively): They are as well. They updated funciton of both should be `vim.diagnostic.show()`. When I try `:lua vim.diagnostic.show()`, nothing happen again.
- :warning: `lua vim.lsp.diagnostic.set_loclist()` (mapped to `<space>q`): Deprecated again. The function should be `vim.diagnostic.setloclist()`. When I try `:lua vim.diagnostic.setloclist()`, it works.

### Expected behavior

1. The `minimal_init.lua` should not be using the deprecated function to assess to functionality of a given plugin
2. The commands `:lua vim.diagnostic.*` should work properly, but it doesn't.
3. In my humble opinion, the [documentation](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md) is terribly incomplete with regard to the `julials` capabilities. How will a beginner make out what features a given LSP provides? Even if he could search into the LSP capabilities documentation, I think it is worth to put a link of the capabilities list for a given LSP in the `lspconifg` documentation.

If you all agree with I my statements (I hope so), let me know, I can provide such such improvements through a PR when a have a "free time' :)

### Minimal config

```Lua
It is equal to `miniminal_init.lua`, but set to `julials`:


local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'julials'
  local cmd = { "julia", "--startup-file=no", "--history-file=no", "-e", '    # Load LanguageServer.jl: attempt to load from ~/.julia/environments/nvim-lspconfig\n    # with the regular load path as a fallback\n    ls_install_path = joinpath(\n        get(DEPOT_PATH, 1, joinpath(homedir(), ".julia")),\n        "environments", "nvim-lspconfig"\n    )\n    pushfirst!(LOAD_PATH, ls_install_path)\n    using LanguageServer\n    popfirst!(LOAD_PATH)\n    depot_path = get(ENV, "JULIA_DEPOT_PATH", "")\n    project_path = let\n        dirname(something(\n            ## 1. Finds an explicitly set project (JULIA_PROJECT)\n            Base.load_path_expand((\n                p = get(ENV, "JULIA_PROJECT", nothing);\n                p === nothing ? nothing : isempty(p) ? nothing : p\n            )),\n            ## 2. Look for a Project.toml file in the current working directory,\n            ##    or parent directories, with $HOME as an upper boundary\n            Base.current_project(),\n            ## 3. First entry in the load path\n            get(Base.load_path(), 1, nothing),\n            ## 4. Fallback to default global environment,\n            ##    this is more or less unreachable\n            Base.load_path_expand("@v#.#"),\n        ))\n    end\n    @info "Running language server" VERSION pwd() project_path depot_path\n    server = LanguageServer.LanguageServerInstance(stdin, stdout, project_path, depot_path)\n    server.runlinter = true\n    run(server)\n  ' }
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

https://gist.github.com/tapyu/ab09a18874d81866805fb22850e7e803

**Comment by mjlbach** [comment]
> May it is necessary to wait a couple of seconds until lspconfig download all the cache data :)

This isn't a thing. Why did you guess or assume this?

julia-language-server has a long delay period until it finishes indexing. There's nothing we can do about this.

> The minimal_init.lua should not be using the deprecated function to assess to functionality of a given plugin

I kept the minimal init.lua backwards compatible, it's sole purpose is for filing GH issues. The deprecated functions alias to the new functions, other than a harmless warning it still works. I've removed backwards compatibility in a commit this morning.

> In my humble opinion, the [documentation](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md) is terribly incomplete with regard to the julials capabilities. How will a beginner make out what features a given LSP provides?

Reading the upstream julia language server documentation. We're not going to exhaustively duplicate language server documentation here.

I'm not sure what the main point to address was in this issue, the issue title and body don't seem to align. I removed the deprecated examples in the minimal init.lua

**Comment by tapyu** [comment]
> This isn't a thing. Why did you guess or assume this? julia-language-server has a long delay period until it finishes indexing. There's nothing we can do about this.

Ok, fine! Let's go on. I never said it's a problem, let alone a `nvim-lspconfig` problem. I just commented. No probls...

> I've removed backwards compatibility in a commit this morning.

Great! :)

>  We're not going to exhaustively duplicate language server documentation here.

Duplicate the documentation??? I've never said that! My idea I just leave a link to the language server documentation for the reader. Let me make a PR and you gonna see what I mean. If you dislike, just reject it, no grudge :+1: 

> I'm not sure what the main point to address was in this issue

This issue's point is: `vim.lsp.diagnostic.goto_prev()`, `vim.lsp.diagnostic.goto_next()`, and `vim.diagnostic.open_float()` are not working for `julials`. I just change the issue's title to make it clear.

Thank you for the collaboration.

**Comment by jfecher** [comment]
In case anyone else is looking at this issue with the same error of `vim.lsp.diagnostic.goto_next()` and goto_prev no longer working, what fixed it for me was changing the path to remove `.lsp`. The new commands should be:
`vim.diagnostic.goto_next()` and
`vim.diagnostic.goto_prev()`
