### ISSUE TITLE
lsp server pyright  import could not be resolved

### ISSUE THREAD

**Issue by yangqi766** [neovim/nvim-lspconfig#1861]
### Description

I mean that the file account/views/oj.py cannot import files in the directory、options、utils、problem.
![企业微信截图_20220426092848](https://user-images.githubusercontent.com/13087771/165200841-1b8bc67c-99a3-49c5-be16-e81469b9e386.png)

And，the pyright installed by nvim-lsp-installer and nvim-lsp-config in neovim  all config items  are default.  But when i use vscode , after install the pyright , all is well.

![企业微信截图_20220426093047](https://user-images.githubusercontent.com/13087771/165201037-7a7713fc-55cf-48ae-b578-cc09b14e07b5.png)

![企业微信截图_20220426093552](https://user-images.githubusercontent.com/13087771/165201492-a595ba58-c81f-454e-ae53-018990d0ca26.png)

![企业微信截图_20220426093727](https://user-images.githubusercontent.com/13087771/165201643-a3898f45-9265-4a34-8302-f97ce26df348.png)

### Neovim version

NVIM v0.7.0-dev+1269-g746a29c58
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

710deb04d9f8b73517e1d995a57a1505cbbaac51

### Operating system and version

ubuntu 20.04

### Affected language servers

python

### Steps to reproduce

when open the python project , import other directory files 

### Actual behavior

import "problem.models" could not be resolved

### Expected behavior

I think it is all is right , also like when i use pyright in vscode ,the config is same.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

vim.lsp.set_log_level('debug')

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end

    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.diagnostic.open_float()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.diagnostic.setloclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'pyright'
  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

[INFO][2022-04-26 10:01:52] .../vim/lsp/rpc.lua:261	"Starting RPC client"	{   args = { "--stdio" },   cmd = "pyright-langserver",   extra = {     cwd = "/home/za/.config/nvim"   } }

**Comment by lithammer** [comment]
Did you activate the virtualenv before starting Neovim?

**Comment by yangqi766** [comment]
The two methods of activation and deactivation are such prompt and error message.

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.

**Comment by lithammer** [comment]
> I get a similar behavior on my projects. In my case the virtualenv is handled by poetry.

You still need to activate the virtualenv before starting Neovim regardless if you're using virtualenv manager like poetry. There's no logic here to automatically find the correct Python interpreter. I think Pyright itself will just look for `python` and/or `python3` in your `$PATH`.

You can guide it using a `pyrightconfig.json` file though:

```json
{
  "venvPath": "/path/to/folder/with/virtualenv",
  "venv": "env"
}
```

https://github.com/microsoft/pyright/blob/main/docs/configuration.md

**Comment by caetanosauer** [comment]
@yangqi766 Have you checked if the root of your project matches one of the root file names in the [default config](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/pyright.lua)? I had the same errors as you, and I fixed. it by passing an additional `WORKSPACE` file name that is used in our Bazel project.

```lua
local lspconfig = require('lspconfig')
local python_root_files = {
  'WORKSPACE', -- added for Bazel; items below are from default config
  'pyproject.toml',
  'setup.py',
  'setup.cfg',
  'requirements.txt',
  'Pipfile',
  'pyrightconfig.json',
}
lspconfig["pyright"].setup {
    on_attach = on_attach,
    root_dir = lspconfig.util.root_pattern(unpack(python_root_files))
}
```

**Comment by SichangHe** [comment]
This worked for me.
https://www.reddit.com/r/neovim/comments/x7dann/pyright_diagnoses_error_import_could_not_be/

**Comment by YiHui-Liu** [comment]
> > I get a similar behavior on my projects. In my case the virtualenv is handled by poetry.
> 
> You still need to activate the virtualenv before starting Neovim regardless if you're using virtualenv manager like poetry. There's no logic here to automatically find the correct Python interpreter. I think Pyright itself will just look for `python` and/or `python3` in your `$PATH`.
> 
> You can guide it using a `pyrightconfig.json` file though:
> 
> {
>   "venvPath": "/path/to/folder/with/virtualenv",
>   "venv": "env"
> }
> https://github.com/microsoft/pyright/blob/main/docs/configuration.md

it not works for me. I'm using `python -m venv venv` to create a virtual environment, here is my configuration:
```json
{
    "venvPath": "/home/fox/foxScripts/MTPC-Alert",
    "venv": "venv"
}
```
however, pyright raises some error:
![Image](https://github.com/user-attachments/assets/4708afff-66ed-43a9-abf7-cc15b8be7fd0)
