### ISSUE TITLE
Can not find the texlab after using setup{}

### ISSUE THREAD

**Issue by xyegithub** [neovim/nvim-lspconfig#1868]
### Description

I add 
```lua 
require('lspconfig').texlab.setup {
  settings = {
    latexindent = {
      modifyLineBreaks = true,
    },
  },
}
``` 
to my init.lua. Then open a tex file. An error accur `Spawning language server with cmd: `texlab` failed. The language server is either not installed, missing from PATH`.  However, when the `setup {}` function is removed from the init.lua, the texlab initializes correctly.

### Neovim version

NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

ad9903c66bac88f344890acb6532f63f1cd4dac3

### Operating system and version

WSL Ubuntu 20.04.4

### Affected language servers

texlab

### Steps to reproduce

1. install the texlab by `nvim-lsp-installer`, which is installed in `~/.local/share/nvim/lsp_servers/latex` by default and not in the $PATH.
2. Then texlab can be correctly initialized.
3. add 
```lua 
require('lspconfig').texlab.setup {
  settings = {
    latexindent = {
      modifyLineBreaks = true,
    },
  },
}
```  
to the init.lua. Then texlab failed to be initialized when open a tex file.
4. add `~/.local/share/nvim/lsp_servers/latex` to the $PATH. Then the texlab is initialized correctly. However, `modifyLineBreaks = true,` does not work.

### Actual behavior

When open a tex file an error accur `Spawning language server with cmd: `texlab` failed. The language server is either not installed, missing from PATH`.  

### Expected behavior

Correctly initialize the texlab when open a tex file and `modifyLineBreaks = true` works.

### Minimal config

```Lua
lunarvim is used.
```

### LSP log

[START][2022-04-27 19:15:54] LSP logging initiated [INFO][2022-04-27 19:15:54] .../vim/lsp/rpc.lua:261	"Starting RPC client"	{  args = {},  cmd = "texlab",  extra = {    cwd = "/home/LunarVim/temp_try"  }} [INFO][2022-04-27 19:15:54] .../vim/lsp/rpc.lua:261	"Starting RPC client"	{  args = {},  cmd = "texlab",  extra = {    cwd = "/home/LunarVim/temp_try"  }} [START][2022-04-27 19:16:41] LSP logging initiated

**Comment by mjlbach** [comment]
> install the texlab by nvim-lsp-installer, which is installed in ~/.local/share/nvim/lsp_servers/latex by default and not in the $PATH.

Issues that require a plugin to reproduce are not issues that should be filed here.
