### ISSUE TITLE
Alternative project local settings

### ISSUE THREAD

**Issue by henry-hsieh** [neovim/nvim-lspconfig#1874]
### Requested feature

I'm aware of there is a Wiki page for [project local settings](https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings). It uses `set exrc` that Neovim will execute the .nvimrc or .exrc of the current directory. However, the `set exrc` is not secure. Moreover, the option is not usable at latest release version of Neovim (0.7.0).

Coc uses .vim/coc-settings.json as [local configuration file](https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file) instead of using script. I thought that other LSP clients use configuration files, too. It's more secure by parsing configuration file.

### Other clients which have this feature

coc.nvim

**Comment by uggedal** [comment]
For per project level virtualenv paths with pylsp I did the following:

```lua
local jedi_env = function(env)
  return {
    pylsp = {
      plugins = {
        jedi = {
          environment = env,
        },
      },
    },
  }
end

lspconfig.pylsp.setup({
  on_init = function(client)
    local path = client.workspace_folders[1].name

    if path == '/home/foo/src/project1' then
      client.config.settings = jedi_env('/home/foo/.local/pipx/venvs/pyinfra')
    elseif path == '/home/foo/src/project2' then
      client.config.settings = jedi_env('./venv')
    end

    client.notify('workspace/didChangeConfiguration')
    return true
  end,
})
```

**Comment by henry-hsieh** [comment]
I recently realized that Neovim has a built-in function for converting JSON to Lua table. All you need to do is parsing setting files at root directory and assign to LSP settings.

The example is in my pull request of [svlangserver](https://github.com/neovim/nvim-lspconfig/pull/1916/files). Check the `on_init` function at line 38.

**Comment by henry-hsieh** [comment]
> For per project level virtualenv paths with pylsp I did the following:
> 
> ```lua
> local jedi_env = function(env)
>   return {
>     pylsp = {
>       plugins = {
>         jedi = {
>           environment = env,
>         },
>       },
>     },
>   }
> end
> 
> lspconfig.pylsp.setup({
>   on_init = function(client)
>     local path = client.workspace_folders[1].name
> 
>     if path == '/home/foo/src/project1' then
>       client.config.settings = jedi_env('/home/foo/.local/pipx/venvs/pyinfra')
>     elseif path == '/home/foo/src/project2' then
>       client.config.settings = jedi_env('./venv')
>     end
> 
>     client.notify('workspace/didChangeConfiguration')
>     return true
>   end,
> })
> ```

I updated the project local settings in [Wiki page](https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings). I think that your method should be default method for project local settings because [replacement](https://github.com/neovim/neovim/issues/5784#issuecomment-506993689) of `exrc` is detecting path in personal vimrc.

[nlsp-settings.nvim](https://github.com/tamago324/nlsp-settings.nvim) provides project local settings likes coc.nvim for lspconfig. Therefore, my custom json loader can be replaced by it.
