### ISSUE TITLE
Default suggested key mapping as an option

### ISSUE THREAD

**Issue by ubitux** [neovim/nvim-lspconfig#1877]
### Language server

Any

### Requested feature

Would it be possible to have access to the default suggested key-mappings as an option? I kind of understand why they are not enabled by default, but I would argue that most people are not enthusiastic at the idea of copy/pasting 50 lines of code into their config and regularly check out the repository's README in order to check if it needs to be adjusted.

I believe it would help integration tremendously if we could enable the whole LSP features out of the box with a single line such as:

```lua
require('lspconfig')[lsp].setup{on_attach=lspconfig_default_bindings}
```

IMO I would go even further and propose to have:

```lua
local servers = { 'pyright', 'rust_analyzer', 'tsserver' }
require('lspconfig').setup(servers)
```

**Comment by glepnir** [comment]
Everyone's key mappings are different. Of course provide default key maps can satisfy some people. But it will also annoy others that they need to remap and unbind the default keymap then set their own keymap.  This project only provides server configuration for lsp server. This is just my personal opinion. Please correct me if there are any mistakes .

**Comment by ubitux** [comment]
Everyone's key mappings are different because they are not provided… Imagine if every use had to set all the bindings of vim? I don't understand this logic.

**Comment by glepnir** [comment]
> Everyone's key mappings are different because they are not provided

I don't know this logic. like I like use the `K` to show hover doc .other people like use `T` . If we set the default keymap hover to `K`. other people will like this ? I don't think so. they will want to unbind the default keymap and rebind it to `T`

**Comment by ubitux** [comment]
> > Everyone's key mappings are different because they are not provided
> 
> I don't know this logic. like I like use the `K` to show hover doc .other people like use `T` . If we set the default keymap hover to `K`. other people will like this ? I don't think so. they will want to unbind the default keymap and rebind it to `T`

Then they can just do that? Right now all the users have to carry the burden or configuring all the bindings.

**Comment by glepnir** [comment]
And it can be dynamic if the keymap is set in `on_attach`. For example, check whether the server supports a certain provider. Then do key bindings.

```lua
on_attatch = function(client.bufnr)
if client.server_capabilities.formatProvider then
  bind buffer map
end
end
```

**Comment by ubitux** [comment]
My first suggestion is to simply add a function that users would be free to use or not. But instead of asking all the users to copy/paste a random blob that is going to change randomly, a single line will be required for users who wish to have sane defaults.

**Comment by glepnir** [comment]
> Then they can just do that? Right now all the users have to carry the burden or configuring all the bindings.

Of course. it will be troublesome for this part of the people I think. Maybe some newbies. would they like it ?

**Comment by glepnir** [comment]
> My first suggestion is to simply add a function that users would be free to use or not

```lua
function lsp_keymap(bufnr)
  local bufopts = { noremap=true, silent=true, buffer=bufnr }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, bufopts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, bufopts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, bufopts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, bufopts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, bufopts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, bufopts)
  vim.keymap.set('n', '<space>ca', vim.lsp.buf.code_action, bufopts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
end
```
then you can use this function in everywhere you want. is this a hassle ？T.T

**Comment by ubitux** [comment]
> > My first suggestion is to simply add a function that users would be free to use or not
> 
> ```lua
> function lsp_keymap(bufnr)
>   local bufopts = { noremap=true, silent=true, buffer=bufnr }
>   vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, bufopts)
>   vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
>   vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
>   vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
>   vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, bufopts)
>   vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, bufopts)
>   vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, bufopts)
>   vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, bufopts)
>   vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, bufopts)
>   vim.keymap.set('n', '<space>ca', vim.lsp.buf.code_action, bufopts)
>   vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
> end
> 
> lspconfig.someserver.({
>   on_attatch = function(client , bufnr)
>     lsp_keymap(bufnr)
>   end
> })
> ```
> 
> then you can use this function in everywhere you want. is this a hassle ？T.T

**Yes.**

I don't want to have to code half my editor configuration configuring random bindings and monitoring the stuff to copy/paste from dozens of plugins README. Configuring the neovim LSP is currently a nightmare TBH, because the integration work is pretty much non-existent.

I don't have any issue with the ability to let some power users with 100k LoC to configure their editor, but for the vast majority of casual vim users who want an out-of-the-box experience, it's just the worse. Please just provide some sane defaults to facilitate this.

**Comment by gegoune** [comment]
There also is https://github.com/nanotee/nvim-lsp-basics attempting just that. Please have a look at https://github.com/nanotee/nvim-lsp-basics/issues/1 which lists various considerations regarding keymaps - it's not that simple to come up with sane defaults which might be partially the reason behind them not being set up for an user (which I would pretty much like to have as well).

**Comment by glepnir** [comment]
Yes. It's hard to figure out some sensible default keys and make sure they don't conflict.

**Comment by ubitux** [comment]
Do you really want to leave this issue closed?

**Comment by glepnir** [comment]
for me there is no necessary to add this. check the roadmap `nvim-lspconfig` you may know more about this project do. 
 I will follow his @justinmk  advice .

**Comment by justinmk** [comment]
We'll eventually add something to core that helps here. Out of scope for nvim-lspconfig.
