### ISSUE TITLE
Improve server configuration documentation

### ISSUE THREAD

**Issue by gerazov** [neovim/nvim-lspconfig#1880]
### Language server

pylsp

### Requested feature

It took me while to figure out how to enable disable plugins in the `pylsp` server. One thing I don't find very useful is the McCabe complexity check. Finally I got it working via the `lspconfig` setup function using:
```lua
require('lspconfig').pylsp.setup {
  on_attach = on_attach,
  flags = {
    -- This will be the default in neovim 0.7+
    debounce_text_changes = 150,
  },
  settings = {
    pylsp = {
      plugins = {
        -- pylint = { enabled = true },
        mccabe = { enabled = false }
      }
    }
  }
}
```

This might be server specific, but it would be nice to have this in the documentation to make it easier for people to find and tweak their server settings. I found these listed via `:LspInstallInfo` from [williamboman/nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer).

![image](https://user-images.githubusercontent.com/15214418/166215810-f15af383-9fac-466a-ab52-e4f364126267.png)

**Comment by justinmk** [comment]
There is a huge amount of docs in this repo. Check carefully.

If there is a specific tweak to those docs needed, send a PR.
