### ISSUE TITLE
resolved_capabilities is deprecated, update your plugins or configuration to access client.server_capabilities i nstead.The new key/value pairs in server_capabilities directly match those defined in the language server protocol

### ISSUE THREAD

**Issue by xaotag** [neovim/nvim-lspconfig#1891]
### Description

![Uploading image.png…]()

### Neovim version

NVIM v0.8.0-dev+127-g3ec93ca92c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

arch   5.17.5-arch1-1

### Affected language servers

all 

### Steps to reproduce

/

### Actual behavior

/

### Minimal config

```Lua
/
```

### LSP log

/

**Comment by phaazon** [comment]
Same thing and I can’t figure out which plugin is causing that.

**Comment by WillEhrendreich** [comment]
I'm also interested in the solution

**Comment by gegoune** [comment]
https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767

**Comment by asmodeus812** [comment]
I have another question, we have capabilities object which is usually passed in with the config before the server is started, while the old resolved capabilities were intercepted and set after the server was started. How do we preemptively set capabilities during the config stage of any lang server ?

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/how-to-config-multiple-lsp-for-document-hover/3093/2
