### ISSUE TITLE
Tilt LSP Support

### ISSUE THREAD

**Issue by hbjydev** [neovim/nvim-lspconfig#1895]
### Language server

tilt lsp

### Requested feature

It'd be useful to get the Tilt LSP server added to this. The command to start [according to the docs](https://docs.tilt.dev/cli/tilt_lsp_start.html) should be `tilt lsp start`, it uses stdio mode by default.

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
