### ISSUE TITLE
Update deprecated Grammarly server

### ISSUE THREAD

**Issue by rober-m** [neovim/nvim-lspconfig#1896]
### Language server

grammarly

### Requested feature

The current Grammarly server is deprecated (See: [repo](https://github.com/emacs-grammarly/unofficial-grammarly-language-server)). The new server is [this one](https://github.com/emacs-grammarly/grammarly-language-server).

It would be great if someone could update it! :)

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
