### ISSUE TITLE
nvim-cmp and tsserver are not finding new react components to import

### ISSUE THREAD

**Issue by lucaspeixotot** [neovim/nvim-lspconfig#1897]
### Description

I'm using nvim-lspconfig and nvim-cmp and I have a setup for golang, c++, java and other languages. Today I'm trying to have a setup for react development, so I'm using tsserver. However, I'm not able to complete code with new react components that I created. Look the image below:

![image](https://user-images.githubusercontent.com/11475476/167698279-daa2e5cd-c895-4284-94c8-c850e8aa434f.png)

### Neovim version

NVIM v0.8.0-dev
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by lucas@adpasp

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

### Operating system and version

Ubuntu 20.04

### Affected language servers

tsserver

### Steps to reproduce

1. npx create-react-app folder
2. touch folder/src/component.js
3. edit component.js file to return some JSX code
4. nvim folder/src/App.js
5. try to auto complete the component that you just created

### Actual behavior

![Uploading image.png…]()

### Expected behavior

Testcomponent appears as an option to auto complete.

### Minimal config

```Lua
https://github.com/lucaspeixotot/dotfiles/tree/master/.config/nvim
```

### LSP log

https://gist.github.com/lucaspeixotot/48919507b60f57d3d5d22660985f8d87

**Comment by justinmk** [comment]
This is not a support channel. Send a PR with a clear explanation, or ask questions elsewhere. This repo is best-effort.
