### ISSUE TITLE
Fortran Language Server outdated

### ISSUE THREAD

**Issue by gnikit** [neovim/nvim-lspconfig#1900]
### Language server

fortls

### Requested feature

The `fortls` link that is listed in the documentation [see](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#fortls) is quite outdated (and presumed abandoned). I have taken over the work for some time now, for developing and maintaining a Fortran Language Server https://github.com/gnikit/fortls.
The server is mostly backwards compatible with the old one  (hence why the binary name is `fortls`) so it should break people's workflows.

I am opening the issue because I am not sure if the old reference to `fortls` should be removed or a new entry should be added with `fortls` referring to the new server and `fortran-language-server` to the old one.

I am also having a look at the setup instructions listed for the server because I am not convinced they are correct.

**Comment by justinmk** [comment]
> I am not sure if the old reference to `fortls` should be removed or a new entry should be added with `fortls` referring to the new server and `fortran-language-server` to the old one.

Just remove the old one. PR welcome.

These configs are not intended to be backwards-compatible. People need to either upgrade, or use a custom config. nvim-lspconfig is just a starting point. We can't maintain zillions of backwards-compatible configs.

PR very welcome and appreciated!

**Comment by gnikit** [comment]
Thanks for the info @justinmk I will open a PR soon with the correct info.
