### ISSUE TITLE
`Pyright` cannot get information that the user has created a new file.

### ISSUE THREAD

**Issue by askfiy** [neovim/nvim-lspconfig#1905]
### Description

After `Pyright` is started, if the user creates a new `python` module and imports it, `Pyright` throws an exception.

The error can only be suppressed after restarting `Pyright`, i.e. neovim will not send a report to `Pyright` after the user has created a new `python` file.

I raised an issue with `Pyright` about this [#3461](https://github.com/microsoft/pyright/issues/3461), and they clearly pointed out that this is caused by neovim.

### Neovim version

$ nv -v
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

9ff2a06cebd4c8c3af5259d713959ab310125bec

### Operating system and version

Operating System: Manjaro Kernel version: 5.15.38

### Affected language servers

Pyright

### Steps to reproduce

Its structure is similar to:

````
--module/
  |-- __init__.py
  |-- a.py
-- b.py
````

caution! `a.py` was created later than `b.py`

In `b.py` write:

````

●● Pyright: "b" is unknown import symbol

from module import a

````

### Actual behavior

Errors that should not be generated:

`Pyright: "b" is unknown import symbol`

### Expected behavior

`Pyright` should correctly recognize user-created modules without requiring the user to manually restart `Pyright`

### Minimal config

```Lua
...
```

### LSP log

[logfile](https://gist.github.com/askfiy/c49578de4c5a65c1609a97b7f9d91fc1)

**Comment by askfiy** [comment]
Ahh.. `BUG` that seriously affects usage ..

**Comment by lithammer** [comment]
Probably because you're missing one of the root markers so it goes into single file mode:

https://github.com/neovim/nvim-lspconfig/blob/9ff2a06cebd4c8c3af5259d713959ab310125bec/lua/lspconfig/server_configurations/pyright.lua#L10-L17

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
