### ISSUE TITLE
Windows: tsserver only spawn empty cmd and does not attach

### ISSUE THREAD

**Issue by Chanakan55991** [neovim/nvim-lspconfig#1907]
### Description

when I open a typescript file, the cmd window pop up but it doesn't seem to attach to the neovim buffer (checked by LspInfo), If I press enter on it 2 times it will error with missing header (might not be related but just in case). 

### Neovim version

NVIM v0.8.0-dev+203-g9e4286294
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

9ff2a06cebd4c8c3af5259d713959ab310125bec

### Operating system and version

Windows 11 21H2

### Affected language servers

tsserver, tailwindcss

### Steps to reproduce

1. open javascript/typescript file on neovim with the minimal config `nvim -u minimal.lua`

### Actual behavior

the cmd of the language server will pop up but it doesn't actually seem to do anything, it does not attach to the current buffer.

### Expected behavior

for tsserver/tailwindcss to attach to the buffer and work properly

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
    buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
    buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    buf_set_keymap('n', '<space>e', '<cmd>lua vim.diagnostic.open_float()<CR>', opts)
    buf_set_keymap('n', '[d', '<cmd>lua vim.diagnostic.goto_prev()<CR>', opts)
    buf_set_keymap('n', ']d', '<cmd>lua vim.diagnostic.goto_next()<CR>', opts)
    buf_set_keymap('n', '<space>q', '<cmd>lua vim.diagnostic.setloclist()<CR>', opts)
  end

  -- Add the server that troubles you here
  local name = 'tsserver'
  local cmd = { 'cmd', '/C', 'typescript-language-server.cmd', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

https://gist.github.com/Chanakan55991/5c542377dc167abc34d4618d3f5636eb

**Comment by Chanakan55991** [comment]
here is an additional screenshots if that help
![image](https://user-images.githubusercontent.com/80865605/168449801-61f64581-a0b1-43bd-a891-c842d129ee91.png)

 ### The error below only shows up after you pressed enter on it 2 times. If you didn't press anything it would simply be empty cmd

![image](https://user-images.githubusercontent.com/80865605/168449809-92f27cac-8b36-4fc0-8613-4638bebe8082.png)

**Comment by justinmk** [comment]
Might be a windows issue. Works for me on macos.

PR welcome.

**Comment by jortiz2015** [comment]
I'm having the same exact issue. Please let me know if you find a solution.

**Comment by tamago324** [comment]
I think it is caused by https://github.com/neovim/neovim/commit/6cfb1d4c280a90bcce4e793f56d791b68c66c264.
So it seems that on Windows you need to set `detached` to `false` in the table you pass to `lspconfig[name].setup()`.

```lua
...
  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
    detached = false
  }
```

**Comment by Chanakan55991** [comment]
> I think it is caused by [neovim/neovim@6cfb1d4](https://github.com/neovim/neovim/commit/6cfb1d4c280a90bcce4e793f56d791b68c66c264). So it seems that on Windows you need to set `detached` to `false` in the table you pass to `lspconfig[name].setup()`.
> 
> ```lua
> ...
>   nvim_lsp[name].setup {
>     cmd = cmd,
>     on_attach = on_attach,
>     detached = false
>   }
> ```

This solution worked on both tsserver and tailwindcss language server, thanks!

**Comment by jortiz2015** [comment]
> I think it is caused by [neovim/neovim@6cfb1d4](https://github.com/neovim/neovim/commit/6cfb1d4c280a90bcce4e793f56d791b68c66c264). So it seems that on Windows you need to set `detached` to `false` in the table you pass to `lspconfig[name].setup()`.
> 
> ```lua
> ...
>   nvim_lsp[name].setup {
>     cmd = cmd,
>     on_attach = on_attach,
>     detached = false
>   }
> ```

Thank you so much @tamago324 this solution worked for me as well. I appreciate your help 👍 
Regards,
Jose Ortiz
