### ISSUE TITLE
set python version 2

### ISSUE THREAD

**Issue by preethamveeranna** [neovim/nvim-lspconfig#1910]
### Description

setting python provider to point to python 2.7 version using _vim.g.python3_host_prog_ and _:checkhealth_ shows the provider being picked. However, both pyright and pylsp LSPs are still using python version 3 for diagnostics!!
how do I set python 2.7 version for these LSPs?

### Neovim version

NVIM v0.7.1-dev+9-gaff05c573
Build type: Debug
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

 pylsp (python)       version   1.4.1

### Operating system and version

Ubuntu WSL

### Affected language servers

pyright, pylsp

### Steps to reproduce

1. set vim.g.python3_host_prog and vim.g.python_host_prog to point to python 2.7 version installation binary.
2. open a python file with python 2.7 only feature like 'raw_input'
3. pyright/pylsp shows errors for python2.7 features

### Actual behavior

python 2.7 version is NOT used for diagnostics.

### Expected behavior

python 2.7 version is used for diagnostics.

### Minimal config

```Lua
Not applicable
```

### LSP log

Not applicable

**Comment by mjlbach** [comment]
`vim.g.python3_host_prog` has nothing to do with the python interpreter used by pyright, it inherits whatever your shell's python interpreter is (respecting VIRTUAL_ENV) if applicable.

**Comment by preethamveeranna** [comment]
> `vim.g.python3_host_prog` has nothing to do with the python interpreter used by pyright, it inherits whatever your shell's python interpreter is (respecting VIRTUAL_ENV) if applicable.
Well I'm using Conda, and none of the neovim's python LSPs are picking the active Conda's python 2.7 version.

**Comment by preethamveeranna** [comment]
> `vim.g.python3_host_prog` has nothing to do with the python interpreter used by pyright, it inherits whatever your shell's python interpreter is (respecting VIRTUAL_ENV) if applicable.

It doesnt recognize Conda's environment, is there a way to make pyright/pylsp pick that up?

**Comment by mjlbach** [comment]
Activate the conda environment before starting neovim.
