### ISSUE TITLE
tailwindcss memory and cpu is very high

### ISSUE THREAD

**Issue by username664** [neovim/nvim-lspconfig#1922]
### Description

When used with nvim-cmp and tailwindcss in class(className - whatever) - lags, when trying to add or remove letters and big memory and cpu usage. When using some time LSP - ram of nvim process will be like 1gb or something. Some memory leak probably. When i use tailwindcss with coc-nvim with this settings all is fine:
```
  "languageserver": {
    "tailwind-lsp": {
      "command": "tailwindcss-language-server",
      "args": ["--stdio"],
      "filetypes": ["javascriptreact", "typescriptreact"],
      "rootPatterns": ["tailwind.config.js", "tailwind.config.ts"],
      "settings": {
        "tailwindCSS": {
          "validate": true,
          "lint": {
            "cssConflict": "warning",
            "invalidApply": "error",
            "invalidScreen": "error",
            "invalidVariant": "error",
            "invalidConfigPath": "error",
            "invalidTailwindDirective": "error",
            "recommendedVariantOrder": "warning"
          },
          "classAttributes": ["class", "className", "classList", "ngClass"],
          "experimental": {}
        }
      }
    }
  },
```

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Debian GNU/Linux 11 (bullseye)

### Affected language servers

tailwindcss

### Steps to reproduce

1 Install it with LspInstall tailwindcss (nvim-lsp-installer).
2. Start using tailwindcss with nvim-cmp in class or className(whatever) with configured project(React, plain html or whatever).
3. Try to add and remove some classes some time, like a minute.
4. Try to add letters or remove in staing in class(className and etc) field. Should be lags.
5. Check ram of nvim process.
6. Process should be around 500mb-1gb.
With coc-nvim all is fine.

### Actual behavior

Lags when typing, ram usage big and cpu.

### Expected behavior

Smooth, memory not leaking and etc, not laging when typing.

### Minimal config

```Lua
https://gist.github.com/username664/c1b0fac472d2ae4f6b0d5a7b71ca6c2d
```

### LSP log

https://gist.github.com/username664/09df9df6d2bc166c8031a89a51fc52fb

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
