### ISSUE TITLE
:bprev after go to definition is broken

### ISSUE THREAD

**Issue by timsofteng** [neovim/nvim-lspconfig#1930]
### Description

I've faced up with issue in gopsl and tsserver.
After goToDefinition where definition is in another file I can't go to my previous buffer with `:bpre`. It redirect me to another buffer but not to previous.

### Neovim version

0.7

### Operating system and version

Void, Alpine edge

### Affected language servers

gopls, tsserver

### Steps to reproduce

1. Go to definition which is in another file.
2. :bprev

### Actual behavior

Back to buffer which is not previous.

### Expected behavior

Back to previous buffer.

### Minimal config

```Lua
*
```

### LSP log

*

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lspconfig#lspconfig):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix to one of the configs here, send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the Nvim core `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with steps in a to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
