### ISSUE TITLE
unable to use code_actions

### ISSUE THREAD

**Issue by wesleimp** [neovim/nvim-lspconfig#1949]
### Description

Error when trying to use lsp code_actions

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

ed3df8f8e380ebe408760af2c74aa1c3c23d4007

### Operating system and version

PopOS 22.04

### Affected language servers

golang

### Steps to reproduce

1. Open a golang file
2. Try to use `code_action` for some import

### Actual behavior

![image](https://user-images.githubusercontent.com/42675056/172616271-d4992b9c-5960-424d-8c64-0cce814fc3cc.png)

### Minimal config

not relevant

### LSP log

not relevant

**Comment by justinmk** [comment]
This repo is only for LSP configs. 

But anyways, try the development version of Nvim.

- The [Releases](https://github.com/neovim/neovim/releases/tag/nightly) page has pre-built archives for Linux/Windows/macOS. 
- Check `:version` to confirm that you are using the latest version.
