### ISSUE TITLE
add settings to clangd server

### ISSUE THREAD

**Issue by Tej12345** [neovim/nvim-lspconfig#1957]
### Language server

clangd

### Requested feature

I want to be able to set several path of compile_commands.json.
Example:
clangd --compile-commands-path="linux/build;linux_2/build"
I spent 3 hours understanding how to pass several paths of compile_commands.json to clangd language server.
And failed dramatically...
Please, consider.

**Comment by justinmk** [comment]
This is not a support channe;.

**Comment by Tej12345** [comment]
What are you talking about?
