### ISSUE TITLE
The link to kickstart.nvim is broken

### ISSUE THREAD

**Issue by jolars** [neovim/nvim-lspconfig#1967]
### Description

The link to https://github.com/nvim-lua/kickstart.nvim in https://github.com/neovim/nvim-lspconfig/wiki/Complete-init.lua-example is broken because there no longer is a kickstar.nvim repo.

I've tried to see if it's been relocated but haven't found it anywhere.

### Neovim version

NVIM v0.7.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

linux

### Affected language servers

all

### Steps to reproduce

Click the link.

### Actual behavior

The link is broken.

### Minimal config

```Lua
asdf
```

### LSP log

asdf

**Comment by justinmk** [comment]
kickstart was deleted/hidden by its author. I've deleted the wiki page https://github.com/neovim/nvim-lspconfig/wiki/Complete-init.lua-example
