### ISSUE TITLE
Small typo in readme

### ISSUE THREAD

**Issue by RayZ0rr** [neovim/nvim-lspconfig#1973]
### Description

In the readme, since in suggested kepmapping `vim.keymap.set` is used, shouldn't `remap = false` ( default I guess) be used instead of `noremap = true` ?

### Neovim version

.

### Operating system and version

Arch

### Affected language servers

.

### Steps to reproduce

.

### Actual behavior

.

### Minimal config

```Lua
.
```

### LSP log

.

**Comment by justinmk** [comment]
no. why?
