### ISSUE TITLE
Use 'q' and/or '<C-g>' to close the LspInfo popup window

### ISSUE THREAD

**Issue by raw-bin** [neovim/nvim-lspconfig#1977]
### Requested feature

At present, it appears that invoking:
```
:LspInfo
```
.. results in a popup window which can only be closed by pressing 'Esc'.

This is somewhat inefficient especially when resting on the home row as the Vim way.

Could we just support pressing the 'q' key to close the popup ?

I also think that it is an unwritten rule to always support `<C-g>` as an alternative to pressing the 'Esc' key which would also be a better option.

I appreciate that this kind of falls into the bucket of first world problems but small tweaks like this contribute to a more efficient workflow IMHO.

Oh and if there is a configuration option to solve this one then that would be fine too. I couldn't find any but I'm not sure I tried hard enough.

Thanks!

**Comment by Clejd** [comment]
You can achieve this by typing `<C-w> q`

**Comment by justinmk** [comment]
`gq` is the preferred convention because `q` starts/stops a macro, which is generally useful in almost any context.
