### ISSUE TITLE
Eslint false positive errors

### ISSUE THREAD

**Issue by Arelav** [neovim/nvim-lspconfig#1982]
### Description

I have some error using native LSP in Neovim. I don't have any of those Using Eslint in Webstorm, VSCode or using Ale or COC
<img width="1164" alt="CleanShot 2022-07-02 at 14 35 03@2x" src="https://user-images.githubusercontent.com/1059539/177015560-530c40a3-eb15-46e1-809a-ae019f7445aa.png">

### Neovim version

NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 12.3.1

### Affected language servers

eslint

### Steps to reproduce

It's a complex monorepo, looks like eslint uses a wrong config or something like this.
I don't know from what to start troubleshooting however with some help I'm ready to do any checks would be necessary to prevent potential error like this on the future.

### Actual behavior

<img width="925" alt="CleanShot 2022-07-02 at 14 49 01@2x" src="https://user-images.githubusercontent.com/1059539/177015805-927518c1-573f-4736-9cda-91caebaf556e.png">

### Expected behavior

No errors

### Minimal config

```Lua
local lspconfig = require("lspconfig")
lspconfig.eslint.setup({})
```

### LSP log

https://gist.github.com/Arelav/33c8813ca5b87e36ba22d57518ff19c3

**Comment by justinmk** [comment]
Could compare the server config that is sent by nvim lsp client, vs the others. Should be in the logs somewhere.

**Comment by Arelav** [comment]
`2022-07-03T20:46:04.984 INFO (pid:93788) [plugin] - coc.nvim initialized with node: v16.14.2 after 34ms
2022-07-03T20:46:07.670 ERROR (pid:93788) [core-editors] - document not found for window: 1000
2022-07-03T20:46:09.606 INFO (pid:93788) [services] - registered service "eslint"
2022-07-03T20:46:09.607 INFO (pid:93788) [services] - ESLint state change: stopped => starting
2022-07-03T20:46:09.662 INFO (pid:93788) [services] - ESLint state change: starting => running
2022-07-03T20:46:09.665 INFO (pid:93788) [services] - service eslint started
2022-07-03T20:46:17.765 INFO (pid:93788) [attach] - receive notification: openLog []`
This is `coc-eslint` enabled and logged through `:CocOpenLog` not much useful info.

**Comment by Arelav** [comment]
It maybe related when using global installed eslint vs local. Not the version difference but perhaps it takes a different config
I see something similar when trying Doom Emacs.

**Comment by Arelav** [comment]
I use Fish shell. Today I migrated from fundle to Fisher and this maybe a reason or maybe vim plugins where updated. 
Bottom line it works as supposed to be now.

**Comment by Arelav** [comment]
One more thing changed is after `brew upgrade` neovim version was changed from `7.0` to `7.2`
I hope it will help somebody with the same issues.
