### ISSUE TITLE
LSP rename doesn't change symbol on other files. (Only in pyright)

### ISSUE THREAD

**Issue by danielgarzaf** [neovim/nvim-lspconfig#1985]
### Description

Not sure if this belongs here instead of the main neovim repo, but running `vim.lsp.buf.rename()` doesn't change symbol under cursor on other files

### Neovim version

NVIM v0.8.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

c107a0f33e7af39dd48ad0e681c3d65281b812d1

### Operating system and version

Ubuntu 20.04

### Affected language servers

pyright

### Steps to reproduce

Run `:lua vim.lsp.buf.rename()` while cursor is under any symbol.

### Actual behavior

Symbol only changes in current file

### Expected behavior

Symbol changes in every relevant file

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
    vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
    vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
    vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
  end

  -- Add the server that troubles you here
  local name = 'pyright'
  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  vim.cmd [[autocmd User PackerComplete ++once lua load_config()]]
else
  load_plugins()
  require('packer').sync()
  _G.load_config()
end
```

### LSP log

[START][2022-07-06 00:31:03] LSP logging initiated [WARN][2022-07-06 00:31:03] ...lsp/handlers.lua:113	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless" [WARN][2022-07-06 00:31:03] ...lsp/handlers.lua:475	"stubPath typings is not a valid directory."

**Comment by justinmk** [comment]
We cannot debug every random lsp server. If you can demonstrate a bug in `vim.lsp`, send the issue to https://github.com/neovim/neovim

**Comment by jyue86** [comment]
For anyone who encounters this issue in the future, the problem is likely a missing `pyrightconfig.json`. Pyright uses this file in order to keep track of which files to analyze, and when no such file is provided, it'll default to only analyzing the open ones. To confirm that this is the case, you can run `LspInfo`, and if pyright is running in single file mode, then a `pyrightconfig.json` file should be provided. 

Refer to this [link](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-config-file) for an example config file. The key part here is the `include` part, where you'll want to specify which directory/files that pyright should analyze.

Also a helpful source: https://github.com/microsoft/pyright/issues/375

**Comment by Lamby777** [comment]
> For anyone who encounters this issue in the future, the problem is likely a missing `pyrightconfig.json`. Pyright uses this file in order to keep track of which files to analyze, and when no such file is provided, it'll default to only analyzing the open ones. To confirm that this is the case, you can run `LspInfo`, and if pyright is running in single file mode, then a `pyrightconfig.json` file should be provided.
> 
> Refer to this [link](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-config-file) for an example config file. The key part here is the `include` part, where you'll want to specify which directory/files that pyright should analyze.
> 
> Also a helpful source: [microsoft/pyright#375](https://github.com/microsoft/pyright/issues/375)

Any equivalent of this for `pylsp`?
