### ISSUE TITLE
changed $CARGO_HOME

### ISSUE THREAD

**Issue by ignamartinoli** [neovim/nvim-lspconfig#1992]
### Description

I wanted to be compliant with the **XDG** specification.
So I added to my `~/.zshenv` the following line

```zsh
export CARGO_HOME="$XDG_DATA_HOME/cargo"
path+=("$CARGO_HOME/bin")
```

removed from `~/.zshenv`

```zsh
. "$HOME/.cargo/env"
```

and just to be sure I changed `~/.local/share/cargo/env` to

```sh
#!/bin/sh
# rustup shell setup
# affix colons on either side of $PATH to simplify matching
case ":${PATH}:" in
    *:"$CARGO_HOME/bin":*)
        ;;
    *)
        # Prepending path in case a system-installed rustc needs to be overridden
        export PATH="$CARGO_HOME/bin:$PATH"
        ;;
esac
```

and lastly I moved the `~/.cargo/*` directory to `~/.local/share/cargo`.

After that, whenever I open a **Rust** file I receive the error message

```
LSP[rust_analyzer] rust-analyzer failed to load workspace: Failed to find sysroot for Cargo.toml file /home/sicro/Code/Rust/example/Cargo.toml. Is rust-src installed?: can't load standard library from sysroot
/usr/lib/rust/1.62.0
(discovered via `rustc --print sysroot`)
try installing the Rust source the same way you installed rustc
```

Since I setted the environment variables properly and all other **Rust** tools work in the terminal I don't know if I missed something or either `nvim-lspconfig` or `rust-analyzer` assume the **Cargo** directory location.

### Neovim version

VIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

Latest, don't really know how to see the hash

### Operating system and version

Gentoo 2.8

### Affected language servers

rust-analyzer

### Steps to reproduce

Detailed above

### Actual behavior

Error message above

### Expected behavior

`rust-analyzer` running fine

### Minimal config

```Lua
-- I use junnplus/nvim-lsp-setup. Trying to use the minimal config made Neovim but as you can see I have no fancy options enabled

require 'nvim-lsp-setup'.setup {
	servers = {
		rust_analyzer = {},
	}
}
```

### LSP log

https://gist.github.com/ignamartinoli/d977a911ddbdc11bf1ad13d228b13b07

**Comment by lithammer** [comment]
That sounds like a rust-analyzer issue.

**Comment by ignamartinoli** [comment]
I'm submitting an issue there just in case

**Comment by ignamartinoli** [comment]
Solved there, thanks!
