### ISSUE TITLE
LSP[rust_analyzer] recieved end message with no corresponding begin

### ISSUE THREAD

**Issue by bexxmodd** [neovim/nvim-lspconfig#2002]
### Description

I'm getting errors stated in the title when I open any Rust file/project. Idk if it some way affects how rust files are processed yet but this only happens with Rust

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

manjaro

### Affected language servers

rust_analyzer

### Steps to reproduce

nvim main.rs

### Actual behavior

small delay at loading file and then I get error stated in the title

### Minimal config

```Lua
I'm using the standard config provided in this repo
```

### LSP log

na

**Comment by justinmk** [comment]
This repo isn't a support channel, it's just a collection of quickstart configs.

Your particular issue is/was a bug in rust_analyzer: https://github.com/neovim/neovim/issues/19158

**Comment by xbladesub** [comment]
Had the same issue - updated rust-analyzer to latest version and error gone.
Clone rust-analyzer repo, cd to it and do 'cargo xtask install --server'
