### ISSUE TITLE
grammarly lsp: "Failed to parse URL"

### ISSUE THREAD

**Issue by felipecrp** [neovim/nvim-lspconfig#2007]
### Description

Greetings,

I installed grammarly language server (with npm global and also with the lsp install plugin).

When I try to start the server:
 
```
require'lspconfig'.grammarly.setup{}
```
I got the following error:

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/lsp.lua:955: RPC[Error] code_name = InternalError, message = "Request initialize failed with messa
ge: clientId is required"                                                                                                                                                    
stack traceback:                                                                                                                                                             
        [C]: in function 'assert'                                                                                                                                            
        /usr/share/nvim/runtime/lua/vim/lsp.lua:955: in function ''                                                                                                          
        vim/_editor.lua: in function <vim/_editor.lua:0>                   
```

If I start the server passing the same client id used in vscode:
```
require'lspconfig'.grammarly.setup { init_options = { clientId = "client_XXXX" } } 
```
It still don't work.
```
Client 1 quit with exit code 1 and signal 0 
```
I observed the `code: 'ERR_INVALID_URL'` error in LSP log:
```
[ERROR][2022-07-16 15:57:50] .../vim/lsp/rpc.lua:420	"rpc"	"grammarly-languageserver"	"stderr"	"(node:20692) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time\n(Use `node --trace-warnings ...` to show where the warning was created)\n"
[ERROR][2022-07-16 15:57:52] .../vim/lsp/rpc.lua:420	"rpc"	"grammarly-languageserver"	"stderr"	"node:internal/deps/undici/undici:4813\n            throw new TypeError(\"Failed to parse URL from \" + input, { cause: err });\n                  ^\n\nTypeError: Failed to parse URL from /home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm\n    at new Request (node:internal/deps/undici/undici:4813:19)\n    at Agent.fetch2 (node:internal/deps/undici/undici:5505:29)\n    ... 4 lines matching cause stack trace ...\n    at new Promise (<anonymous>)\n    at Parser.init (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:332)\n    at createParserInner (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/grammarly-richtext-encoder/dist/index.cjs:449:42)\n    at Object.createParser (/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/grammarly-richtext-encoder/dist/index.cjs:445:20) {\n  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL\n      at new NodeError (node:internal/errors:377:5)\n      at URL.onParseError (node:internal/url:563:9)\n      at new URL (node:internal/url:643:5)\n      at new Request (node:internal/deps/undici/undici:4811:25)\n      at Agent.fetch2 (node:internal/deps/undici/undici:5505:29)\n      at Object.fetch (node:internal/deps/undici/undici:6332:20)\n      at fetch (node:internal/bootstrap/pre_execution:196:25)\n      at /home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15192\n      at /home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15413\n      at new Promise (<anonymous>) {\n    input: '/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm',\n    code: 'ERR_INVALID_URL'\n  }\n}\n\nNode.js v18.3.0\n"
```
Can you help identify what is missing in the config?

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

Arch

### Affected language servers

grammarly

### Steps to reproduce

1. Install the language server
2. Run `require'lspconfig'.grammarly.setup{}` or `require'lspconfig'.grammarly.setup { init_options = { clientId = "client_XXXX" } } `

### Actual behavior

The LSP does not start.

### Expected behavior

The LSP should start.

### Minimal config

```Lua
require'lspconfig'.grammarly.setup { init_options = { clientId = "client_XXXX" } }
```

### LSP log

https://gist.github.com/felipecrp/753b909c4fd09c9617d0b6b1c9eeac3c

**Comment by justinmk** [comment]
"clientId is required" is presumably a follow-on effect of the fact that the lang server failed.

```
[ERROR][2022-07-16 15:57:52] .../vim/lsp/rpc.lua:420	"rpc"
"grammarly-languageserver"	"stderr"
"node:internal/deps/undici/undici:4813\n            throw new TypeError(\"Failed
to parse URL from \" + input, { cause: err });\n
^\n\nTypeError: Failed to parse URL from
/home/user/.local/share/nvim/lsp_servers/grammarly/node_modules/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm\n
```

`Failed to parse URL` comes from grammarly. Maybe we're sending an invalid URL or maybe grammarly has a bug.

You could try seeing if the URL shows somewhere in the previous logs.

**Comment by felipecrp** [comment]
Thank you for the response. I attached the log (debug) on the gist link (https://gist.github.com/felipecrp/753b909c4fd09c9617d0b6b1c9eeac3c).

I can start the language server from the command line. Can I attach the LSP to an active language server?

**Comment by felipecrp** [comment]
Also, I can use the language server with vscode.

**Comment by justinmk** [comment]
from your log:

    [INFO][2022-07-16 16:07:52] ...lsp/handlers.lua:459	"open file:///home/user/sites/user.github.io/_drafts/how-to-install-arch-linu-on-wsl.md"

presumably that is the URL it is throwing on? does that path exist on your machine?

**Comment by felipecrp** [comment]
Yes, it exists.

**Comment by justinmk** [comment]
k. why is grammarly throwing then? Sounds like something they should debug.

**Comment by felipecrp** [comment]
Probably something missing in the LSP connection.

**Comment by felipecrp** [comment]
@justinmk Why did you close the issue?

**Comment by justinmk** [comment]
no

**Comment by renatolond** [comment]
I managed to follow the instructions for emacs, over here: https://github.com/emacs-grammarly/lsp-grammarly#-method-1-login-with-vscode-easier
But now I can't seem to make it work again in a different computer. Hope it helps!

**Comment by telphan** [comment]
@felipecrp did you get anywhere with this?

**Comment by jeremyboles** [comment]
If anyone else is running into this, make sure that `grammarly-languageserver` is running with Node v16. More info here: https://github.com/znck/grammarly/issues/334
