### ISSUE TITLE
generate root_dir docs from source code

### ISSUE THREAD

**Issue by justinmk** [neovim/nvim-lspconfig#2011]
## Problem

https://github.com/neovim/nvim-lspconfig/issues/1742 reported that the generated docs for `root_dir` are sometimes invalid. The response was https://github.com/neovim/nvim-lspconfig/commit/9dc02492c4a457479f8a0ec7a65aac1852ff59c0 which just removed the generation: https://github.com/neovim/nvim-lspconfig/commit/733fe92baafb23cb413300571e31cb1fec962b1a

Besides being cumbersome, the manual documentation leads to problems like: https://github.com/neovim/nvim-lspconfig/pull/2006

## Solution

1. Restore code generation removed in https://github.com/neovim/nvim-lspconfig/commit/9dc02492c4a457479f8a0ec7a65aac1852ff59c0 and...
    1. make it _link to the source_ instead of trying to parse it (e.g. `[path/to/foo.lua](https://github.com/neovim/nvim-lspconfig/blob/…/foo.lua#L132-L149)`)
    1. or just fix the parsing.
1. Use treesitter to parse the file?

**Comment by sersorrel** [comment]
this would also fix e.g. [rnix's docs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rnix) saying that root_dir defaults to "vim's starting directory" when in fact it's `util.find_git_ancestor(fname) or vim.loop.os_homedir()`, which is very much not the same thing
