### ISSUE TITLE
Elm Language Server is not working 

### ISSUE THREAD

**Issue by bokutotu** [neovim/nvim-lspconfig#2012]
### Description

Elm's languge server is not working properly.

for example this is my profeject
`tree
`
```
├── README.md
├── elm-stuff
│   └── 0.19.1
│       ├── Main.elmi
│       ├── Main.elmo
│       ├── d.dat
│       ├── i.dat
│       ├── lock
│       └── o.dat
├── elm.json
└── src
    └── Main.elm
```

And, this is `:LspInfo`

![image](https://user-images.githubusercontent.com/56831446/179467853-26a9fa4c-ceab-44f7-9f1c-ba0f4f6d8d2f.png)

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.7.2/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

347947355ba0a15d803cbd61b18f8bb8f401c793

### Operating system and version

macOS 12.4

### Affected language servers

elmls

### Steps to reproduce

1. `nvim Main.elm`
2. `:LspInfo`

this is my 

### Actual behavior

neovim's LSP fails to find the Elm root directory and Elmls does not start up.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

let join_paths = function (...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

_G.load_config = function()
  vim.lsp.set_log_level 'trace'
  if vim.fn.has 'nvim-0.5.1' == 1 then
    require('vim.lsp.log').set_format_func(vim.inspect)
  end
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
    vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
    vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
    vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
  end

  -- Add the server that troubles you here
  local name = 'pyright'
  local cmd = { 'pyright-langserver', '--stdio' } -- needed for elixirls, omnisharp, sumneko_lua
  if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]]
  end

  nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end
```
```


### LSP log

https://gist.github.com/bokutotu/0d38616ecc1bc47f878d5593495b2898

**Comment by justinmk** [comment]
Check the LSP logs:

1. Restart Nvim.
2. Set verbose logging.
   ```
   :lua vim.lsp.set_log_level(0)
   ```
3. Open a file that is recognized by the LSP service. Try to invoke the LSP feature you are interested in.
4. Open the LSP log file.
   ```
   :exe 'edit' v:lua.vim.lsp.get_log_path()
   ```

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lspconfig#nvim-lspconfig):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix to one of the configs here, send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the Nvim core `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with steps in a to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.

**Comment by oopjot** [comment]
@bokutotu downgrading Node version from 18.4 to 16.x worked for me. Check out [this issue](https://github.com/elm-tooling/elm-language-server/issues/692).

**Comment by matt-savvy** [comment]
As far as anyone can tell, the root of the issue is in tree-sitter and needs to be fixed upstream there. See https://github.com/tree-sitter/tree-sitter/issues/1765
