### ISSUE TITLE
Impossible to copy info from `:LspInfo`

### ISSUE THREAD

**Issue by WhyNotHugo** [neovim/nvim-lspconfig#2021]
### Description

I want to copy details from the popup that render with `:LspInfo`.

Entering visual mode immediately closes the popup, so it is not possible to select any text for copying.

Yanking also immediately closes the popup, so it is not possible to take that approach either.

### Neovim version

```
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/5dhji48ck1pkh1zfpbnjrmx1ybgjn31q-neovim-unwrapped-0.7.0/share/nvim
"

Run :checkhealth for more info
```

### Nvim-lspconfig version

9ff2a06cebd4c8c3af5259d713959ab310125bec

### Operating system and version

Linux

### Affected language servers

all

### Steps to reproduce

1. `:LspInfo`
2. Try to select or yank the text from the popup.

### Actual behavior

It should be possible to somehow select or yank the text; the floating should not close when attempting to do so.

### Expected behavior

The popup closes immediately when interacting with it.

### Minimal config

```Lua
No changes required to the minimal config.
```

### LSP log

n/a

**Comment by justinmk** [comment]
> It should be possible to somehow select or yank the text; the floating should not close when attempting to do so.

Agreed. Probably some over-eager event handler. PR welcome.

**Comment by dstein64** [comment]
I cannot reproduce this using Neovim v0.7.2, on either a new lspconfig commit nor the commit mentioned in the issue.

The `LspInfo` popup stays open when switching to visual mode and/or copying text.

**Comment by justinmk** [comment]
@WhyNotHugo see `:help bisect`, check if a plugin is interfering.
