### ISSUE TITLE
rust_analyzer won't attach to rust buffers

### ISSUE THREAD

**Issue by zoefiri** [neovim/nvim-lspconfig#2030]
### Description

rust_analyzer won't attach to Rust buffers.  For some reason it doesn't appear in the "Configured server list" in :LspInfo, but it does appear in :LspInstallInfo (see actual behaviour)

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by void-buildslave@a-fsn-de

### Nvim-lspconfig version

1b7ef62

### Operating system and version

VoidLinux (linux-5.18_1)

### Affected language servers

rust_analyzer

### Steps to reproduce

config at https://github.com/zoefiri/dots/blob/master/confs/nvim/:

nvim main.rs
:LspInstall rust_analyzer
:LspStart

### Actual behavior

![image](https://user-images.githubusercontent.com/27149384/180896043-9ddaa196-be06-49fb-906d-9604d4bc9b93.png)
![image](https://user-images.githubusercontent.com/27149384/180896085-1b47878a-2d08-492b-ac43-f282bd78bb9a.png)

### Expected behavior

rust_analyzer attaching to the rust buffer

### Minimal config

```Lua
https://github.com/zoefiri/dots/blob/master/confs/nvim/init.lua
```

### LSP log

https://gist.github.com/672dfa489b77392fc915427c55c407b2

**Comment by sigmaSd** [comment]
What if you run 
````sh
:lua require"lspconfig".setup("rust_analyzer")
```
Then check lspinfo

**Comment by glepnir** [comment]
@zoefiri  did you still have this problem?
