### ISSUE TITLE
change wiki as williamboman/nvim-lsp-installer will not be maintained

### ISSUE THREAD

**Issue by smolovk** [neovim/nvim-lspconfig#2031]
### Requested feature

change [Automatic server installation](https://github.com/neovim/nvim-lspconfig/wiki/Installing-language-servers#automatically) wiki page as williamboman/nvim-lsp-installer will not be maintained

> nvim-lsp-installer will no longer be actively maintained, meaning I won't be doing things like porting new mason.nvim packages to nvim-lsp-installer, monitoring lspconfig for changes that require updates, or put much effort into user support or bug issues (the recommendation for the latter will be to migrate to mason.nvim).
https://github.com/williamboman/nvim-lsp-installer

**Comment by justinmk** [comment]
done, thanks!
