### ISSUE TITLE
Add explanation and use cases to readme

### ISSUE THREAD

**Issue by DonjiKong** [neovim/nvim-lspconfig#2035]
### Requested feature

I have no idea what the thing does or why I should use it.

**Comment by justinmk** [comment]
First line of the readme says:

> [Configs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md) for the [Nvim LSP client](https://neovim.io/doc/user/lsp.html) (:help lsp).

We can expand on it:

> nvim-lspconfig is a collection of configurations for use with the Nvim builtin LSP client, to save you the trouble of manually creating such configurations. For example to use Nvim LSP with a typescript project, you would need to 
>
> 1. install the typescript language server
> 2. in your init.lua (or init.vim) configure it like this: https://github.com/neovim/nvim-lspconfig/blob/80fddd28de5fe0642da7adee955f5762b933e730/lua/lspconfig/server_configurations/tsserver.lua#L3-L26
> 
> With nvim-lspconfig, you only need to:
>
> 1. install the typescript language server
> 2. in your init.lua (or init.vim) call `require'lspconfig'.tsserver.setup{}`

Is that clear?

**Comment by justinmk** [comment]
Need to add the above changes to the readme before closing this.

**Comment by glepnir** [comment]
closed because Readme has been updated.
