### ISSUE TITLE
ansiblels completion does not work with default config

### ISSUE THREAD

**Issue by sincomil** [neovim/nvim-lspconfig#2046]
### Description

ansiblels completion does not work with default configuration:
LspLog show error message for each attempt to get completion suggest:
```[ERROR][2022-08-02 16:22:38] ...lsp/handlers.lua:455	"An error occurred in 'onCompletion' handler: [TypeError] Cannot read properties of undefined (reading 'provideRedirectModules')\nTypeError: Cannot read properties of undefined (reading 'provideRedirectModules')\n    at /home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/providers/completionProvider.js:45:112\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/providers/completionProvider.js:5:58)"
[ERROR][2022-08-02 16:22:38] ...lsp/handlers.lua:455	"An error occurred in 'onCompletion' handler: [TypeError] Cannot read properties of undefined (reading 'provideRedirectModules')\nTypeError: Cannot read properties of undefined (reading 'provideRedirectModules')\n    at /home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/providers/completionProvider.js:45:112\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/providers/completionProvider.js:5:58)"
[ERROR][2022-08-02 16:22:38] ...lsp/handlers.lua:455	"An error occurred in 'onCompletion' handler: [TypeError] Cannot read properties of undefined (reading 'provideRedirectModules')\nTypeError: Cannot read properties of undefined (reading 'provideRedirectModules')\n    at /home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/providers/completionProvider.js:45:112\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/user/.local/share/nvim/mason/packages/ansible-language-server/node_modules/@ansible/ansible-language-server/out/server/src/providers/completionProvider.js:5:58)"
```

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

06744ba3783ce2d502838f988dec95378543f5d7

### Operating system and version

Arch Linux

### Affected language servers

ansiblels

### Steps to reproduce

1. Install: mason.nvim + mason-lspconfig
2. Uninstall: nvim-lsp-installer
3. Install: ansible-language-server
4. Open ansible-file
5. Start server with: LspStart ansiblels
6. Start typing/modifying

### Actual behavior

No completion from LSP-source available, only from current buffer

### Expected behavior

Should be available completion for ansible modules, for example:
When typing: ansible.builtin.shell - it should display a list of options

### Minimal config

```Lua
Using mason-lspconfig/mason
```

### LSP log

https://gist.github.com/sincomil/51384201beff913dd2a51804db864a1c

**Comment by justinmk** [comment]
error is occurring in `completionProvider.js`, which is code we don't own. An ansible user needs to debug this and send a PR.

**Comment by sincomil** [comment]
Let me disagree with you, @justinmk
[ansiblels.lua[(https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/ansiblels.lua) - is a configuration file for ansible-language-server. This config file is provided by [neovim-lspconfig](https://github.com/neovim/nvim-lspconfig). My research has led me to the fact that this config file is missing important configuration options, so correct config file should include that options:
```
return {
  filetypes = {
       "yaml-ansible",
  },
  settings = {
    ansible = {
      ansible = {
        path = "ansible",
        useFullyQualifiedCollectionNames = true
      },
      ansibleLint = {
        enabled = true,
        path = "ansible-lint"
      },
      executionEnvironment = {
        enabled = false
      },
      python = {
        interpreterPath = "python"
      },
      completion = {
          provideRedirectModules = true,
          provideModuleOptionAliases = true
      }
    },
  },
}
```

**Comment by glepnir** [comment]
when you use this setting in your config the issue fixed?

**Comment by justinmk** [comment]
Then someone needs to send a PR to update the asiblels.lua config.

**Comment by jonaz** [comment]
Most of what @sincomil suggested is the defaults and should not be needed to send? https://github.com/ansible/ansible-language-server/blob/v1.0.1/docs/settings.md

**Comment by justinmk** [comment]
The configs in this repo are provided as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- a failing test case added to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
