### ISSUE TITLE
Update suggested mappings in readme

### ISSUE THREAD

**Issue by bronzehedwick** [neovim/nvim-lspconfig#2049]
### Requested feature

The README.md file has suggested mappings for LSP, but many of these show a deprecation message. These are the commands I noticed that are deprecated.

- `vim.lsp.diagnostic.show_line_diagnostics()`
- `vim.lsp.diagnostic.goto_prev()`
- `vim.lsp.diagnostic.goto_next()`
- `vim.lsp.diagnostic.set_loclist()`

I'm not sure what to replace these commands with, if any are supported, so would love to see that explained.

Thanks!

**Comment by sigmaSd** [comment]
Are you reading an old README? the current README  https://github.com/neovim/nvim-lspconfig/blob/master/README.md actually don't use those apis and use the correct new ones, for example 
```lua
vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
```

**Comment by bronzehedwick** [comment]
you're absolutely right, sorry about that!
