### ISSUE TITLE
Update README Quick Start instructions

### ISSUE THREAD

**Issue by lognorman20** [neovim/nvim-lspconfig#2050]
### Requested feature

After trying the installation instructions and jumping right into the Quick Start section, I ran into a lot of trouble trying to get my language server set up. I followed the existing Quick Start instructions to get the pyright language server set running to test, however, I ran into the error of `Spawning language server with cmd: pyright-langserver failed. The language server is either not installed, missing from PATH, or not executable.` when I tried to open up a Python file. 

Upon running through each of the sections in the Troubleshooting writeup, I found that my root directory was not setup properly. This led me to question what was wrong with the way I had installed everything.

Once I started debugging, I found that I needed to install the language servers using [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer#setup). Once I installed the language server using this, everything worked fine for me. 

**My suggestion is this:** 

To help new users, add the language installation through nvim-lsp-installer to make it clear how each language server should be installed.

This may have been something I just did not understand and missed when reading the documentation; however, adding this tidbit will greatly improve the new user experience.

**Comment by glepnir** [comment]
I think the error message already reports your problem in great detail. There are many ways to install the server. You can install it manually using the package manager. Of course you can also use plugins. `nvim-lsp-installer` is a personal plugin. Similar plugins are `mason.nvim `and so on. So that's not the problem.
