### ISSUE TITLE
Svelte / HIghlight

### ISSUE THREAD

**Issue by kamalkech** [neovim/nvim-lspconfig#2063]
### Description

![image](https://user-images.githubusercontent.com/1313428/184503193-cf8ea75b-6fbd-44c5-92f0-bcdcab775e80.png)

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

### Operating system and version

5.18.16-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Aug 3 11:18:52 UTC 2022 x86_64 GNU/Linux

### Affected language servers

svelte-language-server

### Steps to reproduce

.

### Actual behavior

.

### Minimal config

```Lua
.
```

### LSP log

NVIM v0.7.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser.

**Comment by theHamsta** [comment]
What do you expect to happen? Highlighting is not related in any way with this repo. Highlighting via LSP might be enabled in future (pre-work for this to work here: https://github.com/neovim/neovim/pull/15723), but at the moment Neovim has no support for semantic highlighting.

You can use a Vim plugin or nvim-treesitter (https://github.com/nvim-treesitter/nvim-treesitter/) for highlighting svelte

**Comment by kamalkech** [comment]
nvim-treesitter is already install and configured, that s reason i post here to understand where is the problem 

![image](https://user-images.githubusercontent.com/1313428/184512209-1c5f9075-dbe5-4af1-ac46-7ffb587c2ab7.png)

lsp config file

![image](https://user-images.githubusercontent.com/1313428/184512345-8510ccdf-b7e1-4228-b5de-9a57025c068e.png)

**Comment by theHamsta** [comment]
@kamalkech and have you installed svelte, html and JS parsers? `:TSInstall svelte javascript typescript html`

In any way, this is not related to lsp-config

**Comment by kamalkech** [comment]
@ThatsNoMoon i am sorry for that because i am new user of neovim and thank for ur answer ;)

**Comment by kaiuri** [comment]
svelte-lsp provides semantic highlights, if you get it working it looks just like VSCode's highlights. Better in my opinion.
