### ISSUE TITLE
Include null-ls as alternative for Snippets support

### ISSUE THREAD

**Issue by paulodiovani** [neovim/nvim-lspconfig#2064]
### Language server

null-ls

### Requested feature

Currently, `lspconfig` suggest either `cmp` or `coq` for [snippets support](https://github.com/neovim/nvim-lspconfig/wiki/Snippets), but both these options are hard to configure (compared to `lspconfig`) and include a lot more (maybe unwanted) features, including:

- override completion feature and mapping, forbidding the use of `omnifunc`
- include other sources, like `ctags`

As an alternative, `null-ls` can be used for extra completions, and supports `luasnip` or `vssnip` as sources for snippets (https://github.com/jose-elias-alvarez/null-ls.nvim/blob/main/doc/BUILTINS.md#completion) with a far easier setup.

For people who wants to dive into the native lsp support without huge plugins, `null-ls` seems a better alternative. I've tried `cmp` and `coq` and found both too intrusive for my simple nvim setup.

**Comment by justinmk** [comment]
If this is a suggestion for the documentation, send a PR.

**Comment by paulodiovani** [comment]
No PR for the wiki, so I just included in https://github.com/neovim/nvim-lspconfig/wiki/Snippets#null-ls--luasnip
