### ISSUE TITLE
Add a setup option to configure border of the floating window of LspInfo and others

### ISSUE THREAD

**Issue by msva** [neovim/nvim-lspconfig#2068]
As per discussion in gitter/matrix, @glepnir asked to create an issue and tag him, and promised to inmpement it later :grin:

**Comment by glepnir** [comment]
@msva  Thanks for report.

**Comment by glepnir** [comment]
@msva  please check #2051 usage is `LspInfo border=single` highlight is `LspInfoBorder`

**Comment by msva** [comment]
> @msva please check #2051 usage is `LspInfo border=single` highlight is `LspInfoBorder`

Yeah, it works (renders wfloating window with specified type of borders, but:

1) will it be possible to set this up (default border type) with config after merging that PR?

2) I tried to set "custom" border (`nvim_open_win()` allows to pass a table with 8 elements, which will be used as border symbols), but it didn't work.
Not that I really need it now, just courious, if nothing broken.

**Comment by glepnir** [comment]
> will it be possible to set this up (default border type) with config after merging that PR?

yup we can set a default border.

> I tried to set "custom" border (nvim_open_win() allows to pass a table with 8 elements, which will be used as border symbols), but it didn't work.

support custom border it can be support.  I am thinking about is there a necessary to support custom border .looks like not make sense .because we have `single double rounded solid shadow none`.maybe enough ?

**Comment by msva** [comment]
> because we have `single double rounded solid shadow none`.maybe enough ?

Well, as I said, at lease for now, I, actually don't really need that.
But, on the other hand, as far as I know, this option just passed to `nvim_open_win()`, so, it is hust strange that it does not work :shrug:

**Comment by glepnir** [comment]
Now there has no lua interface  that you can use to set config of some commands. because `lspconfig` only provide the server config. so if you wan t to pass some configs to commands , you only  pass it from command line . pass a complex table will be like
` :LspInfo border= { { "character","highligt"}, { "character","highligt"}, { "character","highligt"}, { "character","highligt"}....}`
