### ISSUE TITLE
julials not starting

### ISSUE THREAD

**Issue by ignamartinoli** [neovim/nvim-lspconfig#2071]
### Description

After opening a **Julia** file, the LSP doesn't start automatically.

### Neovim version

NVIM v0.7.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

Freshly updated

### Operating system and version

Gentoo Base System release 2.8

### Affected language servers

julials

### Steps to reproduce

1. `nvim -nu minimal.lua`

### Actual behavior

LSP not starting on file opening

### Expected behavior

LSP starting on file opening 

### Minimal config

```Lua
local cmp = require 'cmp'
local cnl = require 'cmp_nvim_lsp'
local lsp = require 'lspconfig'
local snp = require 'luasnip'
local tel = require 'telescope.builtin'
local typ = require 'cmp.types'

local servers = {
	julials = {
		# The file is present
		cmd = { '/home/sicro/.local/share/nvim/mason/packages/julia-lsp/julia-lsp' }
	},
}

vim.lsp.set_log_level('debug')

for server, config in pairs(servers) do
	config = vim.tbl_deep_extend('keep', config, {
		capabilities = cnl.update_capabilities(vim.lsp.protocol.make_client_capabilities()),
		on_attach = function ()
			vim.keymap.set('n', 'ga', vim.lsp.buf.code_action)
			vim.keymap.set('n', 'gd', tel.diagnostics)
			vim.keymap.set('n', 'gi', tel.lsp_implementations)
			vim.keymap.set('n', 'gr', tel.lsp_references)
			vim.keymap.set('n', 'gs', tel.spell_suggest)
			vim.keymap.set('n', 'rn', vim.lsp.buf.rename)
		end
	})

	lsp[server].setup(config)
end
```

### LSP log

https://gist.github.com/ignamartinoli/ec7d3be4a6eaa871212d6948eae17c67

**Comment by justinmk** [comment]
> [ERROR][2022-08-18 03:33:08] .../vim/lsp/rpc.lua:420	"rpc"	"/home/sicro/.local/share/nvim/mason/packages/julia-lsp/julia-lsp"	"stderr"	"nvim-lsp.jl:15\nin expression starting at /home/sicro/.local/share/nvim/mason/packages/julia-lsp/nvim-lsp.jl:15\n"

julia-lsp/nvim-lsp.jl is throwing an error. That file doesn't live here.

**Comment by ignamartinoli** [comment]
I checked and here is the content of that directory

```
sicro@sicro ~ $ ls ~/.local/share/nvim/mason/packages/julia-lsp
julia-lsp  mason-receipt.json  nvim-lsp.jl  scripts
```

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
