### ISSUE TITLE
Prisma formatting is wrong

### ISSUE THREAD

**Issue by billop** [neovim/nvim-lspconfig#2086]
### Description

The formatting provided by prismals is incorrect in that it seems to use `vim.opt.shiftwidth` value for indentation rather than 2 spaces as `prisma format` would.

Relevant bit of lsp.log seems to be here: https://gist.github.com/billop/c4e6bcaf55f69bbbe434bc7384d6d0c6#file-lsp-log-L598

### Neovim version

NVIM v0.8.0-dev-929-g9a100ee169
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/x/.cache/paru/clone/neovim-git/src/build/cmake.config -I/home/x/.cache/paru/clone/neovim-git/src/neovim-git/src -I/usr/include -I/home/x/.cache/paru/clone/neovim-git/src/build/src/nvim/auto -I/home/x/.cache/paru/clone/neovim-git/src/build/include
Compiled by x@deep

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

b004cc6e586fd623d331eb78e7f258547d2225c3

### Operating system and version

Arch Linux

### Affected language servers

prismals

### Steps to reproduce

1. `mkdir testdir && cd testdir && touch .git`
2. create `prisma.schema` file with contents:
```prisma
datasource db {
provider = "postgresql"
url      = env("DATABASE_URL")
}
```
3. `nvim -u minimal_init.lua schema.prisma`
4. `:lua vim.lsp.buf.format()`

### Actual behavior

schema.prisma is formatted to this:
```prisma
datasource db {
                                                                                                    provider = "postgresql"
                                                                                                    url      = env("DATABASE_URL")
}
```

### Expected behavior

it should be formatted to this:
```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

### Minimal config

```Lua
vim.opt.shiftwidth = 100

local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      "neovim/nvim-lspconfig",
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  })
end

local load_config = function()
  vim.lsp.set_log_level("trace")
  require("vim.lsp.log").set_format_func(vim.inspect)
  local nvim_lsp = require("lspconfig")
  local on_attach = function(_, bufnr)
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

    -- Mappings.
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
    vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
    vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
    vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
    vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
    vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set("n", "<space>wl", function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
    vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
    vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
    vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
    vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
    vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
    vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
  end

  -- Add the server that troubles you here
  local name = "prismals"
  if not name then
    print("You have not defined a server name, please edit minimal_init.lua")
  end
  if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print([[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]])
  end

  nvim_lsp[name].setup({
    cmd = cmd,
    on_attach = on_attach,
  })

  print(
    [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
  )
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
  local packer_group = vim.api.nvim_create_augroup("Packer", { clear = true })
  vim.api.nvim_create_autocmd(
    "User",
    { pattern = "PackerComplete", callback = load_config, group = packer_group, once = true }
  )
else
  load_plugins()
  require("packer").sync()
  load_config()
end
```

### LSP log

https://gist.github.com/billop/c4e6bcaf55f69bbbe434bc7384d6d0c6

**Comment by glepnir** [comment]
I think there should some options in server settings . you may find this in server doc. then try to config it in server setting and give it a test

**Comment by billop** [comment]
Thanks for the tip.

I found the relevant code in neovim for setting tabSize when sending formatting requests to a language server:
https://github.com/neovim/neovim/blob/a46e6afb8b95229478c5c1fb75e3f1c55991def0/runtime/lua/vim/lsp/util.lua#L1990

Looks like for the lsp-format plugin this could be specified directly:
```lua
require("lsp-format").setup({
  prisma = { tabSize = 2 },
})
```

Although checking why other text editors automatically set tabSize to 2 it seems like this should be done at the filetype level.

```lua
-- RUNTIMEPATH/ftplugin/prisma.lua
vim.opt_local.shiftwidth = 2
vim.opt_local.tabstop = 2
```

**Comment by glepnir** [comment]
use `after/ftplugin/prisma.lua `
