### ISSUE TITLE
Misssing LspLog command?

### ISSUE THREAD

**Issue by anthony-S93** [neovim/nvim-lspconfig#2087]
### Description

![Missing Command](https://user-images.githubusercontent.com/69449791/186660233-48d8a945-7a64-4716-a367-545aad1b6b57.jpg)

Is anyone else having this issue? I read the change logs, but I didn't find anything about the `LspLog` command being deprecated. I already checked the `.cache/nvim/lsp.log` file. The logging itself is still working properly, just that the `LspLog` command is missing. 

I also made sure to update the plugin with vimplug. When that didn't work, I removed `nvim-lspconfig` entirely and re-installed it. 

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

### Operating system and version

Manjaro XFCE

### Affected language servers

all

### Steps to reproduce

1. Launch Neovim and enter command mode. 
2. Run `:LspLog`

### Actual behavior

`LspLog` is not listed inside the autocomplete list. When run, it says that `LspLog` is not an editor command. 

### Expected behavior

`LspLog` to be available.

### Minimal config

```Lua
Not applicable.
```

### LSP log

Not applicable.

**Comment by glepnir** [comment]
@anthony-S93  Does any command works fine ? `Lsplog` works for me

**Comment by anthony-S93** [comment]
@glepnir Every other command works fine. I swear I was still using LspLog just yesterday.

**Comment by glepnir** [comment]
@anthony-S93  you are right :) wait for while fix it later

**Comment by anthony-S93** [comment]
Cheers man.

**Comment by anthony-S93** [comment]
The problem is resolved. Thanks for being so efficient!

**Comment by glepnir** [comment]
it is okay. also thanks for report

**Comment by 1xcxcx** [comment]
I'm having this issue now with the stable branch (v0.9.0)
