### ISSUE TITLE
Jdtls Server exits with code 13

### ISSUE THREAD

**Issue by williamhCode** [neovim/nvim-lspconfig#2106]
### Description

I cannot get the jdtls language server to work. I have a build.gradle file which activates the root directory, and my build works correctly and everything, but the language server just doesn’t attach and it shows the error: 
`Client n quit with exit code 13 and signal`
This might be a local problem, and if it does anyone have any suggestions on how to fix it?
<img width="1792" alt="Screen Shot 2022-08-31 at 10 15 59 AM" src="https://user-images.githubusercontent.com/83525937/187700663-d2fabb41-0d8b-4c55-a0b1-ad1c3cf25386.png">

edit:
someone else also has this issue here: https://solveforum.com/forums/threads/problems-when-trying-to-install-jdtls-lsp-for-neovim.1333866/

### Neovim version

NVIM v0.8.0-dev+528-g3b1423bfa
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macos 12.5.1

### Affected language servers

jdtls

### Steps to reproduce

1. install nvim-lspconfig using any package manager
2. install jdtls using nvim-lsp-installer (what I did) or manually
3. have `require('lspconfig').jdtls.setup()` in vim config.
4. create a new directory and cd there
5. create a java file in the directory
6. activate the root directory requirements with a build file (ex. gradle init)

### Actual behavior

No clients attach to the buffer, and `Client n quit with exit code 13 and signal`

### Expected behavior

The language server should attach.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

local load_config = function()
  vim.lsp.set_log_level 'trace'
  require('vim.lsp.log').set_format_func(vim.inspect)
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
    vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
    vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
    vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
  end

  -- Add the server that troubles you here
  local name = 'jdtls'
  nvim_lsp[name].setup {
    on_attach = on_attach,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  local packer_group = vim.api.nvim_create_augroup('Packer', { clear = true })
  vim.api.nvim_create_autocmd(
    'User',
    { pattern = 'PackerComplete', callback = load_config, group = packer_group, once = true }
  )
else
  load_plugins()
  require('packer').sync()
  load_config()
end
```

### LSP log

https://gist.github.com/williamhCode/4c974065e13a309ab8b2766266a8c976

**Comment by glepnir** [comment]
@williamhCode   some useful information. should problem with your java env
https://www.reddit.com/r/neovim/comments/u2vlmb/client_1_quit_with_exit_code_1_and_signal_0_jdtls/

**Comment by williamhCode** [comment]
Thanks a lot. i literally just uninstalled, restarted, then installed the JDK and it worked!

**Comment by glepnir** [comment]
glad hear that.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/lspconfig-jdtls-server-not-attaching/3086/2

**Comment by Lcarv20** [comment]
Hi there, I went to lvim discord and was advised to  delete ./.cache/jdtls. It worked for me.

**Comment by williamhCode** [comment]
I actually had a weird error where it would say something along the lines of "table nil error: provided begin function without end" or something like that. I'd have to close the message and it would not work like 10% of the time. I just switched to nvim-jdtls and that works extremely well. U can even clear the jdtls workspace from nvim. Highly recommend even if u just need basic functionality.

**Comment by glepnir** [comment]
> U can even clear the jdtls workspace from nvim

you also can do this without any plugin.  you can get the workspace from jtdls then remove the folder

**Comment by glepnir** [comment]
> U can even clear the jdtls workspace from nvim

you also can do this without any plugin.  you can get the workspace from jtdls then remove the folder

**Comment by williamhCode** [comment]
Yeah, but its just one command so saves some time. But anyways, I just finished my Java OOP class (exam is tmr), so I'll probably never touch java again lmao.

But anyways here's a video of the error showing up. It pops up real fast before the server starts working.
https://user-images.githubusercontent.com/83525937/207293128-662f132b-27c8-400d-8f32-697f415c2ec1.mov

**Comment by glepnir** [comment]
honestly I have some distaste for java so I will not build any java environment. So there's nothing I can do sorry. Welcome to PR
