### ISSUE TITLE
Omnisharp .NET Framework and .NET 6 Support

### ISSUE THREAD

**Issue by KiLLeRRaT** [neovim/nvim-lspconfig#2108]
### Language server

omnisharp

### Requested feature

Hi,

I've recently realised that if I use the OmniSharp .NET 6 version, my .NET Framework projects doesn't have LSP support (This is also confirmed by the OmniSharp-Roslyn team).  So in those cases I have to use the .NET Framework OmniSharp version.  This means I have to keep changing config when loading different projects.  Right now upgrading all my projects to .NET 6 is not possible or feasible, too many projects.

Is there a way to support both? Maybe a prompt when loading a .cs file which asks if it's .NET Framework or .NET 6? Or perhaps detect by looking at the .csproj file that contains the file I just opened?

So I guess the way to do this is much like the `use mono`, but have that available on Windows as a setting, and also to load that dynamically based on the project type.

I'd appreciate some help or ideas on how to get this working fluidly without having to do config changes every time.

Thanks!

**Comment by glepnir** [comment]
I don't know much about .net projects. This is just a way I thought of maybe it can help you .

first disable the autostart of csharp_ls and ominisharp. avoid they auto start in cs file

```lua
lspconfig.csharp_ls.autostart({
  autostart = false
}

lspconfig.omnisharp.autostart({
  autostart = false
}

```
then

```lua
vim.api.nvim_create_autocmd("FileType",{
  pattern = 'csharp',
  callback = function()
    -- check the cspj or something else to confirm it's .net framework or .net core project
   if is_netcore then
       vim.cmd('LspStart  omnisharp')
        return
   end
   vim.cmd('LspStart csharp_ls')
  end
}

```

**Comment by KiLLeRRaT** [comment]
That's a great starting point, thank you! I will start dabbling with this.

**Comment by glepnir** [comment]
my pleasure :)
