### ISSUE TITLE
`Line with spaces only` in Lua should not appear in current line when editing

### ISSUE THREAD

**Issue by NEX-S** [neovim/nvim-lspconfig#2109]
### Description

in lua dev, diagnostics info: `Line with spaces only` in Lua should not appear in current cursor line(insert mode), it's little bit annoying when start a new line.

![image](https://user-images.githubusercontent.com/97107165/188304146-02c3467a-52f1-4f84-a02a-1c7eee2fc620.png)

### Neovim version

NVIM v0.8.0-dev-1020-gea10e0c104
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions     -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security     -fstack-clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/nex/.cache/yay/neovim-git/src/build/cmake.config -I/home/nex/.cache/yay/neovim-git/src/neovim-git/src -I/usr/include -I/home/nex/.cache/yay/neovim-git/src/build/src/nvim/auto -I/home/nex/.cache/yay/neovim-git/src/build/include

### Nvim-lspconfig version

NEWEST

### Operating system and version

Manjaro Linux Gnome

### Affected language servers

sumneko_lua or someother

### Steps to reproduce

open a lua file
into the insert mode
type someting and press to start a new line with autoindent
then we will see the diagnostics info: `Line with spaces only`

### Actual behavior

1

### Minimal config

```Lua
1
```

### LSP log

1

**Comment by glepnir** [comment]
that mean this newline has spaces. it should be your config problem. it make a newline has space.

**Comment by glepnir** [comment]
no check your indent config. we don't get this message.

**Comment by glepnir** [comment]
that's correct and the only way. disable diagnostic in insert mode.
