### ISSUE TITLE
Disabling auto insert of () on solargraph

### ISSUE THREAD

**Issue by otavioschwanck** [neovim/nvim-lspconfig#2113]
### Description

Continuation of: https://github.com/castwide/solargraph/issues/594

Ruby method call, when no arguments, shouldn't have (), its only methods with parameters.

the lsp is adding () itself.

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compilado por brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

    arquivo vimrc de sistema: "$VIM/sysinit.vim"
            padrão para $VIM: "/opt/homebrew/Cellar/neovim/0.7.2_1/share/nvim
"

Run :checkhealth for more info

### Nvim-lspconfig version

last commid

### Operating system and version

Mac

### Affected language servers

solargraph

### Steps to reproduce

```ruby
def call
end

value = call # (toggle call with autocomplete)
```

### Actual behavior

```ruby
value = call()
```

### Expected behavior

```ruby
value = call
```

### Minimal config

```Lua
.
```

### LSP log

.

**Comment by glepnir** [comment]
I think you need check your autopair plugin or completion plugin. lspconfig only provide the server config.
