### ISSUE TITLE
Store on_attach in configs

### ISSUE THREAD

**Issue by lbrayner** [neovim/nvim-lspconfig#2128]
### Requested feature

Currently these values are stored in [configs](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#L133) :

```lua
    -- Used by :LspInfo
    M.get_root_dir = get_root_dir
    M.filetypes = config.filetypes
    M.handlers = config.handlers
    M.cmd = config.cmd
    M.autostart = config.autostart
```

Let's say I have this setup in `plugin/lsp.lua`:

```lua
local lspconfig = require "lspconfig"

lspconfig.tsserver.setup {
    autostart = false,
    on_attach = function(_client, bufnr)
       vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc")
    end,
}
```

I want to override `cmd` in a site local file `after/plugin/lsp.lua`:

```lua
local tsserver = require "lspconfig".tsserver

local local_config = {
    cmd = {
        "tsserver-v16.15.1",
        "--stdio"
    },
}

tsserver.setup(vim.tbl_deep_extend("keep", local_config, tsserver))
```

My previous `autostart` setting is kept, but `on_attach` is lost. Therefore I'd like to request that `on_attach` be stored in `configs`.

**Comment by ranjithshegde** [comment]
If I am understanding your problem correctly, then there are several ways this can be handled.

check `:h vim.lsp.start_client`. Particularly `on_init` and `before_init` calls.

Also, `nvim 0.8` introduces an `LspAttach` autocmd which might be better for `on_attach` calls. That way you can have your overrides in `before_init` that can modify `cmd`, then your on attach called by `LspAttach` is unaffected.

`nvim-lspconfig` is for quick-start and default configurations. If you wish to override them per project, this plugin might not be the best place to handle it. You could simply override the default setup in that project's config entirely, or extract the table to simply change the `before_init` call.

**Comment by lbrayner** [comment]
Thanks, this plugin is amazing in the sense that it allows you to quickly benefit from the native LSP client without getting deep into the technical aspects and take your time to understand them if you choose to. I'll try your suggestions!
