### ISSUE TITLE
Clangd crashes for no reason.

### ISSUE THREAD

**Issue by seeth23** [neovim/nvim-lspconfig#2129]
### Description

While working in nvim with clangd, almost always server crashes after few minutes of working and won't restart, only restarts when I close nvim and open file again.
The last lsp.log error, when server stops respond: nStack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it
What is LLVM_SYMBOLIZER_PATH and how do I set it, there is no documentation in google on it.

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

linux 5.19.6-arch1-1

### Affected language servers

clangd

### Steps to reproduce

Default lsp config.

### Actual behavior

LSP stops suggesting stuffs and errors.

### Minimal config

```Lua
Default config from lsp-config repository
```

### LSP log

[ERROR][2022-09-09 19:15:33] .../vim/lsp/rpc.lua:420  "rpc" "clangd"  "stderr"  "/usr/lib/libc.so.6(__clone+0x44)[0x7f4a3c9208e4]\nStack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):\nSignalled during preamble action: CodeComplete\n

**Comment by glepnir** [comment]
I think it might relate with your env. can't reproduce that.

**Comment by justinmk** [comment]
Doesn't crash for me. This is not a support forum for LSP servers.
