### ISSUE TITLE
Enabling LSP server based on file extension

### ISSUE THREAD

**Issue by PolSust** [neovim/nvim-lspconfig#2140]
### Requested feature

Is there a way to enable lsp servers based on the file extension?

That way we could enable cssls for files ended in style.js or the html server for blade.php for example

It would give more control over when to enable which servers

**Comment by glepnir** [comment]
you can set your file extension with a filetype which in server settings filetypes.

**Comment by glepnir** [comment]
you can custom it with LspAttatch event if you are in 0.8 if file match `style.js` do smoething .

**Comment by PolSust** [comment]
Could you show an example?

**Comment by glepnir** [comment]
···lua
vim.api.nvim_create_autocmd('LspAttach', {
  callback = function()
       local file_name = vim.api.nvim_buf_get_name(0)
       if not ifle_name:find('style.ks') then
         return
       end
       local clients = vim.lsp.get_active_clients({buffer = 0 })
        do something ..
  end
})

``
