### ISSUE TITLE
pyre server not found

### ISSUE THREAD

**Issue by ALipAkrohk** [neovim/nvim-lspconfig#2146]
### Description

Unfortunately, the pyre server is not in the list of lspconfig servers, what is the reason?
![Screenshot_20220921_135832](https://user-images.githubusercontent.com/27810360/191469430-d91b28be-d079-494b-b1d0-eb64bef3f4af.png)
![Screenshot_20220921_140742](https://user-images.githubusercontent.com/27810360/191471055-09465caa-cfe4-4594-95c5-2f69078c7547.png)

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

51775b12cfbf1b6462c7b13cd020cc09e6767aea

### Operating system and version

arch linux 5.19.9-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Thu, 15 Sep 2022 16:08:24 +0000 x86_64 GNU/Linux

### Affected language servers

pyre

### Steps to reproduce

1. Open a Python file using neovim (be careful, you must use a neovim that already has lspconfig and mason installed on it, at least by default)
2. Type: LspInstall.

### Actual behavior

![Screenshot_20220921_135832](https://user-images.githubusercontent.com/27810360/191471811-b1b0916f-55a2-4b0f-bbd3-c55e980a2c5a.png)

### Expected behavior

It was expected to be easily installed and replaced just like other language servers.

### Minimal config

```Lua
How can I do this when the server is not found at all?
```

### LSP log

https://gist.github.com/ALipAkrohk/18d9b49debb314c618f94e6070bc41e3

**Comment by glepnir** [comment]
look at your pic you used the mason.nvim plugin to install server. please try install server manually or create an issue in mason.nvim
