### ISSUE TITLE
when LspInfo open the float window, press LspInfo again, cause buffer cannot be delete

### ISSUE THREAD

**Issue by Marskey** [neovim/nvim-lspconfig#2154]
### Description

```
Error executing Lua callback: ...packer/start/nvim-lspconfig/lua/lspconfig/ui/windows.lua:108: Window was closed immediately
stack traceback:
	[C]: in function 'nvim_open_win'
	...packer/start/nvim-lspconfig/lua/lspconfig/ui/windows.lua:108: in function 'percentage_range_window'
	...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:161: in function <...packer/start/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:148>
	...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:64: in function <...te/pack/packer/start/nvim-lspconfig/plugin/lspconfig.lua:63>
```
also cause Neo-tree plugin not working

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

### Nvim-lspconfig version

8e65dbb6e187604cdaf0e0ef2e90c790760912e7

### Operating system and version

macOS 12.3.1

### Affected language servers

any

### Steps to reproduce

1.in command mode :LspInfo
2.keep LspInfo floating window open
3.in command mode :LspInfo

### Actual behavior

None

### Expected behavior

close the previous floating window then open a new one to prevent error

### Minimal config

```Lua
None
```

### LSP log

None

**Comment by glepnir** [comment]
`LspInfo` is not a toggle command . the top line have a tip that you can use `q` or `esc` to close the lspInfo window
