### ISSUE TITLE
Add a field to specify the search directory for lsp servers

### ISSUE THREAD

**Issue by winkee01** [neovim/nvim-lspconfig#2180]
### Language server

anyone

### Requested feature

Currently, lspconfig can only search lsp servers that are in System $PATH, if lsp servers are located in some other directory, there is noway to tell lspconfig to to find them.  For example, I downloaded all my lsp server binaries in `~/.local/bin` directory,  without some additional plugins (like mason & mason-lspconfig), lspconfig can not find them.

**Comment by justinmk** [comment]
you can already set an explicit path
