### ISSUE TITLE
Add a field to specify the search directory for lsp servers

### ISSUE THREAD

**Issue by winkee01** [neovim/nvim-lspconfig#2182]
### Language server

anyone

### Requested feature

Currently, lspconfig can only search lsp servers that are in System $PATH, if lsp servers are located in some other directory, there is noway to tell lspconfig to to find them. For example, I downloaded all my lsp server binaries in `~/.local/bin` directory, without some additional plugins (like mason & mason-lspconfig), lspconfig can not find them.

the search directory field can be something like this: 

````
search_dir: {'~/.local/bin', '~/.local/share/nvim/lsp_servers/'}
````

**My previous request was closed without a convincing reason**, the guy said I already can set an explicit path, but the problem with his method is that I have to set an explicit path for **every lsp server**, that's tedious and is the core reason I want a feature that can set the **search directory**. I mean you won't execute a shell command each time with an absolute path, right? the system searches it for you in $PATH. Won't it be so nice to have this feature?

At the moment, I can only use a third party plugin to achieve this, for example, `lsp-installer`, after its `setup()` function is called, lspconfig can find all executables in `~/.local/share/nvim/lsp_servers`, but I don't know how that works. Maybe we can get some ideas from it.

### Other clients which have this feature

neovim

**Comment by glepnir** [comment]
> My previous request was closed without a convincing reason, the guy said I already can set an explicit path

that mean you can  explicitly pass the path to the server's cmd command

**Comment by winkee01** [comment]
> > My previous request was closed without a convincing reason, the guy said I already can set an explicit path
> 
> that mean you can explicitly pass the path to the server's cmd command

Sorry? I know that. What I am saying is it's tedious and I have to pass the path to every server. If I can set a search directory, I don't have to specify in every cmd = "".

**Comment by glepnir** [comment]
If you put all the servers in `~/,local/bin` do it like this ?

```lua
local function get_server()
    local path = '~/.local/bin/'
    local server_list = { 
         ['c'] = 'clangd',
         ['go'] = 'gopls',
         ['rust'] = 'rust-analyazer'
    }
    if server_list[vim.bo.filetype] then
          return path ..  server_list[vim.bo.filetype]
    end
    vim.notify('Does not find server bin file', vim.log.Error)
end

lspconfig.gopls = {
       cmd = get_server(),
        ....
}
```

**Comment by winkee01** [comment]
@glepnir Hi, while hard-coding a path prefix here could be a solution. I still can't understand what could be the problem with achieving it with a search directory. isn't it much more convenient?

**Comment by glepnir** [comment]
maybe a simple code snippet like this. but I still think do it like above code is enough. if  @justinmk   agree add this option  I will implement.

```diff
diff --git a/lua/lspconfig/configs.lua b/lua/lspconfig/configs.lua
index b963e42..1f1e200 100644
--- a/lua/lspconfig/configs.lua
+++ b/lua/lspconfig/configs.lua
@@ -33,6 +33,14 @@ function configs.__newindex(t, config_name, config_def)
   function M.setup(user_config)
     local lsp_group = vim.api.nvim_create_augroup('lspconfig', { clear = false })
 
+    if lsp.util.search_dir then
+      for _,dir in pairs(lsp.util.search_dir) do
+        if vim.fn.executable(dir .. user_config.cmd[1]) then
+          user_config.cmd[1] = dir .. user_config.cmd[1]
+        end
+      end
+    end
+
     validate {
       cmd = { user_config.cmd, 't', true },
       root_dir = { user_config.root_dir, 'f', true },
```

**Comment by winkee01** [comment]
> 

Sure, I think it's the way to implement it, looping through `search_dir` table and see if it's an executable. 👍

**Comment by justinmk** [comment]
> **My previous request was closed without a convincing reason**, the guy said I already can set an explicit path, but the problem with his method is that I have to set an explicit path for **every lsp server**, that's tedious and is the core reason I want a feature that can set the **search directory**

Adding path-like behavior to nvim-lspconfig is out of scope for nvim-lspconfig. If something like this is really needed it should be done in the core client in https://github.com/neovim/neovim

**Comment by winkee01** [comment]
👎
