### ISSUE TITLE
warning: multiple different client offset_encodings detected

### ISSUE THREAD

**Issue by NEX-S** [neovim/nvim-lspconfig#2184]
### Description

every time i peek_definition, I got this message `warning: multiple different client offset_encodings detected for buffer, this is not supported yet` I don't know what's happening.

### Neovim version

NVIM v0.9.0-dev-55-gedc8a1f04
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az119-532

### Nvim-lspconfig version

newest

### Operating system and version

Arch Linux Gnome

### Affected language servers

clangd

### Steps to reproduce

call vim.lsp.buf.definition() on some symbol

### Actual behavior

1

### Expected behavior

goto definition directly

### Minimal config

```Lua
lspconfig.clangd.setup {
    on_attach = M.on_attach,
    capabilities = M.capabilities,
    -- single_file_support = true,
    -- root_dir = root_dir('c'),
    -- cmd = {
    --     "clangd",
    --     -- "--background-index",
    --     -- "--clang-tidy",
    --     -- "--clang-tidy-checks=performance-*,bugprone-*",
    --     -- "--all-scopes-completion",
    --     -- "--completion-style=detailed",
    --     -- "--header-insertion=iwyu",
    -- }
}
```

### LSP log

```
[WARN][2022-10-10 00:34:55] ...lsp/handlers.lua:113	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2022-10-10 00:34:55] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:55.785] <-- textDocument/documentSymbol(3)\nI[00:34:55.785] --> reply:textDocument/documentSymbol(3) 0 ms\n"
[ERROR][2022-10-10 00:34:56] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:56.180] <-- shutdown(4)\nI[00:34:56.180] --> reply:shutdown(4) 0 ms\n"
[ERROR][2022-10-10 00:34:56] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:56.182] <-- exit\nI[00:34:56.182] LSP finished, exiting with status 0\n"
[START][2022-10-10 00:34:58] LSP logging initiated
[ERROR][2022-10-10 00:34:58] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:58.734] clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)\nI[00:34:58.734] Features: linux+grpc\nI[00:34:58.734] PID: 23384\nI[00:34:58.734] Working directory: /home/nex/tmp\nI[00:34:58.734] argv[0]: clangd\nI[00:34:58.734] Starting LSP over stdin/stdout\nI[00:34:58.734] <-- initialize(1)\nI[00:34:58.735] --> reply:initialize(1) 0 ms\n"
[ERROR][2022-10-10 00:34:58] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:58.782] <-- initialized\nI[00:34:58.782] <-- textDocument/didOpen\n"
[ERROR][2022-10-10 00:34:58] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:58.782] <-- textDocument/documentSymbol(2)\nI[00:34:58.782] Failed to find compilation database for /home/nex/tmp/test.c\nI[00:34:58.782] ASTWorker building file /home/nex/tmp/test.c version 0 with command clangd fallback\n[/home/nex/tmp]\n/usr/bin/clang -resource-dir=/home/nex/.local/share/nvim/mason/packages/clangd/clangd/lib/clang/15.0.1 -- /home/nex/tmp/test.c\n"
[ERROR][2022-10-10 00:34:58] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:58.802] --> textDocument/publishDiagnostics\n"
[ERROR][2022-10-10 00:34:58] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:58.803] --> reply:textDocument/documentSymbol(2) 20 ms\n"
[WARN][2022-10-10 00:34:59] ...lsp/handlers.lua:113	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[ERROR][2022-10-10 00:34:59] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:59.138] <-- textDocument/documentSymbol(3)\n"
[ERROR][2022-10-10 00:34:59] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:34:59.138] --> reply:textDocument/documentSymbol(3) 0 ms\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.070] <-- textDocument/definition(4)\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.070] --> reply:textDocument/definition(4) 0 ms\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.706] clangd version 15.0.1 (https://github.com/llvm/llvm-project b73d2c8c720a8c8e6e73b11be4e27afa6cb75bdf)\nI[00:35:01.706] Features: linux+grpc\nI[00:35:01.706] PID: 23413\nI[00:35:01.706] Working directory: /usr/include\nI[00:35:01.706] argv[0]: clangd\nI[00:35:01.706] Starting LSP over stdin/stdout\nI[00:35:01.706] <-- initialize(1)\nI[00:35:01.707] --> reply:initialize(1) 0 ms\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.731] <-- initialized\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.731] <-- textDocument/didOpen\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.732] <-- textDocument/documentSymbol(2)\nI[00:35:01.732] Failed to find compilation database for /usr/include/stdio.h\nI[00:35:01.732] ASTWorker building file /usr/include/stdio.h version 0 with command clangd fallback\n[/usr/include]\n/usr/bin/clang -xobjective-c++-header -resource-dir=/home/nex/.local/share/nvim/mason/packages/clangd/clangd/lib/clang/15.0.1 -- /usr/include/stdio.h\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.754] --> textDocument/publishDiagnostics\n"
[ERROR][2022-10-10 00:35:01] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[00:35:01.755] --> reply:textDocument/documentSymbol(2) 23 ms\n"

```

**Comment by justinmk** [comment]
It's just a warning. Coming from here: https://github.com/neovim/neovim/blob/09dffb9db7d16496e55e86f78ab60241533d86f6/runtime/lua/vim/lsp/util.lua#L1917-L1946

@rish987 @mfussenegger does this happen if multiple servers are working on the same buffer?

**Comment by mfussenegger** [comment]
> It's just a warning. Coming from here: https://github.com/neovim/neovim/blob/09dffb9db7d16496e55e86f78ab60241533d86f6/runtime/lua/vim/lsp/util.lua#L1917-L1946
> 
> @rish987 @mfussenegger does this happen if multiple servers are working on the same buffer?

It happens if multiple clients with different offset encoding are attached to the same buffer. Usually it's clangd using utf-8, + some other using utf-16.

The fix is to set the offset encoding to utf-16 for clangd too.

**Comment by Corgile** [comment]
> The fix is to set the offset encoding to utf-16 for clangd too.

## how

**Comment by tanveerraza789** [comment]
If you're using lazy to handle plugins you can find it here `~/.local/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/server-configurations/clangd.lua` or simply use `find / -type f -iname "clangd.lua"` to check where the file exist, then change
```lua
local default_capabilities = {
  textDocument = {
    completion = {
      editsNearCursor = true,
    },
  },
  offsetEncoding =  { 'utrf-8', 'utf-16' } ,
}
```
to
```lua
local default_capabilities = {
  textDocument = {
    completion = {
      editsNearCursor = true,
    },
  },
  offsetEncoding =  'utf-16' ,
}
```

This worked for me.

**Comment by joshuachp** [comment]
If anyone is having problem with `rust-analyzer` and ends up here. The message about the different encoding problem disappeared after setting the `general.positionalEncodings` capabilities:

```lua
--- Generates the LSP client capabilities
--- @return table
function M.default_capabilities()
  -- Client capabilities
  local capabilities = vim.lsp.protocol.make_client_capabilities()
 
  --- Setup capabilities to support utf-16, since copilot.lua only works with utf-16
  --- this is a workaround to the limitations of copilot language server
  capabilities = vim.tbl_deep_extend('force', capabilities, {
    offsetEncoding = { 'utf-16' },
    general = {
      positionEncodings = { 'utf-16' },
    },
  })

  return capabilities
end


```

**Comment by glepnir** [comment]
it has been fixed  see https://github.com/neovim/neovim/commit/15641f38cf4b489a7c83e2c3aa6efc4c63009f00

**Comment by doums** [comment]
Hi, @glepnir even with the above commit, I still need to add @joshuachp config bits to fix the issue
Is that normal?

**Comment by joshuachp** [comment]
In the diff it seems that all of the UTF encodings are advertised. Unfortunately with copilot, I believe it's still necessary to restrict them to UTF-16 with the above configuration

**Comment by harrykar** [comment]
> If you're using lazy to handle plugins you can find it here `~/.local/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/server-configurations/clangd.lua` or simply use `find / -type f -iname "clangd.lua"` to check where the file exist, then change
> 
> ```lua
> local default_capabilities = {
>   textDocument = {
>     completion = {
>       editsNearCursor = true,
>     },
>   },
>   offsetEncoding =  { 'utrf-8', 'utf-16' } ,
> }
> ```
> 
> to
> 
> ```lua
> local default_capabilities = {
>   textDocument = {
>     completion = {
>       editsNearCursor = true,
>     },
>   },
>   offsetEncoding =  'utf-16' ,
> }
> ```
> 
> This worked for me.

Thank you very much finally got rid that annoying warning

**Comment by the-bokya** [comment]
> If you're using lazy to handle plugins you can find it here `~/.local/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/server-configurations/clangd.lua` or simply use `find / -type f -iname "clangd.lua"` to check where the file exist, then change
> 
> local default_capabilities = {
>   textDocument = {
>     completion = {
>       editsNearCursor = true,
>     },
>   },
>   offsetEncoding =  { 'utrf-8', 'utf-16' } ,
> }
> 
> to
> 
> local default_capabilities = {
>   textDocument = {
>     completion = {
>       editsNearCursor = true,
>     },
>   },
>   offsetEncoding =  'utf-16' ,
> }
> 
> This worked for me.

here for @atamakahere-git
