### ISSUE TITLE
Clangd not finding/indexing includes from arm GNU Toolchain

### ISSUE THREAD

**Issue by arminveres** [neovim/nvim-lspconfig#2206]
### Description

I am trying to work on an embedded project on the Raspberry Pi Pico, for which I have got set up the toolchain system and SDK.
On VScode the workspace/projekt gets indexed automatically, while inside neovim, it doesn't recognize the includes.
I have a `compile_commands.json` and according to the LspLog it also gets recognized
`[ERROR][2022-10-20 16:57:42] .../vim/lsp/rpc.lua:733	"rpc"	"clangd"	"stderr"	"I[16:57:42.848] <-- textDocument/documentHighlight(3)\nI[16:57:42.848] Loaded compilation database from /home/arminveres/Projects/picolino/build/compile_commands.json\nI[16:57:42.848] <-- clangd/inlayHints(4)\n"`
and compiling also works.

The link to the toolchain: https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

### Neovim version

NVIM v0.8.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

3592f769f2d6b07ce3083744cd0a13442f5d4f43

### Operating system and version

Fedora release 36 (Thirty Six) x86_64
5.19.16-200.fc36.x86_64

### Affected language servers

clangd

### Steps to reproduce

For a reproduction one could clone my repo https://github.com/arminveres/picolino.git and compile it.
My (neovim) lsp config: https://github.com/arminveres/dotfiles/blob/main/dotfiles/nvim/.config/nvim/lua/user/lsp/settings/clangd.lua

### Actual behavior

![image](https://user-images.githubusercontent.com/45210978/196985663-a0cf2238-7040-4711-a138-42b03e13faca.png)

### Expected behavior

Correct indexing and no errors of missing headers.

### Minimal config

```Lua
https://github.com/arminveres/dotfiles/blob/main/dotfiles/nvim/.config/nvim/
```

### LSP log

https://gist.github.com/arminveres/7af4003f9588964d35c6a09b14ef2142

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by rollschild** [comment]
Hi @arminveres I'm having the same error. Did you by any chance solve/fix it? I'm curious. Thanks!

**Comment by arminveres** [comment]
> Hi @arminveres I'm having the same error. Did you by any chance solve/fix it? I'm curious. Thanks!

It's kind of a hit or miss, but you can use the `--query-driver=*gcc*` flag for clangd and even glob the compiler. Although gcc does not always work for C++ as it does not recognize the c++ headers. clangd also prefers `compile_commands.json` so it may mess up there as well and prioritize the compiler used in there.

[This](https://github.com/arminveres/nvim/blob/main/lua/user/lsp/settings/clangd.lua) is how I am using it now.
