### ISSUE TITLE
Unable to goto next/previous diagnotsic

### ISSUE THREAD

**Issue by cameron1024** [neovim/nvim-lspconfig#2207]
### Description

Apologies in advance if this is an LSP-specific issue, I'm not sure if this issue belongs here or the main nvim repo. 

When trying to use `vim.lsp.diagnostic.goto_next({ focusable = false })` (and `goto_prev`), I get an error:
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'goto_next' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```
The error persists even without specifying `focusable = false`.

This has previously worked, but an upgrade has broken this. Running `print(vim.inspect(vim.lsp.diagnostic))` gives this:
```
{
  get_line_diagnostics = <function 1>,
  get_namespace = <function 2>,
  on_publish_diagnostics = <function 3>,
  reset = <function 4>
}
```
Happy to provide any details that might help. Thanks in advance :grin: 

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/14a0mn10gkbxs5knxa4kxk8qlbgi9k0c-neovim-unwrapped-0.8.0/share/nvim
"

Run :checkhealth for more info

### Operating system and version

NixOS 22.05

### Affected language servers

all

### Steps to reproduce

Run command `:lua vim.lsp.diagnostic.goto_next()` (whether an LSP client is connected or not)

### Actual behavior

I get the error mentioned

### Expected behavior

It jumps to the next diagnostic

### Minimal config

```Lua
The unmodified minimal_init.lua reproduces this issue
```

### LSP log

(There was no log file after triggering the issue) https://gist.github.com/cameron1024/fce251d475419c9057a0ab0c60bc3792

**Comment by cpmsmith** [comment]
Looks like you're looking at an old version of `minimal_init.lua`. Most of the functions in `vim.lsp.diagnostic` have been moved to `vim.diagnostic` (see breaking change here: https://github.com/neovim/neovim/issues/14090#issuecomment-921312955), and `minimal_init.lua` was updated here: https://github.com/neovim/nvim-lspconfig/commit/db8357abc0c97a5110e7adb6decfe2c13ecd43b4

**Comment by cameron1024** [comment]
AHH, I must have missed this in the changeling. Thanks for the speedy reply, works perfectly 😊
