### ISSUE TITLE
attempt to index local 'user_config' (a nil value)

### ISSUE THREAD

**Issue by bendavis78** [neovim/nvim-lspconfig#2211]
### Description

Starting neovim gives the following error:

```
Error detected while processing /Users/bdavis/.dotfiles/.config/nvim/init.vim[2]../Users/bdavis/.dotfiles/.vim/vimrc[37]../Users/bdavis/.dotfiles/.vim/rc.d/ls
p-config.vim:
line    2:
E5108: Error executing lua ...are/vim/plugged/nvim-lspconfig/lua/lspconfig/configs.lua:37: attempt to index local 'user_config' (a nil value)
stack traceback:
        ...are/vim/plugged/nvim-lspconfig/lua/lspconfig/configs.lua:37: in function 'setup'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

ee2e8c63cff0a8bfc7f4ef985ea466f10bb7e691

### Operating system and version

macOS 12.6

### Affected language servers

all

### Steps to reproduce

1. start nvim using config shown below

### Actual behavior

error shown above

### Expected behavior

no error

### Minimal config

```Lua
local Plug = vim.fn['plug#']
vim.call('plug#begin', '~/.local/share/vim/plugged')
Plug 'neovim/nvim-lspconfig'
vim.call('plug#end')

vim.lsp.set_log_level('debug')

require'lspconfig'.pyright.setup(){}
```

### LSP log

log file not created

**Comment by bendavis78** [comment]
Just found my error. The last line in my init should instead be:

    require'lspconfig'.pyright.setup{}

**Comment by jost-s** [comment]
For anyone coming across this, I had just

```lua
require("lspconfig").tsserver.setup()
```

and it had to be

```lua
require("lspconfig").tsserver.setup({})
```

with empty curly braces. Took me a while!
