### ISSUE TITLE
move/rename file and update imports

### ISSUE THREAD

**Issue by renzhamin** [neovim/nvim-lspconfig#2215]
### Requested feature

Language servers usually have the ability to 
- move code segment to a new file and update all the imports or 
- automatically update imports on file rename via `:!mv ... ...` 

But I haven't found a way to do it with nvim-lsp

There's no interface like vim.lsp.buf.rename_file, there is vim.lsp.util.rename but that just renames the file and doesnt update any imports

As far as I know vim.lsp.buf.rename doesnt deal with file renames

Another problem : 
Move to a new file code action uses the very first function/variable name as the new filename and doesn't ask for the new filename, so even if I can move some code segment to a new file, I have no control over the new filename
if it did there could be a workaround to achieve file rename by selecting everything and use the move to a new file code action, then deleting the current file.
I'm not sure if this behaviour is language server specific, the one I tested with is tsserver

Note : coc has CocCommand workspace.renameCurrentFile

Expected behaviour should be to prompt the user if imports should be updated after a `:!mv ... ` ,  as is the case with coc

### Other clients which have this feature

coc

**Comment by glepnir** [comment]
please create this feature request on neovim .thanks for report.
