### ISSUE TITLE
Ability to "abort" starting/attaching based on details of the buffer

### ISSUE THREAD

**Issue by gwerbin** [neovim/nvim-lspconfig#2224]
### Language server

N/A

### Requested feature

In certain situations, I want to prevent a language server from starting or attaching to a buffer. I don't want to set `autostart = false` because I still do want autostart in most cases.

However, there are some specific situations (e.g. specific root dir, specific buffer name, or even specific file contents) when I do *not* want a language server attached to the buffer.

**The request**: I want to be able to "abort" the current LSP startup/attach process from inside one of the setup hook functions. Maybe I can do this by returning some specific sentinel value, or calling some specific function, in one of the setup hook functions.

Practical example: I want to autostart the YAML language server, _except_ when the file appears to contain Jinja template syntax.

One workaround would be to set `autostart = false` and then write my own autocommand to call `LspStart` or `LspAttach`, with my own if/else checks. But then I lose the benefit of the Lspconfig magic root detection to choose between starting a new client and attaching an existing one.

### Other clients which have this feature

Unknown

**Comment by justinmk** [comment]
More features are out of scope for lspconfig, which is intended to be only a set of quickstart configs. 

This might be worth raising at https://github.com/neovim/neovim
