### ISSUE TITLE
packer.nvim: Error running config for nvim-lspconfig: attempt to call a nil value

### ISSUE THREAD

**Issue by kevinkirkup** [neovim/nvim-lspconfig#2225]
### Description

Every time I load na new `nvim` instance, I get this error message with no other information.
I've tried to remove everything in the nvim-lspconfig configuration file but still get the same result.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

 5f4b1fa83c80f43e434c1fb227967dac9ad8f44c 

### Operating system and version

macOS 13.0

### Affected language servers

all

### Steps to reproduce

1. nvim

### Actual behavior

LSP isn't loaded

### Expected behavior

LSP should be loaded

### Minimal config

```Lua
[START][2022-11-04 14:58:36] LSP logging initiated
[INFO][2022-11-04 14:58:36] .../lua/vim/lsp.lua:1814    "exit_handler"  {}
```

### LSP log

asdf

**Comment by glepnir** [comment]
please provide more information. the min config and reproduce step!!
