### ISSUE TITLE
[lsp] request add https://github.com/Tencent/LuaHelper

### ISSUE THREAD

**Issue by cathaysia** [neovim/nvim-lspconfig#2227]
### Language server

luahelper

### Requested feature

add lsp https://github.com/Tencent/LuaHelper

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by cathaysia** [comment]
thanks, I can do this later :)
________________________________
