### ISSUE TITLE
GraphQL does not provide hover information when hovering first character of an identifier

### ISSUE THREAD

**Issue by DanielPower** [neovim/nvim-lspconfig#2231]
### Description

There appears to be an off by one error in the column number provided to the language server. The first character of an identifier does not provide hover information. However, if you put a single space after the identifier, that space will provide hover information.

### Neovim version

NVIM v0.8.0                                                                           
Build type: Release                                                                   
LuaJIT 2.1.0-beta3                                                                    
Compiled by brew@Monterey 

### Nvim-lspconfig version

5f4b1fa83c80f43e434c1fb227967dac9ad8f44c

### Operating system and version

MacOS 12.6

### Affected language servers

graphql

### Steps to reproduce

Reproduction video:

https://user-images.githubusercontent.com/12166320/200351816-6747abf5-876f-4f34-b804-0c4c6da52154.mov

1. `nvim -nu minimal_init.lua`
2. Open a GraphQL file
3. Move cursor to the first character of an identifier
4. `K`

You will receive the message "No information available"

5. Move the cursor to any other character on that identifier
6. `K`

You should receive the hover popup with type information.

7. Add a couple of spaces after the identifier name, and attempt to hover on them.

You'll notice that the first space after the identifier provides hover information, but subsequent spaces do not.

### Actual behavior

Hover information is provided when the cursor is on any part of an identifier except for the first character.

### Expected behavior

Hover information should be provided when the cursor is on the first character of an identifier.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
	require("packer").startup({
		{
			"wbthomason/packer.nvim",
			"neovim/nvim-lspconfig",
		},
		config = {
			package_root = package_root,
			compile_path = compile_path,
		},
	})
end

local load_config = function()
	vim.lsp.set_log_level("trace")
	require("vim.lsp.log").set_format_func(vim.inspect)
	local nvim_lsp = require("lspconfig")
	local on_attach = function(_, bufnr)
		local function buf_set_option(...)
			vim.api.nvim_buf_set_option(bufnr, ...)
		end

		buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

		-- Mappings.
		local opts = { buffer = bufnr, noremap = true, silent = true }
		vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
		vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
		vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
		vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
		vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
		vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
		vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
		vim.keymap.set("n", "<space>wl", function()
			print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
		end, opts)
		vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
		vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
		vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
		vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
		vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
		vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
		vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
	end

	-- Add the server that troubles you here
	local name = "graphql"
	local cmd = { "graphql-lsp", "server", "-m", "stream" } -- needed for elixirls, omnisharp, sumneko_lua
	if not name then
		print("You have not defined a server name, please edit minimal_init.lua")
	end
	if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
		print([[You have not defined a server default cmd for a server
      that requires it please edit minimal_init.lua]])
	end

	nvim_lsp[name].setup({
		cmd = cmd,
		on_attach = on_attach,
	})

	print([[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]])
end

if vim.fn.isdirectory(install_path) == 0 then
	vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
	load_plugins()
	require("packer").sync()
	local packer_group = vim.api.nvim_create_augroup("Packer", { clear = true })
	vim.api.nvim_create_autocmd(
		"User",
		{ pattern = "PackerComplete", callback = load_config, group = packer_group, once = true }
	)
else
	load_plugins()
	require("packer").sync()
	load_config()
end
```

### LSP log

The reproduction steps did not produce any log outputs

**Comment by glepnir** [comment]
I don't think it's hover ? your `<C-k>` map to `signature_help`

**Comment by DanielPower** [comment]
I'm sorry, I did mean hover, but wrote the wrong binding in my reproduction step. I should have said `K`.

**Comment by justinmk** [comment]
we don't debug individual lang servers. If there's a bug in Nvim LSP report it to neovim main repo. But do not ask troubleshooting questions there.

**Comment by DanielPower** [comment]
I used the minimal config that **you** provide, and showed that the issue exists there. I'm not asking troubleshooting questions. I'm reporting a bug.

Whether the bug is with lspconfig, nvim core, or the graphql language server itself I do not, and I do not have the knowledge to determine.

If the bug is not with lspconfig, can you tell me where you believe it to be?
