### ISSUE TITLE
Support tsserver settings

### ISSUE THREAD

**Issue by chrisgrieser** [neovim/nvim-lspconfig#2243]
### Language server

tsserver

### Requested feature

The typescript language server does support some settings for formatting and inlayhints, and those [are implemented for Sublime](https://github.com/sublimelsp/LSP-typescript/blob/master/LSP-typescript.sublime-settings) or [coc-tsserver](https://github.com/neoclide/coc-tsserver#configuration-options).

However, I cannot figure out how to configure `tsserver` when using neovim's builtin LSP.

The server configuration docs do not list a `settings` key as a [configuration option for tsserver](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver), and instead recommend to use a `tsconfig.json` or `jsconfig.js`.

I tried both, using `jsconfig.json`, as well as passing `settings` in `require("lspconfig").tsserver.setup()` similar to how it works with the `sumneko_lua` LSP, but I could not get it to work either way. (To be sure that it isn't an issue with the [inlayhints-plugin](https://github.com/lvimuser/lsp-inlayhints.nvim) (which does work for sumneko_lua for me), I tried changing formatting options.)

### Other clients which have this feature

sumneko_lua, css

**Comment by lithammer** [comment]
Likely because they're integrating with tsserver directly (which isn't a language server) while we're using https://github.com/typescript-language-server/typescript-language-server. However the README mentions experimental support for inlay hints though.

**Comment by chrisgrieser** [comment]
I see. well, the inlay hint support loos more like instructions for LSP client devs than for LSP users to me, though...

Well, that means that basically, we are not able to configure ts/js with the builtin LSP then? 🙁

**Comment by chrisgrieser** [comment]
@kylo252 Thanks for the suggestion!

using those configurations, it does work 🥳 
Seems I was indeed looking in the wrong place for the configuration options
