### ISSUE TITLE
zls download fails

### ISSUE THREAD

**Issue by jalornales** [neovim/nvim-lspconfig#2249]
### Description

Downloading zls failed. Returns 404

### Neovim version

NVIM v0.8.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

debian 11

### Affected language servers

zls

### Steps to reproduce

1. `nvim`
2. `:LspInstall zig`
3. press 1 to select zls and press Enter

### Actual behavior

Returns this Error
`    ➜ zls (failed)
        Downloading file "https://github.com/zigtools/zls/releases/download/0.10.0/x86_64-linux.tar.xz"...
        ...taller/lua/nvim-lsp-installer/core/managers/std/init.lua:61: Failed to download file "https://github.com/zigtools/zls/releases/download/0.10.0/x86_64-linux.tar.xz".
        spawn: curl failed with exit code 22. curl: (22) The requested URL returned error: 404 
`

when looking at the zls releases page

![image](https://user-images.githubusercontent.com/95468718/202842911-2cc28319-3eaa-4044-b665-0cceab4b6614.png)

downloader looks for *.tar.xz file while at release page has *.tar.zst

### Minimal config

```Lua
N/A
```

### LSP log

N/A

**Comment by glepnir** [comment]
nvim-lspconfig does not have `LspInstall` command. I think you used the mason or something else .

**Comment by sigmaSd** [comment]
Lspinstall is not part of this project its this https://github.com/williamboman/nvim-lsp-installer/ 

And just so you know its deprecated and the the maintainer suggest moving to https://github.com/williamboman/mason.nvim

**Comment by jalornales** [comment]
Oh, my apologies. I thought this was the repo for that. 
Thank you
