### ISSUE TITLE
yamlls is active when filetype is "helm"

### ISSUE THREAD

**Issue by varac** [neovim/nvim-lspconfig#2252]
### Description

I try to setup [helm linting ls](https://github.com/mrjosh/helm-ls). If works, but my configured yamlls starts complaining even though it's configured for yaml files only (default `filetypes : { "yaml", "yaml.docker-compose" }`).

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

ea5744f9243ec25a178a0bc403a4c8203ecc4f23

### Operating system and version

PopOS 22.04

### Affected language servers

yamlls, helm-ls

### Steps to reproduce

1. Configure `yamlls`, [vim-helm](https://github.com/towolf/vim-helm) and [helm-ls](https://github.com/mrjosh/helm-ls) (see minimal config below)
2. Edit any helm chart template, i.e. 

```
git clone https://github.com/bitnami/charts.git
nvim -u /tmp/helm_ls.lua  bitnami/bitnami/nginx/templates/deployment.yaml 
```

### Actual behavior

* Filetype is set properly to `helm`
* `yamlls` is active (LspInfo hows it as client attached to the buffer) and it produces errors all over the place because helm templates are not valid yaml, see screenshot below:

![image](https://user-images.githubusercontent.com/488213/203411438-098058b1-3d3c-4a51-a2ed-a1484ad8f7a2.png)

### Expected behavior

`yamlls` should *not* be active when filtype is `helm`.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

local function load_plugins()
  require('packer').startup {
    {
      'wbthomason/packer.nvim',
      'towolf/vim-helm',
      'neovim/nvim-lspconfig',
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  }
end

local load_config = function()
  vim.lsp.set_log_level 'trace'
  require('vim.lsp.log').set_format_func(vim.inspect)
  local nvim_lsp = require 'lspconfig'
  local on_attach = function(_, bufnr)
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
    vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
    vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
    vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
  end

  -- Add the server that troubles you here

  -- https://github.com/mrjosh/helm-ls#nvim-lspconfig-setup

  local configs = require('lspconfig.configs')
  local util = require('lspconfig.util')

  if not configs.helm_ls then
    configs.helm_ls = {
      default_config = {
        cmd = {"helm_ls", "serve"},
        filetypes = {'helm'},
        root_dir = function(fname)
          return util.root_pattern('Chart.yaml')(fname)
        end,
      },
    }
  end
  local lsp = require('lspconfig')
  lsp.helm_ls.setup {
    filetypes = {"helm"},
    cmd = {"helm_ls", "serve"},
  }

  lsp.yamlls.setup{
    -- on_attach = on_attach,
    -- -- filetypes = { "yaml", "yaml.docker-compose" },
    -- filetypes = { "yaml.docker-compose" },
    -- flags = lsp_flags,
    -- capabilities = capabilities,
    -- settings = {
    --   yaml = {
    --     completion =  true,
  }

  print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system { 'git', 'clone', 'https://github.com/wbthomason/packer.nvim', install_path }
  load_plugins()
  require('packer').sync()
  local packer_group = vim.api.nvim_create_augroup('Packer', { clear = true })
  vim.api.nvim_create_autocmd(
    'User',
    { pattern = 'PackerComplete', callback = load_config, group = packer_group, once = true }
  )
else
  load_plugins()
  require('packer').sync()
  load_config()
end

```
```


### LSP log

https://gist.github.com/varac/1ea134e78288e79dd7e95e4454cc0b57

**Comment by glepnir** [comment]
because it also use `.yaml` file when you open this file it will trigger the `Filetype` event early before you changed it filetype I think . so the yamlls started.  try this

```lua
vim.api.nvim_create_autocmd({'BufNewFile', 'BufRead'} , {
    pattern = 'deployment.yaml',
    callback = function()
          vim.opt_local.filetype = 'helm'
    end
```
`BufNewFile, BufRead` is triggered before `FileType` event.

**Comment by varac** [comment]
@glepnir Thank you for your quick response ! It works nicely.
For reference, the [vim-helm plugin sets the filetype here](https://github.com/towolf/vim-helm/blob/master/ftdetect/helm.vim):

    autocmd BufRead,BufNewFile */templates/*.yaml,*/templates/*.tpl,*.gotmpl,helmfile*.yaml set ft=helm

I just wonder what would be the best way to fix this in a more general way, since I guess I might bump into similar issues like this, where some plugin sets the filetype and I would need to duplicate the filename pattern in an override like above.
Do you have any idea what needs to happen to solve this ? Would a change needs to happen in plugins like vim-helm, neovim or lspconfig itself ?

**Comment by glepnir** [comment]
there is nothing to do on neovim or lspconfig. because the helm use `yaml` file as it config file with a new filetype.  if it has a fixed name then the problem becomes very simple. But it doesn't. I think it would be better to specify some rules in your config or some plugins.

**Comment by david-polak** [comment]
To prevent yamlls from attaching for anyone with the following setup: `Lazy`; `nvim-lspconfig`; `helm_ls`; `yamlls`

Use this lazy plugin definition, `ft='helm'` sorts out the yamlls errors on helm files.
```
return { 
  'towolf/vim-helm',       
  ft = 'helm' 
}
```

**Comment by relief-melone** [comment]
My autocommand is a bit different. What I basically do is I scan the first 50 lines of the file and if {{ gets found it changes the filetype to helm. I have yamlls and helm_ls enabled. A bit sketchy I admit but it does the trick for me pretty well so far. I'm using nixvim so the syntax is a bit different

```nix
{
  autoCmd = [
    {
      event = [ "BufRead" "BufNewFile" ];
      pattern = [ "*.yaml" "*.yml" ];
      callback = {
        __raw = ''
          function()
            local lines = vim.api.nvim_buf_get_lines(0, 0, 50, false)
            for _, line in ipairs(lines) do
              if line:match("{{") then
                vim.bo.filetype = "helm"
                break
              end
            end
          end
        '';
      };
    }
  ];
}
```
