### ISSUE TITLE
add erblint?

### ISSUE THREAD

**Issue by lidizi** [neovim/nvim-lspconfig#2253]
### Language server

erb-lint

### Requested feature

add erblint?

### Other clients which have this feature

null-ls

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).
