### ISSUE TITLE
Expose root_dir to texlab.rootDirectory

### ISSUE THREAD

**Issue by har7an** [neovim/nvim-lspconfig#2259]
### Language server

texlab

### Requested feature

Hello,

I think it would be helpful if nvim-lspconfig could share its determined `root_dir` with LSP servers if they define a similar config/attribute. In particular I've come across this with `texlab` LSP. I've got a multifolder project and the "rootdir detection" in `texlab` picks the wrong root directory. However, nvim determines it correctly.

This could be solved e.g. by providing the `root_dir` to `settings.texlab.rootDirectory`, in case the latter is `nil` (the default). Unfortunately, I haven't yet found a way to do this, because `root_dir` is determined by means of a function. I'm also not sure whether this is run exactly once at LSP server startup, or repeatedly as needed.

I'm also open to using a workaround that I can fill into `texlab.rootDirectory` at LSP startup time, but honestly I wouldn't know how to do that.

Thank you!

**Comment by glepnir** [comment]
you can use   `on_new_config` with a new root_dir

**Comment by har7an** [comment]
@glepnir First time I hear about that. Would something like this do:

```lua
    on_new_config = function(new_config, new_root_dir)
        return new_config.settings.texlab.rootDirectory = new_root_dir
    end,
```

or how exactly does it work? The docs I've found so far didn't explain much about it.

**Comment by har7an** [comment]
For anyone interested, this seems to work:

```lua
    on_new_config = function(new_config, new_root_dir)
        new_config.settings.texlab.rootDirectory = new_root_dir
    end,
```

Thank you very much, @glepnir !

**Comment by glepnir** [comment]
my pleasure, close then.
