### ISSUE TITLE
Create an open buffer when LSP requests a file

### ISSUE THREAD

**Issue by Invertisment** [neovim/nvim-lspconfig#2261]
### Description

When I'm editing a source file and use LSP server's refactoring to add a test then I can't view the file.
I can't see the file in NvimTree and I can't see the file in `:ls`. The buffer isn't loaded and the file isn't saved on disk.

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

abe6c99

### Operating system and version

Linux 6.0.2-2

### Affected language servers

clojure-lsp, maybe others as well

### Steps to reproduce

1. Open a project which an LSP server can handle (I used clojure-lsp but it can be any project that has LSP server refactoring that creates files)
2. Trigger a file creation from LSP side
3. File is not visible in NvimTree buffer
4. File is not visible in `:ls` (maybe that's a clue, probably)

### Actual behavior

When I choose `10: Create test for 'my-function'` in `clojure-lsp` server's refactoring menu then I can't see the file.
If the test file that I'm adding doesn't exist then LSP server will send a file creation request to nvim so that it would be created (but not written yet). 
So these "created but non-written" files are not displayed in vim.

Do you think it's a good idea to display them? These files also don't show up in the `:ls` menu. So it may be a problem with `nvim` itself or a problem with how nvim handles LSP. I don't know much how it's handled so I write here.

### Expected behavior

Files should at least show up in `:ls` command menu. NvimTree could also show them (persist empty file to disk and load it) but first the `:ls` should show that the buffer exists.

### Minimal config

```Lua
I think this should be easily reproducible with any language server and any config as long as it has "create test" or a similar refactoring option.
```

### LSP log

none

**Comment by glepnir** [comment]
> 10: Create test for 'my-function'

about this from code action ?

**Comment by Invertisment** [comment]
When I trigger that code action for `clojure-lsp` then it calls this function:
https://github.com/clojure-lsp/clojure-lsp/blob/01500c34e00efa2b4affc627bdc80e89af18f55d/lib/src/clojure_lsp/refactor/transform.clj#L970

But this function doesn't actually create files and only instructs the editor that LSP has edited that file.
That means that the editor doesn't pick it up.

**Comment by glepnir** [comment]
looks like a code action kind is `refactor` and it will create a test file.

**Comment by Invertisment** [comment]
I know. But then why doesn't it show up in `:ls` command menu?

**Comment by glepnir** [comment]
`ls` command will ouput the buffers which set the `buflisted ` option.

**Comment by glepnir** [comment]
you can use this after you called the code action

```lua
local buf = vim.fn.bufadd('your new file')
vim.bo[buf].buflisted = true
```
then you will see this file in your `ls` command

**Comment by Invertisment** [comment]
Ok. So... this needs to run when nvim gets input from LSP server, not when I decide it has to run :thinking:
Can I even control it for each and every LSP server...?

**Comment by glepnir** [comment]
you can..need rewrite the default handlers of code action.

**Comment by sigmaSd** [comment]
I did some debugging, it seems like clojure lsp wants the test file to exist before the code action, if you do that it will apply the edits correctly.

If you don't have the file already it sends `workspace/applyEdit`  with no params which is weird 
![image](https://user-images.githubusercontent.com/22427111/204823837-dd9f2bd2-76bb-45fd-b0be-92eaf09b7f6a.png)
