### ISSUE TITLE
`root_dir` is being ignored

### ISSUE THREAD

**Issue by datwaft** [neovim/nvim-lspconfig#2273]
### Description

Hello!

I am trying to implement [this suggestion](https://deno.land/manual@v1.28.2/getting_started/setup_your_environment#neovim-06-using-the-built-in-language-server) from Deno's documentation but I am having a problem, when setting `root_dir` with the suggested values it is being ignored. When checking with `:LspInfo` I can see that the servers still have their default values.

This issue is similar to #2069.

### Neovim version

NVIM v0.9.0-dev-408+g98695b499
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

d346335af862ede0cece75739d789cfdc46c4454

### Operating system and version

macOS 13.0.1

### Affected language servers

tsserver, denols

### Steps to reproduce

1. Use the minimal configuration and install `lspconfig`.

2. Create a Typescript project with a `.git` folder inside (can be deno or tsserver, in both happens).

3. Open any typescript file inside that project.

### Actual behavior

Both `denols` and `tsserver` are being loaded into the buffer because they still have `.git` as part of their `root_dir` configuration.

### Expected behavior

If the project doesn't contain a `package.json` nor a `deno.json` then neither of the language servers must be loaded. If the project contains a `package.json` only `tsserver` must be loaded and if the project contains a `deno.json` only `denols` must be loaded.

### Minimal config

```Lua
local lspconfig = require("lspconfig")

lspconfig.denols.setup({
  root_dir = lspconfig.util.root_pattern("deno.json", "deno.jsonc"),
})

lspconfig.tsserver.setup({
  root_dir = lspconfig.util.root_pattern("package.json"),
})
```

### LSP log

https://gist.github.com/datwaft/22e964e1a56e481a265e1b3b33f9426d

**Comment by glepnir** [comment]
can't reproduce. if are using packer  I think you need recompile your config file

**Comment by datwaft** [comment]
I could reproduce it in a Docker environment (I did it to verify it before creating the issue).

I will recreate the docker environment and I will send you the Github repository link.

I could reproduce it with only lspconfig installed, without packer or any other plugin.

**Comment by glepnir** [comment]
I had test it in a min config with clean neovim. it works fine. test config

```lua
vim.opt.runtimepath:append("~/Workspace/nvim-lspconfig/")
local lspconfig = require("lspconfig")
lspconfig.tsserver.setup({
  root_dir = lspconfig.util.root_pattern('package.json')
})
```
test dir

```
.
├── .git
│   ├── HEAD
│   ├── config
│   ├── description
│   ├── hooks
│   │   ├── applypatch-msg.sample
│   │   ├── commit-msg.sample
│   │   ├── fsmonitor-watchman.sample
│   │   ├── post-update.sample
│   │   ├── pre-applypatch.sample
│   │   ├── pre-commit.sample
│   │   ├── pre-merge-commit.sample
│   │   ├── pre-push.sample
│   │   ├── pre-rebase.sample
│   │   ├── pre-receive.sample
│   │   ├── prepare-commit-msg.sample
│   │   ├── push-to-checkout.sample
│   │   └── update.sample
│   ├── info
│   │   └── exclude
│   ├── objects
│   │   ├── info
│   │   └── pack
│   └── refs
│       ├── heads
│       └── tags
├── min.lua
└── test.ts

```

-  `nvim --clean -u ./min.lua test.ts`
-  `LspInfo` there is no tsserver client attatched

**Comment by datwaft** [comment]
I finally got to reproduce it again using Docker. It is a pain because deno lasts 10 minutes compiling.

As you can see in this screenshot, if I don't have the `.git` folder it works properly (but it shows that it search for the default root patterns even if I overrode those in my configuration):

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/204958861-5320de3a-4991-4f03-808a-09b3bd8c47c9.png">

The same with `tsserver`:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/204958924-b37d748b-0ee6-4b74-a899-81d11452d3cd.png">

But, when I created the `.git` folder using `git init .`, even if it showed that it searched for `.git`, that seems to be a visual bug, as it didn't load the other language server:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/204959676-617fe4e0-cab1-44d6-ac9d-2392a0d87ec4.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/204959620-02b6d6aa-fe39-4207-8111-64a7d203e690.png">

So that means that my issue was not reproduced by the `.git` folder, but some other reason.

As you can see here it is still occurring in my personal configuration:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/204959334-1dcb168f-b440-4dcd-be17-1786bec864e6.png">

Do I open a new issue for that visual bug, or is that expected behavior?

I refer to specifically this line:

```
root directory:    Not found. Searched for: root_pattern("package.json", "tsconfig.json", "jsconfig.json", ".git").
```

I will continue debugging my configuration and will open a new issue if I find the cause of my issue and am able to reproduce it with Docker.

Thanks for your help!

**Comment by glepnir** [comment]
about the `Searched for` it get the pattern from server document config. so it's not mean it will search that when you override the root_dir pattern. I think should remove the `Searched for` text message

**Comment by datwaft** [comment]
As an small update, in case someone also has the same issue.

Using my minimal config example but without Docker makes no difference, the issue is not reproduced.

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/37723586/204963018-f9c40122-222a-4a13-9b91-75a9ea627400.png">

**Comment by datwaft** [comment]
I finally found the cause of this issue. You can see it here: https://github.com/folke/neoconf.nvim/issues/1

I leave this here in case someone in the future finds this issue and haves the same problem.

Thanks for your help!
