### ISSUE TITLE
Multi workspace support for `sumneko_lua`

### ISSUE THREAD

**Issue by musjj** [neovim/nvim-lspconfig#2302]
### Language server

sumneko_lua

### Requested feature

https://github.com/sumneko/lua-language-server/wiki/Developing#multiple-workspace-support
Is it possible to have a multi-workspace environment for `sumneko_lua`? AKA, a single LSP instance for multiple projects?
I've also noticed this PR: https://github.com/neovim/nvim-lspconfig/pull/2287, does it have anything to do with this feature?
I'm on the latest lspconfig commit with the latest nvim nightly, but multiple Lua projects still spawn multiple LSP instances.
A few other related issues I've found:
https://github.com/neovim/nvim-lspconfig/issues/842
https://github.com/prabirshrestha/vim-lsp/issues/1069

### Other clients which have this feature

vim-lsp

**Comment by musjj** [comment]
Did a quick look through the code, and it seems that this is a bug caused by treating `clients` as a number-keyed table instead of a string-keyed table :
```lua
if clients[1] then
  local client = lsp.get_client_by_id(clients[1])
  if client.name == new_config.name then
    local params = lsp.util.make_workspace_params(
      { { uri = vim.uri_from_fname(root_dir), name = root_dir } },
      { {} }
    )
    table.insert(client.workspace_folders, params.event.added[1])
    return clients[1]
  end
end
```

When it is properly treated, multi workspace now works (the list of workspace folders also have to be checked and initialized):
```lua
local _, id = next(clients)
if id then
  local client = lsp.get_client_by_id(id)
  if client.name == new_config.name then
    local params = lsp.util.make_workspace_params(
      { { uri = vim.uri_from_fname(root_dir), name = root_dir } },
      { {} }
    )
    client.workspace_folders = client.workspace_folders or {}
    table.insert(client.workspace_folders, params.event.added[1])
    return id
  end
end
```

**Comment by glepnir** [comment]
can you test #2303 ?

**Comment by glepnir** [comment]
seems like the clients store the null-ls not sumneko_lua so there still spawn the new lua server.

**Comment by ehaynes99** [comment]
Sorry, I don't follow. *Previously* (I was on `f11fdff7e8b5b415e5ef1837bdcdd37ea6764dda`), it would spawn a new lua server. Now, it does not. There's just one instance with a now arbitrary root.

**Comment by glepnir** [comment]
I don't think spawn multiple servers is correct. it should use one instance with multiple workspacefolders.  in your situation it should have one lua instance. when you open file1 in project 1 the proejct 1 will insert to worskpaceFolders . same as other projects. currently problem is the `clients` store the last server in you case is null-ls. so there is only one null-ls instance. it should store all servers not last one.

**Comment by musjj** [comment]
@glepnir 
You also need to check if `client.workspace_folders` is `nil` and initialize a new table if so.
https://github.com/neovim/nvim-lspconfig/blob/3bb0c53b1df74d4b3b70d5939a015b19064a5a06/lua/lspconfig/util.lua#L261

@ehaynes99 
Yes, it does _look_ weird, but it works. Doing it this way saves a lot of RAM for heavier LSPs.
I think in the future the workspace folders should also be listed in `:LspInfo` to make it clearer.

**Comment by glepnir** [comment]
I will fix the root dir of lspinfo . it should show the correct path from workspace folders.

**Comment by musjj** [comment]
If `client.workspace_folders` is `nil`, then it will crash, because `table.insert` only accepts tables.
I had it crash because of that, even though the client wasn't in single file mode.
Also, another possible edge case is a client that doesn't support multi workspaces. I think most clients supports it now, but there might be some that don't.

**Comment by glepnir** [comment]
@musjj  @ehaynes99  check #2304

**Comment by glepnir** [comment]
#2304 not merge now. if you want test .please use #2304 branch for test not master.

**Comment by ehaynes99** [comment]
I used this, correct?
```lua
  { 'glepnir/nvim-lspconfig', branch = 'fixing' },
```

**Comment by glepnir** [comment]
I test it works fine you structure like this right ?

```
  tree
.
├── project1
│   └── p1.lua
├── project2
│   └── p2.lua
└── project3
    └── p3.lua

```

**Comment by ehaynes99** [comment]
Cool, looks good now!
