### ISSUE TITLE
One LSP-server multiple Buffers

### ISSUE THREAD

**Issue by Mikilio** [neovim/nvim-lspconfig#2306]
### Requested feature

I noticed that each buffer will start its own instance of an LSP server even if they are of the same file type, each hogging 600MB of memory  (in the case of Lua). Since it is quite common to have multiple buffers of the same type open during development but can only edit one at a time, this seems like a waste of resources. 
The question is:
Can we do better?

**Comment by glepnir** [comment]
#2304
