### ISSUE TITLE
Implement handler for 'workspace/diagnostic/refresh'

### ISSUE THREAD

**Issue by Mikilio** [neovim/nvim-lspconfig#2309]
### Language server

sumneko_lua

### Requested feature

Apparently, the server always requests the above-mentioned method but the client has no handler for it. This causes a warning in the lsp.log:
`[WARN][2022-12-12 10:27:52] .../lua/vim/lsp.lua:1065	"server_request: no handler found for"	"workspace/diagnostic/refresh"
`
I don't really like warnings, so I hope someone who feels the same could solve this.

(In reality, this warning is duplicated and thrown twice maybe [this](https://gist.github.com/folke/fe5d28423ea5380929c3f7ce674c41d8) solution by @folke can help here.)

**Comment by glepnir** [comment]
create at neovim core.

**Comment by folke** [comment]
I have the following in my dots to fix this. Should probably be added to core:
```lua
  vim.lsp.handlers["workspace/diagnostic/refresh"] = function(_, _, ctx)
    local ns = vim.lsp.diagnostic.get_namespace(ctx.client_id)
    pcall(vim.diagnostic.reset, ns)
    return true
  end
```

**Comment by wvffle** [comment]
> I have the following in my dots to fix this. Should probably be added to core:
> 
>   vim.lsp.handlers["workspace/diagnostic/refresh"] = function(_, _, ctx)
>     local ns = vim.lsp.diagnostic.get_namespace(ctx.client_id)
>     pcall(vim.diagnostic.reset, ns)
>     return true
>   end

This breakes rustaceanvim diagnostics. They are displayed for a split second and then are reset. However looking at neovim source code, it seems like it's already implemented?
