### ISSUE TITLE
Allow customizing gdscript port

### ISSUE THREAD

**Issue by Cretezy** [neovim/nvim-lspconfig#2311]
### Language server

gdscript

### Requested feature

The gdscript configuration hard-codes 6008 (https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/gdscript.lua), while Godot allows for customizing the port (see screenshot).

![image](https://user-images.githubusercontent.com/2672503/207092988-651361f1-b7b5-4538-99f2-73011783c1e4.png)

Since Godot 3 and 4 uses different ports, it would be great to allow customizing the port.

### Other clients which have this feature

Godot's VS Code plugin has an option to change the port.
![image](https://user-images.githubusercontent.com/2672503/207093135-02b10c0f-1e12-432a-a765-a2aa5bf6b788.png)

Also it seems CoC has it, however I'm not experienced using it. https://github.com/habamax/vim-godot#setting-up-cocnvim-for-godot-322

**Comment by glepnir** [comment]
#2313 work with a port env variable named `GDScript_Port` .

**Comment by Cretezy** [comment]
That would definitely help. Is there a way to pass it to the `setup` function too?

**Comment by glepnir** [comment]
hmm currently can do that . but a little trouble :) so maybe we can support it in future.
