### ISSUE TITLE
E5108: 'show_line_diagnostics'

### ISSUE THREAD

**Issue by kristoferjoseph** [neovim/nvim-lspconfig#2315]
### Description

When attempting to get line diagnostics from an info hint I get the following error:
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'show_line_diagnostics' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
```

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

Features: +acl +iconv +tui

### Operating system and version

macOS 12.6

### Affected language servers

all

### Steps to reproduce

go to line with info marker.
trigger line diagnostics

### Actual behavior

Error

### Expected behavior

Diagnostics for line are shown

### Minimal config

```Lua
na
```

### LSP log

na

**Comment by gpanders** [comment]
You have a chunk of code somewhere (either in a plugin or in your own config) using `vim.lsp.diagnostics.get_line_diagnostics()`, which was deprecated in Neovim 0.7 and removed in Neovim 0.8. Use `vim.diagnostic.get()` instead.
