### ISSUE TITLE
Call Hierarchy on tsserver

### ISSUE THREAD

**Issue by nfrid** [neovim/nvim-lspconfig#2317]
### Language server

tsserver

### Requested feature

Add support for `textDocument/prepareCallHierarchy` to `tsserver`.

It has support for call history for a long time now (https://github.com/microsoft/TypeScript/pull/35176).
But yet, when I try and call `vim.lsp.buf.incoming_calls()`, it shows this error: `method textDocument/prepareCallHierarchy is not supported by any of the servers registered for the current buffer`.

It seems like tsserver really does not have `textDocument/prepareCallHierarchy` method but somehow `coc-tsserver` added the support (https://github.com/neoclide/coc-tsserver/issues/128).

It doesn't look like something `nvim-lspconfig` has to do with, but I would appreciate if you help me at least find out what we can do to make it work.

### Other clients which have this feature

coc-tsserver

**Comment by nfrid** [comment]
oh I see... Thank you very much 😊

**Comment by nfrid** [comment]
it seems there is already an issue **and** a PR: https://github.com/typescript-language-server/typescript-language-server/issues/591 | https://github.com/typescript-language-server/typescript-language-server/pull/98

**Comment by justinmk** [comment]
> BTW, The naming of this server in nvim-lspconfig is confusing because it is actually not `tsserver` and some features are not implemented.

+1 for fixing that
