### ISSUE TITLE
lemminx does not work on Windows

### ISSUE THREAD

**Issue by sa-mendez** [neovim/nvim-lspconfig#2319]
### Description

Spawning the lemminx language server fails when running neovim (with mason) on Windows, but works on Linux .  After some digging into this, I found the problem to be that the **cmd** is always set to 'lemminx'.   This works fine on Linux, but not on Windows.

The solution is probably to just implement the same fix as was done in #2039.

I have tested this locally and it works.  I only tested on Windows, but I am sure it works on Linux (and other OSes as well).

### Neovim version

NVIM v0.8.0-1210-gd367ed9b2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

3bb0c53b1df74d4b3b70d5939a015b19064a5a06

### Operating system and version

Windows 10

### Affected language servers

lemminx

### Steps to reproduce

Open XML file after setting up nvim-lspconfig with lemminx language server.

### Actual behavior

Fails to spawn lemminx language server.  I get notified with the following error:

_Spawning language server with cmd: `lemminx` failed. The language server is either not installed, missing from PATH, or not executable._

### Expected behavior

lemminx language server should launch properly.

### Minimal config

```Lua
NA
```

### LSP log

NA

**Comment by justinmk** [comment]
> The solution is probably to just implement the same fix as was done in #2039.

The solution is to make `cmd` just do this automatically. No more of these one-off changes for each langserver.

**Comment by sa-mendez** [comment]
I wholeheartedly agree.  After poking around your issues, I see that you have #2130 already tracking this more general approach.  Should I close this, and mark it as a duplicate of that?

**Comment by glepnir** [comment]
duplicate #2130
