### ISSUE TITLE
Docs: asm-lsp info is lacking

### ISSUE THREAD

**Issue by madskjeldgaard** [neovim/nvim-lspconfig#2328]
### Description

The info for the `asm-lsp` server has a line that doesn't make immediate sense to me. "See source file", it says, but which source file and see what?

https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md?plain=1#L568

Would be great with a clarification. Thanks a lot <3

### Neovim version

Latest

### Operating system and version

macos

### Affected language servers

asm-lsp

### Steps to reproduce

docs

### Actual behavior

docs

### Minimal config

```Lua
docs
```

### LSP log

docs

**Comment by madskjeldgaard** [comment]
And it seems this particular key `root_dir` causes an error in LSP, which is why I looked it up :) 

```
Config: asm_lsp
 	Refer to :h lspconfig-root-detection for help.
 	filetypes:         asm, vmasm
 	root directory:    Not found.
 	cmd:               asm-lsp
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```

**Comment by glepnir** [comment]
`see source file` that mean check the `asm_lsp.lua` . the root dir of `asm_lsp` use `.git` folder

**Comment by glepnir** [comment]
k
