### ISSUE TITLE
Unnecessary error in pop-up window

### ISSUE THREAD

**Issue by atpur-rafif** [neovim/nvim-lspconfig#2340]
### Description

![image](https://user-images.githubusercontent.com/66266045/209028168-c46f9ab8-e917-42d2-99ef-7e411b1b5228.png)
There is red error in pop-up window at the end of parenthesis

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

WSL

### Affected language servers

sumneko_lua

### Steps to reproduce

1. Use config described below
1. Install Packer using `:PackerSync`
1. Run `:lua vim.lsp.buf.hover()` over the function (twice to go into the pop-up window)
1. To check the highlight info, use `:echo synIDattr(synID(line("."), col("."), 1), "name")` over closing parenthesis in pop-up window

### Actual behavior

![image](https://user-images.githubusercontent.com/66266045/209028168-c46f9ab8-e917-42d2-99ef-7e411b1b5228.png)
Red parenthesis in pop-up window, when inspecting what the highlight is, got
![image](https://user-images.githubusercontent.com/66266045/209028338-68713488-abe6-4bde-b033-2a1007152ea3.png)
luaParenError 

### Expected behavior

No error in pop-up window

### Minimal config

```Lua
local use = require('packer').use
require('packer').startup(function()
  use 'wbthomason/packer.nvim' -- Package manager
  use 'neovim/nvim-lspconfig' -- Configurations for Nvim LSP
end)

require('lspconfig').sumneko_lua.setup {
	settings = {
		Lua = {
			runtime = {
				version = "Lua 5.1"
			},
			diagnostics = {
				globals = { 'vim' }
			}
		}
	}
}

vim.lsp.start({ name = 'sumneko-lua',
  cmd = {'lua-language-server'}
})
```

### LSP log

https://gist.github.com/atpur-rafif/dad970a53fbfcb23ae5918eb63635b41

**Comment by glepnir** [comment]
It's `LuaParenError` problem of syntax. already known issue on neovim core
