### ISSUE TITLE
Duplicated LSP server

### ISSUE THREAD

**Issue by lvim-tech** [neovim/nvim-lspconfig#2353]
### Description

Each buffer starts the lsp server

### Neovim version

NVIM v0.9.0-dev-554+g6f25623e7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

efafc5d09f1815f29985108f0edfd1fe74b65458

### Operating system and version

openSuse Leap

### Affected language servers

all

### Steps to reproduce

1. Start nvim 
2. Open file1.lua
3. Open file2.lua in horizontal (or vertical) split
4. Create session file (:mksession session_name)
5. Close nvim
6. Start nvim
7. Load session (:source session_name)

### Actual behavior

Each buffer starts the lsp server

### Minimal config

```Lua
yes
```

### LSP log

https://gist.github.com/lvim-tech/67e2670f9e566b300ac2ef32e9dc28ba

**Comment by glepnir** [comment]
can't reproduce.

**Comment by glepnir** [comment]
can you test #2354
