### ISSUE TITLE
b0bd429 breaks sumneko_lua

### ISSUE THREAD

**Issue by folke** [neovim/nvim-lspconfig#2355]
### Description

When I switch between a file in my workspace and a file outside the worksapce, sumneko diagnostics get reset on all buffers and all buffers start showing errors.

The error only starts happening after b0bd429

See also https://github.com/folke/neodev.nvim/issues/98

### Neovim version

nightly

### Operating system and version

linux

### Affected language servers

sumneko_lua

### Steps to reproduce

1. open a lua file in your project directory that is in .gitignore
2. open a lua file in your project

### Actual behavior

The second file will list a lot of errors

### Expected behavior

no errors

### Minimal config

```Lua
..
```

### LSP log

...

**Comment by glepnir** [comment]
do you add this `    diagnostics = { globals = { 'vim' },` line ?

**Comment by glepnir** [comment]
does #2356 works for you ?

**Comment by folke** [comment]
just tested and still the same issue.

One sumneko instance always has two internal instances running. One for single files and one for the workspace.

It seems that when I open a single file, that the config without the workspace is pushed to the active sumneko instance and as such clearing its workspace settings

**Comment by theHamsta** [comment]
For me, https://github.com/neovim/nvim-lspconfig/commit/b0bd4297763024bfeb0c3065609361fb599c3594 or a commit after it causes `rust-analyzer` to crash with error code 101 (https://github.com/rust-lang/rust-analyzer/blob/2872e0558982360d499bdba79cf1a3ed06f1ae82/crates/rust-analyzer/src/bin/main.rs#L41-L45). Reverting to before https://github.com/neovim/nvim-lspconfig/commit/b0bd4297763024bfeb0c3065609361fb599c3594 fixes the problem.
