### ISSUE TITLE
LspStop should stop only managed clients

### ISSUE THREAD

**Issue by ianliu** [neovim/nvim-lspconfig#2358]
### Description

`LspStop` is currently stopping all LSP clients attached to the current buffer, even those not managed by lspconfig, such as null-ls.

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

25f0c65bd8fddadbafd0048a68560bf160ceb98c

### Operating system and version

Arch Linux

### Affected language servers

all

### Steps to reproduce

1. Setup lspconfig and null-ls
2. `LspInfo` shows 2 clients
3. `LspStop`
4. `LspInfo` shows 0 clients

### Actual behavior

`LspStop` is closing all clients on this line: https://github.com/neovim/nvim-lspconfig/blob/a63d2c75c6880d45209baff596939343e8a431fd/plugin/lspconfig.lua#L132

### Expected behavior

It should close only managed clients, like `LspRestart` does.

### Minimal config

```Lua
n/a
```

### LSP log

n/a

**Comment by glepnir** [comment]
there has a param wrong  it's `bufnr` not `buffer`. it should close all clients of this buffer.

**Comment by ianliu** [comment]
@glepnir I've seen your commit, but it doesn't change the behavior of LspStop. As of now, LspStop is closing all clients attached to the current buffer. This is problematic for clients that aren't managed by lspconfig, such as null-ls, since it is not possible (or trivial) to restart null-ls. For example, LspStart will not start null-ls again after a LspStop.

**Comment by glepnir** [comment]
you can use `LspStop client_name` to stop the client that you want stop.  you setup two clients `null-ls` and other client , then you want `LspStop` without any argument to close one ? how to do ? how neovim know which client you want to close ?
also someone want this command close all.  currently please use `Lspstop with argument`

**Comment by ianliu** [comment]
I was expecting `LspStop` to stop the managed clients by using the `require('lspconfig.util').get_managed_clients()` function.

**Comment by glepnir** [comment]
currently this function had rewrite . it get clients for all root.
