### ISSUE TITLE
Haskell HLS v1.9.0.0 should be enabled on .cabal files

### ISSUE THREAD

**Issue by mizlan** [neovim/nvim-lspconfig#2369]
### Description

The super-recent release of HLS 1.9.0.0 allows HLS to work on `.cabal` files, but only that version (and up). If it is feasible to first detect this and then set the `filetypes` field, I would be more than happy to make a PR. Otherwise I am sure it can be solved in a custom manner.

### Neovim version

--irrelevant

### Operating system and version

macOS 12.6.1

### Affected language servers

hls

### Steps to reproduce

--irrelevant

### Actual behavior

https://github.com/neovim/nvim-lspconfig/blob/7d0ce54a4cf6e844d87e49d1576c0fffb6d27a6e/lua/lspconfig/server_configurations/hls.lua#L6

Only supported on haskell and lhaskell filetypes.

### Expected behavior

also cabal filetype

### Minimal config

```Lua
--irrelevant
```

### LSP log

--irrelevant

**Comment by glepnir** [comment]
you can make a pr for this.
