### ISSUE TITLE
tsserver resolves `package.json` before `tsconfig.json`

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/nvim-lspconfig#237]
- `nvim --version`: 

```
NVIM v0.5.0-9816173fb
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200510-7337-1p8c8yy/build/config -I/tmp/neovim-20200510-7337-1p8c8yy/src -I/usr/local/include -I/tmp/neovim-20200510-7337-1p8c8yy/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200510-7337-1p8c8yy/build/src/nvim/auto -I/tmp/neovim-20200510-7337-1p8c8yy/build/include
Compiled by ahmed@pandoras-box

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-9816173/share/nvim"

Run :checkhealth for more info
```

- nvim-lsp version(commit hash): https://github.com/neovim/nvim-lsp/commit/205a9f0ca9e733d94f15f228b9e23b29a80af7cd
- `:checkhealth` result

```

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - WARNING: bibtex is not executable, so bibtex completions are disabled.
  - OK: General viewer should work properly!
  - ERROR: |g:vimtex_compiler_method| (`latexmk`) is not executable!

health#targets#check
========================================================================
  - OK: No conflicting mappings found

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.

health#gitmessenger#check
========================================================================
  - OK: +job is available to execute Git command
  - OK: Git command `git` is available: git version 2.26.2
  - OK: Floating window is available for popup window

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion source are valid

## snippet source
  - OK: You are using UltiSnips as your snippet source

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.7
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Disabled (g:loaded_ruby_provider=0).

## Node.js provider (optional)
  - INFO: Node.js: v14.2.0
  - INFO: Nvim node.js host: /usr/local/bin/neovim-node-host
  - OK: Latest "neovim" npm/yarn package is installed: 4.8.0

## Perl provider (optional)
  - INFO: Disabled (g:loaded_perl_provider=0).
```

- What language server(If the problem is related to a specific language server): `tsserver`
- Operating system/version: macoS 10.15.4
- Terminal name/version: kitty 0.17.4
- `$TERM`: `tmux-256color`

### How to reproduce the problem from neovim startup

Here is minimal setup to reproduce this

```
.
├── src
│  ├── module1
│  │  ├── index-wrong.ts <-- Inside this file `root_dir` is resolved to src/module1 because of package.json
│  │  └── package.json
│  ├── module2
│  │  └── index.ts <-- Inside this file root_dir is resolved to src because of tsconfig.json
│  └── tsconfig.json
└── package.json 
```

`tsconfig.json` should take precedence over `package.json` because if I'm in a TypeScript project, I need the information from `tsconfig.json` to resolve imports etc… but if there is no `tsconfig.json` it should resolve to `package.json` then `.git`

You can check the output when you open each file if you run

```
:lua print(vim.inspect(vim.lsp.buf_get_clients()))
```

The output in `module1/index-wrong.ts`

<img width="833" alt="Screenshot 2020-05-17 at 17 09 10" src="https://user-images.githubusercontent.com/63876/82152393-28ae9080-9861-11ea-96c1-3ec9cfcf2209.png">

The output in `module2/index.ts`

<img width="842" alt="Screenshot 2020-05-17 at 17 10 08" src="https://user-images.githubusercontent.com/63876/82152432-60b5d380-9861-11ea-8226-f4abb7cb6fba.png">

I thought the problem was the order in the code here https://github.com/neovim/nvim-lsp/blob/b77a24f6b6bdf32d621f37c733f399f33a7eab0d/lua/nvim_lsp/tsserver.lua#L20

But even if I change that to be

```lua
nvim_lsp.tsserver.setup{
  root_dir = nvim_lsp.util.root_pattern("tsconfig.json", "package.json", ".git");
}
```

It still resolves `package.json` before `tsconfig.json`, so I looked at https://github.com/neovim/nvim-lsp/blob/b77a24f6b6bdf32d621f37c733f399f33a7eab0d/lua/nvim_lsp/util.lua#L289-L322 but my Lua knowledge is very minimal. I tried to add a couple of `print` statements but couldn't figure out the issue. 

The only solution for me now is to remove `package.json` from the list. Which is not what I want to do.

### Actual behaviour

Setting root_dir to the closest `package.json`

### Expected behaviour

Setting root_dir to the closest `tsconfig.json`, then `package.json`

**Comment by h-michael** [comment]
@ahmedelgabri 
The current logic is to recursively look for the first file you open that is a marker for each root directory in the parent directory.
In this case, instead of searching for each maker file, it searches for each marker file in each directory.
That's why things like this issue are happening.

How do you think it would be better to change it?
How about searching from the first marker in order from the directory of the opened file to `vim.fn.getcwd()`, and if not, searching for the next marker?

**Comment by lithammer** [comment]
> How do you think it would be better to change it?
> How about searching from the first marker in order from the directory of the opened file to `vim.fn.getcwd()`, and if not, searching for the next marker?

This sounds like the reasonable behaviour. However I would like to change that from `vim.fn.getcwd()` to `vim.fn.expand("$HOME")` to make it work if I happen to be one or more directories deeper than the project root. And then use `vim.fn.getcwd()` as final fallback if nothing matches.

Basically, given `util.root_pattern("tsconfig.json", "package.json")` it would first search for `tsconfig.json` starting at the opened file all the way up to the home directory. If nothing is found, try the same with `package.json`. And if both fail, use `vim.fn.getcwd()`.

**Comment by lithammer** [comment]
On second thought, using `vim.fn.expand("$HOME")` will probably re-introduce issues like https://github.com/neovim/nvim-lsp/pull/176 again. So scratch that.

**Comment by ahmedelgabri** [comment]
> Basically, given `util.root_pattern("tsconfig.json", "package.json")` it would first search for `tsconfig.json` starting at the opened file all the way up to the home directory. If nothing is found, try the same with `package.json`. And if both fail, use `vim.fn.getcwd()`.

@h-michael I agree with @lithammer on this, and that's actually how I thought it was working. I thought that `util.root_patten` was checked in order.

**Comment by h-michael** [comment]
OK, if noone try this, I'll try this later.

**Comment by ahmedelgabri** [comment]
What I ended up doing is this, not sure if it's good enough to open a PR for it though.

I created my own `root_pattern()` function & used that instead of `require'nvim_lsp'.util.root_pattern()`

```lua
local function root_pattern(...)
  local patterns = vim.tbl_flatten {...}

  return function(startpath)
    for _, pattern in ipairs(patterns) do
      return lsp.util.search_ancestors(startpath, function(path)
        if lsp.util.path.exists(vim.fn.glob(lsp.util.path.join(path, pattern))) then
          return path
        end
      end)
    end
  end
end
```

**Comment by mjlbach** [comment]
@ahmedelgabri Can you test if #554 resolves everything the way you would expect?

**Comment by mjlbach** [comment]
I think we should add an ordered resolver similar to you suggested as a util, but maybe once we know how much code duplication it saves.

**Comment by ahmedelgabri** [comment]
Thanks @mjlbach a quick check shows that it fixes the problem 👍🏼
