### ISSUE TITLE
clangd does not recognize the address of the header file

### ISSUE THREAD

**Issue by yych0745** [neovim/nvim-lspconfig#2374]
### Language server

clangd

### Requested feature

In the log, my root directory is the upper-level folder, but the corresponding address cannot be recognized when opening the file.

#include "kernel/param.h"      file not found
#include "../kernel/param.h"   file can find

log output:

rootPath = "/Users/yych/repositry/os_lab",    rootUri = "file:///Users/yych/repositry/os_lab",    trace = "off",    workspaceFolders = { {        name = "/Users/yych/repositry/os_lab",        uri = "file:///Users/yych/repositry/os_lab"      } }  }}
[ERROR][2023-01-01 16:47:04] .../vim/lsp/rpc.lua:733	"rpc"	"efm-langserver"	"stderr"	"2023/01/01 16:47:04 efm-langserver: no configuration file\n2023/01/01 16:47:04 efm-langserver: reading on stdin, writing on stdout\n"

kernel dir path
/Users/yych/repositry/os_lab/kernel

**Comment by glepnir** [comment]
we use these file to get the root dir by default in clangd. you can use tools like bear to generate `compile_command.json` file in `kernel`

```lua
local root_files = {
  '.clangd',
  '.clang-tidy',
  '.clang-format',
  'compile_commands.json',
  'compile_flags.txt',
  'configure.ac', -- AutoTools
}
```
