### ISSUE TITLE
Use ESC to close floating windows like diagnostics

### ISSUE THREAD

**Issue by Martinits** [neovim/nvim-lspconfig#2380]
### Language server

all

### Requested feature

Can I close popup windows like diagnostics or hover info with ESC? How can I configure to do so?

**Comment by glepnir** [comment]
I don't think you need do this ? it will auto close when you trigger some autocommand events like `CursorMoved`.

**Comment by Martinits** [comment]
Maybe I'm used to "close" a popup just like other floating windows opened by plugins. But I'll accept it. Thanks

**Comment by nmsobri** [comment]
it would be nice to have the option to bind to a specific keymap to close the floating pop up
