### ISSUE TITLE
Server per root_directory

### ISSUE THREAD

**Issue by mireq** [neovim/nvim-lspconfig#2388]
### Requested feature

I would like to use nvim-lspconfig on project with multiple subprojects, each with own `root_dir`. Currently it's not possible because `get_client_from_cache` always returns first started server. Removing fallback in function `get_client_from_cache` allows to start separate instance for `root_directory`.

https://github.com/neovim/nvim-lspconfig/blob/7b98aadc6e85db4fc3af6c1ec22c4774d965506e/lua/lspconfig/util.lua#L267-L274

**Comment by glepnir** [comment]
I don't think start multiple server is correct.  server should support workspace.  
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_workspaceFolders

**Comment by mireq** [comment]
Sorry, my mistake.  Closing this issue and opening new issue on python-lsp-server. https://github.com/python-lsp/python-lsp-server/issues/335
