### ISSUE TITLE
LSP: ESLint finds .eslintrc.js in current directory but does not traverse higher to root directory

### ISSUE THREAD

**Issue by mshirlaw-alteryx** [neovim/nvim-lspconfig#2400]
### Description

I have a project with a structure something like the following:

```
project
|__ src
       |__ models
           |__ Model.ts
           |__ .eslintrc.js
        |__ components
           |__ Component.tsx
.eslintrc.js
.git
```
For all of the exports that I have defined in `Model.ts` I receive a warning `Exported declaration XYZ is not used within other modules` even though these are imported in `src/components/Component.tsx`. 

When I do `:LspInfo` in this `Model.ts`  file I can see that the root directory is being set as `/Users/<username>/Documents/project/src/models` - i.e. it is finding the first `eslintrc.js`

```
 Client: eslint (id: 5, pid: 61525, bufnr: [59])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx, vue, svelte, astro
 	autostart:       true
 	root directory:  /Users/<username>/Documents/project/src/models
 	cmd:             vscode-eslint-language-server --stdio
 
 Client: tsserver (id: 3, pid: 61523, bufnr: [59])
 	filetypes:       javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
 	autostart:       true
 	root directory:  /Users/<username>/Documents/project
 	cmd:             typescript-language-server --stdio
 
 Configured servers list: html, jsonls, tsserver, bashls, cssls, eslint
```

In my lsp config I am setting `root_dir` for all language servers using `util.root_pattern('.git')` which seems to work for `tsserver` (see above) but not for `eslint`. 

```
for _, lsp in pairs(servers) do
  require('lspconfig')[lsp].setup {
    root_dir = util.root_pattern('.git'),
    on_attach = on_attach,
    capabilities = capabilities,
    flags = lsp_flags, 
  }
end
```

Is there something else I need to configure to allow eslint to traverse up to the top level directory? This problem does NOT exist in vscode. The same configuration works correctly.

### Neovim version

NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local

### Operating system and version

macOS 12.6

### Affected language servers

eslint

### Steps to reproduce

1. Create project with nvim-lspconfig
2. Install eslint 
3. Use directory structure above

### Actual behavior

ESLint does not find correct `.eslintrc.js`

### Expected behavior

ESLint does find correct `.eslintrc.js`

### Minimal config

```Lua
[START][2023-01-17 13:02:07] LSP logging initiated
[START][2023-01-17 13:02:27] LSP logging initiated
[WARN][2023-01-17 13:02:46] ...lsp/handlers.lua:110	"The language server eslint triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-01-17 13:02:48] ...lsp/handlers.lua:110	"The language server eslint triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

### LSP log

[START][2023-01-17 13:02:07] LSP logging initiated [START][2023-01-17 13:02:27] LSP logging initiated [WARN][2023-01-17 13:02:46] ...lsp/handlers.lua:110	"The language server eslint triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless" [WARN][2023-01-17 13:02:48] ...lsp/handlers.lua:110	"The language server eslint triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"

**Comment by mshirlaw-alteryx** [comment]
> same as #1908 both need the parent as the root i think

I don't think this issue would be solved by just making the parent (one directory higher) as root. The problem would still exist for deeper directories.

I suspect the root should actually be the directory where `.git` lives which is specified in the configuration file but this is not respected. 

I think the solution needs to recursively search up the directory tree until it reaches the pattern specified as the root dir or the `.eslintrc` which specifies `"root": true` rather than just stopping when it finds the first `.eslintrc`

If I'm not mistaken (I am not an eslint expert though) this is how eslint is intended to operate according to their docs.

**Comment by mshirlaw-alteryx** [comment]
Hardcoding a path to my project directory fixed it but I don't know lua so I am not sure how to do this in a generic way recursively back up the tree @glepnir :

<img width="887" alt="Screenshot 2023-02-01 at 10 46 03 am" src="https://user-images.githubusercontent.com/107894907/215909460-f9049b79-1962-4dcd-9eaf-70d49d594693.png">

**Comment by glepnir** [comment]
actually problem is the current find dir function not smart .some util function need improve. thanks for report

**Comment by glepnir** [comment]
looks like it fixed now.  in my test

```
test
       .git
       .estlintrc.js
       project
          .estlintrc.js
           test.ts
```

lspinfo show me the root is `test`  not `project`
