### ISSUE TITLE
[gopls] No underline for some kinds of diagnostics

### ISSUE THREAD

**Issue by rockyzhang24** [neovim/nvim-lspconfig#2403]
### Description

The underline for some kinks of diagnostics does not show up. Others such as sign and virtual_text work well.
<img width="467" alt="image" src="https://user-images.githubusercontent.com/11582667/213037122-a2925c0b-ec55-4976-98e6-862ff2b7884c.png">

### Neovim version

NVIM v0.9.0-dev-667+gdd200db98
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 13.1

### Affected language servers

gopls

### Steps to reproduce

1. Make a directory for testing `mkdir test` and then `cd` into it
2. Run `nvim test.go -u minimal_init.lua`
3. Type `packa abc`
4. Then the sign and virtual text show up saying the error message "syntax: expected 'package', ...", but no underline there.

### Actual behavior

No underline for diagnostics for some kinds of errors.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
end

-- Add the server that troubles you here
local name = 'gopls'
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
  on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

https://gist.github.com/rockyzhang24/971fd1635959fa27f66527c4bf968ab9

**Comment by glepnir** [comment]
`:h vim.diagnostic.config`

**Comment by rockyzhang24** [comment]
@glepnir `config.underline` is true by default, so the underline should display. This is more likely a bug. Please reopen it. Thanks.

**Comment by glepnir** [comment]
not bug of neovim or this plugin. `hi DiagnosticError`

**Comment by rockyzhang24** [comment]
I tested using the minimal config and hl-DiagnosticError has been set to red. Could you please try to reproduce it?

**Comment by rockyzhang24** [comment]
hl-DiagnosticUnderlineError and all the related diagnostic hlighgroups are set by using the mininal config. Still no underline. The issue just happens for gopls.

**Comment by glepnir** [comment]
try reproduce it later. thanks for report.

**Comment by glepnir** [comment]
the reason is gopls return 0 for column. so there is no underline 

```
{                                                                                             
  bufnr = 1,                                                                                  
  col = 0,                                                                                    
  end_col = 0,                                                                                
  end_lnum = 0,                                                                               
  lnum = 0,                                                                                   
  message = "expected ';', found 'EOF'",                                                      
  namespace = 18,                                                                             
  severity = 1,                                                                               
  source = "syntax",                                                                          
  user_data = {                                                                               
    lsp = {}                                                                                  
  }                                                                                           
}            
```

**Comment by glepnir** [comment]
so there is nothing on neovim . thanks. report it to gopls if you think this is important for you .

**Comment by rockyzhang24** [comment]
Thank you for confirming it. So is it a bug of gopls or a kind of deliberate design? I am not family with the LSP specification. Is it possible for neovim or this plugin to fix it by adjusting `col` returned by the server?

**Comment by glepnir** [comment]
it should return a range that include lnum and col pos. on plugin level we just get result from server and set highlight through this range.  `0` just mean the start col . we don't know the actual wrong pos column. 

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range

>  I tested on VSCode and it showed the underline normally.

gopls vscode extension write by google . maybe they think 0 is mean whole line ? I don't know why design like this. it's not lsp spec.

**Comment by rockyzhang24** [comment]
Okay I got it. Thank you so much for guiding me. I will close this issue.
