### ISSUE TITLE
Issue with cmake-language-server lsp when working with cmake files

### ISSUE THREAD

**Issue by josedev9** [neovim/nvim-lspconfig#2406]
### Description

I recently finished configuring my neovim environment, mainly for working with python/c/cpp projects, I even managed to configure a dap setup which "kind of" works I guess. My problem is when it comes to syntax highlighting/general usage of the lsp client for cmake, nothing seems to work even though I configured it exactly the same way as other lsps I'm currently using.

I created a project with multiple folders including a .git and build folders, which should be triggered as the root dir so the lsp should be attached to the CMakelists.txt file or Makefile file, or at least that's what I understood in the https://github.com/regen100/cmake-language-server description.

My lsp configuration is the same as this one: https://github.com/LunarVim/nvim-basic-ide/blob/master/lua/user/lsp/mason.lua adding to the servers the cmake one. I can provide some more screenshots showing other lsp clients working fine out of the box with their buffers but the cmake being active and not attaching to any cmake file I create.

Do you guys have any idea why am I having this issue? Needless to say I'm a total beginner when it comes to vim/neovim stuff, and I recently managed to put together kind of a semi-decent configuration copying plenty of the options Chris and other delevopers from lunarvim shared in their repos.

Thank you for taking time to read my question, this might be a duplicate but I've been aimlessly searching trying to find someone with a similar issue than mine with no results.

I tried creating multiple cmake and make style files. Plus adding more folders so that the root directory would be detected and the lsp client could be attached to the buffer successfully.

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

 a59ba78f164f586d47a2f315dc3d021a630768d0

### Operating system and version

Ubuntu 22.04.1 LTS 

### Affected language servers

cmake

### Steps to reproduce

1. Create  sample project directory structure including a .git, src, include, libs, build and bin folders.
2. Add a Makefile in the project's root and a CMakelists.txt
3. Open either one of these files in a buffer with nvim

### Actual behavior

The cmake client is not attached to any of the buffers even though the on attach premise condition has theoretically been met
![image](https://user-images.githubusercontent.com/80027196/213144370-ec0f19b5-d974-499d-a75d-3b9dcd211d48.png)

### Expected behavior

The client should be attached to the buffer providing auto-completion and other features from lsps

### Minimal config

```Lua
My configuration is mostly the same as this github repo provided by the Chris colleagues from Lunarvim, with the exception of the cmake server being added into the servers list, plus installing it using the Mason plugin.
https://github.com/LunarVim/nvim-basic-ide/blob/master/lua/user/lsp/mason.lua
```

### LSP log

https://gist.github.com/josedev9/57f0eb2bc35ce681035cb529f2de62ab#file-lsp-log

**Comment by glepnir** [comment]
your filetype is `txt` . changed it to `cmake`

**Comment by josedev9** [comment]
I'm so stupid, I thought that by default the standard was to use a CMakelists ending in a .txt format instead of cmake. Didn't think of changing that, my bad, thanks for the answer. =)

**Comment by starball5** [comment]
The filename CmakeLists.txt has a special meaning in CMake.

You **have** to have at least one such file in any CMake project (the root CMake config file for the project). When you run CMake to configure a buildsystem, you pass it the path to a _directory containing_ a CMakeLists.txt file- not the path to a CMake file. See [the CMake docs on invoking the configuration process](https://cmake.org/cmake/help/latest/manual/cmake.1.html#generate-a-project-buildsystem).

And when you call [`add_subdirectory()`](https://cmake.org/cmake/help/latest/command/add_subdirectory.html), the subdirectory is expected to contain a file named "CMakeLists.txt". It's not a valid workaround for the root config file or config files added via `add_subdirectory` to change the file extension from `.txt` to `.cmake`.

This issue should really be re-opened and "CMakeLists.txt" added as a special case to be supported.

**Comment by TrustinN** [comment]
Ran into this issue and if anyone needs this I put 
```
local Txt = vim.api.nvim_create_augroup('Txt', { clear = true })
vim.api.nvim_create_autocmd({"BufEnter"}, {
    group = Txt,
    pattern = {".txt"},
    callback = function()
        if vim.fn.expand("%:p:t") == "CMakeLists.txt" then
            vim.opt.filetype = 'cmake'
        end
    end

})
```
in my after/plugin/autocommands.lua and it worked.

**Comment by thomaskvnze** [comment]
> The filename CmakeLists.txt has a special meaning in CMake.
> 
> You **have** to have at least one such file in any CMake project (the root CMake config file for the project). When you run CMake to configure a buildsystem, you pass it the path to a _directory containing_ a CMakeLists.txt file- not the path to a CMake file. See [the CMake docs on invoking the configuration process](https://cmake.org/cmake/help/latest/manual/cmake.1.html#generate-a-project-buildsystem).
> 
> And when you call [`add_subdirectory()`](https://cmake.org/cmake/help/latest/command/add_subdirectory.html), the subdirectory is expected to contain a file named "CMakeLists.txt".
> 
> It's not a valid workaround for the root config file or config files added via `add_subdirectory` to change the file extension from `.txt` to `.cmake`.
> 
> This issue should really be re-opened and "CMakeLists.txt" added as a special case to be supported.

This is true. These files are supposed to have .txt, not .cmake. Many libraries are written this way and are not supported by default with the current config.

**Comment by TrustinN** [comment]
I think maybe this works
```
local Cmake = vim.api.nvim_create_augroup('Cmake', { clear = true })
vim.api.nvim_create_autocmd({"BufEnter"}, {
    group = Cmake,
    pattern = {"*.txt"},
    callback = function()
        if vim.fn.expand("%:p:t") == "CMakeLists.txt" then
            vim.opt.filetype = 'cmake'
        end
    end
})
```
but havent used cmake in a while so idk

**Comment by AlphaNumericPencil** [comment]
> your filetype is `txt` . changed it to `cmake`

Neovim source code itself has nine CMakeLists.txt files. Would you please consider allowing a PR for CMakeLists.txt files to be picked up by this LSP? This is inconveniencing me at my job and it would be kind of embarrassing if I changed 30 CMake files because my IDE is the only one that can't handle the files

**Comment by RhysFonville** [comment]
Bumping this issue. I do believe as well CMakeLists.txt should be included.
