### ISSUE TITLE
Show current LSP config in :LspInfo floating window

### ISSUE THREAD

**Issue by ellisonleao** [neovim/nvim-lspconfig#2412]
### Requested feature

Hey people, i was wondering if it would be nice to show the contents of the loaded lsp server configs in `:LspInfo` output. I know we already have the docs for the default config, but sometimes I need to use the output from `vim.api.get_active_clients()`  to check what's actually my current config. 

I was wondering if we could add something like a hidden accordion with the full config where you can just toggle it if needed

![screenshot-github com-2023 01 20-16_25_09](https://user-images.githubusercontent.com/178641/213790262-6696106e-0848-402e-9e35-612fe1bfd74e.png)

**Comment by glepnir** [comment]
currently the `checkhealth` command show some lsp relate like server id root .   and catch some custom pattern will add some codes.  I don't think @justinmk  will allow these codes.
