### ISSUE TITLE
``Client is required to execute lens`  after restarting LS and trying to run code lens

### ISSUE THREAD

**Issue by carbolymer** [neovim/nvim-lspconfig#2425]
### Description

I'm not sure if this bug is related more to how codelens are implemented in neovim lsp or how `nvim-lspconfig` performs a restart of LS so I'm posting it here first. 

### Neovim version

NVIM v0.9.0-dev-701+g34b973b1d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g  -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -fstack-protector-strong -DNVIM_UNIBI_HAS_VAR_FROM -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/.deps/usr/include/luajit-2.1 -I/usr/include -I/home/runner/work/neovim/neovim/.deps/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src
Compiled by runner@fv-az435-523

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

1e988250a0f52a68ddb72905d623405d634e9c5d

### Operating system and version

Archlinux latest

### Affected language servers

all

### Steps to reproduce

1. Open a file, let language server start. One can use sample code from the original codelens neovim support pr: https://github.com/neovim/neovim/pull/13165
2. Restart language server via `:LspRestart`, wait till LS starts
3. Try to run code lens `:vim.lsp.codelens.run()`

### Actual behavior

Neovim returns the following error and the codelens isn't executed:
```
E5108: Error executing lua: /usr/share/nvim/runtime/lua/vim/lsp/codelens.lua:35: Client is required to execute lens, client_id=1                                                                                                                                         
stack traceback:
        [C]: in function 'assert'
        /usr/share/nvim/runtime/lua/vim/lsp/codelens.lua:35: in function 'execute_lens'
        /usr/share/nvim/runtime/lua/vim/lsp/codelens.lua:96: in function </usr/share/nvim/runtime/lua/vim
/lsp/codelens.lua:80>
```

### Expected behavior

The code lens are executed

### Minimal config

```Lua
local lsp = require('lspconfig')

local on_attach = function(client, bufnr)
  -- auto refresh code lens
  vim.api.nvim_create_autocmd({'CursorHold','CursorHoldI','InsertLeave'}, {
    pattern = '*',
    callback = vim.lsp.codelens.refresh
  })

  local bufopts = { noremap=true, silent=true, buffer=bufnr }
  vim.keymap.set('n', '<leader>la', vim.lsp.codelens.run, bufopts)
end

lsp.hls.setup{
  filetypes = { 'haskell', 'lhaskell', 'cabal' },
  on_attach = on_attach
}
```

### LSP log

none

**Comment by glepnir** [comment]
can you try `vim.lsp.codelens.clear` after you restart ?

**Comment by carbolymer** [comment]
@glepnir I've tried that:
```lua
lsp.hls.setup {
  filetypes = { 'haskell', 'lhaskell', 'cabal', 'cabalproject' },
  on_attach = on_attach,
  on_exit = vim.lsp.codelens.clear
}
```
and I get the same error.

**Comment by glepnir** [comment]
nope . `vim.lsp.codelens.clear`  need `clientid ,bufnr`,  `on_exit  ` function is `code, signal, clientid`.

```lua

local on_attach = function(client, bufnr)
  -- auto refresh code lens
  vim.api.nvim_create_autocmd({'CursorHold','CursorHoldI','InsertLeave'}, {
    pattern = '*',
    callback = vim.lsp.codelens.refresh
  })

  vim.api.nvim_create_autocmd('LspDetach', {
        callback = function(opt)
               vim.lsp.codelens.clear(opt.data.client_id, opt.buf)
        end
   })
end
``

**Comment by carbolymer** [comment]
@glepnir The error is gone, but code lens do not reappear after `:lua vim.lsp.codelens.refresh()`

**Comment by glepnir** [comment]
you need create  `CursorMoved` in `LspAttach`  callback

**Comment by carbolymer** [comment]
@glepnir do you mean something like:
```
vim.api.nvim_create_autocmd('LspAttach', {
    callback = function(opt)
      vim.api.nvim_create_autocmd({ 'CursorMoved' }, {
        pattern = '*',
        callback = vim.lsp.codelens.refresh
      })
      vim.lsp.codelens.refresh()
    end
  })
```
?
It still doesn't work, because `vim.lsp.codelens.refresh()` doesn't do anything after `LspRestart`.
