### ISSUE TITLE
Incorrect requests being passed to `rust_analyzer`

### ISSUE THREAD

**Issue by Aaronik** [neovim/nvim-lspconfig#2431]
### Description

In my hunting down of an nvim segfault that's been disrupting my work flow, I came across the fact that `nvim-lspconfig` seems to be passing incorrect requests to at least the `rust_analyzer` LSP server.

I opened a ticket with them and found this to be happening from [this comment](https://github.com/rust-lang/rust-analyzer/issues/14050#issuecomment-1408160410), which says that `rust_analyzer` does not support the `workspace/executeCommand` request, and declares so, but is still having it passed in.

I have a third ticket in neovim itself (https://github.com/neovim/neovim/issues/22112) about the segfaulting, which is neither the fault of `rust_analyzer` or of `lspconfig`. However I am hopeful that maybe if `lspconfig` doesn't send incorrect requests to `rust_analyzer`, *maybe* my segfault story will come to a close! Which I would just super love a lot.

### Neovim version

NVIM v0.9.0-dev-613+gef18c9f9b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/nvim/parts/nvim/build/build/cmake.config -I/build/nvim/parts/nvim/build/src -I/build/nvim/parts/nvim/build/.deps/usr/include -I/usr/include -I/build/nvim/parts/nvim/build/build/src/nvim/auto -I/build/nvim/parts/nvim/build/build/include
Compiled by root@lcy02-amd64-005

Features: +acl +iconv +tui

### Nvim-lspconfig version

902d6aa

### Operating system and version

Linux dellbert 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Affected language servers

rust_analyzer

### Steps to reproduce

With the config

```lua
-- https://github.com/folke/lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

require("lazy").setup({
  {
    'williamboman/mason.nvim',
    config = {}
  },

  {
    'williamboman/mason-lspconfig.nvim',
    config = {
      ensure_installed = { 'rust_analyzer' }
    },
    init = function()
      require('mason-lspconfig').setup_handlers {
        ["rust_analyzer"] = function()
          require("lspconfig")["rust_analyzer"].setup({}) -- without this single line, nvim won't segfault
        end,

      }
    end
  },

  {
    'neovim/nvim-lspconfig',
  },
})
```
Now just open some file, and about 30% of the time, nvim will segfault. I suspect there's some race condition somewhere, but that every time, `rust_analyzer` is getting this incorrect request. I could be wrong here though.

I have this:

Following a thread in the checkhealth command, looking in `~/.local/state/nvim/lsp.log`, I'm seeing this error, among other errors from other LSP servers:

`[ERROR][2022-12-13 19:07:44] .../vim/lsp/rpc.lua:733  "rpc" "rust-analyzer" "stderr"  '[ERROR rust_analyzer::dispatch] unknown request: Request { id: RequestId(I32(344)), method: "workspace/              
     executeCommand", params: Object({"title": String("triggerParameterHints"), "command": String("editor.action.triggerParameterHints")}) }\n'` -- I don't know if this is related to the segfaults.

### Actual behavior

The language server is sent requests that do not request the language server's declared capabilities

### Expected behavior

The requests sent should respect the language server's declared capabilities

### Minimal config

```Lua
listed above
```

### LSP log

https://gist.github.com/Aaronik/0595c4e8f9cd41d8d1fee38b285f3415

**Comment by glepnir** [comment]
can't reproduce . and I don't think lsp can make your neovim crash. your issue is duplicate.  you already opened in neovim

**Comment by Aaronik** [comment]
You can't reproduce that `rust_analyzer` is receiving the `workspace/executeCommand` request?

I left an issue in `neovim` about neovim segfaulting - the issue here is different, it's based on my conversation with the `rust_analyzer` folk, who say that neovim is sending an incorrect request.

**Comment by glepnir** [comment]
even send the wrong request it doesn't make your neovim crash . the segment mean there has some wrong memory alloc or something else. maybe caused by some api? idk your env. for my daily use in rust works fine

**Comment by glepnir** [comment]
and please try the min config from nvim-lspconfig no any third party plugin. lspconfig just start sever

**Comment by Aaronik** [comment]
Yes Ok I'm working on the crash situation over in the neovim repo proper. But I don't think `nvim-lspconfig` should be sending requests to lsp servers that aren't declared as supported, correct?

**Comment by glepnir** [comment]
lspconfig doesn't send request except the workspace/didchange notify. but it will check server support it or not. rust-anaylzer not supprt so this notify does not.send. other method send when you called built in lsp function. lspconfig only star server and attach buffer to it

**Comment by Aaronik** [comment]
So what entity is sending the `workspace/executeCommand` request to the rust_analyzer?

**Comment by glepnir** [comment]
I will check it later .outside and reply on phone

**Comment by glepnir** [comment]
as far as I know this method for code action

**Comment by Aaronik** [comment]
It seems to be being called immediately when the LSP server is setup.

The line, in my config, `require("lspconfig")["rust_analyzer"].setup({})`, is what makes my nvim crash, which is _I believe_ tied to those error messages, although I'm not totally sure about that. Either way -- I don't think it's supposed to be called on LSP servers that don't support it.

So you say it's for code action -- my question is, **what entity is making that call**??

**Comment by glepnir** [comment]
> require("lspconfig")["rust_analyzer"].setup({})

I don't think this line can make your neovim crash . and it works fine for me .even i used a min config for test.

**Comment by Aaronik** [comment]
It is happening to me - there must be some kind of state different in our setups. It is making mine crash, there's no question about it.

But seriously - is it this the code in `nvim-lspconfig` or somewhere else that's making the `workspace/executeCommand` request?

**Comment by glepnir** [comment]
as the comment first. did you try the min config provide by lspconfig ?

**Comment by glepnir** [comment]
this is my rust config . do any operate on rust file 30s no crash.

```lua
lspconfig.rust_analyzer.setup({
  on_attach = _attach,
  capabilities = capabilities,
  settings = {
    ['rust-analyzer'] = {
      imports = {
        granularity = {
          group = 'module',
        },
        prefix = 'self',
      },
      cargo = {
        buildScripts = {
          enable = true,
        },
      },
      procMacro = {
        enable = true,
      },
    },
  },
})

```


![jump](https://user-images.githubusercontent.com/41671631/216751247-8a6d06a1-59aa-4963-8bf0-5f0532a0ef70.gif)

**Comment by Aaronik** [comment]
No it's not within 30s it crashes, it's that 30% of the time it crashes **immediately upon opening the editor**.

I'm working on it with your minimal config right now. I assume this is what you're talking about https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua. 

You're right - it's not crashing doing this. Out of curiosity - you said you couldn't repro with the config I left -- did you actually try it with that config? Is it something in there that's causing the issue?

**Comment by glepnir** [comment]
> No it's not within 30s it crashes, it's that 30% of the time it crashes immediately upon opening the editor.
that's too bad. but for my daily usage on rust project . my neovim works fine . 

`can't reproduce` that mean i can't reproduce with the min config and my config . sorry I didn't test the config you provide 

There are some issues that may or may not be caused by 3rd party plugins. Perhaps some api caused an internal error. This will take some time to investigate. But for minimal configuration some 3rd party plugins are provided for which I don't work. Because I don't want to spend time on issues that end up being caused by these plugins. So if a minimal configuration can reproduce the problem. I will be responsible to the end. Feel sorry. My time is not so rich.

about the wrong method. even there has the wrong lsp request it run in runtime. not neovim core code . so  It doesn't cause neovim segmentation fault. This error is usually caused by some memory allocation problem.  may call internal api or something else . for lsp request it not .

`executeCommand` will send when you trigger codeaction .

https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_executeCommand

I can understand the inconvenience of a tool crashing. You are not in a good mood. But you should investigate your own configuration first

**Comment by Aaronik** [comment]
Believe me, I have been exploring this on my own for over a month. I'm finally reaching out for help. 

Thank you for your help this far. Finding that your minimal config indeed does not trigger the issue will help me hunt further on my own.

**Comment by glepnir** [comment]
> Believe me, I have been exploring this on my own for over a month.

that's really fucking bad ..  you can just use a config which only include `theme complete-plugin nvim-lspconfig ` in your rust develop for test.  maybe can works fine.

**Comment by mfussenegger** [comment]
The `editor.action.triggerParameterHints` command could be part of a completion candidate. (https://github.com/rust-lang/rust-analyzer/blob/1575d55fc81c328eb7ae728d9e3aaba9d13d4a16/editors/code/src/client.ts)

In `vscode` `editor.action.triggerParameterHints` it is a client side command and shows the function parameters to the user.

If that causes an issue with rust-analyzer it's probably caused by a completion plugin you're using.

Not sure who's fault it is. A language server cannot assume a command exist on the client. On the other hand, the client should probably check the `ExecuteCommandOptions` in the server capabilities. In this case the completion plugin would need to do it. 


As a workaround you could define a command handler for it. E.g. with something like this:

```lua
vim.lsp.commands['editor.action.triggerParameterHints'] = function()
  local ok, result = pcall(vim.lsp.buf.signature_help)
  if ok then
    return vim.NIL
  else
    return vim.lsp.rpc_response_error(vim.lsp.protocol.ErrorCodes.InternalError, result)
  end
end
```
