### ISSUE TITLE
Ability to disable lsp for some buffers

### ISSUE THREAD

**Issue by randomizedthinking** [neovim/nvim-lspconfig#2437]
### Requested feature

When working with repl, I have some utility buffers of the same type as the main files and the lsp server would generate many errors on them. I wish lsp can be turned off for such buffers.

The implementation could be simple. For instance, if a buffer is set with a local variable `b:lsp_disable`, then lsp would skip them. It would be nice if it is systematically implemented in nvim-lspconfig.

**Comment by glepnir** [comment]
I think you can  simply use the vim diagnostic.disable with buffer number to disable all diagnostic.

**Comment by respectTheCode** [comment]
The `vim.diagnostic.disable(0)` call is deprecated now and should be updated like this

```lua
local lsp_grp = vim.api.nvim_create_augroup("lsp_disable", { clear = true })
vim.api.nvim_create_autocmd({ "BufEnter", "BufNewFile" }, {
  group = lsp_grp,
  pattern = { ".env", ".env.*" },
  callback = function()
    vim.diagnostic.disable(vim.api.nvim_get_current_buf())
  end,
})
```
