### ISSUE TITLE
Hover does not work for rust-analyzer

### ISSUE THREAD

**Issue by LollipopFt** [neovim/nvim-lspconfig#2443]
### Description

when hovering over imported functions, structs, types, etc. information is shown:
![image](https://user-images.githubusercontent.com/62802897/217418980-152243d0-3c19-4f46-842c-66f5180dbe6c.png)
![image](https://user-images.githubusercontent.com/62802897/217419010-6aed88b7-50ff-4db0-a288-382d1ead975e.png)
however, when hovering over variables or even constants, the server says no information available:
![image](https://user-images.githubusercontent.com/62802897/217419202-1a6d2914-8e4f-45ac-85fa-47e3e941e805.png)
in other editors, this shows `i32`
![image](https://user-images.githubusercontent.com/62802897/217419263-9a1df8c5-7bc3-458d-ba1c-bc0d36738ef0.png)
should show `current: i32`

### Neovim version

NVIM v0.9.0-dev-874+g5c4b503d3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

d3c82d2f9a6fd91ec1ffee645664d2cc57e706d9

### Operating system and version

Windows 10

### Affected language servers

rust-analyzer

### Steps to reproduce

nil

### Actual behavior

above

### Expected behavior

hover should work on almost all the code there, not only certain ones

### Minimal config

```Lua
see below
```

### LSP log

https://gist.github.com/LollipopFt/e0ddc700b3385873d554f75ddcb89de5

**Comment by glepnir** [comment]
can't reproduce with min config rust config is

```lua

lspconfig.rust_analyzer.setup({
    settings = {
        ["rust-analyzer"] = {
            imports = {
                granularity = {
                    group = "module",
                },
                prefix = "self",
            },
            cargo = {
                buildScripts = {
                    enable = true,
                },
            },
            procMacro = {
                enable = true,
            },
        },
    },
})

```
![image](https://user-images.githubusercontent.com/41671631/217457476-0280ae38-8a4f-4ddc-884b-4d07caf0433b.png)

**Comment by LollipopFt** [comment]
i have done some testing, see discussion here -> https://github.com/rust-lang/rust-analyzer/issues/14105. it is now working on lapce and other editors after clearing temp folder for some reason, but still failing on neovim. from the above, it seems you tested on a much simpler file structure, could you test it again? thank you! (neovim rust config has nothing to do with it, i have tried with default rust config)
