### ISSUE TITLE
`:LspInfo` client's root_directory seems to be always "Running in single file mode" even with `single_file_support = false`; Undefined global 'type'

### ISSUE THREAD

**Issue by caldwell-63** [neovim/nvim-lspconfig#2446]
### Description

I tested that with `tsserver` and sumneko lua, so it is probably not Language Server issue, I suspect that it has something to do with Windows.

My configs are minimal taken from the readme, but with `single_file_support` set to `false`...

I did check if root_dir is resolved correctly, and it is:

```lua
  root_dir = function(fname)
    local root = util.root_pattern('.git')(fname);

    print(root, type(root)); --> C:/Users/.../.../dir   string

    return root;
  end,
```

Regardless, most features work properly, as if the actual root_dir were handled right under the hood.

Also, for some reason out of all globals, the `type` standard Lua function is not getting recognized:

![image](https://user-images.githubusercontent.com/124377735/217840503-473fa7af-c2a0-412f-b00d-1a5d48349d06.png)

https://github.com/neovim/nvim-lspconfig/issues/2366 - might be related

### Neovim version

NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az28-353

### Nvim-lspconfig version

aeb76066212b09c7c01a3abb42fe82f0130ef402 (latest)

### Operating system and version

Windows 10

### Affected language servers

tsserver, sumneko_lua, potentially all of them

### Steps to reproduce

:LspInfo

### Actual behavior

![image](https://user-images.githubusercontent.com/124377735/217842119-d2747afa-b17b-44f0-8d6e-b04b3ba6814e.png)

### Expected behavior

It should be a path, especially with single_file_support option set to false

### Minimal config

```Lua
lspc.sumneko_lua.setup {
  on_attach = on_attach, -- just basic keymaps
  single_file_support = false,
  cmd = { 'lua-language-server' },
  filetypes = { 'lua' },
  log_level = 2,
  root_dir = function(fname)
    local root = util.root_pattern('.git')(fname);

    print(root, type(root));

    return root;
  end,
  settings = {
    Lua = {
      runtime = { version = 'LuaJIT' },
      diagnostics = { globals = { 'vim' } },
      workspace = {
        library = vim.api.nvim_get_runtime_file('', true),
      },
    },
  },
};
```

### LSP log

https://gist.github.com/caldwell-63/666080bc3d8a86279e6e23f04afb70a3

**Comment by glepnir** [comment]
about diagnostic. you need workspace/diagnostic/refresh handler. lspinfo problem.I will fix it tomorrow

**Comment by glepnir** [comment]
you are in windows?   #2343  maybe can fix lspinfo bug.
