### ISSUE TITLE
`vim.lsp.buf.format()` will cause a null modification in Lua

### ISSUE THREAD

**Issue by leonasdev** [neovim/nvim-lspconfig#2454]
### Description

If your buffer is already formatted, then when you execute `vim.lsp.buf.format()` again, the file will become a modified file even it's changed nothing.

Moreover, if you press `u` to undo this buffer, you will find that it does nothing.

So if you do `vim.lsp.buf.format()` multiple times, you will need to undo it multiple times to undo your desired modification.

My thought:
Maybe this happened because `lua-language-server` not checking if the formatting file is already formatted or if this is something that lspconfig should check.

### Neovim version

NVIM v0.9.0-dev-944+g89722ddfa
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

1712672

### Operating system and version

Ubuntu 22.04

### Affected language servers

lua_ls

### Steps to reproduce

1. `nvim init.lua`
2. If the buffer is not formatted, then execute `vim.lsp.buf.format()` and `:w`
3. execute `vim.lsp.buf.format()` again
4. notice the buffer has been changed to the modified buffer
5. press `u` to undo
6. notice that the undo not change anything

### Actual behavior

`vim.lsp.buf.format()` will cause a null modification in Lua even the buffer is formatted. 

### Expected behavior

If the buffer is formatted, `vim.lsp.buf.format()` should not cause a modification.

Just like `jose-elias-alvarez/null-ls.nvim`'s behavior.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'

-- Add the server that troubles you here
local name = 'lua_ls'
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

No output

**Comment by glepnir** [comment]
create on neovim repo.
