### ISSUE TITLE
Terraformls sends invalid uri on `textDocument/hover`

### ISSUE THREAD

**Issue by rwblokzijl** [neovim/nvim-lspconfig#2461]
### Description

As discussed in https://github.com/hashicorp/terraform-ls/issues/1177. Neovim is sending an incorrect URI to terraform ls, causing it to panic and crash.

Is there a call log somewhere that allows me to see what plugin made this call?

### Neovim version

NVIM v0.8.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

### Operating system and version

Arch Linux

### Affected language servers

terraform-ls

### Steps to reproduce

Will post if logs are not sufficient.

### Actual behavior

Crash

### Expected behavior

No crash

### Minimal config

Will post if logs are not sufficient.

### LSP log

https://gist.github.com/rwblokzijl/10efdd8dc476fa86c127ea10a7d650d4

**Comment by sigmaSd** [comment]
I can't reproduce the issue, nvim correctly sends the uri as uri , I guess you will need to try to debug

There is no plugin, hover is builtin to nvim, to reproduce just run `:lua vim.lsp.buf.hover()`

To debug I guess you will need to follow the code in nvim lsp file and put some prints there

**Comment by glepnir** [comment]
can't reproduce. try min config.

**Comment by rwblokzijl** [comment]
Reinstalling all plugins, mason LSPs and neovim itself fixed it.
