### ISSUE TITLE
Warn about using undeclared filetypes

### ISSUE THREAD

**Issue by SomeoneSerge** [neovim/nvim-lspconfig#2462]
### Description

Currently[^1], calling `require'lspconfig'.KNOWN_SERVER.setup{ ..., filetypes = { 'UNKNOWN_EXT' }}` with `.UNKNOWN_EXT` unrecognized by [`vim.filetype.match`](https://neovim.io/doc/user/lua.html#lua-filetype) does not result in a warning. This means that  `nvim-lspconfig` will appear[^2] to silently ignore the `setup{...}` definition when `nvim-lspconfig` knows the `KNOWN_SERVER` but `nvim` doesn't know `UNKNOWN_EXT`. There won't be any mentions of `SOME_SERVER` in `:LspLog` or `:LspInfo`, there won't be errors in `:checkhealth` or `:messages`. The only hint of what went wrong that I know of would be the empty list of filetypes in `:LspInfo`.

I ran into this issue running, apparently, a version of `nvim` that hasn't[^3] learned about dhall yet, and a version  of `nvim-lspconfig` that is aware of its lsp server.

It would be desirable, for example, to explicitly notify the user about referring to an unregistered "filetype" the moment `setup` is called. Or at any other point. This particular choice has the caveat of having to run `vim.filetype.add` before configuring `nvim-lspconfig` to avoid warnings.

[^1]: ...in the revision I'm running, at least
[^2]: from the user's point of view
[^3]: `lua vim.pretty_print(vim.filetype.match({filename = 'whatever.dhall'}))` outputs nothing

### Neovim version

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by nixbld

### Nvim-lspconfig version

902d6aa31450d26e11bedcbef8af5b6fe2e1ffe8

### Operating system and version

Linux 5.15.93 #1-NixOS SMP Thu Feb 9 10:26:48 UTC 2023 GNU/Linux

### Affected language servers

dhall_lsp_server, all

### Steps to reproduce

1. Run  `nvim some.UNKNOWN_EXT` with `require'lspconfig'.dhall_lsp_server.setup{ filetypes={'UNKNOWN_EXT'} }` in the lua 
2. 

### Actual behavior

No mentions of dhall or UNKNOWN_EXT in `:LspInfo`, no server running

### Expected behavior

A message about trying to bind to `UNKNOWN_EXT` that can't be `vim.filetype.match`-ed. Similar to the message one gets if they try to `.setup` a configuration `nvim-lspconfig` doesn't know about

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
    local path_sep = on_windows and '\\' or '/'
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
    vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
    local function buf_set_option(...)
        vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings.
    local opts = { buffer = bufnr, noremap = true, silent = true }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
        print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
    vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
    vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
    vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = 'dhall_lsp_server'
local cmd = { 'dhall-lsp-server' } -- needed for elixirls, lua_ls, omnisharp
if not name then
    print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
    print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
    filetype = { '.dhall', '.UNKNOWN_EXT' },
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

https://gist.github.com/SomeoneSerge/4109b67e2754bf472e6dd8b07bcbd382

**Comment by glepnir** [comment]
make sense. if match return nil through a warning .
