### ISSUE TITLE
yaml-language-server not sending FoldingRange Capabilities correctly?

### ISSUE THREAD

**Issue by briandipalma** [neovim/nvim-lspconfig#2464]
### Description

I'm seeing this issue: https://github.com/redhat-developer/yaml-language-server/issues/820 when opening yaml files.

```
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
RPC[Error] code_name = InternalError, message = "Request textDocument/foldingRange failed with message: Cannot read properties of undefine
d (reading 'lineFoldingOnly')"
```
 
When I uninstall/disable yaml-ls everything is fine so it's not the ansible-ls that's raising the error.

I grepped this repositories codebase and I can't find any reference to `foldingRange` so I've no idea how to attempt to fix this. Any pointers?

### Neovim version

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

### Operating system and version

Linux

### Affected language servers

yaml-language-server

### Steps to reproduce

1. Just open a yml file

### Actual behavior

An error is raised.

### Minimal config

```Lua
-
```

### LSP log

-

**Comment by glepnir** [comment]
provide log and try min config. i don't think problem from neovim lsp. the error say there has a field `undefined`. we don't send this in request method.
