### ISSUE TITLE
Powershell_es process its started but Neovim never attaches a buffer to it

### ISSUE THREAD

**Issue by TheLeoP** [neovim/nvim-lspconfig#2465]
### Description

The powershell LS (powershell_es) process its started by this plugins, but Neovim nevers attaches a buffer to it.

### Neovim version

NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

e20d77deac40e6e65d036acd60aff474c0f09282

### Operating system and version

Windows 10

### Affected language servers

powershell_es

### Steps to reproduce

1. `nvim -nu minimal_init.lua`
2. `:MasonInstall powershell-editor-services`
3. `:e foo.ps1`

### Actual behavior

The LS its started, but Neovim never attachers a buffer to it

### Expected behavior

Neovim should attach the buffer of the file `foo.ps1` to the LS

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local lspconfig_path = join_paths(package_root, "test", "start", "nvim-lspconfig")

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
	vim.fn.system({ "git", "clone", "https://github.com/neovim/nvim-lspconfig", lspconfig_path })
end

local mason_path = join_paths(package_root, "test", "start", "mason")

if vim.fn.isdirectory(mason_path) ~= 1 then
	vim.fn.system({ "git", "clone", "https://github.com/williamboman/mason.nvim", mason_path })
end

vim.lsp.set_log_level("trace")
require("vim.lsp.log").set_format_func(vim.inspect)
local nvim_lsp = require("lspconfig")
local on_attach = function(_, bufnr)
	local function buf_set_option(...)
		vim.api.nvim_buf_set_option(bufnr, ...)
	end

	buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

	-- Mappings.
	local opts = { buffer = bufnr, noremap = true, silent = true }
	vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
	vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
	vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
	vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
	vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
	vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
	vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
	vim.keymap.set("n", "<space>wl", function()
		print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
	end, opts)
	vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
	vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
	vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
	vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
	vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
	vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
	vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
end

require("mason").setup({
	install_root_dir = mason_path,
})

local mason_root = join_paths(mason_path, "packages")

-- Add the server that troubles you here
local name = "powershell_es"
local bundle_path = vim.fs.normalize(join_paths(mason_root, "powershell-editor-services"))
if not name then
	print("You have not defined a server name, please edit minimal_init.lua")
end
-- if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
-- 	print([[You have not defined a server default cmd for a server
--     that requires it please edit minimal_init.lua]])
-- end

nvim_lsp[name].setup({
	bundle_path = bundle_path,
	on_attach = on_attach,
})

print(
	[[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
)
```

### LSP log

https://gist.github.com/TheLeoP/9307c03613a1355780a591b895cf2858

**Comment by glepnir** [comment]
please try the min config no any other plugin in test  will be more clear .

**Comment by TheLeoP** [comment]
The problem is that the powershell-es config requires the path to the installation directory of `powershell-editor-services`, so it is impossible to create a minimal reproduction withouth knowing how `powershell-editor-services` was installed (in this case, using mason.nvim)

**Comment by justinmk** [comment]
It is up to you to figure out what plugins like mason.nvim doing. We can't troubleshoot every configuration.

The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by TheLeoP** [comment]
The problem isn't mason, it is installing the language server as it should.

The problem is nvim-lspconfig not setting the `cmd` option (I think (?) since I do not fully understand the source code) after calling `require'lspconfig'.powershell_es.setup` with the option `bundle_path` as the docs say. Mason isn't something particular to my config, I just used it for the minimal reproduction because `bundle_path` needs the path where the powershell LS is installed and I can't know the path unless I know how the LS was installed (in this case, using mason).

I tried to debug this myself and I couldn't figure out was going wrong. `on_new_config` gets called normally and it modifies the config table with a `cmd` option, but I got lost on how the configuration works and I just know that `:LspInfo` shows that there is no `cmd` set for `powershell_es`. So, I came here with a minimal reproduction and created an issue to ask for help.

The minimal reproduction would work exactly the same taking out mason, but it would require to install powershell_es manually and I just thought that using mason was a better idea. Should it help if I create a minimal reproduction installing the server manually? I really would like to contribute to solve this issue

**Comment by rudesome** [comment]
am facing the same issue, only experiencing this bug with powershell_es on Windows systems. 
Same lsp config on linux is working as expected/documented. Seems to be something with lspconfig..

I've set `bundle_path` and `cmd` manually but it just wont attach to the buffer

**Comment by rudesome** [comment]
@TheLeoP  I have tested on my personal device (W10) with the same nvim config / version and it gets attached as expected, when i try on my corporate device (W11) i got the same problem as you.. Maybe permissions or AV/Policy is disallowing the attachment with pwsh/powershell? Other LSP's are functioning as expected.

**Comment by TheLeoP** [comment]
My problem is happening on my personal computer, so I don't think that it may be because of permissions of AV/Policy. Maybe we are having two different problems (?)

**Comment by MoaidHathot** [comment]
@rudesome, I have the same problem. Works on my personal device but not on my Corp device.

**Comment by rudesome** [comment]
@MoaidHathot did you find any solution? 

When i run neovim as administrator and using the same configuration as my regular account the LSP **does** get attached, which makes me still think something is blocking the connection but can't trace down what it is

**Comment by scottmckendry** [comment]
@MoaidHathot, @rudesome  did either of you get this working? I'm fairly sure I'm running into the same problem (Win 11 corp device)

**Comment by MoaidHathot** [comment]
@scottmckendry, @rudesome, not yet. PowerShell had some breaking changes lately regarding I/O pipes. I think it may be related.

**Comment by scottmckendry** [comment]
@MoaidHathot  @rudesome @TheLeoP 
I've opened a new issue for this [here](https://github.com/neovim/nvim-lspconfig/issues/2810).

**Comment by TheLeoP** [comment]
For anyone wondering, [this comment](https://github.com/PowerShell/PowerShellEditorServices/issues/2092#issuecomment-1773535625) explains the problem and to avoid it you only need to do the following:


```lua
      require("lspconfig").powershell_es.setup {
        bundle_path = "path/to/your/bundle_path",
        init_options = {
          enableProfileLoading = false,
        },
      }
```

**Comment by MoaidHathot** [comment]
@TheLeoP, that works, thanks!
