### ISSUE TITLE
`astro-ls` does not update changes from  external `.ts` files in the current workspace

### ISSUE THREAD

**Issue by Odas0R** [neovim/nvim-lspconfig#2467]
### Description

I've been trying to identify the issue but no luck. When I modify a type on e.g `foo.ts` that change is not immediately updated on the astro lsp server, both `tsserver` and `astro-ls` are not in sync here and it affects the DX :(

### Neovim version

NVIM v0.9.0-dev-77-gf175ca9f7

### Nvim-lspconfig version

649137cbc53a044bffde36294ce3160cb18f32c7

### Operating system and version

Linux pop-os 6.0.12-76060006-generic

### Affected language servers

astro-ls

### Steps to reproduce

1. npm create astro@latest
2. create a `foo.ts` with
```ts
export const foo = () => {
  return {
    param: "1" // change to 1 then.
  }
}
```
3. import `foo.ts` it on a `.astro` file
4. change the foo() return value and check if the lsp updates

### Actual behavior

My types are _NOT_ updated on `.astro` files when I modify them.

### Expected behavior

My types are updated on `.astro` files when I modify them.

### Minimal config

```Lua
-
```

### LSP log

-

**Comment by glepnir** [comment]
need this pr neovim/neovim#21293 i think

**Comment by Odas0R** [comment]
> need this pr [neovim/neovim#21293](https://github.com/neovim/neovim/pull/21293) i think

Hummmmmmmm, nice. Makes sense, I tried to achieve that, but no luck. Can you point me in a direction for a possible _fix_?

**Comment by glepnir** [comment]
currently no good ways until that pr merge. only way is when you do edit in that file restart server. like do it in a bufwritepost callback.

**Comment by Odas0R** [comment]
I've installed the newer neovim version where the `didChangeWatchedFiles` was merged. I'm currently trying to:

```lua
local workspace_capabilities = {
  workspace = {
    didChangeWatchedFiles = {
      dynamicRegistration = true,
    },
  },
}

-- Inject lsp thingy into nvim-cmp
local capabilities = require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities())
capabilities = vim.tbl_deep_extend("keep", capabilities, workspace_capabilities)

require("lspconfig").astro.setup({
  on_attach = on_attach,
  capabilities = capabilities,
  flags = flags,
})
```

Still it does not work... :/ @glepnir 

Anything I'm missing?

**Comment by nojnhuh** [comment]
@Odas0R The config you have looks like it should work at first glance. The only difference I notice with mine is that in my `vim.tbl_deep_extend`, I call it with "keep" and the cmp capabilities listed after my didChangeWatchedFiles override table:
```lua
local default_caps = {
  workspace = {
    didChangeWatchedFiles = {
      dynamicRegistration = true,
    },
  },
}

capabilities = vim.tbl_deep_extend(
  "keep",
  default_caps,
  require("cmp_nvim_lsp").default_capabilities()
)
```

I would check the following in Neovim's LSP log with the verbosity turned up to at least `DEBUG`:
1. The client capability is set as expected in the `initialize` client call.
2. The server sends a `client/registerCapability` request for the `workspace/didChangeWatchedFiles` method.
3. Creating/changing/deleting a file you expect to match any of the `watchers` from the register request triggers a `workspace/didChangeWatchedFiles` notification sent to the server.

From a quick look at the source code for Astro, I can see where it [consumes the notifications](https://github.com/withastro/language-tools/blob/94bc851d4cebd281eb5b0fa17f4c1fa711a268e9/packages/language-server/src/server.ts#L216), but I don't see where it sends the request to register the capability.

**Comment by Odas0R** [comment]
> @Odas0R The config you have looks like it should work at first glance. The only difference I notice with mine is that in my `vim.tbl_deep_extend`, I call it with "keep" and the cmp capabilities listed after my didChangeWatchedFiles override table:
> 
> ```lua
> local default_caps = {
>   workspace = {
>     didChangeWatchedFiles = {
>       dynamicRegistration = true,
>     },
>   },
> }
> 
> capabilities = vim.tbl_deep_extend(
>   "keep",
>   default_caps,
>   require("cmp_nvim_lsp").default_capabilities()
> )
> ```
> 
> I would check the following in Neovim's LSP log with the verbosity turned up to at least `DEBUG`:
> 
>     1. The client capability is set as expected in the `initialize` client call.
> 
>     2. The server sends a `client/registerCapability` request for the `workspace/didChangeWatchedFiles` method.
> 
>     3. Creating/changing/deleting a file you expect to match any of the `watchers` from the register request triggers a `workspace/didChangeWatchedFiles` notification sent to the server.
> 
> 
> From a quick look at the source code for Astro, I can see where it [consumes the notifications](https://github.com/withastro/language-tools/blob/94bc851d4cebd281eb5b0fa17f4c1fa711a268e9/packages/language-server/src/server.ts#L216), but I don't see where it sends the request to register the capability.

Thank you for taking the time for the detailed response :)

I've been trying multiple things but still no success. I'm not very proficient in on LSP is supposed to work, but "I don't see where it sends the request to register the capability." makes sense. I guess I'll open an issue there to see if we can get this looked into.

I've also seen the `lsp.log` and didn't find the event `workspace/didChangeWatchedFiles` anywhere from the Astro server. So confirms what you've said!

Thank you.
