### ISSUE TITLE
Time to migrate to `vim.lsp.start()`?

### ISSUE THREAD

**Issue by musjj** [neovim/nvim-lspconfig#2470]
### Description

I have been suffering from a lot of LSP-related bugs recently, especially with LuaLS, and I have found that a lot of these issues does _not_ happen with the native `vim.lsp.start`.

### Neovim version

NVIM v0.9.0-dev-987+g371a74e4e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

b5db147e28337319331d516a826b00976f3584de

### Operating system and version

Windows 10

### Affected language servers

lua_ls

### Steps to reproduce

Refer to the part below for the reproduction configs.

1. `nvim -nu repro.lua ~/projects/foo/lua/foo.lua`
2. `:e ~/projects/bar/lua/bar.lua`

### Actual behavior

With the native configuration, everything works perfectly fine.
With the lspconfig configuration, when you open the second project, you will get tons of undefined global errors, and module paths are not resolved correctly when you `vim.lsp.buf.hover()` over any `require` statements.

### Expected behavior

Everything should just work.

### Minimal config

Here are two reproduce-able configurations that you can try, one with `vim.lsp.start` and the other with `lspconfig`. Make sure you have `lua-language-server` in your `PATH`.

<details>
<summary>Native (vim.lsp.start)</summary>

```lua
local root = vim.loop.os_tmpdir() .. "/.repro"
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath }
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
  "folke/tokyonight.nvim",
  "folke/neodev.nvim",
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")

require("neodev").setup { lspconfig = false }
vim.api.nvim_create_autocmd("FileType", {
  pattern = "lua",
  callback = function(opts)
    vim.lsp.set_log_level("debug")
    local name = vim.api.nvim_buf_get_name(opts.buf)
    local root = vim.fs.dirname(vim.fs.find({ ".git" }, { path = vim.fs.dirname(name), upward = true })[1])
    vim.keymap.set("n", "K", vim.lsp.buf.hover, { buffer = opts.buf })
    vim.lsp.start {
      name = "lua-language-server",
      cmd = { "lua-language-server" },
      before_init = require("neodev.lsp").before_init,
      root_dir = root,
      settings = { Lua = { workspace = { checkThirdParty = false } } },
    }
  end,
})
```
</details>

<details>
<summary>lspconfig</summary>

```lua
local root = vim.loop.os_tmpdir() .. "/.repro"
for _, name in ipairs { "config", "data", "state", "cache" } do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system { "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath }
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
  "folke/tokyonight.nvim",
  "folke/neodev.nvim",
  {
    "neovim/nvim-lspconfig",
    event = { "BufReadPost", "BufNewFile" },
    keys = { { "K", vim.lsp.buf.hover } },
    config = function()
      vim.lsp.set_log_level("debug")
      require("neodev").setup()
      require("lspconfig").lua_ls.setup {
        settings = { Lua = { workspace = { checkThirdParty = false } } },
      }
    end,
  },
}

require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
```
</details>

### LSP log

[native.log](https://gist.github.com/musjj/68d8578c96f37c01dcdd8276e21b3255)
[lspconfig.log](https://gist.github.com/musjj/afa79eafd78f716a514cc5150d665a9f)

**Comment by musjj** [comment]
Never mind all of this, `vim.lsp.start` spawns a second server instance of re-using the existing instance

**Comment by justinmk** [comment]
We do want to migrate, but may need to upstream something to vim.lsp.start ?

**Comment by glepnir** [comment]
lspconfig also used api which based on vim.lsp.start.problem not here.

**Comment by glepnir** [comment]
i had create a pr in upstream .

**Comment by glepnir** [comment]
https://github.com/neovim/neovim/pull/22388  okay this pr closed.  and i can' help you then.
