### ISSUE TITLE
Conditionally disabling an LSP for certain buffers

### ISSUE THREAD

**Issue by LordMZTE** [neovim/nvim-lspconfig#2477]
### Requested feature

I'm looking to stop an LSP from attaching to a buffer (and being started if it's not already running) if a callback function I provide returns false. Specifically, I want to disable an LSP for a filename that matches a pattern.

**Comment by justinmk** [comment]
one way would be to call stop() in your `on_attach` callback. See 

- https://github.com/neovim/nvim-lspconfig#suggested-configuration
- `:help vim.lsp.start_client()`

**Comment by LordMZTE** [comment]
This isn't ideal, as the server is still started, but I guess it'll do.

**Comment by glepnir** [comment]
set `auto_start` to false .create a Filetype event pattern is you filanme .then do config.luanch in callback
