### ISSUE TITLE
LSP[solc] not functional

### ISSUE THREAD

**Issue by zeroknots** [neovim/nvim-lspconfig#2478]
### Description

Trying to use solc LSP in lazyvim
simply installed solc lsp, and it throws error with every character I type

```
LSP[solc]: Error INVALID_SERVER_MESSAGE: {
  error = {
    code = -32803,
    message = "Unknown file: file:///Users/ops/work/*****/foundry/playground/src/Counter.sol"
  },
  jsonrpc = "2.0"
```

### Neovim version

NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

91998cef4b1ae3a624901d0f9c894409db24e760

### Operating system and version

MacOS 12.6

### Affected language servers

solc

### Steps to reproduce

1. install solc
2. mkdir foobar
3. forge init 
4. nvim ./src/Counter.sol
5. type anything in nvim
6. -> errors appear as documentented below

### Actual behavior

LSP[solc]: Error INVALID_SERVER_MESSAGE: {
  error = {
    code = -32803,
    message = "Unknown file: file:///Users/ops/work/*****/foundry/playground/src/Counter.sol"
  },
  jsonrpc = "2.0"

### Minimal config

```Lua
:LspInstall solc
```

### LSP log

-

**Comment by glepnir** [comment]
looks like the server not handle the schema + filename.

**Comment by zeroknots** [comment]
@glepnir  is there anything I can do to config this?

**Comment by h0tw4t3r** [comment]
I also confirm this bug with trying to get `solc --lsp` working in the `nvim` environment.

**Comment by iFrostizz** [comment]
You can use the hardhat solidity extension which is to date probably the best one: https://github.com/NomicFoundation/hardhat-vscode/pull/362

**Comment by justinmk** [comment]
The configs in this repo are provided as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- a failing test case added to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
