### ISSUE TITLE
Remap for accepting LSP suggestion

### ISSUE THREAD

**Issue by JasonBoyett** [neovim/nvim-lspconfig#2480]
### Requested feature

I would like to be able to change the behavior where when you get a suggestion list you hit enter to accept.  To often I will be at the end of a line and hit enter to go to the next line and instead of going to the next line the LSP suggestion will populate.

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
