### ISSUE TITLE
All highlight and color sechma gone after using sourcery 

### ISSUE THREAD

**Issue by meicale** [neovim/nvim-lspconfig#2481]
### Description

I use native lsp and pywrite for python file. After install sourcery lspconfig, I can use the function of sourcery and pyright, but I lose all the code highlight.

### Neovim version

NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

62856b20751b748841b0f3ec5a10b1e2f6a6dbc9

### Operating system and version

WSL2 Ubuntu20.04

### Affected language servers

pyright and treesitter

### Steps to reproduce

In stall sourcery as https://github.com/neovim/nvim-lspconfig/pull/1495 and https://github.com/sourcery-ai/sourcery/issues/43

### Actual behavior

has highlight

### Expected behavior

highlight gone

### Minimal config

```Lua
I don't know why, but I get no lsp.log even after I set the vim.lsp.set_log_level('debug') .
Thank you!
```

### LSP log

https://gist.github.com/

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by glepnir** [comment]
try disable semantic token.

**Comment by meicale** [comment]
> try disable semantic token.

Would you mind say something more about it? Where and How to set that?
The workaround I use is to set filetype again manually using the command: set filetype=python

**Comment by CLZamb** [comment]
I found a solution. as @glepnir mentioned you have to disable the: "lsp-semantic_tokens feat".

to disabled it you need to set these on your attach setup configuration.

```
on_attach = function(client)
        client.server_capabilities.semanticTokensProvider = nil
end
```

yo can also use.

```
on_init = function(client)
  client.server_capabilities.semanticTokensProvider = nil
end
```

or 

```
on_attach = function(client)
  if vim.g.colors_name == "dracula" then
     vim.schedule(function() vim.lsp.semantic_tokens.stop(bufnr, client.id) end)
  end
end
```

for more info read.
`https://github.com/neovim/neovim/commit/9f035559defd9d575f37fd825954610065d9cf96`

**Comment by CLZamb** [comment]
> > try disable semantic token.
> 
> Would you mind say something more about it? Where and How to set that? The workaround I use is to set filetype again manually using the command: set filetype=python

I found a solution. as @glepnir mentioned you have to disable the: "lsp-semantic_tokens feat".

to disabled it you need to set these on your attach setup configuration.

on_attach = function(client)
        client.server_capabilities.semanticTokensProvider = nil
end

yo can also use.

on_init = function(client)
  client.server_capabilities.semanticTokensProvider = nil
end

or

on_attach = function(client)
  if vim.g.colors_name == "dracula" then
     vim.schedule(function() vim.lsp.semantic_tokens.stop(bufnr, client.id) end)
  end
end

for more info read.
https://github.com/neovim/neovim/commit/9f035559defd9d575f37fd825954610065d9cf96

**Comment by marziply** [comment]
@meicale since @glepnir provided a very unhelpful but otherwise correct suggestion, here's the solution they should have provided:

```lua
vim.api.nvim_create_autocmd('LspAttach', {
  callback = function(args)
    local client = vim.lsp.get_client_by_id(args.data.client_id)

    client.server_capabilities.semanticTokensProvider = nil
  end
})
```
