### ISSUE TITLE
Mathematical formulas do not display properly

### ISSUE THREAD

**Issue by Case3y** [neovim/nvim-lspconfig#2484]
### Language server

pylsp

### Requested feature

When I check some method descriptions, the mathematical formulas in the method descriptions do not display properly.
<img width="960" alt="屏幕截图 2023-03-01 133251" src="https://user-images.githubusercontent.com/71315026/222054197-efa74d0b-3272-4793-99b6-8e21e8d4af4c.png">

**Comment by glepnir** [comment]
default markdown syntax render based on regex conceal so it might not works fine on some situations.  maybe treesitter markdown render can works fine on this ? not sure.
