### ISSUE TITLE
Rust lsp settings does not take affect

### ISSUE THREAD

**Issue by fioncat** [neovim/nvim-lspconfig#2485]
### Description

I follow the instruction to config settings for rust_analyzer, but it does not take affect.

### Neovim version

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

archlinux

### Affected language servers

rust_analyzer

### Steps to reproduce

1. Change the settings for `rust_analyzer`
```lua
nvim_lsp.rust_analyzer.setup({
    settings = {
        ["rust-analyzer"] = {
            procMacro = {
                enable = false,
            },
        },
    },
})
```
2. Change the log level for  `rust_analyzer`:
```bash
export RA_LOG="rust_analyzer=info"
```
3. Open a rust project.
4. View log:
```bash
cat ~/.local/state/nvim/lsp.log | grep -i 'procMacro_enable'
```

### Actual behavior

The `procMacro_enable` is still `true`.

### Expected behavior

The `procMacro_enable` should be `false`.

### Minimal config

```Lua
local nvim_lsp = require("lspconfig")		
nvim_lsp.rust_analyzer.setup({
    settings = {
        ["rust-analyzer"] = {
            procMacro = {
                enable = false,
            },
        },
    },
})
```

### LSP log

https://gist.github.com/fioncat/048c1e3e91884b671c2b9ce1f9a51501

**Comment by glepnir** [comment]
first `export RA_LOG="rust_analyzer=info"` you do this export rust analyzer log . then you check neovim lsp log ? it's different. you should check server log.  this is not work for lsp log level.  if you want debug lsp log you need set `vim.lsp.log.level` in your config. and clean log first.

**Comment by fioncat** [comment]
> first `export RA_LOG="rust_analyzer=info"` you do this export rust analyzer log . then you check neovim lsp log ? it's different. you should check server log. this is not work for lsp log level. if you want debug lsp log you need set `vim.lsp.log.level` in your config. and clean log first.

Tanks for reply, but the settings does not take effect in practice. Is there something wrong with my config?

**Comment by fioncat** [comment]
I found the `initial config` message in `lsp.log`, the value is incorrect.

**Comment by fioncat** [comment]
@glepnir the log seems to be empty

```bash
cat lsp.log | grep -i 'config from json'
```

```
.....[INFO rust_analyzer::config] updating config from JSON: {}\n'
[ERROR][2023-03-01 16:19:40] .../vim/lsp/rpc.lua:733    "rpc"   "rust-analyzer" "stderr"        "[INFO rust_analyzer::config] updating config from JSON: []\n"
[ERROR][2023-03-01 16:19:40] .../vim/lsp/rpc.lua:733    "rpc"   "rust-analyzer" "stderr"        "[INFO rust_analyzer::config] updating config from JSON: []\n"
```

Is this normal?

**Comment by fioncat** [comment]
@glepnir Thanks for helping, I solved it. The rust-tool plugin overwrite the settings.

**Comment by glepnir** [comment]
it's okay but next time you should try the min config first i think :)
