### ISSUE TITLE
Conflict `denols` and `vtsls` attached to the same buffer

### ISSUE THREAD

**Issue by hgigas** [neovim/nvim-lspconfig#2487]
### Description

`denols` and `vtsls` attached to the same buffer but deno's typescript differs from node's typescript, then imposible solve some diagnostics.

Sometimes both attached to buffer in deno project, sometimes both attached to buffer in node project.

### Neovim version

NVIM v0.9.0-dev-1084+g8bd0a9c36
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

95b7a69

### Operating system and version

Debian GNU/Linux 11

### Affected language servers

denols, vtsls

### Steps to reproduce

1. Create `deno.json`:
```json
{
  "imports": {
    "fs/": "https://deno.land/std@0.178.0/fs/",
    "http/": "https://deno.land/std@0.178.0/http/",
    "io/": "https://deno.land/std@0.178.0/io/"
  }
}
```
2. Open `server.ts` with nvim:
```typescript
import { serve } from 'http/server.ts';
import { Buffer } from 'io/buffer.ts';

const port = 8000;

const dirname = new URL('.', import.meta.url).pathname;

const requestListener = async (req: Request): Promise<Response> => {
  console.log('Request received: ', req.url);
  return await Deno.readTextFile(dirname + "/index.html")
  .then((contents: Buffer) => new Response(contents, { status: 200 }))
  .catch((err: Error) => new Response(err.message, { status: 500 }));
};

await serve(requestListener, { port })
```
3. Run `LspInfo`: `denols` and `vtsls` attached to the buffer.

Line 10 with error "Cannot find name 'Deno'." but it is a deno project.

Same in node project with `.git` and `package.json`, both attached but only `vtsls` required.

### Actual behavior

`denols` and `vtsls` attached to the buffer

### Expected behavior

Only `denols` attached to the buffer. Same in node project with `.git` and `package.json`, both attached but only `vtsls` required.

### Minimal config

```Lua
local on_attach = function(client, bufnr)
  ...
end
local capabilities = require'cmp_nvim_lsp'.default_capabilities(
  vim.lsp.protocol.make_client_capabilities()
)
for _, lsp in pairs({
  'vtsls', 'denols',
}) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
    flags = {
      debounce_text_changes = 1000,
    }
  }
end
```

### LSP log

lsp.log is empty

**Comment by glepnir** [comment]
you need custom the root pattern for your situation.

**Comment by hgigas** [comment]
`vtsls` has

```
    single_file_support = true,
```
custom root pattern don't works in this case, in fact the default `root_dir` function returns `nil` in the example in **Steps to reproduce**

**Comment by glepnir** [comment]
why it not works ? you can disable the single file mode ? and you can set the `autostart` to false and create `Filetype` event to do config.launch in callback . write start server logic by your self.

**Comment by hgigas** [comment]
In some cases is interesting `single_file_support`. Could you give me an example code of _you can set the autostart to false and create Filetype event to do config.launch in callback_ ?

**Comment by hgigas** [comment]
To whom it may concern:
```
      local util = require'lspconfig.util'
      lspconfig.vtsls.setup {
        single_file_support = false,
        root_dir = function(fname)
          return not util.root_pattern('deno.json', 'deno.jsonc')(fname)
          and (util.root_pattern('tsconfig.json')(fname) or util.root_pattern(
          'package.json', 'jsconfig.json', '.git', '.')(fname))
        end,
        ...
      }
      lspconfig.denols.setup {
        root_dir = util.root_pattern('deno.json', 'deno.jsonc'),
        ...
      }
```
Very tricky but works...
