### ISSUE TITLE
jsonls typo on language server command

### ISSUE THREAD

**Issue by anthony2025** [neovim/nvim-lspconfig#2489]
### Description

The jsonls includes the wrong command for the language server:
it says `vscode-json-language-server` when it should be `vscode-json-languageserver`.

### Neovim version

NVIM v0.9.0-dev-1063+gf64098a2d-dirty
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

n/a

### Affected language servers

jsonls

### Steps to reproduce

n/a

### Actual behavior

n/a

### Minimal config

```Lua
n/a
```

### LSP log

n/a

**Comment by glepnir** [comment]
there is no `vscode-json-languageserver`. command is correct.

**Comment by polyzen** [comment]
It's actually the official name from upstream VS Code.

https://github.com/neovim/nvim-lspconfig/pull/1288

**Comment by anthony2025** [comment]
It appears listed by npm as  `vscode-json-languageserver`, at least on macos.

**Comment by polyzen** [comment]
Seems VS Code doesn't bump the versions for these servers. That package has 1.3.4 which is the latest version, but there has been a fair amount of work since then.
