### ISSUE TITLE
Add support for settings schema from VSCode package.json

### ISSUE THREAD

**Issue by norcalli** [neovim/nvim-lspconfig#25]
https://github.com/rust-lang/rls-vscode/blob/master/package.json
https://github.com/lampepfl/dotty/blob/master/vscode-dotty/package.json
https://github.com/mauve/vscode-terraform/blob/master/package.json

There is a very simple part of the existing VSCode extensions that we can automatically adopt by parsing `contributes.configuration`. There are other sections that we can get as well.

I'm considering adding this to `docs` just for auto generating documentation about what the default settings are, but we could use the same schema to provide client side validation of the settings as well.

So currently, I think this will be sufficient:

```lua
docs = {
  package_json = "https://github.com/rust-lang/rls-vscode/blob/master/package.json";
}
```

and then we can pull it from docgen (and cache it in case it hasn't changed). 

Also, we can put these in the

<details>
<summary>Default server settings:</summary>
<pre>
nvim_lsp[server].setup {
  settings = {
    ...
  }
}
</pre>
</details>

since these settings will often be long.

**Comment by norcalli** [comment]
Implemented in #29

**Comment by norcalli** [comment]
Follow up in #49. Adds the ability to scrape the vspackage itself from microsoft directly, which is more accurate. We should prefer that in the future.

**Comment by justinmk** [comment]
@norcalli  What's remaining to be done here?

**Comment by saadparwaiz1** [comment]
Hi @mjlbach. If it's fine with you I want to try and attempt something for this issue? I currently have a partially complete attempt at this [here](https://github.com/saadparwaiz1/validate-nvim-lsp-settings) if you like this approach let me know and I can work on this further and make a PR.

The approach is pretty simple use the package.json such as one for [pyls](https://github.com/saadparwaiz1/validate-nvim-lsp-settings/blob/main/json/pyls.json)  and convert it to an equivalent [lua](https://github.com/saadparwaiz1/validate-nvim-lsp-settings/blob/main/lua/server_settings/pyls.lua) table. Then validation should be as simple as iterating over the keys in user settings to the default server settings.

I am pretty new to using lua, so the codebase isn't that great. but I can try and improve things

**Comment by mjlbach** [comment]
Sounds terrific to me. I lean towards it being a helper function which isn't loaded by default that people can call with their current configs table to check if all settings are valid. No runtime penalty for those who already have working configs and the like (people could wrap/call the helper in their config if they want).

**Comment by saadparwaiz1** [comment]
Sounds, good. I'll get working on this and make a PR soon!

**Comment by mjlbach** [comment]
vscode package.json's have increasingly started mixing in non-server settings. I think it will be difficult to reliably use these without manual validation.
