### ISSUE TITLE
Add ability to control whether the server starts or not even when single_file_support=true

### ISSUE THREAD

**Issue by hrsh7th** [neovim/nvim-lspconfig#2508]
### Language server

N/A

### Requested feature

I have `denols` and `vtsls` for typescript.

I'm implemented the following root_dir function.

```lua
  local function deno_or_node(prefer)
    return function(fname)
      local type = {
        deno = require('lspconfig').util.root_pattern("deno.json")(fname),
        node = require('lspconfig').util.root_pattern("package.json")(fname),
      }
      local other = prefer == 'deno' and 'node' or 'deno'
      if type[prefer] and type[other] then
        local is_other = #vim.split(type[other], '/', { plain = true }) > #vim.split(type[prefer], '/', { plain = true })
        if is_other then
          return
        end
      end
      return type[prefer]
    end
  end
```

But I have to specify `single_file_support=false` for this.

It's useful if lspconfig provided a function to determine `whether to attach or not`.

**Comment by glepnir** [comment]
need add another condition in this line to determine whether to attach or not

https://github.com/neovim/nvim-lspconfig/blob/63f4c0082f007d2356df4bc335f55e6d414da89c/lua/lspconfig/configs.lua#L125

**Comment by justinmk** [comment]
> It's useful if lspconfig provided a function to determine `whether to attach or not`.

`on_attach` ?

**Comment by hrsh7th** [comment]
The `on_attach` can't be used to determine the server should/shouldn't attach to the buffer.

But My intension is this. I think it's useful if we have `should_attach: func...` for this situation.

**Comment by glepnir** [comment]
add new field not a good way. in `on_attach` you can do it like this.

```lua
on_attach = function(client, bufnr)
     if not client.config.root_dir then
        local cwd = vim.loop.cwd()
        if some condition here then
            vim.lsp.stop_client(client.id)
        end
    end
end
```

**Comment by hrsh7th** [comment]
I'm a bit concerned about calling `M._setup_buffer` afterward even if I stop the client in `on_attach`, but the advice seems to meet my needs. thank you!

I think this issue is in a state to be closed if necessary.

**Comment by glepnir** [comment]
yet another way is set the `server.auto_start` to false then do logic in `FileType` autocommand callback

```lua
tsserver.auto_start = false

vim.api.nvim_create_autocmd('FileType', {
     pattern = foo,
     callback = function()
          if logic then
              require('lspconfig.configs')['tsserver'].launch()
          end
     end

```

**Comment by justinmk** [comment]
Nice! Should we add the above as a hint to the readme / `:help lspconfig` ?

**Comment by hrsh7th** [comment]
I think `require('lspconfig.configs')['%SERVER%'].launch()` is ideal solution.
Thank you again!

**Comment by hrsh7th** [comment]
It may be a documentation issue, but I'm a little concerned that `launch` actually means not only starting the server, but also attaching to the current buffer.

**Comment by glepnir** [comment]
it will attach current buffer to this client. in this way start client or not determine what  the your logic condition is 

```
lspconfig.tssserver.setup({
       -- config this lspconfig won't set the FileType event to start server you need start server manually
        auto_start = false
})

vim.api.nvim_create_autocmd('FileType', {
    pattern = 'typescript'
    callback = function()
        local cwd = vim.loop.cwd()
        if vim.fn.filereadable(cwd ..'/deno.json') == 0 then
             require('lspconfig.configs')['tsserver'].launch()
        end
    end
```

**Comment by hrsh7th** [comment]
I tried this approach but it didn't work.

It seems that once nvim-lspconfig attaches to a particular file type, it automatically attaches the next time you open a buffer of the same file type.
And in that case, checks such as root_dir are still performed, so deno/vtsls isolation does not work well.

It seems to me that there should be a setting like should_attach.

_Google Translation_

thank you for the advice! I'll explore this.

**Comment by glepnir** [comment]
```lua
vim.api.nvim_create_autocmd('FileType', {
    pattern = 'typescript',
    callback = function(opt)
        local cwd = vim.loop.cwd()
        local client
        for _, item in ipairs(vim.lsp.get_active_clients(opt.buf)) do
          if item.name == 'tsserver' then
            client = item
            break
          end
        end
        local condition = vim.fn.filereadable(cwd ..'/deno.json') == 0
        if client and condition then
          vim.lsp.buf_attach_client(opt.buf, client)
        elseif not client and condition then
          require('lspconfig.configs')['tsserver'].launch()
        end
    end
  })
```

**Comment by hrsh7th** [comment]
In my investigation, the lspconfig adds the autocmd at https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#L104.
So tsserver will be attached on all of new typescript buffer.

I think the current lspconfig doesn't have an ideal solution for this situation.

I will consider this problem and lspconfig.
Along the way, I may choose not to use lspconfig.
First of all, I'd like to see if lspconfig could be improved.

**Comment by hrsh7th** [comment]
IMO, the autocmd still be added in L104.

If we specify `autostart=false`, `root_dir = nil`, the autocmd wont added.

But `root_dir=nil` was specified, workspaceFolder wont be initialized correctly.

**Comment by glepnir** [comment]
nope what i mean is add a patch to check create this event `BufReadPost`  or not .if `autostart` to false lspconfig shouldn't create any event.

**Comment by NReilingh** [comment]
+1 to the `should_attach` idea. I think I came to the same conclusion as hrsh7th prior to finding this issue. You can be in a state where both LSPs should be running in your editor, but you still want to micromanage their attachments to different buffers. Lspconfig provides lots of tools for controlling language server start/stop, but not attach/detach.

Using `on_attach` could work _if_ it were possible to call `vim.lsp.buf_detach_client()` here, but neovim doesn't actually mark the client as attached to the buffer until after `on_attach` and `LspAttach` have been fired. [This Reddit comment](https://www.reddit.com/r/neovim/comments/168u3e4/comment/jyyluyo/) describes using `vim.schedule()` or `vim.defer_fn()` to work around the limitation, but this would be much cleaner if you had fine-grained control over which buffers lspconfig tries to attach to in the first place.

**Comment by Drew-Daniels** [comment]
@NReilingh Bump
