### ISSUE TITLE
Function documentation dissappears after selecting lsp completion

### ISSUE THREAD

**Issue by demizer** [neovim/nvim-lspconfig#251]
This is a feature request, a similar issue has already been reported to vim-lsp at https://github.com/prabirshrestha/vim-lsp/issues/275

- `nvim --version`:  v0.5.0-508-gc37d9fa3d
- nvim-lsp version(commit hash): 205a9f0ca9e733d94f15f228b9e23b29a80af7cd

### The issue

When a completion is shown in the menu, the function documentation is shown correctly. But when the completion is selected, or the "(" is typed, the function documentation disappears. My memory is not that great, so it would be helpful to keep showing function documentation.

![doc_popup_example](https://user-images.githubusercontent.com/30035/82851460-c125c000-9eb4-11ea-9177-71d01e2c02fd.gif)

### Expected behavior

As identified in the vim-lsp issue above, other editors with lsp implementations show a popup window with the documentation and it updates as the function parameters are typed.

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
