### ISSUE TITLE
sqls have been deprecated.

### ISSUE THREAD

**Issue by uga-rosa** [neovim/nvim-lspconfig#2530]
### Language server

sqls

### Requested feature

[sqls](https://github.com/lighttiger2505/sqls) is now public archived.
I will leave it to you to decide whether to keep it or delete it, but I will report it.

**Comment by glepnir** [comment]
currently we can mark it as deprecated. and wonder do we have second server choice ?

**Comment by uga-rosa** [comment]
There are [sqlls](https://github.com/joe-re/sql-language-server), which are already in.

**Comment by glepnir** [comment]
yep I found it. but currently github can't push code .. so I will mark the sqls as deprecated later.

**Comment by uga-rosa** [comment]
@glepnir hi :)

**Comment by glepnir** [comment]
pong. sry a little busy recently.  need to popup a notify when server is deprecated in a version.  currently we don't have this. so I am thinking add a  field in setup like `deprecated` or something else .

**Comment by sigzegv** [comment]
why sqls has been deprecated ? for now I tested sqlls, it doesn't seems to handle parameters in connection settings (as exemple to configure tls, I didn't found anything), and the lsp client tells me that sqlls doesn't handle hovering and displaying definitions (sqls does it)

**Comment by uga-rosa** [comment]
> [sqls](https://github.com/lighttiger2505/sqls) is now public archived.

**Comment by uga-rosa** [comment]
What's that magic box in front of you for?
