### ISSUE TITLE
TailwindCSS lsp is Extremely Buggy and Slow.

### ISSUE THREAD

**Issue by sadikeey** [neovim/nvim-lspconfig#2532]
### Description

- Just wanted to give a heads up about Neovim native LSP for TailwindCSS. I've noticed that it often takes a long time to respond, which can be frustrating when trying to work efficiently.
- I've tested several other language servers with Neovim and haven't had any issues with slow response times.
- I've also tested the TailwindCSS lsp in VSCode and haven't noticed any issues with slow response times.

### Neovim version

NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

9139e5c

### Operating system and version

Arch Linux

### Affected language servers

TailwindCSS

### Steps to reproduce

You can simply install tailwindcss language server and you will start noticing the approximate 1 sec delay for a lsp to respond the suggestion.

### Actual behavior

It takes approximately 1 sec second lag for providing the suggestion and not just that it freezes for that second.

### Expected behavior

I expects the responds imediately, just like other language server.

### Minimal config

```Lua
I am using masonlsp-config
```

### LSP log

Client: tailwindcss attached to the buffer.

**Comment by polyzen** [comment]
I assume you're using nvim-cmp? https://github.com/hrsh7th/nvim-cmp/issues/1009

**Comment by sadikeey** [comment]
> I assume you're using nvim-cmp? [hrsh7th/nvim-cmp#1009](https://github.com/hrsh7th/nvim-cmp/issues/1009)

Yes

**Comment by login6** [comment]
> > I assume you're using nvim-cmp? [hrsh7th/nvim-cmp#1009](https://github.com/hrsh7th/nvim-cmp/issues/1009)
> 
> Yes, I am using nvim-cmp Is it because of [hrsh7th/nvim-cmp#1009](https://github.com/hrsh7th/nvim-cmp/issues/1009) ??

just use coc-nvim, this issue is not related to the nvim-lspconfig

**Comment by sadikeey** [comment]
- But I don't want to use coc-nvim.
- I don't know if this issue is related to nvim-lspconfig or not. What exactly is the issue?

**Comment by login6** [comment]
> * But I don't want to use coc-nvim.
> * I don't know if this issue is related to nvim-lspconfig or not. What exactly is the issue?

this issue is related to the implementation of tailwindcss server, which returns too many items to each query, and currently only coc-nvim (maybe other too, but i'm not sure) can normally work with this server(due to specific optimizations).

**Comment by sadikeey** [comment]
Ok, thankyou

**Comment by vasujain275** [comment]
Any progress with nvim-cmp compatibility? It is still really slow and buggy with mason and nvim-cmp

**Comment by sadiksaifi** [comment]
@vasujain275 Now it has been fixed and it works like a charm!

**Comment by yebt** [comment]
> Now it has been fixed and it works like a charm

Sorry, Where is it fixed?

**Comment by doaortu** [comment]
> Sorry, Where is it fixed?

I also face the same problem, didn't know if this could help but, I read post on reddit with the same title, and someone pointed that we can improve `nvim-cmp` performance by applying this config:
```
M.cmp = {
  sources = {
    name = "nvim_lsp",
    priority = 10,
    keyword_length = 6,
    group_index = 1,
    max_item_count = 30,
  },
  performance = {
    trigger_debounce_time = 500,
    throttle = 550,
    fetching_timeout = 80,
  },
}
```

source: https://www.reddit.com/r/neovim/comments/124pi2t/neovim_native_lsp_with_tailwind_css_is_extremely/

**Comment by sadiksaifi** [comment]
@doaortu this issue has been fixed, now you don't need to do any special thing for tailwindcss lsp, not need to add this block
```lua
  performance = {
    trigger_debounce_time = 500,
    throttle = 550,
    fetching_timeout = 80,
  },
```

**Comment by Pismice** [comment]
> [@doaortu](https://github.com/doaortu) this issue has been fixed, now you don't need to do any special thing for tailwindcss lsp, not need to add this block
> 
>   performance = {
>     trigger_debounce_time = 500,
>     throttle = 550,
>     fetching_timeout = 80,
>   },

where do you need to add that ? I still have the issue
