### ISSUE TITLE
Issue: it's been a while since last stable release

### ISSUE THREAD

**Issue by craigmac** [neovim/nvim-lspconfig#2545]
### Description

Can another official release be cut? Last release says Dec. 2022. I check the roadmap/breaking changes pinned issues, but those seemed out of date and maybe not-relevant anymore? There's been breaking changes that aren't listed there, and it the issue was closed also. The change in name of 'help' to 'vimdoc' is causing issues over at lazyvim repo and kickstart repo as well, many which could probably be worked around with a better understanding of their config but I digress. What are the blockers for a release?

### Neovim version

NVIM Head

### Operating system and version

macOS 12.15

### Affected language servers

help

### Steps to reproduce

Copy default kickstart.nvim template and boot it. 

### Actual behavior

you get error about no found 'help' server

### Expected behavior

Flawless install of kickstart.nvim :)

### Minimal config

```Lua
https://github.com/nvim-lua/kickstart.nvim/blob/master/init.lua
```

### LSP log

not relevant

**Comment by dundargoc** [comment]
I am thoroughly confused. Was this meant for the nvim-treesitter repo?

**Comment by dundargoc** [comment]
Actually, why open an issue to `kickstart.nvim` instead?

**Comment by craigmac** [comment]
I think I've confused myself as well, on second read. Closing!
