### ISSUE TITLE
Various LSP servers break color/seem to load twice

### ISSUE THREAD

**Issue by EricDriussi** [neovim/nvim-lspconfig#2552]
### Description

I'm not entirely sure how to describe the issue, but I think the images are quite explanatory.

When loading any (lua_ls, tsserver) lsp server, the tokens look like this:

![lsp1](https://user-images.githubusercontent.com/46979145/230720534-2e400646-66cc-4e54-9142-c8a0d0a3b73a.png)

And then immediately change to this:

![lsp2](https://user-images.githubusercontent.com/46979145/230720536-45b33258-84c8-4df9-9eb4-b9ce16bb0225.png)

Since this happens with various languages, I'm assuming the issue is related to this plugin rather than the langs themselves. I might be wrong tho.

### Neovim version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

e683951a35ade60f9e1768ef770bb42ffcc1d2b7

### Operating system and version

Linux 6.2.9-arch1-1

### Affected language servers

all? (tested with lua and typescript)

### Steps to reproduce

1. download the provided minimal config
1. open a `.lua` file with `nvim -u minimal_init.lua`
1. wait for 2 seconds or so

### Actual behavior

As stated above, something seems to break the colors/tokens.
Initially loads like this:

![lsp1](https://user-images.githubusercontent.com/46979145/230720551-02fc12a4-27ed-4e64-87ed-e16ddf4c9e7e.png)

After a second or so, changes to this:

![lsp2](https://user-images.githubusercontent.com/46979145/230720554-02333092-1c2d-41f8-b2f2-50837449204d.png)

### Expected behavior

After seeing how it behaves when using a proper color scheme, I would expect the second "re-paint" to not happen at all.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match "Windows"

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv "TEMP" or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local lspconfig_path = join_paths(package_root, "test", "start", "nvim-lspconfig")

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
	vim.fn.system { "git", "clone", "https://github.com/neovim/nvim-lspconfig", lspconfig_path }
end

vim.lsp.set_log_level "trace"
require("vim.lsp.log").set_format_func(vim.inspect)
local nvim_lsp = require "lspconfig"
local on_attach = function(_, bufnr)
	local function buf_set_option(...)
		vim.api.nvim_buf_set_option(bufnr, ...)
	end

	buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

	-- Mappings.
	local opts = { buffer = bufnr, noremap = true, silent = true }
	vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
	vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
	vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
	vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
	vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
	vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
	vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
	vim.keymap.set("n", "<space>wl", function()
		print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
	end, opts)
	vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
	vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
	vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
	vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
	vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
	vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
	vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = "lua_ls"
local cmd = { "lua-language-server" } -- needed for elixirls, lua_ls, omnisharp
if not name then
	print "You have not defined a server name, please edit minimal_init.lua"
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
	print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
	cmd = cmd,
	on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

https://gist.github.com/EricDriussi/91fa8618a0b2fc7b78a27372ab9ad8b3

**Comment by glepnir** [comment]
`:h lsp-semantic_tokens`

**Comment by EricDriussi** [comment]
Well, at least that pointed me to the right direction...

In case anyone ends up here: What needs to be done to correct this behavior is set `client.server_capabilities.semanticTokensProvider` to false within the `on_attach` function in your lsp config.

This `semanticTokensProvider` is supposed to only be enabled when attached to a client that supports it, but for me it just made things generally worse.
You might want to only disable it for a problematic client `if client.name == "lua_ls" then blablabla`.

**Comment by marziply** [comment]
@glepnir being only marginally helpful before closing this issue... @EricDriussi is correct, an example use is below:

```lua
vim.api.nvim_create_autocmd('LspAttach', {
  callback = function(args)
    local client = vim.lsp.get_client_by_id(args.data.client_id)

    client.server_capabilities.semanticTokensProvider = nil
  end
})
```
