### ISSUE TITLE
Duplicating Servers when switching git worktrees

### ISSUE THREAD

**Issue by pedro757** [neovim/nvim-lspconfig#2561]
### This is the output of `:LspInfo` from the first worktree:

![image](https://user-images.githubusercontent.com/30637426/232075023-11b6a42e-6d87-4762-8e39-2172e58ea3a7.png)

All of them point to `pedro_branch` which is correct.

### This is the output of `:LspInfo` after switching worktrees:

![image](https://user-images.githubusercontent.com/30637426/232075628-e961e2cc-a3c2-47dd-a98e-2d19337472e0.png)

**Some** of them point to `main_branch` which is correct. But **some** are running in `single file mode`.

### Neovim version

NVIM v0.10.0-dev-53+g5ccec143d
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

e52efca5d4f5536533d447ec0d97e4d525b37ace

### Operating system and version

Linux

### Affected language servers

tsserver

### Steps to reproduce

I might add this later

### Actual behavior

After switching worktrees it duplicates the servers, but using the `single file mode`:

![image](https://user-images.githubusercontent.com/30637426/232075628-e961e2cc-a3c2-47dd-a98e-2d19337472e0.png)

### Expected behavior

Is it possible to not create those servers?

### Minimal config

```Lua
I might add this later
```

### LSP log

I might add this later

**Comment by glepnir** [comment]
provide log and reproduce step.
