### ISSUE TITLE
[+doc] instruction setting a language server as optional and toggle it

### ISSUE THREAD

**Issue by SichangHe** [neovim/nvim-lspconfig#2566]
### Requested feature

I could not find documentation as of how to set a language server as optional and toggle it on and off without restarting Neovim.

I think this is a common use case and it would be nice to have it documented.

This could easily be achieved by setting `autostart` to `false` and using `:LspStart`.

Example: set `pylsp` as optional and toggle it on manually:

```lua
-- init.lua
require('lspconfig').pylsp.setup {
    autostart = false,
    settings = {
        pylsp = {
            plugins = {
                flake8 = {
                    enabled = true,
                },
            },
        },
    },
}
```

Using the above setup, PyLSP would not be started even if a `py` file is open.

One would toggle it on using `:LspStart pylsp`.

**Comment by glepnir** [comment]
should be write in wiki.

**Comment by adrian5** [comment]
I've added a [Wiki entry](https://github.com/neovim/nvim-lspconfig/wiki/Toggle-LSP-for-current-buffer), as I was looking for this functionality too.
