### ISSUE TITLE
Completion list items are really long

### ISSUE THREAD

**Issue by demizer** [neovim/nvim-lspconfig#257]
When showing completions, the completion items are so long they go off the screen. See attached screenshot.

I am not certain where the problem is originating from, the nvim-lsp plugin or the LSP server.

- `nvim --version`: v0.5.0-508-gc37d9fa3d
- nvim-lsp version(commit hash): 54f4f823a27ffa8f9e6c308d550888f3ae21373e
- `:checkhealth` result: Everything is "OK"
- What language server(If the problem is related to a specific language server): Latest from https://github.com/zigtools/zls
- Operating system/version: Arch Linux
- Terminal name/version: zsh 5.8
- `$TERM`: screen-256-color

I am using additional plugins to make omnifunc a little nicer:

```
Plug 'haorenW1025/completion-nvim'
Plug 'ncm2/float-preview.nvim'
```

I have these settings set:

```
set completeopt=menu,noinsert,noselect,menuone
set shortmess+=c
```

### How to reproduce the problem from neovim startup

Type a variable in the current buffer, a really long completion window is shown.

![Screenshot from 2020-05-31 19-47-15](https://user-images.githubusercontent.com/30035/83372199-7f47be80-a379-11ea-887c-f07f3793eb20.png)

### Expected behaviour

A completion list that only shows what is necessary.

**Comment by demizer** [comment]
I should note, this is the only LSP I am using currently, and it under very active development.

**Comment by Shougo** [comment]
It seems new lines are not truncated.

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
