### ISSUE TITLE
Unable to configure robotframework_ls server

### ISSUE THREAD

**Issue by restagner** [neovim/nvim-lspconfig#2572]
### Description

I'm **_new to neovim_** and I am attempting to configure `robotframework_ls` [server](https://github.com/robocorp/robotframework-lsp/tree/master/robotframework-ls).  I understand that this is a client-server architecture, where `neovim` is the client and `robotframework_ls` is the server.  However, and I've searched the internet for examples, I'm unable to understand how to configure the client to update the server's pythonpath, using the `robot.pythonpath` settings as described in its [configuration settings](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/config.md).

The issue I'm encountering is an inability for the LS to identify the `SeleniumLibrary` within my `robot` file (see below screen shot). 

![robotframework-ls-error](https://user-images.githubusercontent.com/798521/233870766-117e4f5f-728f-4621-a88e-fe992d0d0fd9.png)

I'd like to configure the server to accept the `robot.pythonpath` as noted in the  [configuration settings](https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/config.md), but I'm new to neovim and I'm not having any luck setting up the LS to support this.

### Neovim version

NVIM v0.8.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az178-366

### Operating system and version

Kubuntu 22.04.2 LTS x86_64 (Kernel: 5.15.0-70-generic)

### Affected language servers

robotframework_ls

### Steps to reproduce

1. be sure to install `robotframework_ls` using Mason
2. open a robot (or resource) file that contains a statement that uses the `SeleniumLibrary`
3. if the language server finds the selenium library, then I would expect to see no errors

### Actual behavior

![robotframework-ls-error](https://user-images.githubusercontent.com/798521/233870926-7d7e3944-2212-4d6d-b1be-04e2129da588.png)

### Expected behavior

no errors from language server

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = 'robotframework_ls'
local cmd = { 'robotframework_ls' } -- needed for elixirls, lua_ls, omnisharp
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
  cmd = cmd,
  on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log
[lsp log file for robotframework](https://gist.github.com/restagner/f3434294e31c784c5e11172cb20a675e)

**Comment by sigmaSd** [comment]
it should look like this 
```lua
nvim_lsp[name].setup {
  cmd = cmd,
  on_attach = on_attach,
  settings = {
    robot = {
      pythonpath = "patthere"
    }
  }
}
```
