### ISSUE TITLE
does typescript-language-server support on_new_config ?

### ISSUE THREAD

**Issue by tcstory** [neovim/nvim-lspconfig#2586]
### Language server

typescript-language-server

### Requested feature

typescript-language-server will use its own tsserver by default, but i want it to use the tsserver that specified by the package.json. the following are the example config.

```lua
local function get_typescript_server_path(root_dir)

  local global_ts = util.path.join(vim.fn.stdpath('data'), 'mason', 'packages', 'typescript-language-server', 'node_modules', 'typescript', 'lib')

  local found_ts = ''
  local function check_dir(path)
    found_ts =  util.path.join(path, 'node_modules', 'typescript', 'lib')
    if util.path.exists(found_ts) then
      return path
    end
  end
  if util.search_ancestors(root_dir, check_dir) then
    return found_ts
  else
    return global_ts
  end
end


require'lspconfig'.tsserver.setup{
  on_attach = on_attach,
  capabilities = capabilities,
  on_new_config = function(new_config, new_root_dir)
    new_config.init_options.tsserver.path = get_typescript_server_path(new_root_dir)
  end,
}

```

**Comment by glepnir** [comment]
> typescript-language-server will use its own tsserver by default

what you mean own ? it use the server which you install with `npm -g ` . in your global node_modules dir.

this is not correct way to use `on_new_config`. in you situation you should custom the `cmd` field .

**Comment by tcstory** [comment]
I dont want it to use the global server, i just want it to use the server that specified by the project(the version specified by the package.json) 

@glepnir

**Comment by glepnir** [comment]
You can specify the server address you use in cmd, right?  `cmd = { path/to/your/build/typescrpt-language-server ,'--stdio' }`

**Comment by tcstory** [comment]
> You can specify the server address you use in cmd, right? `cmd = { path/to/your/build/typescrpt-language-server ,'--stdio' }`

thanks, I had found the solution, my previous config has an error, change ` new_config.init_options.tsserver.path = get_typescript_server_path(new_root_dir)` to  
`
    new_config.init_options.tsserver = {
      path = get_typescript_server_path(new_root_dir)
    }
` will fix the problem

**Comment by glepnir** [comment]
no need make it trouble . just chagne cmd path to use your mason installed.
