### ISSUE TITLE
rust_analyzer is not working 

### ISSUE THREAD

**Issue by joshuaautawi** [neovim/nvim-lspconfig#2589]
### Description

Hi guys, i new in neovim. I have a problem when running rust_analyzer lsp.

### Neovim version

NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

git rev-parse HEAD

### Operating system and version

Kubuntu 22.04.2 LTS x86_64 (Kernel: 5.15.0-70-generic)

### Affected language servers

rust_analyzer

### Steps to reproduce

install rust_analyzer using mason

### Actual behavior

![Screenshot from 2023-05-07 10-22-41](https://user-images.githubusercontent.com/77089209/236655961-1558f2ed-b94b-4e63-8509-04a94b8c5d0b.png)

### Minimal config

```Lua
local lsp = require("lsp-zero")

lsp.preset("recommended")

lsp.ensure_installed({
  'tsserver',
  'rust_analyzer',
})

-- Fix Undefined global 'vim'
lsp.nvim_workspace()


local cmp = require('cmp')
local cmp_select = {behavior = cmp.SelectBehavior.Select}
local cmp_mappings = lsp.defaults.cmp_mappings({
  ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
  ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
  ['<C-y>'] = cmp.mapping.confirm({ select = true }),
  ["<C-Space>"] = cmp.mapping.complete(),
})

cmp_mappings['<Tab>'] = nil
cmp_mappings['<S-Tab>'] = nil

lsp.setup_nvim_cmp({
  mapping = cmp_mappings
})

lsp.set_preferences({
    suggest_lsp_servers = false,
    sign_icons = {
        error = 'E',
        warn = 'W',
        hint = 'H',
        info = 'I'
    }
})

lsp.on_attach(function(client, bufnr)
  local opts = {buffer = bufnr, remap = false}

  vim.keymap.set("n", "gd", function() vim.lsp.buf.definition() end, opts)
  vim.keymap.set("n", "K", function() vim.lsp.buf.hover() end, opts)
  vim.keymap.set("n", "<leader>vws", function() vim.lsp.buf.workspace_symbol() end, opts)
  vim.keymap.set("n", "<leader>vd", function() vim.diagnostic.open_float() end, opts)
  vim.keymap.set("n", "[d", function() vim.diagnostic.goto_next() end, opts)
  vim.keymap.set("n", "]d", function() vim.diagnostic.goto_prev() end, opts)
  vim.keymap.set("n", "<leader>vca", function() vim.lsp.buf.code_action() end, opts)
  vim.keymap.set("n", "<leader>vrr", function() vim.lsp.buf.references() end, opts)
  vim.keymap.set("n", "<leader>vrn", function() vim.lsp.buf.rename() end, opts)
  vim.keymap.set("i", "<C-h>", function() vim.lsp.buf.signature_help() end, opts)
end)

lsp.setup()

vim.diagnostic.config({
    virtual_text = true
})
```

### LSP log

i cannot find my log file

**Comment by glepnir** [comment]
Can't reproduce . you should test with min config which provide by lspconfig  https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua.

**Comment by joshuaautawi** [comment]
pyhon, go , cland lsp is fine. I only have problem in rust_analyzer

**Comment by glepnir** [comment]
it works fine on my local .so please test with min config which provide by lspconfig .

**Comment by joshuaautawi** [comment]
my bad , your recommendation works. Thank you for the replies and sorry for bothering you for this noob question
peace

**Comment by renxzen** [comment]
facing the same issue but minimal config does not solve it
