### ISSUE TITLE
Rome LSP lag with large number of files

### ISSUE THREAD

**Issue by maximyurevich** [neovim/nvim-lspconfig#2591]
### Description

Rome LSP lag with large number of JavaScript files

### Neovim version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Arch Linux

### Affected language servers

rome

### Steps to reproduce

```lua
lspconfig.rome.setup({
on_attach = on_attach,
capabilities = capabilities,
root_dir = lspconfig.util.root_pattern("rome.json"),
single_file_support = true,
})
```

### Actual behavior

Lag on input code

### Minimal config

```Lua
lspconfig.rome.setup({
on_attach = on_attach,
capabilities = capabilities,
root_dir = lspconfig.util.root_pattern("rome.json"),
single_file_support = true,
})
```

### LSP log

.

**Comment by glepnir** [comment]
did you report it in server side.  i don't think it's lspconfig issue

**Comment by folke** [comment]
This is due to the new watcher code on nightly. Disable it with:

```lua
  require("vim.lsp._watchfiles")._watchfunc = function()
    return function() end
  end
```
