### ISSUE TITLE
Nushell LSP server

### ISSUE THREAD

**Issue by danielfalk** [neovim/nvim-lspconfig#2592]
### Language server

nushell-lsp-server

### Requested feature

Nushell recently created their own lsp server: https://github.com/nushell/vscode-nushell-lang

### Other clients which have this feature

No Vim implementation only VSCode

**Comment by glepnir** [comment]
I don't think it can be port to neovim unless they make it like a single language server

**Comment by danielfalk** [comment]
Is it not a single language server? (Apologies, I'm not well versed so I'm not sure what's required)

I see this: https://github.com/nushell/vscode-nushell-lang/tree/main/server and it seems to have its own package.json

What do they need additionally?  Some sort of way of calling it from the command line?  Anything you could do to point me in the right direction here would be appreciated.

**Comment by glepnir** [comment]
it bind with vscode extensions so .. I am not sure this can work . no test.

```lua
lspconfig.null_shell_ls.setup({
 cmd = {'nushell-lsp-server', '--stdio'},
 filetypes= { 'nushell' },
 root_dir = util.find_git_ancestor,
}

**Comment by danielfalk** [comment]
Got it.  Thanks.  So this would be possible if this issue were resolved: https://github.com/nushell/vscode-nushell-lang/issues/117

**Comment by KFearsoff** [comment]
Apparently, the plugin in question is a thin wrapper around Nushell that calls the binary with a `--ide-blah` parameter (the result is a JSON). This itself is not a valid LSP server, but it provides LSP info; maybe it is enough to provide a good experience in Neovim already?
https://github.com/nushell/vscode-nushell-lang/issues/117#issuecomment-1712674843

**Comment by felschr** [comment]
Can we reopen this issue?
nushell just merged a PR for native LSP support: https://github.com/nushell/nushell/pull/10723

It can be used with `nu --lsp`.
