### ISSUE TITLE
Windows installation scripts

### ISSUE THREAD

**Issue by norcalli** [neovim/nvim-lspconfig#26]
I want to add support for auto windows installation, but I'm not exactly sure what the existing procedure is for most of the servers.

The basic neovim installation procedure is that we provide a directory on `stdpath("cache")/nvim_lsp/$server` where you can download files and put binaries that can be used from the `setup()` function if it is installed. This means that all installation should be **local installations**.

Therefore, I would like to collect some examples of how people install things on windows and how it could be done with this kind of procedure, and what kind of utilities we would need to provide to make this ergonomic. **Privilege escalation should not be required.**

**Comment by mjlbach** [comment]
Closed by #498
