### ISSUE TITLE
Single server instance versus Multi server instance for workspace / root_dir

### ISSUE THREAD

**Issue by asmodeus812** [neovim/nvim-lspconfig#2607]
### Language server

lua_ls, clangd

### Requested feature

Hello, i am having a difficult time understanding what is going on with nvim lsp config, **I am using a single neovim instance**, and I have two test configurations one for clangd and one for lua_ls, now when i visit two distinct root / workspace directories for clangd, nvim-lspconfig starts two clangd instances for each workspace, which is okay BUT if i do the same with lua_ls then only a single instance is started for the first visited workspace, **the workspace_folders table for the client  is correctly populated with both workspaces**, and when changing buffers attached between both workspaces **LspInfo does correctly determine the root_dir**. But the new workspace in a way becomes a child of the original (whichever was visited and triggered lua_ls to start first), which is not good, see below.

**However, this is incredibly confusing and inconsistent, several problems with that:**
- if you want to grab the current working directory, you can't ? The property of client.config.root_dir contains the flat string workspace directory of the first workspace, the only table that has information for the other workspace is the workspace_folders ?
- if you want to initialize each workspace with different settings per workspace, that is also not going to work, for single instance language servers like that you would have to send didChangeConfig each time you change between the two working directories to notify the server ?
- probably even more issues arise from this inconsistency that i can't think of right now  !

There is no clear way that i see from the docs that determine when/why multiple instances will be started or only a single one, what gives ? Why is that the case ? **The most important issue is inconsistency here, IMO, there is no easy way to handle both cases in a more general way, i would argue.** 

So the requested feature here would be to somehow allow us to choose then to use single instance and when not to, per workspace if that is not a feature at the moment, what are the drawbacks here ? Why would certain servers work like that out of the box and others wont ?

EDIT: Having looked at the util.lua file, on line 352, i might have some idea when this is decided actually, which means for servers not supporting workspaces then it just makes a new instance, still what about properly setting up settings per workspace folder for example in that case ? What about getting the current "active" workspace from the client attached to the current buffer (client.config.root_dir is, after server has started already resolved to string)

Thanks !

**Comment by glepnir** [comment]
Neovim does not have the same workspace concept as vscode. When there is new project root. We assume this is a new workspace. for language servers. If it supports workspaceFolder, it will not start a new instance and use the existing instance and then send `didChagneWorksapceFolders` . `clangd` doesn't support that so you see two instances. `lua_ls `supports so only one instance. You should check the lua_ls wiki for instructions on how `lua_ls` works in multiple workspaces.

and what you mean `didchangeconfig` ？ I think you mean `workspace.didChangeConfiguration`? this is work for like user change vscode settings in vscode.

**Comment by asmodeus812** [comment]
No one, ever mentioned vscode, not once. I don't care about vscode, i care about having consistent coherent behavior, what we have now is something not working as expected at best, and possibly half broken at worst, i don't know why you want to close this so fast without having a proper discussion.

**I think you misunderstand the problem here, as the behavior you described, is hidden from the user**, and as i added above in my first post, yes it is obvious if you start digging in the code that you use workspaceFolder if it the server supports it, but that is still not correct.

For example, if i have a plugin that i am developing in lua and i open its root directory, root_dir will resolve to the root of that plugin (okay), and then open files from another 5 plugins it will now add these secondary plugins in as a workspaceFolder, now if you query the client.config.root_dir, guess what you will find, guess what config.settings points at ? What if each of those plugins have separate set of local settings, what if i start opening lua projects (e.g not neovim plugins) we might need completely different set of local settings for ?

**So at the moment lspconfig does provide only the ability to attach a workspace folder if the language server supports it, but it's done so silently** and the only way to opt out is to manually force it from serverCapabilities, and to actually know to do that. **But we have no way of detecting and updating the local settings with workspace.didChangeConfiguration when the workspace scope that is currently worked on (i.e active buffer's root_dir) changes for the workspaces we have attached, even more issues, there is something called workspace.fileOperations, at the moment they are only resolved for the initial root_dir with which the server is started !**

**Not to mention this has nothing to do with lua_ls specifically** this behavior will be the same across all servers which work with workspaceFolders so the issue is on a much larger scale.

**Comment by glepnir** [comment]
If you haven't used it. It is recommended that you compare the behavior with vscode. lsp was originally designed only for vscode? Many issue reports are comparing the behavior in vscode. The display of lspinfo is not accurate I am modifying it. To reiterate that for the server to support workspaceFolder we chose to reuse the server. I don't think there's anything wrong with that. This is consistent with vscode behavior. The problem is that we don't create a workspace as shown in vscode. Maybe provide a command or something. Allows to manually start a separate server for the project. I work with a lua_ls every day in several plugins and I don't see a problem.
