### ISSUE TITLE
`terraform-ls`: [LSP] Format request failed, no matching language servers. 

### ISSUE THREAD

**Issue by shalomb** [neovim/nvim-lspconfig#2613]
### Description

I believe this is a regression as of df58d91c9351a9dc5be6cf8d54f49ab0d9a64e73 and all was working fine in 79982ef99377aede4b7508ac71b05c12b6c4613a.

In `*.tf` files, LSP formatting appears to have broken recently.

```
:set tf
  filetype=terraform

:lua vim.lsp.buf.format()
[LSP] Format request failed, no matching language servers.
```

I have a feeling `terraform-ls` is being launched in the wrong directory.

Working: 79982ef99377aede4b7508ac71b05c12b6c4613a
```
$ ps aux | grep -i terraform-ls
sb      781544  1.2  1.1 802440 70876 ?        Ssl  16:13   0:09 terraform-ls serve
```

Broken: df58d91c9351a9dc5be6cf8d54f49ab0d9a64e73
```
$ ps aux | grep -i terraform-ls
sb      815090  0.0  0.4 1249036 28080 ?       Ssl  16:29   0:00 /home/sb/.local/bin/terraform-ls serve
```

### Neovim version

```
:version
NVIM v0.10.0-dev-137+gf1b415b3a
Build type: Release
LuaJIT 2.1.0-beta3
```

### Nvim-lspconfig version

df58d91c9351a9dc5be6cf8d54f49ab0d9a64e73

### Operating system and version

Debian 6.1.15-1

### Affected language servers

terraform-ls

### Steps to reproduce

Deploy `nvim-lspconfig`, open any terraform file and attempt to run formatting via

```
:lua vim.lsp.buf.format()
```

### Actual behavior

Nothing happens to the buffer and an error is returned
```
[LSP] Format request failed, no matching language servers.
```

### Expected behavior

I expect a misformatted document to be formatted.

### Minimal config

```Lua
asd
```

### LSP log

asd

**Comment by shalomb** [comment]
In https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#LL89C1-L91C52

`config.cmd[1]` ends up being resolved to an instance of `terraform-ls` that exists outside of the [mason-managed bin directory](https://github.com/williamboman/mason.nvim).

```
config_cmd:  /home/unop/.local/bin/terraform-ls                     # this is definitely odd/unexpected as it isn't in line with the other language servers in  mason/bin
config_cmd:  /home/unop/.local/share/nvim/mason/bin/yaml-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/vscode-html-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/vscode-json-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/lua-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/gopls
config_cmd:  /home/unop/.local/share/nvim/mason/bin/pyright-langserver
config_cmd:  /home/unop/.local/share/nvim/mason/bin/sql-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/tflint
```

Disabling  ` /home/unop/.local/bin/terraform-ls`
```
$ chmod -v -x $(command -v terraform-ls)
mode of '/home/unop/.local/bin/terraform-ls' retained as 0644 (rw-r--r--)
```

now causes us to find and invoke `terraform-ls` from `mason/bin` 

```
config_cmd:
config_cmd:  /home/unop/.local/share/nvim/mason/bin/typescript-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/vim-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/pyright-langserver
config_cmd:  /home/unop/.local/share/nvim/mason/bin/sql-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/vscode-json-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/rust-analyzer
config_cmd:  /home/unop/.local/share/nvim/mason/bin/lua-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/ansible-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/terraform-ls                         # <-- expected
```

and now all works fine.

```
:lua vim.lsp.buf.format()
```

So what's different?  
```
$ sha1sum ~/.local/share/nvim/mason/bin/terraform-ls   ~/.local/bin/terraform-ls
644856c17d108d29eb3654475e2159dae7013bda  /home/unop/.local/share/nvim/mason/bin/terraform-ls
38599910745a7485a5ac26bd73a011539f68ebf2  /home/unop/.local/bin/terraform-ls
```

Out of date version of `terraform-ls`?

```
$ cp -a ~/.local/share/nvim/mason/bin/terraform-ls ~/.local/bin/terraform-ls

$ vi main.tf -c ':messages'
config_cmd:  /home/unop/.local/bin/terraform-ls         
config_cmd:  /home/unop/.local/share/nvim/mason/bin/yaml-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/vscode-json-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/gopls
config_cmd:  /home/unop/.local/share/nvim/mason/bin/ansible-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/pyright-langserver
config_cmd:  /home/unop/.local/share/nvim/mason/bin/sql-language-server
config_cmd:  /home/unop/.local/share/nvim/mason/bin/tflint
config_cmd:  /home/unop/.local/share/nvim/mason/bin/awk-language-server
config_cmd:  /home/unop/.local/bin/terraform-ls
...
```

And viola - seems like all is OK with the newer version!!

Seems we have an incompatibility with older versions of `terraform-ls`.

And could we not have the `vim.fn.exepath(config.cmd[1])` resolve to binaries managed by neovim/mason ? That would avoid outside/distant configuration from surprising users.

**Comment by glepnir** [comment]
First of all, I am not using mason, that is another plugin. Not much to do here. exepath returns the path to the binary. This binary is in your system path. It seems that the installation path of mason is not under the system path. So it returns the path of your other server. If you use mason. It is best not to install multiple servers.
