### ISSUE TITLE
No GitHub Releases for `v0.1.5` and `v0.1.6`

### ISSUE THREAD

**Issue by cloudlena** [neovim/nvim-lspconfig#2617]
### Requested feature

Currently, there are no GitHub releases for the latest two versions `v0.1.5` and `v0.1.6`. It would be great to have those to better understand where the project stands.

**Comment by justinmk** [comment]
> to better understand where the project stands.

How exactly? The releases have no artifacts, and the "release notes" are just copy-pasted from the git logs.

**Comment by jn64** [comment]
Currently on the [project front page](https://github.com/neovim/nvim-lspconfig), users will see in the sidebar this misleading information:

![screenshot_2023-07-07_21-48-46](https://github.com/neovim/nvim-lspconfig/assets/23169302/290fe3b8-ceaf-4e8d-aa47-678f1b26b532)

Clicking through to the [Releases](https://github.com/neovim/nvim-lspconfig/releases) page also makes it seem like v0.1.4 is the latest release.

Meanwhile on the [Tags](https://github.com/neovim/nvim-lspconfig/tags) page we can see the actual latest tag is v0.1.6.

---

So, please hide releases from the front page of the project if it is not going to be updated. The setting can be found in a cog icon on the top right here:

![screenshot_2023-07-07_21-56-50](https://github.com/neovim/nvim-lspconfig/assets/23169302/22692658-c946-43de-8cc0-32533843bdf7)


Additionally, consider removing all releases from the GitHub frontend. As you said, there are no artifacts and no unique information. Users can get the same information from the tags page (which requires no extra work other than creating git tags, unlike GitHub releases).

**Comment by justinmk** [comment]
> please hide releases from the front page of the project if it is not going to be updated. ... Additionally, consider removing all releases from the GitHub frontend

Done.
