### ISSUE TITLE
`rust_analyzer` `get_root_dir` fails assert

### ISSUE THREAD

**Issue by korken89** [neovim/nvim-lspconfig#2618]
### Description

When trying to get the root dir of the current Rust project it fails with the error:

```
E5108: Error executing lua ...ig/lua/lspconfig/server_configurations/rust_analyzer.lua:14: assertion failed!
stack traceback:
        [C]: in function 'assert'
        ...ig/lua/lspconfig/server_configurations/rust_analyzer.lua:14: in function 'get_workspace_dir'
        ...ig/lua/lspconfig/server_configurations/rust_analyzer.lua:63: in function 'get_root_dir'
        [string ":lua"]:1: in main chunk
```

Example command: `:lua print(require('lspconfig')["rust_analyzer"].get_root_dir(vim.fn.getcwd()))`

### Neovim version

NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

Arch Linux (6.3.2)

### Affected language servers

rust_analyzer

### Steps to reproduce

1. Create a random project `cargo new test-error`
2. `cd test-error`
3. `nvim src/main.rs`
4. Run `:lua print(require('lspconfig')["rust_analyzer"].get_root_dir(vim.fn.getcwd()))`

### Actual behavior

Crash

### Expected behavior

Not a crash, get the root dir printed.

### Minimal config

```Lua
???
```

### LSP log

-

**Comment by glepnir** [comment]
you can't run it in cmdline it's async must run in a coroutine
