### ISSUE TITLE
Prevent a language server from _reading_ a certain buffer / hide the buffer from the server

### ISSUE THREAD

**Issue by doronbehar** [neovim/nvim-lspconfig#2626]
### Requested feature

I am using a language server that makes Neovim unbearably slow when I edit large files with it. Unfortunately, I often edit that file, along with other files of the same filetype. I wish to make the server do read small size buffers, and give me diagnostics etc, but I don't want it to even _attempt reading_ large files at all, even if their buffers are open in the same session along with small size buffers.

I managed to disable diagnostics for such buffers, based on a [post I found here](https://neovim.discourse.group/t/how-can-i-disable-completely-diagnostics-for-a-specific-buffer/1757):

```lua
vim.api.nvim_create_autocmd('BufReadPre', {
	callback = function(t)
		if bufIsBig(t.buf) then
			vim.diagnostic.disable(t.buf)
		end
	end
})
```

But it doesn't prevent the language server from _reading_ the large file - it just hides the diagnostics. I also tried to add `autocmd BufEnter` that will run `LspStart` and `LspStop` depending on the size of the buffer, but it turned out to make my Neovim completely stuck when I switched buffers.

Essentially I wish to "hide" a buffer from a language server.

The language server I experience this issue with is [`nil`](https://github.com/oxalica/nil) but I don't think it matters in principle. I created a repository that reproduces the experience here:

https://github.com/doronbehar/nvim-issues-reproduce

**Comment by doronbehar** [comment]
Apparently the slowness is due to this issue (Thanks to `@oxalica`):

https://github.com/neovim/neovim/issues/23026

It would still be nice though to implement this feature.

**Comment by glepnir** [comment]
use `vim.lsp.buf_detach_client` on `LspAttach` autocmd

**Comment by doronbehar** [comment]
> use `vim.lsp.buf_detach_client` on `LspAttach` autocmd

Thanks for the idea @glepnir, it looks like a nit solution. But, I tried something similar:

```lua
	lsp[v].setup{
		autostart = true,
		capabilities = capabilities,
		on_attach = function(client, bufnr)
			if bufIsBig(bufnr) then
				vim.lsp.buf_detach_client(bufnr, client.id)
			end
		end,
		-- ...
	}
```

Where `v` is my language server, and I got the error upon startup (when file was big):

```
Buffer (id: 1) is not attached to client (id: 1). Cannot detach.
```

And also considering `LspAttach`, the following also failed for me:

```lua
vim.api.nvim_create_autocmd('LspAttach', {
	callback = function(t)
		if bufIsBig(t.buf) then
			vim.lsp.buf_detach_client(t.buf, t.data.client_id)
		end
	end
})
```

Where the above is based upon the docs for `LspAttach`. The error is:

```
E5113: Error while calling lua chunk: /home/doron/.config/nvim/host-specific/ZENIX.lua:45: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_get_name'
        /home/doron/.config/nvim/host-specific/ZENIX.lua:45: in function 'bufIsBig'
        /home/doron/.config/nvim/host-specific/ZENIX.lua:177: in main chunk
```

**Comment by glepnir** [comment]
error in your function `bufIsBig` . so check your function . idk what's the detail of  that function .trace in `nvim_buf_get_name` . error is `Expected Lua number.`

**Comment by doronbehar** [comment]
It's a very simple function that just gets a buffer number and returns if it's too big:

```lua
bufIsBig = function(bufnr)
	local max_filesize = 100 * 1024 -- 100 KB
	local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(bufnr))
	if ok and stats and stats.size > max_filesize then
		return true
	else
		return false
	end
end
```

By contrast, the following _does_ work:

```lua
vim.api.nvim_create_autocmd('BufReadPre', {
	callback = function(t)
		if bufIsBig(t.buf) then
			print("A big file!")
		end
	end
})
```

**Comment by glepnir** [comment]
maybe you don't need invoke `vim.loop.fs_stat` it's a io function from libuv. 
```lua
vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(opt)
    local fname = vim.api.nvim_buf_get_name(opt.buf)
    if #fname <= 0 then
      return
    end
    local size = vim.fn.getfsize(fname) / 1024
    if size >= 100 then
      vim.schedule(function()
        vim.lsp.buf_detach_client(opt.buf, opt.data.client_id)
      end)
    end
  end
})
```

**Comment by doronbehar** [comment]
This sort of works @glepnir . I still get the following error upon startup from some reason:

```
[LSP] Client with id 1 not attached to buffer 1
```

But at least according to `LspInfo` the client indeed is not connected to the large file's buffer, and indeed the performance indicates that. Your re-implementation of `bufIsBig` didn't make a difference to me.

However, regarding the original issue: The usage of the `vim.schedule` function is not something trivial to realize. Also, the fact that the client is attached to the buffer and then detached seems kind of awkward to me, and this awkwardness is observed in the error message I see. Do you think perhaps it'd have been better if `e.g` the `autostart` attribute given to `lsp[v].setup` would have accepted a function instead of boolean? This function could wrap `bufIsBig` function for example.

I appreciate your help, but I'd appreciate if this issue was kept open, and thus open for discussion.

**Comment by llllvvuu** [comment]
detach on attach floods me with notifications for some reason. not sure if there is some kinda infinite loop

**Comment by llllvvuu** [comment]
With the detach on attach method, I find go to definition creates an infinite loop of attaching and reattaching which spams with notifications

**Comment by doronbehar** [comment]
> use `vim.lsp.buf_detach_client` on `LspAttach` autocmd

Finally, I managed to do this, using the following:

```lua
vim.api.nvim_create_autocmd('LspAttach', {
	callback = function(t)
		if bufIsBig(t.buf) then
			for _,client in pairs(vim.lsp.get_active_clients({bufnr = t.buf})) do
				-- Using vim.defer_fn because when this event is fired, we are
				-- not really attached. See:
				-- https://www.reddit.com/r/neovim/comments/168u3e4/comment/jyyluyo/
				vim.defer_fn(function()
					vim.lsp.buf_detach_client(t.buf, client.id)
					print(
						"Detaching client " .. client.name .. " because buffer " ..
						vim.fn.bufname(t.buf) .. " is too big"
					)
				end, 10)
			end
		end
	end
})
```

**Comment by serranomorante** [comment]
`buf_detach_client` still takes some seconds before switching buffers.
Blocking the "FileType" event altogether is much faster.

The following seems to work but I have just tested the happy path:

```lua
vim.api.nvim_create_autocmd('BufReadPre', {
	callback = function(t)
		if bufIsBig(t.buf) then
                    vim.o.eventignore = "FileType"
                    vim.schedule(function() vim.o.eventignore = "" end)
		end
	end
})
```
