### ISSUE TITLE
Release including `lua_ls`

### ISSUE THREAD

**Issue by cloudlena** [neovim/nvim-lspconfig#2634]
### Language server

lua_ls

### Requested feature

It would be great to have a new release that includes the rename of `sumneko_lua` to `lua_ls`. That would help users of https://github.com/williamboman/mason-lspconfig.nvim and who prefer to use only released versions of plugins.

**Comment by glepnir** [comment]
duplicate #2617

**Comment by cloudlena** [comment]
> duplicate #2617

@glepnir, I don't see how these are duplicates.

- #2634 is about creating a new Git tag and GitHub release (e.g., `v0.1.7`) that includes the renaming of the Lua language server
- #2617 is about creating GitHub releases for existing Git tags `v0.1.5` and `v0.1.6`

I don't understand why either of them was closed because both are not resolved. Could you please reopen?

**Comment by glepnir** [comment]
If you're asking for a release, this is a duplicate. If you want to use a certain version use pin commit.
