### ISSUE TITLE
_mm_getcsr SSE lib error

### ISSUE THREAD

**Issue by benmaia** [neovim/nvim-lspconfig#2639]
### Description

I'm using bazel and hedron_comile_commands to generate a compile_commands.json so the clangd can work properly, and everything it's fine except the '__mm_getcsr' error that's says :
 `Use of undeclared identifier '__mm_getcsr`
 
 And I not being able of remove that error. The rest jump tp definition and lsp is working perfect.

### Neovim version

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim-Kx6rX8/neovim-0.10.0~ubuntu1+git202305282018-c48f94d1f-9b397864c/.deps/usr/include -I/build/neovim-Kx6rX8/neovim-0.10.0~ubuntu1+git202305282018-c48f94d1f-9b397864c/build/src/nvim/auto -I/build/neovim-Kx6rX8/neovim-0.10.0~ubuntu1+git202305282018-c48f94d1f-9b397864c/build/include -I/build/neovim-Kx6rX8/neovim-0.10.0~ubuntu1+git202305282018-c48f94d1f-9b397864c/build/cmake.config -I/build/neovim-Kx6rX8/neovim-0.10.0~ubuntu1+git202305282018-c48f94d1f-9b397864c/src

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Operating system and version

WSL / Ubuntu 20.04 LTS

### Affected language servers

clangd

### Steps to reproduce

Using the xmmintrin.h lib and call it inside a function, the .h itself giving uses _mm_getcst error, but it doesn't show it in CLion

### Actual behavior

In icluded file: definition of builtin function '_mm_getcsr'

### Expected behavior

no error at all

### Minimal config

```Lua
config I have its the default
```

### LSP log

.

**Comment by glepnir** [comment]
maybe relate https://github.com/clangd/clangd/issues/547 ?
