### ISSUE TITLE
ansiblels: 'URI must contain a scheme' error when trying to go-to-definition

### ISSUE THREAD

**Issue by serpro69** [neovim/nvim-lspconfig#2641]
### Description

When trying to to go definition of an ansible module (`ansible.builtin.debug` in this case) getting an error: `nvim/runtime/lua/vim/uri.lua:107: URI must contain a scheme: /home/sergio/.virtualenvs/oci/lib/python3.8/site-packages/ansible/modules/debug.py`

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

9166622781a39a829878d1fd24c174529d996838

### Operating system and version

Linux 5.10.102.1-microsoft-standard-WSL2

### Affected language servers

ansiblels

### Steps to reproduce

1. open yaml file
```yaml
---
- hosts: localhost
  tasks:
    - ansible.builtin.debug:
```
2. make sure it's detected as ansible `:set filetype=yaml.ansible`
3. go to debug module definition

### Actual behavior

```
E5108: Error executing lua .../.mount_vimE2JdyM/usr/share/nvim/runtime/lua/vim/uri.lua:107: URI must contain a scheme: /home/sergio/.virtualenvs/oci/lib/python3.8/site-packages/ansible/modules/debug.py
stack traceback:
        [C]: in function 'assert'
        .../.mount_vimE2JdyM/usr/share/nvim/runtime/lua/vim/uri.lua:107: in function 'uri_to_fname'
        .../.mount_vimE2JdyM/usr/share/nvim/runtime/lua/vim/uri.lua:128: in function 'uri_to_bufnr'
        ...vimE2JdyM/usr/share/nvim/runtime/lua/vim/lsp/tagfunc.lua:6: in function 'mk_tag_item'
        ...vimE2JdyM/usr/share/nvim/runtime/lua/vim/lsp/tagfunc.lua:25: in function 'add'
        ...vimE2JdyM/usr/share/nvim/runtime/lua/vim/lsp/tagfunc.lua:37: in function 'query_definition'
        ...vimE2JdyM/usr/share/nvim/runtime/lua/vim/lsp/tagfunc.lua:69: in function <...vimE2JdyM/usr/share/nvim/runtime/lua/vim/lsp/tagfunc.lua:66>
```

### Expected behavior

Should open the module source file

### Minimal config

```Lua
added log
```

### LSP log

https://gist.github.com/serpro69/3c59afe58f3a1d40d1c8c54d40037949

**Comment by glepnir** [comment]
that's mean server return uri data  without schema `foo://` . server issue .

ref https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#uri

**Comment by serpro69** [comment]
Thanks for the quick response @glepnir !
I can see that there's already an open issue for this in ansible-language-server repo https://github.com/neovim/nvim-lspconfig/issues/2641
