### ISSUE TITLE
vls: Client has shut down after sending a message

### ISSUE THREAD

**Issue by tami5** [neovim/nvim-lspconfig#266]
- `nvim --version`: nightly
- nvim-lsp version(commit hash): current
- `:checkhealth` result
```
## Checking language server protocol configuration
  - INFO: html: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: intelephense: configuration checked.
  - INFO: vuels: configuration checked.


```

- What language server(If the problem is related to a specific language server): Vue Language Server
- Operating system/version: Linux
- Terminal name/version:
- `$TERM`:

### How to reproduce the problem from neovim startup
- LspInstall vuels
- add `call luaeval("require'nvim_lsp'.vuels.setup{}")`
- open vue file

### Expected behaviour
Vue Language server working fine

**Comment by h-michael** [comment]
@tamibam Could you show me sample codes or project?

**Comment by lithammer** [comment]
I'm also seeing this for `bashls` and `pyls_ms`. The thing is, the language server actually starts and works just fine.

> Could you show me sample codes or project?

I can reproduce with just an empty .sh or .py file.

**Comment by tamibam** [comment]
@h-michael Hay, michael, any empty vue file will call the server and this message appere

**Comment by h-michael** [comment]
I see, I'll invest this.

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.
