### ISSUE TITLE
Add context to LTeX filetypes

### ISSUE THREAD

**Issue by usertzuiop** [neovim/nvim-lspconfig#2663]
### Language server

ltex-ls

### Requested feature

LTeX supports Context by default. Vim knows the file type context and can determine it. Please add the "context" file type to the default language server settings.
![image](https://github.com/neovim/nvim-lspconfig/assets/74067428/fc5ead10-9e35-49b1-833b-607e9e220510)
https://valentjn.github.io/ltex/supported-languages.html

**Comment by glepnir** [comment]
fixed by #2979
