### ISSUE TITLE
cmd not defined for "openedge_ls"

### ISSUE THREAD

**Issue by TechnicalDC** [neovim/nvim-lspconfig#2672]
### Description

Getting cmd not defined for "openedge_ls" error, even after setting the cmd in the lsp configuration

### Neovim version

NVIM v0.9.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Operating system and version

Windows 11

### Affected language servers

openedge_ls

### Steps to reproduce

1. Configure the lsp as per the server_configuration.md
2. open test.p in neovim

### Actual behavior

gives following error:

[lspconfig] cmd not defined for "openedge_ls". Manually set cmd in the setup {} call according to server configuration.md, see :help lspconfig-index.

### Minimal config

```Lua
return {
	"williamboman/mason.nvim",
	dependencies = {
		"williamboman/mason-lspconfig.nvim",
		'neovim/nvim-lspconfig',
	},
	config = function ()
		require("mason").setup()
		require("mason-lspconfig").setup({
			ensure_installed = { "lua_ls", "pyright", "tsserver" }
		})
		local nvim_lsp = require('lspconfig')
		local servers = {
			'openedge_ls',
		}
		local oe_jar_path = 'C:\\Users\\Dilip Chauhan\\AppData\\Local\\nvim-data\\mason\\packages\\openedge-language-server\\abl-lsp.jar'
		for _, lsp in ipairs(servers) do
			if nvim_lsp[lsp] == "openedge_ls" then
				nvim_lsp[lsp].setup {
					on_attach = on_attach,
					cmd = {
						 'java',
						 '--add-opens=java.base/java.lang=ALL-UNNAMED',
						 '--add-opens=java.base/java.math=ALL-UNNAMED',
						 '--add-opens=java.base/java.util=ALL-UNNAMED',
						 '--add-opens=java.base/java.util.concurrent=ALL-UNNAMED',
						 '--add-opens=java.base/java.net=ALL-UNNAMED',
						 '--add-opens=java.base/java.text=ALL-UNNAMED',
					},
					root_dir = root_pattern('openedge-project.json'),
					oe_jar_path = oe_jar_path,
					-- oe_jar_path = '/home/dilip/.local/share/nvim/mason/packages/openedge-language-server/abl-lsp.jar',
					dlc = '12.2:C\\Progress\\OpenEdge\\bin', -- Version number and OpenEdge root directory (colon separator)
					debug = true, -- Set to true for debug logging
					trace = false -- Set to true for trace logging (REALLY verbose)
				}
			else
				nvim_lsp[lsp].setup {
					on_attach = on_attach,
				}
			end
		end
	end
}

```

### LSP log

NA

**Comment by glepnir** [comment]
you need config it by manually read default doc 

[Language server](https://github.com/vscode-abl/vscode-abl) for Progress OpenEdge ABL.

For manual installation, download abl-lsp.jar from the [VSCode
extension](https://github.com/vscode-abl/vscode-abl/releases/latest).

Configuration

```lua
require('lspconfig').['openedge_ls'].setup {
  oe_jar_path = '/path/to/abl-lsp.jar',
  dlc = '12.2:/path/to/dlc-12.2', -- Version number and OpenEdge root directory (colon separator)
  debug = false, -- Set to true for debug logging
  trace = false -- Set to true for trace logging (REALLY verbose)
}
```

**Comment by TechnicalDC** [comment]
I have already configured it manually. its provided in the Minimal config above

**Comment by glepnir** [comment]
no any third party plugin please we provide a min config https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua

**Comment by TechnicalDC** [comment]
I have already configured it manually. its provided in the Minimal config above.
