### ISSUE TITLE
jsonls formats and writes to buffer even if it is already formatted.

### ISSUE THREAD

**Issue by adiSuper94** [neovim/nvim-lspconfig#2676]
### Description

I have setup an auto command to format files on save
`autocmd BufWritePre *.js,*.json lua vim.lsp.buf.format({async = true}`
 and I am using the `vscode-json-language-server` via `jsonls`.

Every time I save, the JSON gets formatted as expected, but it also 'reformats' a formatted file so it looks like the buffer has been edited. 

This issue get resolved when it set `async = false`, but it would be nice if i didn't have to.
Note: I tried using versions of nvim-lspconfig as old as of Jan 2022. The issue was still there.

PS: I know this is a very small issue, but thought it would be nice if it is recorded.

### Neovim version

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_TS_HAS_SET_MAX_START_DEPTH -I/usr/include/luajit-2.1 -I/usr/include -I/build/neovim-99djAy/neovim-0.10.0~ubuntu1+git202306032020-72300feec-9b397864c/.deps/usr/include -I/build/neovim-99djAy/neovim-0.10.0~ubuntu1+git202306032020-72300feec-9b397864c/build/src/nvim/auto -I/build/neovim-99djAy/neovim-0.10.0~ubuntu1+git202306032020-72300feec-9b397864c/build/include -I/build/neovim-99djAy/neovim-0.10.0~ubuntu1+git202306032020-72300feec-9b397864c/build/cmake.config -I/build/neovim-99djAy/neovim-0.10.0~ubuntu1+git202306032020-72300feec-9b397864c/src

  system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

### Nvim-lspconfig version

295c646488d5baa63c6c4da68fe61171b9257375

### Operating system and version

Ubuntu 23.04

### Affected language servers

jsonls

### Steps to reproduce

Save a formatted json file.

### Actual behavior

Formats the file even if it is already formatted, and writes to the buffer.
So the `+` icon on buffer is always there.

### Expected behavior

Formats the file if not formatted.
So maximum of two saves required (One extra because of async) 

### Minimal config

```Lua
local nvim_lsp = require'lspconfig'
nvim_lsp.jsonls.setup {}

autocmd BufWritePre *.js,*.json lua vim.lsp.buf.format({async = true}
```

### LSP log

-

**Comment by glepnir** [comment]
because it's async  when you use in `BufWritePre` . when you save file autocmd execute the format it's async so it will run when callback insert to the event loop callback queue . then vim do save file . then event loop check queue find it run it .format your buffer . modified changed so you see `+` . it work as expect. not bug.
