### ISSUE TITLE
Error messages (E5248) when editing terraform.tfvars

### ISSUE THREAD

**Issue by rgruyters** [neovim/nvim-lspconfig#2685]
### Description

I get error messages when editing Terraform tfvars (terraform.tfvars) files with Neovim.

```
E5248: Invalid character in group name
E5248: Invalid character in group name
E5248: Invalid character in group name
E5248: Invalid character in group name
...
```

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

a51892484c2002c083a8b0a9dfcefb3a569be36d

### Operating system and version

macOS 13.4

### Affected language servers

terraformls

### Steps to reproduce

1. Use a minimal.lua with just nvim-lspconfig and terraformls
2. Edit a terraform.tfvars file

### Actual behavior

E5248: Invalid character in group name
E5248: Invalid character in group name
E5248: Invalid character in group name
E5248: Invalid character in group name

### Expected behavior

issue is not there when using nvim-lspconfig version v0.1.5

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local lspconfig_path = join_paths(package_root, "test", "start", "nvim-lspconfig")

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
	vim.fn.system({ "git", "clone", "https://github.com/neovim/nvim-lspconfig", lspconfig_path })
end

vim.lsp.set_log_level("trace")
require("vim.lsp.log").set_format_func(vim.inspect)
local nvim_lsp = require("lspconfig")
local on_attach = function(_, bufnr)
	local function buf_set_option(...)
		vim.api.nvim_buf_set_option(bufnr, ...)
	end

	buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

	-- Mappings.
	local opts = { buffer = bufnr, noremap = true, silent = true }
	vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
	vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
	vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
	vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
	vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
	vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
	vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
	vim.keymap.set("n", "<space>wl", function()
		print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
	end, opts)
	vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
	vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
	vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
	vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
	vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
	vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
	vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = "terraformls"
local cmd = { "terraform-ls", "serve" } -- needed for elixirls, lua_ls, omnisharp
if not name then
	print("You have not defined a server name, please edit minimal_init.lua")
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
	print([[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]])
end

nvim_lsp[name].setup({
	cmd = cmd,
	on_attach = on_attach,
})

print(
	[[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
)
```

### LSP log

https://gist.github.com/rgruyters/aa59b929915373c981efb1c52b8a3807

**Comment by rgruyters** [comment]
I also have this issue on my Linux workstation. (same Neovim version, 0.9.1)

**Comment by glepnir** [comment]
this mean your colorscheme has wrong character in highlight group.

**Comment by glepnir** [comment]
make sure you run in a clean env. again error message only occurs when colorscheme highlight group not correct.

**Comment by rgruyters** [comment]
I have tested it by removing all related {.cache/nvim,.local/share/nvim,.local/state/nvim,.config/nvim} folders. But still the same issue. When I skip/remove lspconfig the error message isn't shown. Only when I use lspconfig.

**Comment by piedrahitapablo** [comment]
This is also mentioned on neovim/neovim#23184, and someone mentioned this change to the terraform-ls docs:

https://github.com/hashicorp/terraform-ls/pull/999/files

I've been trying to find out how to set up terraform-ls without sending those files but haven't had any luck

**Comment by piedrahitapablo** [comment]
you're right, I misread and understood that `*.tfvars` shouldn't be sent to the language server

**Comment by rgruyters** [comment]
I have tested it with by setting the filetype to "terraform" and the issue isn't there. (so the file is still being processed by terraform-ls)
Looks like it could be true about filetypes with hyphens.

**Comment by joeterlecki** [comment]
This has been an issue with me on my neovim config as well. Since terraform.tfvars is parsed and shown as terraform-vars I get the same error.

@rgruyters What did you do to configure this so the error doesn't return.? I tried editing the lsp config for the correct files but with no luck.

I have tried vanilla configs with no luck too

**Comment by rgruyters** [comment]
I have just set the filetype to terraform (`set ft=terraform`)
It doesn't matter now, because terraform.tfvars can be parsed by terraform-ls as well. Now with filetype terraform it is still being parsed by terraform-ls.

Although it would be better to parse the file by its own filetype. (in my opinion)

**Comment by amplexus** [comment]
I'm seeing the same error - Ubuntu 23.04 running nvim v0.9.1 when editing terraform files. 

I get it when editing *.tfvar files (filetype=terraform-vars) but not with *.tf files (filetype=terraform).

Above solution of setting `ft=terraform` on *.tfvars files is a workaround, but would be nice not to have to do that every time when opening these *.tfvars files.

**Comment by Takadimi** [comment]
@amplexus Wherever makes sense in your nvim config lua you can add this to override the filetype:

```lua
-- Set additional filetypes
vim.filetype.add({
  extension = {
    tfvars = "terraform"
  }
})
```

**Comment by radeksimko** [comment]
👋🏻 Terraform LS maintainer here

@amplexus @Takadimi @shusann01116

I would discourage folks from assigning `terraform` language ID with `*.tfvars` files. There is a good reason [we have two different language IDs](https://github.com/hashicorp/terraform-ls/blob/main/docs/language-clients.md#language-ids). Those different file types have very different purpose and syntax and by overriding it like that, you will most likely end up with irrelevant diagnostics, completion and other odd or unhelpful behaviours.

What may be reasonable (but still requires careful consideration) is to assign `hcl` as a language ID. That will cause it to be ignored by the Terraform LS, probably still enable syntax highlighting (which happens outside of the LS), but not misinterpreting it.
