### ISSUE TITLE
tsserver shows an error if typescript version < 4.4 and inlay hints is enabled in LSP

### ISSUE THREAD

**Issue by Zeioth** [neovim/nvim-lspconfig#2686]
### Description

tsserver shows an error if typescript version is lower than 4.4 and inlay_hint is enabled on lsp
![screenshot_2023-06-21_13-41-59_498897312](https://github.com/neovim/nvim-lspconfig/assets/3357792/c1a39272-e61a-4623-be6d-2055b45c9d14)

### Neovim version

0.9.1

### Nvim-lspconfig version

head

### Operating system and version

arch

### Affected language servers

tsserver

### Steps to reproduce

1. On LSP enable inlay hints as described here:
https://github.com/vantaboard/dotfiles-unix/commit/503c7adc209ed6365e3626349fda503244be35aa

2. Open a typescript project of version 4.3 or lower, the error will pop on opening the file.

### Actual behavior

The error is displayed

### Expected behavior

We should not show this error, as there is nothing the user can do about it.

### Minimal config

```Lua
x
```

### LSP log

x

**Comment by ndavd** [comment]
Unrelated to your issue: Thanks for providing the link to those options, I kept wondering why inlay hints weren't working on my setup

**Comment by glepnir** [comment]
if you work on a low typescript version whichi not support inlyhint.  disable inlayhint.
