### ISSUE TITLE
Go to definition error for svelte components 

### ISSUE THREAD

**Issue by jamesmcl113** [neovim/nvim-lspconfig#2687]
### Description

When trying to goto definition using "vim.lsp.buf.definition()" on a Svelte component in a JS file, I get this error:

```
Error executing vim.schedule lua callback: ...vim/HEAD-e27377e/share/nvim/runtime/lua/vim/lsp/util.lua:1207: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...vim/HEAD-e27377e/share/nvim/runtime/lua/vim/lsp/util.lua:1207: in function 'jump_to_location'
        ...HEAD-e27377e/share/nvim/runtime/lua/vim/lsp/handlers.lua:410: in function 'handler'
        ...r/neovim/HEAD-e27377e/share/nvim/runtime/lua/vim/lsp.lua:1515: in function 'cb'
        vim/_editor.lua:324: in function <vim/_editor.lua:323>
```

However, it does jump to the definition once I hit continue which is very annoying.

https://github.com/neovim/nvim-lspconfig/assets/29102582/0ffc521e-6197-41a5-8692-2b21abddf939

### Neovim version

NVIM v0.10.0-dev-551+ge27377e33-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 12.6.6

### Affected language servers

tsserver

### Steps to reproduce

1. `npm i svelte typescript-svelte-plugin`
2. Crate a jsconfig to reference the TS svelte plugin.
3. Create a JS file and svelte component and import the component.
4. Goto definition of component from the JS file. 

### Actual behavior

An error saying the cursor is out of position appears. Once continue is pressed, the definition is opened normally.

### Minimal config

```Lua
I can add this later if necessary.
```

### LSP log

N/A

**Comment by glepnir** [comment]
update your neovim version

**Comment by jamesmcl113** [comment]
I've tried the same test using the latest nightly release and I get the exact same error.
