### ISSUE TITLE
rust-analyzer doesn't work with rust files.

### ISSUE THREAD

**Issue by MubinMuhammad** [neovim/nvim-lspconfig#2695]
### Description

After I have opened a rust file this error pops up:

![20230703_19h59m48s_grim](https://github.com/neovim/nvim-lspconfig/assets/101094719/3da98e66-b327-4789-9d80-4b3d7bdba6d0)

And this is the state of my lspconfig.lua:
```lua
local on_attach = require("plugins.configs.lspconfig").on_attach
local capabilities = require("plugins.configs.lspconfig").capabilities

local lspconfig = require "lspconfig"
local servers = {"clangd", "zls", "rust-analyzer"}

for _, lsp in ipairs(servers) do
  lspconfig[lsp].setup {
    on_attach = on_attach,
    capabilities = capabilities,
  }
end
```

Thanks.

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

### Operating system and version

Linux Kernel 6.1.32-1-lts

### Affected language servers

rust-analyzer

### Steps to reproduce

Paste in the config from the description.

### Actual behavior

LSP server doesn't work.

### Minimal config

```Lua
local servers = {"rust-analyzer"}
```

### LSP log

I don't know how to get LSP log.

**Comment by jamestrew** [comment]
it's `rust_analyzer` with an underscore.
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#rust_analyzer

**Comment by MubinMuhammad** [comment]
Ok, It now works. But only with projects that has been created with 'cargo new' but just a file ending with .rs does not get analyzed. It is a problem. As people do problem solving with rust too. They don't want to create a project for it.

**Comment by glepnir** [comment]
it not support single file mode.
