### ISSUE TITLE
rust-analyzer: do not reuse server if rust-toolchain has different version

### ISSUE THREAD

**Issue by seblj** [neovim/nvim-lspconfig#2696]
### Description

The current logic for reusing the server could give some errors in rust if using a `.rust-toolchain.toml`. If one project has one version of rust, and the other project has another version, then it could report errors if it reuses the server. 

### Neovim version

NVIM v0.10.0-dev-565+g3688735c2
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

0011c435282f043a018e23393cae06ed926c3f4a

### Operating system and version

macOS 13.4.1

### Affected language servers

rust-analyzer

### Steps to reproduce

Clone this repo: https://github.com/seblj/foo

1. `nvim -u minimal_init.lua`
2. `:e foo/one/src/main.rs`
3. With for it to start the server
4. `:e foo/two/src/main.rs`
5. Wait for it to index
6. See all the errors about 

<img width="805" alt="Screenshot 2023-07-03 at 22 38 23" src="https://github.com/neovim/nvim-lspconfig/assets/5160701/bdcc5b4b-f37b-470b-868d-56a2a42ab778">

### Actual behavior

It reuses the server even though the toolchain specifies that it should have a different version. This leads to a bunch of errors.

### Expected behavior

It should not reuse the server, and instead verify the version and start a new instance if it's not the same version as the current one

VSCode seems to handle this just fine, although I am not sure how they do it.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local lspconfig_path = join_paths(package_root, "test", "start", "nvim-lspconfig")

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
	vim.fn.system({ "git", "clone", "https://github.com/neovim/nvim-lspconfig", lspconfig_path })
end

vim.lsp.set_log_level("trace")
require("vim.lsp.log").set_format_func(vim.inspect)
local nvim_lsp = require("lspconfig")
local on_attach = function(_, bufnr)
	local function buf_set_option(...)
		vim.api.nvim_buf_set_option(bufnr, ...)
	end

	buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

	-- Mappings.
	local opts = { buffer = bufnr, noremap = true, silent = true }
	vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
	vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
	vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
	vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
	vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
	vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
	vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
	vim.keymap.set("n", "<space>wl", function()
		print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
	end, opts)
	vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
	vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
	vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
	vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
	vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
	vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
	vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
end

nvim_lsp["rust_analyzer"].setup({ on_attach = on_attach })
```

### LSP log

https://gist.github.com/seblj/d675fb3078d1121b96d51e4198697170

**Comment by glepnir** [comment]
can't reproduce 

![image](https://github.com/neovim/nvim-lspconfig/assets/41671631/af6e952e-f10f-4c00-b493-8cc5504572b5)

**Comment by seblj** [comment]
Did you try the minimal config? Because the screenshot is not from minimal config

**Comment by seblj** [comment]
And it's important that you open `foo/one/src/main.rs` before `foo/two/src/main.rs`

**Comment by glepnir** [comment]
> And it's important that you open `foo/one/src/main.rs` before `foo/two/src/main.rs`

yep open one before two. my config just simple . my rust_analyzer config just

```lua
lspconfig.rust_analyzer.setup({
  on_attach = M._attach,
  settings = {
    ['rust-analyzer'] = {
      imports = {
        granularity = {
          group = 'module',
        },
        prefix = 'self',
      },
      cargo = {
        buildScripts = {
          enable = true,
        },
      },
      procMacro = {
        enable = true,
      },
    },
  },
})
```

**Comment by seblj** [comment]
Yes, but try with default rust_analyzer config. Comment out the settings you have for it

**Comment by seblj** [comment]
The problem is because the two folders are using different versions of `rust-analyzer`, because `foo/one` is using `rust-analyzer 1.70.0 (90c54180 2023-05-31)`, and `foo/two` is using `rust-analyzer 1.72.0-nightly (8084f397 2023-06-25)` because of `rust-toolchain.toml`

**Comment by glepnir** [comment]
I know your point but for min test can't reproduce.
![Untitled](https://github.com/neovim/nvim-lspconfig/assets/41671631/a6d11008-f699-4416-bc57-3a94083da3f2)

**Comment by seblj** [comment]
What is your version of rust-analyzer in the two folders? Here is mine:

<img width="596" alt="Screenshot 2023-07-04 at 10 23 39" src="https://github.com/neovim/nvim-lspconfig/assets/5160701/7fd83b97-c4f5-4924-b0a5-8cd0c2824b6d">

<img width="605" alt="Screenshot 2023-07-04 at 10 24 18" src="https://github.com/neovim/nvim-lspconfig/assets/5160701/14fb8e85-63b6-413a-a699-3a73d4f4c8ed">


https://github.com/neovim/nvim-lspconfig/assets/5160701/9f68fe1f-f712-4c79-a7c3-0aceade0f1cb

And did you also remove all the settings for `rust-analyzer` so it's only: 
`require("lspconfig")["rust_analyzer"].setup({ on_attach = on_attach })`?

**Comment by glepnir** [comment]
your version is too old. new is `07-02`

**Comment by seblj** [comment]
Can you please navigate to the two directories and say what the version of rust-analyzer is in those two directories?

I suspect that you have default rust nightly on or something, and the the nightly rust-analyzer will attach to both buffers, and then the issue will go away. However, I don't think that is expected, as it might add other issues

**Comment by glepnir** [comment]
just use package management install `rust-analyzer`  . my default of rust is `stable`  for check version both in stable. 

check your pic . you start two rust-analyzer one in `1.70` two in `1.72` . you use component add two version rust-analyzer. 

just install one .

![image](https://github.com/neovim/nvim-lspconfig/assets/41671631/a1432378-fc2f-489d-84a3-ef8b9594bd98)

**Comment by seblj** [comment]
Alright, I can try using nightly rust-analyzer for stable project
