### ISSUE TITLE
`:LspRestart` does not start pyright after stopping it

### ISSUE THREAD

**Issue by denppa** [neovim/nvim-lspconfig#2707]
### Description

I expect `pyright` to stop and start again after passing in the command `:LspRestart`, but `pyright` remains in a stopped state after it has stopped. I have to run `:LspStart` to get it to start again.

### Neovim version

NVIM v0.9.1

### Nvim-lspconfig version

Latest

### Operating system and version

macOS Ventura

### Affected language servers

`pyright`

### Steps to reproduce

1. `:LspRestart`

### Actual behavior

`pyright` stops, but does not start back up. I waited for a few minutes.

### Minimal config

```Lua
I used astronvim, but it should be reproduceable with vanilla config too.
```

### LSP log

N/A

**Comment by NicolasGB** [comment]
I have the same problem with all the lsps i use (Gopls, rust_analyzer. lua_ls) so i would guess it happens to all lsps

**Comment by glepnir** [comment]
did you try run this command after server initialized ?

**Comment by denppa** [comment]
Thank you so much, the commit #2725 did fix the problem. Tested in astronvim.
