### ISSUE TITLE
Add support for vscode-mypy?

### ISSUE THREAD

**Issue by baggiponte** [neovim/nvim-lspconfig#2710]
### Language server

mypy

### Requested feature

Microsoft released [vscode-mypy](https://github.com/microsoft/vscode-mypy). I think it's a language server, am I right? Could it be supported?

**Comment by justinmk** [comment]
> Could it be supported?

Sure. Send a PR. https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig
