### ISSUE TITLE
Infinite loop when opening file with $ in path

### ISSUE THREAD

**Issue by stephen776** [neovim/nvim-lspconfig#2713]
### Description

When opening a .ts or .tsx file it causes nvim to hang for several seconds.

see the responses from folke here re: potential bug:

https://www.reddit.com/r/neovim/comments/14vpzdo/lazyvim_slow_to_open_tsx_file_with_in_path/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=2&utm_term=1

### Neovim version

9

### Operating system and version

macOS 11.5

### Affected language servers

tsserver

### Steps to reproduce

Open any .ts(x) with a `$` in the path or file name.

### Actual behavior

File is taking up to 10 seconds to open or save on my machine.

### Minimal config

```Lua
LazyVim default
```

### LSP log

N/a

**Comment by glepnir** [comment]
try min config for test not a preconfig

**Comment by stephen776** [comment]
> try min config for test not a preconfig

Sorry - not sure I have the knowledge of lazy.nvim to create a repro myself. Happy to provide any other info I can though.

**Comment by stephen776** [comment]
UPDATE: This fixed it for me

https://www.reddit.com/r/neovim/comments/olrtof/a_fix_for_neovim_been_slow_for_fish_users/

I switched to `fish` right when this issue popped up for me.
