### ISSUE TITLE
Feature request: Add guide how to communicate launch tcp server and connect to it

### ISSUE THREAD

**Issue by hacker-DOM** [neovim/nvim-lspconfig#2719]
### Requested feature

Hi there!

We spent a lot of time building an [Lsp server for Solidity](https://github.com/Ackee-Blockchain/woke/tree/main/woke/lsp) and now I'd like to add its configuration for Nvim users! The issue is, I can't get it to work myself.

I am editing my `server_configurations` directory directly to ensure there's no gotchas. It seems like the `default_config.cmd` function has to do something like `return vim.lsp.rpc.connect('127.0.0.1', port_num)`.

Everything works fine when I launch the lsp (`woke --debug lsp --port 65433` for example) and just connect to it. However, I cannot get it work by adding a

```lua
os.execute('woke lsp --port ' .. port_str .. ' &')
```

in the aforementioned function (the `&` at the end should presumably launch it as a background process). Are there any examples/guides how to do this? 🙂 It seems like there is just one tcp server (gdscript.lua) and that connects to an ex-ante-launched process

**Comment by justinmk** [comment]
> ```lua
> os.execute('woke lsp --port ' .. port_str .. ' &')
> ````
>   
> in the aforementioned function (the & at the end should presumably launch it as a background process).
> ```

Using `&` is a shell trick. Using os.execute plus shell tricks is fragile and platform-specific. In Nvim 0.10 you can using `vim.spawn`, in older Nvim you can use `jobstart()` to start a background process.

The title of this issue requests a "guide" for this specific thing, that's out of scope for nvim-lspconfig which is just a collection of configs.

**Comment by hacker-DOM** [comment]
Actually jobstart does work. I'll send over a PR in the coming days

**Comment by llllvvuu** [comment]
I think the tricky part is you need to await for the `jobstart`ed process to finish setting up before you launch `nc` or `vim.lsp.rpc.connect`. I don't think async is baked into nvim-lspconfig and it probably doesn't make sense to block the thread either. The most tractable way to set up such an LSP might be to do it without lspconfig, just call `vim.lsp.start()` in `ftplugin`: https://f1sty.github.io/neovim/nvim/lsp/language-server/config/dotfiles/completion/2023/09/10/simple-nvim-lsp-setup.html
