### ISSUE TITLE
RLS: configuration settings in CONFIG.md are inaccurate

### ISSUE THREAD

**Issue by nerosnm** [neovim/nvim-lspconfig#273]
For example, the [instructions for RLS](https://github.com/neovim/nvim-lsp#rls) say that the server accepts configuration via the `settings` key, and lists options in "available settings" like:

- `rust-client.engine`
- `rust.build_on_save`
- `rust.rust-analyzer`

That information would lead me to believe that this is a valid call to `nvim_lsp.rls.setup`:

```lua
nvim_lsp = require'nvim_lsp'

nvim_lsp.rls.setup {
    settings = {
        ["rust-client"] = {
            engine = "rust-analyzer",
        },
        rust = {
            build_on_save = false,
            ["rust-analyzer"] = {
                completion = {
                    addCallArgumentSnippets = false,
                    addCallParenthesis = false,
                },
            },
        },
    },
}
```

However, it looks like all of the settings that begin with `rust-client` actually don't belong inside `settings`, so the call should look like this...

```lua
nvim_lsp.rls.setup {
    ["rust-client"] = {
        engine = "rust-analyzer",
    },
    settings = {
        rust = {
            build_on_save = false,
            ["rust-analyzer"] = {
                completion = {
                    addCallArgumentSnippets = false,
                    addCallParenthesis = false,
                },
            },
        },
    },
}
```

...and nvim-lsp still complains "LSP[rls][Warning] Unknown RLS configuration: \`rust_analyzer\`" when opening a Rust file (which is a separate issue, filed as #274).

There are clearly some things that need to be fixed with the configuration instructions for this language server (and maybe others), but it looks like they're auto-generated, and I'm not really sure where to start. If anyone could point me in the general direction of what needs to change to fix this, I'm very happy to try, though.

**Comment by nerosnm** [comment]
Sorry, accidentally submitted early :) I'm editing now

**Comment by ngortheone** [comment]
I have somewhat related problem. I want to disable snippets, and I configure everything according to the docs but there is no effect. Snippets are still offered...


https://github.com/neovim/nvim-lsp/issues/276

**Comment by justinmk** [comment]
> it looks like they're auto-generated, and I'm not really sure where to start. If anyone could point me in the general direction

we pull those settings from vscode or whatever repo is set in `docs.package_json`

https://github.com/neovim/nvim-lspconfig/blob/96976f5ccf92d7f7f76926e360bbe1957bc15392/scripts/docgen.lua#L138

**Comment by mjlbach** [comment]
The main source of confusino with this, is we're passing the vscode settings automatically, when in reality these don't correspond to the settings RLS accepts, but the settings the vscode extension [here](https://github.com/rust-lang/vscode-rust/blob/master/package.json). The ["rust-client"] and ["rust-analyzer"] keys are unique to vscode.


All settings for RLS are *always* under the settings.rust and are defined [here](https://github.com/rust-lang/rls/blob/4d5e9df12b6a75d7ab48a7de060a97265ce49cee/rls/src/actions/notifications.rs#L157)

And documented [here](
(https://github.com/rust-lang/rls/blob/4d5e9df12b6a75d7ab48a7de060a97265ce49cee/rls/src/config.rs#L125-L177)

All of these settings should go under the settings key. I'll remove vscode parsing for this config and update the docs to make it more clear.

```lua
nvim_lsp.rls.setup {
    settings = {
        rust = {
            build_on_save = false,
            },
        },
    },
}
```
