### ISSUE TITLE
nvim-lspconfig shortcircuits if `on_attach` contains `vim.api.nvim_exec2` statements

### ISSUE THREAD

**Issue by jeanlucthumm** [neovim/nvim-lspconfig#2731]
### Description

If the user defined `on_attach` functions contains a `vim.api.nvim_exec2` statement (see minimum repro example below), then nvim-lspconfig will mysteriously and without error stop execution on this line and not proceed: 

https://github.com/neovim/nvim-lspconfig/blob/dd11ba7b3c8f82d51b6d4dd7d68fce2d78bf78a0/lua/lspconfig/configs.lua#L333

This is bad because the next couple of lines register the user passed `commands`:

https://github.com/neovim/nvim-lspconfig/blob/dd11ba7b3c8f82d51b6d4dd7d68fce2d78bf78a0/lua/lspconfig/configs.lua#L335-L340

So this means that the commands field is completely ignored, and this is the reason that my [rust-tools](https://github.com/simrat39/rust-tools.nvim) had none of its [commands](https://github.com/simrat39/rust-tools.nvim/blob/0cc8adab23117783a0292a0c8a2fbed1005dc645/lua/rust-tools/lsp.lua#L30) on start up (took way too long to root cause 😳)

### Neovim version

NVIM v0.9.0-dev-1319+g10baf8971
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

dd11ba7b3c8f82d51b6d4dd7d68fce2d78bf78a0

### Operating system and version

Linux main 6.4.3-zen1-2-zen #1 ZEN SMP PREEMPT_DYNAMIC Sat, 15 Jul 2023 20:18:15 +0000 x86_64 GNU/Linux

### Affected language servers

all

### Steps to reproduce

1. `nvim -u min.lua sample.rs` (need a sample rust file to trigger rust_analyzer)
2. Try `:SampleCommand`

### Actual behavior

`E492: Not an editor command: SampleCommand`

### Expected behavior

`hello world`

i.e. `SampleCommand` was defined

### Minimal config

```Lua
local opt = vim.opt
local api = vim.api
local fn = vim.fn

--- Lazy bootstrap
local lazypath = fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  vim.notify('Bootstraping lazy.nvim...')
  fn.system({
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable', -- latest stable release
    lazypath,
  })
end
opt.rtp:prepend(lazypath)

-- Problematic function
local function bad_on_attach()
  -- This statement causes SampleCommand to not be registered.
  -- Comment it out and it will regsiter
  api.nvim_exec2[[
    augroup lsp_document_highlight
    autocmd! * <buffer>
    autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
    autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
    augroup END
  ]]
end

require'lazy'.setup {
  {
    'neovim/nvim-lspconfig',
    config = function()
      local lspconfig = require'lspconfig'
      lspconfig.rust_analyzer.setup {
        on_attach = bad_on_attach,
        commands = {
          SampleCommand = {
            function()
              print('hello world')
            end,
          },
        },
      }
    end,
  },
}
```

### LSP log

see minimal lua

**Comment by sigmaSd** [comment]
nvim_exec2 takes 2 arguments not one thats why its failing

**Comment by jeanlucthumm** [comment]
Ah you're right, just tried it manually via `:lua vim.api.nvim_exec2('echo hello')`:

```
E5108: Error executing lua [string ":lua"]:1: Expected 2 arguments                                                                                                                                                   
stack traceback:                                                                                                                                                                                                     
        [C]: in function 'nvim_exec2'                                                                                                                                                                                
        [string ":lua"]:1: in main chunk  
```

But for this issue, I never got an error message. Execution just stopped silently.

**Comment by justinmk** [comment]
> I never got an error message. Execution just stopped silently.

If it's during startup, that is a Nvim core issue. Using `:messages` manually, should show the error.
