### ISSUE TITLE
ubuntu out of memory with node

### ISSUE THREAD

**Issue by muribury123** [neovim/nvim-lspconfig#2736]
### Description

Hi,

I used this plugin for long time ago, but now it's starting to give me problems.
Things that change, I only can think in the  project size that now is 200M.
I'm in Ubuntu22, but I recently change, and before I work with Ubuntu18 and 20, that has the same problem... yes, I change twice my S.O. in one year.

I started to see that when I try things like 'go to definition', it takes like a minute (when it works), and see lot of errors like 'Client n quit with exit code n and signal n' (the numbers change so I put an 'n')
And another thing I notice is that node starts to give me some problems, because ubuntu tell me to send the report.

I follow the README and install with basic configuration. Commenting code here and there I discover the line that give me problems.
I tried to look where node is launch, and without that line, node doesn't start:
`lspconfig.pyright.setup {}`
with the line node starts with:
CPU: 190,7
MEM: 13,8
(more or less)
The problem with node apparently is a resource problem, so maybe it's getting too much resources with the basic configuration.

### Neovim version

NVIM v0.10.0-dev-698+g02d859a07
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

### Operating system and version

Ubuntu22

### Affected language servers

python

### Steps to reproduce

Install plugin with Suggested configuration

### Actual behavior

It takes some minutes to 'go to definition'
node stop working

### Minimal config

```Lua
-- Setup language servers.
local lspconfig = require('lspconfig')
lspconfig.pyright.setup {}
lspconfig.tsserver.setup {}
lspconfig.rust_analyzer.setup {
  -- Server-specific settings. See `:help lspconfig-setup`
  settings = {
    ['rust-analyzer'] = {},
  },
}


-- Global mappings.
-- See `:help vim.diagnostic.*` for documentation on any of the below functions
vim.keymap.set('n', '<space>e', vim.diagnostic.open_float)
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev)
vim.keymap.set('n', ']d', vim.diagnostic.goto_next)
vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist)

-- Use LspAttach autocommand to only map the following keys
-- after the language server attaches to the current buffer
vim.api.nvim_create_autocmd('LspAttach', {
  group = vim.api.nvim_create_augroup('UserLspConfig', {}),
  callback = function(ev)
    -- Enable completion triggered by <c-x><c-o>
    vim.bo[ev.buf].omnifunc = 'v:lua.vim.lsp.omnifunc'

    -- Buffer local mappings.
    -- See `:help vim.lsp.*` for documentation on any of the below functions
    local opts = { buffer = ev.buf }
    vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
    vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
    vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
    vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
    vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
    vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
    vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
    vim.keymap.set('n', '<space>wl', function()
      print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
    end, opts)
    vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
    vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
    vim.keymap.set({ 'n', 'v' }, '<space>ca', vim.lsp.buf.code_action, opts)
    vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
    vim.keymap.set('n', '<space>f', function()
      vim.lsp.buf.format { async = true }
    end, opts)
  end,
})
```

### LSP log

[START][2023-07-26 10:00:40] LSP logging initiated [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"\n<--- Last few GCs --->\n\n[35793:0x6435f20]   706547 ms: Mark-sweep (reduce) 1869.1 (2046.0) -> 1869.1 (1992.8) MB, 2193.1 / 0.0 ms  (average mu = 0.386, current mu = 0.000) last resort; GC in old space requested\n[35793:0x6435f20]   708360 ms: Mark-sweep (reduce) 1869.1 (1992.8) -> 1869.1 (1979.8) MB, 1813.2 / 0.0 ms  (average mu = 0.250, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834  [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 7: 0xf07d2c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 8: 0xf07ea5 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 9: 0x11c2f0e v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"10: 0x11c2fc3 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 10:00:40] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"12: 0x17035b9  [/usr/bin/node]\n" [START][2023-07-26 13:44:12] LSP logging initiated [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"\n<--- Last few GCs --->\n\n[87797:0x5badf20]   353038 ms: Mark-sweep (reduce) 1862.2 (2045.5) -> 1862.2 (1990.5) MB, 995.3 / 0.0 ms  (average mu = 0.438, current mu = 0.000) last resort; GC in old space requested\n[87797:0x5badf20]   354840 ms: Mark-sweep (reduce) 1862.2 (1990.5) -> 1862.2 (1974.3) MB, 1802.1 / 0.0 ms  (average mu = 0.232, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834  [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 7: 0xf07d2c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 8: 0xf07ea5 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 9: 0x11c2f0e v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"10: 0x11c2fc3 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 13:44:12] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"12: 0x17035b9  [/usr/bin/node]\n" [START][2023-07-26 15:26:17] LSP logging initiated [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"\n<--- Last few GCs --->\n\n[95110:0x6fcdf20]   570221 ms: Scavenge (reduce) 1976.9 (2080.2) -> 1976.0 (2080.2) MB, 6.9 / 0.0 ms  (average mu = 0.346, current mu = 0.462) allocation failure; \n[95110:0x6fcdf20]   570272 ms: Scavenge (reduce) 1977.0 (2080.2) -> 1976.1 (2080.2) MB, 21.4 / 0.0 ms  (average mu = 0.346, current mu = 0.462) allocation failure; \n[95110:0x6fcdf20]   570298 ms: Scavenge (reduce) 1977.0 (2080.2) -> 1976.2 (2080.5) MB, 6.1 / 0.0 ms  (average mu = 0.346, current mu = 0.462) allocation failure; \n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834  [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf42265  [/usr/bin/node]\n 6: 0xf43168 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/usr/bin/node]\n 7: 0xf53673  [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 8: 0xf544e8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 9: 0xf2ee4e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"10: 0xf30217 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"11: 0xf113ea v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"12: 0x12d674f v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 15:26:17] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"13: 0x17035b9  [/usr/bin/node]\n" [START][2023-07-26 15:36:23] LSP logging initiated [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"\n<--- Last few GCs --->\n\n[97111:0x6bb0f20]   532971 ms: Mark-sweep (reduce) 1863.9 (2039.3) -> 1863.9 (1987.5) MB, 2504.2 / 0.0 ms  (average mu = 0.294, current mu = 0.000) last resort; GC in old space requested\n[97111:0x6bb0f20]   536481 ms: Mark-sweep (reduce) 1863.9 (1987.5) -> 1863.9 (1983.8) MB, 3509.8 / 0.0 ms  (average mu = 0.139, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834  [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n" [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n 7: 0xf07d2c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n 8: 0xf07ea5 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/bin/node]\n 9: 0x11c2f0e v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n10: 0x11c2fc3 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/bin/node]\n" [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 15:36:23] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"12: 0x17035b9  [/usr/bin/node]\n" [START][2023-07-26 16:08:31] LSP logging initiated [ERROR][2023-07-26 16:08:31] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"\n<--- Last few GCs --->\n\n[101147:0x7738f20]   363091 ms: Mark-sweep (reduce) 1862.0 (2039.0) -> 1862.0 (1986.3) MB, 1251.0 / 0.0 ms  (average mu = 0.324, current mu = 0.000) last resort; GC in old space requested\n[101147:0x7738f20]   364354 ms: Mark-sweep (reduce) 1862.0 (1986.3) -> 1862.0 (1968.8) MB, 1263.0 / 0.0 ms  (average mu = 0.199, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834  [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n 7: 0xf07d2c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n 8: 0xf07ea5 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/bin/node]\n 9: 0x11c2f0e v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n10: 0x11c2fc3 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/bin/node]\n11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 16:08:31] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"12: 0x17035b9  [/usr/bin/node]\n" [START][2023-07-26 16:27:45] LSP logging initiated [ERROR][2023-07-26 16:27:45] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"\n<--- Last few GCs --->\n\n[103641:0x5decf20]   510891 ms: Mark-sweep (reduce) 1862.1 (2041.5) -> 1862.1 (1985.3) MB, 2700.5 / 0.0 ms  (average mu = 0.315, current mu = 0.000) last resort; GC in old space requested\n[103641:0x5decf20]   513125 ms: Mark-sweep (reduce) 1862.1 (1985.3) -> 1862.1 (1971.8) MB, 2233.0 / 0.0 ms  (average mu = 0.195, current mu = 0.000) last resort; GC in old space requested\n\n\n<--- JS stacktrace --->\n\nFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory\n 1: 0xb83f50 node::Abort() [/usr/bin/node]\n 2: 0xa94834  [/usr/bin/node]\n 3: 0xd647c0 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 4: 0xd64b67 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/bin/node]\n 5: 0xf3039f v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/bin/node]\n 6: 0xf10760 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [/usr/bin/node]\n 7: 0xf07d2c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [/usr/bin/node]\n" [ERROR][2023-07-26 16:27:45] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	" 8: 0xf07ea5 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/usr/bin/node]\n 9: 0x11c2f0e v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate<v8::internal::Isolate>(v8::internal::Isolate*, int, v8::internal::AllocationType) [/usr/bin/node]\n10: 0x11c2fc3 v8::internal::MaybeHandle<v8::internal::OrderedHashMap> v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash<v8::internal::Isolate>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [/usr/bin/node]\n11: 0x12cd30d v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [/usr/bin/node]\n" [ERROR][2023-07-26 16:27:45] .../vim/lsp/rpc.lua:675	"rpc"	"/home/hugo/projects/ue/ue-dev/venv/bin/pyright-langserver"	"stderr"	"12: 0x17035b9  [/usr/bin/node]\n"

**Comment by justinmk** [comment]
> I used this plugin for long time ago, but now it's starting to give me problems.

"This plugin" is just a collection of configs. Problems with whatever LSP server are running have nothing to do with this plugin.

> Things that change, I only can think in the project size that now is 200M.

This plugin is just a collection of configs. If pyright or whatever LSP server is having problems, you need to resolve that with pyright or whatever LSP server.
