### ISSUE TITLE
Pyright stopped working with recent updates

### ISSUE THREAD

**Issue by ema2159** [neovim/nvim-lspconfig#2742]
### Description

Pyright stopped working after updating this repo to the latest version. Downgraded to 5f3167bab9892329d0f9a4205f72b33ee320fec5 and it seems to be working again.

### Neovim version

NVIM v0.10.0-dev-741+g996dd36c7
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

b6091272422bb0fbd729f7f5d17a56d37499c54f

### Operating system and version

Red Hat Enterprise Linux Server release 7.7

### Affected language servers

Pyright

### Steps to reproduce

Enable Pyright with default settings installed with Mason in any Python file.

### Actual behavior

Pyright appears to work (Lsp info shows no error and Pyright appears to be working) however, none of its functionalities work (i.e. hover, go to definition etc.).

### Minimal config

```Lua
require("lspconfig").pyright.setup({})
```

### LSP log

lsp.log empty (or not containing Pyright information rather)

**Comment by glepnir** [comment]
can't reproduce . provide more information.
