### ISSUE TITLE
Add Actions Language Server for GitHub Workflows

### ISSUE THREAD

**Issue by pbnj** [neovim/nvim-lspconfig#2748]
### Language server

actions-languageserver

### Requested feature

[Actions Language Server](https://www.npmjs.com/package/@actions/languageserver) is an LSP for GitHub Workflows, providing value-aware, context-aware, and expression-aware completion and diagnostics.

**Comment by justinmk** [comment]
https://github.com/neovim/nvim-lspconfig/issues/2737
