### ISSUE TITLE
lsp: Add preStart/postStop hooks to run custom command when start lsp

### ISSUE THREAD

**Issue by 3Xpl0it3r** [neovim/nvim-lspconfig#2749]
### Language server

golang

### Requested feature

&emsp; Is possible supplied a way to inject custom command into vim.lsp?  like 
```lua
vim.lsp.start({
   name="gopls",
   cmd= {'name-of-language-extensions'},
   root_dir=str,
   pre_start={'custom command'} or function or nil,
   post_stop = {'custom command'} or function or nil,  
})
```

**Comment by justinmk** [comment]
`:help LspAttach`, `:help LspDetach`

More generally: this repo is a collection of configs. More "features" will not be added to this repo.
