### ISSUE TITLE
Add support for postgres_lsp

### ISSUE THREAD

**Issue by llimllib** [neovim/nvim-lspconfig#2757]
### Language server

postgres_lsp

### Requested feature

[postgres_lsp](https://github.com/supabase/postgres_lsp/) is a new LSP for postgres. 

It includes [instructions on how to set it up with nvim-lspconfig](https://github.com/supabase/postgres_lsp/blob/1250f5ed14a0e86b2b7fa581214284c67b960621/README.md?plain=1#L67) already, which hopefully would help smooth the integration.

**Comment by figsoda** [comment]
#2781

**Comment by llimllib** [comment]
Thank you @figsoda !
