### ISSUE TITLE
Show capabilities summary for LSP in `:LspInfo`

### ISSUE THREAD

**Issue by jeanlucthumm** [neovim/nvim-lspconfig#2758]
### Requested feature

A common pattern of users' `on_attach` functions is to gate keymaps and functionality based on the server's capabilities, e.g.:

```lua
if client.server_capabilities.documentHighlightProvider then
  -- ...
end
```
As such, it'd be nice to have an overview of what the currently attached LSP server is capable of.

**Comment by MariaSolOs** [comment]
Given the resolution of #2932, should we just close this?
