### ISSUE TITLE
How to disable snippets in rust_analyzer

### ISSUE THREAD

**Issue by ngortheone** [neovim/nvim-lspconfig#276]
despite setting ` snippetSupport = false` snipptes are still suggested where I want just simple completion.

init.vim
```
lua <<EOF
require'nvim_lsp'.rust_analyzer.setup{
        settings={
        capabilities = {
            textDocument = {
                completion = {
                    completionItem = {
                        snippetSupport = false;                    
                     }
                }
            }
        }
    }
}

EOF
```
it feels like this lua heredoc has 0 effect on what is going on

example:
![nvim_lsp_snippet1](https://user-images.githubusercontent.com/18271144/84526131-9fd51a00-ac91-11ea-8f4a-7a92b49e1e51.png)

after pressing enter a garbage is inserted
![nvim_lsp_snippet2](https://user-images.githubusercontent.com/18271144/84526176-b8ddcb00-ac91-11ea-90be-b6ca705c9a64.png)

Please help to disable those snippets. I simply want a normal completion

**Comment by kosayoda** [comment]
This does it on my end.
```lua
require'nvim_lsp'.rust_analyzer.setup{
    capabilities = {
        textDocument = {
            completion = {
                completionItem = {
                    snippetSupport = false
                }
            }
        }
    },
}
```
Pairing it with `completion-nvim` and
```vim
let g:completion_enable_auto_paren = 1
```
gets me the parenthesis upon completion confirm back.
