### ISSUE TITLE
ASCII color codes are displayed inline for rust_analyzer

### ISSUE THREAD

**Issue by lindhe** [neovim/nvim-lspconfig#2760]
### Description

Sometimes, the error printed as ASCII color codes in the string from rust_analyzer. It makes the error very hard to read. Could this be caused by an underlying library? I had a quick look at [the trait definition I used](https://github.com/SergioBenitez/Rocket/blob/c2936fcb1e4f8f4907889b54a9e4e741a565a7d7/core/http/src/uri/fmt/uri_display.rs), and didn't find any offending color codes there.

### Neovim version

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

### Operating system and version

Ubuntu 22.04

### Affected language servers

rust_analyzer

### Steps to reproduce

1. Create the following crate:

    ```shell
    cargo new -q foo
    cd foo
    cargo add -q rocket@0.5.0-rc.3
    cat <<EOF > src/main.rs
    use rocket::UriDisplayPath;
    
    fn main() {
        println!("Hello, world!");
    }
    
    #[derive(UriDisplayPath)]
    pub enum Foo {
        Bar,
    }
    EOF
    ```

2. Optionally run `cargo check`. 
3. Open `src/main.rs` with Vim.

### Actual behavior

The same thing, just without the ASCII color codes printed. Ideally, they would be encoded into colors, but if that's hard then they should be stripped.

### Expected behavior

![Screenshot from 2023-08-11 10-51-47](https://github.com/neovim/nvim-lspconfig/assets/7773090/e6acfdf5-af0c-4032-95bb-11366ee7146d)

### Minimal config

```Lua
local on_attach = function(client, bufnr)
  -- Enable completion triggered by <c-x><c-o>
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
end

require("mason").setup()
require("mason-lspconfig").setup({
  ensure_installed = {
    "rust_analyzer",
  },
  automatic_installation = true,
})

require('lspconfig')['rust_analyzer'].setup {
    on_attach = on_attach,
}
```

### LSP log

https://gist.github.com/lindhe/07979ad869c5f19ff50728e4b7af0da0

**Comment by glepnir** [comment]
I think it's more like a rust-analyzer issue. vs code
have the same problem

**Comment by glepnir** [comment]
you can use `vim.lsp.with` to reformat the message by using regex remove these ascii color code.
