### ISSUE TITLE
add  global config option for clangd not only with `compile_commands.json`

### ISSUE THREAD

**Issue by cxwx** [neovim/nvim-lspconfig#2761]
### Language server

clangd

### Requested feature

like ycmd, I could set include and other options in `.ycm_extra_conf.py` like this
```
flag=[
    '-isystem',
    '/opt/homebrew/include/root/',
    '-isystem',
    '/opt/homebrew/include',
    '-isystem',
    '/opt/homebrew/include/Geant4/',
    '-isystem',
    '/opt/homebrew/include/star/',
]
```
Is there some method to do this?

I've try to modify ~/.config/clangd/config.yaml as metioned in `https://clangd.llvm.org/config`
but not works

### Other clients which have this feature

yaml
ale

**Comment by justinmk** [comment]
> I've try to modify ~/.config/clangd/config.yaml as metioned in `https://clangd.llvm.org/config` but not works

That's up to clangd, what does that have to do with this repo?
