### ISSUE TITLE
List of references is duplicated for pyright

### ISSUE THREAD

**Issue by carschandler** [neovim/nvim-lspconfig#2765]
### Description

Using `:lua vim.lsp.buf.references()` in a python file with pyright connected produces 2 entries for each reference in the quickfix list. For example:

```
pyfrontal.py|338 col 9| moments = cv.moments(contour[0])
pyfrontal.py|338 col 9| moments = cv.moments(contour[0])
pyfrontal.py|346 col 23| mu_prime_20 = moments["mu20"] / px_area
pyfrontal.py|346 col 23| mu_prime_20 = moments["mu20"] / px_area
pyfrontal.py|347 col 23| mu_prime_02 = moments["mu02"] / px_area
pyfrontal.py|347 col 23| mu_prime_02 = moments["mu02"] / px_area
pyfrontal.py|348 col 23| mu_prime_11 = moments["mu11"] / px_area
pyfrontal.py|348 col 23| mu_prime_11 = moments["mu11"] / px_area
pyfrontal.py|379 col 20| xbar = int(moments["m10"] / px_area)
pyfrontal.py|379 col 20| xbar = int(moments["m10"] / px_area)
```

Only having this issue with pyright. Other language servers are fine.

### Neovim version

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/5ksh5vbvdgy0vs2d4p32qlmxg3vbmfld-neovim-unwrapped-0.9.1/share/nvim
"
```

### Nvim-lspconfig version

0d29cad8de3b2c654315203fc1fe12fde722a18a

### Operating system and version

Arch Linux

### Affected language servers

pyright

### Steps to reproduce

1. `nvim file.py`
2. Place cursor onto an appropriate symbol
3. `:lua vim.lsp.buf.references()`
4. QFL is opened with the duplicate references

### Actual behavior

QuickFix List is opened with two entries per reference

### Expected behavior

QuickFix List is opened with a single entry per reference

### Minimal config

```Lua
return {
  {
    'neovim/nvim-lspconfig',

    config = function()

      local lspconfig = require('lspconfig')

      vim.api.nvim_create_autocmd('LspAttach', {
        group = vim.api.nvim_create_augroup('UserLspConfig', {}),
        callback = function(ev)
          local opts_desc = function(d)
            return { buffer = ev.buf, desc = d }
          end

          vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts_desc('Go to references'))
        end,
      })

      lspconfig.pyright.setup {}

      vim.lsp.set_log_level('debug')
    end
  }
}
```

### LSP log
See lines 57-64 of the log for the references request... you can search for each line number in the result and find the duplicates.

https://gist.github.com/carschandler/cadbbdfdf709eb20ee37e535d3e6c69f

**Comment by carschandler** [comment]
So I have discovered that this is only occurring with one file in one of my projects... I’ll try to diagnose why it's only happening with that one.

**Comment by carschandler** [comment]
I figured out that this is only happening for symbols that are defined inside of functions... happening in both root-directory mode and single-file mode. A minimal example would be:
```python
def main():
    msg_dup = "hello"
    print(msg_dup)

msg_normal = "bye"
print(msg_normal)
```

Invoking `vim.lsp.buf.references()` on `msg_normal` yields:
![image](https://github.com/neovim/nvim-lspconfig/assets/92899389/73f1b6de-0189-4eef-9133-6d7eeeba1d77)

while doing the same on `msg_dup` yields:
![image](https://github.com/neovim/nvim-lspconfig/assets/92899389/8d6c7f6d-b619-4a62-9732-2c41d05b434a)

**Comment by carschandler** [comment]
I also confirmed that this is not happening with Pyright when using Doom Emacs or VSCode

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by stvhuang** [comment]
HI @carschandler, I also met this issue. Do you have any solution?

**Comment by carschandler** [comment]
@stvhuang glad to see it's not just me! I don't have a solution yet. I've been meaning to do some more troubleshooting to determine what exactly is responsible for this, but haven't had the time yet. I’ll post an update here when I do.

**Comment by stvhuang** [comment]
@carschandler Got it! I will also try to troubleshoot it.

**Comment by rickboks** [comment]
I'm also experiencing this issue. Will try to investigate when I get the chance.

**Comment by carschandler** [comment]
@stvhuang @rickboks check the issue I opened on the pyright repo here https://github.com/microsoft/pyright/issues/6666. It seems that this is a pyright issue and that VS Code just happens to be de-duplicating them on its own!
