### ISSUE TITLE
configurtion for java_language_server not works.

### ISSUE THREAD

**Issue by yimingwangdell** [neovim/nvim-lspconfig#2773]
### Description

https://stackoverflow.com/questions/76944249/how-to-specify-classpath-with-java-language-server-of-neovim

I tried add classpath to ~/.config/Code/User/settings.json  , $PROJ/.vscode/settings.json  as doc described, also tried CLASSPATH variable with .jar path.
none of them works for me, any ideas to make it works?

### Neovim version

NVIM v0.10.0-dev-835+gdd09630a2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Run "nvim -V1 -v" for more info

### Nvim-lspconfig version

latest

### Operating system and version

linux

### Affected language servers

java_language_server

### Steps to reproduce

return {
	setup = function(lspconfig, lsp)
		lspconfig.java_language_server.setup {}
	end
}

### Actual behavior

all packages were not found by lsp

### Expected behavior

all packages were found by lsp

### Minimal config

```Lua
return {
	setup = function(lspconfig, lsp)
		lspconfig.java_language_server.setup {}
	end
}
```

### LSP log

https://gist.github.com

**Comment by glepnir** [comment]
server name is jdtls there is no java_language_server

**Comment by yimingwangdell** [comment]
@glepnir that's not correct 
![image](https://github.com/neovim/nvim-lspconfig/assets/121928908/35f27aed-19ba-48a7-87ae-2fd1ac319f0d)

actually I tries jdtls days ago, it totally not works for my side.
https://github.com/eclipse-jdtls/eclipse.jdt.ls/issues/2798

**Comment by yimingwangdell** [comment]
@glepnir please consider reopening this issue.

**Comment by glepnir** [comment]
oh sry there has java-language-server. but the mostly used is jdtls.

**Comment by glepnir** [comment]
relate #2769 ? I think this issue duplicated ?

**Comment by yimingwangdell** [comment]
@glepnir I am not sure if that issue is the same as mine, in that issue, it's not mentioned whether packages are recognized correctly. Also I notice java runtime packages are found correctly, I can see class methods with "K" with "show document" key binding, so it seems lsp is running correctly but just a misconfiguration of java_language_server.

**Comment by justinmk** [comment]
The configs in this repo are provided as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- a failing test case added to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
