### ISSUE TITLE
Recent commit stops LSP servers / LSP wont load properly.

### ISSUE THREAD

**Issue by npotts** [neovim/nvim-lspconfig#2798]
### Description

Starting with https://github.com/neovim/nvim-lspconfig/commit/204f08ea407e4b3b7ad272287e1821f47e52d4b3, any time I start `nvim`, I get a cryptic error (below), and it looks like none of the LSP servers are retained, and I must re-run `LspInstall gopls` on each restart.

Im not familiar with Lua, but it looks like something isnt being loaded properly during the config setup.  From what I have seen from my cobbled-together configuration, I might not be initilizing things properly, but rolling back to the previous commit everything works as expected.

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Operating system and version

macOS 12.6.5

### Affected language servers

all

### Steps to reproduce

1. Checkout any version past `204f08ea407e4b3b7ad272287e1821f47e52d4b3`
2. Start nvim, get cryptic message (shown below).

### Actual behavior

Get a cryptic error like 
<img width="1022" alt="image" src="https://github.com/neovim/nvim-lspconfig/assets/5854162/d2f45ff2-f5dd-420b-889a-0d0d3dfe0e44">

### Expected behavior

LSPConfig to load "properly" without an error.

### Minimal config

```Lua
Im not entirely sure how to use the minimal config.

What I am using might be causing problems, but I will have to upload it.
```

### LSP log

https://gist.github.com/npotts/5e74e5db0f86784900023f234768d09e

**Comment by tobsto** [comment]
I have the same problem

**Comment by glepnir** [comment]
check your plugin . ohter plugin use old api from lspconfig I guess.

**Comment by tobsto** [comment]
On my side I suspect that it is connected to me using outdated (unmaintained) plugins lsp-installer and packer. I am currently migrating.
