### ISSUE TITLE
Mojo language server configuration

### ISSUE THREAD

**Issue by KatieUmbra** [neovim/nvim-lspconfig#2799]
### Language server

mojo

### Requested feature

Modular/Mojo just enabled users to use the mojo language inside their machine alongside a vscode extension with the language server implementation, There should be a configuration template for mojo.

[mojo](https://www.modular.com/mojo)
[extension](https://marketplace.visualstudio.com/items?itemName=modular-mojotools.vscode-mojo)

### Other clients which have this feature

None

**Comment by llllvvuu** [comment]
The Mojo LSP is easy to run (command is just `mojo-lsp-server`), the problem is that it doesn't work: https://github.com/modularml/mojo/issues/672
