### ISSUE TITLE
Eslint: invalid code action ranges when using vim-sleuth

### ISSUE THREAD

**Issue by icholy** [neovim/nvim-lspconfig#2800]
### Description

When using [vim-sleuth](https://github.com/tpope/vim-sleuth), the code actions regularly have incorrect ranges. I've attempted to reproduce this by manually configuring the values vim-sleuth is setting, but that doesn't work. In the following example, the code-action deletes the first 3 characters of the `console.log` statement.

![tty](https://github.com/neovim/nvim-lspconfig/assets/943597/7ec6e77b-3dd9-44f5-8892-2c8b57a54bb3)

The number it's off by is always equal to the configured tabstop value. Looking at the `textDocument/didChange` event, instead of sending a single TAB character, it's sending N single space changes where N=tabstop.

Example:

``` json
{
  "jsonrpc": "2.0",
  "method": "textDocument/didChange",
  "params": {
    "contentChanges": [
      {
        "range": {
          "end": { "character": 0, "line": 1 },
          "start": { "character": 0, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      },
      {
        "range": {
          "end": { "character": 1, "line": 1 },
          "start": { "character": 1, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      },
      {
        "range": {
          "end": { "character": 2, "line": 1 },
          "start": { "character": 2, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      },
      {
        "range": {
          "end": { "character": 3, "line": 1 },
          "start": { "character": 3, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      },
      {
        "range": {
          "end": { "character": 4, "line": 1 },
          "start": { "character": 4, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      },
      {
        "range": {
          "end": { "character": 5, "line": 1 },
          "start": { "character": 5, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      },
      {
        "range": {
          "end": { "character": 6, "line": 1 },
          "start": { "character": 6, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      },
      {
        "range": {
          "end": { "character": 7, "line": 1 },
          "start": { "character": 7, "line": 1 }
        },
        "rangeLength": 0,
        "text": " "
      }
    ],
    "textDocument": {
      "uri": "file:///home/icholy/src/github.com/icholy/quickfixbug/main.js",
      "version": 11
    }
  }
}
```

### Neovim version

NVIM v0.10.0-dev
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

d177ad277a638f262edb73c75ffe33e377b95dc5

### Operating system and version

Ubuntu

### Affected language servers

vscode-langservers-extracted

### Steps to reproduce

Repo: https://github.com/icholy/quickfixbug

* Clone repo: `git clone https://github.com/icholy/quickfixbug.git`
* Install language server: `npm i -g vscode-langservers-extracted`.
* Install npm dependencies: `npm i`.
* Open source file`vim main.js`
* Insert tab on second line. `ji<TAB><ESC>`.
* Run `:EslintFixAll`.

### Actual behavior

After indenting the line, eslint diagnostic is still there and applying the code-action to fix it, deletes part of the code.

### Expected behavior

After indenting the line, eslint diagnostic goes away.

### Minimal config

```Lua
vim.o.expandtab = true

vim.cmd.packadd("packer.nvim")

require("packer").startup(function(use)
  use("wbthomason/packer.nvim")
  use("tpope/vim-sleuth")
  use({
    "neovim/nvim-lspconfig",
    config = function()
      require("lspconfig").eslint.setup({})
    end
  })
end)
```

### LSP log

https://gist.github.com/icholy/03a8b07bc4959bc85876608ea8bd36db

**Comment by icholy** [comment]
Setting `flags.allow_incremental_sync = false` make the issue go away.

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by icholy** [comment]
Related: https://github.com/neovim/neovim/pull/25125
