### ISSUE TITLE
Dynamic registration of formatting capabilities

### ISSUE THREAD

**Issue by chrisgrieser** [neovim/nvim-lspconfig#2807]
### Language server

biome (formerly rome)

### Requested feature

Currently, `vim.lsp.buf.format()` is not working for the `biome` (formerly rome) LSP. However, upon inquiry at the biome repo, I've been told [that the biome LSP is indeed capable of formatting, if dynamically registered](https://github.com/biomejs/biome/discussions/87).

I somewhat lack the knowledge about how LSPs work, but it looks to me like it is only specific form of configuration that is missing to enable that?

**Comment by justinmk** [comment]
did you try Nvim 0.10 ([unreleased](https://github.com/neovim/neovim/releases/tag/nightly)) ? It has https://github.com/neovim/neovim/pull/23681

**Comment by chrisgrieser** [comment]
haven't tried it myself yet, but according to others,[it does indeed work with nvim 0.10](https://github.com/biomejs/biome/discussions/87#discussioncomment-7081344). So this matter can be considered resolved I guess.
