### ISSUE TITLE
Root dir nil value

### ISSUE THREAD

**Issue by coffebar** [neovim/nvim-lspconfig#2811]
### Description

```:LspInfo```

I got this error with bashls LSP. I think we need to add nil check for `root_dir` at line 140

```
Error executing Lua callback: ...re/nvim/lazy/nvim-lspconfig/lua/lspconfig/ui/lspinfo.
lua:141: attempt to index local 'root_dir' (a nil value)
stack traceback:
        ...re/nvim/lazy/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:141: in function '
make_client_info'
        ...re/nvim/lazy/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:248: in function <
...re/nvim/lazy/nvim-lspconfig/lua/lspconfig/ui/lspinfo.lua:187>
        ...ocal/share/nvim/lazy/nvim-lspconfig/plugin/lspconfig.lua:64: in function <.
..ocal/share/nvim/lazy/nvim-lspconfig/plugin/lspconfig.lua:63>
```

### Neovim version

version doesn't matter 

### Operating system and version

Linux

### Affected language servers

bashls

### Steps to reproduce

-

### Actual behavior

Error

### Minimal config

```Lua
-
```

### LSP log

-

**Comment by justinmk** [comment]
> I think we need to add nil check for `root_dir` at line 140

PR welcome
