### ISSUE TITLE
Make `root_files` configurable

### ISSUE THREAD

**Issue by musjj** [neovim/nvim-lspconfig#2819]
### Requested feature

It'd be nice if we can configure the `root_files` of LSP servers via `.setup()`:

https://github.com/neovim/nvim-lspconfig/blob/f3195835c0447ee2c80152b893ab51ca162b04a9/lua/lspconfig/server_configurations/lua_ls.lua#L3-L11

It might be a tricky to implement though, since we need to make sure that the `root_dir` function refers to the same table when it was defined. Any ideas?

**Comment by glepnir** [comment]
We encourage users to gradually use `vim.lsp.start`. although it may be necessary to manually handle the trouble of starting, re-using and stopping the server now. But we will add more support in the core. lspconfig is currently only a repo collected as server configuration. More features and suggestions may not be considered. Sorry.

**Comment by musjj** [comment]
Welp, tried to make a PR to improve the root detection for `lua_ls` and it's also rejected: https://github.com/neovim/nvim-lspconfig/pull/2820

I am not sure what a user should even do here. Are they expected to copy-paste the entire file to their config just to add 10 chars? If `lspconfig` is just a "a repo collected as server configuration", then why not remove `.setup()` altogether and just make everything static and unconfigurable?

This overall situation has been really frustrating. Apparently users are expected to use `vim.lsp.start`, which makes this whole thing even more confusing. Is `lspconfig` going to be deprecated? 

Because the current feature parity between `lspconfig` and `vim.lsp.start` is not even close, and I don't really see any signs that it would change. No client re-use, no status menu, no stop/start/restart interface. 

And let's say that we now have feature parity. What will happen to `lspconfig` then? Is every user now expected to write hundreds or even thousands of lines inside their local config just to set up every single LSP client from a scratch?

I just don't see a clear path forward here.

**Comment by glepnir** [comment]
You can define your own `root_files` in the `root_dir` function. lspconfig is not deprecated. Because it can export the repo as server configuration. Pass it to `vim.lsp.start`. In the future we hope to have the unified `vim.lsp` interface take over. For example `vim.lsp.config` `vim.lsp.start`, etc.
