### ISSUE TITLE
lspinfo.lua uses vim.lsp.util._trim which no longer exists

### ISSUE THREAD

**Issue by sid-6581** [neovim/nvim-lspconfig#2823]
### Description

This line in `lspinfo.lua` now causes LspInfo to crash:

`fmt_buf_lines = vim.lsp.util._trim(fmt_buf_lines, {})`

### Neovim version

NVIM v0.10.0-dev-c4f4c7a
Build type: RelWithDebInfo
LuaJIT 2.1.1694940244

### Nvim-lspconfig version

f319583

### Operating system and version

Windows 11

### Affected language servers

all

### Steps to reproduce

On latest nightly, call `LspInfo`

### Actual behavior

Crash when trying to call `_trim`

### Expected behavior

Expect no crash

### Minimal config

```Lua
n/a
```

### LSP log

n/a

**Comment by gpanders** [comment]
Fixed by #2822.
