### ISSUE TITLE
gdscript language server is very slow

### ISSUE THREAD

**Issue by VPavliashvili** [neovim/nvim-lspconfig#2824]
### Description

I set up gdscript client according to [docs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#gdscript) and is so slow that impossible to use, I tested it with minimal config and also asked a [question](https://www.reddit.com/r/neovim/comments/16m9cvf/gdscript_lsp_painfully_slow_godot_4/) on subreddit too (where I got the suggestion to raise an issue here).

I know how much effort does it take to maintain this project which I respect and very much appreaciate and I am sorry for asking for your time regarding this issue

### Neovim version

NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958

### Nvim-lspconfig version

4266f9bb36b4fb09edd19b67d95043cf7ff88ddf

### Operating system and version

Arch Linux Kernel 6.5.3

### Affected language servers

gdscript

### Steps to reproduce

1. nvim -nu minimal_init.lua
2. going insert mode
3. typing several lines of code
4. exiting to normal mode

### Actual behavior

1. lsp scans every new symbol, character by character which takes 1-2 seconds for each one
2. in the process lsp recognizes everything as errors before finishing to scan every new symbol
3. coding process becomes very slow

### Expected behavior

just a normal fast typing experience

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
require'lspconfig'.gdscript.setup{}


local name = 'gdscript'
local cmd = vim.lsp.rpc.connect('127.0.0.1', 6005)
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
  cmd = cmd,
  on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

https://gist.github.com/VPavliashvili/9ece15008e1e3a53d73f433b00000aa5

**Comment by VPavliashvili** [comment]
Compared to sane experience,when you write 2 lines of code and you are waiting your lsp to analyze it for 1 minute is slow i guess and does not need to compare to anything after that. Or if you really want comparison, compared to all of these langauge servers  `tsserver, jsonls, lua_ls, gopls, pyright, ccls, html, omnisharp`.

I understand now that this is wrong repo for this issue to report, thanks for that information and I will be glad if you can suggest me where to report this issue further

**Comment by lithammer** [comment]
> [...] I will be glad if you can suggest me where to report this issue further

Presumably the gdscript-language-server server repo since it's a server issue.
