### ISSUE TITLE
Add `typos-vscode`

### ISSUE THREAD

**Issue by mawkler** [neovim/nvim-lspconfig#2827]
### Language server

[typos-vscode](https://github.com/tekumara/typos-vscode)

### Requested feature

[typos-vscode](https://github.com/tekumara/typos-vscode) is an LSP wrapper around [typos](https://github.com/crate-ci/typos), which is a spell checker for source code.

~It's currently made for VSC\*\*e. I'm not sure what the best way is to decouple it. I've asked in [this thread](https://github.com/crate-ci/typos/issues/263). How was this dealt with for `tsserver`? Do you just use the entire repo and not really care about the VSC\*\*de specific stuff?~

**Edit**: The language server binary is now published under [typos-vscode's releases](https://github.com/tekumara/typos-vscode/releases).

**Comment by mehalter** [comment]
Just a heads up, this was added in #2886
