### ISSUE TITLE
Errors during LSP config callbacks are silently discarded

### ISSUE THREAD

**Issue by A-Babin** [neovim/nvim-lspconfig#2835]
### Description

Please have a look at https://github.com/neovim/neovim/issues/25375 for backstory. 

To sum up, neovim's lsp client is `pcall`ing user config callbacks and discarding their return. Configs recommended by `nvim-lspconfig` using `on_init` assume `client.workspace_folders` is defined, but `nvim-lspconfig` removes it in single file mode. The callback throws an error attempting to index `nil`, neovim swallows it, and there is no indication whatsoever that the user's initialization failed. 

https://github.com/neovim/nvim-lspconfig/blob/68b23c06132cb1ef8d5690111c112388fbcf1c30/lua/lspconfig/manager.lua#L145-L152

Relevant config recommendations include:
https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#lua_ls
https://github.com/neovim/nvim-lspconfig/wiki/Project-local-settings
and these have been [propagated elsewhere](https://www.google.com/search?q=%22local+path+%3D+client.workspace_folders%5B1%5D.name%22&rlz=1C1RXQR_enUS939US939&oq=%22local+path+%3D+client.workspace_folders%5B1%5D.name%22&aqs=chrome..69i57j33i160l5j33i299l2.703j0j7&sourceid=chrome&ie=UTF-8). 

I would also like to point out that `nvim-lspconfig` is also using `pcall` to haphazardly silence errors. 

https://github.com/neovim/nvim-lspconfig/blob/68b23c06132cb1ef8d5690111c112388fbcf1c30/lua/lspconfig/configs.lua#L94-L96

https://github.com/neovim/nvim-lspconfig/blob/68b23c06132cb1ef8d5690111c112388fbcf1c30/lua/lspconfig/configs.lua#L197-L202

### Neovim version

NVIM v0.10.0-dev-1203+g0592fd5e1
Build type: Release
LuaJIT 2.1.1695409640

### Nvim-lspconfig version

68b23c06132cb1ef8d5690111c112388fbcf1c30

### Operating system and version

n/a

### Affected language servers

lua_ls

### Steps to reproduce

1. Build `neovim`
2. Install prebuilt `lua-language-server` 
3. Install `nvim-lspconfg`
4. Config `lua-ls` using https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#lua_ls
5. Open lua file without a workspace. 

### Actual behavior

The lsp client is starts successfully but config during `on_init` does not complete and no indication is given that there was a problem. 

### Expected behavior

Recommended `lua_ls` config should work without problems regardless of single file mode. Errors that can't be handled gracefully should never be thrown away.

### Minimal config

```Lua
require'lspconfig'.lua_ls.setup {
  on_init = function(client)
    local path = client.workspace_folders[1].name
    if not vim.loop.fs_stat(path..'/.luarc.json') and not vim.loop.fs_stat(path..'/.luarc.jsonc') then
      client.config.settings = vim.tbl_deep_extend('force', client.config.settings, {
        Lua = {
          runtime = {
            -- Tell the language server which version of Lua you're using
            -- (most likely LuaJIT in the case of Neovim)
            version = 'LuaJIT'
          },
          -- Make the server aware of Neovim runtime files
          workspace = {
            checkThirdParty = false,
            library = {
              vim.env.VIMRUNTIME
              -- "${3rd}/luv/library"
              -- "${3rd}/busted/library",
            }
            -- or pull in all of 'runtimepath'. NOTE: this is a lot slower
            -- library = vim.api.nvim_get_runtime_file("", true)
          }
        }
      })

      client.notify("workspace/didChangeConfiguration", { settings = client.config.settings })
    end
    return true
  end
}
```

### LSP log

-

**Comment by MariaSolOs** [comment]
@A-Babin since https://github.com/neovim/neovim/pull/25409 (all ?) LSP server misconfiguration errors should be displayed.

I just tried the configuration provided in this issue together with the one from https://github.com/neovim/neovim/issues/25375, and now I get an error message with quite a good stacktrace:
<img width="1512" alt="image" src="https://github.com/neovim/nvim-lspconfig/assets/62502207/1568bb41-2260-4aaf-b577-4fc0c9ac46f2">

I _personally_ consider this issue resolved then.
