### ISSUE TITLE
how to not let codes that are disabled by preprocessor be grayed out?  

### ISSUE THREAD

**Issue by step0035** [neovim/nvim-lspconfig#2854]
### Description

Using clangd
e.g

```c
#if 0
printf("hello\n");
#endif
```
how to not gray out the printf?

### Neovim version

nvim 0.9.2

### Operating system and version

ubuntu 22.04

### Affected language servers

clangd

### Steps to reproduce

define some codes inside of 

```c
#if 0
// code here
#endif

### Actual behavior

codes inside of the disabled preprocessor gets grayed out

### Expected behavior

how to configure it so as to not gray out these codes?

### Minimal config

```Lua
using default clangd
```

### LSP log

nil

**Comment by justinmk** [comment]
Try https://vi.stackexchange.com for questions about usage and configuration.
