### ISSUE TITLE
Import a class with many constructor params messes the UI up (java, spring boot)

### ISSUE THREAD

**Issue by Delice0** [neovim/nvim-lspconfig#2861]
### Description

I'm unsure if this is the right place to create this ticket but when I create a new instance of a class, and have multiple import options, and one of the options has many constructor params, the UI is totally messed up.

I have a hard time actually seeing _where_ the import is from.

![Screenshot 2023-10-14 at 00 50 08](https://github.com/neovim/nvim-lspconfig/assets/59118341/b7560bbe-72dc-4edb-9dc7-00aa64056327)

### Neovim version

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

bb8e3df

### Operating system and version

latest mac

### Affected language servers

java

### Steps to reproduce

1. create new spring boot project
2. write: new User somewhere
2. a list of import suggestions pop up and you will find the same messed up UI as I posted under description

### Actual behavior

Hard to see where it imports from

### Expected behavior

Better UI to display where it imports from. Right now, it's wrapped so much it's hard to see.

### Minimal config

```Lua
Using LazyVim if that helps otherwise this is irrelevant.
```

### LSP log

N/A

**Comment by glepnir** [comment]
hmm which command ?

**Comment by Delice0** [comment]
I don't use any commands. It's auto completion i think. The import options shows up as I type.

**Comment by glepnir** [comment]
so it's that other plugin issue. lspsaga no auto completion

**Comment by glepnir** [comment]
there is no auto completion lazy use nvim-cmp or other plugin idk then
