### ISSUE TITLE
Enable inlay hints for all servers

### ISSUE THREAD

**Issue by CWood-sdf** [neovim/nvim-lspconfig#2867]
### Requested feature

With neovim's native inlay hints api coming out in nightly builds, it would be nice if that feature could be supported for everyone using inlay hints. Currently, to enable hints, I have to go to each server's website to find out their specific configuration, with the exception of clangd and rust_analyzer, which already default to having them on.

**Comment by glepnir** [comment]
You can enable it through the api in on_attach. Not every server supports it.
