### ISSUE TITLE
Inlay hints not working in rust analyzer on_attach

### ISSUE THREAD

**Issue by SrWither** [neovim/nvim-lspconfig#2876]
### Description

I have put a function in on_attach which should activate the inlay hints, it works well in other languages, but not in rust.
 when I make a file change it is already seen

### Neovim version

NVIM v0.10.0-dev-ac353e8
Build type: RelWithDebInfo
LuaJIT 2.1.169788790

### Nvim-lspconfig version

d0467b9574b48429debf83f8248d8cee79562586

### Operating system and version

ArchLinux 6.5.9-arch2-1

### Affected language servers

rust_analyzer

### Steps to reproduce

set `vim.lsp.inlay_hint(bufnr, true)` in on_attach function

### Actual behavior

the inlay hints are not seen in rust until the file is changed
![imagen](https://github.com/neovim/nvim-lspconfig/assets/59105868/cef18dff-f88b-481a-b366-d4b0d93f3a71)

### Expected behavior

the inlay hints should be seen when loading rust analyzer
![imagen](https://github.com/neovim/nvim-lspconfig/assets/59105868/262ded6d-a204-4586-b6e9-903becc99b15)

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(client, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  if client.server_capabilities.inlayHintProvider then
        local inlay_hints_group = vim.api.nvim_create_augroup('InlayHints', { clear = true })

        -- Initial inlay hint display.
        local mode = vim.api.nvim_get_mode().mode
        vim.lsp.inlay_hint(bufnr, mode == 'n' or mode == 'v')

        vim.api.nvim_create_autocmd('InsertEnter', {
            group = inlay_hints_group,
            buffer = bufnr,
            callback = function()
                vim.lsp.inlay_hint(bufnr, true)
            end,
        })
        vim.api.nvim_create_autocmd('InsertLeave', {
            group = inlay_hints_group,
            buffer = bufnr,
            callback = function()
                -- vim.lsp.inlay_hint(bufnr, true)
            end,
        })
    end

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = 'rust_analyzer'
local cmd = { 'rust-analyzer'} -- needed for elixirls, lua_ls, omnisharp
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
  cmd = cmd,
  on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

https://gist.github.com/SrWither/d6c09b3f855539301e604a29fdb940c8

**Comment by justinmk** [comment]
Your logs suggest that Nvim enabled inlay hints and is receiving them.

The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by rikhuijzer** [comment]
For anyone coming across this issue because they want to enable inlay hints for `rust_analyzer` with Nvim and `lspconfig`, the solution is very simple on Nvim >= 0.10.

Add the following to `init.vim`:

```vim
lua << EOF
  local lspconfig = require('lspconfig')

  lspconfig.rust_analyzer.setup({
    on_attach = function(client, bufnr)
      vim.lsp.inlay_hint.enable(bufnr)
    end
  })
EOF
```
Assuming you have `neoclide/coc.nvim` with `coc-rust-analyzer` installed. By default, `rust_analyzer` has inlay hints enabled already, so this just enables inlay hints at the Neovim side.

Having to manually enable it is apparently expected behavior of `lspconfig`:

> You can enable [inlay hints] through the api in on_attach. Not every server supports it.

https://github.com/neovim/nvim-lspconfig/issues/2867#issuecomment-1763574674

**NB: You need to edit the file after `rust_analyzer` is done loading to see the hints.**

**Comment by KoushikSahu** [comment]
@rikhuijzer why is editting the file required? Is there any way around this?

**Comment by baco** [comment]
> [@rikhuijzer](https://github.com/rikhuijzer) why is editing the file required? Is there any way around this?

Exactly, why? I mean, I've noticed the same, but other LSP servers have Inlay Hints upon enabling, no need to edit the buffer whatsoever.
