### ISSUE TITLE
Auto-detected install path incorrect for LSP servers

### ISSUE THREAD

**Issue by 0xRainy** [neovim/nvim-lspconfig#289]
- `nvim --version`:  NVIM v0.5.0-574-g352831229
- nvim-lsp version(commit hash): 8e978339b57cd03d97ae301659136ce103435910
- `:checkhealth` result: Everything OK, INFO: vimls: configuration checked., no python2
- What language server(If the problem is related to a specific language server):
- Operating system/version: Win10 Build 2004
- Terminal name/version: WindowsTerminal 1.0.1401.0
- `$TERM`:

Getting this error with `:LspInstallInfo vimls` and same for jsonls
```
 {
  bin_dir = "C:\\Users\\rainy\\AppData\\Local\\Temp\\nvim\\nvim_lsp\\vimls\\node_modules\\.bin",
  binaries = {
    ["vim-language-server"] = "C:\\Users\\rainy\\AppData\\Local\\Temp\\nvim\\nvim_lsp\\vimls\\node_modules\\.bin\\vim-language-server"
  },
  install_dir = "C:\\Users\\rainy\\AppData\\Local\\Temp\\nvim\\nvim_lsp\\vimls",
  is_installed = false
} 
```
I used `npm --global` to install `vim-language-server` and it is installed to `C:\Users\rainy\AppData\Roaming\npm`

When calling `:LspInstall vimls` it says it is already installed, same for jsonls.

Also have similar issue with the other LSPs I have installed, rust/pyls
Calling `:PlugInstallInfo rls` returns
```
E5108: Error executing lua ...\.config\nvim\autoload\plugged\nvim-lsp\lua\nvim_lsp.lua:63: attempt to call field 'install_info' (a nil value)
```
but rls.exe available through my PATH, same result for pyls

Upon opening a .vim file I also get this error: 
```
Error detected while processing FileType Autocommands for "vim":
E5108: Error executing lua C:\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:268: attempt to index upvalue 'handle' (a nil value)
```
*edit - Have working config on linux, same config doesn't work on windows, getting above error still when opening .vim files

### How to reproduce the problem from neovim startup
Launch neovim on Windows
:LspInstallInfo vimls

### Actual behaviour
is_installed = false
LSP doesn't work
### Expected behaviour
is_installed = true
and the LSP works
### Notes
Also discovered that this plugin breaks some lua functions for [vim-clap](https://github.com/liuchengxu/vim-clap), specifically searching a file for text with the grep function.

**Comment by mjlbach** [comment]
Closed by #498
