### ISSUE TITLE
bug: jdtls $/progress does not display the messages correctly

### ISSUE THREAD

**Issue by s1n7ax** [neovim/nvim-lspconfig#2897]
### Description

At the moment, `1.29.0` (released on 2023-10-26 13:40) is the latest version of jdtls. Right now in lspconfig, `language/status` and `$/progress` both handled by the same `on_language_status` function.

https://github.com/neovim/nvim-lspconfig/blob/d5d7412ff267b92a11a94e6559d5507c43670a52/lua/lspconfig/server_configurations/jdtls.lua#L122-L123

However, the data sent from jdtls are different.

**language/status** 2nd parameter

```lua
{
  message = "0% Starting Java Language Server",
  type = "Starting"
}
```

**$/progress** 2nd parameter

```lua
{
  token = "38f85eca-ebcf-4c4a-8e83-7b27fd530f99",
  value = {
    kind = "report",
    message = "Initialize Workspace - 30% ",
    percentage = 30
  }
}
```

Due to this progress handler prints just `nil`.

Progress handler was added a fix to https://github.com/neovim/nvim-lspconfig/pull/2153 in Nov 21, 2022

I tested the `vim.lsp.handlers['$/progress']` handler and it works fine right now. So it's only matter of removing the handler in the config. I would like any feedback & ideas regarding removing `$/progress` handler from the jdtls config.

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1693350652

### Nvim-lspconfig version

36e4ffe

### Operating system and version

NixOS 23

### Affected language servers

jdtls

### Steps to reproduce

1. `lspconfig.jdtls.setup({})`
2. check the progress messages

### Actual behavior

`nil` being printed

### Expected behavior

progress message should be displayed correctly

### Minimal config

```Lua
-
```

### LSP log

-

**Comment by justinmk** [comment]
> Progress handler was added a fix to #2153
>
> ... I tested the `vim.lsp.handlers['$/progress']` handler and it works fine right now. So it's only matter of removing the handler in the config. I would like any feedback & ideas regarding removing `$/progress` handler from the jdtls config.

Please do. This repo should avoid custom things as much as possible.

**Comment by le4ker** [comment]
I don't get any formatting or diagnostics messages and progress from my LSPs in my [statusline](https://github.com/NvChad/ui/blob/v2.0/lua/nvchad/statusline/default.lua#L136). 

@s1n7ax @justinmk can this be related? 

On the other hand, when I format or run a linter through [none-ls](https://github.com/nvimtools/none-ls.nvim/), I get the messages.

**Comment by le4ker** [comment]
I just noticed that [taplo doesn't implement these handlers](https://github.com/neovim/nvim-lspconfig/blob/d5d7412ff267b92a11a94e6559d5507c43670a52/lua/lspconfig/server_configurations/taplo.lua), maybe that's the root cause?
