### ISSUE TITLE
Error message: Cannot access configuration for lua_ls

### ISSUE THREAD

**Issue by dominicmeyer** [neovim/nvim-lspconfig#2901]
### Description

I can't install lua_ls with lsp-zero and mason, there is always a error like below.
Sorry for some reason my logs are not filled right now, I can try later to fill this fields too, if needed.

### Neovim version

NVIM v0.9.2
Build type: MinSizeRel
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

255e07ce2a05627d482d2de77308bba51b90470c

### Operating system and version

alpine linux 3.18.4

### Affected language servers

lua_ls

### Steps to reproduce

1. Create a Dockerfile with this content:

```dockerfile
FROM alpine:3.18.4

RUN apk update && \
        apk add --no-cache curl=8.4.0-r0 git=2.40.1-r0 neovim=0.9.2-r0 g++=12.2.1_git20220924-r10 \ 
          nodejs-current=20.8.1- r0 npm=9.6.6-r0 python3=3.11.6-r0 tar=1.34-r3 gzip=1.12-r1

COPY nvim /root/.config/nvim
```

2. Create a `nvim` folder right next to it, with a `init.lua` like this:

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=v10.15.1",
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		'williamboman/mason.nvim',
		version = "1.8.3"
	},
	{
		'williamboman/mason-lspconfig.nvim',
		version = "v1.22.0",
		config = function()
			local lsp_zero = require('lsp-zero')
			lsp_zero.extend_lspconfig()

			lsp_zero.on_attach(function(client, bufnr)
				-- see :help lsp-zero-keybindings
				-- to learn the available actions
				lsp_zero.default_keymaps({ buffer = bufnr })
				vim.keymap.set({ "n", "i" }, "<C-f>", function()
					vim.lsp.buf.format({ async = false })
					vim.cmd("w")
				end)
			end)

			require('mason').setup({})
			require('mason-lspconfig').setup({
				ensure_installed = { "dockerls", "bashls", "volar", "yamlls", "jsonls", "pylsp",
					"marksman", "rust_analyzer", "tsserver", "emmet_ls", "html", "lua_ls" },
				handlers = {
					lsp_zero.default_setup,
				},
			})
		end
	},
	{
		'VonHeikemen/lsp-zero.nvim',
		branch = 'v3.x'
	},
	{
		'neovim/nvim-lspconfig',
		version = "v0.1.6"
	},
	{
		'hrsh7th/cmp-nvim-lsp',
		commit = "44b16d11215dce86f253ce0c30949813c0a90765"
	},
	{
		'hrsh7th/nvim-cmp',
		version = "v0.0.1"
	},
	{
		'L3MON4D3/LuaSnip',
		version = "v2.1.0"
	}
})
```

3. Open NeoVIm and the error should show after the Mason installation.

### Actual behavior

After the Mason run this error return: `Cannot access configuration for lua_ls. Ensure this server is listed in `server_configurations.md` or added as a custom server`.

### Expected behavior

Installation should succeed

### Minimal config

```Lua
Not used, if needed will be added later
```

### LSP log

Not used, if needed will be added later

**Comment by justinmk** [comment]
> I can't install lua_ls with lsp-zero and mason, there is always a error like below.

Has nothing to do with this repo

**Comment by HwKt** [comment]
Check the version of nvim-lspconfig,lua_ls seems to be the new name of sumneko_ls.If the nvim-lspconfig version is too old, lua_ls will definitely not exist.Check /nvim-lspconfig/doc/server_configurations.md first.
