### ISSUE TITLE
cleanup lsp config with new `root_dir` behaviour

### ISSUE THREAD

**Issue by emilioziniades** [neovim/nvim-lspconfig#2904]
### Requested feature

Now that #2885 has been merged, we can clean up a bunch of language server configs that had to manually specify priorities of patterns for finding the root directory. For example, in `tsserver`, this
https://github.com/neovim/nvim-lspconfig/blob/90a28fd7637b66e055af62387ecee06f7cbd3173/lua/lspconfig/server_configurations/tsserver.lua#L15-L18
can simply become

```lua
return util.root_pattern('tsconfig.json', 'package.json', 'jsconfig.json', '.git')
```

Anywhere where a language server has something like `return util.root_pattern(pattern1) or util.root_pattern(pattern2) or ...` can be simplified.

Here's a list of language servers I've identified:
https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/cairo_ls.lua#L11-L14

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/custom_elements_ls.lua#L7-L10

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/gopls.lua#L23

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/gradle_ls.lua#L20

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/hls.lua#L8-L11

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/kotlin_language_server.lua#L29

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/omnisharp.lua#L41-L49

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/syntax_tree.lua#L8

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/tailwindcss.lua#L103-L106

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/tsserver.lua#L15-L18

https://github.com/neovim/nvim-lspconfig/blob/7384e7149e79365c96dc623d9fa3444737776982/lua/lspconfig/server_configurations/vtsls.lua#L14-L17

Let me know if I have missed any.

cc @glepnir @justinmk

**Comment by justinmk** [comment]
🚀
