### ISSUE TITLE
Diagnostics get stuck after :e! / :edit!

### ISSUE THREAD

**Issue by andrescuco** [neovim/nvim-lspconfig#2909]
### Description

LSP diagnostics get stuck / stop working after running `:e!` command on neovim. See screenrecording:

https://github.com/neovim/nvim-lspconfig/assets/36432023/071f5ebb-f00a-4b8d-9dc3-47ecd9c10937

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1692716794

### Nvim-lspconfig version

7fedba8b1f8d0080c775851c429b88fd2ed4c6f5

### Operating system and version

Debian GNU/Linux VERSION="10 (buster)"

### Affected language servers

tsserver

### Steps to reproduce

1. Setup a language server
2. Make a file change that triggers a diagnostic
3. Write `:e!` on neovim command mode and press Enter

### Actual behavior

4. Now the diagnostic is stuck, it won't work for that particular file until you restart `:LspRestart`

### Expected behavior

Diagnostics shouldn't be stuck, they should be able to keep working after `:e!`

### Minimal config
init.vim
```
call plug#begin('~/.vim-plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua <<EOF
  local lspconfig = require('lspconfig')
  require('lspconfig')['tsserver'].setup {}
EOF
```

### LSP log

https://gist.github.com/andrescuco/930182635d7acdbbb174eae6a2e5a1e4

**Comment by glepnir** [comment]
report on neovim
