### ISSUE TITLE
Spring boot language server

### ISSUE THREAD

**Issue by s1n7ax** [neovim/nvim-lspconfig#2921]
### Language server

spring boot language server

### Requested feature

I would like to see spring boot language server being added to the list.

https://github.com/spring-projects/sts4

It seems that the spring toolkit consist of 4 different language servers and the language server requested in this issue is 
spring-boot language server.

![image](https://github.com/neovim/nvim-lspconfig/assets/18459807/95fe7c25-210c-4a84-a93b-f2234fac75a8)

For reference:
https://github.com/spring-projects/sts4/issues/76
https://github.com/spring-projects/sts4/issues/1128

**Comment by justinmk** [comment]
send a pr

**Comment by 4r73m190r0s** [comment]
This is still not resolved?

**Comment by justinmk** [comment]
because no one sent a pr ?
