### ISSUE TITLE
LSP failing to start Rubocop LSP

### ISSUE THREAD

**Issue by orafaelfragoso** [neovim/nvim-lspconfig#2927]
### Description

I have spent my whole day trying to figure it out Rubocop on LSP config. I have a legacy project that is running an old version of Rubocop and I have the latest version installed globally. I am also running Ruby 2.7.6 which is the project version.

This is the error I'm getting:
```
[START][2023-12-11 22:26:00] LSP logging initiated
[ERROR][2023-12-11 22:26:00] .../vim/lsp/rpc.lua:675	"rpc"	"bundle"	"stderr"	"invalid option: --lsp\nFor usage information, use --help\n"
```

And this is my config for LSP:

```lua
lspconfig.rubocop.setup {
  on_attach = on_attach,
  capabilities = capabilities,
  cmd = { os.getenv "HOME" .. "/.asdf/shims/rubocop", "--lsp" },
  filetypes = { "ruby" },
  root_dir = util.root_pattern("Gemfile", ".git"),
}
```

This is the output for LspInfo:

```
 Language client log: /Users/rafael/.local/state/nvim/lsp.log
 Detected filetype:   ruby
 
 1 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, bufnr: [1])
 	filetypes:       typescriptreact, javascriptreact, javascript, typescript, markdown, json, jsonc, html, css, js, jsx, ts, tsx, luau, lua, go, ruby
 	autostart:       false
 	root directory:  /Users/rafael/Development/project
 	cmd:             <function>
 
 Other clients that match the filetype: ruby
 
 Config: rubocop
 	filetypes:         ruby
 	root directory:    /Users/rafael/Development/project
 	cmd:               /Users/rafael/.asdf/shims/rubocop --lsp
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
 
 Configured servers list: lua_ls, html, clangd, rubocop, cssls, gopls, tsserver
```

### Neovim version

NVIM v0.10.0-dev-1742+g17f3a3ae3-Homebrew
Build type: Release
LuaJIT 2.1.1700008891

### Operating system and version

macOS 14.1.2

### Affected language servers

rubocop

### Steps to reproduce

1. Setup an old rails project that uses ruby 2.7 and rubocop prior to 1.x
2. Install Rubocop globally `gem install rubocop`
3. Install the rubocop lsp config
4. Open a ruby file inside the project

### Actual behavior

It does not work

### Expected behavior

I was hopping to have LSP working with all the goodies.

PS: The same config on VSCode just works like magic. Using the same gem.

### Minimal config

```Lua
I'm using NvChad with the default configuration, just added rubocop.
```

### LSP log

don't have

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
