### ISSUE TITLE
Incomplete documentation for `lua_ls`

### ISSUE THREAD

**Issue by aminnairi** [neovim/nvim-lspconfig#2951]
### Description

As per the discussion in #2948, it would be great to update the documentation to clearly indicate that the `/lua` folder needs to be used at the end in order for the Lua language server to pick up documentations for the Vim's Lua runtime.

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

### Nvim-lspconfig version

master

### Operating system and version

Arch

### Affected language servers

lua_ls

### Steps to reproduce

1. Go to the [`server_configurations.md`](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md) file.
2. Search for the documentation for [`lua_ls`](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#lua_ls).
3. Notice that the line where `vim.env.VIMRUNTIME` is described lacks the `/lua` folder at the end.

### Actual behavior

The documentation does not mention concatenating the `/lua` folder when setting up the `lua_ls`.

### Expected behavior

The documentation should mention concatenating the `/lua` folder when setting up the `lua_ls`.

### Minimal config

```Lua
require'lspconfig'.lua_ls.setup {
  on_init = function(client)
    local path = client.workspace_folders[1].name
    if not vim.loop.fs_stat(path..'/.luarc.json') and not vim.loop.fs_stat(path..'/.luarc.jsonc') then
      client.config.settings = vim.tbl_deep_extend('force', client.config.settings, {
        Lua = {
          runtime = {
            -- Tell the language server which version of Lua you're using
            -- (most likely LuaJIT in the case of Neovim)
            version = 'LuaJIT'
          },
          -- Make the server aware of Neovim runtime files
          workspace = {
            checkThirdParty = false,
            library = {
              vim.env.VIMRUNTIME
              -- "${3rd}/luv/library"
              -- "${3rd}/busted/library",
            }
            -- or pull in all of 'runtimepath'. NOTE: this is a lot slower
            -- library = vim.api.nvim_get_runtime_file("", true)
          }
        }
      })

      client.notify("workspace/didChangeConfiguration", { settings = client.config.settings })
    end
    return true
  end
}
```

### LSP log

None.

**Comment by lithammer** [comment]
I would probably just use https://github.com/folke/neodev.nvim instead.

**Comment by justinmk** [comment]
PR welcome?

**Comment by MariaSolOs** [comment]
> I would probably just use https://github.com/folke/neodev.nvim instead.

Note that since https://github.com/neovim/neovim/pull/24592 there's no need for `neodev` anymore.
