### ISSUE TITLE
LSP response "No implementations found", but gopls response LSP info

### ISSUE THREAD

**Issue by newro** [neovim/nvim-lspconfig#2957]
### Description

This bug has a very unique behavior and was not easy to reproduce.

First, it doesn't respond with "No implementations found" in all situations.
At first, the implementation behaves normally,
to the correct line and column in the file.
This means that LSP and gopls are working fine.

Then, if It try to go to definitions with a normal struct method that doesn't have an interface
go to definitions will create a buffer for that file and move it as normal.
And that's as far as it goes.

After that, most implementation actions on interfaces will emit a "No implementations found" response.
The code that moved normally above will not move either.

However, if It close the buffer of the file It just moved to definition, the implementation works fine again.
The implementation works fine.

This situation is reproduced about 80-90% of the time, but not 100% of the time.
In some code situations, following the above instruction will work fine.
However, if you navigate to the definition in another area, the implementation behavior will inevitably respond with "No implementations found".
Similarly, if it runs into this error situation, close all definition buffers and run
and the implementation will behave normally again.

This test is the same for all the open source implementations of the GO language,
neovim in minimal config mode.

Additionally, if it finds in a situation where the implementation behavior is not happening at once in code,
the definition action will jump to the definition of the interface, and from there
Calling the implementation behavior from there will finally take to the implementation location.
This means that what should have been a single action is now split into two separate actions.

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1700008891

### Operating system and version

macOS Sonoma 14.2.1(23C71)

### Affected language servers

gopls

### Steps to reproduce

local lazy = {}

function lazy.install(path)
  if not vim.loop.fs_stat(path) then
    print('Installing lazy.nvim....')
    vim.fn.system({
      'git',
      'clone',
      '--filter=blob:none',
      'https://github.com/folke/lazy.nvim.git',
      '--branch=stable', -- latest stable release
      path,
    })
  end
end

function lazy.setup(plugins)
  if vim.g.plugins_ready then
    return
  end

  -- You can "comment out" the line below after lazy.nvim is installed
  lazy.install(lazy.path)

  vim.opt.rtp:prepend(lazy.path)

  require('lazy').setup(plugins, lazy.opts)
  vim.g.plugins_ready = true
end

lazy.path = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
lazy.opts = {}

lazy.setup({
  {'folke/tokyonight.nvim'},
  {'kyazdani42/nvim-web-devicons'},
  {'nvim-lualine/lualine.nvim'},
  {"neovim/nvim-lspconfig"},
})

require'lspconfig'.gopls.setup{}

### Actual behavior

1. open the source code that calls the interface's implementation.
2. at the call location, call `lua vim.lsp.buf.implementation()` and watch it jump to the implementation's code location.
3. return to the call location and move the cursor to the call location of the other struct method in the same source code and call `lua vim.lsp.buf.definition()` to move to the code location.
4. come back and repeat step 2 again and see that you get the "No implementations found" error.
5. close the buffer in the struct method code.
6. Come back and repeat step 2 again to verify that it navigates to the code location correctly.

### Expected behavior

Always properly go to implementation behavior at once.

### Minimal config

```Lua
local on_windows = vim.loop.os_uname().version:match 'Windows'

local function join_paths(...)
  local path_sep = on_windows and '\\' or '/'
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd [[set runtimepath=$VIMRUNTIME]]

local temp_dir = vim.loop.os_getenv 'TEMP' or '/tmp'

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local lspconfig_path = join_paths(package_root, 'test', 'start', 'nvim-lspconfig')

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
  vim.fn.system { 'git', 'clone', 'https://github.com/neovim/nvim-lspconfig', lspconfig_path }
end

vim.lsp.set_log_level 'trace'
require('vim.lsp.log').set_format_func(vim.inspect)
local nvim_lsp = require 'lspconfig'
local on_attach = function(_, bufnr)
  local function buf_set_option(...)
    vim.api.nvim_buf_set_option(bufnr, ...)
  end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { buffer = bufnr, noremap = true, silent = true }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, opts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, opts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, opts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, opts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, opts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, opts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, opts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, opts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, opts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, opts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, opts)
  vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
  vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
  vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
  vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = 'gopls'
local cmd = { 'gopls', '--mode=stdio' } -- needed for elixirls, lua_ls, omnisharp
if not name then
  print 'You have not defined a server name, please edit minimal_init.lua'
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
  print [[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]]
end

nvim_lsp[name].setup {
  cmd = cmd,
  on_attach = on_attach,
}

print [[You can find your log at $HOME/.cache/nvim/lsp.log. Please paste in a github issue under a details tag as described in the issue template.]]
```

### LSP log

nothingLogged

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
