### ISSUE TITLE
Add explanation how to configure severity of diagnostics of for `typos_lsp`

### ISSUE THREAD

**Issue by pavkam** [neovim/nvim-lspconfig#2966]
### Language server

typos_lsp

### Requested feature

Took me a while, to look at the source code of the LSP. But can a simple explanation be included in how to set the diagnostic severity in the docs:

```
  init_options = {
      diagnosticSeverity = 'Hint', -- 'Warning' or 'Error'. Default is 'Error'
  }
```

Thanks.

**Comment by justinmk** [comment]
this repo is a collection of configs. we aren't going to document Nvim LSP features here.

https://neovim.io/doc/user/diagnostic.html#vim.diagnostic.severity

**Comment by pavkam** [comment]
@justinmk  I think you are mistaken -- this was an example of configuring `typos_lsp` not nvim diagnostics. As in:
```
 typos_lsp = {
    init_options = { -- Sent to the LSP on init
        diagnosticSeverity = 'Hint',
    },
},
```
