### ISSUE TITLE
Option to spawn new instance instead of appending to workspace folders (also wrong `root_dir` docs)

### ISSUE THREAD

**Issue by smackesey** [neovim/nvim-lspconfig#2967]
### Requested feature

The docs for the `root_dir` setting say:

```
- {root_dir}

    `function(filename, bufnr)`

    Returns either a filepath (string) or nil. The language server will only
    start if the function returns a filepath.

    If a root directory (string) is returned which is unique from any
    previously returned root_dir, a new server will be spawned with that
    root directory. See |lspconfig-root-detection| for more details
```

AFAICT this is wrong. I believe what lspconfig does is check for "workspace folders" support on the server. If it's supported then lspconfig adds the new root directory as a new workspace folder to an existing server instance. It only launches a new instance if workspace folders isn't supported.

Because not all servers implement workspace folders support perfectly, this behavior is not always desirable. It would be better to grant the user control here over whether to create a new server instance or add to workspace folders of an existing instance.

(Aside: I am running into a problem specifically with `lua_ls`-- anyone know a workaround to prevent adding to workspace folders for this specific server?)

**Comment by justinmk** [comment]
Thanks for your report. This repo is just a collection of configs, it has nothing to do with "starting a new server".

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by smackesey** [comment]
>This repo is just a collection of configs, it has nothing to do with "starting a new server".

?

`lspconfig.manager` contains logic that determines whether to spawn a new client (which IIUC starts a new server process). The specific part I'm talking about, where the decision to spawn a new client is conditioned on whether an existing client/server has "workspace folders" support, can be found right [here]: https://github.com/neovim/nvim-lspconfig.git/blob//lua/lspconfig/manager.lua#L159-L176

```
--- @private
--- @param bufnr integer
--- @param new_config lspconfig.Config
--- @param root_dir string
--- @param client lsp.Client
--- @param single_file boolean
function M:_attach_or_spawn(bufnr, new_config, root_dir, client, single_file)
  if check_in_workspace(client, root_dir) then
    return self:_attach_and_cache(bufnr, root_dir, client.id)
  end

  local supported = vim.tbl_get(client, 'server_capabilities', 'workspace', 'workspaceFolders', 'supported')
  if supported then
    return self:_register_workspace_folders(bufnr, root_dir, client)
  end
  self:_start_new_client(bufnr, new_config, root_dir, single_file)
end
```

**Comment by smackesey** [comment]
@justinmk In light of the above, can we reopen this issue? I would be willing to provide a PR.
