### ISSUE TITLE
Inlayhints for jdtls

### ISSUE THREAD

**Issue by snaggen** [neovim/nvim-lspconfig#2970]
### Language server

jdtls

### Requested feature

By default jdtls doesn't send inlay hints, this can be enabled by the server config (signatureHelp is not really inlay related, but still nice to have)

```json
                        settings = {
                            java = {
                                inlayHints = { parameterNames = { enabled = "all" } },
                                signatureHelp = { enabled = true },
                            }
                        }
```

However, jdtls have a slow start and run in to the inlay hint not drawn on startup as discussed in 
https://github.com/neovim/neovim/issues/26511#issuecomment-1890962251
so to work around that I have registered handler
```lua
                        handlers = {
                            ['language/status'] = function(_, result, ctx, _)
                                if result.type == "ServiceReady" then
                                    for _, bufnr in ipairs(vim.lsp.get_buffers_by_client_id(ctx.client_id)) do
                                        vim.lsp.inlay_hint.enable(bufnr, false);
                                        vim.lsp.inlay_hint.enable(bufnr, true);
                                    end
                                end
                            end
                        },

```

This of course needs ot be genralized to check if the user have inlay hints enabled before toggling them, but you get the idea.

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by snaggen** [comment]
If you read the discussion, you see that the consensus was that this is not a bug in Neovim but should be fixed with setup. That is why I filed it here with the  method I provide.
