### ISSUE TITLE
Document unsupported nvim

### ISSUE THREAD

**Issue by EvanCarroll** [neovim/nvim-lspconfig#2972]
### Requested feature

When I start neovim, I get

> Requires neovim version 0.8 above. Update Nvim and nvim-lspconfig before reporting an issue.

That may be true for the latest neovim, but it would be nice if there was advice on how to use the last available version of `nvim-lspconfig` supported for my neovim `NVIM v0.7.2`. I'm on the lastest supported version of Debian.

**Comment by alet** [comment]
Plug 'neovim/nvim-lspconfig', { 'commit': 'fcc270cc834acbc0ad6aebf1f4bf0d0bb87a8eb8'} "Last commit with nvim 0.7 support

Next commit changes requirement to >0.8

**Comment by justinmk** [comment]
it's in the readme: https://github.com/neovim/nvim-lspconfig?tab=readme-ov-file#install

**Comment by EvanCarroll** [comment]
@justinmk  I don't see in the readme at all. What I needed was the line provided by @alet

**Comment by EvanCarroll** [comment]
I mean you could always create a tag to make it easier. (a better idea).

Then you just maintain a tag that represents the last version of nvim that was supported by each version of vim. For example a tag for `nvim-0.8`

**Comment by alet** [comment]
The 'fcc270cc834acbc0a' commit doesn't work. It be better to use 'bc62a72'

[https://github.com/neovim/nvim-lspconfig/issues/2499](https://github.com/neovim/nvim-lspconfig/issues/2499)
