### ISSUE TITLE
[Biome] Only attach if the folder contains a biome.json

### ISSUE THREAD

**Issue by willparsons** [neovim/nvim-lspconfig#2980]
### Language server

biome

### Requested feature

The default config for biome lets it run in any node/git folder which leads to situations where an eslint project is conflicting with biome since they're both producing lints or trying to format.

I think it makes more sense that the default configuration of biome expects that the project is actually configured to use biome, similar to how eslint works.

E.g.
```lua
return {
  root_dir = util.root_pattern "biome.json",
  single_file_support = false,
}
```

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by willparsons** [comment]
> We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

I'm happy to create a PR for this, I thought I'd raise the suggestion first to see if the current behaviour was preferred.

**Comment by willparsons** [comment]
https://github.com/neovim/nvim-lspconfig/pull/2984

I made a PR in case you're happy to include this change.

**Comment by acheong08** [comment]
Is it possible to make this configurable? I don't use eslint and I would rather not have to bring javascript configuration hell to my projects which only have a tiny bit of plain javascript embedded.

**Comment by willparsons** [comment]
just override it to fit your use case, it's always configurable

**Comment by kotasudhakar** [comment]
There is still an issue i am facing when there is an biome extension installed but no biome json file is there in the repo, still the biome is showing those as errors. I dont want it as in this repo i have already prettier and eslint configured

**Comment by kotasudhakar** [comment]
I am using biome extension version 1.9.2
