### ISSUE TITLE
Support for typespec

### ISSUE THREAD

**Issue by jellydn** [neovim/nvim-lspconfig#2981]
### Language server

typespec

### Requested feature

TypeSpec is a language for describing cloud service APIs and generating other API description languages, client and service code, documentation, and other assets. TypeSpec provides highly extensible core language primitives that can describe API shapes common among REST, OpenAPI, GraphQL, gRPC, and other protocols.

https://github.com/microsoft/typespec

There is an LSP implementation so it would be great if we could bring this to Neovim.

**Comment by BingCoke** [comment]
yep i need it!

**Comment by jpx40** [comment]
> ### Language server
> 
> typespec
> ### Requested feature
> 
> TypeSpec is a language for describing cloud service APIs and generating other API description languages, client and service code, documentation, and other assets. TypeSpec provides highly extensible core language primitives that can describe API shapes common among REST, OpenAPI, GraphQL, gRPC, and other protocols.
> 
> https://github.com/microsoft/typespec
> 
> There is an LSP implementation so it would be great if we could bring this to Neovim.
> ### Other clients which have this feature
> 
> _No response_

wanna try it too

**Comment by RiwEZ** [comment]
I think this is already done on this PR https://github.com/neovim/nvim-lspconfig/pull/3093
