### ISSUE TITLE
rust_analyzer consumes much more memory than than the VSCode extension

### ISSUE THREAD

**Issue by teackot** [neovim/nvim-lspconfig#2985]
### Description

When I'm working on a large project that uses gtk-rs in neovim, rust-analyzer's memory usage grows up to 4GiB after a couple of minutes. Then it gradually goes over 8GiB and eventually gets killed by systemd-oomd. It also constantly uses more than 8% of my CPU.

However, when I use vscode memory usage stays around 2GiB.

I wonder if there is a problem with the lspconfig's default configuration of rust_analyzer?

I'm not sure if this is the right place to report it though

### Neovim version

NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1702233742

### Nvim-lspconfig version

8917d2c830e04bf944a699b8c41f097621283828

### Operating system and version

Arch Linux

### Affected language servers

rust_analyzer

### Steps to reproduce

1. Open a large project in neovim
2. Open the same project in vscode
3. Compare memory usage

### Actual behavior

OOM

### Expected behavior

No OOM

### Minimal config

```Lua
local lspconfig = require('lspconfig')
lspconfig.rust_analyzer.setup {}
```

### LSP log

https://gist.github.com/teackot/af1d753fcb9136809b29bd18d3729c29

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
