### ISSUE TITLE
TexLab setup is unable to compile successfully even on minimal TeX script

### ISSUE THREAD

**Issue by winstxnhdw** [neovim/nvim-lspconfig#2989]
### Description

I am on the latest version of `Tectonic` and I am trying to compile a simple TeX script. I have `TexLab` installed via Mason and I am using a minimal `nvim` setup. No distros, nothing. Just the lazy plugin manager. I have scoured `TexLab`, this repo, Reddit and StackOverflow for any hints at all but I came empty after half a day :D So I am guessing it's likely a bug.

```tex
\documentclass[12pt]{article}
\begin{document}
Hello world!
\end{document}
```

Yes, I can compile the script successfully outside of `nvim`.

```bash
tectonic -X compile test.tex --synctex --keep-logs --keep-intermediates
```

No, `vim.lsp.set_log_level('debug')` doesn't produce logs or print anything.

Yes, I am using the correct arguments according to TexLab's [docs](https://github.com/latex-lsp/texlab/wiki/Tectonic).

I have also used the V1 CLI syntax for Tectonic and tried other's 2 year old TexLab config for Tectonic that supposedly worked for them back then.

### Neovim version

NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

### Operating system and version

Arch Linux

### Affected language servers

TexLab

### Steps to reproduce

1. Install Tectonic
2. Install Texlab via Mason
3. Paste LSP minimal config
4. Run `:TexlabBuild`
5. Cry

### Actual behavior

It prints `Build Error`.

### Expected behavior

Build successfully.

### Minimal config

```Lua
require('lspconfig').texlab.setup({
    settings = {
        texlab = {
            build = {
                executable = 'tectonic',
                args = { '-X', 'compile', '%f', '--synctex', '--keep-logs', '--keep-intermediates' },
                onSave = true
            }
        }
    }
})
```

### LSP log

No logs were generated.

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
