### ISSUE TITLE
changing the diagnistics language in pyright

### ISSUE THREAD

**Issue by svenXY** [neovim/nvim-lspconfig#2993]
### Description

pyright ships with localization for its diagnostics. To detect the language the user prefers, it uses the well known environment variables (see https://github.com/microsoft/pyright/blob/main/docs/configuration.md#locale-configuration)

This means that the setup provided by lspconfig does not easily allow to change the diagnostics back to English, which I would prefer because it is easier to find support for the original diagnostic strings and some of the translations are rather, well, ... unusual.

The first thing I tried was to set cmd to `cmd = {"LANG=en", "pyright-langserver", "--stdio"}`, but that fails with something like command not found

Then I tried to put this into a script - 
```sh
LANGUAGE=en pyright-langserver --stdio
```
and added that as cmd. Now LspInfo reports it like that:

```
[...]
Other clients that match the filetype: python
 
 Config: pyright
 	filetypes:         python
 	root directory:    /Users/Sven/.config/nvim
 	cmd:               /Users/Sven/bin/launch_pyright.sh
 	cmd is executable: true
 	autostart:         true
 	custom handlers:   
```

but it does not do anything, no diagnostics, no completion support, no nothing.

Starting nvim with the language environment variable works, but that breaks other things like spelling and so on, so I would prefer to run neovim with German (in my case) while starting pyright with English.

Now I'm out of options, therefore I'd like to know if it were possible to soehow pass environment variables via lspconfig or similar.

Thanks

**Comment by glepnir** [comment]
```lua
 cmd_env = {    Language = 'en' },
```

**Comment by svenXY** [comment]
interestingly enough, it works with LANG, but not with LANGUAGE, even though the pyright config documenation suggests that LANGUAGE shoul work as well...

Thanks for the helpful information. Solved.
