### ISSUE TITLE
should use gI instead of gi in config

### ISSUE THREAD

**Issue by 0n3W4y7ick3t** [neovim/nvim-lspconfig#2999]
### Description

https://github.com/neovim/nvim-lspconfig/blob/d12140c5687a1186b95b3f42dbc6cc769df0cf0d/README.md?plain=1#L75

`gi` is mapped to go to last insert place and enter insert mode by default, which is quite useful, so this config should use `gI` instead

**Comment by glepnir** [comment]
`gI` also mapped. it's just an exmaple config .
