### ISSUE TITLE
Start lsp server in the background and reuse on subsequent starts by default

### ISSUE THREAD

**Issue by nhooyr** [neovim/nvim-lspconfig#300]
I think this would be a much better model as someone who constantly closes and opens neovim, it's a little annoying to have to wait for the language server to start up sometimes.

If by default it was started in the background and then reused by subsequent startups, things would be very fast.

Interestingly enough, it also delays shutdown if it neovim was just started. i.e if I open a Go file and then instantly press `:q` to close, neovim takes a second before closing. Without `nvim-lsp` installed, this does not occur.

**Comment by Shougo** [comment]
But who closes the background process?
It is always exists?

**Comment by nhooyr** [comment]
Ideally it’d time-out after it hasn’t been used in a while and exit. Perhaps we could start it under a parent process that handles that.

**Comment by tjdevries** [comment]
Should be possible for you to do this already. Just change the command you issue for your configuration. Make some shell script that either starts or connects to a server.
