### ISSUE TITLE
Custom commands field collide with `vim.lsp.client` definition on nvim nightly

### ISSUE THREAD

**Issue by yioneko** [neovim/nvim-lspconfig#3009]
### Description

This is the definition of `commands` in `nvim-lspconfig`:

https://github.com/neovim/nvim-lspconfig/blob/ae91a303a2258cb9cd9501e9d20c2dc92792d362/doc/lspconfig.txt#L281-L284

Compared to nvim, where the mapped value is just a function, not a table:

https://github.com/neovim/neovim/blob/ce5a9bfe7e537c81d34bd4a27fc6638f20114e67/runtime/doc/lsp.txt#L995-L1000

The collision here worked fine in the previous version of nvim, but incurred problem since https://github.com/neovim/neovim/commit/597ecf751603cde2d5f58021d503ae20a12eb2f2, which adds the native definition of `commands` to `client.config`, and causes error at https://github.com/neovim/nvim-lspconfig/blob/ae91a303a2258cb9cd9501e9d20c2dc92792d362/lua/lspconfig/configs.lua#L283-L285.

A simple validation of the problem:
```lua

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup({
	{
		"neovim/nvim-lspconfig",
		config = function()
			require("lspconfig").vtsls.setup({
				on_attach = function(client)
					client.commands["command"] = function() end
				end,
			})
		end,
	},
}, {})
```
Open a random TypeScript file to start server, we will see the error message:

`LSP[vtsls]: Error ON_ATTACH_ERROR: "...are/nvim_test/lazy/nvim-lspconfig/lua/lspconfig/util.lua:71: bad argument #1 to 'pairs' (table expected, got function)"`

I think we need to deprecate the `commands` field in `nvim-lspconfig`.

**Comment by glepnir** [comment]
try the latest commit build
