### ISSUE TITLE
[lspconfig] Cannot access configuration for mdx_analyzer. 

### ISSUE THREAD

**Issue by lightbluepoppy** [neovim/nvim-lspconfig#3014]
### Description

I installed mdx_analyzer via Mason and it says it is not in [server_configurations.md](https://github.com/neovim/nvim-lspconfig/blob/d1bab4cf4b69e49d6058028fd933d8ef5e74e680/doc/server_configurations.md#mdx_analyzer) but actually is. I use Lunarvim 1.3.
```lua
require "lspconfig".mdx_analyzer.setup({})
```

```
[lspconfig] Cannot access configuration for mdx_analyzer. Ensure this server is listed in `server_configurations.md` or
 added as a custom server.
```

I installed and let other LSP clients to be attached successfully. The code below is using Lunarvim API, but as to mdx_analyzer it does not even recognize, so I have to use lspconfig API directly.

```lua
require("lvim.lsp.manager").setup("gopls")
require("lvim.lsp.manager").setup("lua_ls")
```

**Comment by glepnir** [comment]
can't reproduce . you can try to update your plugins first.

**Comment by lightbluepoppy** [comment]
Turns out that the branch of nvim-lspconfig was fixed to the old one from last year. Managed to update it by `git chekout master` and get the latest server configurations. It was a bug of either Lunarvim or Lazy.nvim.
