### ISSUE TITLE
nvim-lspconfig is the only plugin to startup slow on WSL

### ISSUE THREAD

**Issue by adambarjo** [neovim/nvim-lspconfig#3015]
## Description
The startup time of nvim-lspconfig takes much longer on WSL than on Windows. All other plugins load faster on WSL than on Windows.

![2024-02-17_22-13](https://github.com/neovim/nvim-lspconfig/assets/47948089/8a0c29e8-4e1b-41af-8994-a87727944532)

## Neovim version
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1693350652

## Nvim-lspconfig version
d1bab4c

## Operating system and version
WSL version: 2.0.9.0

## Affected language servers
N/A

## Steps to reproduce
Open neovim.

## Actual behavior
nvim-lspconfig takes: `462.91ms` on WSL compared to `84.21ms` on Windows.

## Expected behavior
The startup time would be similar on WSL, maybe even faster, like other plugins are.

## Minimal config
```lua
return {
  "neovim/nvim-lspconfig",
  dependencies = { "hrsh7th/nvim-cmp" },
  config = function()
    local lspconfig = require("lspconfig")
    local capabilities = require("cmp_nvim_lsp").default_capabilities()

    lspconfig.bashls.setup({ capabilities = capabilities })
    lspconfig.gopls.setup({ capabilities = capabilities })
    lspconfig.marksman.setup({ capabilities = capabilities })
    lspconfig.tailwindcss.setup({ capabilities = capabilities })
    lspconfig.lua_ls.setup({ capabilities = capabilities })
    lspconfig.tsserver.setup({ capabilities = capabilities })

    vim.api.nvim_create_autocmd("LspAttach", {
      callback = function(ev)
        local function map(mode, lhs, rhs, desc)
          vim.keymap.set(mode, lhs, rhs, { noremap = true, silent = true, desc = desc, buffer = ev.buf })
        end
        map("i", "<M-k>", vim.lsp.buf.signature_help, "Signature help")
        -- other keymaps ...
      end,
    })
  end,
}
```

## LSP log
N/A

**Comment by glepnir** [comment]
Don't rely on any plugin's time. Please use startuptime. I believe lazy supports lazy load. You can use lazyload such as ft or event.

**Comment by isvicy** [comment]
same here.

and i don't got an answer from this closed issue which is marked as completed.
