### ISSUE TITLE
Consider renaming twig-language-server

### ISSUE THREAD

**Issue by fbuchlak** [neovim/nvim-lspconfig#3020]
### Description

`twig-language-server` introduced in #2939 should probably be renamed to `twiggy-language-server` to avoid confusion.

Language server used in nvim-lspconfig - [twiggy](https://github.com/moetelo/twiggy) has it's own npm package `twiggy-language-server` and original [twig-language-server](https://github.com/kaermorchen/twig-language-server) is available as `twig-language-server` on npm.

**Comment by justinmk** [comment]
send a PR
