### ISSUE TITLE
Inteliphense format clear all marks

### ISSUE THREAD

**Issue by brunojoao** [neovim/nvim-lspconfig#3035]
### Description

If create a mark example, ma...
... and Format file :Format
all marks are removed

![image](https://github.com/neovim/nvim-lspconfig/assets/16447379/21b1b930-f8fe-4765-89ad-d46c6ceede86)

This only happens when formatting the file and only with inteliphense, this does not happen with anything else.

**Comment by brunojoao** [comment]
my solution:
I used Inteliphense through Mason, I uninstalled it and started using PHP Actor, it's perfect.

**Comment by glepnir** [comment]
there is no format command check you plugin first please
