### ISSUE TITLE
The current Wiki about UI customization of handlers for `textDocument/hover` is buggy!

### ISSUE THREAD

**Issue by nyngwang** [neovim/nvim-lspconfig#3036]
### Description

At the page, https://github.com/neovim/nvim-lspconfig/wiki/UI-Customization#borders:

```lua
-- LSP settings (for overriding per client)
local handlers =  {
  ["textDocument/hover"] =  vim.lsp.with(vim.lsp.handlers.hover, {border = border}),
  ["textDocument/signatureHelp"] =  vim.lsp.with(vim.lsp.handlers.signature_help, {border = border }),
}

```

But this causes an error:

```
   Error  16:28:15 msg_show.lua_error Error executing vim.schedule lua callback: /usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1697: 'width' key must be a positive Integer
stack traceback:
	[C]: in function 'nvim_open_win'
	/usr/local/share/nvim/runtime/lua/vim/lsp/util.lua:1697: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:574: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

To fix it I have to hard-code the `height` and `width` for both:

```lua
{border = border, width=10, height=10}
```

So it seems that someone made a change that either validating/removing the default `height`&`width` when it is not set!

**Comment by nyngwang** [comment]
Nevermind! I just realized this is caused by the fact that if noice.nvim is used and you have its config like this;

```lua
require('noice').setup {
  lsp = {
    -- override markdown rendering so that **cmp** and other plugins use **Treesitter**
    override = {
      ['vim.lsp.util.convert_input_to_markdown_lines'] = true,
      ['vim.lsp.util.stylize_markdown'] = true,
      ['cmp.entry.get_documentation'] = true,
    },
  },
  presets = {
    lsp_doc_border = true,
  },
```

then you will **have to** give up using built-in `vim.lsp.buf.hover`, and use its `require("noice.lsp").hover()` instead.

Reference: https://github.com/folke/noice.nvim/issues/258.

**Comment by miguno** [comment]
Thanks for your comment https://github.com/neovim/nvim-lspconfig/issues/3036#issuecomment-1968518789, @nyngwang.

Replacing `vim.lsp.buf.hover()` with `require("noice.lsp").hover()` also solved my problem where, when using noice, the LSP's floating window was not using a border even though I tried things like:

```lua
["textDocument/hover"] =  vim.lsp.with(vim.lsp.handlers.hover, {border = "rounded"})
```

**Comment by Leandros** [comment]
That solution doesn't really solve the underlying issue.
