### ISSUE TITLE
An error when using the plugin with lazy.nvim

### ISSUE THREAD

**Issue by Blayung** [neovim/nvim-lspconfig#3038]
### Description

Basically, when I launch neovim, I get such an error message:
```
Failed to run `init` for **nvim-lspconfig**

...share/nvim/lazy/nvim-lspconfig/lua/lspconfig/configs.lua:71: attempt to index local 'user_config' (a nil value)

# stacktrace:
  - init.lua:16 _in_ **init**
  - init.lua:3
```
It used to work normally when I was using packer, the error appears only after I've switched to lazy.nvim.  
  
This is my init.lua:
```
vim.opt.rtp:append(vim.fn.stdpath('data') .. '/lazy/lazy.nvim')

require('lazy').setup({
    {
        'https://github.com/neovim/nvim-lspconfig',
        init = function()
            local lspconfig = require('lspconfig')
            lspconfig.rust_analyzer.setup()
        end
    },
    {
        'https://github.com/folke/trouble.nvim'
    }
})
```
Could anybody help me with it?

**Comment by glepnir** [comment]
init is lspconfig iniit .not lazy init

**Comment by Blayung** [comment]
I'm sorry, but I'm not sure I understand.

**Comment by Blayung** [comment]
> init is lspconfig iniit .not lazy init

I'm sorry, but I'm not sure I understand.

**Comment by Blayung** [comment]
Okay, I'm just dumb, the problem was that I didn't pass an empty table to `lspconfig.rust_analyzer.setup()`. I don't know what does `init is lspconfig iniit .not lazy init` mean though.

**Comment by andradei** [comment]
@Blayung exactly my issue too. Thank you for catching that. The documentation shows
`require("lspconfig")[server_name].setup {}`
and I, not understanding the lua syntax, did
`require("lspconfig")[server_name].setup()` which means I'm calling `setup` with the 1st parameter being `nil` when it should be`{}` so, if you want to keep the parentheses:
`require("lspconfig")[server_name].setup({})` is what you want.

**Comment by Blayung** [comment]
Yeah, I also have close to zero experience with lua, so I thought that I'll just prettify it and it stopped working. Didn't use lsp for a few days because of it :D

The formatting in the nvim lsp docs is terrible, i have no idea how can they use such syntax.
