### ISSUE TITLE
F# LS: Error executing vim.schedule lua callback: util.lua:277: attempt to index field 'textEdit' (a userdata value)

### ISSUE THREAD

**Issue by PhilT** [neovim/nvim-lspconfig#304]
- `nvim --version`: v0.5.0-593-g1ca67a73c
- nvim-lsp version(commit hash): 3f7223659f39273c5fe4f2f2d7ee8baa827a9cfb
- `:checkhealth` result: All OK (except for no Perl provider)
- What language server(If the problem is related to a specific language server): fsharp-language-server
- Operating system/version: Windows 10 Pro x64
- Terminal name/version: cmd.exe
- `$TERM`: ($env:TERM) xterm-256color

### Custom language server configuration
```
:lua << END
local configs = require 'nvim_lsp/configs'
local util = require 'nvim_lsp/util'

configs.fsharp = {
  default_config = {
    cmd = {"dotnet", "/Users/Phil/code/fsharp-language-server/src/FSharpLanguageServer/bin/Release/netcoreapp3.1/FSharpLanguageServer.dll"};
    filetypes = {"fsharp"};
    root_dir = util.root_pattern("*.fsproj", "*.sln", ".git");
  };
}

require 'nvim_lsp'.fsharp.setup{}
END
```

### How to reproduce the problem from neovim startup
```
open System

[<EntryPoint>]
let main argv =
    printfn "Hello World from F#!"
    IO.<CTRL+X><CTRL+O>
    0
```

### Actual behaviour
```
Error executing vim.schedule lua callback: C:\tools\Neovim0.5\share\nvim\runtime\lua\vim\lsp\util.lua:277: attempt to index field 'textEdit' (a userdata value)
```

### Expected behaviour
Drop down list (omnifunc) containing completion items.

### Notes
I'm trying to get https://github.com/fsprojects/fsharp-language-server to work with Neovim LSP Client. Errors, definitions and
references are working correctly but I get the above error when I trigger omnifunc for autocompletion. I've never used Lua before but it doesn't look too hard. I could take a stab at debugging this but could do with some pointers on how to go about it. The language server works successfully with LanguageClient-Neovim (or has in the past) and a fork exists for coc-nvim which I might try next but would prefer to use the main one if possible. If I can get this working I'd love to add it to nvim-lsp. Thanks all.

**Comment by PhilT** [comment]
From what I can see in the code at 277 it's checking that `item.textEdit` is not `nil` but it's actually `vim.NIL`.

**Comment by PhilT** [comment]
Fixing that, I get 

```
Error executing vim.schedule lua callback: Neovim0.5\share\nvim\runtime\lua\vim\lsp\util.lua:268: attempt to compare two userdata values
```

Here is an example of the data that's coming back from the server:

```
{                                                             
  additionalTextEdits = {},                       
  command = vim.NIL,
  commitCharacters = {},                          
  data = {                                                  
    FullName = "System.IO.DirectoryInfo"
  },                                                     
  detail = "System.IO.DirectoryInfo",
  documentation = vim.NIL,
  filterText = vim.NIL,   
  insertText = "DirectoryInfo",
  insertTextFormat = vim.NIL,
  kind = 7,                       
  label = "DirectoryInfo",
  sortText = vim.NIL,
  textEdit = vim.NIL
}
```

**Comment by PhilT** [comment]
Yep! So fixed it by adding `vim.NIL` guards around `item.textEdit`, `item.insertText` and `item.sortText` in `sort_completion_items` and `get_compleition_word`. 

So is this something that needs fixing in Neovim LSP or the language server?

It seems like this has been fixed in other places (e.g. https://github.com/neovim/neovim/pull/12237)

**Comment by PhilT** [comment]
Looking at the [docs](https://neovim.io/doc/user/lua.html#vim.NIL) it seems `vim.NIL` is the correct form to use for dictionaries. If someone can confirm this I could potentially make a PR for this but I'll reiterate, this is the first time I've looked at Lua and LSP so I'll probably need some guidance.

**Comment by tjdevries** [comment]
Hey @PhilT Thanks for looking into this. Can you make an issue for this on neovim's core repo? That's where the issue is. If you do that, we can try and take a look at it there. I'd be happy to guide you through a PR as well if you're interested in submitting one (you can skip making the issue if you just want to go straight to the pr).

If you want to do that, then go ahead and tag me there and we can try and figure out how to make it work :)

**Comment by lithammer** [comment]
Seems like different language servers give different results. For example [jedi-language-server](https://github.com/pappasam/jedi-language-server) gives me `vim.NIL` while [pylance](https://github.com/microsoft/pylance-release) gives me plain `nil`.

**Comment by PhilT** [comment]
Hi @tjdevries, I've created an issue (referenced) to address this and need a bit of guidance before creating a PR. Thanks.

@lithammer, so far it appears `nil` is the default as this case is already handled by Neovim but not vim.NIL. LSPs already implemented would be returning `nil` otherwise they'd all be breaking. I think you're right though, it seems we need to handle both cases.

**Comment by PhilT** [comment]
This issue has now been fixed with https://github.com/neovim/neovim/pull/13174. Closing. Thanks all.
