### ISSUE TITLE
Addition of oxlint.

### ISSUE THREAD

**Issue by niksingh710** [neovim/nvim-lspconfig#3062]
### Description

Addition of [oxlint](https://github.com/oxc-project/oxc)

**Comment by emko** [comment]
have you gotten oxlint to work?

**Comment by niksingh710** [comment]
> have you gotten oxlint to work?

nope not yet

**Comment by IWANABETHATGUY** [comment]
I would like to have a try

**Comment by diegoulloao** [comment]
any new on this?

**Comment by DonIsaac** [comment]
Hi there 👋 Oxlint maintainer here. I'd be happy to help you guys get Oxlint set up if you're still struggling. I can check in on this issue, or you can DM me on Twitter (@Don_dev_) or on Discord.

**Comment by justinmk** [comment]
send a pr

**Comment by Lippiece** [comment]
> send a pr

Can you provide a link? I also don't see any support for oxlint in the code.
