### ISSUE TITLE
Multi workspace support for language servers broken after 0a1a2aa5

### ISSUE THREAD

**Issue by asmodeus812** [neovim/nvim-lspconfig#3080]
### Description

It seems that for some reason after this change it is required for a server to have single file support, otherwise it would short circuit and simply spawn new clients. Which imo, is a regression, i have no idea why single_file_support matters in this case.

```
function M:add(root_dir, single_file, bufnr)
  root_dir = util.path.sanitize(root_dir)
  local new_config = self.make_config(root_dir)
  local client = get_client(self._clients, root_dir, new_config.name)

  ---If single_file_mode is false then root_dir should match client otherwise start a new client
  --- this regression here would simply keep spawning new clients even though they might support multi ws.
  --- why does not having single file support imply forcibly spawning new instances ?
  if not client or (not single_file and client.config.root_dir and client.config.root_dir ~= root_dir) then
    return self:_start_new_client(bufnr, new_config, root_dir, single_file)
  end

  if self._clients[root_dir] or single_file then
    lsp.buf_attach_client(bufnr, client.id)
    return
  end

  -- make sure neovim had exchanged capabilities from language server
  -- it's useful to check server support workspaceFolders or not
  -- this is where the multi workspace support code branches off
  if client.initialized and client.server_capabilities then
    self:_attach_or_spawn(bufnr, new_config, root_dir, client, single_file)
  else
    self:_attach_after_client_initialized(bufnr, new_config, root_dir, client, single_file)
  end
end

```

@serranomorante ?

**Comment by asmodeus812** [comment]
Forgot to mention this method is called several times from other places where explicit false is passed in for singe file support param. This means that even if you have it enabled in the lanf server config and set to true, this does not change the behavior of this method.

**Comment by serranomorante** [comment]
Hello! There was an issue in which `:LspRestart` will spawn multiple new clients in single file mode (even when disabled) for no good reason. Imagine having 20 buffers opened on `:lcd apps/app1` and another 20 opened on `:lcd apps/app2` (across tabs in the same neovim instance). If your the only condition for creating new clients is `if not client` then as soon as you do `:LspRestart` it will spawn 20 new clients in single file mode (from either the `apps/app1` dir or the `apps/apps2`) dir.

Maybe doing `single_file == false` instead of `not single_file` could help?

**Comment by serranomorante** [comment]
I'm sure there must be more effective ways of fixing my previous issue... back then I just tried to do the most minimal change I could think of (basically 1 line) to not cause any regression 😭

**Comment by serranomorante** [comment]
I think is best for now to just revert my changes. That will solve this issue here.
My original solution (that caused this regression) don't seem to be working anymore which is strange. Sorry for the inconvenience.
