### ISSUE TITLE
(Help) [Pyright] - Pythonpath being set to .pyenv within the LSP logs, I have no clue why

### ISSUE THREAD

**Issue by doulighan** [neovim/nvim-lspconfig#3085]
### Description

Forgive me if `nvim-lspconfig` is not the correct place for this, maybe someone can point me in the right direction. After updating Lazy/Mason yesterday, pyright suddenly failed to identify import modules for some repos. `pyright --verbose` seems perfect, all of the search paths are correct, $PATH and PYTHONPATH seem perfect within neovim.

This seems to correlate with `basedpyright` propagating through the toolchain, but I haven't even installed it, let alone activate it. 

I've decided it must be down to one weird line in my LspLog:
`[INFO][2024-03-21 11:40:15] ...lsp/handlers.lua:584	'Setting pythonPath for service "/Users/<user>/Development/EDGE/edge-streaming-backend-service": "/Users/<user>/.pyenv/versions/edge-financial-3.6.8/bin/python"'`

I haven't used pyenv in years, I have no clue how this association is being made. Pyenv is nowhere on my $PATH. Theres no shell hooks. *I don't even have a ~/.pyenv folder!*

 Pyright and python say absolutely nothing about pyenv otherwise. `checkhealth` also gives me my correct `venv` environment, no pyenv.

1) Does anyone know how this association is being made?
2) Why is this ONLY visible buried deep in the logs?

**Comment by doulighan** [comment]
Oh my god, I solved it. I had an old .vscode/settings.json folder in the repo. I guess the LSP automatically reads from that, maybe a consequence of Pyright being a vscode LSP primarily? Or is that a Neovim behavior?

It still feels like LspInfo / checkhealth should be reporting this somehow, the pythonpath was being silently overridden. Is that strange behavior, or am I mistaken?

**Comment by glepnir** [comment]
lazy
