### ISSUE TITLE
Outdated rockspec

### ISSUE THREAD

**Issue by bojohnson5** [neovim/nvim-lspconfig#3089]
### Description

The rockspec at [LuaRocks](https://luarocks.org/modules/neovim/nvim-lspconfig) looks to be outdated. Is there an automated process to get the latest code?

**Comment by bojohnson5** [comment]
I think I understand what's happening. The rockspec is correct in pulling in the tagged `v0.1.7` release but that release was cut last year. To get more current code (to get new server configurations, for example) not included in that release I needed to install via `rocks.nvim` as `:Rocks install neovim/nvim-lspconfig rev=master` and things worked as I expected.

**Comment by mrcjkb** [comment]
It looks like the luarocks release is producing deprecation warnings with neovim 0.10.
Any chance we can get another release?
