### ISSUE TITLE
Use workspace root instead of package root for Rust

### ISSUE THREAD

**Issue by geigerzaehler** [neovim/nvim-lspconfig#310]
### How to reproduce the problem from neovim startup

I’m using `rust-analyzer` with the default configuration
~~~lua
require'nvim_lsp'.rust_analyzer.setup{}
~~~

I’m using a Rust workspace that contains multiple packages. The file layout looks like this
```
my-project
├── Cargo.toml
├── crate-a
│   └── Cargo.toml
└── crate-b
    └── Cargo.toml
```

### Actual behaviour

If I edit a file in `crate-a` then `crate-a` is used as the workspace root for rust-analyzer.

### Expected behaviour

I expect `my-project` to be used as the workspace root

---

I’d be happy to provide a patch.

**Comment by justinmk** [comment]
> I’d be happy to provide a patch.

thanks. see https://github.com/neovim/nvim-lspconfig/pulls?q=is%3Apr+is%3Aopen+root for previous PRs dealing with deciding the "root".

**Comment by csmoe** [comment]
A workaround for anyone found that new rust-analyzer process were launched for each crate: overwrite the default `Cargo.toml` pattern with `.git`
```lua
local lsp = require'nvim_lsp'
lsp.rust_analyzer.setup{
    root_dir = lsp.util.root_pattern('.git');
    settings = {}
}
```

**Comment by mjlbach** [comment]
How (concretely) should we implement this? We've gotten complaints about requiring a git repository for language server triggers (probably less of an issue with cargo). Should we just make it clear how to write local project configurations? See: #383

Alternatively should we *first* search for a git repo, and then fall back to Cargo.toml in the default config?
