### ISSUE TITLE
Can't use primary constructors with C# LSP (csharp_ls)

### ISSUE THREAD

**Issue by j0of** [neovim/nvim-lspconfig#3101]
### Description

Hi, I'm currently using the csharp_ls LSP with nvim-config. I'm working on a project using .NET 8, but using primary constructors causes errors to pop up in the editor:
```
The feature 'primary constructors' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version.
```
Additionally, the project builds and runs correctly without any errors. 
How can I resolve this?

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
