### ISSUE TITLE
Broken link - volar

### ISSUE THREAD

**Issue by AOjdanic** [neovim/nvim-lspconfig#3104]
### Description

Hello, im reading through the server configurations, and im looking at volar for vue. I work on a vue 2 project. 

Looking at the doc it says:
"Volar by default supports Vue 3 projects. Vue 2 projects need [additional configuration](https://github.com/vuejs/language-tools/tree/master/packages/vscode-vue#usage)."

however, this additional configuration link is broken.
Can you please provide steps how to configure volar on vue/nuxt 2?
The lsp just goes crazy when i try to use normal volar, so any help would be appreciated.

Thanks

**Comment by justinmk** [comment]
send a PR

**Comment by holic-cl** [comment]
Hi, somebody knows which is the broken link referenced?
