### ISSUE TITLE
ltex language server didn't let me change the language

### ISSUE THREAD

**Issue by GustavoJCL** [neovim/nvim-lspconfig#3135]
### Description

Hi, installed the ltex-ls and followed de config of the documentation to change the language, but it didn't work 
```
require("lspconfig").ltex.setup {
        settings = {
          ltex = {
            language = "es",
          },
        },
      }
```
but it didn't work, it still uses the same language

**Comment by cxwx** [comment]
it seems the total settings is not work correct:
I've tried 
```
settings = { ltex = { enabled = false,}} 
```
not work correctly

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
