### ISSUE TITLE
Problem with jdtls

### ISSUE THREAD

**Issue by MateiGoidan** [neovim/nvim-lspconfig#3141]
### Description

I've noticed a glitch with jdtls and nvim-lspconfig, using lazy nvim. When I create a new file, the warnings and errors don't show up as expected. However, when I open an older file, the warnings and errors start working again, even if I'm editing and saving that older file. Also, when I perform code actions, it seems to execute them for an older file, even if it's not currently open. When deleting that file it sticks onto the next file I choose to open, repeating the process for any new files . This appears to happens with only jdtls, pyright having no problems.

[Edit]
After more testing, it does not work for new java files. I created two java files and for the first one it works as intended. But still, for the last one it still doesn't work.

This is the info from LSP:
Language client log: /home/matei/.local/state/nvim/lsp.log
 Detected filetype:   java
 
 2 client(s) attached to this buffer: 
 
 Client: null-ls (id: 1, bufnr: [6])
 	filetypes:       lua, luau, java, python
 	autostart:       false
 	root directory:  /home/matei
 	cmd:             <function>
 
 Client: jdtls (id: 2, bufnr: [6])
 	filetypes:       java
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             /home/matei/.local/share/nvim/mason/bin/jdtls -configuration /home/matei/.cache/jdtls/config -data /home/matei/.cache/jdtls/workspace

And this is the configure file for lsps:

```lua
return {
	{
		"williamboman/mason.nvim",
		lazy = false,
		config = function()
			require("mason").setup()
			vim.keymap.set("n", "<leader>cm", ":Mason<CR>", {})
		end,
	},
	{
		"williamboman/mason-lspconfig.nvim",
		lazy = false,
		opts = {
			auto_install = true,
		},
	},
	{
		"neovim/nvim-lspconfig",
		config = function()
			local capabilities = require("cmp_nvim_lsp").default_capabilities()

			local lspconfig = require("lspconfig")
			lspconfig.lua_ls.setup({
				capabilities = capabilities,
			})
			lspconfig.clangd.setup({
				capabilities = capabilities,
			})
			-- lspconfig.hls.setup({})
			lspconfig.jsonls.setup({
				capabilities = capabilities,
			})
			lspconfig.jdtls.setup({
				capabilities = capabilities,
			})
			-- lspconfig.tsserver.setup({})
			lspconfig.pyright.setup({
				capabilities = capabilities,
			})
			-- lspconfig.rust_analyzer.setup({})

			-- Look on the github page to configure more keymaps!
			vim.keymap.set("n", "K", vim.lsp.buf.hover, {})
			vim.keymap.set("n", "gd", vim.lsp.buf.definition, {})
			vim.keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, {})
			vim.keymap.set("n", "<leader>d", vim.diagnostic.open_float)
		end,
	},
	{
		"hinell/lsp-timeout.nvim",
		dependencies = { "neovim/nvim-lspconfig" },
		config = function()
			vim.g.lspTimeoutConfig = {
				stopTimeout = 1000 * 60 * 5, -- ms, timeout before stopping all LSPs
				startTimeout = 1000, -- ms, timeout before restart
				silent = false,
			}
		end,
	},
	{
		"j-hui/fidget.nvim",
		tag = "v1.0.0",
		config = function()
			local fidgetconfig = require("fidget")
			fidgetconfig.setup()
		end,
	},
}
```

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
