### ISSUE TITLE
[Feature request]: Exclude pattern option

### ISSUE THREAD

**Issue by MrRoiz** [neovim/nvim-lspconfig#3144]
### Description

First of all, I'm not really sure if this concerns to `nvim-lspconfig` or `neovim` directly, sorry if it does not concerns to you!.

I have configured `bashls` but it starts running on every `.env` file that I open, I was looking into the docs but I didn't find a way to do it. it would be nice to have an option to omit some file patterns to trigger the lsp.

**Comment by glepnir** [comment]
check your bashls filetype config and it just sh filetype in default. so check your config first

**Comment by MrRoiz** [comment]
@glepnir It has everything as default, so the file type is set to `sh` but it recognize `.env` files as `sh`

**Comment by glepnir** [comment]
emm because neovim detect the env extension for  shebang. i think you can edit this behavoir by using something like

```lua
vim.filetype.add({
  extension = {
    env = 'test',
  },
})
```
