### ISSUE TITLE
luarocks package is outdated again

### ISSUE THREAD

**Issue by mrcjkb** [neovim/nvim-lspconfig#3162]
It looks like the latest release is producing deprecation warnings with neovim 0.10.
Any chance we can get another release?

_Originally posted by @mrcjkb in https://github.com/neovim/nvim-lspconfig/issues/3089#issuecomment-2118193183_

**Comment by justinmk** [comment]
https://github.com/neovim/nvim-lspconfig/releases/tag/v0.1.8
