### ISSUE TITLE
LspInfo reports `Running in single file mode` when current buffer is not in `root_dir`

### ISSUE THREAD

**Issue by stasjok** [neovim/nvim-lspconfig#3167]
### Description

When active buffer is outside of `root_dir` `LspInfo` reports root directory as `Running in single file mode`.

# Steps to reproduce

`minimal_init.lua`:
```lua
local lspconfig = require("lspconfig")

lspconfig.lua_ls.setup({
  -- Use dirname as root_dir
  root_dir = vim.fs.dirname,
})

-- Set up lspconfig commands
vim.cmd.runtime("plugin/lspconfig.lua")

-- Make tmpdir
local tmpdir = assert(vim.uv.fs_mkdtemp(vim.fs.joinpath(vim.uv.os_tmpdir(), "lspinfo_repro.XXXXXX")))

-- Open file in tmpdir
vim.schedule(function()
  vim.cmd.edit(vim.fs.joinpath(tmpdir, "file.lua"))
end)

-- Remove tmpdir after vim exit. It won't work if test files were saved there
vim.api.nvim_create_autocmd("VimLeave", {
  callback = function()
    vim.uv.fs_rmdir(tmpdir)
  end,
})
```

1. Run neovim: `nvim --clean --noplugin -u minimal_init.lua`. One buffer is active.
2. Run command: `:LspInfo`. Root directory:  `/tmp/lspinfo_repro.9qkBbS`.
3. Edit any file outside of root dir: `:edit /tmp/lspinfo_repro`.
4. `:LspInfo`. Root directory:  `Running in single file mode`.
5. Switch buffer back: `:buffer #`.
6. `:LspInfo`. Root directory:  `/tmp/lspinfo_repro.9qkBbS`.
7. Edit any file inside of root dir (change `9qkBbS` to your case): `:e /tmp/lspinfo_repro.9qkBbS/1234`.
8. `:LspInfo`. Root directory:  `/tmp/lspinfo_repro.9qkBbS`.
9. When switching to buffer created in 3. `LspInfo` again reports root directory as single file.

**Comment by glepnir** [comment]
it outside so the no root it run in single file mode what's the problem ?

**Comment by stasjok** [comment]
> it outside of the root then it run in single file mode what's the problem ?

Client itself is _not_ outside of the root dir, but it's wrongly reported as such. The problem is wrong info reported by `LspInfo`. Maybe a screenshot would help to understand what's the problem?

![image](https://github.com/neovim/nvim-lspconfig/assets/1353637/5a79a05e-6309-4d4a-aed5-70cd48545213)

All those servers are **not** running in single file mode. They all have its own root_dir. So it's strange to report it like this.

**Comment by glepnir** [comment]
I remeber there has a problem after i add workspace relate stuff see https://github.com/neovim/nvim-lspconfig/pull/2648 I will check it later.
