### ISSUE TITLE
When codelens is turned on in version 0.10.0, there is a non-stop search phenomenon.

### ISSUE THREAD

**Issue by czfadmin** [neovim/nvim-lspconfig#3177]
### Description

When codelens is turned on in version 0.10.0, there is a non-stop search phenomenon.The situation in the picture appears.
![image](https://github.com/neovim/nvim-lspconfig/assets/13393959/2d691baa-3fd0-49a9-9b5d-97f751a4358b)

**Comment by justinmk** [comment]
can't do anything with this report since it doesn't provide steps to reproduce the issue.

p.s. installing a bunch of plugins is not an acceptable way to reproduce an issue
