### ISSUE TITLE
Possibly wrong order in root_dir for tsserver

### ISSUE THREAD

**Issue by DanilaMihailov** [neovim/nvim-lspconfig#3179]
### Description

Is there a reason for this order?
https://github.com/neovim/nvim-lspconfig/blob/d70633830acf605ec03d9728698d9e7232442eb4/lua/lspconfig/server_configurations/tsserver.lua#L15

I see [this](https://github.com/neovim/nvim-lspconfig/commit/3f6d120721e3a2b2812af43e6a8ba5522aa421c5) commit moved tsconfig.json before package.json, but **js**config.json is left after package.json. This is a little bit confusing. Maybe jsconfig.json should be before package.json?

vscode seems to have an order like this `['tsconfig.json', 'jsoncfig.json' ...]` if this is any indication. 

Of course I fixed this in my config by just changing this field, but maybe it should be default? 
```lua 
root_dir = util.root_pattern('tsconfig.json', 'jsconfig.json', 'package.json', '.git')
```

**Comment by glepnir** [comment]
It would be good if any official document describes root directory priority or refer to vscode related

**Comment by justinmk** [comment]
> Maybe jsconfig.json should be before package.json?

Seems reasonable

**Comment by DanilaMihailov** [comment]
Seems like a simple change, I can create a PR
