### ISSUE TITLE
Auto attach to exists buffer  while call `rquire("lspconfig").lua_ls.setup()`

### ISSUE THREAD

**Issue by AbaoFromCUG** [neovim/nvim-lspconfig#3182]
### Description

When I call `rquire("lspconfig").lua_ls.setup()`, lspconfig don't attach to existing lua buffers

Situation:
In my config file `nvim/init.lua`, I use l use some auto-session plugin to restore a session, which will load files to buffers, then I call the `rquire("lspconfig").lua_ls.setup()`  to setup lua-language-server.

I can't guarantee the order of `restore session` and `setup lspconfig` （because I use the asynchronous function to do some check）， in fact, the `restore session` usually before `setup lspconfig`. Therefore, the `lua_ls` will don't attach to the existing buffers, and show ` Other clients that match the filetype: lua` in `:LspInfo`

Should or how to enable lspconfig to attach to existing buffers?

My current temporary solution is to execute `:LspStart lua_ls` manually

thanks

**Comment by glepnir** [comment]
```lua
    local config = require('lspconfig.configs')[server_name]
    if config then
      config.launch()
      return
    end

```
