### ISSUE TITLE
Feature request: Adding single file support for lsp attach

### ISSUE THREAD

**Issue by muneebusmani** [neovim/nvim-lspconfig#3187]
### Description

it is really annoying sometimes when the cwd functions to attach lsps to current buffer dont work because sometimes a ppl are not on a framework and not on git (sometimes) and then they wonder why the lsp wont attach,
for eg if i do some php scripting , just core php then there is no lsp attached if i dont initialize git, ik it is stupid to do projects without git but still the lsp should be able to attach to current file via some kinda method or so, it would be really helpful if this feature gets added to nvim-lspconfig , Thanks.

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
