### ISSUE TITLE
Multiple instances of lua-language-server (sumneko_lua) are running when I open a single file

### ISSUE THREAD

**Issue by ahmedelgabri** [neovim/nvim-lspconfig#319]
- `nvim --version`: 
```
NVIM v0.5.0-1869f86e3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20200809-42220-drihg/build/config -I/tmp/neovim-20200809-42220-drihg/src -I/usr/local/include -I/tmp/neovim-20200809-42220-drihg/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200809-42220-drihg/build/src/nvim/auto -I/tmp/neovim-20200809-42220-drihg/build/include
Compiled by ahmed@pandoras-box

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-1869f86/share/nvim"

Run :checkhealth for more info
```

- nvim-lsp version(commit hash): `3f72236`

- `:checkhealth` 

```

health#targets#check
========================================================================
  - OK: No conflicting mappings found

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: sumneko_lua: configuration checked.
  - INFO: ocamlls: configuration checked.
  - INFO: yamlls: configuration checked.
  - INFO: pyls: configuration checked.
  - INFO: cssls: configuration checked.
  - INFO: rls: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: bashls: configuration checked.

health#gitmessenger#check
========================================================================
  - OK: +job is available to execute Git command
  - OK: Git command `git` is available: git version 2.28.0
  - OK: Floating window is available for popup window

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion source are valid

## snippet source
  - OK: You are using vim-vsnip as your snippet source

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Disabled (g:loaded_ruby_provider=0).

## Node.js provider (optional)
  - INFO: Node.js: v14.7.0
  - INFO: Nvim node.js host: /usr/local/bin/neovim-node-host
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

## Perl provider (optional)
  - INFO: Disabled (g:loaded_perl_provider=0).
```

- What language server(If the problem is related to a specific language server): sumneko_lua
- Operating system/version: macOS 10.15.6
- Terminal name/version: Kitty 0.18.2
- `$TERM`: 
  - Inside TMUX: `tmux-256color`
  - Outside TMUX: xterm-kitty

### How to reproduce the problem from neovim startup

Open any `.lua` file, in my case it's this file https://github.com/ahmedelgabri/dotfiles/blob/e71e9ac3d319cc0af909e7156212ae445de27a10/roles/vim/files/.vim/lua/lsp.lua

### Actual behaviour

- It locks the editor for a couple of seconds
- Runs multiple instances of the LSP 
- Sometimes even can consume 90+% CPU (can't reproduce this now, but saw it happening multiple times)

<img width="1270" alt="Screenshot 2020-08-09 at 17 02 51" src="https://user-images.githubusercontent.com/63876/89735541-85d27080-da63-11ea-99d2-8f62db4e6e46.png">
<img width="1144" alt="Screenshot 2020-08-09 at 17 01 05" src="https://user-images.githubusercontent.com/63876/89735543-879c3400-da63-11ea-871d-1d444f693880.png">

### Expected behaviour

- Run async _if possible_ & don't lock my editor
- Run a single instance of the LSP

**Comment by justinmk** [comment]
I seem to recall @norcalli mentioning that sumneko server had various problems. Maybe he can comment on his current setup for Lua LSP

**Comment by ruifm** [comment]
I'm having the same issue

**Comment by p00f** [comment]
They don't shut down after closing neovim too

**Comment by elianiva** [comment]
I think this has been improved since then? I never experienced it anymore and they always shut down after closing Neovim. I also tried to open 4 files and it only launch 1 instance of lua-language-server. Though, the LSP sometimes uses a ton of my CPU but it never locks my Neovim, it's still usable. After several seconds, it went back to normal.

**Comment by mjlbach** [comment]
I personally haven't noticed this in awhile, I also feel like this is an upstream issue and we can't/shouldn't try to implement more advanced process management for language servers that refuse a shutdown command. The only thing we could try to do is store the PID and pkill it when it fails, but if the language server crashes (as they do), I don't know that we can reliably identify that and not fill whatever process ends up using the same PID.

**Comment by ahmedelgabri** [comment]
I didn't notice this happening either for a while & after merging this #498 I don't think it makes sense to keep this open anymore.

**Comment by mjlbach** [comment]
Unfortunately a lot of bugs seem to be caused by having older language servers, and before when we were managing installs via neovim they would become rather out of date 😞  I'm glad sumneko seems to be working now!

**Comment by nyngwang** [comment]
@mjlbach Thank you!

**Comment by eo1989** [comment]
Apologies to pull this back up, but this issue is still lurking. It also occurs with Null-ls and Pyright.
Im running sumneko_lua (via brew) 2.6.7 and still have the multiple-spawn issue occurring. Anytime I open new files within the same directory, or a same project, a new LSP is spawned. The picture is much like the two posted beforehand.

**Comment by KyleErhabor** [comment]
I've been experiencing the same issue, except a new LSP is spawned whenever the file is written to (e.g. `:w`).

**Comment by ssipos90** [comment]
yep, it still happens to me too. If I work on my lua config, my RAM gets full in 10 minutes and OOM killer triggers.

**Comment by histeward** [comment]
`:lua vim.lsp.stop_client(vim.lsp.get_active_clients())`

This command got rid of the multiple instances for me. It's just a temporary workaround to get rid of the instances while working on the config but it gets rid of the annoying instances.

Multiple instances occurred when I sourced the file `:so %`

**Comment by histeward** [comment]
`:lua vim.lsp.stop_client(vim.lsp.get_active_clients())`

This command got rid of the multiple instances for me. It's just a temporary workaround to get rid of the instances while working on the config.

Multiple instances occurred when I sourced the file `:so %`

**Comment by histeward** [comment]
`:lua vim.lsp.stop_client(vim.lsp.get_active_clients())`

This command got rid of the multiple instances for me. It's just a temporary workaround to get rid of the instances while working on the Lua file.

Multiple instances occurred when I sourced my lsp config file.

**Comment by Aaron-von-Awesome** [comment]
> `:lua vim.lsp.stop_client(vim.lsp.get_active_clients())`
> 
> This command got rid of the multiple instances for me. It's just a temporary workaround to get rid of the instances while working on the Lua file.
> 
> Multiple instances occurred when I sourced my lsp config file.

Thank you for your tip @histeward !

I ended up using this key map in my `init.lua`, so I can reload my settings quickly and avoid multiple LSP servers for the same file type from running:
```lua
vim.keymap.set("n", "<leader><CR>", ":execute 'lua vim.lsp.stop_client(vim.lsp.get_active_clients())' | luafile ~/.config/nvim/init.lua<CR>", {noremap = true})
```

**Comment by anthony-S93** [comment]
@ahmedelgabri 

I myself discovered this issue today while I was trying to set up `nvim-lspconfig`. But because all my plugin configurations are inside `packer.nvim`'s plugin specification file (`plugins.lua`), I managed to solve this by adding a small chunk of logic that would skip the `setup()` call for `sumneko_lua` if there is already an instance of it attached to the buffer. 

Here's what it would look like in your `plugins.lua` file: 

```lua
vim.cmd([[
      augroup packer_user_config
          autocmd!
          autocmd BufWritePost plugins.lua source <afile> | PackerCompile
      augroup end
  ]])

...Your other config...

--Setting up language servers
local lspconfig = require("lspconfig")
local start_sumneko_lua = true --boolean defaults to true, otherwise, the server will never start
local current_buf_id = vim.api.nvim_get_current_buf()
local servers_attached_to_current_buf = vim.lsp.get_active_clients({bufnr = current_buf_id})

for _, server in ipairs(servers_attached_to_current_buf) do
    if server.name == "sumneko_lua" then --an instance of sumneko_lua is already attached to the buffer
        start_sumneko_lua = false 
    end
end

--After that, all you have to do is to wrap sumneko lua's setup() call inside a conditional using the boolean

if start_sumneko_lua then
    lspconfig.sumneko_lua.setup{
         -- yada yada yada
    }
end

--Other servers don't need this, so their setup can be called as usual
lspconfig.pyright.setup{

}

--yada yada yada...

```
The idea is to wrap an `if`-conditional around the `lspconfig.sumneko_lua.setup()` call and then decide whether or not to start the language server based on a "flag." Turning off `single_file_support` is certainly a quick and dirty way to make this issue go away, but sometimes we need `single_file_support` as well. If that's what you need, then this is one way to do it. I've tested it on my setup and haven't run into issues so far. The code seems to be working fine for now.

**Comment by nyngwang** [comment]
In my case, a new `sumneko_lua` LSP client is spawned on different `root directory`, even with the `single_file_support` set to `true`(this is set upon nvim-lspconfig):

<img src="https://user-images.githubusercontent.com/24765272/191458771-492db8d2-e8e4-4e4e-bb56-53f4a3a47d7f.png" width="500">
