### ISSUE TITLE
 Most Lsp commands not working.

### ISSUE THREAD

**Issue by Frusadev** [neovim/nvim-lspconfig#3193]
### Description

Most lsp commands like LspRestart, and LspStart... fail. See this [issue](https://github.com/NvChad/NvChad/issues/2865#issue-2327512597)

**Comment by glepnir** [comment]
use latest release neovim

**Comment by Frusadev** [comment]
I forgot to mention, i'm already using neovim's latest release. But i'm still experiencing those errors.
