### ISSUE TITLE
Get root directory

### ISSUE THREAD

**Issue by Kyle-Thompson** [neovim/nvim-lspconfig#320]
Is there a way to query what the LSP detects as the root directory? I can't seem to find one.

**Comment by himansingh241** [comment]
There's a `root_dir` parameter with most of the language servers that you can set to detect root directory.

**Comment by Kyle-Thompson** [comment]
What would be the syntax to query that? Like with clangd or rust analyzer for example if it's specific to each LS.

I have an understanding of how to set the root directory but I'm still unclear on how to query it's value.

**Comment by himansingh241** [comment]
You can do something like this :
``` 
local nvim_lsp = require'nvim_lsp'
nvim_lsp.clangd.setup{
  root_dir = nvim_lsp.util.root_pattern('.git');
}
```

**Comment by lithammer** [comment]
@himansingh241 you're misunderstanding him. He's asking how query for the _calculated value_ of `root_dir`, not how to set it.

So for example, given this:

```lua
nvim_lsp.clangd.setup {
  root_dir = nvim_lsp.util.root_pattern('foo', 'bar', 'baz')
}
```

What's the value of `root_dir` when the language server starts in some directory X?

**Comment by svvac** [comment]
I had the same issue. Solved it with #363.

**Comment by teto** [comment]
you could use checkhealth with this branch https://github.com/neovim/neovim/pull/12578

**Comment by mjlbach** [comment]
@Kyle-Thompson Technically this is exposed via `:help vim.lsp.buf.list_workspace_folders()` which stores the first root directory on server intitialization by default

**Comment by mjlbach** [comment]
I'm going to close since `:lua vim.lsp.buf.list_workspace_folders() `does list the (true) root directory sent to the server, as well as any additional roots you add in core, and I just added it to the example mappings in the readme

**Comment by DavidePatria** [comment]
> I'm going to close since `:lua vim.lsp.buf.list_workspace_folders() `does list the (true) root directory sent to the server, as well as any additional roots you add in core, and I just added it to the example mappings in the readme

this function doesn't work as of today on neovim nightly, neither using pylsp nor clangd.

**Comment by mjlbach** [comment]
Check that you are not running in single file mode

**Comment by DavidePatria** [comment]
LspInfo (thanks for the edit) show the git root I would expect, but the function doesn't return anything, not even an error. I'm kinda ok for now, thanks
