### ISSUE TITLE
README does not explain what this repo does

### ISSUE THREAD

**Issue by hk0i** [neovim/nvim-lspconfig#3202]
### Description

I can see that a lot of careful work and planning went into this repository and I appreciate the effort that went into this project.

It appears like the README doesn't explain what this repository is for and how it's useful. It's only until I installed the plugin, then ran `:help lspconfig` that I was able to determine that this repository is a collection of configurations.

I'm sure it's obvious for those who are already into it but this is my first time seeing lua in general, and I don't really know what the pros/cons are to this over something else or even if there's an alternative. I'm actually trying to follow a guide to set up Swift support in nvim, and even from the guide I followed I'm not sure if I need this repository or if I just need to create a lua configuration file of my own.

1. Is lua configuration built into neovim or does this plugin add support for it?
2. Is this a plugin actually or is this just a bunch of community vim configurations?

I know most of these seem like silly questions but the README feels like it's geared to people who already know why they are here and that might be why I'm lost. While the instructions on installing are fairly clear it's still not clear to me why I need any of this in the first place.

Thanks again

**Comment by justinmk** [comment]
first 2 lines:

> [Configs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md) for the [Nvim LSP client](https://neovim.io/doc/user/lsp.html) (:help lsp).

<img width="917" alt="image" src="https://github.com/neovim/nvim-lspconfig/assets/1359421/4bd3dd61-a51b-430a-a19b-8233d87e6cfc">


however, it's easy to miss. will make it clearer

**Comment by hk0i** [comment]
Thanks for the quick response.
That makes sense, maybe something like,

"A collection of user-contributed configuration files for the Nvim LSP client"

Thanks again!
