### ISSUE TITLE
Rust analyzer starting two instances when script is opened

### ISSUE THREAD

**Issue by Silzinc** [neovim/nvim-lspconfig#3205]
### Description

Hello. Whenever I open a cargo project, when the first rust script is opened in neovim (lazyvim distro), two rust analyzers start indexing the project. One client is called "rust-analyzer" and the other one "rust_analyzer" (see picture below). This is pretty annoying, as they end up eating twice the RAM needed (which is already fairly high for one instance). 

I tried killing one of the processes : no matter which one I kill, the other works just fine and I still have my diagnostics, but the dead comes back when I open a new script. I do not have any additional configuration for lspconfig. I have a rustacean config, but deleting it does not change anything.

Thank you in advance for helping me out !

![image](https://github.com/neovim/nvim-lspconfig/assets/128738169/417975f4-bd5d-48e3-8144-87fe50b50df3)

**Comment by glepnir** [comment]
ask in rustacean
