### ISSUE TITLE
In config, my own settings for lemminx lsp isn't applied

### ISSUE THREAD

**Issue by asknet** [neovim/nvim-lspconfig#3210]
### Description

Hi,
I am attempting to customize the settings for Lemminx LSP, but it doesn't work as expected. When I directly modify the default configuration provided in the plugin repository with my own settings, it functions properly. (I did this just to test the settings works)

Below is my config that's not working:

Appreciate the help! Thanks!

```lua
  {
    -- LSP Configuration & Plugins
    'neovim/nvim-lspconfig',
    dependencies = {
      -- Automatically install LSPs to stdpath for neovim
      { 'williamboman/mason.nvim', config = true },
      'williamboman/mason-lspconfig.nvim',

      -- Useful status updates for LSP
      -- NOTE: `opts = {}` is the same as calling `require('fidget').setup({})`
      { 'j-hui/fidget.nvim', tag = 'legacy', opts = {} },

      -- Additional lua configuration, makes nvim stuff amazing!
      'folke/neodev.nvim',
    },
        config = function ()
            require('lspconfig').lemminx.setup{
                settings = {
                    xml = {
                        trace = {
                            server = "verbose"
                        },
                        logs = {
                            client = "true"
                        },
                        fileAssociations = {
                            {
                                systemId = '/xyz/Wrkbox/dotfiles/.config/sfdx/xml/flow.xsd',
                                pattern = '**.flow-meta.xml'
                            }
                        },
                    }
                }
            }

        end
  },

```

**Comment by justinmk** [comment]
Thanks for your report. The configs in this repo are unsupported and provided only as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- (optional, but very helpful): by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios
