### ISSUE TITLE
Custom eslint settings not used

### ISSUE THREAD

**Issue by ClementDreptin** [neovim/nvim-lspconfig#3211]
### Description

Passing custom settings to `require("lspconfig").eslint.setup()` doesn't seem to have any effect.

### Config

```lua
-- Loaded with lazy.nvim
return {
  "neovim/nvim-lspconfig",
  config = function()
    require("lspconfig").eslint.setup({
      settings = {
        enable = false,
      },
    })
  end
}
```

### Expected behavior

I expect eslint not to report any diagnostics.

### Actual behavior

Eslint still reports diagnostics.

### What I tried

- This doesn't seem to be an issue with `vscode-eslint-language-server` because the `enable` option works as expected within vscode.
- I tried to start from a [LazyVim](https://www.lazyvim.org/) config and add custom settings to the eslint lsp, and I have the same problem.
- I tried to pass different shapes of objects to `setup`, and nothing made a difference.
  - `{ settings = { enable = false } }`
  - `{ settings = { eslint = { enable = false } } }`
  - `{ enable = false }`
  - `{ eslint = { enable = false } }`

I don't know if this is a bug, or if I'm missing something. If this is just a misunderstanding of the configuration on my part, I'm sorry.

**Comment by martenmatrix** [comment]
I've also tried [these solutions](https://www.reddit.com/r/neovim/comments/119rvhl/how_do_i_disable_an_eslint_rule_globally/), however they did not seem to have an effect.

**Comment by ClementDreptin** [comment]
> Maybe related? https://github.com/neovim/nvim-lspconfig/issues/2797
I'm not sure because `eslint` seems to be the only one not using the custom config. I have a custom config for `lua_ls` and `nvim-lspconfig` passes it with no issues.

**Comment by Delerme** [comment]
The setting you're looking for might be `validate` based on the language server settings: https://github.com/microsoft/vscode-eslint/blob/55871979d7af184bf09af491b6ea35ebd56822cf/server/src/eslintServer.ts#L217

Setting `validate = false` worked for me

**Comment by ClementDreptin** [comment]
I just tested `validate` and can confirm it works for me as well, so some settings seem to be used after all.

I wasn't actually looking for a way to disable eslint though, that's what I did in my example to make it easy to understand. I was trying to change the value of [`run`](https://github.com/microsoft/vscode-eslint/blob/55871979d7af184bf09af491b6ea35ebd56822cf/server/src/eslintServer.ts#L226) to run eslint `onSave` instead of `onType` because the LSP is unacceptably slow on my machine.

**Comment by Delerme** [comment]
Ah yea, I was looking for the same thing and that's how I found this issue

What I discovered is since Neovim 10 the lsp is using [pull diagnostics](https://github.com/neovim/neovim/issues/22838) so the setting doesn't have an effect, because Neovim is explicitly requesting diagnostics when typing. Instead, you'll have to adjust the rate of neovim asking for diagnostics. I found two settings for the lsp setup function: `allow_incremental_sync` and `debounce_text_changes`

Check out `:h lsp-client`and look at the `flags` params. For eslint in particular, turning off incremental sync and setting debounce to 1s worked well for me.

**Comment by ClementDreptin** [comment]
> Instead, you'll have to adjust the rate of neovim asking for diagnostics. I found two settings for the lsp setup function: allow_incremental_sync and debounce_text_changes

I just tried and it works great! I was supposed to do something like this, right?
```lua
require("lspconfig")eslint.setup({
  on_init = function(client)
    client.flags.allow_incremental_sync = false
    client.flags.debounce_text_changes = 1000
  end,
})
```

> An alternative I didn't try was to change the capabilities in the setup to disable pull diagnostics for eslint, that way the run setting is used. If you try this approach, let me know how it goes!

I can try but I what would I need to set the capabilities to? I tried to print the default capabilities returned by `cmp-nvim-lsp` and that's what I have
```
{                                                                                                                                                       
  textDocument = {                                                                                                                                      
    completion = {                                                                                                                                      
      completionItem = {                                                                                                                                
        commitCharactersSupport = true,                                                                                                                 
        deprecatedSupport = true,                                                                                                                       
        insertReplaceSupport = true,                                                                                                                    
        insertTextModeSupport = {                                                                                                                       
          valueSet = { 1, 2 }                                                                                                                           
        },                                                                                                                                              
        labelDetailsSupport = true,                                                                                                                     
        preselectSupport = true,                                                                                                                        
        resolveSupport = {                                                                                                                              
          properties = { "documentation", "detail", "additionalTextEdits", "sortText", "filterText", "insertText", "textEdit", "insertTextFormat", "inse
rtTextMode" }                                                                                                                                           
        },                                                                                                                                              
        snippetSupport = true,                                                                                                                          
        tagSupport = {                                                                                                                                  
          valueSet = { 1 }                                                                                                                              
        }                                                                                                                                               
      },                                                                                                                                                
      completionList = {                                                                                                                                
        itemDefaults = { "commitCharacters", "editRange", "insertTextFormat", "insertTextMode", "data" }                                                
      },                                                                                                                                                
      contextSupport = true,                                                                                                                            
      dynamicRegistration = false,                                                                                                                      
      insertTextMode = 1                                                                                                                                
    }                                                                                                                                                   
  }                                                                                                                                                     
}
```
I expected to have a `diagnostic` table inside of the `textDocument` table.

**Comment by ClementDreptin** [comment]
Hey, sorry for the delay, I've been pretty busy.

I wasn't able to mess around with the eslint lsp capabilities but I got a solution to my initial problem. I saw that you created [an issue on the neovim repo](https://github.com/neovim/neovim/issues/29792) so I think the conversation can continue there and we can close this issue now.

Thanks again for your very valuable help!

**Comment by irvin93d** [comment]
> > Instead, you'll have to adjust the rate of neovim asking for diagnostics. I found two settings for the lsp setup function: allow_incremental_sync and debounce_text_changes
> 
> I just tried and it works great! I was supposed to do something like this, right?
> 
> require("lspconfig").eslint.setup({
>   flags = {
>     allow_incremental_sync = false,
>     debounce_text_changes = 1000,
>   },
> })
> > An alternative I didn't try was to change the capabilities in the setup to disable pull diagnostics for eslint, that way the run setting is used. If you try this approach, let me know how it goes!


Thought this didn't work for me first because eslint was still lagging behind and made it completely unusable. After a lot of debugging I found that debouncing `tailwindcss` as well fixed my issue:
```tsx
require("lspconfig").eslint.setup({
  flags = {
    allow_incremental_sync = false,
    debounce_text_changes = 1000,
  },
})
require("lspconfig").tailwindcss.setup({
  flags = {
    debounce_text_changes = 1000,
  },
})
```
Not sure why it's relevant, but figured I'll mention it if someone else runs into the same issue!
