### ISSUE TITLE
koka language server doesn't attach

### ISSUE THREAD

**Issue by MangoIV** [neovim/nvim-lspconfig#3212]
### Description

For some reason, the koka language server doesn't attach, I don't know if there's something wrong with the configuration (there definitely is, but that should become obvious only *after* it attaches) but it just never attaches. `:set ft?` shows koka. 

Does anybody see what the issue there could be? Thanks in advance!

**Comment by glepnir** [comment]
i think the root dir detect not correct

**Comment by MangoIV** [comment]
can I just overwrite it with 
```lua 
lspconfig.koka.setup({
	cmd = { "koka", "--language-server", "--lsstdio" },
        root_dir = function(fname)
            return require'lspconfig.util'.find_git_ancestor(fname)
        end,
})
``` 
in my `init.lua`?

**Comment by glepnir** [comment]
yup.

**Comment by glepnir** [comment]
I think you can create a pr for correct root detect of koka server.

**Comment by MangoIV** [comment]
I should.

**Comment by MangoIV** [comment]
@glepnir that didn't fix the issue, it still says `0 clients attached to this buffer`. Is there anything else I have to do besides setting
```lua 
vim.filetype.add({
  extension = { 
    kk = "koka",
  }, 
})
```
in my `init.lua`?

**Comment by MangoIV** [comment]
I have set this. `:set ft?` returns `koka`. It still doesn't attach.

**Comment by glepnir** [comment]
then your project has .git folder ?

**Comment by MangoIV** [comment]
the issue was that the plugin set the filetype to `kk` when it should have been `koka`
