### ISSUE TITLE
rust-analyzer: -32603: Invalid offset LineCol xxx

### ISSUE THREAD

**Issue by OliverChao** [neovim/nvim-lspconfig#3233]
### Description

rust-analyzer 0.3.2029-standalone (a5b21ea0a 2024-07-07)
nvim-lspconfig: { "branch": "master", "commit": "216deb2d1b5fbf24398919228208649bbf5cbadf" }
rustc version: rustc 1.79.0 (129f3b996 2024-06-10)
nvim version: I tried nvim-0.10 stable and nvim v0.11.0-dev-408+gb1aa8f5eb

---

## Problem
Some times, when deleting all content from one rust file, rust-analyzer would complain that  error `rust_analyzer: -32603: Invalid offset LineColxxx`
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/1aa27a48-9c1e-4e5e-a4e2-ab5509b5b72f">

> I have tried vscode, and it works fine without any complaint.

## how to reproduce
```bash
1. run  `cargo new hello_world`
```

```rust
2. copy following content to main.rs
#![allow(unused)]
struct Solution {}
use std::collections::HashMap;
fn main() {
    println!("hello_world");
}

```
```
3. Delete all content and will see some errors
```

There is one related rust-analyzer issue: https://github.com/rust-lang/rust-analyzer/issues/17289

**Comment by glepnir** [comment]
create  on neovim core, because is a problem of lsp module.

**Comment by cybergazer** [comment]
No other lsp has this issue, it has to be with rust_analyzer

**Comment by Universal-Invariant** [comment]
I just got this error when pasting a function into a rust file. It is a continuous error. The line was the last line of hte file and I was using code folding and as I was expanding function the error went away. It may be coincidence or some issue with code folding breaking the analyzer.

I saw someone's comment about using cargo to install rust analyzer and it seemed to have worked.
