### ISSUE TITLE
Setup arguments are ignored (for lua_ls and ltex)

### ISSUE THREAD

**Issue by mrseanman** [neovim/nvim-lspconfig#3234]
### Description

See #2797 (similar story except my issue is persistent with minimal config).

Any arguments passed to `lua_ls` on `setup` are ignored. In particular, if I inspect using `:Mason`, 'Lua.completion.callSnippet' is still the default `"Disable"`, rather than `"Replace"` as specified.

See my minimal config [here](https://github.com/mrseanman/kickstart.nvim/blob/minimal_example/init.lua). This is a stripped back version of [kickstart](https://github.com/nvim-lua/kickstart.nvim), where the issue is also present.
I have also tried to pass arguments to `ltex`, with the same issue. I am using `lua_ls` here as an example where I can be sure I haven't made some stupid mistake. I have not tested any other LSPs, the issue may or may not be present for them.

This has been tested on most recent nightly and stable nvim. I have tried a clean nvim install and clean install of all plugins with no change.

I would really appreciate some guidance on what might be going wrong, I am not experienced, but am fairly confident the people who wrote kickstart are! And that this ought to work.
Many thanks

Neovim verison:
NVIM v0.11.0-dev-411+geab535e10                                                                    
Build type: RelWithDebInfo                                                                         
LuaJIT 2.1.1720049189    

OS: 
Debian 12

**Comment by glepnir** [comment]
works fine for me . there already have minimal for test https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua

**Comment by mrseanman** [comment]
> works fine for me . there already have minimal for test https://github.com/neovim/nvim-lspconfig/blob/master/test/minimal_init.lua

Do you have any insight as to what might be going wrong?

I have tried the minimal config you linked, passing some random settings to pyright, without any change.

**Comment by glepnir** [comment]
if something wrong you get some informations from log maybe. log in `vim.fn.stdpath('log')`
