### ISSUE TITLE
[Feature Request]: sqlfluff configuration

### ISSUE THREAD

**Issue by Drew-Daniels** [neovim/nvim-lspconfig#3279]
### Description

Would be nice if we could configure [`sqlfluff`](https://github.com/sqlfluff/sqlfluff) as an LSP server with `nvim-lspconfig`, similar to `eslint`, so we can can get in-buffer diagnostics

Example linter errors from `sqlfluff` on `test.sql`:

![image](https://github.com/user-attachments/assets/76d4e59f-72a6-4691-8116-75b7f02c842b)

Just an example of how diagnostics aren't shown because I haven't configured `sqlfluff` as an LSP with `nvim`:
![image](https://github.com/user-attachments/assets/93850cd6-6ae9-4770-8ce0-346892eb6202)

**Comment by justinmk** [comment]
Not clear what you are asking. If you are asking for lspconfig to include a config for sqlfluff, just send a PR.
