### ISSUE TITLE
vim.lsp.buf.hover() immediately jumps to floating window when 2 LSPs are active

### ISSUE THREAD

**Issue by paulodiovani** [neovim/nvim-lspconfig#3282]
### Description

I have configured both `solargraph` and `sorbet` for Ruby files,
so when I call `vim.lsp.buf.hover()` on a name (currently mapped to `<F9>`) I have an unexpected behavior that really looks like a bug.

It seems like it happens when both LSPs provide hover for that name, otherwise it works fine.
I'm not sure if this happens with other LSPs.

### Expected behavior

- Show hover/floating window for the name under cursor
- If more than one LSP implements `hover`, either
  + show both at same time, on a single floating window
  + show one at each time, allowing to use a mapping to cycle between them (e.g. `[1/2]`)
  + show one at each time, cycling automatically on first, second, and subsequent calls
  + show one at each time, asking from a menu

### Actual behavior

- When there is a single `hover` for the name
  + show that in a floating window as expected
  + does not jump to floating window
- When there is more than one `hover` for that name
  + randomly shows the hover from one of the LSPs
  + immediately jumps to the floating window

The major issue is that it immediately jumps to the floating window, interrupting workflow.

I hope there is a way to fix this using some custom configuration, but I didn't find a way so far.

### My current configuration

https://github.com/paulodiovani/dotfiles/blob/aed80ef/home/user/.config/nvim/lua/completion.lua

### Steps to reproduce

1. Setup both `solargraph` and `sorbet` with `nvim-lspconfig`, optinally using `Mason`.

output of `:LspInfo`
```
 Client: sorbet (id: 2, bufnr: [4])
 	filetypes:       ruby
 	autostart:       true
 	root directory:  /Users/diovani/Development/Ruby/sorbet-lsp-test
 	cmd:             /Users/diovani/.local/share/nvim/mason/bin/srb tc --lsp --disable-watchman /Users/diovani/Development/Ruby/sorbet-lsp-test
 
 Client: solargraph (id: 3, bufnr: [4])
 	filetypes:       ruby
 	autostart:       true
 	root directory:  /Users/diovani/Development/Ruby/sorbet-lsp-test
 	cmd:             /Users/diovani/.local/share/nvim/mason/bin/solargraph stdio
```

2. Make sure to create a mapping.

e.g.
```lua
local bufopts = { noremap = true }
vim.keymap.set({ 'n', 'i' }, '<F9>', vim.lsp.buf.hover, bufopts)
```

3. Create a ruby application and include `sorbet`

`Gemfile`
```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "sorbet-runtime", "~> 0.5.11537"
```

`main.rb`
```ruby
# typed: true
# frozen_string_literal: true

require 'sorbet-runtime'

# sample class
class SampleClass
  extend T::Sig

  sig { params(greet: String, who: String).void }
  def some_method(greet, who)
    puts "#{greet} #{who}"
  end
end

SampleClass.new.some_method('Hello', 'world')
```

4. Install and generate YARD index

```ruby
bundle install
yard gems
```

Open the file and try `hover` (`<F9>`) on some variables, method names or arguments.

**Comment by polyzen** [comment]
You probably want to disable the hover capability of one of those servers, eg.:
```lua
lspconfig.sorbet.setup({
  on_attach = function(client)
    client.server_capabilities.hoverProvider = false
  end,
})
```

**Comment by paulodiovani** [comment]
> You probably want to disable the hover capability of one of those servers, eg.:
> 
> ```lua
> lspconfig.sorbet.setup({
>   on_attach = function(client)
>     client.server_capabilities.hoverProvider = false
>   end,
> })
> ```

That solves the main issue. But the ideal would be to still have both.
I'm doing some tests with `lewis6991/hover.nvim`.

**Comment by paulodiovani** [comment]
This is probably a duplication of https://github.com/neovim/neovim/issues/16363 and might be resolved on `neovim` source code.

**Comment by paulodiovani** [comment]
I managed to make it work the way I wanted by using lewis6991/hover.nvim as follows:

```lua
local util = vim.lsp.util
local get_clients = vim.lsp.get_clients or vim.lsp.get_active_clients

local LSPServerHover = function(server_name)
  return {
    name = string.format('LSP[%s]', server_name),
    priority = 1002, -- above diagnostics

    enabled = function(bufnr)
      return #get_clients({ bufnr = bufnr, name = server_name, method = 'textDocument/hover' }) > 0
    end,

    execute = function(opts, done)
      local params = util.make_position_params()
      local client = get_clients({ bufnr = opts.bufnr, name = server_name, method = 'textDocument/hover' })[1]

      client.request('textDocument/hover', params, function(err, result)
        if result and result.contents and result.contents.value then
          local value = result.contents.value
          done({ lines = vim.split(value, '\n', true), filetype = 'markdown' })
        else
          print(err)
          done()
        end
      end)
    end,
  }
end
```

```lua
-- USAGE:
-- when configuring LSP Servers
    on_attach = function(_, bufnr)
      hover.register(LSPServerHover(server_name))
      vim.keymap.set({ 'n', 'i' }, '<F9>', hover.hover)
    end,
```

https://github.com/paulodiovani/dotfiles/blob/4eb17e19b113b32f3fd6da2c7357d26958056edb/home/user/.config/nvim/lua/completion.lua#L5-L29

The trick was to create and register a new provider on server attach, to be able to split the results while keeping a reference to the name.

Screenshots:
![image](https://github.com/user-attachments/assets/fb26239f-e490-4a87-9643-614dd5714f58)

![image](https://github.com/user-attachments/assets/2cd01296-e1f4-431b-bd77-5d04b8527e15)

**Comment by paulodiovani** [comment]
I'm closing this ticket, since the issue actually happens on `neovim`, on the `lsp.hover` implementation (issue linked above).

For whoever faces the same issue and don't want to disable one of the servers, my solution above might be an option.

**Comment by paulodiovani** [comment]
In case anyone is following this issue, I opted out of `lewis6991/hover.nvim` a while ago. The lack of the ability to jump to the opened floating window makes it hard to read long documentations.

I end up creating another solution using only native `vim.lsp.handlers.hover` and a throttle function to join every lsp client output in a single window.

```lua
local function throttle(callback, delay)
    local is_throttled = false
    local timer = vim.loop.new_timer()

    return function(...)
        if not is_throttled then
            local args = {...}
            callback(unpack(args))

            is_throttled = true
            timer:start(delay, 0, vim.schedule_wrap(function()
                is_throttled = false
                timer:stop()
            end))
        end
    end
end

local get_clients = vim.lsp.get_clients or vim.lsp.get_active_clients

-- throttled function to call textDocumentohover for all lsp clients
-- and join the contents in a single floating window
local lsp_hover_all = throttle(function(_, _, ctx, config)
  -- silently return if not loaded yet
  if not ctx then
    return
  end

  local clients = get_clients({ bufnr = ctx.bufnr, method = ctx.method })
  local remaining = #clients
  local hover_cache = nil

  for _, client in ipairs(clients) do
    -- calls textDocument/hover in each client
    client.request(ctx.method, ctx.params, function(_, result)
      remaining = remaining - 1

      if not (result and result.contents and result.contents.value) then
        return
      end

      if not hover_cache then
        hover_cache = result
      else
        hover_cache.contents.value = hover_cache.contents.value .. '\n---\n' .. result.contents.value
      end

      -- call original hover with the joined result of all clients
      if remaining == 0 then
        return vim.lsp.handlers.hover(_, hover_cache, ctx, config)
      end
    end, ctx.bufnr)
  end
end, 100) -- ms
```

Then, `on_attach` of the LSP clients, I just need to use this new function.

```lua
    handlers = {
      ['textDocument/hover'] = vim.lsp.with(lsp_hover_all, { border = 'rounded' }),
      ['textDocument/signatureHelp'] = vim.lsp.with(vim.lsp.handlers.signature_help, { border = 'rounded' }),
    },
```

The result is like this:

![Image](https://github.com/user-attachments/assets/d9ec84ce-a25e-4f34-8717-254264819ca2)

**Comment by paulodiovani** [comment]
Oh, the issue was fixed on https://github.com/neovim/neovim/pull/30935, now `neovim` supports multiple LSP clients.
This will be part of version `0.11`, to be release on March 2025. https://neovim.io/roadmap/
