### ISSUE TITLE
Reference to non-existent help topic `:help lspconfig-all`

### ISSUE THREAD

**Issue by errael** [neovim/nvim-lspconfig#3297]
The first word of [README.md](https://github.com/neovim/nvim-lspconfig?tab=readme-ov-file#nvim-lspconfig), `Configs`, points to a page and the last phrase of the first paragraph of that page references the non-existent help topic

**Comment by justinmk** [comment]
"non-existent help topic" based on what? `:help lspconfig-all` works for me. And it's defined here: https://github.com/neovim/nvim-lspconfig/blob/056f569f71e4b726323b799b9cfacc53653bceb3/doc/server_configurations.md?plain=1#L2 (which gets generated to a help tag).

Check that your plugin manager is calling `:helptags`

**Comment by errael** [comment]
Oops, sorry for the noise. I manually installed. Works after `:helptags`. Thanks.

I typically don't use many plugins. Using `neovim`, where it seems plugins are more important for setting up, a plugin manager might make more sense so such things are handled during installation.
