### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by flexagoon** [neovim/nvim-lspconfig#3298]
### Description

With some breaking changes being merged since the last release (eg #3232), and other plugins updating to use those features (https://github.com/williamboman/mason-lspconfig.nvim/pull/459), using a tagged release of `nvim-lspconfig` becomes harder. For example, if you see the issue I linked above, the last release of `mason-lspconfig` uses the `ts_ls` server name, which isn't available in the latest `nvim-lspconfig` version.

Please tag a new release of `nvim-lspconfig` and publish it to luarocks.

**Comment by glepnir** [comment]
0.19 is tagged

**Comment by justinmk** [comment]
- tagged [v0.1.9](https://github.com/neovim/nvim-lspconfig/releases/tag/v0.1.9) to just before the ts_ls change
- tagged [v1.0.0](https://github.com/neovim/nvim-lspconfig/releases/tag/v1.0.0)

**Comment by nshen** [comment]
After I replace all tsserver to ts_ls in my config, it still show the WARN message each time I start nvim, Is this expected ?

**Comment by glepnir** [comment]
can't reproduce

**Comment by nshen** [comment]
> can't reproduce

Thanks for reply, I am sure replaced all "tsserver" in my config,  is it possible that it's because I use the [typescript.nvim](https://github.com/jose-elias-alvarez/typescript.nvim)?
