### ISSUE TITLE
Rename of language server tsserver -> ts_ls causes confusion

### ISSUE THREAD

**Issue by tskj** [neovim/nvim-lspconfig#3304]
### Description

Hi there good people, I appreciate that the rename of tsserver to ts_ls was necessary, and the alias provided means it keeps working, but for schmucks like me it's very confusing that neovim all of a sudden complains that "tsserver" is not found (but also the LSP keeps working fine). Nowhere is it explained that I have go into my config and rename it to "ts_ls". For me to figure that out I had to go on a wild chase through your commits! 

I would appreciate it if it was possible for the error message to say as much, or some other way of alerting me to the fact I had to rename the paramter in my config. At least it would help if it was mentioned somewhere in this repo, and not just in the commit messages (which will only get older and harder to find for future people in a similar situation as time passes). This is a very confusing situation right now that makes no sense to a poor end user like myself.

**Comment by glepnir** [comment]
when you configed the `tsserver` there will popup a deprecate message tell you repalce by ts_ls. i can't reproduce your issue.

**Comment by tskj** [comment]
idk what to tell you, except that all it says is this, which is confusing:
![bilde](https://github.com/user-attachments/assets/8eda45a0-4ab5-4afb-ad06-659eb1dcae60)

**Comment by justinmk** [comment]
If you have third-party layers on top of lspconfig, such as mason or lazy, it's difficult to tell you exactly how to adjust your config.

**Comment by tskj** [comment]
Yeah of course I wouldn't expect you to tell me that, the problem I have is that this breaks backwards compatibility and there's no real recourse to find out how or why or what, except trawling the commit history. At least put a note in the readme for people to find that says "oops this used to be called tsserver, sorry to everyone who depended on that, you now need to update".

**Comment by glepnir** [comment]
once again the lspconfig show the deprecate message very clear. your issue is from what thirdy plugin you used. 

![QQ_1726551449989](https://github.com/user-attachments/assets/a8398381-30bc-4386-b7cc-36aa2647c282)
