### ISSUE TITLE
Missing deprecation documentation

### ISSUE THREAD

**Issue by tskj** [neovim/nvim-lspconfig#3306]
### Description

In reference to this issue which you prematurely closed and locked https://github.com/neovim/nvim-lspconfig/issues/3304.

I appreciate your claim that it's because of third party plugin such as Mason that a user like me is not seeing the error message. However, it is also therefore that I ask that this deprecation be _documented_ so that such a user can find that information! Good documenation and careful engineering is necessary for good software. 

I would highly implore you to take backwards compatibility seriously and not break people's setups without proper documentation, even if they happen to use what you call "third party" plugins.

**Comment by glepnir** [comment]
@tskj  I don't understand what you are saying? lspconfig has always been compatible. We provided a deprecation message?  You can't see the message because you use third plugin? Why don't you file an issue there?

**Comment by justinmk** [comment]
Send a PR.

**Comment by glepnir** [comment]
and tsserver still works even lspconfig through a deprecate message. if you don't get it works please check what that plugin do.

**Comment by tskj** [comment]
Yes it's compatible because you aliased it, which I very much appreciate! That's a good practice. I'm saying you should also _document_ this decision somewhere. 

> Send a PR.

Sure, here, I tried my hand at some documenting: https://github.com/neovim/nvim-lspconfig/pull/3307. Feel free to reword it or move however you see fit. I also suggest your project have a deprecation / change history somewhere for people to look at, which I haven't included in this PR. Not sure exactly how that would look, but it would be the correct way to handle breaking backwards compatibility.

**Comment by justinmk** [comment]
After https://github.com/neovim/nvim-lspconfig/pull/3308 LspInfo now shows a "deprecated servers" message.
