### ISSUE TITLE
LSP[id=1] client has shut down after sending the message - when opening a haskell (.hs) file

### ISSUE THREAD

**Issue by tr0b** [neovim/nvim-lspconfig#331]
- `nvim --version`: NVIM v0.5.0-639-g46e74142a-dirty
- nvim-lsp version(commit hash): latest version (executed : PlugUpdate)
- `:checkhealth` result: -> https://pastebin.com/AcenMLg2
- What language server(If the problem is related to a specific language server):
hie - > Haskell IDE Engine
- Operating system/version: Gentoo Linux Kernel  5.3.2
- Terminal name/version: rxvt-unicode
- `$TERM`:xterm-256color

### How to reproduce the problem from neovim startup
-Install stack
-Install ghc version 8.8.3
-Install hie version 8.8.3
-Install hoogle
-Install neovim builtin lsp
-For more accuracy, run neovim with the following dotvim configs:
aesthetics.vim:
https://pastebin.com/p5eDf1ZE
general.vim:
https://pastebin.com/aCvdEmSs
mapped.vim:
https://pastebin.com/PVry35Dt
initial_plugins.vim:
https://pastebin.com/SBYT7pjf
lsp_config.vim:
https://pastebin.com/PekTjkRE
init.vim:
https://pastebin.com/jxb5gcK6

-Open any haskell file inside a haskell project directory (run hoogle generate prior!)
### Actual behaviour
![image](https://user-images.githubusercontent.com/60306480/91645385-ea00a880-ea01-11ea-90eb-d824b2777dfb.png)
When opening any haskell file inside a project directory, the following error message gets thrown by neovim during startup:
"LSP[id=1] client has shut down after sending the message"
Virtual text for errors seem to work fine..
![image](https://user-images.githubusercontent.com/60306480/91645414-1b797400-ea02-11ea-97b9-935f2d716f0b.png)
For some functions, when you press HoverDocumentation button, documentation appears:
![image](https://user-images.githubusercontent.com/60306480/91645441-5085c680-ea02-11ea-911f-6672e0b6537a.png)
complementing neovim lsp with completion-nvim in haskell partially works. hie lsp references appear during completion asynchronously, although when hovering over the selection in the popup menu, no documentation appears (not sure if this is expected behaviour ):
![image](https://user-images.githubusercontent.com/60306480/91645544-1ec12f80-ea03-11ea-90c4-4745fef4a5ed.png)

### Expected behaviour
The expected behaviour should be: No error should occur when opening a haskell file in neovim. if HIE supports it, Hovering documentation should be appearing when selecting a suggestion from the completion popup-menu.

Example of *expected method documentation in popup menu for hie and haskell (but using pyls and a python file):
![image](https://user-images.githubusercontent.com/60306480/91645691-61373c00-ea04-11ea-941c-d115800162b5.png)

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to `test/functional/plugin/lsp_spec.lua`, which has code to setup a fake LSP server to simulate various scenarios.

**Comment by tr0b** [comment]
Thank you @justinmk . I've tried configuring the lsp client for hie but it's been difficult for me since I'm an absolute beginner with neovim-lsp. I'll keep trying configuring hie (or maybe attempt to use ghcide) since nvim lsp works really well for other language servers for me, except for a few (Haskell, ruby and go).
