### ISSUE TITLE
Feature request: autostop functionality in addition to autostart

### ISSUE THREAD

**Issue by jfly** [neovim/nvim-lspconfig#3326]
### Description

I am familiar with nvim-lspconfig's [autostart functionality](https://github.com/neovim/nvim-lspconfig/blob/76e7c8b029e6517f3689390d6599e9b446551704/lua/lspconfig/configs.lua#L99-L113). I find it odd that there's no corresponding auto*stop* functionality. If I manually change the filetype of a buffer, I see a new LSP server start up, but the old one is still running.

I found this Reddit thread sort of talking about this: https://www.reddit.com/r/neovim/comments/15h6f4o/lsp_is_started_even_though_i_change_the_filetype/, but I haven't been able to find any discussion here or over on neovim core.

Is this a feature you're open to adding to nvim-lspconfig? If so, I'd be happy to send in a PR implementing it!

**Comment by justinmk** [comment]
nvim-lspconfig will not gain any new features. It's intended to be a data-only repo. 

Its "features" will be upstreamed as appropriate to Nvim core: https://github.com/neovim/neovim/issues/28479

**Comment by jfly** [comment]
Ok, that makes sense!

IIUC, it feels premature to file an issue with Nvim core asking for auto*stop* functionality when there isn't even auto*start* functionality yet.

I'm subscribed to the issue you linked to. If this doesn't get resolved with the upstreaming work, I'll follow up later.
