### ISSUE TITLE
Split doc/server_configurations.md to load available configs faster

### ISSUE THREAD

**Issue by satk0** [neovim/nvim-lspconfig#3329]
### Description

Because many new lsps were added to the project, the `doc/server_configurations.md` page takes significant time to load and it is frustrating (at least for me). Splitting it up into smaller files could resolve that issue.

**Comment by justinmk** [comment]
It's also available as a .txt (help format) file via `:help lspconfig-all`

**Comment by satk0** [comment]
It does, still a bit lag but could do if you don't want to split it ;d

**Comment by justinmk** [comment]
splitting the files is a very narrow solution to a very specific problem, that introduces many new problems. For example, after spliting the file, that will add 300 new help tags. And users won't be able to search one file, they have to now search many files.
