### ISSUE TITLE
ts_ls doesn't exist on windows

### ISSUE THREAD

**Issue by NRicode** [neovim/nvim-lspconfig#3332]
### Description

it told me to update tsserver to ts_ls, on my linux machine it works fine, but on my windows it says

 Cannot access configuration for ts_ls. Ensure this server is listed in `server_configurations.md` or added as a custom server

**Comment by justinmk** [comment]
> Cannot access configuration for ts_ls. Ensure this server is listed in `server_configurations.md` or added as a custom server

if you are getting that error then you need to update nvim-lspconfig
