### ISSUE TITLE
LspInfo is broken

### ISSUE THREAD

**Issue by acederberg** [neovim/nvim-lspconfig#3342]
### Description

Running results in

```
==============================================================================
lspconfig: require("lspconfig.health").check()

- ERROR Failed to run healthcheck for "lspconfig" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua .../share/nvim/lazy/nvim-lspconfig/lua/lspconfig/health.lua:192: attempt to call field 'get_clients' (a nil value)
  stack traceback:
  .../share/nvim/lazy/nvim-lspconfig/lua/lspconfig/health.lua:192: in function 'check_lspconfig'
  .../share/nvim/lazy/nvim-lspconfig/lua/lspconfig/health.lua:283: in function 'check'
  [string "luaeval()"]:1: in main chunk
```

**Comment by samuelvp360** [comment]
After a `:PackerSync`minutes ago, my lspconfig is completely broken. Not working on `require('lspconfig')` statements in lua files. The same for `require('lspconfig/util')`. I had to uninstall it.

`E5113: Error while calling lua chunk: lsp.lua:1: loop or previous error loading module 'lspconfig' 
stack traceback:
[C]: in function 'require'
lsp.lua:1: in main chunk
`

**Comment by acederberg** [comment]
I was in the same boat, I had to specify my version explicitly in my lazy config.

**Comment by samuelvp360** [comment]
Thanks Bro, v0.1.8 worked for me. Why?, I don't know.

**Comment by justinmk** [comment]
are you on Nvim 0.9? nvim-lspconfig now requires Nvim 0.10

**Comment by acederberg** [comment]
Ah I'm using version `0.9.5` of ``nvim``. My problems are my fault for not setting package versions in my lazy config - not doing so meant that updating resulted in a number of plugins updating with breaking changes since many of the plugins I use have had new major versions lately.

Thanks for your help justin!

**Comment by mehalter** [comment]
@justinmk should we go through and make sure that all of lspconfig supports neovim 0.9? Things such as LSP commands?

**Comment by justinmk** [comment]
> make sure that all of lspconfig supports neovim 0.9? Things such as LSP commands?

I think existing configs should support Nvim 0.9 , but going forward, new configs/commands will not.

So https://github.com/neovim/nvim-lspconfig/commit/c25b9dd6bddb125b538f3f01cb47b4a6e606f6c5 should be reverted
