### ISSUE TITLE
LspInfo: Root directory is always "Running in single file mode"

### ISSUE THREAD

**Issue by h3xOo** [neovim/nvim-lspconfig#3346]
### Description

As title says, root directory is always "Running in single file mode". On commit dd329912c8d446240584a2dbcd3802af3a19105a it still works.

**Comment by justinmk** [comment]
do you mean :LspInfo says this?

can you confirm if https://github.com/neovim/nvim-lspconfig/commit/71ff1585a8a2d66c13f0da7d76e7ce4922128d8f works too?

**Comment by h3xOo** [comment]
> do you mean :LspInfo says this?

Yes, that's what I meant.

**Comment by WillEhrendreich** [comment]
For whatever reason it's still happening to me, as well. checked for Roslyn.nvim and Ionide.nvim, though those are not exactly part of lspconfig defaults, so perhaps it has something to do with that?
