### ISSUE TITLE
`:LspStop config-name` (as opposed to `:LspStop client-id`)

### ISSUE THREAD

**Issue by Drew-Daniels** [neovim/nvim-lspconfig#3362]
### Description

Apologies if there has already been an issue for this - I couldn't find anything out there that seemed similar. 

There are some occasions where I would like to be able to stop a specific LSP (like `eslint`), but leave all other language servers running on a buffer (`volar`, `tailwindcss`, etc.)

Currently, the only way that I know of to disable LSPs on a buffer is with `:LspStop`, but this stops all language servers.

I think it would be a nice feature to modify this to accept LSP server names like `:LspStop eslint` so we can stop specific LSPs that are attached to buffer and leave all the others attached.

**Comment by justinmk** [comment]
`:LspStop` accepts a client-id (see `:help :LspStop`), but it's probably reasonable for it to also accept a config name (`eslint`, etc.).

Meanwhile, to get the client-id you can use :LspInfo or `:che lspconfig`, then just run `:LspStop <id>`.

**Comment by glepnir** [comment]
maybe we can enhancement to support multiple format of client name and id like

- `LspStop` no argment close all the clients which start by lspconfig mean get them from manage_clients
- `LspStop arg` the format of arg can be pure id , pure name or id with name or a buffer split with comma or space
                            `1,2` `clangd,tsserver` `2, clangd` `bufnr(s)`

**Comment by justinmk** [comment]
>  or id with name or a buffer split with comma or space `1,2` `clangd,tsserver` `2, clangd` `bufnr(s)`

If anyone needs something that complicated they can use `vim.lsp` API, there is no reason to make the commands complex.

Supporting the plain "config name" for a command makes sense. Commands are a high-level interface.

**Comment by Drew-Daniels** [comment]
Thanks @glepnir @justinmk !
