### ISSUE TITLE
svelte-language-server: root dir not found on folder with square brackets

### ISSUE THREAD

**Issue by vipexv** [neovim/nvim-lspconfig#3365]
### Describe the bug

So i'm using Neovim development/nightly build due to the fact that it allows me to use Netrw to access directories that have brackets around them, so everything works fine, in React/Lua and every other language server, but in svelte it just throws an error saying not found, more info will be found below.

My Nvim Config can also be found [here](https://github.com/vipexv/nvim)

### Reproduction

Try to access a directory that's wrapped with square brackets, and the Lsp doesn't start up.

### Expected behaviour

The LSP is expected to start and work normally.

### System Info

- OS: Windows 11
- IDE: Neovim (Nightly)

### Which package is the issue about?

svelte-language-server installed using Mason.

### LspInfo:

==============================================================================
```
lspconfig:                                 require("lspconfig.health").check()

LSP configs active in this session (globally) ~
- Configured servers: svelte, tailwindcss, lua_ls, ts_ls
- OK Deprecated servers: (none)

LSP configs active in this buffer (id=13) ~
- Language client log: ~\AppData\Local\nvim-data\lsp.log
- Detected filetype: `svelte`
- 1 client(s) attached to this buffer
- Client: tailwindcss (id: 1, bufnr: [13])
  filetypes:       aspnetcorerazor, astro, astro-markdown, blade, clojure, django-html, htmldjango, edge, eelixir, elixir, ejs, erb, eruby, gohtml, gohtmltmpl, haml, handlebars, hbs, html, htmlangular, html-eex, heex, jade, leaf, liquid, markdown, mdx, mustache, njk, nunjucks, php, razor, slim, twig, css, less, postcss, sass, scss, stylus, sugarss, javascript, javascriptreact, reason, rescript, typescript, typescriptreact, vue, svelte, templ
  root directory:  Running in single file mode.
  cmd:             ~\AppData\Local\nvim-data\mason\bin\tailwindcss-language-server.CMD --stdio
  autostart:       true
- Other clients that match the "svelte" filetype: 
- Config: svelte
  filetypes:         svelte
  root directory:    ~\Desktop\test-server-ox\data\resources\[cfx]\[gameplay]\new_chat\Not found.
  cmd:               ~\AppData\Local\nvim-data\mason\bin\svelteserver.CMD --stdio
  cmd is executable: true
  autostart:         true
  custom handlers:   
```

**Comment by vipexv** [comment]
Managed to fix this by doing this on my LSP Config:

```
		svelte = function()
			require("lspconfig").svelte.setup({
				capabilities = lsp_capabilities,
				root_dir = function()
					return vim.fn.getcwd()
				end,
			})
		end,
```

I'm pretty sure this only works on Neovim 11 Development/Nightly build, because it seems like they've fixed allot of weird issues with square brackets in this version.

**Comment by justinmk** [comment]
Thanks for the followup. But it's not clear whether you are saying any action is needed here. Are you suggesting a change to the svelte config?

If this is fixed in Nvim 0.11 then there is nothing left to be done.

**Comment by vipexv** [comment]
@justinmk Sorry for the late reply, so NVIM 0.11 fixes the issue with square brackets in general, but somehow the Svelte LSP still has that issue, but updating the root_dir function of that LSP to just use the `vim.fn.getcwd()` func from neovim seems to fix the issue, so yes manual action is needed for me personally.

**Comment by justinmk** [comment]
> somehow the Svelte LSP still has issues handling square brackets on folders

Does that issue manifest with the same server + config + paths, in other editors (e.g. vscode)? If not, maybe the Nvim core lsp client needs a fix.

**Comment by vipexv** [comment]
in VSCode i've never had issues with square brackets, any LSP i've used in there has always worked doesn't matter what folder i was in, as far as i can remember.

**Comment by justinmk** [comment]
This is the same as https://github.com/neovim/neovim/issues/19976 , right?
