### ISSUE TITLE
denols definition get no result in a jsr package

### ISSUE THREAD

**Issue by niuiic** [neovim/nvim-lspconfig#3369]
### Description

Use the default config. Create `index.ts` in a git repo. Add `jsr:@std/assert` to cache.

```ts
import { assertEquals } from 'jsr:@std/assert'

Deno.test('simple test', () => {
  const x = 1 + 2
  assertEquals(x, 3)
})
```

Move cursor to `assertEquals`, run `vim.lsp.buf.definition()`, no result was returned. But in vscode, with deno extension, it works.

`/usr/share/nvim/runtime/lua/vim/lsp/client.lua`
![Image](https://github.com/user-attachments/assets/d3b09401-36ca-46a0-b919-0d07c35e75f8)

**Comment by glepnir** [comment]
you can simply override handler to check the result

```lua
vim.lsp.handlers['textDoucment/definition'] = funciton(...)
  print(vim.inspect({...})
end
```

**Comment by niuiic** [comment]
The line in the picture is the code that defines the function used to get what the handler has received.

Close this issue and create a new one on neovim core.
