### ISSUE TITLE
Command not executable

### ISSUE THREAD

**Issue by keleset** [neovim/nvim-lspconfig#337]
- `nvim --version`: 0.5.0 (latest nightly)
- nvim-lsp version(commit hash): latest master
- `:checkhealth`:
```
health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - ERROR: dart_lsp: The given command "dast_lsp.sh" is not executable.
```
- What language server(If the problem is related to a specific language server):

```
lua <<EOF
local nvim_lsp = require'nvim_lsp'
local configs = require'nvim_lsp/configs'
-- Check if it's already defined for when I reload this file.
if not configs.dart_lsp then
  configs.dart_lsp = {
    default_config = {
      cmd = {'dast_lsp.sh'};
      filetypes = {'dart'};
      root_dir = function(fname)
        return nvim_lsp.util.find_git_ancestor(fname) or vim.loop.os_homedir()
      end;
      settings = {};
    };
  }
end
nvim_lsp.dart_lsp.setup{}
EOF
```
dart_lsp.sh **can** be executed in shell (just as `dart_lsp.sh`)

- Operating system/version: 5.4.*
- Terminal name/version: alacritty

Is there any way to solve this by myself?

P.S. I know that there is default dart lsp config, but neither flutter nor dart are in $PATH on my setup and should not be, so this not gonna work I guess.

**Comment by ktfleming** [comment]
From your config...
`cmd = {'dast_lsp.sh'};`

Could it just be a typo? (dast -> dart)

**Comment by justinmk** [comment]
you need a shell to execute a shell script. Try this

   cmd = {'bash', 'dast_lsp.sh'};

**Comment by keleset** [comment]
@justinmk 
Thanks. I've got following question, why is LSP server run though script is not responding to commands, while it works pretty well when executed through direct command from nvim lsp config?
