### ISSUE TITLE
How are warnings and errors displayed?

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/nvim-lspconfig#338]
- `nvim --version`: NVIM v0.5.0-nightly-141-g24b5f69a4
- nvim-lsp version(commit hash): b7b311e22a0b071dfb43aa6a9ccc0ed92e5eab3d
- `:checkhealth` result All OK
- What language server(If the problem is related to a specific language server): rust-analyzer
- Operating system/version: Mac
- Terminal name/version: iTerm2
- `$TERM`: screen-256color

### How to reproduce the problem from neovim startup
1. Start neovim.
2. Open the main.rs file for your Rust project.

### Actual behaviour
The place where the error is occurring is not marked.

### Expected behaviour
The following code should detect the error.
```rust
fn main() {
    // let a = [1, 2, 3, 4, 5];
    let b = a.iter().map(|x| x * x); // <- No error is displayed.
    b.for_each(|x| println!("it is {}", x));
}
```
No warning is displayed.
```rust
fn foo() {
    let a = [1, 2, 3, 4, 5]; // <- No unused warnings are displayed.
}
```

**Comment by nabezokodaikon** [comment]
By the way, it is displayed in 'LanguageClient-neovim'.

**Comment by nabezokodaikon** [comment]
My LSP setting.
```lua
local lsp = require'nvim_lsp'

local capabilities = {
    textDocument = {
        completion = {
            completionItem = {
                snippetSupport = false
            },
        },
    },
};

local on_attach = function(client)
    diagnostic.on_attach(client)
end

lsp.rust_analyzer.setup {
    capabilities = capabilities,
    on_attach = on_attach,
}
```

**Comment by justinmk** [comment]
Thanks for your report. The configs here [are best-effort](https://github.com/neovim/nvim-lsp#nvim-lsp):

> It is hoped that these configurations serve as a "source of truth", but they are strictly best effort. If something doesn't work, these configs are useful as a starting point, which you can adjust to fit your environment.

- If you have an improvement or fix, please send a PR! 
- If you have a specific question we'll try to answer it (keeping in mind the configs in this repo are best-effort and unsupported).
- If you found a bug in the core `lsp` module, the best way to get it fixed is to describe steps to reproduce it without the particular LSP server and other factors particular to your environment. Or better, by adding a failing test case to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios.

**Comment by lithammer** [comment]
> My LSP setting.

I would start by disabling diagnostic-nvim and see if that helps. Then remove the custom `capabilities`.

**Comment by nabezokodaikon** [comment]
Yes. I deleted diagnostic-nvim setting and confirmed.
