### ISSUE TITLE
vscode-markdown-language-server does not work with nvim-lspconfig

### ISSUE THREAD

**Issue by melsiir** [neovim/nvim-lspconfig#3385]
### Description

my machine for some reason cannot run marksman lsp so i am trying vscode-markdown-language-server
but it seem that it does not have config template in nvim-lspconfig and i wish if anyone add vscode-markdown-language-server support for nvim-lspconfig

**Comment by justinmk** [comment]
The configs in this repo are provided as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- a failing test case added to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by polyzen** [comment]
@melsiir, iirc the server isn't fully implemented in LSP and/or would require custom client code.
