### ISSUE TITLE
ts_ls throws errors

### ISSUE THREAD

**Issue by ceejey** [neovim/nvim-lspconfig#3403]
### Description
I have added ts_ls to my mason ensure installed list and added the lsp config for ts_ls. ts_ls gets installed successfully and if I open a .js file it seems that the lsp config is trying to load but throws following error:

Error executing vim.schedule lua callback: ...m Files\Neovim\share\nvim\runtime/lua/vim/lsp/client.lua:588: RPC[Error] code_name = InternalError, message = "Request initialize failed with message: Maximum call stack size exceeded"                                                                                  stack traceback:                                                                                                [C]: in function 'assert'                                                                               ...m Files\Neovim\share\nvim\runtime/lua/vim/lsp/client.lua:588: in function 'fn'                       vim/_editor.lua:351: in function <vim/_editor.lua:350>

### System Info
OS: Windows 11
Neovim version: v0.10.2
ts_ls was installed using mason

### Lsp config:
lspconfig.ts_ls.setup {
	on_attach = on_attach,
	root_dir = function()
		return vim.fn.getcwd()
	end,
	capabilities = capabilities
}

### LspInfo:

lspconfig: require("lspconfig.health").check()

LSP configs active in this session (globally) ~
- Configured servers: pylsp, powershell_es, yamlls, ts_ls, lua_ls
- OK Deprecated servers: (none)

LSP configs active in this buffer (bufnr: 2) ~
- Language client log: ~\AppData\Local\nvim-data\lsp.log
- Detected filetype: `javascript`
- _**0 client(s) attached to this buffer**_
- Other clients that match the "javascript" filetype:
- Config: ts_ls
  filetypes:         javascript, javascriptreact, javascript.jsx, typescript, typescriptreact, typescript.tsx
  cmd:               ~\AppData\Local\nvim-data\mason\bin\typescript-language-server.CMD --stdio
  version:           `4.3.3`
  executable:        true
  autostart:         true
  root directory:    ~\Git\configs

**Comment by justinmk** [comment]
> Language client log: ~\AppData\Local\nvim-data\lsp.log

Are there any more info in that log? (Do not post the entire log here; use your judgement to find useful messages in the log, and post only those).



> "Request initialize failed with message: Maximum call stack size exceeded"

That call stack error comes from javascript. This could be a bug in ts_ls.

**Comment by ceejey** [comment]
I'm not sure if some of the messages are duplicates but they were logged around the same time:

[DEBUG][2024-10-25 17:00:46] ...m/lsp/client.lua:678	"LSP[lua_ls]"	"client.request"	2	"textDocument/documentHighlight"	{  position = {    character = 1,    line = 51  },  textDocument = {    uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"  }}	<function 1>	10
[DEBUG][2024-10-25 17:00:46] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 24,  jsonrpc = "2.0",  method = "textDocument/documentHighlight",  params = {    position = {      character = 1,      line = 51    },    textDocument = {      uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"    }  }}
[DEBUG][2024-10-25 17:00:46] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 24,  jsonrpc = "2.0"}
[DEBUG][2024-10-25 17:00:46] ...m/lsp/client.lua:678	"LSP[lua_ls]"	"client.request"	2	"textDocument/documentHighlight"	{  position = {    character = 1,    line = 42  },  textDocument = {    uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"  }}	<function 1>	10
[DEBUG][2024-10-25 17:00:46] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 25,  jsonrpc = "2.0",  method = "textDocument/documentHighlight",  params = {    position = {      character = 1,      line = 42    },    textDocument = {      uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"    }  }}
[DEBUG][2024-10-25 17:00:46] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 25,  jsonrpc = "2.0",  result = { {      kind = 3,      range = {        ["end"] = {          character = 9,          line = 39        },        start = {          character = 6,          line = 39        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 4,          line = 42        },        start = {          character = 1,          line = 42        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 5,          line = 46        },        start = {          character = 2,          line = 46        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 41,          line = 53        },        start = {          character = 38,          line = 53        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 31,          line = 54        },        start = {          character = 28,          line = 54        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 5,          line = 55        },        start = {          character = 2,          line = 55        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 17,          line = 58        },        start = {          character = 14,          line = 58        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 5,          line = 61        },        start = {          character = 2,          line = 61        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 17,          line = 64        },        start = {          character = 14,          line = 64        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 5,          line = 67        },        start = {          character = 2,          line = 67        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 14,          line = 68        },        start = {          character = 11,          line = 68        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 7,          line = 70        },        start = {          character = 4,          line = 70        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 7,          line = 71        },        start = {          character = 4,          line = 71        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 21,          line = 78        },        start = {          character = 18,          line = 78        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 21,          line = 79        },        start = {          character = 18,          line = 79        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 12,          line = 157        },        start = {          character = 9,          line = 157        }      }    } }}
[DEBUG][2024-10-25 17:00:47] ...m/lsp/client.lua:678	"LSP[lua_ls]"	"client.request"	2	"textDocument/documentHighlight"	{  position = {    character = 4,    line = 30  },  textDocument = {    uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"  }}	<function 1>	10
[DEBUG][2024-10-25 17:00:47] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 26,  jsonrpc = "2.0",  method = "textDocument/documentHighlight",  params = {    position = {      character = 4,      line = 30    },    textDocument = {      uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"    }  }}
[DEBUG][2024-10-25 17:00:47] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 26,  jsonrpc = "2.0",  result = { {      kind = 3,      range = {        ["end"] = {          character = 13,          line = 29        },        start = {          character = 6,          line = 29        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 7,          line = 30        },        start = {          character = 0,          line = 30        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 9,          line = 32        },        start = {          character = 2,          line = 32        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 9,          line = 33        },        start = {          character = 2,          line = 33        }      }    }, {      kind = 2,      range = {        ["end"] = {          character = 9,          line = 35        },        start = {          character = 2,          line = 35        }      }    } }}
[DEBUG][2024-10-25 17:00:48] ...m/lsp/client.lua:678	"LSP[lua_ls]"	"client.request"	2	"textDocument/documentHighlight"	{  position = {    character = 1,    line = 26  },  textDocument = {    uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"  }}	<function 1>	10
[DEBUG][2024-10-25 17:00:48] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 27,  jsonrpc = "2.0",  method = "textDocument/documentHighlight",  params = {    position = {      character = 1,      line = 26    },    textDocument = {      uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"    }  }}
[DEBUG][2024-10-25 17:00:48] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 27,  jsonrpc = "2.0",  result = { {      kind = 3,      range = {        ["end"] = {          character = 23,          line = 26        },        start = {          character = 1,          line = 26        }      }    } }}
[DEBUG][2024-10-25 17:00:51] ...m/lsp/client.lua:678	"LSP[lua_ls]"	"client.request"	2	"textDocument/documentHighlight"	{  position = {    character = 1,    line = 81  },  textDocument = {    uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"  }}	<function 1>	10
[DEBUG][2024-10-25 17:00:51] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 28,  jsonrpc = "2.0",  method = "textDocument/documentHighlight",  params = {    position = {      character = 1,      line = 81    },    textDocument = {      uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"    }  }}
[DEBUG][2024-10-25 17:00:51] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 28,  jsonrpc = "2.0"}
[DEBUG][2024-10-25 17:00:52] ...m/lsp/client.lua:678	"LSP[lua_ls]"	"client.request"	2	"textDocument/documentHighlight"	{  position = {    character = 0,    line = 160  },  textDocument = {    uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"  }}	<function 1>	10
[DEBUG][2024-10-25 17:00:52] .../vim/lsp/rpc.lua:286	"rpc.send"	{  id = 29,  jsonrpc = "2.0",  method = "textDocument/documentHighlight",  params = {    position = {      character = 0,      line = 160    },    textDocument = {      uri = "file:///C:/Users/e.dyck/Git/configs/1nvim/lua/pluginconf/mason/lsp.lua"    }  }}
[DEBUG][2024-10-25 17:00:52] .../vim/lsp/rpc.lua:408	"rpc.receive"	{  id = 29,  jsonrpc = "2.0"}

**Comment by ceejey** [comment]
Okay, I fixed it.
Note to myself: Stick with LTS version of nodejs (https://github.com/typescript-language-server/typescript-language-server/issues/926)
Thanks anyway :)
