### ISSUE TITLE
LspInfo has no border

### ISSUE THREAD

**Issue by sahashirshendu** [neovim/nvim-lspconfig#3405]
### Description

I had previously set `:LspInfo` border with
```lua
require('lspconfig.ui.windows').default_options.border = 'single'
```
But now that doesn't seem to work. `:LspInfo` doesn't even open as floating. Is there any way to fix this?

**Comment by sahashirshendu** [comment]
Seems the API was removed.

**Comment by GKSN** [comment]
I have the same question.

**Comment by glepnir** [comment]
now lspinfo is calling the health no floating window is used so this feature is no long support

**Comment by justinmk** [comment]
This could be an enhancement to Nvim's `:checkhealth`, and should be requested at https://github.com/neovim/neovim . Not going to support it as a special case for nvim-lspconfig.
