### ISSUE TITLE
Editor is interrupted by log rust-analyzer log messages

### ISSUE THREAD

**Issue by vikulikov** [neovim/nvim-lspconfig#3410]
### Description

rust-analyzer started to interrupt neovim while typing with this message `rust_analyzer: -32802: server cancelled the request` in last releases. Is there a way to suppress these log messages?

my config:
```lua
{
                ['rust-analyzer'] = {
                    server = { path = "/opt/homebrew/bin/rust-analyzer" },
                    assist = {
                        importMergeBehavior = "last",
                        importPrefix = "by_self",
                    },
                    files = {
                        excludeDirs = { "target" }
                    },
                    workspace = {
                        symbol = {
                            search = {
                                limit = 3000
                            }
                        }
                    },
                    procMacro = {
                        enable = true
                    },
                    diagnostics = {
                        enable = true,
                        disabled = { "unresolved-proc-macro" },
                        enableExperimental = true,
                    },
                    check = {
                        -- command = "clippy"
                    },
                    cargo = {
                        features = "all",
                        loadOutDirsFromCheck = true,
                    }

                },
            }
```
rust-analyzer version: rust-analyzer 0.0.0 (3b3a87fe9 2024-10-27)
lspconfig version: should be the lastest available

[ref to the issue in rust-analyzer repo](https://github.com/rust-lang/rust-analyzer/issues/18434)

**Comment by justinmk** [comment]
The configs in this repo are provided as a starting point. We depend on users (like you) to troubleshoot issues with their specific LSP setups and [send improvements](https://github.com/neovim/nvim-lspconfig/blob/master/CONTRIBUTING.md#adding-a-server-to-lspconfig).

If you have a usage question, try asking it at:
- https://github.com/neovim/neovim/discussions
- https://vi.stackexchange.com/

If you found a bug in the _core_ Nvim  `vim.lsp` module (not part of this repo), the best way to get it fixed is to [report to Nvim](https://github.com/neovim/neovim) (not nvim-lspconfig) with:
- steps to reproduce it without the particular LSP server and other factors particular to your environment
- a failing test case added to [lsp_spec.lua](https://github.com/neovim/neovim/blob/master/test/functional/plugin/lsp_spec.lua), which has code to setup a fake LSP server to simulate various scenarios

**Comment by WhyNotHugo** [comment]
See: https://github.com/neovim/neovim/issues/30985
