### ISSUE TITLE
config "jdtls" not found

### ISSUE THREAD

**Issue by 93mmm** [neovim/nvim-lspconfig#3412]
### Description

Hi, firstly: thanks for beautiful plugin (not sarcasm)
Secondly: I have an trouble with jdtls. Today I decided to add some new plugins to my config and I ran into a problem: jdtls not working anymore, it happened after ```:PackerSync``` 
After some research I didn'n found solution of the problem, please help me

lsp_servers:
```lua
return {
  "pylsp",
  "clangd",
  "cmake",
  "marksman",
  "lua_ls",
  "jdtls",
  "bashls"
}
```
![Image](https://github.com/user-attachments/assets/c3bc02a3-052f-408a-95a4-b1ec87b845ab)
PS: sorry for my bad english

**Comment by glepnir** [comment]
`:lua=require('lspconfig').jdtls` this should return a table. please check your config

**Comment by 93mmm** [comment]
didn't find anything that could help me
```lua
:lua=require('lspconfig').jdtls
```
![Image](https://github.com/user-attachments/assets/8c85926c-3b09-4700-8b77-0f36b5ca7aca)

```lua
:lua=require('lspconfig').clangd
```
![Image](https://github.com/user-attachments/assets/a30b42cd-cffb-44a9-80e5-2984772a822e)

**Comment by glepnir** [comment]
it works fine. check your local env and try **minimal** config which does not include any config only have lspconfig.

![Image](https://github.com/user-attachments/assets/69b1fb1d-2ca5-472e-847b-173b5a8e0671)

**Comment by 93mmm** [comment]
following your advice: removed all caches and config, `:lua=require('lspconfig').jdtls`, now it works perfectly fine! Thanks a lot!
![Image](https://github.com/user-attachments/assets/6ae6a6ac-dd2d-4d2b-bce8-2d881e9fa527)

**Comment by Posrabi** [comment]
I got into a similar problem with neovim 0.9.1, bumping it to latest version fixes it
