### ISSUE TITLE
tailwindcss: 'on_attach' user callback never called

### ISSUE THREAD

**Issue by fnune** [neovim/nvim-lspconfig#3415]
### Description

I was trying to set up an `BufWritePre` action for the `tailwindcss` server like this:

```lua
      lspconfig.tailwindcss.setup({
        capabilities = cmp_lsp.default_capabilities(),
        on_attach = function(client, bufnr)
          vim.notify("HI FROM TAILWIND")
          vim.api.nvim_create_autocmd("BufWritePre", {
            buffer = bufnr,
            callback = function()
              vim.cmd("TailwindSortSync")
            end,
          })
        end,
      })
```

However, I never see `HI FROM TAILWIND` and the autocmd never registers. I modified `nvim-lspconfig` source locally to add some logging:

```diff
@@ -280,6 +280,12 @@ function configs.__newindex(t, config_name, config_def)
       return
     end
     local config = client.config --[[@as lspconfig.Config]]
+    vim.notify(
+      'Working on '
+        .. client.name
+        .. ' with config '
+        .. vim.inspect({ on_attach = config.on_attach, _attach_two = config._on_attach })
+    )
     if config._on_attach then
       config._on_attach(client, bufnr)
     end
```

When I pass `on_attach` to my setup of other language servers (I've tried `typescript-tools` and `biome`), then the log line contains both `on_attach` as well as `_on_attach`. However, when I pass it to `tailwindcss`, I only ever see `on_attach`,  and never `_on_attach`. This makes me suspect that the bug may be within Neovim source code somewhere. But it seems worthwhile posting it here.

The output is:

```
Working on biome with config {
  _on_attach = <function 1>,
  on_attach = <function 2>
}
HI FROM BIOME
Working on tailwindcss with config {
  on_attach = <function 1>
}
Working on typescript-tools with config {
  _on_attach = <function 1>,
  on_attach = <function 2>
}
HI FROM TSSERVER
Press ENTER or type command to continue
```

Here are the contents of my `lsp.log` after opening a file that attaches the `tailwindcss` server:

```
[START][2024-11-03 11:40:29] LSP logging initiated
[WARN][2024-11-03 11:40:29] ...lsp/handlers.lua:625	"Language mappings are currently set via initialization options (`userLanguages`). This is deprecated and will be removed in a future release. Please use the `tailwindCSS.includeLanguages` setting instead."
[WARN][2024-11-03 11:40:30] ...lsp/handlers.lua:135	"The language server tailwindcss triggers a registerCapability handler for workspace/didChangeWorkspaceFolders despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by fnune** [comment]
Alternative, for what it's worth:
```lua
vim.api.nvim_create_autocmd("LspAttach", {
  callback = function(args)
    if vim.lsp.get_client_by_id(args.data.client_id).name == "tailwindcss" then
      vim.api.nvim_create_autocmd("BufWritePre", {
        buffer = args.buf,
        callback = function()
          vim.cmd("TailwindSortSync")
        end,
      })
    end
  end,
})
```

**Comment by glepnir** [comment]
please try the minimal config which only include nvim-lspconfig i can't reproduce

![Image](https://github.com/user-attachments/assets/a1b4df48-a33e-4595-a019-e52daab8f4b5)

**Comment by fnune** [comment]
Argh, sorry to have wasted your time. It's my https://github.com/luckasRanarison/tailwind-tools.nvim installation which defaults to overriding the `lspconfig`-set-up LSP :(

**Comment by fnune** [comment]
To make things more confusing, there was a bug in `tailwind-tools` related to this: https://github.com/luckasRanarison/tailwind-tools.nvim/pull/63
