### ISSUE TITLE
Border for `vim.lsp.buf.hover` doesn't appear

### ISSUE THREAD

**Issue by wojciech-kulik** [neovim/nvim-lspconfig#3425]
### Description

Hi! 

I use `NVIM v0.11.0-dev-1092+g0da4d89558` and I try adding a border for the hover. However, it doesn't appear.

I set handlers as suggested in the Wiki:
```lua
local handlers = {
  ["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, { border = "rounded" }),
  ["textDocument/signatureHelp"] = vim.lsp.with(vim.lsp.handlers.signature_help, { border = "rounded" }),
}

lspconfig["lua_ls"].setup({
  handlers = handlers,
  ...
}
```

I also tried calling hover with a `border` option:
```lua
vim.lsp.buf.hover({ border = "rounded" })
```

Here is what I get (not border):
![Image](https://github.com/user-attachments/assets/cd664a80-0337-461a-b50e-7f933cb1fb9a)

**Comment by glepnir** [comment]
`:lua=vim.lsp.buf.hover({border = "single"})` this works for me

**Comment by wojciech-kulik** [comment]
@glepnir did you check on the latest nightly version? Or you don't support the latest Neovim?

**Comment by glepnir** [comment]
my neovim build from source with last commit every day

**Comment by n-crespo** [comment]
Were you able to fix the problem by disabling or editing your noice config?

**Comment by wojciech-kulik** [comment]
I disabled Noice for hover:

```lua
lsp = {
  hover = { enabled = false },
}
```

**Comment by m15a** [comment]
I have the same problem: setting handlers in LSP setup function doesn't work while just running `:lua=vim.lsp.buf.hover({border = "single"})` works.
I use Neovim v0.11.0-dev nightly and do not use noice plugin.

The recent change on `vim.lsp.buf.hover()` shown below might be the cause?
https://github.com/neovim/neovim/blob/359763307546ae7a401e9458fefeb6f4cd37a40f/runtime/doc/news.txt#L91-L92

     |vim.lsp.buf.hover()| now support merging the results of multiple clients
     but no longer trigger the global handlers from `vim.lsp.handlers`

**Comment by rbjorklin** [comment]
I started out with the same config as in the first post and ended up with:
```lua
keymap("n", "K", function() vim.lsp.buf.hover({ border = "rounded"}) end, opts)
keymap("n", "<C-k>", function() vim.lsp.buf.signature_help({ border = "rounded" }) end, opts)
```
