### ISSUE TITLE
handling of `vim.lsp.buf.execute_command` deprecation

### ISSUE THREAD

**Issue by DimitrisDimitropoulos** [neovim/nvim-lspconfig#3426]
### Description

I noticed that recently the `vim.lsp.buf.execute_command` has been deprecated and replaced with `Client:exec_cmd`, [see](https://github.com/neovim/neovim/pull/30932). I have already adapted most of the occurrences, in the texlab configuration, of the old way to use the new method. However, the new method is only available on newer nightly versions. How should the new way be deployed , in order to cause the least amount of disturbance to the users?

**Comment by glepnir** [comment]
ref utils.lua have nvim_eleven  you can use same logic in textleb config
