### ISSUE TITLE
Pylyzer requires Erg as dependency, suggest adding this info

### ISSUE THREAD

**Issue by fishBone000** [neovim/nvim-lspconfig#3433]
### Description

Pylyzer needs Erg to function correctly, whose path to its binary and libs should be stored in env var $ERG_PATH:
> [ERROR][2024-11-11 12:08:17] .../vim/lsp/rpc.lua:770	"rpc"	"/home/fishbone/.local/share/nvim/mason/bin/pylyzer"	"stderr"	"\27[91m[ERR] ERG_PATH not found\27[m\n"

I can resolve this by extracting tar from [Erg release](https://github.com/erg-lang/erg/releases/tag/v0.6.47) to my `~/.erg`, then export env var by `vim.fn.setenv("ERG_PATH", vim.fn.getenv("HOME") .. "/.erg")`

However no such info regarding Erg is provided in `lspconfig-all`. I suggest adding this, or even better, adding `erg_path` option to let lspconfig handle exporting the env var automatically.

**Comment by fishBone000** [comment]
File structure of Erg tarball:
```plain
tar -tf erg-x86_64-unknown-linux-gnu.tar.gz                                                                                                                                     exit 1  47s
erg
lib/
lib/std/
lib/std/exception.er
...and more lib/ files
```

**Comment by justinmk** [comment]
send a pr
