### ISSUE TITLE
ansiblels ansible.validation.lint.enabled doesn't work

### ISSUE THREAD

**Issue by daniyl-x** [neovim/nvim-lspconfig#3446]
### Description

ansiblels asks for ansible-lint every time when it's not installed or uses it when available.

Accordingly to both [official docs](https://ansible.readthedocs.io/projects/vscode-ansible/als/settings/#validation.lint.enabled) and [nvim-lspconfig docs](https://github.com/neovim/nvim-lspconfig/blob/master/doc/configs.md#ansiblels) ansible-lint usage can be disabled by setting ansible.validation.lint.enabled to false.

### My LSP config:
```lua
require("lspconfig").setup {
    settings = {
        ansible = {
            validation = {
                lint = {
                    enabled = false,
                }
            }
        }
    }
}
```

### The warning (when no ansible-lint installed)
```
Ansible-lint is not available. Kindly check the path or disable validation using ansible-lint:
Type number and <Enter> or click with the mouse (q or empty cancels):
```

### Expected behavior:
- **No ansible-lint installed:** no ansible-lint  warning when opening file
- **With ansible-lint installed:** no ansible-lint hints in buffer

### Actual behavior:
- **No ansible-lint installed:** ansible-lint  warning when opening file
- **With ansible-lint installed:** ansible-lint hints in buffer

**Comment by lithammer** [comment]
It's because you're calling the wrong `setup()` function.

```diff
-require("lspconfig").setup {
+require("lspconfig").ansiblels.setup {
```
