### ISSUE TITLE
dartls: writing hebrew in multiline strings causes error

### ISSUE THREAD

**Issue by eifr** [neovim/nvim-lspconfig#3455]
### Description

writing hebrew in 3-single-quotes `.dart` file causes error
![Image](https://github.com/user-attachments/assets/99a2e3d2-99a8-43ef-a9a7-8d6bd127f7ef)

example:
```dart
final jsonRes = '''
א
''';
```

**Comment by glepnir** [comment]
the error seems like from semantic_tokens.lua please report on neovim thanks.
