### ISSUE TITLE
manager.lua:76: attempt to index field 'Methods' (a nil value)

### ISSUE THREAD

**Issue by 93mmm** [neovim/nvim-lspconfig#3467]
### Description

updated config tonight, caught an error while trying to switch between files:
```lua
[lspconfig] unhandled error: ...share/nvim/lazy/nvim-lspconfig/lua/lspconfig/manager.lua:76: attempt to index field 'Methods' (a nil value)
```

**Comment by justinmk** [comment]
I'm guessing you have Nvim 0.9? Please, always mention the Nvim version when reporting anything.

https://github.com/neovim/nvim-lspconfig/commit/8d9fd3581ac07a2e1940435e13bda31a0cdeb795

we probably need to revert that line back to 

    client.rpc.notify('workspace/didChangeWorkspaceFolders', params)

**Comment by edoardo-bluframe** [comment]
Same warning here! **Super** annoying notification every time we open a new file :smile: 

nvim 0.9+ and astronvim

Looks like that commit fixes it next release yeah?? :smile:

**Comment by justinmk** [comment]
@edoardo-bluframe this was already fixed. there was no "release" with or without the fix.

**Comment by edoardo-bluframe** [comment]
> [@edoardo-bluframe](https://github.com/edoardo-bluframe) this was already fixed. there was no "release" with or without the fix.

Maybe I am missing something then? Why does it keep popping up **every** time we open a file for the first time in the nvim notifications? And why did this start about 2 weeks ago? 😄
