### ISSUE TITLE
[BUG]: dirname and sanitize were just removed from path instead of being deprecated

### ISSUE THREAD

**Issue by kapral18** [neovim/nvim-lspconfig#3472]
### Description

2 hours ago this change happened

https://github.com/neovim/nvim-lspconfig/commit/d651732cecfc77be1b3727512bec0438c22410d1#diff-9e30880c16142e9d50a64563fd1260aa9f851b782dd74678163e151b93878568L217-L219

They were grouped in the end but on the instance of `util` module and not `util.path` where they belong

This causes `util.path.sanitize()` to error out

**Comment by glepnir** [comment]
please update it fixed just now.
