### ISSUE TITLE
link for downloading elixir-ls is returning `404` on `curl` command

### ISSUE THREAD

**Issue by HicaroD** [neovim/nvim-lspconfig#3488]
#### Command
![Image](https://github.com/user-attachments/assets/3d03140f-36b4-4dbb-9542-53068b49fe85)

#### Result
![Image](https://github.com/user-attachments/assets/21a08ba1-7368-478b-8ec6-f00cb6f8a7f7)

**Comment by HicaroD** [comment]
I went to the language server repository and the following command works properly:

`curl -fLO https://github.com/elixir-lsp/elixir-ls/releases/download/v0.24.1/elixir-ls-v0.24.1.zip`

**Comment by justinmk** [comment]
yeah, they broke their artifacts, so now we can't provide a `curl` command without knowing an exact artifact version.
