### ISSUE TITLE
Fail to start kotlin-language-server due to suffix extension

### ISSUE THREAD

**Issue by KevinNitroG** [neovim/nvim-lspconfig#3499]
### Description

In the kotlin-language-server README, they say the executable file can be suffixed with sh, cmd, or bat (https://github.com/fwcd/kotlin-language-server#figuring-out-the-dependencies). However, the current nvim-lspconfig for kotlin LSP on Windows will be suffixed with .bat, which failed to start on my machine.

![Image](https://github.com/user-attachments/assets/47d26e5e-f37d-4d8a-871e-9491be14b9a9)

Current nvim-lspconfig: https://github.com/neovim/nvim-lspconfig/blob/5a812abc65d529ea7673059a348814c21d7f87ff/lua/lspconfig/configs/kotlin_language_server.lua#L4C1-L7C1

I tried to remove the suffix extension (`cmd = { 'kotlin-language-server' }`), and it worked fine. Also `kotlin-language-server.cmd` exist on my PATH (installed via mason), not `kotlin-language-server.bat`

**Comment by justinmk** [comment]
Looks like a bug, that part of the config is 3 years old. Send a PR to fix it?

**Comment by KevinNitroG** [comment]
Alright I'm gonna create a PR for this
