### ISSUE TITLE
f675f broke ("refactor: deprecate util.find_package_json_ancestor")

### ISSUE THREAD

**Issue by jacobrreed** [neovim/nvim-lspconfig#3503]
### Description

Moving from https://github.com/neovim/nvim-lspconfig/commit/124be12d782d656b3c75b513a44d9e4728406078 to https://github.com/neovim/nvim-lspconfig/commit/f675f8c430ae3012f6d140899c2cec3b59e9cb43 breaks lspconfig for me

```                      
[lspconfig] unhandled error: ...al/share/nvim/lazy/nvim-lspconfig/lua/lspconfig/util.lua:256: bad argument #1 to 'lines' (/Users/jrreed/dev/drg-maui-plugin/package.json/package.json: Not a directory)
```

I manually tested moving between both commits, works fine on previous commit

**Comment by justinmk** [comment]
does reverting the change in `lua/lspconfig/util.lua` specifically, fix the issue?

**Comment by jacobrreed** [comment]
![Image](https://github.com/user-attachments/assets/d27e0e1a-7043-4a94-b169-061090a880af)

**Comment by justinmk** [comment]
Oh, the problem is that the new `fs.find()` call is returning the `package.json` file, but it should return the parent dir.

**Comment by monoira** [comment]
same problem here.

**Comment by minusfive** [comment]
Same

**Comment by jacobrreed** [comment]
> Oh, the problem is that the new `fs.find()` call is returning the `package.json` file, but it should return the parent dir.

Opened PR, simply wrapped the vim.fs.find with vim.fs.dirname
