### ISSUE TITLE
Error: [lspconfig] unhandled error: vim/fs.lua:0: path: expected string, got function

### ISSUE THREAD

**Issue by igorgue** [neovim/nvim-lspconfig#3512]
### Description

Getting this warning with basedpyright:

```
[lspconfig] unhandled error: vim/fs.lua:0: path: expected string, got function
```

I'm using LazyVim with this config:

https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/plugins/extras/lang/python.lua

**Comment by janwaltl** [comment]
I have just started getting this error for ruff_lsp couple minutes ago. For me, I think the cause is change in https://github.com/neovim/nvim-lspconfig/commit/12d163c5c2b05e85431f2deef5d9d59a8fd8dfc2 in `root_dir` - `util.root_pattern` function is not applied to `fname` but instead it is returned.

**Comment by igorgue** [comment]
@janwaltl Yeah looks like the same problem I wonder how I can fix it at least locally...

**Comment by igorgue** [comment]
Reverting to `124be12d782d656b3c75b513a44d9e4728406078` fixes my issue.
