### ISSUE TITLE
gopls removes all comments if 'C' package is imported

### ISSUE THREAD

**Issue by roskee** [neovim/nvim-lspconfig#3518]
### Description

I have the following lspconfig in neovim
```
lspconfig.gopls.setup({
  on_attach = on_attach,
  capabilities = capabilities,
  cmd = { "gopls"},
  filetypes = {"go", "gomod", "gowork", "gotmpl"},
  root_dir = util.root_pattern("go.mod"),
  settings = {
    gopls = {
      completeUnimported = true,
      analyses = {
        unusedparams = true,
        unreachable = true,
      },
      hints = {
        parameterNames = true,
        assignVariableTypes = true,
        compositeLiteralFields = true,
        constantValues = true,
        functionTypeParameters = true,
      }
    }
  }
})
```

I created a main.go file with the following content
```
package main

// #include <stdio.h>
// void hello() {
//    printf("Hello from C\n");
//    fflush(stdout);
// }
import "C"
func main() {
	C.hello()
	C.hello()
}
```

The lsp shows an error saying 'regenerate cgo definitions'. I didn't mind the error but when I tried to save the file with `:w` the lsp removes all comments in the code including the c function before the import and even any other comments in the file. Am I missing something? I have saved the file with the old school vi and it compiles and executes fine.

**Comment by glepnir** [comment]
upstream https://github.com/golang/go/issues/35721
