### ISSUE TITLE
Question: coc-settings.json alternative in nvim-lsp

### ISSUE THREAD

**Issue by RishabhRD** [neovim/nvim-lspconfig#357]
coc provides coc-settings.json file where we can write any default configuration for clangd and other lsp client. For clangd configuration it supports fallbackFlags. This enables us to set extra clang flags used to parse files when no compilation database is found.
Is there any similiar thing corresponding in nvim-lsp.

**Comment by osherbz** [comment]
I don't work on this project, but I think that you can add flags in the cmd command(If I understand your question correctly).
https://github.com/neovim/nvim-lspconfig#clangd -- read the clangd section In readme.md
https://github.com/neovim/nvim-lspconfig#example-override-some-defaults -- example of overriding some defaults
for example: 
require'nvim_lsp'.clangd.setup{
  on_attach...., 
  **cmd ={ "clangd", "--background-index","other flags",...,..., }**
}
I hope this info helpful.

**Comment by RishabhRD** [comment]
Oh yes!! I am really surprised why didn't I think that. It works prefectly and it should. My mistake
