### ISSUE TITLE
lsp for golang (gopls) failed to launch inside pkg/mod folder if .mod/.git not existed

### ISSUE THREAD

**Issue by ray-x** [neovim/nvim-lspconfig#362]
- `nvim --version`:
NVIM v0.5.0-651-gaa60cb108
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/Users/ray.xu/github/neovim/build/config -I/Users/ray.xu/github/neovim/src -I/Users/ray.xu/github/neovim/.deps/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/Users/ray.xu/github/neovim/build/src/nvim/auto -I/Users/ray.xu/github/neovim/build/include
Features: +acl +iconv +tui
See ":help feature-compile"
   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

- nvim-lsp version(commit hash): Latest
- `:checkhealth` :

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: gopls: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized (DEBUG) build. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
- What language server(If the problem is related to a specific language server):
- Operating system/version:
- Terminal name/version:
- `$TERM`:

### How to reproduce the problem from neovim startup
minium config(vimrc.min):

```vim
call plug#begin('~/.vim/plugged')
Plug 'neovim/nvim-lspconfig'
call plug#end()
lua <<EOF
local nvim_lsp = require('nvim_lsp')
nvim_lsp.gopls.setup{
    on_attach=on_attach_vim
}
local servers = { 'gopls', 'tsserver' }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup {
    on_attach = on_attach,
  }
end

EOF


nnoremap <silent> gd    <cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <silent> <c-]> <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <silent> K     <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap <silent> gD    <cmd>lua vim.lsp.buf.implementation()<CR>
nnoremap <silent> <c-k> <cmd>lua vim.lsp.buf.signature_help()<CR>
nnoremap <silent> 1gD   <cmd>lua vim.lsp.buf.type_definition()<CR>
nnoremap <silent> gr    <cmd>lua vim.lsp.buf.references()<CR>
nnoremap <silent> g0    <cmd>lua vim.lsp.buf.document_symbol()<CR>
nnoremap <silent> gW    <cmd>lua vim.lsp.buf.workspace_symbol()<CR>
nnoremap <buffer> <silent> <C-LeftMouse> <LeftMouse> <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <buffer> <silent> g<LeftMouse> <LeftMouse> <cmd>lua vim.lsp.buf.implementation()<CR>
```

cd into pkg/mod folder e.g.
go/pkg/mod/github.com/newrelic/go-agent@v2.2.0+incompatible
use nvim to open the source code e.g. 
`nvim -u ~/github/dotfiles/vimrc.min internal_app.go`

The folder do not have go.sum/go.mod/.git and it seems gopls failed to detect the root dir and failed to launch.  I could not use c-] to navigate in the code.

### Actual behaviour
gopls and lsp failed to work.

### Expected behaviour
gopls should still work inside pkg folder where some of the package do not contains go.mod/.git

**Comment by lithammer** [comment]
You can change the `root_dir` yourself to include `util.path.dirname(...)` (which will use the directory of the opened buffer as root). Or you can just add more patterns to `util.root_pattern(...)`.

```diff
 local nvim_lsp = require('nvim_lsp')
+local util = require('nvim_lsp/util')
 nvim_lsp.gopls.setup{
-     on_attach=on_attach_vim
+     on_attach=on_attach_vim,
+     root_dir = function(fname)
+       return util.root_pattern("go.mod", ".git")(fname) or
+         util.path.dirname(fname)
+     end
 }
 local servers = { 'gopls', 'tsserver' }
 for _, lsp in ipairs(servers) do
   nvim_lsp[lsp].setup {
     on_attach = on_attach,
   }
 end
```

**Comment by ray-x** [comment]
The changes works for me. Really appreciated. 
Maybe put this as default gopls setup in the documents.

**Comment by lithammer** [comment]
I think `util.path.dirname(fname)` is generally a good fallback for all language servers. Unless some kind of fallback is implemented on the server side, but my experience is that most don't.

**Comment by ray-x** [comment]
Maybe from golang 1.12, golang is using mod `GO111MODULE=on` by default. And it will not use current directory.

**Comment by ray-x** [comment]
I think the bug could be closed. The comment https://github.com/neovim/nvim-lspconfig/issues/362#issuecomment-696541248
solved my issue.

**Comment by chiendo97** [comment]
Update because I got error `nvim_lsp/util` not found. 
```lua
local nvim_lsp = require('lspconfig')
local util = require "lspconfig/util"

nvim_lsp.gopls.setup {
    root_dir = function(fname)
        return util.root_pattern('go.mod', '.git')(fname) or
                   util.path.dirname(fname)
    end,
}
```

**Comment by mjlbach** [comment]
I guarantee you it works. Here's a minimal init.lua with your snippet injected. Just drop this in any lua file, then run `nvim -u my_minimal_init.lua`

```lua
-- install packer
local fn = vim.fn

local install_path = "/tmp/nvim/site/pack/packer/start/packer.nvim"

vim.cmd [[set packpath=/tmp/nvim/site]]

local function load_plugins()
  local use = require("packer").use
  require("packer").startup {
    function()
      use "wbthomason/packer.nvim"
      use "neovim/nvim-lspconfig"
    end,
    config = { package_root = "/tmp/nvim/site/pack" },
  }
end

_G.load_config = function()
  vim.lsp.set_log_level "trace"
  local nvim_lsp = require "lspconfig"
  local on_attach = function(_, bufnr)
    local function buf_set_keymap(...)
      vim.api.nvim_buf_set_keymap(bufnr, ...)
    end
    local function buf_set_option(...)
      vim.api.nvim_buf_set_option(bufnr, ...)
    end

    buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

    -- Mappings.
    local opts = { noremap = true, silent = true }
    buf_set_keymap("n", "gd", "<Cmd>lua vim.lsp.buf.definition()<CR>", opts)
    buf_set_keymap("n", "K", "<Cmd>lua vim.lsp.buf.hover()<CR>", opts)s)
  end

  local nvim_lsp = require('lspconfig')
  local util = require "lspconfig/util"
  
  nvim_lsp.gopls.setup {
      root_dir = function(fname)
          return util.root_pattern('go.mod', '.git')(fname) or
                     util.path.dirname(fname)
      end,
  }
end

if fn.isdirectory(install_path) == 0 then
  fn.system { "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path }
  load_plugins()
  require("packer").sync()
  vim.cmd "autocmd User PackerComplete ++once lua load_config()"
else
  load_plugins()
  _G.load_config()
end
```
