### ISSUE TITLE
Organize readme.md contents into vim-compatible docs/helptags

### ISSUE THREAD

**Issue by Happy-Dude** [neovim/nvim-lspconfig#367]
While the readme seems to be automatically generated via GitHub Actions, it has gotten pretty large, unwieldy, and cluttered overall.

Before 0.5.0 is live, can those docs be reorganized to support vim-styled help documentation and tags?
A good reference style would probably be how ALE laid out their docs: https://github.com/dense-analysis/ale/tree/master/doc

**Comment by mjlbach** [comment]
I started working on this, open for comments. https://github.com/neovim/nvim-lspconfig/compare/master...mjlbach:readme

**Comment by mjlbach** [comment]
As we move towards 0.5, I'd like this to get done, but I really don't want to manually edit the readme. If anyone has suggesion for (maintained) markdown to vimdoc converters please comment.

**Comment by Mathijs-Bakker** [comment]
I could take a look at this.

**Comment by mjlbach** [comment]
> The best solution would be to build a GitHub action (as there's none yet).

Easy part :) 

> One that auto generates vim docs from markdown.

Hard part :( 

I talked to glacambre about this, and they also gave up (currently) and generating vimdocs. There's not a good converterd (the one I checked out seemed like it's not going to deliver satisfactory results).

**Comment by mjlbach** [comment]
I'm thinking of just throwing a manually generated helpdoc (not anything with server specific setting ofc) and calling it a day, with a disclaimer that the README.md is more up to date.

**Comment by mjlbach** [comment]
I have a prototype tree-sitter based markdown to vimdoc converter working here (using Readme.md from nvim-lspconfig as a demo): https://github.com/mjlbach/babelfish.nvim

Contributions encouraged.
