### ISSUE TITLE
File-wide code-actions with JDTLS

### ISSUE THREAD

**Issue by jacksonludwig** [neovim/nvim-lspconfig#369]
I haven't been able to do certain code actions, e.g. ``Generate Getters and Setters`` or ``Generate Constructor``, unless there is already a warning about them not existing. Only sometimes, for example, does ``Generate toString()`` show up.

To me, it seems like right now I am only getting code actions that deal with selections or snippets of code, e.g. using a code action to fix an error.

In COC, there are two separate commands -- codeaction for section/selection, and codeaction for entire file.

Can the same be done with this plugin? Java can be quite annoying without these code actions to quicken things up!

Thank you.

**Comment by ludwj61** [comment]
Also, another question, can snippets built in be disabled?

**Comment by mfussenegger** [comment]
Some of the code actions of jdtls require special client extensions that are not part of the default LSP specification.

To get them working you could take a look at [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls). It's a plugin that extends the built-in LSP client to support jdtls specific extensions.

**Comment by laxman20** [comment]
@mfussenegger's extension is excellent and I highly recommend it over the configuration in this repo.

The jdt language server has too much custom implementation required by lsp clients (I don't think they understood the point of language server protocol). A lot of which is not included in this repository.

**Comment by ludwj61** [comment]
Thanks guys, this is very helpful. I guess I will leave this open, though, because maybe these things can be added in the future to this repo?

**Comment by mjlbach** [comment]
I'm going to close this, as I think we provide a minimal jdtls config (finally got it working) that does provide code actions that adhere to the spec, jdtls implements so many non protocol adherent options, and @mfussenegger's nvim-jdtls is a great plugin.
