### ISSUE TITLE
rust_analyzer can't be automatically installed (yet)

### ISSUE THREAD

**Issue by marioidival** [neovim/nvim-lspconfig#374]
- `nvim --version`: v0.5.0-727-gc10c2fab5
- nvim-lsp version(commit hash): nightly-20201003
- `:checkhealth` result
```
    1 health#nvim_lsp#check
    2 ========================================================================
    3 ## Checking language server protocol configuration
```
    just that...
- What language server(If the problem is related to a specific language server):
Rust Analyzer
- Operating system/version: Windows 10
- Terminal name/version:
- `$TERM`:

### How to reproduce the problem from neovim startup
:LspInstall rust_analyzer

### Actual behaviour
rust_analyzer can't be automatically installed (yet)
### Expected behaviour
I don't know, I never use this plugin before.

**Comment by JulpikarGupran** [comment]
Yes `:LspInstall rust_analyzer` not supported yet, but you can manually install rust-analyzer by yourself from [https://github.com/rust-analyzer/rust-analyzer](url), and rust_analyzer executable to your environment path.

**Comment by marioidival** [comment]
@JulpikarGupran thank you
