### ISSUE TITLE
[Enhancement] Pyls use g:python3_host_prog for path to pyls

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [neovim/nvim-lspconfig#376]
Title says it all. It feels a little odd that `pyls` cannot be found  when it exists in `g:python3_host_prog`.

**Comment by lithammer** [comment]
I don't think you can safely assume that though. For me, the Python pointed to by `g:python3_host_prog` is almost never the same as where `pyls` exists.

For example, I install `pyls` with [`pipx`](https://pipxproject.github.io/pipx/) or directly into a project-specific virtualenv. And `g:python3_host_prog` just points to system Python, e.g. `/usr/local/bin/python3`.

**Comment by Th3Whit3Wolf** [comment]
I'm not saying everyone uses it that way but people definitely do. [Rafi's vim config](https://github.com/rafi/vim-config), which has over 1 thousand stars, for example uses it this way. 

Checking if it exists in `g:python3_host_prog` doesn't seem very expensive.

**Comment by mjlbach** [comment]
I'm not sure this is a good idea, as I think pyls can only provide completions for a given virtualenv if installed within the currently active virtualenv (not sure if this is the case anymore, as I've switched to using pyright)

**Comment by Th3Whit3Wolf** [comment]
That's a good point
