### ISSUE TITLE
Question: hide completion description from scratch

### ISSUE THREAD

**Issue by hissssst** [neovim/nvim-lspconfig#378]
Currently omnicompletion menu opens scratch split on top of my current buffer to preview completion documentation. Can I changle this behaviour?

![scrot_201009093031](https://user-images.githubusercontent.com/37012324/95550878-2d830500-09f9-11eb-8e76-98420cfa7f38.png)

**Comment by 0x6273** [comment]
It can be disabled with `set completeopt-=preview`
