### ISSUE TITLE
Terraform LSP does not work

### ISSUE THREAD

**Issue by alexaandru** [neovim/nvim-lspconfig#380]
- nvim `v0.5.0-746-gf7cc3ae0b`
- nvim-lsp version(commit hash): `60133c`
- `:checkhealth` result: no error: `INFO: terraformls: configuration checked`
- terraform-ls `v0.8.0`
- `xterm-kitty`:

### How to reproduce the problem from neovim startup

Given `test.vim`:

```VimL
packadd nvim-lspconfig
lua require'nvim_lsp'.terraformls.setup{}
```

and `test.tf`:

```Terraform
resource "null_resource" "void" {
  provisioner "local-exec" {
    command = "echo Hello World > success.txt"
  }
}

bogus should upset LSP...
```

and having initialized it with `terraform init`...

### Actual behaviour

`nvim -u test.vim test.tf` shows no error, even though the Terraform code is obviously invalid.
You can also run `terraform validate` to confirm the code is invalid.

### Expected behaviour

I expect LSP to complain about invalid code (at the very least) OR `:checkhealth` to report there is an issue with the LSP setup, if that's what the problem is.

I can run `terraform-ls` manually just fine, however I do not see `terraformls` in the output of `:LspInstallInfo` at all.

**Comment by lithammer** [comment]
See https://github.com/neovim/nvim-lspconfig/pull/351

**Comment by alexaandru** [comment]
Sorry I missed that @lithammer , not sure how, I did search for `terraform` before creating this ticket... yup, it just won't come up: https://github.com/neovim/nvim-lspconfig/issues?q=is%3Aissue+terraform+is%3Aopen  

Should I close this one?

**Comment by lithammer** [comment]
> Sorry I missed that @lithammer , not sure how, I did search for `terraform` before creating this ticket... yup, it just won't come up: https://github.com/neovim/nvim-lspconfig/issues?q=is%3Aissue+terraform+is%3Aopen

Probably because it's a pull request, and not an issue 😉 

> Should I close this one?

Depends. Did you try the workaround mentioned in #351?

**Comment by alexaandru** [comment]
> > Sorry I missed that @lithammer , not sure how, I did search for `terraform` before creating this ticket... yup, it just won't come up: https://github.com/neovim/nvim-lspconfig/issues?q=is%3Aissue+terraform+is%3Aopen
> 
> Probably because it's a pull request, and not an issue 
> 
That would explain it 🙂

> > Should I close this one?
> 
> Depends. Did you try the workaround mentioned in #351?
Nope, seems like it does not. The updated `test.vim` is now:

```VimL
packadd nvim-lspconfig
lua require'nvim_lsp'.terraformls.setup{cmd = {'terraform-ls', 'serve'}}
```

Running the command manually seems fine:

```
$ terraform-ls serve
2020/10/12 18:11:35 serve_command.go:137: Starting terraform-ls 0.8.0
2020/10/12 18:11:35 service.go:61: Preparing new session ...
2020/10/12 18:11:35 service.go:78: Worker pool size set to 24
2020/10/12 18:11:35 watcher.go:118: watching for changes ...
2020/10/12 18:11:35 langserver.go:69: Starting server (pid 2006877) ...
```

**Comment by lithammer** [comment]
Might be a problem with `root_uri` then. Do you have either `.terraform` or  `.git` in the same directory?

**Comment by alexaandru** [comment]
Yes, I do. In the OP, under "How to reproduce..." the last step I gave was to run `terraform init`. That will initialize the `.terraform` folder (among other things).

**Comment by lithammer** [comment]
Check what the logs say. You can find its location with this:

```vim
:lua print(vim.lsp.get_log_path())
```

**Comment by alexaandru** [comment]
Very nice - progress! :) 

```
[ ERROR ] 2020-10-12T15:54:27+0300 ] ..._nvim.a7VNZhj/usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:428 ]	"rpc"	"terraform-ls"	"stderr"	"Usage: terraform-ls [--version] [--help] <command> [<args>]\n\nAvailable commands are:\n    completion        Lists available completion items\n    inspect-module    Lists available debug items\n    serve             Starts the Language Server\n\n"
```

Obviously, I do NOT have `terraform-ls stderr` in my config, I have what was suggested earlier and posted above. Thank you!

**Comment by lithammer** [comment]
Now that GH-351 have been merged, I guess this can bli closed?

**Comment by alexaandru** [comment]
Seems to be working fine now, with my regular `init.vim`. For some reason, I cannot get it to work with the code provided in the OP, no idea why. Seems like that alone should be sufficient to have the LSP kick in.

Anyway, it works, so AFAIAC it can be closed. Thank you! :)

**Comment by lithammer** [comment]
I'm not a maintainer, but maybe it's easier if you close it yourself?

**Comment by mnarrell** [comment]
Is this actually working for you?  Even with the overridden cmd, before this commit, I get nothing from the Terraform server.

**Comment by h-michael** [comment]
@mnarrell It works for me.
Provide me with a minimal code base that doesn't boot and I'll try to debug it.

**Comment by mnarrell** [comment]
A simple provider definition:
```
provider "kubernetes" {
  insecure         = true
  load_config_file = false
  host             = var.kubernetes_api_host
  token            = var.rdei_token
}
```
nvim-lsp configured as: `require'lspconfig'.setup{}`

I open this file (with a terraform init'd directory) and I see the lsp output in the logs.  If I try the hover action implemented here: https://github.com/hashicorp/terraform-ls/pull/294, im told the following:

```
[ ERROR ] 2020-11-15T18:27:12-0700 ] ...ocal/share/neovim/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]  "rpc"   "terraform-ls"  "stderr"        "2020/11/15 18:27:12 root_module.go:254: loading of root module /Users/matt/tmp/example finished: 0 errors occurred:\n\t\n\n"
[ WARN ] 2020-11-15T18:27:16-0700 ] ...t/.local/share/neovim/share/nvim/runtime/lua/vim/lsp.lua:85 ]    "method textDocument/hover is not supported by any of the servers registered for the current buffer"
```

Am I missing additional configuration?

**Comment by h-michael** [comment]
@mnarrell 
terraform-ls which is implemented "hover" has not yet been release.
https://github.com/hashicorp/terraform-ls/tree/v0.9.0/internal/lsp
<img width="988" alt="Screen Shot 2020-11-16 at 12 54 43" src="https://user-images.githubusercontent.com/4556097/99211158-0ba44b80-280b-11eb-80c9-8af87cfa08ca.png">

If you want to use that feature, you can use it if you build it yourself.

**Comment by mnarrell** [comment]
I see.  Apologies for my confusion...

**Comment by h-michael** [comment]
@mnarrell No problem :)
