### ISSUE TITLE
LspInstall pyls_ms fails to report missing unzip command

### ISSUE THREAD

**Issue by dutchgecko** [neovim/nvim-lspconfig#389]
- What language server(If the problem is related to a specific language server):
    - pyls_ms
- Operating system/version:
    Ubuntu 20.04

### How to reproduce the problem from neovim startup

On a system without the `unzip` command installed, run `:LspInstall pyls_ms` from nvim.

### Actual behaviour

The LspInstall command fails silently, without output. Inspecting the nvim cache directory reveals that a `pyls.nupkg` file has been placed, but no further processing occurred.

### Expected behaviour

The process should have given a clear error that the `unzip` command is not available. From examining the source, it appears this is already done for a few other requirements, but unzip has been skipped.

**Comment by mjlbach** [comment]
I wrote the original config/install, but I think generally the sentiment is that we're moving install actions out of the plugin, but it shouldn't be too hard to fix this (sorry for the oversight). Also microsoft's python language server is deprecated in favor of pyright, so I would be in favor of removing the config altogether.

**Comment by mjlbach** [comment]
@dutchgecko Do you want to test #405 for me?
