### ISSUE TITLE
[FeatureRequest] rust-analyzer to support loading output dirs

### ISSUE THREAD

**Issue by damienpontifex** [neovim/nvim-lspconfig#391]
See setting for VSCode https://github.com/rust-analyzer/rust-analyzer/issues/1964#issuecomment-600530924 such that rust-analyzer will look in `OUT_DIR`.

Opening this issue if another finds the implementation specifics for rust-analyzer here for nvim-lspconfig. And whether it's something that would become part of the default, or just updated docs to indicate how to include add it if desired

**Comment by mjlbach** [comment]
How common is having this enabled, and are there common cases where it should *not* be enabled? It's trivial to add right now.

```
require'lspconfig'.rust_analyzer.setup{
  settings = {
    rust_analyzer = {
      cargoFeatures = {
        loadOutDirsFromCheck = true;
      }
    }
  }
}
```

**Comment by damienpontifex** [comment]
Thanks @mjlbach I wasn't aware of the settings value there. I'll do that in my local config

**Comment by mjlbach** [comment]
@damienpontifex Glad to help, but my question is mostly should this be on by default? I'm a casual rust user and have never used this

**Comment by damienpontifex** [comment]
Probably shouldn't be by default. 

I was only looking to use the setting with `rust-bindgen` and `OUT_DIR` as described https://rust-lang.github.io/rust-bindgen/tutorial-3.html

I can't imagine this is a common enough scenario to be having it set as `true` by default
