### ISSUE TITLE
ElixirLS error

### ISSUE THREAD

**Issue by hissssst** [neovim/nvim-lspconfig#407]
- `nvim --version`: `NVIM v0.5.0-765-g75996a2cd`
- nvim-lsp version(commit hash): `1f86bfd62d0ba78b0479373661be3fa13f1f8f35`
- `:checkhealth` result - everything `OK`
- What language server(If the problem is related to a specific language server): `ElixirLS 0.6.2 3acc1fdb2ef2c1167935f7b6e74300e039200ec5`
- Operating system/version: `linux 5.7.12`

### How to reproduce the problem from neovim startup

* Enter directory with `mix.exs` (a.k.a elixir project root)
* `$ nvim mix.exs`

### Actual behaviour
```
Error detected while processing function LspStatus:
line    2:
E5108: Error executing lua ...m/plugged/lsp-status.nvim/lua/lsp-status/diagnostics.lua:12: attempt to index field 'diagnostic' (a nil value)
Press ENTER or type command to continue
Error detected while processing function LspStatus:
line    2:
E5108: Error executing lua ...m/plugged/lsp-status.nvim/lua/lsp-status/diagnostics.lua:12: attempt to index field 'diagnostic' (a nil value)
```

### Expected behaviour

No errors

### Additional info

* Happened after upgrade from `nvim-lsp` to `lspconfig`
* All `elixir_ls` tests successfully passed

**Comment by lithammer** [comment]
I think you just need to update https://github.com/nvim-lua/lsp-status.nvim that includes the recent diagnostic changes. See https://github.com/nvim-lua/lsp-status.nvim/issues/19 and https://github.com/neovim/neovim/pull/12655.

**Comment by hissssst** [comment]
@lithammer thanks, I'll try it out right now

**Comment by lithammer** [comment]
Also ensure you have the latest Neovim nightly for good measure.

**Comment by hissssst** [comment]
Same issue with `NVIM v0.5.0-828-g0a95549d6` (latest prebuilt package avaliable in AUR)
Guess I'll have to build from master

**Comment by mjlbach** [comment]
@hissssst Is this still an issue?

**Comment by hissssst** [comment]
Fixed in current nighly release
