### ISSUE TITLE
gopls language server error messages

### ISSUE THREAD

**Issue by the42** [neovim/nvim-lspconfig#411]
- `nvim --version`: v0.5.0-828-g0a95549d6
- nvim-lsp version(commit hash):
- What language server(If the problem is related to a specific language server): gopls
- Operating system/version: uname -a: Linux ebola 5.9.3-1-MANJARO #1 SMP PREEMPT Sun Nov 1 14:25:36 UTC 2020 x86_64 GNU/Linux
- Terminal name/version: Gnome Terminal
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup
Open any .go - file

### Actual behaviour
Error message:

```
LSP[gopls][Log] Loading packages...
LSP[gopls][Info] Error loading packages: failed to get workspace configuration f
rom client (file:///home/john/src/gocode/src/github.com/the42/cartconvert/cartco
nvert): MethodNotFound
LSP[gopls] Error loading workspace folders (expected 1, got 0)
failed to load view for file:///home/john/src/gocode/src/github.com/the42/cartco
nvert/cartconvert: failed to get workspace configuration from client (file:///ho
me/john/src/gocode/src/github.com/the42/cartconvert/cartconvert): MethodNotFound
```

### Additional info

LSP Setup in `init.vim`:

```
"" LSP
call minpac#add('neovim/nvim-lsp')
packadd nvim-lsp
call minpac#add('neovim/nvim-lspconfig')
packadd nvim-lspconfig

" LSP configuration
lua << EOF
  local lspconfig = require'lspconfig'

  local on_attach = function(_, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')

    -- Mappings
    local opts = { noremap=true, silent=true }
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
    -- vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>e', '<cmd>lua vim.lsp.util.show_line_diagnostics()<CR>', opts)
  end

  local servers = {'gopls', 'jsonls', 'yamlls'}
  for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup {
      on_attach = on_attach,
    }
  end
EOF

augroup LSP | au!
  autocmd BufWritePre *.json,*.yaml lua vim.lsp.buf.formatting_sync(nil, 1000)
augroup END

let g:lsp_diagnostics_enabled = 1

" show diagnostic signs
let g:lsp_signs_enabled = 1
let g:lsp_signs_error = {'text': '✗'}
let g:lsp_signs_warning = {'text': '!'}
let g:lsp_highlights_enabled = 0

" Do not use virtual text, they are far too obtrusive.
let g:lsp_virtual_text_enabled = 0
" echo a diagnostic message at cursor position
let g:lsp_diagnostics_echo_cursor = 0
" show diagnostic in floating window
let g:lsp_diagnostics_float_cursor = 1
" whether to enable highlight a symbol and its references
let g:lsp_highlight_references_enabled = 1
let g:lsp_preview_max_width = 80


```

**Comment by alexaandru** [comment]
I got here to report the same bug. FWIW, my term is `Kitty`.

**Comment by lithammer** [comment]
Probably related to https://github.com/neovim/neovim/issues/12617 (PR available at https://github.com/neovim/neovim/pull/12638).

**Comment by tkinz27** [comment]
Also running into this issue. Feels like it should be supported based on https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/configs.lua#L54 however I am not really well versed in LSP or the neovim implementation

**Comment by samisagit** [comment]
I had this working fine on one machine, but not another. After a lot of poking around and checking versions I ended up recompiling neovim to get the most recent build (the machine I had working had a slightly later release). This fixed the issue for me, since recompiling, everything seems to work as expected.

**Comment by tkinz27** [comment]
Things are also working for me too with a more recent version of neovim nightly.

**Comment by the42** [comment]
Will you @tkinz27  share the commit you built your neovim or your :version? Still not working for me.

**Comment by tkinz27** [comment]
@the42  I use the ubuntu unstable ppa https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable

**Comment by arthurk** [comment]
I had the same error but it's fixed in the latest master (`NVIM v0.5.0-nightly-261-g6af64d384`)

**Comment by mjlbach** [comment]
Is this solved by https://github.com/neovim/neovim/pull/12638?

**Comment by the42** [comment]
Indeed, it's fixed, thanks for asking!
