### ISSUE TITLE
sumneko_lua install fails, asking for chmod, unzip etc.

### ISSUE THREAD

**Issue by salkin-mada** [neovim/nvim-lspconfig#419]
- `nvim --version`: NVIM v0.5.0-856-g7dfeadb0f
- nvim-lsp version(commit hash): recent as of "now".
- `:checkhealth` result: OK
- What language server: sumneko_lua
- Operating system/version: Arch Linux 5.9.1-rt20-1-rt
- Terminal name/version: alacritty 0.5.0 (a6681e3a)
- `$TERM`: alacritty

So this worked without any problems until today when I updated lspconfig.
using `packer.nvim`
```

	-- nvim lsp
	use {
		'neovim/nvim-lspconfig',
		opt = true,
		ft = {
			"vim",
			"sh",
			"zsh",
			"lua",
			"cpp",
			"rust",
			"html",
			"json",
			"yaml",
			"arduino",
			"cpp",
			"c"
		},
		config = function ()
			-- local lsp = require'nvim_lsp' -- changed name to lspconfig
			local lsp = require'lspconfig'
			vim.cmd [[packadd nvim-lspconfig]]

			vim.cmd("LspInstall sumneko_lua")
			lsp.sumneko_lua.setup{
				on_attach=require'completion'.on_attach,
				settings = {
					Lua = {
						diagnostics = {
							globals = {
								"vim",
								"use"
							}

						}
					}
				}
			}
		end
	}

```

### How to reproduce the problem from neovim startup
`:LspInstall sumneko_lua`
give me:
![scrn-2020-11-22-16-22-40](https://user-images.githubusercontent.com/12082586/99908057-92ac6480-2ce0-11eb-9081-67598e752207.png)
![scrn-2020-11-22-16-25-41](https://user-images.githubusercontent.com/12082586/99908058-94762800-2ce0-11eb-8b56-b4c144c3c94d.png)

### Actual behaviour
cant install sumneko_lua

### Expected behaviour
install sumneko_lua

**Comment by saadparwaiz1** [comment]
I don't use packer.nvim so I might be wrong but shouldn't  `vim.cmd [[packadd nvim-lspconfig]]` be before `local lsp = require'lspconfig'`

**Comment by salkin-mada** [comment]
@saadparwaiz1 hmm not needed. I am still doing:
```
			local lsp = require'lspconfig'
			vim.cmd [[packadd nvim-lspconfig]]
```
and as of the last 10 days all is good again. not sure what happened. maybe packer compile lazy loader issue, maybe some short term neovim nightly issue. i am really not sure. i basically did nothing, didn't change my plugins.lua file, i just updated nvim and the issue is now gone :)

yippi
