### ISSUE TITLE
Does sumneko_lua really need clang to compile?

### ISSUE THREAD

**Issue by dlukes** [neovim/nvim-lspconfig#421]
The `sumneko_lua` install recipe requires `clang`:

https://github.com/neovim/nvim-lspconfig/blob/4f19567fb76438d39ed196ae5b4e06b749e75e16/lua/lspconfig/sumneko_lua.lua#L42-L43

However, I noticed during one of my recent installs that GCC was actually being used for compilation, and when I tried on another machine without `clang` and just commented out the check above to bypass it, everything seems to be working fine (as in, the same).

**Comment by mjlbach** [comment]
Closed by #498
