### ISSUE TITLE
rust-analyzer fails when saving the buffer

### ISSUE THREAD

**Issue by EmilSodergren** [neovim/nvim-lspconfig#423]
- `nvim --version`:  v0.5.0-866-g2d36b62ed-dirty
- nvim-lsp version(commit hash): 4f19567fb76438d39ed196ae5b4e06b749e75e16
- `:checkhealth` result All well except for optional providers
- What language server(If the problem is related to a specific language server): rust-analyzer
- Operating system/version: WSL2 Debian 10, on Windows 10
- Terminal name/version: WSL Terminal
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

Using following minimal vimrc:

> call plug#begin(expand('~/.vim/plugged'))
>   if has('nvim')
>       Plug 'neovim/nvim-lspconfig'
>   end
>   call plug#end()
>   
>   lua <<EOF
>   local lspconfig = require'lspconfig';
>   lspconfig.rust_analyzer.setup{}
>   EOF
>   
>   nnoremap <silent> K <cmd>lua vim.lsp.buf.hover()<CR>

- Open an .rs file. 
- Verify that LSP works by e.g. calling `<cmd>lua vim.lsp.buf.hover()` on a char. "char" shows up after a while. 
- Save the buffer `:w`.
- call hover again. Get following error: `E5108: Error executing lua /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:302: RPC[Error] code_name = MethodNotFound, message = "method textDocument/hover is not supported by any of the servers registered for the current buffer"`
- Reload the buffer with `:e`. Everything starts to work again after ~10 seconds, until the next buffer save.

### Actual behaviour
rust-analyzer breaks when saving

### Expected behaviour
rust-analyzer will continue to work even after I save the buffer

**Comment by lithammer** [comment]
I can reproduce, and rust-analyzer is crashing. See related upstream issue: https://github.com/rust-analyzer/rust-analyzer/issues/6603

You can quickly get it working again by rolling back to a previous version (e.g. [2020-11-16](https://github.com/rust-analyzer/rust-analyzer/releases/2020-11-16)).

**Comment by lithammer** [comment]
Also, see https://github.com/neovim/neovim/pull/13362 and https://github.com/neovim/neovim/pull/13363.

**Comment by poliorcetics** [comment]
This has been fixed (at least for me) using the most recent `HEAD` of `rust-analyzer`, is it working for you @EmilSodergren ?

**Comment by EmilSodergren** [comment]
@poliorcetics Yes, it works now. Great! Just a bad time to rebuild rust-analyzer I guess :)
