### ISSUE TITLE
Exception thrown when running "lsp.buf.declaration()" in an unsaved file

### ISSUE THREAD

**Issue by TyOverby** [neovim/nvim-lspconfig#426]
- `nvim --version`: NVIM v0.5.0-dev
- nvim-lsp version(commit hash): 936bbd1
- `:checkhealth` result: all ok
- What language server: ocamllsp
- Operating system/version: WSL
- Terminal name/version: windows terminal
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup
1. Open ocaml file
2. Edit the file (it can be any edit, the file must not be saved though)
3. execute `lua vim.lsp.buf.declaration()` on any symbol

A minimal vimrc can be found here: https://github.com/TyOverby/nvim/blob/minimal/init.vim

### Actual behaviour
This error is printed to the console:

```
/usr/share/nvim/runtime/lua/vim/lsp/util.lua:606: Failed to switch to buffer 3
```

Because of the weird "file must be dirty" behavior, I don't expect that this is an "ocamllsp" issue, though I don't have any other lsp servers set up, I haven't checked it out for other languages.

### Expected behaviour
I should have gone to the definition of the

**Comment by mjlbach** [comment]
I'm not able to reproduce this, vim.lsp.buf.declaration() works fine for me in unsaved and unsaved buffers without the error, and I've never encountered this error of the files.

Can you provide a repository, opam, and ocaml-lsp version that consistently reproduces the issue?

**Comment by mjlbach** [comment]
I've tried a couple times since, and haven't been able to reproduce this. Feel free to reopen if you can find a repro!

**Comment by zindel** [comment]
I was able to reproduce the problem, but I don't think it's an lsp issue per se. The problem happens when `set hidden` is not set and file is not saved. I.e. buffer needs to be changed, but cannot be because of unsaved state.

The related question btw, is it possible to make `vim.lsp.buf.declaration()` open the vertical split instead?

**Comment by mjlbach** [comment]
Ah, maybe we should document that you should enable `:set hidden` somewhere.

Usage questions should go on the discourse, but if you want to change the behavior of declaration you'll have to override it to point to a custom location handler (https://github.com/mjlbach/neovim/blob/3b01dd418383452ac18df58a34938c48e7492559/runtime/lua/vim/lsp/handlers.lua#L298)
