### ISSUE TITLE
pyright.lua minor setting issue

### ISSUE THREAD

**Issue by nialov** [neovim/nvim-lspconfig#430]
- `nvim --version`: NVIM v0.5.0-ea3aaa0
- nvim-lsp version(commit hash): 09fc9449e88b8a4f97d14e87af3685a48df2137f
- What language server(If the problem is related to a specific language server): pyright

### Description of the problem

Current [pyright.lua](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/pyright.lua) has settings as such:

~~~lua
settings = {
      analysis = { autoSearchPaths= true; };
      pyright = { useLibraryCodeForTypes = true; };
~~~

*analysis* should be wrapped in another parent table *python* as described here:

* https://github.com/microsoft/pyright/blob/master/docs/settings.md

E.g. in my personal init.lua

~~~lua
settings = {python = {analysis = {autoImportCompletions = false}}}
~~~

I could not get autoImportCompletions settings to work using the default way but configuring like above works for me.

**Comment by lithammer** [comment]
Fix: https://github.com/neovim/nvim-lspconfig/pull/432
