### ISSUE TITLE
advice for a basic good documentation.

### ISSUE THREAD

**Issue by JulesC2020** [neovim/nvim-lspconfig#436]
Hello,

May I just suggest to stay focus and test your documentation before committing it, please?

```
Install

    Requires Nvim HEAD/nightly (v0.5 prerelease).
    nvim-lspconfig is just a plugin. Install it like any other Vim plugin, e.g. with vim-plug:

    :Plug 'neovim/nvim-lspconfig'

    Call :packadd nvim-lspconfig in your vimrc if you installed nvim-lspconfig to 'packpath' or if you use a package manager such as minpac.

```

Don't mix vim-plug and built-in command and other application, please. 
What's the point to mention vimrc? Note that I do know I should not execute both but  anyway, I heard neovim team is building its own lsp client thus, I did expect that it was only neovim related.  

So, let me just suggest something like:

```
#INSTALL
Requires NVIM HEAD/nightly  (v0.5 prerelease).
nvim-lspconfig is a plugin. We suggest to you to install it  with eg: vim-plug.

To do so, open your $HOME/.config/nvim/init.vim and  add the following line
:Plug 'neovim/nvim-lspconfig'
save the file
:w
then initiate the installation
:PlugInstall

For VIM installation refer to section Misc.

#USAGE
To install a lsp module, just do the following:
eg:
:LspInstall vimls
```

To the point, no ambiguity, save time and hairs.

Stay focus, only mention things related to neovim with full path. Keep non-vim in an appendix/misc section.

Please excuse the tone but I just came back to neovim and even from the official documentation, plugins is still a pain to set up. Some still refer to .local/share/nvim/site/blabla... :/

**Comment by kuator** [comment]
Don't want to sound patronizing, but the project is open-source. "Be the change that you wish to see in the world." - some indian dude.

**Comment by JulesC2020** [comment]
Not sure to get it @kuator 
Do you mean, by sending a patch?  For the description, really? :)

**Comment by kuator** [comment]
Yes

**Comment by mjlbach** [comment]
I think describing how to use vim-plug (and generally a lengthy discussion of how to install plugins) is out of scope for this repository. This is unlikely to be a user's first plugin.

**Comment by mjlbach** [comment]
I'm closing this since I've redone some of the documentation, and half of this particular issue pertained to LspInstall which will be removed soon, and the other half is about providing documentation for vim-plug specific commands, which I believe it out of scope of the project. If you're using a plugin with a package manager, you should know what the respective installation command is.  And since there are always going to be n+1 package managers,  we shouldn't provide the commands for each of them.
