### ISSUE TITLE
Error with vim.lsp.diagnostic.set_loclist() on InsertLeave - gopls

### ISSUE THREAD

**Issue by ChrisAmelia** [neovim/nvim-lspconfig#442]
- `nvim --version`: `NVIM v0.5.0-31787a9`
- nvim-lsp version(commit hash): 76f11625481eddb7b
- What language server(If the problem is related to a specific language server): `gopls`
- Operating system/version: Ubuntu 18.04
- Terminal name/version: Kitty
- `$TERM`: `xterm-kitty`

### How to reproduce the problem from neovim startup

**init.vim**
```vim
set runtimepath^=~/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig

augroup UPDATE_DIAGNOSTICS_LOCLIST
	autocmd!
	autocmd InsertLeave * lua vim.lsp.diagnostic.set_loclist({open_loclist = false})
augroup END

lua << EOF

require'lspconfig'.gopls.setup{
	cmd = {"gopls", "serve"},
	settings = {
		gopls = {
			analyses = {
				unusedparams = true,
			},
			staticcheck = true,
		},
	},
}
EOF
```

**main.go**
```go
package main

func main() {

	for {
}
```

1. Open `main.go`.
1. Go into insert mode then get back to normal mode, the following error is then triggered:

```text
Error detected while processing InsertLeave Autocommands for "*":
E5108: Error executing lua ...t_nvimci4S1X/usr/share/nvim/runtime/lua/vim/lsp/util.lua:1357: Index out of bounds
```

**Comment by mhartington** [comment]
How is this related to nvim-lspconfig? That error indicates there could be an issue with nvim itself.  nvim-lspconfig just provides the setup for **starting** an lsp for a given file type.
