### ISSUE TITLE
Can't get intelephense (php) to work

### ISSUE THREAD

**Issue by pricheal** [neovim/nvim-lspconfig#445]
- `nvim --version`: `NVIM v0.5.0-dev+918-g4383c0f95`
- nvim-lsp version(commit hash): `76f1162`
- `:checkhealth` result: https://pastebin.pl/view/raw/5bec974c
- What language server(If the problem is related to a specific language server): `intelephense`
- Operating system/version: Arch linux
- Terminal name/version: Alacritty
- `$TERM`: `xterm-256color`

First thing I tried doing to get php intelephense language server setup was run `:LspInstall intelephense`. This gave me the following error:

```
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "intelephense" under a package
npm ERR! also called "intelephense". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR!
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pat/.npm/_logs/2020-12-08T00_05_26_708Z-debug.log
Installation of intelephense failed
```

So I ran `:LspInstallInfo` and got the following:

```
{
  intelephense = {
    bin_dir = "/home/pat/.cache/nvim/lspconfig/intelephense/node_modules/.bin",
    binaries = {
      intelephense = "/home/pat/.cache/nvim/lspconfig/intelephense/node_modules/.bin/intelephense"
    },
    install_dir = "/home/pat/.cache/nvim/lspconfig/intelephense",
    is_installed = false
  }
}
```

So I checked out `/home/pat/.cache/nvim/lspconfig/intelephense`, and I found a single `package.json` (nothing else in the directory), and the name of the package in package.json was `intelephense`. Since the error said it couldn't install `intelephense` under a package with the name `intelephense`, I renamed it to something random and retried -- this seemed to fix the installation problem. Installing manually also worked fine for me, but I still have the following issue.

I can't get any language server features from intelephense whatsoever. I am using the default intelephense config that is provided, I am opening a php file that is in a directory with a composer.json and a .git, I have other language servers working totally fine. If I run `:lua print(vim.inspect(vim.lsp.buf_get_clients()))` while I have the php buffer open, I only get `{}` instead of all the language server info. I checked out the lsp logs (from `:lua print(vim.lsp.get_log_path())`) and I can see that SOMETHING is happening with intelephense at least. I get a gigantic log from intelephense, many lines that are all over 40,000 columns (it seems like its outputting the source code or something, its javascript code). But at the very end, I see the following error:

```
[Error]: MethodNotFound
at /home/pat/.cache/nvim/lspconfig/intelephense/node_modules/intelephense/lib/intelephense.js:3:168725
at /home/pat/.cache/nvim/lspconfig/intelephense/node_modules/intelephense/lib/intelephense.js:3:169019
at Immediate.<anonymous> (/home/pat/.cache/nvim/lspconfig/intelephense/node_modules/intelephense/lib/intelephense.js:3:169378)
at processImmediate (node:internal/timers:463:21) {
    code: -32601,
    data: undefined
}
```

Like I said, I was able to actually get intelephense installed fine manually (it seems like `:LspInstall intelephense` might be broken though?), but my main issue is that the server seems to be crashing on initialization for some reason. Does anyone know why this might be happening? Is there anyone that has gotten intelephense to work totally fine? Thanks for any help.

**Comment by pricheal** [comment]
Finally found out what my issue was, it seems like intelephense itself wasn't working with my version of node (15).

**Comment by TC72** [comment]
Hi,
I'm running into exactly the same error, what did you do to fix it?

**Comment by pricheal** [comment]
> Hi,
> I'm running into exactly the same error, what did you do to fix it?

I used nvm (node version manager) to change my system node (which was v15) to v12 instead, which resolved the issue for me.

**Comment by TC72** [comment]
I reply here in case it helps anyone else.
As I'm running this on an M1 Mac Mini I can't easily install v12.
I guess a fix for intelephense on V15 wouldn't be a bad idea.

Also @pricheal thanks for the email exchange to help me with this.
