### ISSUE TITLE
sumneko_lua takes 35-40 seconds to load

### ISSUE THREAD

**Issue by sidmadala** [neovim/nvim-lspconfig#446]
- `nvim --version`: NVIM v0.5.0-dev+4383c0f
- nvim-lsp version(commit hash): 76f11625481eddb7bcbf86b3e4f592a1aef35b37
- `:checkhealth` result: All green
- What language server (If the problem is related to a specific language server): sumneko_lua
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Alacritty 0.6.0
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

I installed lspconfig using packer.nvim with nvim-completions as a dependency. I installed sumneko_lua using `:LspInstall sumneko_lua` within Neovim. I have pasted my configuration for packer.nvim and nvim-lspconfig below.  I don't know if this is a problem only related to myself.

<details>
<summary>plugins.lua</summary>

```lua
--[[
Packer plugin configuration
--]]

-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]

require("packer").startup(function()

	-- Essential
	use {"wbthomason/packer.nvim", opt = true}		-- Packer can manage itself as an optional plugin
	use {"svermeulen/vimpeccable"}

	-- Aesthetic
	use {"jnurmine/zenburn", config = require("plugins.colorscheme")}
	use {"itchyny/lightline.vim", config = require("plugins.lightline")}
	use {"Yggdroot/indentLine", config = require("plugins.indentline")}
	use {"junegunn/goyo.vim", config = require("plugins.goyo")}
	use {"kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons", config = require("plugins.tree")}

	-- LSP
	use {"neovim/nvim-lspconfig", requires = "nvim-lua/completion-nvim", config = require("plugins.lsp_config")}
	use {"nvim-treesitter/nvim-treesitter", config = require("plugins.treesitter")}
	use {"liuchengxu/vista.vim", config = require("plugins.vista")}
	use {"rust-lang/rust.vim"}

	-- Utilities
	use {"tpope/vim-commentary"}
	use {"jiangmiao/auto-pairs"}
	use {"junegunn/fzf.vim", requires = "junegunn/fzf", config = require("plugins.fzf")}
	use {"junegunn/vim-easy-align"}
	use {"lervag/vimtex", config = require("plugins.vimtex")}
	use {"tpope/vim-fugitive", config = require("plugins.fugitive")}
	use {"christoomey/vim-tmux-navigator"}
end)
```
</details>

<details>
<summary>lsp_config.lua</summary>

```lua
-- LSP for neovim

if not pcall(require, 'vimp') then
  vim.cmd [[ echom 'Cannot load `vimp`' ]]
end

-- Imports
local lspconfig = require("lspconfig")
local completion = require("completion")
local diagnostic = require("vim.lsp.diagnostic")

-- Functions

local custom_attach = function()

	-- Attaching completion and diagnostics for buffer
	completion.on_attach()

	print("LSP Attached")
end


-- LSP Servers

-- Lua
lspconfig.sumneko_lua.setup{
	on_attach = custom_attach

	-- settings = {
	-- 	Lua = {
	-- 		runtime = { version = "LuaJIT", path = vim.split(package.path, ';'), },
	-- 		completion = { keywordSnippet = "Disable", },
	-- 		diagnostics = { enable = true, globals = {
	-- 			"vim", "describe", "it", "before_each", "after_each" },
	-- 		},
	-- 		workspace = {
	-- 			library = {
	-- 				[vim.fn.expand("$VIMRUNTIME/lua")] = true,
	-- 				[vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
	-- 			}
	-- 		}
	-- 	}
	-- }
}

-- Python
lspconfig.pyls.setup{
	on_attach = custom_attach
}

-- Golang
lspconfig.gopls.setup{
	on_attach = custom_attach
}

-- Rust
lspconfig.rust_analyzer.setup{
	on_attach = custom_attach
}

-- Latex
lspconfig.texlab.setup{
	on_attach = custom_attach
}

-- Settings

-- Diagnostic

-- Completion
vim.cmd [[ inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>" ]]	-- Use <Tab> to navigate down popup menu
vim.cmd [[ inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>" ]]	-- Use <S-Tab> to navigate up popup menu
-- let g:completion_enable_auto_paren = 1								-- Complete parentheses for functions
-- vim.opt.completeopt = { "menuone" , "noinsert", "noselect" }				-- Set completeopt to have a better completion experience
vim.cmd [[ set completeopt=menuone,noinsert,noselect ]]
vim.cmd [[ set shortmess+=c ]]										-- Avoid showing message extra message when using completion
```
</details>

### Actual behaviour

Sumneko_lua warnings and autocomplete take between 35-40 seconds to appear when initially opening a file (specifically when opening files related to neovim configuration). On other Lua files it fluctuates between loading relatively quickly and extremely slowly. Other LSPs I use (i.e. gopls, rust-analyzer, texlab) only take around 1-5 seconds to load.

### Expected behaviour

Sumneko_lua should take a constant sub 1-second loading time like it did on an older Neovim 0.5 and nvim-lsp commit I had until recently.

**Comment by lithammer** [comment]
It probably depends on what root directory (`root_dir`) it picks. This is the default:

https://github.com/neovim/nvim-lspconfig/blob/76f11625481eddb7bcbf86b3e4f592a1aef35b37/lua/lspconfig/sumneko_lua.lua#L97-L99

Which means, unless you're in a git repository it will use your home directory. So it will basically scan your home folder for Lua files. Personally I changed it to use the buffer directory as fallback instead of home to prevent this:

```lua
    root_dir = function(fname)
      return util.find_git_ancestor(fname) or
        util.path.dirname(fname)
    end
```

**Comment by sidmadala** [comment]
This solved it perfectly. Thank you for the assistance.

**Comment by lithammer** [comment]
See https://github.com/neovim/nvim-lspconfig/pull/450 for changing the default value.

**Comment by monopoly-db** [comment]
> This solved it perfectly. Thank you for the assistance.
> 
> For anyone's future reference, add this line to the top of your lsp_config.lua to get utils.
> 
> `utils = require("lspconfig.utils")`

util = require("lspconfig.util")

This is what worked for me.
