### ISSUE TITLE
Question on sumneko_lua configuration

### ISSUE THREAD

**Issue by sidmadala** [neovim/nvim-lspconfig#447]
More of a question than a bug, therefore I did not label it as such. I was wondering where I am going wrong in configuring sumneko_lua to recognize Neovim objects and autocomplete with its API.

- `nvim --version`: NVIM v0.5.0-dev+4383c0f
- nvim-lsp version(commit hash): 76f11625481eddb7bcbf86b3e4f592a1aef35b37
- `:checkhealth` result: All green
- What language server (If the problem is related to a specific language server): sumneko_lua
- Operating system/version: MacOS Catalina 10.15.4
- Terminal name/version: Alacritty 0.6.0
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

I installed nvim-lspconfig using packer.nvim with nvim-completions as a dependency. I installed sumneko_lua using `:LspInstall sumneko_lua` within Neovim. I have pasted my configuration for packer.nvim and nvim-lspconfig below.

<details>
<summary>plugins.lua</summary>

```lua
--[[
Packer plugin configuration
--]]

-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

vim.cmd [[ autocmd BufWritePost plugins.lua PackerCompile ]]

require("packer").startup(function()

	-- Essential
	use {"wbthomason/packer.nvim", opt = true}		-- Packer can manage itself as an optional plugin
	use {"svermeulen/vimpeccable"}

	-- Aesthetic
	use {"jnurmine/zenburn", config = require("plugins.colorscheme")}
	use {"itchyny/lightline.vim", config = require("plugins.lightline")}
	use {"Yggdroot/indentLine", config = require("plugins.indentline")}
	use {"junegunn/goyo.vim", config = require("plugins.goyo")}
	use {"kyazdani42/nvim-tree.lua", requires = "kyazdani42/nvim-web-devicons", config = require("plugins.tree")}

	-- LSP
	use {"neovim/nvim-lspconfig", requires = "nvim-lua/completion-nvim", config = require("plugins.lsp_config")}
	use {"nvim-treesitter/nvim-treesitter", config = require("plugins.treesitter")}
	use {"liuchengxu/vista.vim", config = require("plugins.vista")}
	use {"rust-lang/rust.vim"}

	-- Utilities
	use {"tpope/vim-commentary"}
	use {"jiangmiao/auto-pairs"}
	use {"junegunn/fzf.vim", requires = "junegunn/fzf", config = require("plugins.fzf")}
	use {"junegunn/vim-easy-align"}
	use {"lervag/vimtex", config = require("plugins.vimtex")}
	use {"tpope/vim-fugitive", config = require("plugins.fugitive")}
	use {"christoomey/vim-tmux-navigator"}
end)
```
</details>

<details>
<summary>lsp_config.lua</summary>

```lua
-- LSP for neovim

if not pcall(require, 'vimp') then
  vim.cmd [[ echom 'Cannot load `vimp`' ]]
end

-- Imports
local lspconfig = require("lspconfig")
local completion = require("completion")
local diagnostic = require("vim.lsp.diagnostic")

-- Functions

local custom_attach = function()

	-- Attaching completion and diagnostics for buffer
	completion.on_attach()

	print("LSP Attached")
end


-- LSP Servers

-- Lua
lspconfig.sumneko_lua.setup{
	on_attach = custom_attach

	settings = {
		Lua = {
			runtime = { version = "LuaJIT", path = vim.split(package.path, ';'), },
			completion = { keywordSnippet = "Disable", },
			diagnostics = { enable = true, globals = {
				"vim", "describe", "it", "before_each", "after_each" },
			},
			workspace = {
				library = {
					[vim.fn.expand("$VIMRUNTIME/lua")] = true,
					[vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
				}
			}
		}
	}
}


-- Completion
vim.cmd [[ inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>" ]]	-- Use <Tab> to navigate down popup menu
vim.cmd [[ inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>" ]]	-- Use <S-Tab> to navigate up popup menu
-- let g:completion_enable_auto_paren = 1								-- Complete parentheses for functions
-- vim.opt.completeopt = { "menuone" , "noinsert", "noselect" }				-- Set completeopt to have a better completion experience
vim.cmd [[ set completeopt=menuone,noinsert,noselect ]]
vim.cmd [[ set shortmess+=c ]]										-- Avoid showing message extra message when using completion
```
</details>

### Actual behaviour

I get the following error when entering any file.

`
E5113: Error while calling lua chunk: ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:417: /Users/sidmadala/.config/nvim/lua/plugins.lu
a:24: module 'plugins.lsp_config' not found:
        no field package.preload['plugins.lsp_config']
        no file './plugins/lsp_config.lua'
        no file '/usr/local/Cellar/luajit/2.0.5/share/luajit-2.0.5/plugins/lsp_config.lua'
        no file '/usr/local/share/lua/5.1/plugins/lsp_config.lua'
        no file '/usr/local/share/lua/5.1/plugins/lsp_config/init.lua'
        no file '/usr/local/Cellar/luajit/2.0.5/share/lua/5.1/plugins/lsp_config.lua'
        no file '/usr/local/Cellar/luajit/2.0.5/share/lua/5.1/plugins/lsp_config/init.lua'
        no file './plugins/lsp_config.so'
        no file '/usr/local/lib/lua/5.1/plugins/lsp_config.so'
        no file '/usr/local/Cellar/luajit/2.0.5/lib/lua/5.1/plugins/lsp_config.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './plugins.so'
        no file '/usr/local/lib/lua/5.1/plugins.so'
        no file '/usr/local/Cellar/luajit/2.0.5/lib/lua/5.1/plugins.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
`

### Expected behaviour

Sumneko_lua should be able to recognize Neovim objects and provide completion and diagnostics based on its API.

**Comment by sidmadala** [comment]
Fixed after referring to #446 and #412.

**Comment by EduardoBorsa** [comment]
Hey @sidmadala.

My language server still did not recognize the vim object inside any lua file after the instalation of the sumneko_lua language server.

My config for the lspconfig is:
```
lsp_installer.on_server_ready(function(server)
  local opts = {}
  if server.name == "sumneko_lua" then
    opts = {
      settings = {
        Lua = {
          diagnostics = {
            globals = { 'vim', 'use' }
          },
          runtime = {
            -- Tell the language server which version of Lua you're using (most likely LuaJIT in the case of Neovim)
            version = 'LuaJIT',
            -- Setup your lua path
            path = runtime_path,
          },
          -- Do not send telemetry data containing a randomized but unique identifier
          telemetry = {
            enable = false,
          },
          workspace = {
            library = {
              -- Make the server aware of Neovim runtime files
              library = vim.api.nvim_get_runtime_file("", true),
            },
        },
        }
      }
    }
  end
  server:setup(opts)
end)
```
and :lua print(vim.api.nvim_get_runtime_file("", true))
returns an object: table: 0x41943ba0

Any other config that I might be missing?

**Comment by clason** [comment]
The issue tracker is not for usage questions; please ask your question on https://neovim.discourse.group.
