### ISSUE TITLE
[question] auto install lsp servers

### ISSUE THREAD

**Issue by alex-popov-tech** [neovim/nvim-lspconfig#448]
Basically its a question - can i use `nvim-lspconfig` in the same matter i used coc-nvim
```
let g:coc_global_extensions = ['coc-json', 'coc-git', 'coc-tsserver']
```
which means that on start these will be installed, so i should not call manually `LspInstall {servername}` for each server

**Comment by lithammer** [comment]
Not at the moment. And possible never since there's talk about removing the installation capabilities completely, see https://github.com/neovim/nvim-lspconfig/issues/334.

**Comment by alex-popov-tech** [comment]
thanks @lithammer , i will subscribe there, and hope that something instead would be introduced as an entrypoint for installing lsp servers
