### ISSUE TITLE
LspInstallInfo always return empty eventhough I've installed some LSP

### ISSUE THREAD

**Issue by sheldonldev** [neovim/nvim-lspconfig#452]
- `nvim --version`: 0.5.0 nightly
- nvim-lsp version(commit hash):   latest nvim-lspconfig, and completion-nvim
- `:checkhealth` result

health#defx#check
=======================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#lspconfig#check
========================================================================
## Checking language server protocol configuration

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion source are valid

## snippet source
  - INFO: You haven't setup any snippet source.

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=0).

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /opt/anaconda3/bin/python3
  - INFO: Python version: 3.9.0
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v15.4.0
  - INFO: Nvim node.js host: /Users/sheldonl/.config/yarn/global//node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - Perl version is too old, 5.22+ required

- What language server(If the problem is related to a specific language server):  tsserver, cssls

- Operating system/version: macOS catalina 10.15.7

- Terminal name/version: iTerm2
- `$TERM`: zsh

### How to reproduce the problem from neovim startup
run `:LspInstall cssls` or `yarn global add cssls`
call `:LspInstallInfo` 
It shows: 
{
  cssls = {
    bin_dir = "/Users/sheldonl/.cache/nvim/lspconfig/cssls/node_modules/.bin",
    binaries = {
      ["css-languageserver"] = "/Users/sheldonl/.cache/nvim/lspconfig/cssls/node_modules/.bin/css-languageserver"
    },
    install_dir = "/Users/sheldonl/.cache/nvim/lspconfig/cssls",
    is_installed = true
  }
}

### Actual behaviour
But, when I leave and restart nvim, run `:LspInstallInfo`, it returns
{},
And, no lint, no completion is available

### Expected behaviour
When I leave and restart nvim, run `:LspInstallInfo`, it should returns
{
  cssls = {
    bin_dir = "/Users/sheldonl/.cache/nvim/lspconfig/cssls/node_modules/.bin",
    binaries = {
      ["css-languageserver"] = "/Users/sheldonl/.cache/nvim/lspconfig/cssls/node_modules/.bin/css-languageserver"
    },
    install_dir = "/Users/sheldonl/.cache/nvim/lspconfig/cssls",
    is_installed = true
  }
}
either.
And , lint and completion should available

**Comment by jerrywang1981** [comment]
it looked like cssls was not installed. if installed, when `checkhealth`
it would be shown in `health#lspconfig#check` section
did you verify it in `~/.cache/nvim/lspconfig/cssls` ?

**Comment by sheldonldev** [comment]
yes, I'm sure  

 ~/.cache/nvim/lspconfig/cssls  ls -l
total 8
drwxr-xr-x  13 sheldonl  staff  416 Dec 11 16:37 node_modules
-rw-r--r--   1 sheldonl  staff  219 Dec 11 16:37 package.json

**Comment by sheldonldev** [comment]
and run :LspInstallInfo
{}

**Comment by jerrywang1981** [comment]
https://github.com/neovim/nvim-lspconfig#cssls

did you set it up?
```
require'lspconfig'.cssls.setup{}
```

**Comment by benawas** [comment]
I don't know if this problem is the same as yours. I upgraded nodejs version 14 to 15 on windows and get {} message. I rolling back to nodejs 14 and its working fine.

**Comment by sheldonldev** [comment]
yes, I think I'v set everything like the documentation.

Well, maybe it's the node version, because I use version 15 right now. I will try to roll back later

**Comment by sheldonldev** [comment]
yes, I think I'v set everything like the documentation.

Well, maybe it's the node version, because I use version 15 right now. I will try to roll back later. Thank you @benawas

**Comment by mjlbach** [comment]
@sheldonldev Did you try rolling back node? Is this still an issue?

**Comment by sheldonldev** [comment]
@mjlbach not yet, I'll try it this Sunday or Monday

**Comment by sheldonldev** [comment]
This time I uninstall my node 15.4, it seems no problem.

run checkhealth:
```bash
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: cssls: configuration checked.

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion source are valid

## snippet source
  - INFO: You haven't setup any snippet source.
## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.
```

run  `LspInstallInfo`:
```bash
{
  cssls = {
    bin_dir = "/Users/sheldonl/.cache/nvim/lspconfig/cssls/node_modules/.bin",
    binaries = {
      ["css-languageserver"] = "/Users/sheldonl/.cache/nvim/lspconfig/cssls/node_modules/.bin/css-languageserver"
    },
    install_dir = "/Users/sheldonl/.cache/nvim/lspconfig/cssls",
    is_installed = true
  },
  tsserver = {
    bin_dir = "/Users/sheldonl/.cache/nvim/lspconfig/tsserver/node_modules/.bin",
    binaries = {
      ["typescript-language-server"] = "/Users/sheldonl/.cache/nvim/lspconfig/tsserver/node_modules/.bin/typescript-language-server"
    },
    install_dir = "/Users/sheldonl/.cache/nvim/lspconfig/tsserver",
    is_installed = true
  }
}
```

**Comment by mjlbach** [comment]
It seems like a lot of language servers are affected negatively by node 15. Is your issue resolved by reverting back then, and can we close?

**Comment by sheldonldev** [comment]
I'm now using node 14 with nvm. It seems OK now. Sure we can close it. Thank you.

**Comment by mjlbach** [comment]
Thank you! If you can isolate the issue to something in particular one of the configuration scripts is doing, file another issue. Otherwise if this is an upstream issue it should be reported to the respective language server.

**Comment by sheldonldev** [comment]
Alright.  Thank you!
