### ISSUE TITLE
Make the hover popup menu persist while typing arguments into a function?

### ISSUE THREAD

**Issue by atticusmatticus** [neovim/nvim-lspconfig#458]
When I'm entering variables into a function that takes several inputs it would be nice to have the vim.lsp.buf.hover() output stay up on the screen so I can reference it as I am typing. Unfortunately the default behavior makes the hover popup window disappear once any keyboard input is entered. Is there any way to change this behavior?

If not, is this a feature you would consider adding?

Thanks

**Comment by atticusmatticus** [comment]
I have since realized that while in insert mode if you pause after typing a comma within the parentheses of a function the popup menu shows the hover help for that function. This is essentially what I was suggesting in the original comment.

**Comment by qazip** [comment]
I am trying to do what you've already done @atticusmatticus, and I am getting an headache. 

Care to share your config file please?

**Comment by atticusmatticus** [comment]
Sure thing, https://github.com/atticusmatticus/nvim

Let me know if you don't get it working.

**Comment by grimpy** [comment]
I can't seem to reproduce what @atticusmatticus is saying hover does not reopen for me, is there a setting I'm missing?

**Comment by atticusmatticus** [comment]
Not sure what it might be if my config file listed above doesn't get it working for you, @grimpy.
