### ISSUE TITLE
root_dir no longer being respected with diagnosticls

### ISSUE THREAD

**Issue by chris-burgin** [neovim/nvim-lspconfig#461]
- `nvim --version`: v0.5.0-871-ga6bd52d87
- nvim-lsp version(commit hash):
- `:checkhealth` result: Fine
- What language server(If the problem is related to a specific language server): diagnosticls
- Operating system/version: Fedora 33
- Terminal name/version: Alactritty
- `$TERM`: zsh

### How to reproduce the problem from neovim startup
Recently I have noticed that diagnosticls has stopped respecting custom `root_dir` and is instead running `eslint` from the root project directory.
```lua
nvim_lsp = require'lspconfig'
nvim_lsp.diagnosticls.setup{
	filetypes = { "javascript", "javascript.jsx", "typescript", "typescriptreact" };
	root_dir= nvim_lsp.util.root_pattern(
		"client/src/js/app",
		"client/src/tests",
	);
	init_options = {
		filetypes = {
			javascript = "eslint";
			["javascript.jsx"] = "eslint";
			javascriptreact = "eslint";
			typescriptreact = "eslint";
			typescript = "eslint";
			typescriptreact = "eslint";
		};
		linters = {
			eslint = {
				sourceName = "eslint";
				command = "eslint_d";
				rootPatterns = { ".git" };
				debounce = 100;
				args = {
					"--cache";
					"--stdin";
					"--stdin-filename";
					"%filepath";
					"--format";
					"json";
				};
				sourceName = "eslint";
				parseJson = {
					errorsRoot = "[0].messages";
					line = "line";
					column = "column";
					endLine = "endLine";
					endColumn = "endColumn";
					message = "${message} [${ruleId}]";
					security = "severity";
				};
				securities = {
					 [2] = "error";
					 [1] = "warning";
				};
			};
		};
	}
}
```
### Actual behaviour
eslint is being run from the root project directory instead of the working directories mentioned in `root_dir`.

I know that `rootPatterns` is set to `{ "git" }`, but this same config worked about a week ago.

### Expected behaviour
eslint is run from the directories listed in `root_dir` not from the root of the project.

Like I said, this config worked about a week ago. I do expect that there might be a change that I am unaware of that broke this config. 

Thanks for any help you can offer!

**Comment by mjlbach** [comment]
With your config as you have it, you need to either open neovim in `client/src/js/app` or `client/src/tests`, or `:cd` to those directories *before* opening a file in your project in order for it to do what you want .

You can play with the util.root_patten in vim's cmdline to see how it works, but it will search up the file structure until it hits the root pattern, not down.

From the root directory of your project:
```
.
├── client
│   └── src
│       ├── js
│       │   ├── app
│       │   └── main.ts
│       └── tests
└── tags
```

```lua
:lua print(require'lspconfig'.util.root_pattern("app")("./client/src/js/app"))
/Users/michael/Repositories/neovim_development/custom_project/client/src/js
```

util.root_pattern returns a function, whose only argument is the directory to search. Your function will work like so:

```lua
:cd client/src/js/app/
:lua print(require'lspconfig'.util.root_pattern("app")("."))
/Users/michael/Repositories/neovim_development/custom_project/client/src/js
```
