### ISSUE TITLE
Trouble adding Perl-LanguageServer

### ISSUE THREAD

**Issue by pretentious7** [neovim/nvim-lspconfig#478]
So, I tried adapting pyls config:
```
local configs = require 'lspconfig/configs'
local util = require 'lspconfig/util'

configs.perlls = {
  default_config = {
    cmd = {"perl",
    "-MPerl::LanguageServer",
    "-e", "Perl::LanguageServer::run","--",
    "--port 13603"};
    filetypes = {"perl"};
    root_dir = function(fname)
        return util.root_pattern(".git")(fname) or vim.loop.os_homedir()
    end;
  };
  docs = {
    package_json = "https://github.com/richterger/Perl-LanguageServer/blob/master/clients/vscode/perl/package.json";
    description = [[
https://github.com/richterger/Perl-LanguageServer/tree/master/clients/vscode/perl
`Perl-LanguageServer`, a language server for Perl.
    ]];
    default_config = {
      root_dir = "vim's starting directory";
    };
  };
};
-- vim:et ts=2 sw=2
```

and it seems to kind of work, ie.
`lua print(vim.inspect(vim.lsp.buf_get_clients())) `
shows the correct client

But, there's no highlighting or anything and for some strange reason
`lua print(vim.lsp.buf.server_ready())`
only shows true the FIRST time it's run and it's false after that.

also, how would I go about configuring custom settings for the language server? eg. from lsp-mode perl.el:
```
(lsp-register-custom-settings
 '(("perl.perlCmd" lsp-perl-perl-cmd)
   ("perl.perlInc" lsp-perl-perl-inc)
   ("perl.fileFilter" lsp-perl-file-filter)
   ("perl.ignoreDirs" lsp-perl-ignore-dirs)))
```

Even weirder, when it ostensibly claims that it's ready, I can still start another instance on port 13603 in shell. what gives?

Incidentally using netcat and connecting to 13603 doesn't seem to work properly either , but it atleast gave me an error:

```
Attribute (params) does not pass the type constraint because: Validation failed for 'HashRef' with value ARRAY(0x564c74e31ef8) at /usr/local/lib/x86_64-linux-gnu/perl/5.30.0/Moose/Object.pm line 24
	Moose::Object::new('Perl::LanguageServer::Req', 'HASH(0x564c74de12b8)') called at /usr/local/share/perl/5.30.0/Perl/LanguageServer.pm line 242
	Perl::LanguageServer::__ANON__ at /usr/local/lib/x86_64-linux-gnu/perl/5.30.0/Coro.pm line 716
	Coro::_coro_run at -e line 0
```

for which the code in question is:
```
  has 'params' =>
      (
      isa => 'HashRef',
      is  => 'ro' 
      ) ; 
```

I'm not quite sure what exactly `params` means here not too familiar with lsp, but since it seems to be working with vscode and emacs I don't quite know what's going on...

help would be much appreciated.

**Comment by mjlbach** [comment]
You might want to look at this pyright snippet 
https://github.com/neovim/nvim-lspconfig/blob/d1043a19b0e24e44972948d1ebf522c66b9caff5/lua/lspconfig/pyright.lua#L21-L27

**Comment by pretentious7** [comment]
Yo that fixed it :), I'll have a PR in tom, thankssssssssssss.
