### ISSUE TITLE
Latest rust-analyzer requires LSP spec 3.16 compatibility

### ISSUE THREAD

**Issue by Masterchef365** [neovim/nvim-lspconfig#479]
- `nvim --version`:
NVIM v0.5.0-dev+950-g5ce328df4
Build type: RelWithDebinfo
LuaJIT 2.1.0-beta3
- nvim-lsp version(commit hash): dbc4bf514198f9e328e200a9aa63b462d6e1e9f1
- `:checkhealth` result
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: rust_analyzer: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: RelWithDebinfo
  - WARNING: Non-optimized build. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.9.1
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v15.4.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed
```
- What language server(If the problem is related to a specific language server): rust-analyzer (5e2935e)
- Operating system/version: Linux 5.9.14-arch1-1
- Terminal name/version: alacritty 0.6.0 (04cbf767)
- `$TERM`:xterm-256color

### Config file
```
call plug#begin('~/.config/nvim/bundle')
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua require'lspconfig'.rust_analyzer.setup({})
```

### Behaviour
`rust-analyzer` is not launched when opening a Rust source file. Other language servers such as `clangd` work as expected.

**Comment by mjlbach** [comment]
Does your project trigger the route pattern? https://github.com/neovim/nvim-lspconfig/blob/42a13e5ad99b688bc7376fa4d236e924985d04cc/lua/lspconfig/rust_analyzer.lua#L8

Rust-analyzer won't be triggered without having one of those files in the current project directory.

**Comment by Masterchef365** [comment]
I do have `Cargo.toml` in the project's root, yes. This same setup was working before I updated - I'm not sure of the commit hash I was using before the update, however.

**Comment by mjlbach** [comment]
Can you attach a log? When you say "updated", do you mean you updated rust-analyzer? Nothing has changed on the nvim-lspconfig side recently.

**Comment by Masterchef365** [comment]
I was dumb and updated many things at once, so I changed many variables so-to-speak. I thought that nvim-lspconfig was the entrypoint for starting Neovim's LSP, so I made an issue here. Here's a log from opening up a project with the config file from the issue:
[log.txt](https://github.com/neovim/nvim-lspconfig/files/5732747/log.txt)

**Comment by mjlbach** [comment]
You need to set `vim.lsp.log.set_level("info")` to your lua heredoc in your init.vim and post the log from `~/.local/share/nvim/lsp.log`

**Comment by Masterchef365** [comment]
Sorry to be so clueless - I saw in the neovim docs that that _should_ be a function I can call, but when I try I get `E5108: Error executing lua [string ":lua"]:1: attempt to index field 'log' (a nil value)` which is just odd considering I'm using an up to date version of nvim afaict

**Comment by mjlbach** [comment]
Whoops my bad.  `vim.lsp.set_log_level("debug")`

**Comment by Masterchef365** [comment]
Hm, having looked at the log I it seems like the rust-analyzer update is what did it. Here's the full thing
[lsp.log](https://github.com/neovim/nvim-lspconfig/files/5732886/lsp.log)

**Comment by mjlbach** [comment]
See: 
https://github.com/rust-analyzer/rust-analyzer/issues/6979
https://github.com/rust-analyzer/rust-analyzer/issues/6997

**Comment by mjlbach** [comment]
Rust-analyzer has introduced in a non-backwards compatible way LSP spec 3.16 support, and fails to initialize if the client does not support all features of 3.16 (which neovim's core does not). This isn't particularly related to this repository, except in the sense that we might add a mitigation here. The real solution is adding support for the 3.16 spec, and in the meantime introducing the workaround here https://github.com/fannheyward/coc-rust-analyzer/commit/b795891573678bbb3a84aa64e553e674b20a5df6

If you don't have time to make a PR, I would recommend falling back to the previous version of rust-analyzer.

**Comment by Masterchef365** [comment]
Yep, that'd do it. Going to downgrade, thank you for your help!

**Comment by mjlbach** [comment]
I think we should keep this open, since this is a legitimate thing that needs to be addressed. I renamed the issue to reflect your debugging :)

**Comment by mjlbach** [comment]
@Masterchef365 Can you try #481? I can't test it at the moment.

**Comment by Masterchef365** [comment]
#481 works for me!

**Comment by mjlbach** [comment]
Sorry to be a bother, but can you confirm it works both on nightly and with the old rust-analyzer? don't want to break anything for anyone 😆

**Comment by Masterchef365** [comment]
No bother, got a specific commit of rust-analyzer you'd like to see tested? (The one I just tested was the more recent one that had broken, 5e2935e, since I hadn't gotten around to switching to the older version yet)

**Comment by Masterchef365** [comment]
Just tested an older version (dbd0cfb) and it failed with the following log:
[lsp.log](https://github.com/neovim/nvim-lspconfig/files/5733056/lsp.log)

**Comment by mjlbach** [comment]
That message didn't show up in the log for the newer rust-analyzer?

**Comment by Masterchef365** [comment]
Just ran `4a2f60c` again to check, nope that error is unique to `dbd0cfb`

**Comment by ludwj61** [comment]
Just chipping in to say that I have the same issue of rust-analyzer not starting with the latest nvim nightly/lspconfig. Using older versions of rust-analyzer does not seem to make a difference.

**Comment by mjlbach** [comment]
Which commit of rust-analyzer? Did you try the PR?

**Comment by ludwj61** [comment]
I tried both the latest and ``dbd0cfb``. Using the PR with the latest unfortunately doesn't seem to change anything.

**Comment by ludwj61** [comment]
Wait sorry, I somehow forgot to reinstall, the PR does fix it for me, my mistake!

**Comment by zbraniecki** [comment]
The PR from #481 fixed it for me as well!

**Comment by mjlbach** [comment]
Is the general sentiment that I should merge this? I don't know how to keep compatibility with both, I don't think there's a parseable version tag I could check for to determine which settings to send.

**Comment by lithammer** [comment]
> Is the general sentiment that I should merge this? I don't know how to keep compatibility with both, I don't think there's a parseable version tag I could check for to determine which settings to send.

If rust-analyzer isn't working at all, I think it's a good idea to merge. I suspect most people will be using the latest version (or want to).

**Comment by Th3Whit3Wolf** [comment]
@mjlbach I think the majority of the rust community keeps fairly up to date.

**Comment by mjlbach** [comment]
Ok, it's merged. This is still an issue with rust-analyzer not complying with the spec/I'm trying to cut down on the number of these work-arounds.
