### ISSUE TITLE
[newbie] cannot get changes in config/settings to take affect

### ISSUE THREAD

**Issue by yatesco** [neovim/nvim-lspconfig#483]
Hi there - it is almost certainly me, not you, but I can't figure out why :-)

I'm trying to configure `rust-analyzer` but I can't seem to get the config to apply. This is what I ended up with:

```rust
  -- Enable rust_analyzer
  nvim_lsp.rust_analyzer.setup({ 
     on_attach=on_attach;             
     settings = { 
       ["rust-analyzer"] = {           
         procMacro = { enable = true };                         
       }   
     };                                
     init_options = {                 
       procMacro = { enable = true };                          
     }
  }) 
```

but I still see:

![image](https://user-images.githubusercontent.com/181469/102991337-e9d86b80-4510-11eb-93bd-6fde04f99cbd.png)

I've read the following:
 - https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#rust_analyzer
 - https://github.com/neovim/nvim-lspconfig/issues/70 (which made me try `init_options`
 - https://rust-analyzer.github.io/manual.html
 - https://users.rust-lang.org/t/how-to-disable-rust-analyzer-proc-macro-warnings-in-neovim/53150

Help :-)

**Comment by lithammer** [comment]
As mentioned in the manual, `procMacro` requires `cargo.loadOutDirsFromCheck`:

> **rust-analyzer.procMacro.enable (default: false)**
> Enable Proc macro support, cargo.loadOutDirsFromCheck must be enabled.

```lua
settings = {
  ["rust-analyzer"] = {
    cargo = {
      loadOutDirsFromCheck = true
    },
    procMacro = {
      enable = true
    }
  }
}
```

**Comment by yatesco** [comment]
Thanks @lithammer  - yep, I missed that. It still doesn't work though:

```rust
  -- Enable rust_analyzer
  nvim_lsp.rust_analyzer.setup({
     on_attach=on_attach;
     settings = {
    ["rust-analyzer"] = {
      cargo = {
        loadOutDirsFromCheck = true
      },
      procMacro = {
        enable = true
      }
    }
  }
                 
  }) 
```

(after restart) still gives:

![image](https://user-images.githubusercontent.com/181469/102992110-83544d00-4512-11eb-8861-36bed2db88f1.png)

**Comment by yatesco** [comment]
Interestingly enough, disabling the warning works:
``` rust
  
  local settings ={
    ["rust-analyzer"] = {
      diagnostics = {
        disabled = { "unresolved-proc-macro" }
      }
    }
  } 
  
  -- Enable rust_analyzer
  nvim_lsp.rust_analyzer.setup({
     on_attach=on_attach,
     settings = settings,
                         
  })           
```

I suspect a bug somewhere else maybe...

**Comment by yatesco** [comment]
I'll close this for now because this isn't about the macro expansion per se, it is about how to apply config, which is solved. Thanks again @lithammer
