### ISSUE TITLE
Using the suggested mappings overrides `c-]` which breaks navigation in the help system

### ISSUE THREAD

**Issue by yatesco** [neovim/nvim-lspconfig#493]
The `:help lsp` suggests `nnoremap <silent> <c-]> <cmd>lua vim.lsp.buf.definition()<CR>`, which overrides the default key binding for navigating across a tag. 

This means that <c-]> has no effect when viewing help files because the help system doesn't use an LSP server.

What's the idiomatic way to solve this (this is a little out of my depth)? I thought of a function which checks to see if an LSP is active and if not calls the "native" `c-t`, and binding that function to `c-t` globally, but I might be talking nonsense. 

I could also only apply the mapping to non-help files but I can't figure out how to do that - I certainly don't want to add a specific instruction in each `ftplugin` file.

Help :-)

**Comment by mjlbach** [comment]
To be honest, I prefer gd  `vim.api.nvim_buf_set_keymap(bufnr, 'n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)`

If you want to *only* bind LSP keybindings when servers are available for the filetype, you can see my config.

https://github.com/mjlbach/nix-dotfiles/blob/49a6c89b455a79669c17f17d471b9922fd193b65/nixpkgs/configs/neovim/init.vim#L311-L359

It would be possible to fallback to c-[ if the language server is not running. If you still want that I can come up with a snippet.

**Comment by yatesco** [comment]
Your `init.vim` was most instructive, but a snippet to check whether a language server is running might be useful too - thanks!

**Comment by mjlbach** [comment]
You can use `vim.lsp.buf_get_clients()`. I think the way I have it in my configuration is the best way to selectively bind keybinds only if a language server is set up for that buffer (that I know of)

**Comment by lithammer** [comment]
You can also do conditional mapping by checking the `client.resolved_capabilities` table in the `on_attach` callback.

```lua
local lspconfig = require("lspconfig")

local function on_attach(client, bufnr)
  local buf_set_keymap = function(...)
    vim.api.nvim_buf_set_keymap(bufnr, ...)
  end

  local opts = {noremap = true, silent = true}

  if client.resolved_capabilities.document_formatting then
    buf_set_keymap(
      "n", "<Leader>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts
    )
  end
end

lspconfig.foo.setup({
  on_attach = on_attach
})
```

**Comment by mjlbach** [comment]
I'm going to close this @lithammer's solution is reasonable, and the :help lsp documentation is provided in neovim core.

**Comment by yatesco** [comment]
(thanks all - and I hope you had a great Christmas and a happy new year!)
