### ISSUE TITLE
Slows down buffer loading

### ISSUE THREAD

**Issue by maisiliym** [neovim/nvim-lspconfig#496]
This hasen't been formally proven, since nvim's profiling doesnt seem to pickup the lua action, but enough imperial evidence has been observed to conclude that lspconfig's autocmd's slow down buffer loading of the concerned filetypes.
Li naively tried to wrap the autocmd with a defered call, without success;
```lua
    api.nvim_command(string.format(
        "autocmd %s lua vim.defer_fn(require'lspconfig'[%q].manager.try_add(), 1000)"
        , trigger
        , config.name
        ))
```

And, of course, this hack would fail horribly with things like telescope's 'buffer-preview' (which was the source of frustration which led to this report), since the buffer in question may well be gone by the time the timer is due.

Now, it would be best to actually confirm this bug, so if there is a documented method, linking it here would be appreciated.

**Comment by mjlbach** [comment]
What sort of documented method? I'm not sure I fully understand the issue (other than the fact that there is some performance penalty associated with the autocommands). Can you provide a minimal testcase for reproduction, and a minimal init.vim/init.lua? 

Autocommands are only invoked in two places: 

https://github.com/neovim/nvim-lspconfig/blob/4f431b992482d9edbe4ccf65170e6304503614a9/lua/lspconfig/configs.lua#L113-L117

https://github.com/neovim/nvim-lspconfig/blob/4f431b992482d9edbe4ccf65170e6304503614a9/lua/lspconfig/configs.lua#L168-L173

**Comment by maisiliym** [comment]
> What sort of documented method?

To prove the slowdown comes from the autocmd. Yes, There are two autocmds in the code, and the defer fn was tested on both.

**Comment by maisiliym** [comment]
> Can you provide a minimal testcase for reproduction ?

Just load lspconfig and open a supported filetype. Also, editing minimized buffers is slowed down as well. The difference is best observed on a CPU which does not use environmentally-irresponsible clock speeds (such as anything above 1GHz). Tested on 800mhz dual-core.

**Comment by mjlbach** [comment]
I'm still a little confused. No, we don't have any profiling tools you can use to figure out where the slowdown would be. I would expect there would be a slowdown when opening a buffer, which triggered the start of the language server. I don't know why this would affect telescope, as for most file preview for non-open buffers, they are piping bat into the buffer, not opening the buffer in neovim. Switching between already open buffers shouldn't be causing a slowdown, because the autocmd won't trigger when switching to a buffer.

**Comment by mjlbach** [comment]
@maisiliym I dug into this, and I don't think there is an issue in nvim-lspconfig

The only two autocommands are the ones we discussed. In this branch I added logging to the execution time.

https://github.com/mjlbach/nvim-lspconfig/tree/profile_buffer_autocmd

```
autocmd                count    autocmd time (s)      total time (aummed across autocmd)
manager.try_add   2           0.000441575             0.016123914
setup_buffer         1            0.000817582             0.018259068
manager.try_add  4            0.000206566            0.018189713
setup_buffer        2             0.000576976            0.018836044
```

I also used telescope, and the only telescope action that triggered any of these was actually opening the buffer, previewing did not trigger any of them. 

For reference, this was on a 2014, dual core, laptop with a solid state drive.

You can dig in more, but I don't think 0.5 milliseconds on buffer opening is large overhead. If there is a slowdown, it's in neovim core, not nvim-lspconfig.

**Comment by maisiliym** [comment]
> as for most file preview for non-open buffers, they are piping bat into the buffer

Telescope has an option to use buffers for previews

**Comment by mjlbach** [comment]
Hence my caveat > for most file preview for non-open buffers :) 

It never triggered the autocmd unless I switched to the buffer, at which point the average time was around 1.5 milliseconds spent on the autocmd to open the buffer

**Comment by mjlbach** [comment]
You should try the branch I linked out for yourself and report back your timings, if you think there is an issue.

**Comment by maisiliym** [comment]
The culprit was nvim-treesitter. Since the same languages were configured for both, and since Li made assumptions about treesitter vs lsp slowdowns, lsp was first thought responsible.

**Comment by mjlbach** [comment]
No worries! Glad you managed to figure it out and I learned a bit about profiling autocommands along the way! I would report the bug to them and see what they have to say.
