### ISSUE TITLE
No LSP highlighting after calling :colorscheme

### ISSUE THREAD

**Issue by samhh** [neovim/nvim-lspconfig#516]
- `nvim --version`: `v0.5.0-dev+992-gf3a8c930a`
- nvim-lsp version(commit hash): Can't find this, but cloned latest at 4:31pm GMT 1st Jan 2021.
- `:checkhealth` result: Just missing providers, debug build of nvim, nothing unusual.
- Language servers: Both tsserver and hls.
- Can you reproduce this behavior on other language server clients: No, coc.nvim was fine.
- Operating system/version: Arch Linux latest everything.
- Terminal name/version: Alacritty 0.6.0.
- `$TERM`: `alacritty`

### How to reproduce the problem from neovim startup

Add the following nvim config (I believe any plugin manager and language servers will do):

```vim
packadd minpac
call minpac#init()
call minpac#add('k-takata/minpac', {'type': 'opt'})

call minpac#add('neovim/nvim-lspconfig')
lua <<EOF
  require'lspconfig'.tsserver.setup{}
  require'lspconfig'.hls.setup{}
EOF

command! PackUpdate call minpac#update()
command! PackClean  call minpac#clean()
```

Open a file that'll trigger a language server. Make an error, and you'll see an underline underneath it. Now undo the error, the underline will go away. Now run `:colorscheme default`, and repeat the error.

### Actual behaviour

There will be no underline after running `:colorscheme`.

### Expected behaviour

There should still be an underline after running `:colorscheme`.

**Comment by mjlbach** [comment]
This is the repo for language server configuration for neovim's built-in language server client, this seems like an implementation issue in core. FWIW, when switching to a custom colorscheme (one dark) from default, the underline remains intact.

**Comment by mjlbach** [comment]
I would personally recommend adding 
```
vim.cmd([[ autocmd ColorScheme * :lua require('vim.lsp.diagnostic')._define_default_signs_and_highlights() ]]) 
```
If this is bothering you. I'm not sure if this should be added as a default to core or nvim-lspconfig though.

**Comment by mjlbach** [comment]
On further investigation, this isn't even an isolated neovim issue. The issue is in vim core.

https://github.com/vim/vim/issues/4405

All we do is call highlight via a vim command, vim is the one erasing highlight groups on colorscheme changes. The best we can do is maybe add a note somewhere.

**Comment by samhh** [comment]
Your suggested fix works, thank you. :slightly_smiling_face: 

Interesting! I'll keep an eye on this, but feel free to close this at your own leisure.

**Comment by quantum-booty** [comment]
> I would personally recommend adding
> 
> ```
> vim.cmd([[ autocmd ColorScheme * :lua require('vim.lsp.diagnostic')._define_default_signs_and_highlights() ]]) 
> ```
> 
> If this is bothering you. I'm not sure if this should be added as a default to core or nvim-lspconfig though.

Hi @mjlbach, looks like the api has changed for nightly as I cannot find the _define_default_signs_and_highlights() function in the diagnostic.lua How can I do this with nightly?

**Comment by mjlbach** [comment]
I'm pretty sure this isn't necessary with the diagnostic overhaul on 0.6, these functions were removed. cc @gpanders

**Comment by quantum-booty** [comment]
Looks like the underlines disappears when I change from nightfox to gruvbox then back to nightfox.
![image](https://user-images.githubusercontent.com/28958399/135730707-28d15521-e81a-45d2-9f72-590f17d05233.png)
![image](https://user-images.githubusercontent.com/28958399/135730710-98de0b65-8180-4e75-be05-372c5c86a7fc.png)
![image](https://user-images.githubusercontent.com/28958399/135730725-a13e88ce-cf33-4225-9410-51f4fe8b40f4.png)

**Comment by gpanders** [comment]
The colorscheme is running `:hi clear` so the highlight groups are being removed.

Try adding the following to your `init.vim`:

```vim
autocmd ColorScheme * runtime plugin/diagnostic.vim
```

`plugin/diagnostic.vim` is the plugin file included in `$VIMRUNTIME` that defines the highlight groups.

**Comment by quantum-booty** [comment]
> The colorscheme is running `:hi clear` so the highlight groups are being removed.
> 
> Try adding the following to your `init.vim`:
> 
> ```viml
> autocmd ColorScheme * runtime plugin/diagnostic.vim
> ```
> 
> `plugin/diagnostic.vim` is the plugin file included in `$VIMRUNTIME` that defines the highlight groups.

Thank you @gpanders, @mjlbach this worked!

**Comment by gpanders** [comment]
@quantum-booty Note that as of https://github.com/neovim/neovim/pull/15894 that autocommand is no longer necessary and diagnostic highlight groups will always be defined.
