### ISSUE TITLE
Consider adding configuration for markdownlint

### ISSUE THREAD

**Issue by cloggier** [neovim/nvim-lspconfig#522]
Not a bug report. I will try to create PR at some point, but have zero understanding of how this plugin works so will take me a while. In the meantime putting it here as pending task (maybe even someone else will pick it up).

https://github.com/DavidAnson/markdownlint

**Comment by mjlbach** [comment]
I don't believe this is a language server

**Comment by cloggier** [comment]
Ah, of course. Busy day, apologies for the noise.
