### ISSUE TITLE
Julials no completion and crashes at start up

### ISSUE THREAD

**Issue by quantum-booty** [neovim/nvim-lspconfig#524]
- `nvim --version`: NVIM v0.5.0-dev+983-g52163c66b 
- nvim-lsp version(commit hash): 7e9356bb9bbc542ae7afed8f9956a86d4aae3de0
- `:checkhealth` result
link to checkhealth: https://hastebin.com/jibodobida.sql
- What language server(If the problem is related to a specific language server): Julia
- Is this problem isolated to this particular language server: Yes
- Operating system/version: Arch
- Terminal name/version: tried on Kitty and Alacritty

### How to reproduce the problem from neovim startup
My minimal init.vim:
```
au BufNewFile,BufRead *.jl set filetype=julia

call plug#begin('~/.config/nvim/plugged')
Plug 'nvim-lua/completion-nvim'
Plug 'neovim/nvim-lspconfig'
call plug#end()

set updatetime=50
set completeopt+=menuone,noselect,noinsert
set completeopt-=preview
set shortmess+=c

autocmd BufEnter * lua require'completion'.on_attach()

lua <<EOF
require'lspconfig'.julials.setup{}
EOF
```
### LSP log

Log link:
https://hastebin.com/eyiraqoxeq.yaml

**Comment by mjlbach** [comment]
```
"server_request: no handler found for"	"window/workDoneProgress/create"
[ DEBUG ] 2021-01-03T20:57:06+0000 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:500 ]	"server_request: callback result"	{  err = {    code = -32601,    message = "MethodNotFound",    <metatable> = {      __tostring = <function 1>    }  },  status = true}
```
Try updating your nightly, I added this in core in the last couple days

**Comment by quantum-booty** [comment]
@mjlbach I built nvim up to the latest commit and it's still not working, lsp log:
https://hastebin.com/egomofasap.yaml

**Comment by mjlbach** [comment]
Is that it? I don't see a termination message. It shouldn't be crashing.

**Comment by quantum-booty** [comment]
Oh sorry, its working now, I thought it wasn't because the completion was slow.

**Comment by mjlbach** [comment]
Sorry, think that's on julials 😆
