### ISSUE TITLE
jdtls cmd to start - documentation

### ISSUE THREAD

**Issue by ChrisAmelia** [neovim/nvim-lspconfig#532]
After https://github.com/neovim/nvim-lspconfig/commit/cfad27c74c3a8943245904745dc3ef6658d07f9a
The documentation about how to start the server has to be updated

**Comment by hungrybirder** [comment]
Hi,  @ChrisAmelia 
I got a way to start jdtls.

1. Install jdtls on MacOS
```bash
brew install hungrybirder/homebrew-repo/jdt-language-server
```

2. config init.vim
```vim
lua <<EOF
lspconfig.jdtls.setup{
  on_attach=on_attach,
  cmd = {"jdt-language-server"},
  root_dir = util.root_pattern(".git", "pom.xml"),
}
EOF
```
