### ISSUE TITLE
Use better fallback value when root_dir can't be found

### ISSUE THREAD

**Issue by lithammer** [neovim/nvim-lspconfig#533]
Many language servers seem to behave poorly when a project root directory can't be found (see some of the referenced issues). I figured it would be a good idea to add `util.find_git_ancestor(fname)` and `util.path.dirname(fname)`  as global default fallbacks if `get_root_dir()` turns up empty. Something like this:

```diff
diff --git a/lua/lspconfig/configs.lua b/lua/lspconfig/configs.lua
index d1b0090..84b56e4 100644
--- a/lua/lspconfig/configs.lua
+++ b/lua/lspconfig/configs.lua
@@ -186,7 +186,10 @@ function configs.__newindex(t, config_name, config_def)
       if vim.bo.buftype == 'nofile' then
         return
       end
-      local root_dir = get_root_dir(api.nvim_buf_get_name(0), api.nvim_get_current_buf())
+      local fname = api.nvim_buf_get_name(0)
+      local root_dir = get_root_dir(fname, api.nvim_get_current_buf())
+        or util.find_git_ancestor(fname)
+        or util.path.dirname(fname)
       local id = manager.add(root_dir)
       if id then
         lsp.buf_attach_client(0, id)

```

What do you think? I'm not sure which is better between `util.path.dirname(fname)` and `vim.loop.cwd()` though.

Ref https://github.com/neovim/nvim-lspconfig/issues/446, https://github.com/neovim/nvim-lspconfig/issues/361, https://github.com/neovim/nvim-lspconfig/issues/260, https://github.com/neovim/nvim-lspconfig/pull/176

**Comment by lithammer** [comment]
This way each server config can focus on language specific root patterns instead of general ones like `.git` and `util.path.dirname(fname)` to handle stand-alone scripts etc.

**Comment by lithammer** [comment]
I would be happy to provide a pull request if this sounds like a good idea.

**Comment by mjlbach** [comment]
I *think* this is a good idea, because we get a lot of negative feedback about language servers being broken, when it's really that someone is opening up a python/lua file in their home directory which doesn't trigger root directory detection. The *caveat emptor* of this approach is if you fall back to your current directory, and that directory is huge, many language servers will either crash, or have extreme resource usage while indexing the directory.

**Comment by mjlbach** [comment]
The other issue is this may hide failure from the user. If you open a file, and it sets the root directory to the current one, and the server requires something like a cargo.toml or a package.json to work, it will be less transparent. Maybe a warning if root directory isn't matched should be printed.

**Comment by lithammer** [comment]
> The _caveat emptor_ of this approach is if you fall back to your current directory, and that directory is huge, many language servers will either crash, or have extreme resource usage while indexing the directory.

Good point. I guess a lot of people often create temporary scripts or "scratch" files directly in their home directory which could cause the language server to scan the entire home directory (both Sumneko and bash-language-server seem to do this).

A solution/workaround could be a to check if the fallback version of `util.path.dirname(fname)` resulted in the home directory we send `null`/`nil` and let the server handle it (seems valid according to the spec at least).

```diff
diff --git a/lua/lspconfig/configs.lua b/lua/lspconfig/configs.lua
index d1b0090..22bb275 100644
--- a/lua/lspconfig/configs.lua
+++ b/lua/lspconfig/configs.lua
@@ -186,7 +186,12 @@ function configs.__newindex(t, config_name, config_def)
       if vim.bo.buftype == 'nofile' then
         return
       end
-      local root_dir = get_root_dir(api.nvim_buf_get_name(0), api.nvim_get_current_buf())
+      local fname = api.nvim_buf_get_name(0)
+      local root_dir = get_root_dir(fname, api.nvim_get_current_buf())
+        or util.find_git_ancestor(fname)
+      if not root_dir and util.path.dirname(fname) ~= vim.loop.os_homedir() then
+        root_dir = util.path.dirname(fname)
+      end
       local id = manager.add(root_dir)
       if id then
         lsp.buf_attach_client(0, id)

```

**Comment by lithammer** [comment]
> The other issue is this may hide failure from the user. If you open a file, and it sets the root directory to the current working directory, and the server requires something like a cargo.toml or a package.json to work (which isn't in the current working directory because you never made one), it will be less transparent why things are failing since the server may operate but with a reduced feature set. Maybe a warning if root directory isn't matched should be printed.

Makes sense I guess. Unless it turns out the warning is more annoying 🤔 At the very least we should log something for debugging purposes.

**Comment by mjlbach** [comment]
I think you should go ahead and make the PR since it's short and we can discuss it on there/have people try it out and see if annoying corner cases arise.

**Comment by mjlbach** [comment]
I was thinking about this more, and I'm planning extending checkhealth to show the root directory, with an explanation as to why a server is not launching. 

I think we should just manually go ahead and add the current directory to all servers that misbehave, instead of automatically doing it. It's more explicit, hides less of the magic, and makes it easier for people to copy the configs over to neovim core.

**Comment by lithammer** [comment]
Sounds reasonable!
