### ISSUE TITLE
After updating nvim-lspconfig, some lsp-plugins do not work anymore (`command is not executable`)

### ISSUE THREAD

**Issue by rverton** [neovim/nvim-lspconfig#550]
- `nvim --version`: nvim-lsp version(commit hash): NVIM v0.5.0-dev+1012-gfe1ebea33
- `:checkhealth` result:

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - ERROR: jsonls: The given command "vscode-json-languageserver" is not executable.
  - INFO: pyright: configuration checked.
  - INFO: gopls: configuration checked.
  - ERROR: tsserver: The given command "typescript-language-server" is not executable.
  - ERROR: yamlls: The given command "yaml-language-server" is not executable.
  - ERROR: html: The given command "html-languageserver" is not executable.
  - 
```

- What language server(If the problem is related to a specific language server): tsserver
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): yes, for example json
- Operating system/version: macOS Big Sur
- Terminal name/version: iTerm2
- `$TERM`: xterm-256color

### How to reproduce the problem from neovim startup

Open a file configured for the javascript/typescript language server or a json file.

### Actual behaviour

```
Error executing "FileType Autokommandos für "javascript"":
E5108: Error executing lua .../share/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:319: The given command "typescript-language-server" is not executable.
```

### Expected behaviour

No error, LSP is loaded/started.

### LSP log

```
[ INFO ] 2021-01-07T11:44:26+0100 ] .../share/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:311 ]	"Starting RPC client"	{  args = { "--stdio" },  cmd = "typescript-language-server",  extra = {}}
[ INFO ] 2021-01-07T11:44:29+0100 ] ...ocal/share/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:999 ]	"exit_handler"	{}
```

**Comment by mjlbach** [comment]
We deprecated the older installer, so if you used `:LspInstall` before, you'll need to reinstall

`npm install -g typescript typescript-language-server`

**Comment by rverton** [comment]
Thanks! This was not obvious for me, works now.
