### ISSUE TITLE
We've enabled discussions! Please read before posting.

### ISSUE THREAD

**Issue by mjlbach** [neovim/nvim-lspconfig#563]
We've enabled the "discussions" feature on github to facilitate diagnosing language server problems that *aren't* necessarily bugs, and so you can stay up to date with changes in language servers or *upstream* issues with the servers that we can't fix in neovim or nvim-lspconfig. We'll be relying on users to exercise their best discretion and self-triage to determine whether a question should be posted in one of the discussion topics, in nvim-lspconfig's issue tracker, or in neovim core's issue tracker.

Some requests:
* Please keep, and post in, *one* thread per language server, and read the thread history before posting. I'll try to keep these pinned. I think it will help for discovery if one can easily read through a thread to see all discussion pertaining to that language server, and follow that thread for notifications.
* Generally, I will make new topics. If it's *really* necessary to make a topic, please keep it in Q&A. You should probably post in the individual language server's topic though. Comment here if you want a specific topic created.
* Please don't make unnecessary +1 comments, respond with emoji to keep the chat history clean 🎆 
* The discussion forum is meant to have more rapid response than filing an issue, there's not an expectation that a neovim contributor will answer questions though. I'll probably check all issues and threads once a night.
* Please follow all discussions for which you are interested in helping others. Pay it forward!

**Comment by gshpychka** [comment]
`Some requests:` is outdated, as there aren't any LSP-specific topics there yet.

**Comment by mjlbach** [comment]
Sure, I updated it
