### ISSUE TITLE
LspInfo fails when cmd has newline character

### ISSUE THREAD

**Issue by coxackie** [neovim/nvim-lspconfig#660]
The new `LspInfo` functionality is awesome, and works for most cases flawlessly. I noticed a hick-up: I just run LspInfo in a buffer with a Julia project, and got:
![Screenshot from 2021-01-12 17-42-20](https://user-images.githubusercontent.com/22049642/104352492-a7e28a00-54fe-11eb-8233-181690118610.png)
Pressing enter makes the floating window appear empty, and one has to :q to get back to the buffer.

**Comment by mjlbach** [comment]
For reference the issue is just new lines in 'cmd', most language servers pass this as a list of arguments. I'll push a fix later.
