### ISSUE TITLE
How to disable inline buffer error messages?

### ISSUE THREAD

**Issue by madskjeldgaard** [neovim/nvim-lspconfig#662]
HI
Thanks for your hard work. I love this plugin and use it as my daily driver.
I was wondering if there is an option to disable the inlined error message from diagnostics? I would like to hide it (but not the marker in the gutter signifying problems) because I would like to mainly use the navigation capabilities that show the full error message elsewhere. Thanks!

**Comment by lithammer** [comment]
```lua
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false,
    }
)
```

See `:help vim.lsp.diagnostic.on_publish_diagnostics` for more settings.

**Comment by madskjeldgaard** [comment]
Thanks!

**Comment by cpdean** [comment]
@madskjeldgaard 

> See :help vim.lsp.diagnostic.on_publish_diagnostics for more values you can tweak.

Is this out of date as of nvim v0.5?

```
NVIM v0.5.0-753-g4b00916e9
```

```
Error detected while processing command line:                                                                          
E149: Sorry, no help for vim.lsp.diagnostic.on_publish_diagnostics                                                     
Press ENTER or type command to continue             
```

**Comment by agriffis** [comment]
Personally I just wanted to disable diagnostics entirely. This works on current neovim with:

```
lua vim.lsp.handlers["textDocument/publishDiagnostics"] = function() end
```

Just posting that in case it helps someone else.

**Comment by Yutsuten** [comment]
To set the configuration globally, use this:

```lua
vim.diagnostic.config({virtual_text = false})
```

I wanted to apply this setting to [nvim-lint](https://github.com/mfussenegger/nvim-lint) too, so this was the one that worked for me.

**Comment by coding610** [comment]
Is there a way to remove the "E" or "W" thats in the inline if its a error. I got a script that imports another file but lsp cant find it(python can) and it gives it all these E. I doesnt show text just the E but can you remove that too?

**Comment by arrky** [comment]
> Is there a way to remove the "E" or "W" thats in the inline if its a error. I got a script that imports another file but lsp cant find it(python can) and it gives it all these E. I doesnt show text just the E but can you remove that too?

vim.diagnostic.config({signs = false})

**Comment by astier** [comment]
There is also `vim.diagnostic.disable()`. It doesn't show any diagnostics but you still can open them in quickfix-/location-list and navigate them with `vim.diagnostic.goto_next`.

**Comment by ret2src** [comment]
Quickly wanted to share the following snippets I've hacked together to toggle diagnostics, since this thread can easily be found through Google:

``` lua
-- Command to toggle inline diagnostics
vim.api.nvim_create_user_command(
  'DiagnosticsToggleVirtualText',
  function()
    local current_value = vim.diagnostic.config().virtual_text
    if current_value then
      vim.diagnostic.config({virtual_text = false})
    else
      vim.diagnostic.config({virtual_text = true})
    end
  end,
  {}
)

-- Command to toggle diagnostics
vim.api.nvim_create_user_command(
  'DiagnosticsToggle',
  function()
    local current_value = vim.diagnostic.is_disabled()
    if current_value then
      vim.diagnostic.enable()
    else
      vim.diagnostic.disable()
    end
  end,
  {}
)
```

**Comment by Txreq** [comment]
helpfull

**Comment by AtaraxiaZ** [comment]
If you are using [LazyVim](https://www.lazyvim.org/), you could easily toggle diagnostics with `<leader>ud`

**Comment by Paulobox** [comment]
ret2src

-- Keybinding to toggle inline diagnostics (ii)
vim.api.nvim_set_keymap('n', '<Leader>ii', ':lua vim.cmd("DiagnosticsToggleVirtualText")<CR>', { noremap = true, silent = true })

-- Keybinding to toggle diagnostics (id)
vim.api.nvim_set_keymap('n', '<Leader>id', ':lua vim.cmd("DiagnosticsToggle")<CR>', { noremap = true, silent = true })

Works just add keybinding thanks
