### ISSUE TITLE
How to render the markdown in the popups?

### ISSUE THREAD

**Issue by madskjeldgaard** [neovim/nvim-lspconfig#666]
Hi 
Sorry for asking another question here in the issues (maybe there should be a general topic in the discussions for this kind of stuff?)

I am wondering if anyone can point me to the option that makes sure the text in the popups containing markdown is rendered somehow. I don't really need to see the tags etc. Can anyone help me ? Thanks again!

![2021-01-14-124110_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/104586688-14c46400-5666-11eb-9302-d8b606bb6738.png)

**Comment by mjlbach** [comment]
I'm confused what you mean by rendered. Are you saying you'd like ### static-method to be bolded?

**Comment by madskjeldgaard** [comment]
Yeah exactly. Is that possible? As well as the words with code ticks around them.

**Comment by mjlbach** [comment]
Have you overridden conceallevel? Try set `concealevel=4`

**Comment by madskjeldgaard** [comment]
Thanks, my conceallevel is set to 0 it seems but changing it to 3 didn't help either. What is the filetype of the popup, do you know? Thanks for the help!

**Comment by mjlbach** [comment]
You need to toggle conceallevel inside the popup, switch to it with c-w and then run the ex command. What does normal markdown look like to you? 

All the syntax settings for the floating window are done here:

https://github.com/mjlbach/neovim/blob/2390a0d3c412060eeeec2c7076a2014e2834eb10/runtime/lua/vim/lsp/util.lua#L885-L907

**Comment by madskjeldgaard** [comment]
I tried jumping to the window but and setting the conceallevel for it but that doesn't seem to make a difference. Hmm. 

"normal" markdown for me looks like this in the popup, "unrendered" (which I prefer when writing markdown) with hashtags, ticks etc.

![2021-01-14-220642_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/104649309-d4400700-56b4-11eb-8cbc-69fc4ea0058c.png)

**Comment by madskjeldgaard** [comment]
But maybe this is something specific to my setup ...

**Comment by mjlbach** [comment]
You'll need to try a markdown plugin that renders markdown the way you want, I think the floating window should inherit from that. Conceal seems to work fine for me. See video:

https://user-images.githubusercontent.com/13316262/104650895-c1551480-566b-11eb-95ea-16eba7a7f730.mov

**Comment by madskjeldgaard** [comment]
> You'll need to try a markdown plugin that renders markdown the way you want, I think the floating window should inherit from that. Conceal seems to work fine for me. See video:
> Screen.Recording.2021-01-14.at.1.23.03.PM.mov

Ahh okay. But shouldn't your ```### function``` become something like __function__ and the ticks around the word in that line turned into something else as well?

**Comment by madskjeldgaard** [comment]
![2021-01-14-222406_1920x1080_scrot](https://user-images.githubusercontent.com/22474608/104651654-3bab8600-56b8-11eb-9a3b-3f153d3b3d34.png)

Here's an example from bash

**Comment by mjlbach** [comment]
Not with the default vim markdown settings (I think). We're using markdown, so if you copy and paste whatever's in the floating window into a markdown buffer, it should look identical

**Comment by madskjeldgaard** [comment]
Ah okay, gotcha

**Comment by mjlbach** [comment]
The summary is, if you get a regular markdown window looking like how you want it, via plastic boy's markdown plugin/whatever, I think that the floating window should respect those rules. As it is, it will look exactly like your current markdown settings (which is what you're seeing).

**Comment by mjlbach** [comment]
Anyways, I'm going to close for now, as I don't think there's a bug. If you have issues getting your markdown settings from a plugin to apply globally you can file an issue with core and I'll take a look at it, and if it's a usage question feel free to ping me on gitter.

**Comment by madskjeldgaard** [comment]
Yeah setting conceallevel seems to make it a little more tolerable but it does look messy still. But thanks for your help, now I know where to experiment.

**Comment by mjlbach** [comment]
Yeah the function is super readable and overridable (see :help lsp-handlers)
```
vim.lsp.handlers["textDocument/hover"] = my_custom_default_definition
```
You can replace what we do with my_custom_default_definition, but the main thing you'd want to change is the call to `util.fancy_floating_markdown`, like I said though, I think this has more to do with your markdown highlight rules globally though rather than the fancy_floating_markdown function which just reads syntax. Just showing you this because in the event that you want to try modifying the handler, if you override it like above, you can experiment within your config without modifying the neovim source.

**Comment by madskjeldgaard** [comment]
> Yeah the function is super readable and overridable (see :help lsp-handlers)
> 
> ```
> vim.lsp.handlers["textDocument/hover"] = my_custom_default_definition
> ```
> 
> You can replace what we do with my_custom_default_definition, but the main thing you'd want to change is the call to `util.fancy_floating_markdown`, like I said though, I think this has more to do with your markdown highlight rules globally though rather than the fancy_floating_markdown function which just reads syntax. Just showing you this because in the event that you want to try modifying the handler, if you override it like above, you can experiment within your config without modifying the neovim source.

Great. Thanks for the tips! Will experiment with this further
