### ISSUE TITLE
Error loading workspace folders with gopls

### ISSUE THREAD

**Issue by ChrisAmelia** [neovim/nvim-lspconfig#674]
With 325fb3f1635b4ed5b3ae37eb423eab53fe805b2e  
This happens with gopls:

> LSP[gopls] Error loading workspace folders (expected 1, got 0)
failed to load view for file:///home/user/GitHub/invaders: failed to get workspace configuration from client (file:///home/user/GitHub/invaders): MethodNotFound

This is the result of `:LspInfo`:

```text
Available servers: 
	jdtls, gopls, sumneko_lua 
 
Clients attached to this buffer: 1 
 
Client: 1 
	name: gopls 
	root: /home/user/GitHub/invaders 
	filetypes: go, gomod 
	cmd: gopls serve 
 
Total active clients: 1 
 
Client: 1 
	name: gopls 
	root: /home/user/GitHub/invaders 
	filetypes: go, gomod 
	cmd: gopls serve 
 
Clients that match the current buffer filetype: 
 
Config: gopls 
	cmd: gopls serve 
	cmd is executable: True 
	identified root: /home/user/GitHub/invaders 
	custom handlers: client/registerCapability 
```

Can be reproduced with this minimal config:

init.vim
```vim
set runtimepath^=~/.local/share/nvim/site/pack/packer/opt/nvim-lspconfig

lua << EOF
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true

require'lspconfig'.gopls.setup{
	on_attach = on_attach_vim,
	capabilities = capabilities,
	cmd = {"gopls", "serve"},
	settings = {
		gopls = {
			analyses = {
				unusedparams = true,
			},
			staticcheck = true,
		},
	},
}
EOF
```

then open a go project.

**Comment by mjlbach** [comment]
Did you update your nightly?

**Comment by ChrisAmelia** [comment]
Thanks, solved it.

**Comment by mjlbach** [comment]
I thought 2 weeks was a large enough window 😢

**Comment by mjlbach** [comment]
Be prepared to update your nightly in another two weeks because I'm deprecating another handler ;)

**Comment by mjlbach** [comment]
Merged another change requiring the latest nightly. I think this should be the last (major) one.
