### ISSUE TITLE
lua lsp docs should be expanded

### ISSUE THREAD

**Issue by mhartington** [neovim/nvim-lspconfig#68]
Right now, trying to configure the lua lang-server is a bit difficult. It's not clear the best way to customize things based on someones machine/env.

**Comment by csmoe** [comment]
neovim keeps error'd with helpless message on `settings`, it's really annoying for users without lua background to config nvim-lsp :(, have to "learn" lua before adding a simple settings

**Comment by justinmk** [comment]
> It's not clear the best way to customize things based on someones machine/env.

@mhartington can you give specific examples of a custom scenario? Then we can provide examples in the docs.

**Comment by mhartington** [comment]
Specifically lua lsp specifies that the servers cmd is not set


https://github.com/neovim/nvim-lsp#sumneko_lua

We should at least expand on this to show how to set that cmd.

> https://github.com/neovim/nvim-lsp#example-custom-config

These docs show how to completely override the config, but in smaller cases, just setting the cmd should be shown/documented

**Comment by norcalli** [comment]
I would say for the sumneko one, the recommended way to use it is `LspInstall`. But I agree that it would be helpful to be more explicit about the fact that you can override/set the base `vim.lsp.start_client` config options as well.

**Comment by mjlbach** [comment]
@mhartington I made a first pass at solving a bit about overriding the sumneko settings here: https://github.com/neovim/nvim-lspconfig/pull/473

A lot of people ask about why the neovim globals aren't being completed as well, so two birds with one stone?

**Comment by teto** [comment]
There is no recommended way anymore to install sumneko (or any LSP servers) except you shouldn't use LspInstall as we are getting rid of it. Makes sense to document the settings for vim thanks @mjlbach

**Comment by mjlbach** [comment]
Kept the (big) PR separate for removing the install info generally, for now I'll fix the change you suggested on #473
