### ISSUE TITLE
ability to disable autostart

### ISSUE THREAD

**Issue by teto** [neovim/nvim-lspconfig#691]
I would like to decouple the configuration of the language server and its autostart so that I can configure my LSPs globally but decide on a per project basis whether to launch the server or not (via .nvimrc for instance)

**Comment by mjlbach** [comment]
We talked about this on Gitter, but for others, this is currently possible. For a new server, the example would be as follows: 

In `init.vim`:
```lua
local lspconfig = require'lspconfig'
local configs = require'lspconfig/configs'
configs.foo_lsp = {
  default_config = {
    cmd = {'/home/ashkan/works/3rd/lua-language-server/run.sh'};
    filetypes = {'lua'};
    root_dir = function(fname)
      return lspconfig.util.find_git_ancestor(fname) or vim.loop.os_homedir()
    end;
    settings = {};
  };
}
```

In .nvimrc:

```
lspconfig.foo_lsp.setup{}
```

I'm leaving this open as with a server that is already defined, calling `setup()` twice will not override the behavior as expected (at least, I think). This should probably get cleaned up.
