### ISSUE TITLE
Clangd error

### ISSUE THREAD

**Issue by BigfootN** [neovim/nvim-lspconfig#692]
- `nvim --version`: NVIM v0.5.0-dev+1045-g24b60322a
                               Build type: RelWithDebInfo
                               LuaJIT 2.0.5
- What language server (If the problem is related to a specific language server): clangd
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): not tested
- Is the problem isolated to a particular language server: I think so
- Operating system/version: archlinux

### How to reproduce the problem from neovim startup

Use the default config, so just add
```lua
lua << EOF 
require'lspconfig'.clangd.setup{}
EOF
```
in your init.vim

### Actual behaviour

I don't even have the autocompletion, here is what the logs show:

```
[ ERROR ] 2021-01-23T18:09:20+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:20.805] clangd version 11.0.0\nI[18:09:20.805] PID: 24167\nI[18:09:20.805] Working directory: <working dir>\nI[18:09:20.805] argv[0]: clangd\nI[18:09:20.805] argv[1]: --background-index\nI[18:09:20.805] Starting LSP over stdin/stdout\n"
[ ERROR ] 2021-01-23T18:09:20+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:20.805] <-- initialize(1)\n"
[ ERROR ] 2021-01-23T18:09:20+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:20.806] --> reply:initialize(1) 0 ms\n"
[ ERROR ] 2021-01-23T18:09:20+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:20.806] <-- initialized\nI[18:09:20.806] <-- textDocument/didOpen\n"
[ ERROR ] 2021-01-23T18:09:20+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:20.806] Loaded compilation database from /<the directory>\nI[18:09:20.806] --> window/workDoneProgress/create(0)\n"
[ ERROR ] 2021-01-23T18:09:20+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:20.807] Enqueueing 13 commands for indexing\nI[18:09:20.807] ASTWorker building file <the cpp file> version 0 with command \n[<the directory>]\n/usr/bin/c++ --driver-mode=g++ <flags> -c <the cpp file> -fsyntax-only -resource-dir=/usr/lib/clang/11.0.0\nI[18:09:20.807] <-- reply(0)\nI[18:09:20.807] --> $/progress\nI[18:09:20.807] --> $/progress\n"
[ ERROR ] 2021-01-23T18:09:20+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:20.892] --> $/progress\nI[18:09:20.892] --> $/progress\n"
[ ERROR ] 2021-01-23T18:09:21+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:21.118] --> textDocument/publishDiagnostics\n"
[ ERROR ] 2021-01-23T18:09:25+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:25.454] <-- textDocument/didChange\n"
[ ERROR ] 2021-01-23T18:09:25+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:25.454] <-- textDocument/didChange\n"
[ ERROR ] 2021-01-23T18:09:25+0100 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"clangd"	"stderr"	"I[18:09:25.504] ASTWorker building file <the cpp file> version 4 with command \n[<the directory>]\n/usr/bin/c++ --driver-mode=g++ -pipe -resource-dir=/usr/lib/clang/11.0.0\n"
```

The logs just then continue as the last one "ASTWorker building file...."

### Expected behaviour

That it works. Ever command seems to result in `stderr`.

### Health check
Checkhealth result
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: cmake: configuration checked.
```

Thank you very much in advance for any help.

P.S: Just so you know I come from `coc.nvim` where I didn't have any problems, so I don't think it comes from my workspace  build/configuration.

**Comment by mjlbach** [comment]
You can ignore `stderr`, it's just logging all of the messages to stderr (it's not implying there is an error). What exactly is the issue?

**Comment by BigfootN** [comment]
Thank you very much for your quick answer.

> When you say you don't have autocompletion, did you install completion.nvim and set it up?

No, and if it's the problem, why isn't it mentioned in the docs ?

Thank you very much in advance.

**Comment by mjlbach** [comment]
We never said we support auto-completion, so I don't see why we would put this in the readme. We support completion via overriding omnifunc which is in the docs. You need to rely on an external plugin. Completion.nvim has the tightest support, but mu-complete and deooplete also have options which use the lsp results.

**Comment by BigfootN** [comment]
Thank you very much for your time and help :+1:

**Comment by mjlbach** [comment]
Of course :) Sorry for the confusion, hopefully the wiki entry is enough, but if this comes up maybe I'll add something explicit to the docs. I try not to mention external plugins since this is a "core" feature (and core doesn't have autocomplete yet), but I realize that autocomplete is almost an expectation with language servers. That being said, completion.nvim is probably what the implementation would be if it was in core :)
