### ISSUE TITLE
Error message every time I open a file with an installed language server

### ISSUE THREAD

**Issue by atticusmatticus** [neovim/nvim-lspconfig#696]
- `nvim --version`: 
NVIM v0.5.0-dev+nightly
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201210-50061-7it2db/build/config -I/tmp/neovim-20201210-50061-7it2db/src -I/usr/local/include -I/tmp/neovim-20201210-50061-7it2db/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201210-50061-7it2db/build/src/nvim/auto -I/tmp/neovim-20201210-50061-7it2db/build/include

- nvim-lsp version(commit hash):
Not sure how to generate this but I did a :PlugUpdate 2020-01-24 and the error is still occurring.

- What language server (If the problem is related to a specific language server):
  (seems to happen with all of them)
  Configured servers: clangd, rnix, texlab, bashls, vimls, fortls, r_language_server, jedi_language_server

- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
No

- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
Yes, all LSs seem to be effected.

- Is the problem isolated to a particular language server:
No.

- Operating system/version:
macOS Big Sur 11.1

### How to reproduce the problem from neovim startup
Open any file that has an installed LS in Neovim. An error message appears in the status line at the bottom.

### Actual behaviour
Error message when the file is of a type with an installed LS is the following:
Error detected while processing BufEnter Autocommands for "<buffer=1>":
E5108: Error executing lua [string ":lua"]:44: attempt to call field 'nvim_multiline_command' (a nil value)

### Expected behaviour
For there not to be an error message.

### Health check
<details>
<summary>Checkhealth result</summary>

NOTE: If opening a python file in a conda environment with Jedi installed I get this...
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: rnix: configuration checked.
  - INFO: texlab: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: fortls: configuration checked.
  - INFO: r_language_server: configuration checked.
  - INFO: jedi_language_server: configuration checked.

NOTE: If opening a non-python file not in the conda environment with Jedi installed I get...
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: clangd: configuration checked.
  - INFO: rnix: configuration checked.
  - INFO: texlab: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: vimls: configuration checked.
  - INFO: fortls: configuration checked.
  - INFO: r_language_server: configuration checked.
  - ERROR: jedi_language_server: The given command "jedi-language-server" is not executable.

</details>

### LSP log

<details>
<summary>Log file</summary>

That won't generate a log in that location... 
</details>

**Comment by mjlbach** [comment]
nvim_multiline_command was removed from nvim-lspconfig. So it must be used in your config or in another plugin.

**Comment by mjlbach** [comment]
use vim.api.nvim_exec instead:

```lua    
vim.api.nvim_exec([[
      hi LspReferenceRead cterm=bold ctermbg=red guibg=LightYellow
      hi LspReferenceText cterm=bold ctermbg=red guibg=LightYellow
      hi LspReferenceWrite cterm=bold ctermbg=red guibg=LightYellow
      augroup lsp_document_highlight
        autocmd!
        autocmd CursorHold <buffer> lua vim.lsp.buf.document_highlight()
        autocmd CursorMoved <buffer> lua vim.lsp.buf.clear_references()
      augroup END
    ]], false)
```

**Comment by mjlbach** [comment]
Also please follow the issue template in the future, I don't have your init.vim (or a minimal one thereof) otherwise I could more easily identify where the call would be (plugin or otherwise)

**Comment by atticusmatticus** [comment]
Yes vim.api.nvim_exec fixed it. Thank you!

Oh I see. I tried running the minimal_init from the curl command but it didn't work. I forgot to paste my own. My bad.

Thanks for the quick help!

**Comment by mjlbach** [comment]
No worries, it just makes my life easier 😆 

Glad we could resolve the issue quickly!
