### ISSUE TITLE
Remove "LspInstall" editor command

### ISSUE THREAD

**Issue by anott03** [neovim/nvim-lspconfig#697]
It might by time to remove the `LspIsntall` command. I understand why it's still there and providing the deprecation notice, but maybe consider removing it?

I do have a reason I personally would like it gone... I'm working on a replacement extension ([anott03/nvim-lspinstall](https://github.com/anott03/nvim-lspinstall)) and would like to make `LspInstall` an available command. I know I could override it with `!command`, but that requires that the user install lspinstall after they install lspconfig, and that makes things more complicated than I would like.

**Comment by mjlbach** [comment]
Sure, see the linked PR. I'll add your plugin to the wiki. I would recommend checking out the old installers we had before the purge.

**Comment by anott03** [comment]
@mjlbach cool thanks for the tip! I'll take a look at the old code.

**Comment by mjlbach** [comment]
Basically everything removed here: https://github.com/neovim/nvim-lspconfig/pull/498/files
