### ISSUE TITLE
Format on save

### ISSUE THREAD

**Issue by tiagovla** [neovim/nvim-lspconfig#699]
```
nvim --version: NVIM v0.5.0-dev+1022-g77a6049e0
nvim-lsp version(commit hash): 9f3fee22
language server: efm-langserver
operating system/version: linux
```
Is there a way to save the formatted version saving the buffer only once?
It's not really related, but I couldn't find a solution anywhere. 

Example settings:
```lua
    -- Set some keybinds conditional on server capabilities
    if client.resolved_capabilities.document_formatting then
        buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
    elseif client.resolved_capabilities.document_range_formatting then
        buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
    end
```
I attempted to make it format on save:
```lua
    if client.resolved_capabilities.document_formatting then
        vim.cmd [[augroup Format]]
        vim.cmd [[autocmd! * <buffer>]]
        vim.cmd [[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]]
        vim.cmd [[augroup END]]
    end
```
It does format it, but then I need to save it again.

**Comment by mjlbach** [comment]
This isn't an issue but a usage question, and we have enabled github discussions for this. You should try using BufWritePre instead of BufWritePost, or have the autocmd automatically call buf save after

**Comment by agnipau** [comment]
> ```
> nvim --version: NVIM v0.5.0-dev+1022-g77a6049e0
> nvim-lsp version(commit hash): 9f3fee22
> language server: efm-langserver
> operating system/version: linux
> ```
> 
> Is there a way to save the formatted version saving the buffer only once?
> It's not really related, but I couldn't find a solution anywhere.
> 
> Example settings:
> 
> ```lua
>     -- Set some keybinds conditional on server capabilities
>     if client.resolved_capabilities.document_formatting then
>         buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
>     elseif client.resolved_capabilities.document_range_formatting then
>         buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
>     end
> ```
> 
> I attempted to make it format on save:
> 
> ```lua
>     if client.resolved_capabilities.document_formatting then
>         vim.cmd [[augroup Format]]
>         vim.cmd [[autocmd! * <buffer>]]
>         vim.cmd [[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]]
>         vim.cmd [[augroup END]]
>     end
> ```
> 
> It does format it, but then I need to save it again.

If you use `BufWritePre` and `formatting_sync`, it works.

```lua
vim.cmd [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]]
```

**Comment by csy19960309** [comment]
> > ```
> > nvim --version: NVIM v0.5.0-dev+1022-g77a6049e0
> > nvim-lsp version(commit hash): 9f3fee22
> > language server: efm-langserver
> > operating system/version: linux
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is there a way to save the formatted version saving the buffer only once?
> > It's not really related, but I couldn't find a solution anywhere.
> > Example settings:
> > ```lua
> >     -- Set some keybinds conditional on server capabilities
> >     if client.resolved_capabilities.document_formatting then
> >         buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
> >     elseif client.resolved_capabilities.document_range_formatting then
> >         buf_set_keymap("n", "<space>f", "<cmd>lua vim.lsp.buf.formatting()<CR>", opts)
> >     end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I attempted to make it format on save:
> > ```lua
> >     if client.resolved_capabilities.document_formatting then
> >         vim.cmd [[augroup Format]]
> >         vim.cmd [[autocmd! * <buffer>]]
> >         vim.cmd [[autocmd BufWritePost <buffer> lua vim.lsp.buf.formatting()]]
> >         vim.cmd [[augroup END]]
> >     end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It does format it, but then I need to save it again.
> 
> If you use `BufWritePre` and `formatting_sync`, it works.
> 
> ```lua
> vim.cmd [[autocmd BufWritePre <buffer> lua vim.lsp.buf.formatting_sync()]]
> ```

This workaround has been OK until the Neovim version gets to 6.0, and usually when I save I get this:

`Error detected while processing BufWritePre Autocommands for "<buffer=1>":
E5108: Error executing lua ...cal/nvim-linux64/share/nvim/runtime/lua/vim/lsp/util.lua:414: start is higher than end
stack traceback:
        [C]: in function 'nvim_buf_set_text'
        ...cal/nvim-linux64/share/nvim/runtime/lua/vim/lsp/util.lua:414: in function 'apply_text_edits'
        ...ocal/nvim-linux64/share/nvim/runtime/lua/vim/lsp/buf.lua:182: in function 'formatting_sync'`
