### ISSUE TITLE
ccls: remove inaccurate vscode client initialization options from docgen

### ISSUE THREAD

**Issue by cdelledonne** [neovim/nvim-lspconfig#70]
I'm having trouble figuring out how to specify initialization options for `ccls` (the only LSP server I've tested so far) using the `settings` key. Say I want `ccls.cache.directory` to be `/tmp/ccls-cache`, using a command switch I can achieve it like the following
```lua
local nvim_lsp = require 'nvim_lsp'
nvim_lsp.ccls.setup{
    cmd = {
        'ccls',
        '--init={"cache": {"directory": "/tmp/ccls-cache"}}'
    };
}
```

That works. I'd like to be able to do the same using the `settings` key, but I can't. For instance, neither
```lua
local nvim_lsp = require 'nvim_lsp'
nvim_lsp.ccls.setup{
    cmd = {
        'ccls'
    };
    settings = {
        ccls = {
            cache = {
                directory = "/tmp/ccls-cache";
            };
        };
    };
}
```

nor
```lua
local nvim_lsp = require 'nvim_lsp'
nvim_lsp.ccls.setup{
    cmd = {
        'ccls'
    };
    settings = {
        cache = {
            directory = "/tmp/ccls-cache";
        };
    };
}
```

work. Looking into `ccls`'s log, the cache option is not even being sent to the server when initializing it.

Am I doing something wrong?

### Environment
- NVIM v0.5.0-233-g76d1e9360

**Comment by norcalli** [comment]
That would depend on whether it's "initialization options" or "workspace configuration." This is one of my least favorite parts of the LSP protocol, which is that there are many different ways to send initial configurations to the client:

- Initialization options (`initializationOptions` sent via `initialize`) correspond to `init_options` in our system.
- Workspace configuration (`workspace/configuration` and `workspace/didChangeConfiguration`) corresponds to `settings` in our system.

Without looking into it further, I'd double check which one `ccls` is expecting.

**Comment by cdelledonne** [comment]
Indeed using `init_options` works. I guess the same holds for other options listed under `ccls` which have to be sent via `initialize`.

A side question: there are three options under `ccls.misc.<suboption>`. Why is `misc` there? I believe `ccls` only expects `<suboption>`, rather than `misc.<suboption>` (e.g, [`compilationDatabaseDirectory`](https://github.com/MaskRay/ccls/wiki/Customization#compilationdatabasedirectory)).

**Comment by norcalli** [comment]
Those values are scraped directly from the package.json in the vscode extension. I guess that it's impossible to know if they are init_options or settings, but they are things that the `ccls-project.ccls` extension defines, so they are definitely real. I can't really say more than that.

**Comment by cdelledonne** [comment]
Got it, thanks. Feel free to close the issue, but I feel the README is a little confusing.

**Comment by norcalli** [comment]
I'm going to leave it open as a reminder to improve the README :P

**Comment by wheelsandmetal** [comment]
I also found this confusing

This is what I thought the docs were telling me to do
```lua
nvim_lsp.ccls.setup{
  settings = {
    ccls = {
      misc = {     
	compilationDatabaseDirectory = "build"
      }
    }
  }
}
```

And this is what I actually needed
```lua
nvim_lsp.ccls.setup{
  init_options = {
	compilationDatabaseDirectory = "build"
  }
}
```

**Comment by mjlbach** [comment]
@cdelledonne Can you look at #528, I tried to make it clear the customization for ccls is all set via on_init. Many servers are inconsistent with whether configuration is done via settings/init options, so I think the best thing we can do is just have good documentation for each one.

**Comment by cdelledonne** [comment]
@mjlbach the improved documentation with the example is a nice additions, thanks!

However, I can still see the following in CONFIG.md, is that outdated or am I missing something?
https://github.com/neovim/nvim-lspconfig/blob/384e512a640b2b18f3d2c3e9dcb6e870814ed1eb/CONFIG.md#L164

**Comment by mjlbach** [comment]
Ah, you are correct. Docgen automatically adds that https://github.com/neovim/nvim-lspconfig/blob/384e512a640b2b18f3d2c3e9dcb6e870814ed1eb/scripts/docgen.lua#L152

Not sure the best thing to do about that, it should probably be removed and manually added to each server.

Other than removing that, is there anything you would improve?

**Comment by cdelledonne** [comment]
I do have one more question: the example shows how to set the `compilationDatabaseDirectory`

```lua
init_options = { 
    compilationDatabaseDirectory = "build";
    ...
}
```

but the list of options presents it as `ccls.misc.compilationDatabaseDirectory`. Why isn't the options set as follows?
```lua
init_options = { 
    misc = {
        compilationDatabaseDirectory = "build";
    };
    ...
}
```

Do all `misc` options fall directly under `init_options`?

**Comment by mjlbach** [comment]
Does that work for you? I might just remove the package.json for ccls.

I was going by the entry here which isn't nested under misc:
https://github.com/MaskRay/ccls/wiki/Customization#compilationdatabasedirectory

**Comment by mjlbach** [comment]
I'm guessing their package.json is just wrong:

 https://github.com/MaskRay/ccls/blob/a2d2fd8167c17aec3a9711916d4f5c7a031cd769/src/project.cc#L358

https://github.com/MaskRay/ccls/blob/1dc69f45dc3e0c0f750f5a2e220a6aea54f30d2a/src/messages/initialize.cc#L278

**Comment by mjlbach** [comment]
Oh, they remap misc.compilationDatabaseDirectory to compilationDatabaseDirectory when it's sent from the client (vscode-ccls) to the server (ccls) here: https://github.com/MaskRay/vscode-ccls/blob/456f21ebf3013abbc553442dd81610f1595310f5/src/serverContext.ts#L148-L155.

The documentation would be accurate if we were using the vscode client (which of course, we aren't), but we're scraping the settings from the vscode client which explains why the remapped settings are showing up in the documentation. I'm just going to remove them, because it seems like a common source of confusion.
