### ISSUE TITLE
[Pyright] Is there a way to sort auto completion results?

### ISSUE THREAD

**Issue by hungrybirder** [neovim/nvim-lspconfig#704]
Hi,
The `Nvim-lspconfig`  is awesome! 
And I got a problem.

When I set `Pyright` with `Nvim-lspconfig`, the auto completion results are not what I expect. 

<img width="502" alt="image" src="https://user-images.githubusercontent.com/1021047/106346084-78e65980-62ef-11eb-96fb-fb1155e696c1.png">

I wanna move the `Python magic method` to tail of the completion results.
`coc-pyright` did a good job.
<img width="442" alt="image" src="https://user-images.githubusercontent.com/1021047/106346096-99aeaf00-62ef-11eb-94c8-66dbd9383191.png">

so, how can I set up config for this.

Thank you.

Some Info:
pyright 1.1.106
NVIM v0.5.0-dev+d9c1586e4
Nvim-lspconfig: 8c68dc78d00f
MacOS 11.1

**Comment by mjlbach** [comment]
Is this with omnicomplete or completion.nvim? This isn't really an issue with nvim-lspconfig fyi, since the completion candidate list is generated in core.

**Comment by hungrybirder** [comment]
> Is this with omnicomplete or completion.nvim? This isn't really an issue with nvim-lspconfig fyi, since the completion candidate list is generated in core.

Yes, you are right. 

It works for me when I update my init.vim with `let g:completion_sorting = "none"`.

Thank you.

I close this issue.

**Comment by mjlbach** [comment]
> It works for me when I update my init.vim with let g:completion_sorting = "none".

You read my mind 😆 

Glad you got it figured out and hope you enjoy lsp!
