### ISSUE TITLE
not working for javascriptreact :(

### ISSUE THREAD

**Issue by siddhantk232** [neovim/nvim-lspconfig#705]
- `nvim --version`: v0.5.0-dev+1056-gad98b8400
- nvim-lsp version(commit hash): 78a31c0
- What language server (If the problem is related to a specific language server): tsserver
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): haven't tried.
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): haven't tried.
- Is the problem isolated to a particular language server: yes.
- Operating system/version: Arch Linux (Linux kernel version 5.10.9)

### Actual behaviour

The lsp client is loaded for a typescript project but does not work in a javascript (react) project.

### Expected behaviour

The tsserver lsp client should load in the javascript workspace also as the workspace has the required files specified in tsserver [default](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#tsserver) config's root_pattern. On running `:LspInfo` it shows that tsserver matches for this filetype (`javascriptreact`) but 0 clients are attached.

screenshot of `:LspInfo`

![Screenshot from 2021-01-30 18-23-11](https://user-images.githubusercontent.com/36407043/106356801-4c026880-6328-11eb-8460-41fe5c5726c3.png)

the project structure is:

```
.
├── crowdin.yml
├── Dockerfile
├── LICENSE
├── nginx.conf
├── node_modules
├── package.json
├── public
├── README.md
├── schema.json
├── src
└── yarn.lock
```

### Minimal init.vim or init.lua and code sample

This is all my lsp config has:

```viml

call plug#begin('~/.vim/plugged')

" Neovim lsp Plugins
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
Plug 'tjdevries/nlua.nvim'
Plug 'tjdevries/lsp_extensions.nvim'

call plug#end()



nnoremap <leader>ld :lua vim.lsp.buf.definition()<CR>
nnoremap <leader>li :lua vim.lsp.buf.implementation()<CR>
nnoremap <leader>lsh :lua vim.lsp.buf.signature_help()<CR>
nnoremap <leader>lrr :lua vim.lsp.buf.references()<CR>
nnoremap <leader>lrn :lua vim.lsp.buf.rename()<CR>
nnoremap <leader>lh :lua vim.lsp.buf.hover()<CR>
nnoremap <leader>lca :lua vim.lsp.buf.code_action()<CR>

let g:completion_matching_strategy_list = ['exact', 'substring', 'fuzzy']
lua require'lspconfig'.tsserver.setup{ on_attach=require'completion'.on_attach }
lua require'lspconfig'.gopls.setup{ on_attach=require'completion'.on_attach }


autocmd BufEnter * lua require'completion'.on_attach()
```

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: tsserver: configuration checked.
  - INFO: gopls: configuration checked.

health#completion_nvim#check
========================================================================
## general
  - OK: neovim version is supported

## completion source
  - OK: all completion sources are valid

## snippet source
  - INFO: You haven't set up any snippet source

health#nvim_treesitter#check
========================================================================
## Installation
  - OK: `git` executable found.
  - OK: `cc` executable found.

## c parser healthcheck
  - OK: c parser found.
  - OK: `highlights.scm` found.
  - OK: `locals.scm` found.
  - OK: `folds.scm` found.
  - OK: `indents.scm` found.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.9 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 3:
          /usr/bin/python3 does not have the "neovim" module. :help |provider-python|
          python3.10 not found in search path or not executable.
          /usr/bin/python3.9 does not have the "neovim" module. :help |provider-python|
          python3.8 not found in search path or not executable.
          python3.7 not found in search path or not executable.
          python3.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v15.5.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - "Neovim::Ext" cpan module is not installed

</details>

### LSP log

<details>
<summary>Log file</summary>

[ ERROR ] 2021-01-30T15:48:07+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:375 ]	"[tsserver] npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/types-registry failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org\nnpm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.\n"

[ ERROR ] 2021-01-30T15:50:16+0530 ] /usr/share/nvim/runtime/lua/vim/lsp/handlers.lua:375 ]	"[tsserver] npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/types-registry failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org\nnpm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.\n"

[ WARN ] 2021-01-30T17:27:52+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:87 ]	"method textDocument/hover is not supported by any of the servers registered for the current buffer"
[ WARN ] 2021-01-30T17:29:13+0530 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:87 ]	"method textDocument/hover is not supported by any of the servers registered for the current buffer"

</details>

**Comment by mjlbach** [comment]
Can you increase the verbosity of the log? (use "info" instead of "debug"), clear it, and repost?

**Comment by mjlbach** [comment]
Also you may need typescript installed even for a pure javascript project for tsserver to work. I"m not able to reproduce your issue.

<img width="1280" alt="Screen Shot 2021-01-30 at 4 23 14 PM" src="https://user-images.githubusercontent.com/13316262/106371309-cd9dca80-6317-11eb-9be7-15e8d8cc07db.png">
<img width="1280" alt="Screen Shot 2021-01-30 at 4 23 20 PM" src="https://user-images.githubusercontent.com/13316262/106371310-d0002480-6317-11eb-88ee-5d5b33410a10.png">

**Comment by siddhantk232** [comment]
oh, it worked! I just had to add typescript as a global dependency. Thanks for your help @mjlbach .

**Comment by Gowtham-dev369** [comment]
i am having same problem but sserver works on .tsx and .jsx but not in .js file
