### ISSUE TITLE
[gopls] MethodNotFound when opening a file

### ISSUE THREAD

**Issue by urandom** [neovim/nvim-lspconfig#708]
- `nvim --version`:
- nvim-lsp version(commit hash):
- What language server (If the problem is related to a specific language server):
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
- Is the problem isolated to a particular language server:
- Operating system/version:

NVIM v0.5.0-828-g0a95549d6
nvim-lspconfig: 0fb7112

This appears to be a problem with gopls

### How to reproduce the problem from neovim startup

Open a go file.

### Actual behaviour
```
LSP[gopls] Error loading workspace folders (expected 1, got 0)                                                  
failed to load view for file://MODULE_DDIR: failed to get workspace configuration from client (file://MODULE_DIR): MethodNotFound
```

### Expected behaviour

No error should appear.

Going back to an older commit like 49f64e4 fixes the problem

### Minimal init.vim or init.lua and code sample

<details>
lua <<EOF
  local lspconfig = require('lspconfig')

  local on_attach = function(client, bufnr)
    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
  end

  local capabilities = lsp_status.capabilities
  capabilities.textDocument.completion.completionItem.snippetSupport = true

  -- vimls, 
  local servers = {'rust_analyzer', 'tsserver',  'ccls', 'bashls', 'texlab',  'jdtls'} -- 'sumneko_lua',
  for _, lsp in ipairs(servers) do
    lspconfig[lsp].setup {
      on_attach = on_attach,
      capabilities = capabilities,
    }
  end
  lspconfig['gopls'].setup {
    cmd = {"gopls", "-logfile=/tmp/gopls.log"}, -- , "-rpc.trace", "--remote=auto"},
    init_options = {completeUnimported = true}, -- ,  usePlaceholders = true
    on_attach = on_attach,
    capabilities = capabilities,
  }
  lspconfig['jsonls'].setup {
    cmd = {"json-languageserver"},
    on_attach = on_attach,
    capabilities = capabilities,
  }
  lspconfig['pyls_ms'].setup {
    cmd = {"pyls"},
    on_attach = on_attach,
    capabilities = capabilities,
  }

  vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
      -- delay update diagnostics
      update_in_insert = false,
    }
  )
EOF

</details>

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - ERROR: jdtls: config.cmd error, /usr/share/nvim/runtime/lua/vim/lsp.lua:173: cmd: expected list, got nil
    stack traceback:
    /usr/share/nvim/runtime/lua/vim/lsp.lua:173: in function </usr/share/nvim/runtime/lua/vim/lsp.lua:172>
    [C]: in function 'pcall'
    ...fig/nvim/plugged/nvim-lspconfig/lua/lspconfig/health.lua:11: in function 'check_health'
    [string ":lua"]:1: in main chunk
  - INFO: jsonls: configuration checked.
  - INFO: pyls_ms: configuration checked.
  - INFO: ccls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: texlab: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - INFO: bashls: configuration checked.
  - INFO: gopls: configuration checked.

</details>

### LSP log

<details>
<summary>Log file</summary>

</details>

**Comment by mjlbach** [comment]
Your neovim nightly version is very old. Please update, clear you log, set the log level to "trace" and report back.

**Comment by urandom** [comment]
It looks like the 'nightly' git tag was out of date. Updating to HEAD fixed the problem
