### ISSUE TITLE
Rust-Analyzer's diagnostics not updating on Windows 

### ISSUE THREAD

**Issue by sp1n0r** [neovim/nvim-lspconfig#709]
- `nvim --version`: `NVIM v0.5.0-dev+1059-g55add1c1c`
- nvim-lsp version(commit hash): `0fb71129de54577254a3ae143850d11b6902a279`
- What language server (If the problem is related to a specific language server): Rust_Analyzer
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): I don't use others
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): I don't use it
- Is the problem isolated to a particular language server: Yes
- Operating system/version: Windows 10

### How to reproduce the problem from neovim startup
1. `nvim -u minimal.vim`
2. `!cargo new rust_project_name`
3. `e (...)/main.rs` 
4. do something similar to the demo video I attached
(PS: I prerecorded the video using my actual config, thus the colorscheme and lightline. But I assure that using my minimal.vim exactly the same happens)

![rust_analyzer_test](https://user-images.githubusercontent.com/74260683/106669675-ec17f600-65a3-11eb-9b30-638e8a935966.gif)

### Actual behaviour
Diagnostics aren't updating properly.

### Expected behaviour
Diagnostics should update on save instead of having to exit and reload nvim.

### Minimal init.vim or init.lua and code sample
```
E5113: Error while calling lua chunk: minimal_init.lua:10: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
Press ENTER or type command to continue
```
I'm on Windows and I have never used packer.nvim in my life so I have no idea why it's giving me a directory error, but I have reproduced the error using only a minimal config with plug.nvim.
```
call plug#begin('~/AppData/Local/nvim/autoload')
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-lua/completion-nvim'
call plug#end()

" --- Define mapleader for keymaps --------------------------------------"
let mapleader = ' '

" RUST_ANALYZER
lua require'lspconfig'.rust_analyzer.setup{ cmd={"rust-analyzer-windows.exe"} }

" Keymaps
nnoremap <silent>gD          :lua vim.lsp.buf.declaration()<CR>
nnoremap <silent>gd          :lua vim.lsp.buf.definition()<CR>
nnoremap <silent><leader>gk  :lua vim.lsp.buf.hover()<CR>
nnoremap <silent><leader>gr  :lua vim.lsp.buf.rename()<CR>
nnoremap <silent><leader>gR  :lua vim.lsp.buf.references()<CR>
nnoremap <silent><leader>gp  :lua vim.lsp.diagnostic.goto_prev()<CR>
nnoremap <silent><leader>gn  :lua vim.lsp.diagnostic.goto_next()<CR>

autocmd BufEnter * lua require'completion'.on_attach()
let g:completion_confirm_key = '<CR>'
let g:completion_enable_auto_paren = 0
let g:completion_matching_strategy_list =
      \ ['exact', 'substring', 'fuzzy', 'all']

set termguicolors
set background=dark

" --- Disable recommended styles ----------------------------------------"
let g:python_recommended_style = 0
let g:rust_recommended_style = 0

" --- Set g:python3_host_prog -------------------------------------------"
let g:python3_host_prog=
      \'~/AppData/Local/Programs/Python/Python38/python.exe'

" --- Time format language ----------------------------------------------"
language time en_us

" --- Global settings ---------------------------------------------------"
set nowrap
set clipboard=unnamed
set noerrorbells
set nocursorline
set tabstop=2 softtabstop=2
set shiftwidth=2
set expandtab
set smartindent
set nu rnu
set nohls
set ignorecase
set smartcase
set noswapfile
set nobackup
set undofile
set textwidth=80
set colorcolumn=+1
set updatetime=100
set completeopt=menuone,noinsert,noselect
set shortmess+=c
set laststatus=2
set guicursor=a:block-Cursor

" --- Mouse options -----------------------------------------------------"
set mouse=a
behave xterm

nnoremap <leader>w :w<CR>

" --- Window handling ---------------------------------------------------"
nnoremap <silent><leader>h :wincmd h<CR>
nnoremap <silent><leader>j :wincmd j<CR>
nnoremap <silent><leader>k :wincmd k<CR>
nnoremap <silent><leader>l :wincmd l<CR>
nnoremap <silent><leader>x :wincmd c<CR>
nnoremap <silent><leader>r :wincmd r<CR>
nnoremap <silent><leader>T :wincmd T<CR>
nnoremap <silent><leader>= :wincmd =<CR>
nnoremap <silent><leader>o :wincmd o<CR>
nnoremap <silent><leader>sv :wincmd v<CR>
nnoremap <silent><leader>sh :wincmd s<CR>
" Split Resizing
nnoremap <silent> <leader>+ :vertical resize +5<CR>
nnoremap <silent> <leader>- :vertical resize -5<CR>
nnoremap <silent> <A-+> :resize +2<CR>
nnoremap <silent> <A--> :resize -2<CR>

" --- Scroll up/down with keys ------------------------------------------"
nnoremap <silent><C-j> <C-e>
nnoremap <silent><C-k> <C-y>
" 5x FASTER
nnoremap <silent><A-j> 5<C-e>
nnoremap <silent><A-k> 5<C-y>

" --- Scroll left/right with keys ---------------------------------------"
nnoremap <C-h> 3zh
nnoremap <C-l> 3zl

" --- Move lines up/down ------------------------------------------------"
nnoremap <silent><A-s> :m .+1<CR>==
nnoremap <silent><A-w> :m .-2<CR>==
inoremap <silent><A-s> <Esc>:m .+1<CR>==gi
inoremap <silent><A-w> <Esc>:m .-2<CR>==gi
vnoremap <silent><A-s> :m '>+1<CR>gv=gv
vnoremap <silent><A-w> :m '<-2<CR>gv=gv

" --- Tab handling ------------------------------------------------------"
nnoremap <silent><leader>tc :tabc<CR>
nnoremap <silent><leader>tn :tabn<CR>
nnoremap <silent><leader>tp :tabp<CR>
```

### Health check
<details>
<summary>Checkhealth result</summary>

```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.
```
</details>

### LSP log

<details>
<summary>Log file</summary>

It doesn't log anything.
</details>

**Comment by mjlbach** [comment]
I've never used rust on Windows before. Following the rust-analyzer instructions, I managed to get to set everything up:

![image](https://user-images.githubusercontent.com/13316262/106675447-f61d0300-6569-11eb-9b9b-3ac85c8b4d7f.png)


This seems like a configuration issue on your end, and you should ask in our discussions forum for rust-analyzer.

**Comment by mjlbach** [comment]
Oh, and my diagnostics update fine

**Comment by mjlbach** [comment]
Of note, the reason we ask for:

```
Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): I don't use others
Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): I don't use it
Is the problem isolated to a particular language server: Yes
```
Is not to survey users, but to ensure the problem is isolated to neovim's language server. The first step I would ask you to do to debug your config would be to try an alternate client and see if the issue reproduces.

**Comment by mjlbach** [comment]
Oh, I see your problem. I think this is a rust-analyzer issue.

**Comment by mjlbach** [comment]
FYI when I try to use the vscode rust-analyzer extension, I get frequent rust-analyzer crahses:

```
The Rust Analyzer server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

**Comment by sp1n0r** [comment]
Sorry for not presenting the issue properly, the reason is actually that currently I have no access to wifi, so I'm trying to use the least amount of mobile data. So for now I'll present the log but if that information doesn't suffice I'll do the rest later (like trying other servers, etc.)

log: https://paste.sh/4J4qX2vk#w8u6A8YfX-b8ImnGQfMGoclG
(since it was gigantic I pasted it there)

**Comment by sp1n0r** [comment]
Since I already had the necessary components I went and tried rls and it works fine. The problem seems to be rust_analyzer related I guess

**Comment by sp1n0r** [comment]
I should open an issue in Rust_Analyzer.... @mjlbach I'll close this, if you still think it could be related to lspconfig reopen it please

**Comment by mjlbach** [comment]
I'll keep an eye, but you should create an issue in the rust-analyzer repo and link it here so others can follow. I don't use Windows regularly so won't be able to actively test.

**Comment by sp1n0r** [comment]
Alright thank you :)

**Comment by sp1n0r** [comment]
@mjlbach still nothing on rust-analyzer's repo. Should I do some other testing or something else?

**Comment by mjlbach** [comment]
What are you asking? I can't fix it here, and I don't have time to dig into the rust-analyzer codebase and fix it there.

**Comment by sp1n0r** [comment]
Okay
