### ISSUE TITLE
Omnisharp doesn't work properly

### ISSUE THREAD

**Issue by cas1no** [neovim/nvim-lspconfig#713]
Everything works fine, except goto definition, perhaps the problem is that omnisharp uses `-lsp` flag, but should use `-s` as in `OmniSharp/omnisharp-vim`.

**Comment by mjlbach** [comment]
Works for me with the settings in config.md

https://user-images.githubusercontent.com/13316262/106802151-66ce2900-6617-11eb-93aa-b0f94041c809.mov

**Comment by mjlbach** [comment]
Duplicate of https://github.com/neovim/neovim/issues/13827
