### ISSUE TITLE
elmls behavior extremely erratic/completely broken

### ISSUE THREAD

**Issue by kwshi** [neovim/nvim-lspconfig#714]
BTW, I also filed an issue under elm-tooling/elm-language-server#503 for the same problem, since I'm not sure whether the problem is with nvim-lspconfig or elm-language-server.  So far, the problem is unique to the exact combination elm-language-server + nvim-lspconfig.

Also, a sample project source with init.vim & a Dockerfile setting up a minimal Neovim install with nvim-lspconfig, elm, elm-language-server, etc., reproducing the issue can be found here:
https://github.com/kwshi/bug-reports/tree/main/elm-ls-nvim

- `nvim --version` (downloaded & unpacked straight from GH releases page):

  ```
  NVIM v0.5.0-dev+1062-gcc1851c9f
  Build type: RelWithDebInfo
  LuaJIT 2.1.0-beta3
  Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
  Compiled by runner@fv-az175-847

  Features: +acl +iconv +tui
  See ":help feature-compile"

     system vimrc file: "$VIM/sysinit.vim"
    fall-back for $VIM: "/share/nvim"

  Run :checkhealth for more info
  ```

- nvim-lsp version(commit hash): As of writing, master, or 2eb8567
- What language server (If the problem is related to a specific language server): `elmls`
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): Nope. Tried with coc.nvim & behavior was totally normal.
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): Also nope.  My other language servers work normally.
- Is the problem isolated to a particular language server: Yes.
- Operating system/version: Void Linux, but I've also reproduced it in an Ubuntu Dockerfile, so it's likely not OS-specific.

### How to reproduce the problem from neovim startup
Literally make any edits to an Elm file.

### Actual behaviour
On opening a new Elm buffer, LSP behaves fairly normally (type checking works, diagnostics make sense, whatever). After a couple normal editing operations (delete some text, add some text), it appears elm-language-server's internal model of the buffer contents becomes totally malformed, and elm-language-server starts complaining about random, bogus parsing errors & spitting out nonsense diagnostics. Here are some sample error messages it gives:

- `No definition found for 'mport '.`
- `Parsing error.` (on what should be totally valid Elm code)
- `Could not find a module to import named 'String ' in `...
- `Unused pattern variable '='`
- `A value named 'nt' is already defined` (in code that does not define any nt, only uses Int in a type signature).

### Expected behaviour
Normal LSP operation, not nonsense.

### Minimal init.vim or init.lua and code sample
```vim
" init.vim
call plug#begin()
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua << EOF 
require'lspconfig'.elmls.setup{}
EOF 
```

Code sample is created by running `elm init`, saying yes to prompts, and then making a `src/Main.elm` with contents
```
module Main exposing (..)

main : String
main =
    "hello"

f : Int -> Int
f = 3
```

No errors will be shown upon opening the file, but try making some edits (e.g., `import Browser` or some other module, then delete the `f` definition+declaration, then add some line comments here and there), and you'll see what I mean.

### Health check
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: elmls: configuration checked.
```

### LSP log

http://ix.io/2OhE

**Comment by mjlbach** [comment]
As this happens with coc, lets just keep the upstream issue open. I'll comment and watch it, but it seems like this is an issue with elmls rather than the configuration we are sending to the server (which is the only part of neovim's language server client this repo deals with)
