### ISSUE TITLE
help wanted for powershell server

### ISSUE THREAD

**Issue by jmwatte** [neovim/nvim-lspconfig#729]
Not so good at Lua, I guess, but when I put [[....]] and everything between it  

`
cmd={[["C:/Program Files/PowerShell/7/pwsh.exe" -NoLogo -NoProfile -ExecutionPolicy RemoteSigned -File "C:/users/jmwinters/.vscode/extensions/ms-vscode.powershell-2020.6.0/modules/PowerShellEditorServices/Start-EditorServices.ps1" -HostName nvim -HostProfileId 0 -HostVersion 1.0.0 -LogPath "C:/users/jmwinters/Desktop/pses.log.txt" -LogLevel Diagnostic -BundledModulesPath "C:/users/jmwinters/.vscode/extensions/ms-vscode.powershell-2020.6.0/modules" -Stdio -SessionDetailsPath "C:/users/jmwinters/Desktop/.pses_session"]]}
`

in an online lua coder and I paste the output straight into a cmd prompt in windows 10, it starts up the service.  But when I use it like above to configure the server it , I get this checkhealth message ...

`
## Checking language server protocol configuration
  - INFO: vimls: configuration checked.
  - ERROR: powershell_lsp: The given command "C:/Program Files/PowerShell/7/pwsh.exe -NoLogo -NoProfile -ExecutionPolicy RemoteSigned -File \"C:/users/jmwinters/.vscode/extensions/ms-vscode.powershell-2020.6.0/modules/PowerShellEditorServices/Start-EditorServices.ps1\" -HostName nvim -HostProfileId 0 -HostVersion 1.0.0 -LogPath \"C:/users/jmwinters/Desktop/pses.log.txt\" -LogLevel Diagnostic -BundledModulesPath \"C:/users/jmwinters/.vscode/extensions/ms-vscode.powershell-2020.6.0/modules\" -Stdio -SessionDetailsPath \"C:/users/jmwinters/Desktop/.pses_session\"" is not executable.

`
Not executable... So.... something gets lost in translation, I guess. Checked the shell and it is cmd.exe on windows 10. Any help would be appreciated.

**Comment by jmwatte** [comment]
Didn't want the bug label there. Help label, maybe...

**Comment by mjlbach** [comment]
This belongs in the discussion forum. Command needs to be a table, where each entry in the table is either a binary path (the first) or argument to the binary path. You have spaces, which is why the executable check fails.

**Comment by sakhnik** [comment]
Any plans to include PS support out of the box?

**Comment by mjlbach** [comment]
Sure, I'll accept a PR
