### ISSUE TITLE
[Request] I want you to add a function to close the hover.

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/nvim-lspconfig#730]
Currently, it looks like it closes when you move the cursor after displaying the hover, but it would be nice to have a dedicated command to close the hover.

**Comment by mjlbach** [comment]
You can already do this yourself by overriding neovim a hover handler to include a key binding to close the window, toggling into the hover window and closing it with :q etc. anyways, hover is implemented in core so we can't do this in nvim-lspconfig

**Comment by nabezokodaikon** [comment]
understood. Thank you for your reply.
