### ISSUE TITLE
Add helpers for restarting, stopping, and starting language servers

### ISSUE THREAD

**Issue by dbalatero** [neovim/nvim-lspconfig#731]
Hello! I am trying to write a method to restart a failed LSP client (`client_id = 1`) when I detect a certain failure (in this case, my internal VPN dropping my connection to my LSP client, and need to restart the VPN).

This is my `:LSPInfo` output, with some redacted paths:

```
  Configured servers: sumneko_lua, flow, sorbet 
   
  0 client(s) attached to this buffer:  
   
  0 active client(s):  
   
  Clients that match the filetype ruby: 

    Config: sorbet 
    	cmd:              scripts/bin/typecheck --lsp --enable-all-experimental-lsp-features 
    	cmd is executable: True 
    	identified root:   /Users/dbalatero/<redacted>
    	custom handlers:    
```

Is there a quick way to restart an LSP client that is in a stopped state, so I can recover from failure? `:h lsp` talks a lot about starting a new client, and stopping an existing one, but there is a suspicious lack of documentation on restarting.

Thanks!

**Comment by mjlbach** [comment]
I saw your post on reddit. Right now what you'd want to do is `:e` to trigger the autocmd to reattach.

You might also look at the changes here, where you can use a new `.launch()` command
https://github.com/neovim/nvim-lspconfig/pull/721/files

**Comment by dbalatero** [comment]
Yes, the `launch()` command looks great! Let's get that thing merged :) Also when you document it in the `:h` text it would be great to add keywords near it like `restart`, `manually start`, etc for easy searching (I was really surprised to not find these!)

The `:e` solution is fine, but I also have to trigger `:w` to be safe (what if I have an unsaved buffer and my LSP server disconnects?) which feels like a weird side-effect to me! Better to explicitly just try to launch again.

At the point I'm trying to restart, the client has actually already stopped (I'm in an `on_exit` handler) so I probably just need to call `launch()` once that merges in.

Thanks!

**Comment by mjlbach** [comment]
Great, if you want to test the PR and leave a comment on the PR if it addressed your issue, then I'll merge it

**Comment by dbalatero** [comment]
@mjlbach Yes it works! I did this to restart:

```lua
require('lspconfig')["sorbet"].launch()
```

**Comment by wantyapps** [comment]
I have an idea! Maybe create a plugin for LSP, which makes a command `:LspRestart` and it will restart all the servers configured!

**Comment by mjlbach** [comment]
@dbalatero Is the documentation clear enough now with #721 merged?

**Comment by mjlbach** [comment]
Maybe we add syntactic sugar ala LspRestart, LspStart, LspStop

**Comment by akinsho** [comment]
A syntactic sugar command would be awesome, would it be buffer local e.g. stop the clients in the current buffer or take an argument like `:LspRestart sumneko_lua` which seems the most explicit and least error prone

**Comment by mjlbach** [comment]
Leaning towards:

1. No argument -> Restarts all clients currently attached to the buffer/Starts all clients that match buffer filetype/Stops all clients currently attached to the buffer
2. string -> Restarts all clients currently attached to the buffer that also match the string/Starts all clients that match buffer filetype and match the string/Stops all clients currently attached to the buffer that match the string
3. int -> Restarts all clients currently attached to the buffer that also match the  client_id/Starts all clients that match buffer filetype and match the client_id/Stops all clients currently attached to the buffer that match the client_id
4. table, recursively check 2/3

**Comment by dbalatero** [comment]
I'd push for explicit APIs that do one thing each - single functions that take an argument with a `mixed` type are harder to understand at a glance:

* `:LspRestartAll`
* `:LspRestart sumneko_lua`
* `:LspRestartClientId 1`

**Comment by dbalatero** [comment]
> @dbalatero Is the documentation clear enough now with #721 merged?

I don't believe there was a doc update?

**Comment by mjlbach** [comment]
https://github.com/neovim/nvim-lspconfig/blob/master/README.md#manually-starting-or-restarting-language-servers

**Comment by dbalatero** [comment]
Oh I see, I was expected a `:help` txt file (I encourage you to bias towards that for docs btw!) But yes that works for me!

**Comment by mjlbach** [comment]
You can see https://github.com/neovim/nvim-lspconfig/issues/367 for the request for a vimdoc help. I'm aware that some prefer it, but for me (personally), I don't like dealing with having to keep two separate sources of documentation in sync 😕
