### ISSUE TITLE
on_attach function is not provided with buffer id

### ISSUE THREAD

**Issue by svermeulen** [neovim/nvim-lspconfig#732]
- `nvim --version`:  0.5.0
- nvim-lsp version(commit hash):d3c178a
- What language server (If the problem is related to a specific language server):
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
- Is the problem isolated to a particular language server: No
- Operating system/version: Mac OSX 10.15.7

### How to reproduce the problem from neovim startup

Use the provided template for adding lsp bindings.  For example:
```
lua << EOF
local nvim_lsp = require('lspconfig')
local on_attach = function(client, bufnr)
    print("received buffer" .. bufnr)
end

-- Use a loop to conveniently both setup defined servers 
-- and map buffer local keybindings when the language server attaches
local servers = { "pyright", "rust_analyzer", "tsserver" }
for _, lsp in ipairs(servers) do
  nvim_lsp[lsp].setup { on_attach = on_attach }
end
EOF
```

### Actual behaviour

bufnr is passed as null

### Expected behaviour

bufnr is passes as the buffer id

### Health check
<details>
<summary>Checkhealth result</summary>

</details>

### LSP log

<details>
<summary>Log file</summary>

</details>

**Comment by mjlbach** [comment]
Can you try #733
