### ISSUE TITLE
rust-analyzer: search and replace

### ISSUE THREAD

**Issue by csmoe** [neovim/nvim-lspconfig#742]
SSR can be invoked in coc.nvim, is it possible to do that with nvim-lsp? (it's fine to say no as SSR is a non-official feature of LSP)

cc https://rust-analyzer.github.io/manual.html#structural-search-and-replace
```bash
rust-analyzer ssr <RULE>
```

**Comment by mjlbach** [comment]
My general thought is not to add non-spec commands, but for servers in which having a command drastically improves usability (see texlab) it's fine. If you think ssr is a very important feature, then make a PR and I'll merge it.

**Comment by csmoe** [comment]
https://github.com/rust-analyzer/rust-analyzer/pull/7874
rust-analyzer can apply ssr with lsp.code-action 🚀
