### ISSUE TITLE
Doc issue `root_dir = <function 1>` appearing in `CONFIG.md`

### ISSUE THREAD

**Issue by PhilT** [neovim/nvim-lspconfig#749]
e.g. https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#fsautocomplete and https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#gdscript

**Comment by mjlbach** [comment]
Yeah, I'm not sure what we can do about this, dumping lua functions to strings isn't particularly readable.

```lua
> string.dump(function() print "Hello World" end)
uaT�

xV(w@�=stdin���
               ��DG��print�Hello World�������_ENV
```

Maybe clever use of string.match on parsing the file directly, or using something like tree-sitter or lpeg.

**Comment by PhilT** [comment]
Would it be better to manual add the doc config for now?

**Comment by mjlbach** [comment]
I think I'm more in the camp of status quo until we fix docgen

**Comment by mjlbach** [comment]
This is now fixed, I didn't do it for the handlers, as that would be a little annoying, but now there are only 4 mentions of a numbered function in CONFIG.md. The default behavior is to fallback from the docstring  if missing to reading the file if a function is detected.

For future contributors, this could be optimized by using tree-sitter to parse the luafiles like telescope does with tree-sitter-lua. See their docgen pipeline https://github.com/tjdevries/tree-sitter-lua/pull/6/files.
