### ISSUE TITLE
Svelte Config does not Recognize Svelte Projects

### ISSUE THREAD

**Issue by seanaye** [neovim/nvim-lspconfig#752]
lspconfig is not recognizing svelte projects correctly for me. I am using the default svelte lsp setup and other language servers are working fine

relevant `init.nvim` snippet 

```lua
lua << EOF
local lspconfig = require'lspconfig'
lspconfig.tsserver.setup{}
lspconfig.dockerls.setup{}
lspconfig.gopls.setup{}
lspconfig.graphql.setup{}
lspconfig.html.setup{}
lspconfig.jsonls.setup{}
lspconfig.rls.setup{}
lspconfig.pyright.setup{}
lspconfig.vuels.setup{}
lspconfig.svelte.setup{}
EOF
```

`which svelteserver`

`>> /Users/seanaye/.yarn/bin/svelteserver`

I have set the log level to "debug" as described in readme and there are no errors in the log

<img width="1552" alt="Screen Shot 2021-02-22 at 1 51 06 PM" src="https://user-images.githubusercontent.com/24496822/108755253-0430c480-7515-11eb-81e9-d3b520710d9e.png">

_Originally posted by @seanaye in https://github.com/neovim/nvim-lspconfig/discussions/636#discussioncomment-394704_

**Comment by mjlbach** [comment]
Is there something going on with the issue template?

**Comment by seanaye** [comment]
@mjlbach sorry, this was converted from a discussion post, therefore I didn't see issue template. I will edit issue now

**Comment by mjlbach** [comment]
It's ok :) I just need the logs and to know your versions

**Comment by mjlbach** [comment]
Do you have a svelte filetype pack installed? what does `:set ft?` say?

**Comment by seanaye** [comment]
nvim version is homebrew's latest reinstalled as of today
`nvim --version`

```
NVIM v0.5.0-dev+ea8756f
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20210113-54053-1w6otkh/build/config -I/tmp/neovim-20210113-54053-1w6otkh/src -I/opt/local/include -I/tmp/neovim-20210113-54053-1w6otkh/deps-build/include -I/opt/homebrew/include -I/tmp/neovim-20210113-54053-1w6otkh/build/src/nvim/auto -I/tmp/neovim-20210113-54053-1w6otkh/build/include
Compiled by seanaye@Seans-MacBook-Pro-2.local
```

not sure how to check commit hash of lspconfig although `:PlugUpdate` says the package is latest version

run in a svelte buffer 
`:set ft` => `filetype= `

**Comment by mjlbach** [comment]
>  run in a svelte buffer
:set ft => filetype=

That's your problem :) Try adding vim-polyglot and see if it starts

**Comment by seanaye** [comment]
fixed the problem, thank you very much for your helpful and fast replies. Much appreciated!
