### ISSUE TITLE
reload workspace on rust project

### ISSUE THREAD

**Issue by etrnal70** [neovim/nvim-lspconfig#754]
Newly added crates aren't detected unless reopening nvim or restarting server. I think restarting server isn't a good idea especially for large project since rust-analyzer always run cargo check the whole project.

I think rust-analyzer have cargo autoreload option in the settings, but it's not working. Other option is reloading workspace by triggering rust-analyzer/reloadWorkspace (coc have this).

I can have a PR though for the second one, it's adapted from texlab command and working so far, but i'm unsure if it's the desired choice

**Comment by mjlbach** [comment]
I would go ahead and file the PR and we can discuss. What settings did you send to the server for autoreload? Is there a case where this is undesirable?

If it's not working (and we're doing things right on our end), we should file a bug upstream.

**Comment by etrnal70** [comment]
Maybe you can test it ?

**Comment by mjlbach** [comment]
Closed by #755

**Comment by ibraheemdev** [comment]
How do I use the `CargoReload` command? `:CargoReload` gives me `Not an editor command: CargoReload`

**Comment by ibraheemdev** [comment]
@etrnal70 
```lua
lsp.rust_analyzer.setup({
    on_attach = on_attach;
    settings = {
        ["rust-analyzer"] = {
            server = {
                path = "~/.cargo/bin/rust-analyzer"
            };
            cargo = {
                allFeatures = true
            }
        }
    }
})
```

**Comment by etrnal70** [comment]
It's working for me here with `:CargoReload` :/
