### ISSUE TITLE
denols: cannot jump to definition in deno v1.7.5

### ISSUE THREAD

**Issue by kitagry** [neovim/nvim-lspconfig#761]
related https://github.com/neovim/nvim-lspconfig/pull/744#issuecomment-785751001

- `nvim --version`: v0.5.0-dev
- nvim-lsp version(commit hash): 4d5dbea4f
- What language server (If the problem is related to a specific language server): denols
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): no
- Is the problem isolated to a particular language server: yes
- Operating system/version: windows10 wsl ubuntu20.04

### How to reproduce the problem from neovim startup

```
$ deno --version
deno 1.7.5 
```

main.ts

```ts
import { createApp } from "https://servestjs.org/@v1.1.9/mod.ts";
const app = createApp();
```

And, move cursor to `createApp` in line 2. And then, run `:lua vim.lsp.buf.definition()`.

### Actual behaviour

returns error.

```
Error executing vim.schedule lua callback: /usr/share/nvim/runtime/lua/vim/uri.lua:116: URI must contain a scheme: deno:/https/servestjs.org/%40v1.1.9/app.ts
```

### details

This error occurs because denols change the behavior from v1.7.5.

1. v1.7.4 and earlier returns `deno:///` with three slashes
2. v1.7.5 returns `deno:/` with only one slash

This issue is related to https://github.com/denoland/deno/issues/9514.
I'll investigate how this is resolved in vim-lsp and coc.nvim.
Thank you.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/can-i-has-github-notification/55/1

**Comment by mjlbach** [comment]
Sorry, was this fixed in  #753?

**Comment by kitagry** [comment]
No, #753 is unrelated to this.

**Comment by creativenull** [comment]
Can confirm, this also does not work with deno 1.8, but this is only for deno packages that are cached into the machine and not for local files in the project.

**Comment by mjlbach** [comment]
Did you try the linked PR?

**Comment by creativenull** [comment]
@mjlbach yes, I just did and it is working properly! I also get proper definition on hover

**Comment by josephcrawfordSRH** [comment]
@creativenull @mjlbach I am seeing a similar issue in deno 1.46.3. any thoughts what I may do to get this to work?
I am unable to gd to any imports at all in neovim.

The error I am getting is 
```
Error executing vim.schedule lua callback: ...ar/neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/util.lua:1914: index out of range
stack traceback:
    [C]: in function '_str_byteindex_enc'
    ...ar/neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/util.lua:1914: in function 'locations_to_items'
    ...yVim/lazy/telescope.nvim/lua/telescope/builtin/__lsp.lua:205: in function 'handler'
    .../Cellar/neovim/0.10.1/share/nvim/runtime/lua/vim/lsp.lua:936: in function 'handler'
    .../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
    vim/_editor.lua: in function <vim/_editor.lua:0>
```
and my lsp config is below.
```lua
denols = {
  filetypes = { "typescript", "typescriptreact" },
  root_dir = function(...)
   return nvim_lsp.util.root_pattern("deno.jsonc", "deno.json")(...)
  end,
  handlers = {
    ["textDocument/publishDiagnostics"] = nvim_lsp.diagnostic.on_publish_diagnostics,
  },
  settings = {
    deno = {
      enable = true,
      lint = true,
      unstable = true,
      suggest = {
        imports = {
          hosts = {
            ["https://deno.land"] = true,
          },
        },
      },
    },
  },
},
```

**Comment by k14lb3** [comment]
> [@creativenull](https://github.com/creativenull) [@mjlbach](https://github.com/mjlbach) I am seeing a similar issue in deno 1.46.3. any thoughts what I may do to get this to work? I am unable to gd to any imports at all in neovim.

See https://github.com/nvim-telescope/telescope.nvim/issues/2768.

**Comment by k14lb3** [comment]
> [@creativenull](https://github.com/creativenull) [@mjlbach](https://github.com/mjlbach) I am seeing a similar issue in deno 1.46.3. any thoughts what I may do to get this to work? I am unable to gd to any imports at all in neovim.

See https://github.com/nvim-telescope/telescope.nvim/issues/2768. @josephcrawfordSRH

**Comment by josephcrawfordSRH** [comment]
@k14lb3 I am not yet sure what the actual issue i, I am using LazyVim with deno 1.46.3 but see here https://github.com/neovim/neovim/issues/30719#issuecomment-2400538866 it seems that it is working with a minimal config, I am not sure if this is an issue yet in lsp-config or in LazyVim but will be investigating both.

**Comment by creativenull** [comment]
@josephcrawfordSRH it seems to be working with 2.0. I downgraded to 1.46.3 and still able to goto definition. I have not made any modifications to the lspconfig so it's just a simple setup

```lua
require('lspconfig').denols.setup({ on_attach = on_attach })
```

Do you have a repo or some project I can test this on? I only tested this with the latest fresh app.

**Comment by josephcrawfordSRH** [comment]
@creativenull this only seems to happen with cached dependencies which are not referenced by file path on my local system.  Github or Deno url imports I cannot jump to them.

I have created this public repo of my lazyvim configuration

https://github.com/jcrawford/lazyvim

**Comment by creativenull** [comment]
I tried out your config with an example url import.

```sh
mkdir deno-test
cd deno-test
deno init
```

```ts
import OpenAI from "https://deno.land/x/openai@v4.68.0/mod.ts"

export function add(a: number, b: number): number {
  return a + b;
}

// Learn more at https://docs.deno.com/runtime/manual/examples/module_metadata#concepts
if (import.meta.main) {
  console.log("Add 2 + 3 =", add(2, 3));

  const openai = new OpenAI({ baseURL: "https://api.openai.com" });
}
```

From what I can tell it's from telescope (as @k14lb3 mentioned) and some other plugin (that is persisting the files in session).

I switched from telescope to quickfix list/location list and I am able to see the file open and the cursor pointing to the correct place

```lua
denols = {
  keys = {
    { "gd", vim.lsp.buf.definition },
  },
},
```

![Image](https://github.com/user-attachments/assets/26f48d4e-beef-4f63-b193-eb3df9837934)


I'm not too sure why telescope is unable to open it. I'm not seeing any of those problem with my config, goto definition is working as expected with nvim just not with telescope.

**Comment by josephcrawfordSRH** [comment]
You were both correct, I had a thread in the Deno discord as well and a developer Nicholas stated it was due to telesope and had created this [pull request](https://github.com/nvim-telescope/telescope.nvim/pull/2770/commits/2d9e3be46fcd6cba79928667a14fc557948d1ca0).

I hope to see this fixed soon when it is merged :D. 

thank you all for your assistance with this.
