### ISSUE TITLE
Updated to latest (NVIM v0.5.0-dev+1133-g0869cbd55) and lost plugin functionality.

### ISSUE THREAD

**Issue by reedrainer** [neovim/nvim-lspconfig#777]
Im currently running as of this mornings update -> NVIM v0.5.0-dev+1133-g0869cbd55
ive gone to use my usual fuzzy finder function 

                                                            
   **nnoremap <leader>ff <cmd>lua require('telescope.builtin').find_files()<cr>**      

and im getting this error...

E5108: Error executing lua vim.lua:269: Tried to call API function with vim.fn: use vim.api
.nvim_create_buf instead

I'm very new to neovim and linux really so anyone with any know how would be much appreciated.

**Comment by mjlbach** [comment]
Update the plugin

**Comment by reedrainer** [comment]
Yea ive since realised my error.
