### ISSUE TITLE
[Question] How to execute lsp-commands

### ISSUE THREAD

**Issue by TornaxO7** [neovim/nvim-lspconfig#780]
So this is in the help page:
```
execute_command({command})                     *vim.lsp.buf.execute_command()*
                Executes an LSP server command.

                Parameters: ~
                    {command}  A valid `ExecuteCommandParams` object

                See also: ~
                    https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_executeCommand
```
I'm editing a `.c` file and I wanted to use [this](https://github.com/neovim/nvim-lspconfig/blob/3e6d5709f6ae01e181fd47640d1be40a78045a6e/lua/lspconfig/clangd.lua#L44) command to switch between header and source file. How am I supposed to execute a LSP command?

**Comment by TornaxO7** [comment]
I've also read the link under `See also` and the `Parameters` section said that I've to give in an `ExecuteCommandParams` but how I do I have to "declare" it? I've also tried to use a table (`{'command' : 'ClangdSwitchSourceHeader'}`) but I'm getting this error message:
```vim
E5107: Error loading lua [string ":lua"]:1: '}' expected near ':'
```

**Comment by mjlbach** [comment]
`{'command' : 'ClangdSwitchSourceHeader'}` is not valid lua `: -> =`

Usage questions should be asked on our [Discourse](https://neovim.discourse.group/c/7-category/7)

**Comment by TornaxO7** [comment]
Cool, thank you! :)
