### ISSUE TITLE
doesn't like autostart from .nvimrc ?

### ISSUE THREAD

**Issue by teto** [neovim/nvim-lspconfig#782]
- `nvim --version`: latest
- nvim-lsp version(commit hash):  73691999f77db352823c0e92e7cb083582127dd8
- What language server (If the problem is related to a specific language server): pyright
- Is the problem isolated to a particular language server: no
- Operating system/version: nixos for the win

### How to reproduce the problem from neovim startup
disable autostart with 
```
lspconfig.pyright.setup{
	autostart = false; -- This is the important new option
```
create a .nvimrc with `lua require'lspconfig'.pyright.autostart()`

### Actual behaviour
On startup I get
`/home/teto/nvim-lspconfig/lua/lspconfig/configs.lua:72: attempt to concatenate local 'root_dir' (a nil value)`
If I run the same command after start, there is no error

### Expected behaviour
No error

I will probably debug this at some point (might be my config). I would be curious to know if this happens to someone else ?

**Comment by mjlbach** [comment]
I wasn't able to reproduce this issue:

```vim
call plug#begin('/tmp/plugged')

Plug 'neovim/nvim-lspconfig'

call plug#end()

"Allow filetype plugins and syntax highlighting
set exrc 

:lua << EOF
  local nvim_lsp = require('lspconfig')
  vim.lsp.set_log_level("debug")

  nvim_lsp.pyright.setup {
      autostart = false;
   }
EOF
```

local exrc

```
:lua << EOF
require'lspconfig'.pyright.autostart()
EOF
```
