### ISSUE TITLE
definition() doesn't work for libraries with jdtls

### ISSUE THREAD

**Issue by s1n7ax** [neovim/nvim-lspconfig#784]
`vim.lsp.buf.definition()` works for all the project files (`gradle` project) but not for any of standard java libraries or external libraries (downloaded using `gradle`). Completion and diagnostics are working perfectly fine with standard and external libraries but  not "go to definition" action.

I'm using all the default setup configuration for `jdtls`.

```
require'lspconfig'.jdtls.setup{}
```

All env variables are correctly set. `JDTLS_CONFIG` is also the default.

```
export JAR=$HOME/.local/share/nvim/lsp/jdtls/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
export JDTLS_CONFIG=$HOME/.local/share/nvim/lsp/jdtls/config_linux
export GRADLE_HOME=/usr/share/java/gradle
export JAVA_HOME=/usr/lib/jvm/default-runtime
export WORKSPACE=$HOME/workspace
```
Am I missing something?

**Comment by mjlbach** [comment]
Please don't delete the issue template. Fill out the issue template and edit your post.

**Comment by mfussenegger** [comment]
Loading java library sources or that of external libraries with jdtls is not supported via the core language server protocol but requires an extension.  It's implemented in [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls)

**Comment by mjlbach** [comment]
Thanks @mfussenegger, I know nothing about Java so it would have taken me forever to realize this! 

@s1n7ax please use the wonderful plugin nvim-jdtls (it's recommended in our wiki). We try to only implement the core protocol in nvim-lspconfig.

**Comment by s1n7ax** [comment]
@mjlbach Just found it inside [language specific plugins wiki](https://github.com/neovim/nvim-lspconfig/wiki/Language-specific-plugins). I would mention it in the [config wiki](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md) itself because someone would miss it just like I did.
