### ISSUE TITLE
Default keybind not working

### ISSUE THREAD

**Issue by enricofadly** [neovim/nvim-lspconfig#790]
- `nvim --version`: 0.5.0-dev (i can't see the others number i install from ubuntu ppa head)
- nvim-lsp version(commit hash):00e9a7450eac88121768df21fde7d21f43de7529
- What language server (If the problem is related to a specific language server):lua
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):sumneko_lua
- Is the problem isolated to a particular language server:i havent try it in other lsp
- Operating system/version: pop os 20.10

### Actual behaviour
the keybind configuration that i take from default nvim-lspconfig page not working
### Expected behaviour
the keybind didnt work and when i check with :map , those keybinds arent mapped

**Comment by mjlbach** [comment]
I don't really understand your message, and you didn't follow the issue template.

If, and only if, you copied the config from README.md exactly, then the only times those keybindings will be active is when you've attached to a language server.

These types of questions are better suited for [discourse](https://neovim.discourse.group/).
