### ISSUE TITLE
Cmake language server crashes

### ISSUE THREAD

**Issue by niceloaf** [neovim/nvim-lspconfig#805]
- `nvim --version`: v0.5.0-dev+1182-gb79596eb5
- nvim-lsp version(commit hash): [`39a8033`](https://github.com/neovim/nvim-lspconfig/commit/39a803342edd62f36c1ba3a75fd046f912857c37)
- What language server (If the problem is related to a specific language server):
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): No
- Is the problem isolated to a particular language server: Yes
- Operating system/version: Arch Linux

### How to reproduce the problem from neovim startup
- Create a directory with basic root_dir (.git, build, or compile_commands.json) present
- Run `nvim CMakeLists.txt`

### Actual behaviour
- Neovim outputs `Client 1 quit with exit code 1 and signal 0`

### Expected behaviour
- Cmake to start fine

### Minimal init.vim or init.lua and code sample
```lua
-- install packer
local fn = vim.fn

local install_path = '/tmp/nvim/site/pack/packer/opt/packer.nvim'

if fn.empty(fn.glob(install_path)) > 0 then
  vim.fn.execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
end

vim.cmd [[packadd packer.nvim]]
vim.cmd [[autocmd BufWritePost minimal_init.lua PackerCompile]]
vim.cmd [[autocmd BufWritePost minimal_init.lua PackerInstall]]

local use = require('packer').use
require("packer").startup(
  {
    function()
      use "neovim/nvim-lspconfig"
    end,
    config = {package_root = '/tmp/nvim/site/pack'}
  }
)

-- LSP settings
-- log file location: $HOME/.local/share/nvim/lsp.log
vim.lsp.set_log_level("debug")
local nvim_lsp = require('lspconfig')
local on_attach = function(_, bufnr)
  local function buf_set_keymap(...) vim.api.nvim_buf_set_keymap(bufnr, ...) end
  local function buf_set_option(...) vim.api.nvim_buf_set_option(bufnr, ...) end

  buf_set_option('omnifunc', 'v:lua.vim.lsp.omnifunc')

  -- Mappings.
  local opts = { noremap=true, silent=true }
  buf_set_keymap('n', 'gD', '<Cmd>lua vim.lsp.buf.declaration()<CR>', opts)
  buf_set_keymap('n', 'gd', '<Cmd>lua vim.lsp.buf.definition()<CR>', opts)
  buf_set_keymap('n', 'K', '<Cmd>lua vim.lsp.buf.hover()<CR>', opts)
  buf_set_keymap('n', 'gi', '<cmd>lua vim.lsp.buf.implementation()<CR>', opts)
  buf_set_keymap('n', '<C-k>', '<cmd>lua vim.lsp.buf.signature_help()<CR>', opts)
  buf_set_keymap('n', '<space>wa', '<cmd>lua vim.lsp.buf.add_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wr', '<cmd>lua vim.lsp.buf.remove_workspace_folder()<CR>', opts)
  buf_set_keymap('n', '<space>wl', '<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<CR>', opts)
  buf_set_keymap('n', '<space>D', '<cmd>lua vim.lsp.buf.type_definition()<CR>', opts)
  buf_set_keymap('n', '<space>rn', '<cmd>lua vim.lsp.buf.rename()<CR>', opts)
  buf_set_keymap('n', 'gr', '<cmd>lua vim.lsp.buf.references()<CR>', opts)
  buf_set_keymap('n', '<space>e', '<cmd>lua vim.lsp.diagnostic.show_line_diagnostics()<CR>', opts)
  buf_set_keymap('n', '[d', '<cmd>lua vim.lsp.diagnostic.goto_prev()<CR>', opts)
  buf_set_keymap('n', ']d', '<cmd>lua vim.lsp.diagnostic.goto_next()<CR>', opts)
  buf_set_keymap('n', '<space>q', '<cmd>lua vim.lsp.diagnostic.set_loclist()<CR>', opts)
end

-- Add the server that troubles you here
local name = "cmake" -- ONLY EDITED HERE --
local cmd = { "cmake-language-server"} -- ONLY EDITED HERE --
if not name then
  print("You have not defined a server name, please edit minimal_init.lua")
end
if not nvim_lsp[name].document_config.default_config.cmd and (not cmd) then
  print([[You have not defined a server default cmd for a server
          that requires it please edit minimal_init.lua]])
end

nvim_lsp[name].setup {
    cmd = cmd,
    on_attach = on_attach,
}
```

### Health check
```markdown
health#lspconfig#check  
========================================================================  
## Checking language server protocol configuration   
  - INFO: cmake: configuration checked.  
```

### LSP log

<details>
<summary>Log file</summary>
[ START ] 2021-03-28T19:36:25+0800 ] LSP logging initiated
[ INFO ] 2021-03-28T19:36:25+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:311 ]	"Starting RPC client"	{  args = {},  cmd = "cmake-language-server",  extra = {}}
[ DEBUG ] 2021-03-28T19:36:25+0800 ] /usr/share/nvim/runtime/lua/vim/lsp.lua:659 ]	"LSP[cmake]"	"initialize_params"	{  capabilities = {    callHierarchy = {      dynamicRegistration = false,      <metatable> = <1>{        __tostring = <function 1>      }    },    textDocument = {      codeAction = {        codeActionLiteralSupport = {          codeActionKind = {            valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        dynamicRegistration = false,        <metatable> = <table 1>      },      completion = {        completionItem = {          commitCharactersSupport = false,          deprecatedSupport = false,          documentationFormat = { "markdown", "plaintext" },          preselectSupport = false,          snippetSupport = false,          <metatable> = <table 1>        },        completionItemKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },          <metatable> = <table 1>        },        contextSupport = false,        dynamicRegistration = false,        <metatable> = <table 1>      },      declaration = {        linkSupport = true,        <metatable> = <table 1>      },      definition = {        linkSupport = true,        <metatable> = <table 1>      },      documentHighlight = {        dynamicRegistration = false,        <metatable> = <table 1>      },      documentSymbol = {        dynamicRegistration = false,        hierarchicalDocumentSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      hover = {        contentFormat = { "markdown", "plaintext" },        dynamicRegistration = false,        <metatable> = <table 1>      },      implementation = {        linkSupport = true,        <metatable> = <table 1>      },      publishDiagnostics = {        relatedInformation = true,        tagSupport = {          valueSet = { 1, 2 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      references = {        dynamicRegistration = false,        <metatable> = <table 1>      },      rename = {        dynamicRegistration = false,        prepareSupport = true,        <metatable> = <table 1>      },      signatureHelp = {        dynamicRegistration = false,        signatureInformation = {          documentationFormat = { "markdown", "plaintext" },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      synchronization = {        didSave = true,        dynamicRegistration = false,        willSave = false,        willSaveWaitUntil = false,        <metatable> = <table 1>      },      typeDefinition = {        linkSupport = true,        <metatable> = <table 1>      },      <metatable> = <table 1>    },    window = {      showDocument = {        support = false,        <metatable> = <table 1>      },      showMessage = {        messageActionItem = {          additionalPropertiesSupport = false,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workDoneProgress = true,      <metatable> = <table 1>    },    workspace = {      applyEdit = true,      configuration = true,      symbol = {        dynamicRegistration = false,        hierarchicalWorkspaceSymbolSupport = true,        symbolKind = {          valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },          <metatable> = <table 1>        },        <metatable> = <table 1>      },      workspaceEdit = {        resourceOperations = { "rename", "create", "delete" },        <metatable> = <table 1>      },      workspaceFolders = true,      <metatable> = <table 1>    }  },  clientInfo = {    name = "Neovim",    version = "0.5.0"  },  initializationOptions = {    buildDirectory = "build",    <metatable> = <table 1>  },  processId = 7694,  rootPath = "/home/lunz/Projects/C++/ncurses-test",  rootUri = "file:///home/lunz/Projects/C++/ncurses-test",  trace = "off",  workspaceFolders = { {      name = "/home/lunz/Projects/C++/ncurses-test",      uri = "file:///home/lunz/Projects/C++/ncurses-test"    } }}
[ DEBUG ] 2021-03-28T19:36:25+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:391 ]	"rpc.send.payload"	{  id = 1,  jsonrpc = "2.0",  method = "initialize",  params = {    capabilities = {      callHierarchy = {        dynamicRegistration = false,        <metatable> = <1>{          __tostring = <function 1>        }      },      textDocument = {        codeAction = {          codeActionLiteralSupport = {            codeActionKind = {              valueSet = { "", "Empty", "QuickFix", "Refactor", "RefactorExtract", "RefactorInline", "RefactorRewrite", "Source", "SourceOrganizeImports", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports" },              <metatable> = <table 1>            },            <metatable> = <table 1>          },          dynamicRegistration = false,          <metatable> = <table 1>        },        completion = {          completionItem = {            commitCharactersSupport = false,            deprecatedSupport = false,            documentationFormat = { "markdown", "plaintext" },            preselectSupport = false,            snippetSupport = false,            <metatable> = <table 1>          },          completionItemKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25 },            <metatable> = <table 1>          },          contextSupport = false,          dynamicRegistration = false,          <metatable> = <table 1>        },        declaration = {          linkSupport = true,          <metatable> = <table 1>        },        definition = {          linkSupport = true,          <metatable> = <table 1>        },        documentHighlight = {          dynamicRegistration = false,          <metatable> = <table 1>        },        documentSymbol = {          dynamicRegistration = false,          hierarchicalDocumentSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        hover = {          contentFormat = { "markdown", "plaintext" },          dynamicRegistration = false,          <metatable> = <table 1>        },        implementation = {          linkSupport = true,          <metatable> = <table 1>        },        publishDiagnostics = {          relatedInformation = true,          tagSupport = {            valueSet = { 1, 2 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        references = {          dynamicRegistration = false,          <metatable> = <table 1>        },        rename = {          dynamicRegistration = false,          prepareSupport = true,          <metatable> = <table 1>        },        signatureHelp = {          dynamicRegistration = false,          signatureInformation = {            documentationFormat = { "markdown", "plaintext" },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        synchronization = {          didSave = true,          dynamicRegistration = false,          willSave = false,          willSaveWaitUntil = false,          <metatable> = <table 1>        },        typeDefinition = {          linkSupport = true,          <metatable> = <table 1>        },        <metatable> = <table 1>      },      window = {        showDocument = {          support = false,          <metatable> = <table 1>        },        showMessage = {          messageActionItem = {            additionalPropertiesSupport = false,            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workDoneProgress = true,        <metatable> = <table 1>      },      workspace = {        applyEdit = true,        configuration = true,        symbol = {          dynamicRegistration = false,          hierarchicalWorkspaceSymbolSupport = true,          symbolKind = {            valueSet = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26 },            <metatable> = <table 1>          },          <metatable> = <table 1>        },        workspaceEdit = {          resourceOperations = { "rename", "create", "delete" },          <metatable> = <table 1>        },        workspaceFolders = true,        <metatable> = <table 1>      }    },    clientInfo = {      name = "Neovim",      version = "0.5.0"    },    initializationOptions = {      buildDirectory = "build",      <metatable> = <table 1>    },    processId = 7694,    rootPath = "/home/lunz/Projects/C++/ncurses-test",    rootUri = "file:///home/lunz/Projects/C++/ncurses-test",    trace = "off",    workspaceFolders = { {        name = "/home/lunz/Projects/C++/ncurses-test",        uri = "file:///home/lunz/Projects/C++/ncurses-test"      } }  }}
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	'Traceback (most recent call last):\n  File "/usr/bin/cmake-language-server", line 33, in <module>\n'
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	"    sys.exit(load_entry_point('cmake-language-server==0.1.2', 'console_scripts', 'cmake-language-server')())\n  File \"/usr/bin/cmake-language-server\", line 25, in importlib_load_entry_point\n    return next(matches).load()\n  File \"/usr/lib/python3.9/importlib/metadata.py\", line 77, in load\n    module = import_module(match.group('module'))\n  File \"/usr/lib/python3.9/importlib/__init__.py\", line 127, in import_module\n"
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	'    return _bootstrap._gcd_import(name[level:], package, level)\n  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import\n'
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	'  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load\n  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked\n'
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	'  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n'
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	'  File "<frozen importlib._bootstrap_external>", line 790, in exec_module\n  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n'
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	'  File "/usr/lib/python3.9/site-packages/cmake_language_server/server.py", line 6, in <module>\n'
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	"    from pygls.features import (COMPLETION, FORMATTING, HOVER, INITIALIZE,\n"
[ ERROR ] 2021-03-28T19:36:26+0800 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:458 ]	"rpc"	"cmake-language-server"	"stderr"	"ModuleNotFoundError: No module named 'pygls.features'\n"
</details>

**Comment by mjlbach** [comment]
If you read the error trace you can see 'ModuleNotFoundError: No module named pygls.features'

We don't handle setting up your server, I would search the cmake/cmake-language-server issue tracker.
