### ISSUE TITLE
yamlls default config causes file not found on windows

### ISSUE THREAD

**Issue by TurboCartPig** [neovim/nvim-lspconfig#807]
- `nvim --version`: NVIM v0.5.0-dev+1176-g9481310c2
- nvim-lsp version(commit hash): afc2648
- What language server: yamlls
- Is the problem isolated to a particular language server: Yes
- Operating system/version: Windows 10 Build 19042

### How to reproduce the problem from neovim startup
Open a yaml file on windows with neovim and lsp_config configured to use yamlls

### Actual behaviour
You get a file not found error as a result of the language server having a different name on windows.
On windows the filename of yamlls as installed by npm is going to be `yaml-language-server.cmd`. not `yaml-language-server` like on unix systems.

I don't know if this is always true, hence why this is an issue and not a PR.

### Expected behaviour
Working ls without having to manually configure the binaries name.

### Minimal init.lua and code sample

Offending config:
```lua
require'lsp_config'.yamlls.setup {}
```

Working config:
```lua
local yamlls_bin
if vim.fn.has("win32") == 1 then
	yamlls_bin = "yaml-language-server.cmd"
elseif vim.fn.has("unix") == 1 then
	yamlls_bin = "yaml-language-server"
end

require'lsp_config'.yamlls.setup {
	cmd = { yamlls_bin, "--stdio" },
}
```

**Comment by mjlbach** [comment]
This is true, and PR welcome
