### ISSUE TITLE
start vscode-json-languageserver failed

### ISSUE THREAD

**Issue by gmr458** [neovim/nvim-lspconfig#815]
When I open a `package.json` file I get the message that appears in the screenshot.
![image](https://user-images.githubusercontent.com/53343401/113083738-54e5ae00-91a2-11eb-89b4-c3e41f557ed3.png)
This is the configuration in the `init.vim` file
![image](https://user-images.githubusercontent.com/53343401/113083065-2c10e900-91a1-11eb-95fd-1e983b720ccb.png)
I have already installed `vscode-json-languageserver` with `npm`.
The operating system I use is Windows 10 1909.
neovim version is 0.5.0-dev.
I have already installed pyright, rust_analyzer, tsserver and gopls and they work fine.

**Comment by mjlbach** [comment]
Did you read this https://github.com/neovim/nvim-lspconfig#windows?

**Comment by mjlbach** [comment]
Also, please do not delete the issue templates.

There is something wrong with your setup/config. If you want troubleshooting help for configuration issues, you should post on discourse.
