### ISSUE TITLE
formating not work for vue language server (vls)

### ISSUE THREAD

**Issue by cursorzz** [neovim/nvim-lspconfig#821]
Hi, thanks for this awesome project, I got every language servers setup works except the vue language server's formatting. according to the document it does show some configuration for format, but I just can't make it to work. 

- `NVIM v0.5.0-dev+1161-gfa4ee00fa
Build type: Release
LuaJIT 2.1.0-beta3`: 
- nvim-lsp version(commit hash): b6f66eb5f4ec0e6b87db8c7bd2f9726608bc7dec
- What language server (If the problem is related to a specific language server):  vue language server
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): no
- Is the problem isolated to a particular language server: 
- Operating system/version: macos, also in archlinux

### How to reproduce the problem from neovim startup
just add `lsp.vuels.setup{}` into config without any extra settings  (but I did tried override default settings, got no luck)

### Actual behaviour
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/733503/113420558-2105c500-93fc-11eb-831d-1b5b3c634b5e.png">
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/733503/113420811-92de0e80-93fc-11eb-9b58-befa836e572b.png">

### Expected behaviour
vue file should be formated

**Comment by mjlbach** [comment]
I don't use this, but I'm not sure the language server itself supports formatting. Often times these vscode supported language servers use an external formatting tool which is called by the extension (not the language server itself). A lot of people use diagnosticls/efm to run external formatters like prettier.

**Comment by lithammer** [comment]
The documentation mentions it needs a separate formatter:

https://vuejs.github.io/vetur/guide/formatting.html

**Comment by cursorzz** [comment]
> The documentation mentions it needs a separate formatter:
> 
> https://vuejs.github.io/vetur/guide/formatting.html

the vue language server does need tools like prettier to do the formatting work, but even by that it suppose to provide a lsp-way for the client.

with that in mind, i actually dig into to both nvim's lsp.lua and vetur's code and find out that vetur does implement the textDocument/formatting method:
https://github.com/vuejs/vetur/blob/c1f05361250bfe84059bc32714fcbbf9e2fc87f0/server/src/services/vls.ts#L376
but return a false on server capability:
https://github.com/vuejs/vetur/blob/c1f05361250bfe84059bc32714fcbbf9e2fc87f0/server/src/services/vls.ts#L691

then I did a little trick on to make formatting works for vue if anyone stuck on vue formatting
```lua
vim.lsp.vuels.setup{
  on_attach = function(client)
    client.resolved_capabilities.document_formatting = true
  end;
}
```
now we can just use regular `lua vim.lsp.buf.formatting()` to format the vue file

**Comment by lithammer** [comment]
Nice digging. Sounds like you should raise an over at Vetur for the capability issue?

**Comment by mjlbach** [comment]
@cursorzz Will you file an issue? I can't find anything on the vetur repo.

**Comment by mjlbach** [comment]
Closing as this is upstream.

**Comment by singlexyz** [comment]
> > The documentation mentions it needs a separate formatter:
> > https://vuejs.github.io/vetur/guide/formatting.html
> 
> the vue language server does need tools like prettier to do the formatting work, but even by that it suppose to provide a lsp-way for the client.
> 
> with that in mind, i actually dig into to both nvim's lsp.lua and vetur's code and find out that vetur does implement the textDocument/formatting method:
> https://github.com/vuejs/vetur/blob/c1f05361250bfe84059bc32714fcbbf9e2fc87f0/server/src/services/vls.ts#L376
> but return a false on server capability:
> https://github.com/vuejs/vetur/blob/c1f05361250bfe84059bc32714fcbbf9e2fc87f0/server/src/services/vls.ts#L691
> 
> then I did a little trick on to make formatting works for vue if anyone stuck on vue formatting
> 
> ```lua
> vim.lsp.vuels.setup{
>   on_attach = function(client)
>     client.resolved_capabilities.document_formatting = true
>   end;
> }
> ```
> 
> now we can just use regular `lua vim.lsp.buf.formatting()` to format the vue file

Thanks a lot, it works.
