### ISSUE TITLE
Error when executing LspInfo

### ISSUE THREAD

**Issue by folke** [neovim/nvim-lspconfig#827]
- `nvim --version`: v0.5.0-dev+nightly-47-g9fbeaf777
- nvim-lsp version(commit hash): a249b506b8d12ace19c06c047356278cb05711ae
- What language server (If the problem is related to a specific language server): all

### How to reproduce the problem from neovim startup

Execute `:LspInfo`

### Actual behaviour

`E5108: Error executing lua ...ck/packer/start/nvim-lspconfig/lua/lspconfig/lspinfo.lua:120: attempt to call field '_trim' (a nil value)`

### Expected behaviour

No error.

The error seems to be triggered by the latest commit a249b506b8d12ace19c06c047356278cb05711ae

### Health check
<details>
<summary>Checkhealth result</summary>

</details>

### LSP log

<details>
<summary>Log file</summary>

</details>

**Comment by mjlbach** [comment]
You need to updated your nightly.

**Comment by folke** [comment]
@mjlbach perfect, works again. thanks!

**Comment by towry** [comment]
oops 

https://github.com/neovim/neovim/pull/25073/files#diff-de132e20a0c678f2ff3234a05d868b0d118561cb72317910e7f28839640ed2e3L1250
