### ISSUE TITLE
LspInfo error

### ISSUE THREAD

**Issue by GustavoPrietoP** [neovim/nvim-lspconfig#828]
![error](https://user-images.githubusercontent.com/70907734/114023687-2cfce700-9841-11eb-8452-cc235911c2dc.png)

Hey, I keep on getting this erorr whenever i type `:LspInfo` and i haven't found anything related to the same issue.

**Comment by lithammer** [comment]
Duplicate of https://github.com/neovim/nvim-lspconfig/issues/827
