### ISSUE TITLE
Suggestion: Echo diagnostic message

### ISSUE THREAD

**Issue by seblj** [neovim/nvim-lspconfig#835]
Don't know if this is out of scope for this plugin, but I would really like a feature to echo the diagnostic message in the command line like CoC and ALE. If this is something that's not going to be implemented, is it something I could do with an autocommand myself? I tried using `CursorHold` together with `vim.lsp.diagnostic.show_line_diagnostics()`, and got the message printed in the command line. However, I would like the message to be removed when I move my cursor again. Thought about `CursorMoved`, but I don't want it to clear every time I move my cursor

**Comment by mjlbach** [comment]
I don't know what you mean by command line, I assume you don't mean in `:messages` but probably preview's with `splitbelow`, you can achieve this already by overriding the definition the definition of `vim.lsp.diagnostic.show_line_diagnostics().` It sounds like you have a very specific functionality in mind, so it's probably nothing that could be added to neovim core (what you're asking for is not implemented in this plugin).

Re: `CursorMoved`, you can define an autocommand That's executed once `:help autocmd-once`, I'd probably add that to your custom show_line_diagnostics (as in, set up the autocommand with `once` each time show_line_diagnostics is invoked.

Questions like these are best asked on the discourse, as more people will respond/help troubleshoot than here.

**Comment by yochem** [comment]
Hey! Have you found out if this is possible? Would really prefer it over de hovering popup :)

**Comment by seblj** [comment]
> Hey! Have you found out if this is possible? Would really prefer it over de hovering popup :)

I actually made a really simple plugin for this! You can check it out here https://github.com/seblj/nvim-echo-diagnostics

**Comment by yochem** [comment]
Thank you so much!! Was searching for this feature a long time, immediately downloaded it and a happy user from now on :)

**Comment by WIttyJudge** [comment]
@seblj this is great. Thank you for you work!

**Comment by tuxsisir** [comment]
@seblj Thank you for writing the plugin. It works like a charm!

**Comment by realestninja** [comment]
@seblj Thanks for the plugin! great job!

**Comment by 9mm** [comment]
DUDE! @seblj literally i have been searching for weeks and attempting to struggle through this myself. A+++++ THANK YOU
