### ISSUE TITLE
How can implement Deno LSP

### ISSUE THREAD

**Issue by hemedani** [neovim/nvim-lspconfig#837]
please create a instruction for implementing [denols](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#denols) along with [tsserver](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#tsserver) and answer these questions :

1. how can avoid throwing tsserver error which it provide several error on Deno project like 
```
can not find name 'Deno'
An import path cannot end with a '.ts' extension ...
...
```
![Screen Shot 1400-01-24 at 19 44 38](https://user-images.githubusercontent.com/6236123/114576822-bc1a5c80-9c90-11eb-8ee9-65a779d8bad4.png)
2.how can manage active LSP Clients
3.how can disable and enable 1 LSP without reload a buffer.
4. how can read some file for changing LSP option like Deno init option 
```
    init_options = {
      enable = true,
      lint = false,
      unstable = false
    }
```
I'm writing Lua script for reading and parsing json file but LSP do not run after reading files
```lua
local open = io.open
local file = open(".deno/settings.json", "rb")
if not file then return nil end
local jsonString = file:read "*a"
file:close()

-- parse json with lunajson
local json = require 'lunajson'
local t = json.decode(jsonString)
```

**Comment by mjlbach** [comment]
Don't delete the issue template. Usage questions belong on our [discourse](https://neovim.discourse.group/c/7-category/7). I don't know what you're asking for 3/4, the answer to 2 is in the readme, and it's a bad idea to run both tsserver and deno simultaneously.
