### ISSUE TITLE
LSP: support sharing a language server across workspace folders 

### ISSUE THREAD

**Issue by mjlbach** [neovim/nvim-lspconfig#842]
Workspace folder support as of neovim/neovim#12638 is extremely barebones. While you can add a workspace folder to a buffer, if you attempt to *open* a new buffer in a folder that is not within the root URI, it will launch a second language server, and furthermore the second language server does not inherit the first workspace's workspace folders. See neovim/neovim#13398 for a previous bug report.

Two options:
* On opening a file that is outside the root uri, but that matches the filetype of a currently active client, prompt for whether or not the workspace should be added to the client. If this workspace folder was already added, don't prompt.
* Automatically start a second language server (by default) unless you have already added the workspace folder.

I lean towards 1, as this matches vscode, and I don't think people will be that annoyed. Currently, most of this logic is implemented in nvim-lspconfig, so I'd probably want to port over the root detection/launching code.

**Comment by hieulw** [comment]
Is this implemented ? I find that quite annoying that it spawns many lsp clients with the same filetype whenever I jump around my source code library. Then I cannot jump to definition anymore due to new clients doesn't inherit the first one as you said.

**Comment by mjlbach** [comment]
No, if the detected root pattern is different lspconfig will spawn a new server with that root. If it's happening regularly in your source code library, and all files in your source are under the same parent directory, consider removing any root detection fallbacks like `util.path.dirname` until there is a better solution.

**Comment by hieulw** [comment]
Can you tell me how to remove `util.path.dirname` ? I have no clue of what that is. Thanks so much !

**Comment by mjlbach** [comment]
What server are you experiencing the issue with, and can you show `:LspInfo` after it's connected?

**Comment by hieulw** [comment]
> What server are you experiencing the issue with, and can you show `:LspInfo` after it's connected?

Pyright sir. And this is my `:LspInfo`
```
 Language client log: /Users/hieulw/.cache/nvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: efm (id: 1, pid: 38090, bufnr: [1, 586, 581, 570, 592])
 	filetypes:       lua, python
 	autostart:       true
 	root directory:  /Users/hieulw/Site/api.master/app/data-foundation-api
 	cmd:             /Users/hieulw/.local/share/nvim/lspinstall/efm/./efm-langserver
 
 Client: python (id: 2, pid: 38091, bufnr: [1, 586, 581, 570, 592])
 	filetypes:       python
 	autostart:       true
 	root directory:  /Users/hieulw/Site/api.master/app/data-foundation-api
 	cmd:             /Users/hieulw/.local/share/nvim/lspinstall/python/./node_modules/.bin/pyright-langserver --stdio
 
 2 active client(s) not attached to this buffer: 
 
 Client: efm (id: 3, pid: 38199, bufnr: [383, 390, 390])
 	filetypes:       lua, python
 	autostart:       true
 	root directory:  /Users/hieulw/Site/api.master/lib/fii-datapack
 	cmd:             /Users/hieulw/.local/share/nvim/lspinstall/efm/./efm-langserver
 
 Client: python (id: 4, pid: 38200, bufnr: [383, 390, 390])
 	filetypes:       python
 	autostart:       true
 	root directory:  /Users/hieulw/Site/api.master/lib/fii-datapack
 	cmd:             /Users/hieulw/.local/share/nvim/lspinstall/python/./node_modules/.bin/pyright-langserver --stdio
 
 Configured servers list: lua, efm, python, diagnosticls
```

**Comment by kylo252** [comment]
@hieulw, the language server should recognize all files as part of a workspace/project as long as that project directory contains one of these anchors mentioned here:
https://github.com/neovim/nvim-lspconfig/blob/a7df46eead286734203b1f7b71141fb131743d40/lua/lspconfig/pyright.lua#L22-L32

So it will perform the search pattern for these "python-specific" files, then it will try to find a `.git` to determine the project root, and finally if all of above has failed, then it will match that file independently. 

The `bufnr` in `LspInfo` is there to help you see which buffers are treated, more or less, as a project by the server.

**Comment by quantum-booty** [comment]
If I import numpy in a project and also open the numpy source file, I see two pyright clients are created.
![image](https://user-images.githubusercontent.com/28958399/145715029-ac99f222-2943-44b8-90ad-99f298babd07.png)
This is problematic when I would like to modify the numpy source code, as the virtual diagnostics becomes very buggy in numpy and in the project, I would have to do :LspRestart very often to reset the bugged diagnostics.
Is this problem related to the issue discussed here?

**Comment by kylo252** [comment]
The problem is that the first server didn't recognize the workspace, so instead it's attaching in single-file mode. While the other file probably doesn't share the same parent directory. So it spun off another instance instead of treating your entire home-directory as a workspace.

I'd suggest creating a virtual environment for the project you're working on, and then install `numpy` in it.

**Comment by IamAfnanMalik** [comment]
Is there any update regarding this?

**Comment by 0b1100yh** [comment]
Hello, is there a way to work around it?
Starting multiple small memory lsp servers is acceptable, but memory monster like rust-analyzer is a different story.
For every library source accessed, rust-analyzer will eat at least 300M of memory. The scary part is the standard library source, navigating to the `String` source starts an lsp server, navigating to the `Vec` starts another one, one after another.
