### ISSUE TITLE
Suggestion: [Elixirls] Improve documentation

### ISSUE THREAD

**Issue by Rolf1e** [neovim/nvim-lspconfig#843]
- `nvim --version`:
```
NVIM v0.5.0-dev+1249-ge652b2987
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/rolfie/software/neovim/build/config -I/home/rolfie/software/neovim/src -I/home/rolfie/software/neovim/.deps/usr/include -I/usr/include -I/home/rolfie/software/neovim/build/src/nvim/auto -I/home/rolfie/software/neovim/build/include
Compiled by rolfie@debian

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- What language server (If the problem is related to a specific language server): elixirls
- Operating system/version: OS:
```
Debian GNU/Linux 10 (buster) x86_64
Kernel: 4.19.0-16-amd64
```

### Actual behaviour
`echo &filetype` outputs `euphoria3`

### Expected behaviour
`echo &filetype` outputs `elixir`

### Minimal init.vim or init.lua and code sample
you can try vim with empty init.vim

I've been trying to setup elixir-ls with lsp-config builtin. 
So far I've succeed but [documentation](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#elixirls) says to bind filetype to "elixir" or "eelixir". 
When I open a elixir files `.ex`, if I output echo &filetype I got euphoria3. 
I've been googling and I found [this](https://github.com/elixir-editors/vim-elixir/issues/121). I don't think this is a bug because of this [comment](https://github.com/elixir-editors/vim-elixir/issues/121#issuecomment-158277186), but some  documentation could be added with either solutions:
1. 
```
au BufRead,BufNewFile *.ex,*.exs set filetype=elixir
au BufRead,BufNewFile *.eex set filetype=eelixir
```
2. Recommandation of  [vim-elixir plugin ](https://github.com/elixir-editors/vim-elixir) with lsp-config so the file type is preconfigured

**Comment by lithammer** [comment]
I'd say it's outside the scope of this plugin. The fact that stock Vim/Neovim doesn't come with Elixir support isn't really our problem and will just clutter the README with things unrelated to this plugin.

I'll defer to @mjlbach for this though.

**Comment by mjlbach** [comment]
Agreed, there's a limit to how verbose our documentation should be.
