### ISSUE TITLE
Error when executing LspInfo command

### ISSUE THREAD

**Issue by lagachea** [neovim/nvim-lspconfig#844]
Hi, I encountered an error, I tried to see if there was a similar issue that have been resolved, but none of the solution provided did work for me. Also I made sure to use the latest nighlty release of neovim and nvim-lspconfig.

```
NVIM v0.5.0-dev+1256-gd19348923
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az204-644

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"
```
- nvim-lsp version(commit 5029746a27ad817a9554b28d502d00f235fed39c):

### How to reproduce the problem from neovim startup
launch command LspInfo

### Actual behaviour
`E5108: Error executing lua vim.lua:269: Tried to call API function with vim.fn: use vim.api.nvim_create_buf instead`

### Expected behaviour
Display info about registered language servers / attached language servers

### Minimal init.vim or init.lua and code sample
I tried using the minial init.lua

### Health check
<details>
<summary>LSP HEALTHCHECK</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: pyls: configuration checked.
  - INFO: clangd: configuration checked.
  - INFO: jsonls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: html: configuration checked.
  - INFO: cssls: configuration checked.
</details>

### LSP log

<details>
<summary>Log file</summary>
THE LOG FILE WAS EMPTY
</details>

PS: Please correct my english, I would like to improve myself. Thanks in advance NEOVIM ROCKS

**Comment by mjlbach** [comment]
This is an installation/plugin issue. Are you sure you reproduced with the minimal init.lua? There is 100% no call to vim.fn that would cause this in the latest version of the plugin.

**Comment by lagachea** [comment]
Hello, I checked again by using these commands to launch with minimal config.
```
curl -fLO https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua 
After editing to include your language server, run neovim with nvim -u minimal_init.lua 
```
Unfortunately I have the same error when running the command `LspInfo` in nvim:
`E5108: Error executing lua vim.lua:269: Tried to call API function with vim.fn: use vim.api.nvim_create_buf instead`


You mentioned that it might come from a path issue. I am wondering if using a custom name for plugins directory might be the cause. I declared my plugin directory like so (I am using Plug to manage the plugins):
```
call plug#begin('~/.config/nvim/plug.dir')
```

I asked a friend who has almost the same config as me but doesn't have the same problem. I am closing this issue for now i will try to update my findings here if I have a solution. Thanks again

**Comment by a-h** [comment]
I had an old version of this plugin installed, you'll need to have anything later than this version: https://github.com/neovim/nvim-lspconfig/commit/a714ca95532724cead4f2dafe53e3ec1d74ae78c#diff-d13e4b7e47df19f919e0533d340b6d525e60f6b40e0424606dc82cfa512e47d5

I debugged the problem by hitting `:set runtimepath?` and checking through the files in the root path with ripgrep - `rg nvim_create_buf`.

I had a super-old version.

I use the Nix package manager, so this is bit odd if you don't, but:

```
$ nix-store --query --requisites /run/current-system|grep nvim-lspconfig
/nix/store/20w0yram3l0jn6nkyy1sz7ncp672yp84-vimplugin-nvim-lspconfig-2021-02-17
```

After a `nix-channel --update`, it's:

```
/nix/store/q46ls9bnljiwwr939whpzz7jjn1bn68z-vimplugin-nvim-lspconfig-2021-08-16
```

And no problem...
