### ISSUE TITLE
Error executing the command "LspInfo"

### ISSUE THREAD

**Issue by DilanGMB** [neovim/nvim-lspconfig#845]
- `nvim --version`: 
```txt
NVIM v0.5.0-dev
Build type: Debug
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing
-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS
-D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=1 -I/home/dilanbar/Downloads/neovim-nightly/build/con
fig -I/home/dilanbar/Downloads/neovim-nightly/src -I/home/dilanbar/Downloads/neovim-nightly/.deps/usr/include -I/usr/include -I/home/dil
anbar/Downloads/neovim-nightly/build/src/nvim/auto -I/home/dilanbar/Downloads/neovim-nightly/build/include
Compiled by root@machine

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```
- nvim-lsp version(commit hash): 5029746
- What language server (If the problem is related to a specific language server): ---
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): ---
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): ---
- Is the problem isolated to a particular language server: ---
- Operating system/version: Ubuntu 20.04, Kernel: 5.8.0-49-generic

### How to reproduce the problem from neovim startup
During startup everything goes fine and there are no visible errors, however, when executing the :LspInfo command to query the status of the configured servers the following error appears:
(nothing is displayed in the floating window).
(try commenting out the line specified in the error and it works fine)

![error](https://user-images.githubusercontent.com/65829671/115064816-011dd900-9eb3-11eb-871d-57c2644403b3.png)

### Actual behaviour
when I am trying to use the "LspInfo" command I get an error that does not allow me to display the current status of active clients and configured servers.

### Expected behaviour
Proper functioning of the aforementioned instructions

### Minimal init.vim or init.lua and code sample
I basically use minimal_init.lua with some changes.

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration.<br/>
  - INFO: clangd: configuration checked.<br/>
  - INFO: tsserver: configuration checked..<br/>
  - INFO: sumneko_lua: configuration checked..<br/>
  - INFO: pyright: configuration checked..<br/>
  - INFO: jsonls: configuration checked..<br/>
  - INFO: cssls: configuration checked..<br/>
  - INFO: html: configuration checked..<br/>
</details>

### LSP log

<details>
[ START ] 2021-04-16T12:56:34-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T12:56:18-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T12:56:44-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T12:57:16-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T12:59:16-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T12:59:29-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T12:56:50-0500 ] LSP logging initiated<br/>
[ INFO ] 2021-04-16T12:59:36-0500 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1058 ]	"exit_handler"	{}<br/>
[ START ] 2021-04-16T12:59:37-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T13:00:03-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T13:00:16-0500 ] LSP logging initiated<br/>
[ START ] 2021-04-16T13:00:22-0500 ] LSP logging initiated<br/>
[ WARN ] 2021-04-16T13:00:29-0500 ] /usr/local/share/nvim/runtime/lua/vim/lsp/handlers.lua:108 ]	"The language server jdt.ls triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"

<summary>Log file</summary>

[Log-File](https://github.com/neovim/nvim-lspconfig/files/6327190/log.txt)

</details>

**Comment by mjlbach** [comment]
Update your neovim-nightly
