### ISSUE TITLE
How to open definition file as a new tab instead of buffer?

### ISSUE THREAD

**Issue by JunichiSugiura** [neovim/nvim-lspconfig#847]
I have [this](https://github.com/JunichiSugiura/dotfiles/blob/master/packages/nvim/.config/nvim/init.vim#L50) key mapping but I would like to open in a new tab instead of buffer. Is there any ways to do that?

**Comment by mjlbach** [comment]
This is a usage question and belongs on our [discourse](https://neovim.discourse.group/). It's also not implemented in this plugin, but in neovim core. You'll need to override the definition handler.
