### ISSUE TITLE
Solargraph hangs after Prettier formatted the code.

### ISSUE THREAD

**Issue by marcushwz** [neovim/nvim-lspconfig#850]
- `nvim --version`: `v0.5.0-dev+1259-gfe808f02f`
- nvim-lsp version(commit hash): 
- What language server (If the problem is related to a specific language server): `Solargraph`
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): `nope`
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): `nope`
- Is the problem isolated to a particular language server: `yes`
- Operating system/version: `macOS Big Sur 11.2.2`

### How to reproduce the problem from neovim startup
1. Setup neovim with vim-prettier
2. Edit a ruby file, and let prettier do the formatting

### Actual behaviour
- Solargraph seems to hang for quite a long time (around 1 minute) until the next diagnostics show up
- Attach is a short video showing what happen in my terminal
- Note that, saving when there is nothing for Prettier to format works fine.

https://user-images.githubusercontent.com/40255418/115112074-4840c280-9fb6-11eb-924f-1716c3919dea.mp4

### Expected behaviour
- I am hoping the language server will immediately show the next diagnostic immediately like `tsserver`
- Everything works fine with tsserver, even after I format the ts file with prettier, the next diagnostics show up immediately2

### Minimal init.vim or init.lua and code sample
```vim
lua << EOF
require'lspconfig'.tsserver.setup{}
require'lspconfig'.solargraph.setup {}
vim.lsp.set_log_level("debug")
EOF

" calling Prettier Async
:autocmd BufWritePre *.mjs,*.css,*.less,*.scss,*.json,*.graphql,*.vue,*.yaml,*.html,*.rb,*.tsx,*.jsx,*.ts,*.js PrettierAsync

```

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: solargraph: configuration checked.
  - INFO: tsserver: configuration checked.
</details>

### LSP log
- The logs is super long and seems like is repeating for everyline of code I have in that file. I copied part of the log here.
<details>
<summary>Log file</summary>
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 456, firstline: 200, lastline: 200, new_lastline: 201, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  def customer_borne_easy_post?" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 200          },          start = {            character = 0,            line = 200          }        },        rangeLength = 0,        text = "  def customer_borne_easy_post?\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 456    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 457, firstline: 201, lastline: 201, new_lastline: 202, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "    uses_drop_off? && customer_borne_shipping? && shop.courier&.easy_post?" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 201          },          start = {            character = 0,            line = 201          }        },        rangeLength = 0,        text = "    uses_drop_off? && customer_borne_shipping? && shop.courier&.easy_post?\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 457    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 458, firstline: 202, lastline: 202, new_lastline: 203, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  end" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 202          },          start = {            character = 0,            line = 202          }        },        rangeLength = 0,        text = "  end\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 458    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 459, firstline: 203, lastline: 203, new_lastline: 204, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 203          },          start = {            character = 0,            line = 203          }        },        rangeLength = 0,        text = "\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 459    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 460, firstline: 204, lastline: 204, new_lastline: 205, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  def all_items_keep?" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 204          },          start = {            character = 0,            line = 204          }        },        rangeLength = 0,        text = "  def all_items_keep?\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 460    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 461, firstline: 205, lastline: 205, new_lastline: 206, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "    return_items = refunds + exchanges" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 205          },          start = {            character = 0,            line = 205          }        },        rangeLength = 0,        text = "    return_items = refunds + exchanges\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 461    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 462, firstline: 206, lastline: 206, new_lastline: 207, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "    return_items.reduce(true) { |acc, item| acc && item.keep_item }" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 206          },          start = {            character = 0,            line = 206          }        },        rangeLength = 0,        text = "    return_items.reduce(true) { |acc, item| acc && item.keep_item }\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 462    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 463, firstline: 207, lastline: 207, new_lastline: 208, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  end" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 207          },          start = {            character = 0,            line = 207          }        },        rangeLength = 0,        text = "  end\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 463    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 464, firstline: 208, lastline: 208, new_lastline: 209, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 208          },          start = {            character = 0,            line = 208          }        },        rangeLength = 0,        text = "\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 464    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 465, firstline: 209, lastline: 209, new_lastline: 210, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  def approved_line_item_ids" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 209          },          start = {            character = 0,            line = 209          }        },        rangeLength = 0,        text = "  def approved_line_item_ids\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 465    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 466, firstline: 210, lastline: 210, new_lastline: 211, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "    status = pending? ? :all : :approved" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 210          },          start = {            character = 0,            line = 210          }        },        rangeLength = 0,        text = "    status = pending? ? :all : :approved\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 466    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 467, firstline: 211, lastline: 211, new_lastline: 212, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 211          },          start = {            character = 0,            line = 211          }        },        rangeLength = 0,        text = "\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 467    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 468, firstline: 212, lastline: 212, new_lastline: 213, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "    (refunds.send(status) + exchanges.send(status)).map(&:line_item_id)" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 212          },          start = {            character = 0,            line = 212          }        },        rangeLength = 0,        text = "    (refunds.send(status) + exchanges.send(status)).map(&:line_item_id)\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 468    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 469, firstline: 213, lastline: 213, new_lastline: 214, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  end" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 213          },          start = {            character = 0,            line = 213          }        },        rangeLength = 0,        text = "  end\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 469    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 470, firstline: 214, lastline: 214, new_lastline: 215, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 214          },          start = {            character = 0,            line = 214          }        },        rangeLength = 0,        text = "\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 470    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 471, firstline: 215, lastline: 215, new_lastline: 216, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  private" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 215          },          start = {            character = 0,            line = 215          }        },        rangeLength = 0,        text = "  private\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 471    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 472, firstline: 216, lastline: 216, new_lastline: 217, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 216          },          start = {            character = 0,            line = 216          }        },        rangeLength = 0,        text = "\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 472    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 473, firstline: 217, lastline: 217, new_lastline: 218, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  def after_create_actions" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 217          },          start = {            character = 0,            line = 217          }        },        rangeLength = 0,        text = "  def after_create_actions\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 473    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 474, firstline: 218, lastline: 218, new_lastline: 219, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "    ReturnOrder::AfterCreateService.call(self)" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 218          },          start = {            character = 0,            line = 218          }        },        rangeLength = 0,        text = "    ReturnOrder::AfterCreateService.call(self)\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 474    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 475, firstline: 219, lastline: 219, new_lastline: 220, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "  end" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 219          },          start = {            character = 0,            line = 219          }        },        rangeLength = 0,        text = "  end\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 475    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 476, firstline: 220, lastline: 220, new_lastline: 221, old_byte_size: 0, old_utf32_size: 0, old_utf16_size: 0"	{ "end" }
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 220          },          start = {            character = 0,            line = 220          }        },        rangeLength = 0,        text = "end\n"      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 476    }  }}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 477, firstline: 221, lastline: 222, new_lastline: 221, old_byte_size: 1, old_utf32_size: 1, old_utf16_size: 1"	{}
[ DEBUG ] 2021-04-17T19:53:28+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 221          },          start = {            character = 3,            line = 220          }        },        rangeLength = 1,        text = ""      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 477    }  }}
[ DEBUG ] 2021-04-17T19:53:42+0800 ] .../Softwares/nvim-osx64/share/nvim/runtime/lua/vim/lsp.lua:991 ]	"on_lines bufnr: 1, changedtick: 479, firstline: 219, lastline: 220, new_lastline: 219, old_byte_size: 6, old_utf32_size: 6, old_utf16_size: 6"	{}
[ DEBUG ] 2021-04-17T19:53:42+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]	"rpc.send.payload"	{  jsonrpc = "2.0",  method = "textDocument/didChange",  params = {    contentChanges = { {        range = {          end = {            character = 0,            line = 220          },          start = {            character = 0,            line = 219          }        },        rangeLength = 6,        text = ""      } },    textDocument = {      uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb",      version = 479    }  }}
[ DEBUG ] 2021-04-17T19:54:37+0800 ] ...twares/nvim-osx64/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]	"decoded"	{  jsonrpc = "2.0",  method = "textDocument/publishDiagnostics",  params = {    diagnostics = { {        message = " unexpected token $end\n(Using Ruby 2.7 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)",        range = {          end = {            character = 0,            line = 220          },          start = {            character = 0,            line = 220          }        },        severity = 1,        source = "Lint/Syntax"      } },    uri = "file:///Users/marcusheng/Workspace/project-tapir/app/models/return_order.rb"  }}
</details>

Sorry, if this does not belongs here, I have been trying to solve this the whole day but to no avail. I really appreciate if someone can help me out on this issue. Thank you to everyone contributing to this project, I have been enjoing it so far!

**Comment by mjlbach** [comment]
We added debouncing of didChange notifications but it's not on by default. I imagine ~100 ms will fix this issue. See: https://github.com/neovim/neovim/pull/14119 and the closed issues linked in that PR.

**Comment by marcushwz** [comment]
> We added debouncing of didChange notifications but it's not on by default. I imagine ~100 ms will fix this issue. See: [neovim/neovim#14119](https://github.com/neovim/neovim/pull/14119) and the closed issues linked in that PR.

Thank you so much for the reply. I have added the flag to my `Solargraph` config, and it works like a charm! `Solargraph` no longer hangs, and the experience is much more snappy (no more delay in diagnostics). I can close this issue I guess?

**Comment by mjlbach** [comment]
Nice, yes. There's issues upstream in core where the default may be changed (or perhaps here, it's unclear yet), so I think we close this one.

**Comment by jordanbrock** [comment]
@marcushwz Can you post an example of your solargraph config with the added flag?

**Comment by marcushwz** [comment]
Of course @jordanbrock , my current config is pretty bare-bones. It looks something like this
```lua
require'lspconfig'.solargraph.setup {
  flags = {
    debounce_text_changes = 150,
  }
}
```

Also, I have decided to switch over to use the built-in `formatting` using Solargraph with some custom Rubocop config. With the built-in formatting, I don't even need to add the flag to solve the hanging problem. But yeah, with the debounce flag enabled, the experience is much smoother. My config for formatting looks something like this now. I hope it helps :)

```vim
augroup fmt
  autocmd!
  autocmd BufWritePre *.rb lua vim.lsp.buf.formatting()
  autocmd BufWritePre *.mjs,*.css,*.less,*.scss,*.json,*.yaml,*.html,*.tsx,*.jsx,*.ts,*.js PrettierAsync
augroup END
```
