### ISSUE TITLE
bufnr in on_attach lsp config callback is nil

### ISSUE THREAD

**Issue by mnowotnik** [neovim/nvim-lspconfig#856]
I think the autocmd at [this line](https://github.com/neovim/nvim-lspconfig/blob/5c005ce93367ad85933eff80887228bca2a7efee/lua/lspconfig/configs.lua#L142) should be
```lua
          api.nvim_command(string.format(
              "autocmd BufEnter <buffer=%d> ++once lua require'lspconfig'[%q]._setup_buffer(%d,%d)"
              , bufnr
              , config_name
              , client.id
              , bufnr
              ))
```
Currently, bufnr is being passed to user on_attach callback as a nil.

**Comment by mjlbach** [comment]
Closed by #857
