### ISSUE TITLE
util.script_path always returns nil on Windows

### ISSUE THREAD

**Issue by rleathart** [neovim/nvim-lspconfig#872]
- `nvim --version`:
```none
NVIM v0.5.0-dev+1280-gbb7d3790b
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -ID:/a/neovim/neovim/build/config -ID:/a/neovim/neovim/src -ID:/a/neovim/neovim/nvim-deps/usr/include -ID:/a/neovim/neovim/build/src/nvim/auto -ID:/a/neovim/neovim/build/include
Compiled by runneradmin@fv-az152-170

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
```
- nvim-lsp version(commit hash): `05358bd129ea6262436e7b9605b3e203d4aa7c77`
- Operating system/version: `Windows 10 19042.928`

### How to reproduce the problem from neovim startup

Run `nvim -u minimal_init.lua` and observe lua error about `script_path` being `nil`.

### Actual behaviour

`script_path` is `nil` so config isn't loaded properly.

### Expected behaviour

See https://github.com/neovim/nvim-lspconfig/commit/04f223f3d08388eac74a571516145154bf5af64c#r50268524

### Minimal init.vim or init.lua and code sample

Used https://raw.githubusercontent.com/neovim/nvim-lspconfig/master/test/minimal_init.lua

### Health check
<details>
<summary>Checkhealth result</summary>
No output

</details>

**Comment by mjlbach** [comment]
I'm out right now, but will fix this later. For now people can hold off on updating on windows. Thank you for the report!
