### ISSUE TITLE
QUESTION: How to change the colors of inline diagnostics

### ISSUE THREAD

**Issue by brymer-meneses** [neovim/nvim-lspconfig#874]
The default colors for LSP Diagnostics do not match very well with my neovim colorscheme. Is it possible to customize the colors of the inline diagnostics?

**Comment by mjlbach** [comment]
Questions are for our [discourse](https://neovim.discourse.group/c/7-category/7). The lsp diagnostics are like any other highlight group. See ':help highlight` and `:help lsp-highlight-diagnostics`
