### ISSUE TITLE
configuring custom language server broken 

### ISSUE THREAD

**Issue by dimbleby** [neovim/nvim-lspconfig#876]
### How to reproduce the problem from neovim startup

I use the YANG language server and, since it is not natively supported here, I have added custom configuration for it following the pattern in the README, like this:

```lua
local configs = require'lspconfig/configs'
if not lspconfig.yang_language_server then
  configs.yang_language_server = {
    default_config = {
      cmd = {'yang-language-server'};
      filetypes = {'yang'};
      root_dir = lspconfig.util.root_pattern("yang.settings", ".git");
      settings = {};
    };
  }
end
lspconfig.yang_language_server.setup{}
```

With configuration like that, open neovim.

### Actual behaviour

```
Error detected while processing /home/dch/.vim/vimrc:
line  203:
E5108: Error executing lua cannot open /home/dch/.vim/plugged/nvim-lspconfig/lua/lspconfig/yang_language_server.lua: No such file or directory
```

### Expected behaviour

Everything should be fine!

`git bisect` reckons that this was introduced at 04f223f3d08388eac74a571516145154bf5af64c.

### Minimal init.vim or init.lua and code sample

https://github.com/neovim/nvim-lspconfig#example-custom-config

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - ERROR: gopls: The given command "gopls" is not executable.
  - INFO: terraformls: configuration checked.
  - INFO: jedi_language_server: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - ERROR: ccls: The given command "ccls" is not executable.
</details>

### LSP log

N/A

**Comment by mjlbach** [comment]
it should be an easy fix if you want to PR it, just try wrapping dofile in a protected call

**Comment by dimbleby** [comment]
indeed that seems to do it, PR made

**Comment by anand-bala** [comment]
I am not sure if wrapping the `dofile` in a `pcall` helps here as it breaks texlab. Essentially, in the latest commit, when the config for texlab is loaded, the new table for texlab is not created in [`configs.__newindex`](https://github.com/neovim/nvim-lspconfig/blob/746864bec9bae3136d59ab4b7a6188fc950b6e9a/lua/lspconfig/configs.lua#L26).

I replaced the `dofile` [here](https://github.com/neovim/nvim-lspconfig/blob/746864bec9bae3136d59ab4b7a6188fc950b6e9a/lua/lspconfig.lua#L91) with the old call to [`require`](https://github.com/neovim/nvim-lspconfig/blob/6bc13672db464b0f810b7e03446c55bd64c2ee52/lua/lspconfig.lua#L87). This works fine.

I am in the process of debugging why this happens, but would love some help.

**Comment by mjlbach** [comment]
Texlab works fine for me, can you reproduce with our minimal config? I haven't seen your config, but are you doing something like this? https://github.com/neovim/nvim-lspconfig/pull/861#issuecomment-825862325

**Comment by anand-bala** [comment]
Hey @mjlbach, my texlab config is [here](https://github.com/anand-bala/dotfiles/blob/d90878953e3f41604bdf2ce9fc2dfde8721b0d2e/nvim/lua/_lsp/texlab.lua) and the call to setup is [here](https://github.com/anand-bala/dotfiles/blob/d90878953e3f41604bdf2ce9fc2dfde8721b0d2e/nvim/lua/_lsp/init.lua#L117).

**Comment by mjlbach** [comment]
Sorry, I can't read through your personal config. I'd recommend matching the recommended method of adding custom language servers per our readme. Anything else is unsupported (if you want, you're free to override our internal use of dofile with require)

**Comment by anand-bala** [comment]
Turns out the issue was [this](https://github.com/anand-bala/dotfiles/blob/d90878953e3f41604bdf2ce9fc2dfde8721b0d2e/nvim/lua/_lsp/texlab.lua#L3) line. Not sure why, but removing that (unnecessary) line solves my issue.
