### ISSUE TITLE
Pyright: Default python.analysis.diagnosticMode to "workspace"

### ISSUE THREAD

**Issue by fdschmidt93** [neovim/nvim-lspconfig#881]
Hi there,

Pyright currently [defaults](https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/pyright.lua) to the below configuration -

```lua
configs[server_name] = {
  default_config = {
    cmd = {bin_name, "--stdio"};
    filetypes = {"python"};
    root_dir = function(filename)
      return util.root_pattern(unpack(root_files))(filename) or
             util.path.dirname(filename)
    end;
    settings = {
      python = {
        analysis = {
          autoSearchPaths = true;
          useLibraryCodeForTypes = true;
          -- implicit default
          diagnosticMode = "openFilesOnly";
        };
      };
    };
  };
```
I've raised this issue to discuss whether it might make sense to change the default for the diagnostic mode of pyright i.e.

```lua
      python = {
        analysis = {
          autoSearchPaths = true;
          useLibraryCodeForTypes = true;
          diagnosticMode = 'workspace'
        };
```
That way, many users can easily access workspace diagnostics via telescope, lsp-trouble, or parsing `vim.lsp.diagnostic.get_all()`.

In the projects (typically c.1K lines across 5-20 files with large libraries like Pytorch, Huggingface Transformers, Pytorch-Lightning - should that matter) I'm using there is no noticeable slowdown, though of course that might change with bigger projects though since Pyright handles that off Neovim's main process I guess any slowdown would be largely alleviated anyways. 

Further, of course users can always set the option themselves, but it appears a large chunk of the Python neovim community is unaware of this option, as for example [LunarVim](https://github.com/ChristianChiarulli/LunarVim/blob/master/lua/lsp/python-ls.lua) does not expose it (while exposing `typeCheckingMode`) and, while subjectively, general discussion on Pyright over at [/r/neovim](https://www.reddit.com/r/neovim). Thus, such a change in defaults might be appreciated.

I'd wanted to get thoughts on this first prior to rushing to a PR :)

**Comment by mjlbach** [comment]
That's probably fine? Seems like a small change.
