### ISSUE TITLE
Unable to specify buildFlags to support golang build tags / build constraints for gopls

### ISSUE THREAD

**Issue by sieuwerts** [neovim/nvim-lspconfig#888]
- `nvim --version`:
NVIM v0.5.0-dev+ad8114444
Build type: Release
LuaJIT 2.1.0-beta3

- nvim-lsp version(commit hash): `5085668d62214992298b56ad9c73905a94526fe2`
- What language server (If the problem is related to a specific language server): `gopls`
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
The problem exists over different clients, but e.g. vscode have support for specifying buildFlags which solves the issue, meaning that gopls has support for it:

```
"gopls": {
    "buildFlags": ["-tags=integration"]
}
```

So I would like a way to configure gopls for nvim-lsp with this information.

- Can you reproduce this behaviour on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): N/A
- Is the problem isolated to a particular language server: Yes
- Operating system/version: MacOS Catalina

### How to reproduce the problem from neovim startup
Use gopls, open a .go file with [build tags](https://golang.org/pkg/go/build/#hdr-Build_Constraints) at the top, e.g:
`// +build integration`. Then try to use completions or diagnostics in that file.

### Actual behaviour
Completions, diagnostics, etc. simply aren't working.

### Expected behaviour
As if the file was not tagged with a build constraint.

### Minimal init.vim or init.lua and code sample
```
lua << EOF
local lspconfig = require'lspconfig'
lspconfig.gopls.setup{
  on_attach = require'completion'.on_attach;
}
EOF
```

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: gopls: configuration checked.
</details>

**Comment by mjlbach** [comment]
This is a usage question, which belongs on our [discourse](https://neovim.discourse.group/). You're able to specify everything you would on vscode in our client, through the`settings` and `init_options` keys. I'm guessing what you're looking for is 
```lua
lua << EOF
local lspconfig = require'lspconfig'
lspconfig.gopls.setup{
  on_attach = require'completion'.on_attach;
  settings = { gopls =  {
    buildFlags =  {"-tags=integration"}
  }
}
EOF
```

**Comment by sieuwerts** [comment]
Thank you. I will look into the discourse.
When applying the build flags in your example I still got an error, since it looks like that makes `go version` also use the tag (I don't know if this is intended) which renders this error on opening up a file:

```
flag provided but not defined: -tags
usage: go version [-m] [-v] [file ...]
Run 'go help version' for details.
```

I did manage to solve the issue though, so for anyone experiencing the same issue:
I created a table to set the `GOFLAGS` environment variable using the [gopls.env](https://github.com/golang/tools/blob/dd255f23517e12f99e036a76f0b414cbadfe50cd/gopls/doc/settings.md#env-mapstringstring) setting:

```
lua << EOF
local lspconfig = require'lspconfig'
local envs = {}
envs["GOFLAGS"] = "-tags=integration"
lspconfig.gopls.setup{
  on_attach = require'completion'.on_attach;
  settings = {
    gopls =  {
      env = envs
    }
  }
}
EOF
```

**Comment by adonespitogo** [comment]
I'm getting error when  using multiple tags:

```
err: exit status 1: stderr: go: parsing $GOFLAGS: non-flag "dev"
```

I've tried using `GOFLAGS` env variable and the `buildFlags` option with no luck.

**Comment by tscales** [comment]
For those who use LazyVim

```lua
return {
  "nvim/nvim-lspconfig",
  opts = {
    servers = {
      gopls = {
        settings = {
          gopls = {
            buildFlags = { "-tags=integration" },
          },
        },
      },
    },
  },
}
```

**Comment by cl1ckname** [comment]
Should I open PR to add this to configs.md and configs.txt?
