### ISSUE TITLE
Not loading configuration from packages (pack/name/opt/) anymore

### ISSUE THREAD

**Issue by zegervdv** [neovim/nvim-lspconfig#890]
### How to reproduce the problem from neovim startup
I have a custom lsp configuration in a package (under `pack/pkgname/opt/toolname/lua/lspconfig/toolname.lua`) and since the dofile change (04f223f3d08388eac74a571516145154bf5af64c) it seems this file is no longer loaded by lspconfig.

### Actual behaviour
I get an error that the configuration table is nil:
```
E5113: Error while calling lua chunk: ...re/nvim/runtime/pack/vim-pkg/opt/toolname/lua/config.lua:237: attempt to index field 'toolname' (a nil value) 
```

### Expected behaviour
Load the config.

I've confirmed it works by reverting to the commit before the change.

**Comment by mjlbach** [comment]
Yep, that's not supported anymore (and never officially was). You'll have to change your configuration of language servers to match our readme.
