### ISSUE TITLE
Am I the only one where both `pyls` and `pylsp` are not attaching?

### ISSUE THREAD

**Issue by Sammyalhashe** [neovim/nvim-lspconfig#893]
- `nvim --version`: v0.5.0-dev+1260-ga6504ec33
- nvim-lsp version(commit hash): 0a921bf2be74d293c8a8d6dd70122c1d01151a30
- What language server (If the problem is related to a specific language server): pyls/pylsp
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): Yeah
- Is the problem isolated to a particular language server: Just the python ones
- Operating system/version: Ubuntu 10.04.2 LTS (WSL)

### How to reproduce the problem from neovim startup
Open any Python file with the following config
`nvim_lsp["pylsp"].setup{}`

### Actual behaviour
`:LspInfo` returns that there are 0 clients attached to server (and active), but the command is detectable and exectable.

### Expected behaviour
The client attached

### Minimal init.vim or init.lua and code sample

```lua
local nvim_lsp = require'lspconfig'
nvim_lsp["pylsp"].setup{}
```

### Health check
<details>
<summary>Checkhealth result</summary>

</details>
`INFO: pylsp: configuration checked`

### LSP log

<details>
<summary>Log file</summary>

I looked through it, there didn't seem to be much useful. There were some error messages from `rpc.lua` line 457 that `pylsp` was missing some modules like `yapf` and other formatters, but I fail to see why that would matter.
</details>

Worth to know that when I manually run `:LspStart pylsp` it works.

**Comment by mjlbach** [comment]
I need the actual log. Pyls is used by many, so I assume that it is an issue with your installation or setup.

**Comment by mjlbach** [comment]
I'm guessing this is a root-directory issue. Is your project in a git config or does it havea file that mathes root directories from CONFIG.md?  Did you try the debugging steps in the readme?

**Comment by Sammyalhashe** [comment]
Hey, sorry for getting back so late, I'll check these out tonight. I'll also give the log.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by ecly** [comment]
Just to be clear, should your config not simply say:
```
local nvim_lsp = require'lspconfig'
nvim_lsp["pyls"].setup{}
```
ie. "pylsp" -> "pylsp".

Seems to me like it might just be a simple typo?
At least I don't see `pylsp` as a possible option in CONFIG.md

**Comment by Sammyalhashe** [comment]
Sorry for the delay, here is the log
```
[ START ] 2021-05-11T00:32:15-0400 ] LSP logging initiated
[ START ] 2021-05-11T00:33:06-0400 ] LSP logging initiated
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,889 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'autopep8': No module named 'pycodestyle'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,894 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'mccabe': No module named 'mccabe'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,895 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'pycodestyle': No module named 'pycodestyle'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,895 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'pydocstyle': No module named 'pydocstyle'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,896 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'pyflakes': No module named 'pyflakes'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,896 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'pylint': No module named 'pylint'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,897 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'rope_completion': No module named 'rope'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,898 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'rope_rename': No module named 'rope'\n"
[ ERROR ] 2021-05-11T00:33:30-0400 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pylsp"	"stderr"	"2021-05-11 00:33:30,898 UTC - WARNING - pylsp.config.config - Failed to load pylsp entry point 'yapf': No module named 'yapf'\n"
[ START ] 2021-05-11T00:36:22-0400 ] LSP logging initiated
[ START ] 2021-05-11T00:38:30-0400 ] LSP logging initiated

```'
So obviously I'm missing stuff, but I used to use pyls fine and it just worked. New machine, new issues I guess. I don't recall having to install any other modules.

**Comment by mjlbach** [comment]
I verified everything is working as expected.

1. `mkdir test && cd test && git init`
2. touch main.py
3. `conda create -n repro`
4. `conda activate repro`
5. `pip install 'python-lsp-server[all]' (You need [all] for completion *and* error checking)
6. nvim main.py
7. Enjoy errors and completion

If you have additional problems, please ask on the discourse.

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/i-have-been-unable-to-setup-neovim-lsp-for-python-nothing-seems-to-work/1141/1

**Comment by Sammyalhashe** [comment]
So I figured it out. I had a `python.vim` file in my `ftplugin` directory. I tried removing each line but it seems like the presence of any command in that file will cause the lsp servers not to load on attach. Is this meant to happen? Removing the file or removing all the contents of the file causes the lsp servers to attach on open.
