### ISSUE TITLE
html language server not working

### ISSUE THREAD

**Issue by gmr458** [neovim/nvim-lspconfig#894]
- `nvim --version`: v0.5.0-dev+1191-gf89bfa686
- nvim-lsp version(commit hash): `0a921bf`
- What language server (If the problem is related to a specific language server): html
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): No
- Is the problem isolated to a particular language server: Just html language server
- Operating system/version: Windows 10 Home Single 20H2

### How to reproduce the problem from neovim startup
Just open an `.html` file

### Actual behaviour
`E5113: Error while calling lua chunk: %USERPROFILE%\AppData\Local\nvim\init.lua:39: Vim(lua):E5108: Error executing lua ...ols\neovim\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:380: start 'html-languageserver' failed: ENOENT: no such file or directory
Error detected while processing FileType Autocommands for "html":
E5108: Error executing lua ...ols\neovim\Neovim\share\nvim\runtime\lua\vim\lsp\rpc.lua:380: start 'html-languageserver' failed: ENOENT: no such file or directory`

### Expected behaviour
The behavior I expect is that the autocomplete works

### Minimal init.vim or init.lua and code sample
![image](https://user-images.githubusercontent.com/53343401/117771147-69828080-b1fb-11eb-978f-ff80e5806a4b.png)

### Health check
<details>
<summary>Checkhealth result</summary>

`INFO: html: configuration checked.`
</details>

### LSP log

<details>
<summary>Log file</summary>

Sorry I couldn't find it in Windows
</details>

**Comment by mjlbach** [comment]
Did you read the windows section of the readme?
