### ISSUE TITLE
Message "Client 1 quit with exit code 1 and signal 0"

### ISSUE THREAD

**Issue by saahiluppal** [neovim/nvim-lspconfig#895]
NVIM v0.5.0-dev+1316-g5c9b4948d
Build type: RelWithDebInfo
NVIM-LSP commit hash: 0a921bf2be74d293c8a8d6dd70122c1d01151a30
OS: Ubuntu 20.04 LTS

This is my [init.vim](https://github.com/saahiluppal/configfiles/blob/main/nvim/init.vim)
My system have two language servers installed 
1. python (pyright) 
2. golang (gopls)

gopls language server works fine. `:LspInfo says its working`

Following message pops out as soon as i open any python file. `nvim xyz.py` or `:e xyz.py`
```bash
Client 1 quit with exit code 1 and signal 0
```

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
 ========================================================================
 ## Checking language server protocol configuration
   - INFO: gopls: configuration checked.
   - INFO: pyright: configuration checked.
</details>

### LSP log
<details>
<summary>Log file</summary>
[ START ] 2021-05-11T16:28:12+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:28:16+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:32:58+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:33:13+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:34:13+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:35:23+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:36:52+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:37:47+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:40:14+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:40:18+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:40:24+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:41:02+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:41:22+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:41:40+0530 ] LSP logging initiated
[ START ] 2021-05-11T16:42:11+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T16:42:12+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T19:38:32+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T19:38:35+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T19:39:03+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T19:39:04+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T19:41:44+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T19:41:48+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T19:41:50+0530 ] LSP logging initiated
[ START ] 2021-05-11T19:42:45+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T19:42:46+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T19:46:35+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T19:46:36+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T19:49:30+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T19:49:30+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T19:52:31+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T19:52:32+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T20:08:32+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T20:08:33+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ START ] 2021-05-11T20:15:07+0530 ] LSP logging initiated
[ START ] 2021-05-11T20:15:34+0530 ] LSP logging initiated
[ START ] 2021-05-11T20:16:21+0530 ] LSP logging initiated
[ START ] 2021-05-11T20:21:12+0530 ] LSP logging initiated
[ ERROR ] 2021-05-11T20:21:13+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:457 ]	"rpc"	"pyright-langserver"	"stderr"	"internal/modules/cjs/loader.js:638\n    throw err;\n    ^\n\nError: Cannot find module 'worker_threads'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:562:25)\n    at Module.require (internal/modules/cjs/loader.js:692:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)\n    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)\n"
[ INFO ] 2021-05-11T20:25:47+0530 ] /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1213 ]	"exit_handler"	{}

  ~/Workspace/golang   master ?1                                                                                                 mlp-mixer
❯ 
</details>

PS: Refer this `nvim-compe` [thread](https://github.com/hrsh7th/nvim-compe/issues/303)

**Comment by saahiluppal** [comment]
I've updated the issue
and i'm using Ubuntu 20.04

**Comment by lithammer** [comment]
Looks like a problem with the Pyright installation itself, or Node. What happens if you just run `pyright-langserver --stdio` on the command-line?

**Comment by saahiluppal** [comment]
Yes, This error happens
```bash
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.5013 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:603)
    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)
    at Object.8863 (/usr/local/lib/node_modules/pyright/dist/pyright-internal.js:1:1002470)
    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)
    at Object.5822 (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:48)
    at s (/usr/local/lib/node_modules/pyright/dist/pyright-langserver.js:1:743)
```

How to correct the installation?

**Comment by mjlbach** [comment]
How did you install pyright? Did you follow the instructions in CONFIG.md?

**Comment by mjlbach** [comment]
Great! Glad you figured it out.
