### ISSUE TITLE
Windows: vimL function must not be called in a lua loop callback

### ISSUE THREAD

**Issue by EdenEast** [neovim/nvim-lspconfig#899]
- `nvim --version`: NVIM v0.5.0-dev+1318-g61aefaf29
- nvim-lsp version(commit hash): 0a921bf
- Operating system/version: 10.0.19041 Build 19041

Following the instructions in the readme to work around `.cmd` issue on windows presents the error.

```
init.lua E5560: vimL function must not be called in a lua loop callback
```

Current code in readme added to init.lua

```lua
vim.loop.spawn = (function ()
  local spawn = vim.loop.spawn
  return function(path, options, on_exit)
    local full_path = vim.fn.exepath(path)
    return spawn(full_path, options, on_exit)
  end
end)()
```

**Comment by mjlbach** [comment]
Please don't delete the issue template. I can't reproduce this.

**Comment by EdenEast** [comment]
Sorry I should have added repro steps. Adding the above code block to the top of `minimal_init.lua` and having packer initialize causes the error to occur. 

```lua
vim.loop.spawn = (function ()
  local spawn = vim.loop.spawn
  return function(path, options, on_exit)
    local full_path = vim.fn.exepath(path)
    return spawn(full_path, options, on_exit)
  end
end)()

-- install packer
local fn = vim.fn

local install_path = '/tmp/nvim/site/pack/packer/start/packer.nvim'

vim.cmd [[set packpath=/tmp/nvim/site]]

-- ....
```

```sh
rm -rf /tmp/nvim/site/pack
nvim -u minimal_init.lua 
```

It seems related to packer and how it uses `vim.loop.spawn` for it jobs.

**Comment by mjlbach** [comment]
Thanks, I know what it is now, it's the call to vim.fn.exepath which invokes vimscript.

**Comment by mjlbach** [comment]
I've removed the offending workaround from the readme, you can follow the upstream discussion for discussion about how to avoid having to postpend all commands with `.cmd`
