### ISSUE TITLE
elmls not discovering definition of certain functions

### ISSUE THREAD

**Issue by aotarola** [neovim/nvim-lspconfig#901]
- `nvim --version`: v0.5.0-dev+61aefaf29
- nvim-lsp version(commit hash): 0a921bf2be74d293c8a8d6dd70122c1d01151a30
- What language server (If the problem is related to a specific language server): `elmls`
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): No
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): No
- Is the problem isolated to a particular language server: Yes
- Operating system/version: macOS Big Sur, Version 11.3.1

### How to reproduce the problem from neovim startup

install elm-language-server and load up a minimal elm application with `mdgriffith/elm-ui` library installed:

```sh
$ npm install -g @elm-tooling/elm-language-server elm-format elm-test
$ elm init
$ elm install mdgriffith/elm-ui
```

write a simple app:

```elm
  
module Main exposing (main)

import Element exposing (..)
import Element.Border as Border
import Html exposing (Html)
import Random



-- vim.lsp.buf.definition() works on `Random.rounded`


border =
    Border.rounded 10


-- vim.lsp.buf.definition() works on `Random.int`


singleDigit : Random.Generator Int
singleDigit =
    Random.int 0 9



-- vim.lsp.buf.definition() does not work on `layout`, `el` or `text`


main : Html msg
main =
    layout [] <| el [ border ] <| text "Hello World"
```

### Actual behaviour

When using `:lua vim.lsp.buf.definition` or `gd` on `layout`, `el` or `text`, no definition is found

### Expected behaviour

When using `:lua vim.lsp.buf.definition` or `gd` on `layout`, `el` or `text`, definition is found

*NOTE*: Definition discovery works in VSCode using the same version of `elm-language-server`

### Minimal init.vim or init.lua and code sample

Code sample and minimal `init.lua` can be found in https://github.com/aotarola/elm-nvim

### Health check
<details>
<summary>Checkhealth result</summary>

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color
  - WARNING: Neither Tc nor RGB capability set. True colors are disabled. 'termguicolors' won't work properly.
    - ADVICE:
      - Put this in your ~/.tmux.conf and replace XXX by your $TERM outside of tmux:
          set-option -sa terminal-overrides ',XXX:RGB'
      - For older tmux versions use this instead:
          set-option -ga terminal-overrides ',XXX:Tc'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: pyenv: Path: /usr/local/Cellar/pyenv/1.2.26/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /Users/aotarola/.pyenv
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.         - ERROR: Python provider error:                                                                                                 - ADVICE:
      - provider/pythonx: Could not load Python 2:                                                                                      /Users/aotarola/.pyenv/shims/python2 does not have the "neovim" module. :help provider-python                                 /Users/aotarola/.pyenv/shims/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.                                                                         /Users/aotarola/.pyenv/shims/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)                                                                                                 - INFO: pyenv: Path: /usr/local/Cellar/pyenv/1.2.26/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.                                                               - INFO: pyenv: Root: /Users/aotarola/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.                                          - INFO: Executable: /Users/aotarola/.pyenv/versions/3.8.3/bin/python3
  - INFO: Python version: 3.8.3                                                                                                 - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin20]
  - INFO: Host: /Users/aotarola/.rbenv/shims/neovim-ruby-host

</details>

### LSP log

<details>
<summary>Log file</summary>

[ DEBUG ] 2021-05-12T13:58:59-0700 ] ...neovim/HEAD-61aefaf_2/share/nvim/runtime/lua/vim/lsp.lua:894 ]  "LSP[elmls]"    "client.request"      1       "textDocument/definition"       {  position = {    character = 4,    line = 30  },  textDocument = {    uri = "file:///Users/aotarola/dev/elm-nvim/src/Main.elm"  }}  <function 1>    1
[ DEBUG ] 2021-05-12T13:58:59-0700 ] ...im/HEAD-61aefaf_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:390 ]  "rpc.send.payload"   {  id = 2,  jsonrpc = "2.0",  method = "textDocument/definition",  params = {    position = {      character = 4,      line = 30    },    textDocument = {      uri = "file:///Users/aotarola/dev/elm-nvim/src/Main.elm"    }  }}
[ DEBUG ] 2021-05-12T13:58:59-0700 ] ...im/HEAD-61aefaf_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  jsonrpc = "2.0",  method = "window/logMessage",  params = {    message = "A definition was requested",    type = 3  }}
[ DEBUG ] 2021-05-12T13:58:59-0700 ] ...neovim/HEAD-61aefaf_2/share/nvim/runtime/lua/vim/lsp.lua:679 ]  "notification"  "window/logMessage"   {  message = "A definition was requested",  type = 3}
[ DEBUG ] 2021-05-12T13:58:59-0700 ] ...AD-61aefaf_2/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]  "default_handler"    "window/logMessage"      {  client_id = 1,  params = {    message = "A definition was requested",    type = 3  }}
[ INFO ] 2021-05-12T13:58:59-0700 ] ...AD-61aefaf_2/share/nvim/runtime/lua/vim/lsp/handlers.lua:414 ]   "A definition was requested"
[ DEBUG ] 2021-05-12T13:58:59-0700 ] ...im/HEAD-61aefaf_2/share/nvim/runtime/lua/vim/lsp/rpc.lua:491 ]  "decoded"       {  id = 2,  jsonrpc = "2.0",  result = vim.NIL}
[ DEBUG ] 2021-05-12T13:58:59-0700 ] ...AD-61aefaf_2/share/nvim/runtime/lua/vim/lsp/handlers.lua:442 ]  "default_handler"    "textDocument/definition"        {  bufnr = 1,  client_id = 1}
[ INFO ] 2021-05-12T13:58:59-0700 ] ...AD-61aefaf_2/share/nvim/runtime/lua/vim/lsp/handlers.lua:294 ]   "textDocument/definition"     "No location found"
</details>

**Comment by mjlbach** [comment]
Did you try reverting the elm language server? There's currently some issues with the latest version: https://github.com/elm-tooling/elm-language-server/issues/598

**Comment by aotarola** [comment]
Oh, yeah, after trying with version `2.0.3`, the bug is gone. It seems the issue is in `elm-language-server@2.1.0`. Should we wait for resolution from the author's side before closing this one? if not feel free to close this issue 👍🏼

**Comment by mjlbach** [comment]
I would just follow the upstream issue, I don't think it's something on our end :)
