### ISSUE TITLE
High ram issue

### ISSUE THREAD

**Issue by pulme** [neovim/nvim-lspconfig#913]
![unknown](https://user-images.githubusercontent.com/83711649/118555678-d5fd0280-b75a-11eb-859a-23993325326b.png)

i don't have any node running if close it i have just chromium and pcmanfm 
every  time i open project the fun start to spin hardly :-(

**Comment by mjlbach** [comment]
Please do not delete the issue template.

nvim-lspconfig is a lua plugin, it doesn't use nodejs. I assume this is your language server (I have no idea which one since you deleted the issue template). File an upstream bug with the language server if the memory usage is high.
