### ISSUE TITLE
Runtime custom server args

### ISSUE THREAD

**Issue by Nazeehe** [neovim/nvim-lspconfig#915]
Hi!

As I am migrating from coc to nvim client lsp, I noticed a difference in behavior. With Coc-omnisharp, I load up nvim, load a .cs file from my projects via startify, everything loads fine and works. Same flow with client lsp will give me a bunch of errors in the file simply because I did not cd to the project root dir first before loading the file. 

Looking at the code for coc-omnisharp, I can see why it works that way. It utilizes the --source argument of omnisharp to pass in the path to the .sln file it searched for given the path of the .cs file that started it. 

Is there a way in lspconfig today to do something like that? Have a function run when I load up a .cs file, search the folder structure (same as root_pattern works) and returns the path to a sln file if found as a value to the --source argument? 

Thanks!!

**Comment by mjlbach** [comment]
Ooh this is actually a good question, I've wanted to improve C# support for awhile. For now, we can leverage "on_new_config" for this to modify the cmd (see julia). Is there not a way to pass --source on runtime/during initialization? Otherwise we might have to add a before_start hook to lspconfig.

**Comment by Nazeehe** [comment]
> Is there not a way to pass source on runtime/during initialization (after the server has started? Otherwise we might have to add a before_start hook to lspconfig for proper support.

I am not super familiar with their code, so maybe? hard to tell. I don't see why they would have implemented that. Safe to say that the way to do it is the way they provide via the --source argument. I'll take a look at on_new_config right now to see if that helps!

**Comment by mjlbach** [comment]
A lot of servers offer optional command line args or passing it via initializationOptions or settings (via didChangeConfiguration) after the server has already started. If not, it's not really a problem, just before we haven't had any servers that need to dynamically change their args based on the particular project (only settings) so we may have to add a new pre_start hook :)

**Comment by Nazeehe** [comment]
Ok, just did a quick search in the omnisharp repro for didChangeConfiguration and got zero hits. So doesn't look like they support it. Pre_start hook sounds like a good plan!

**Comment by mjlbach** [comment]
FWIW there is a to-do in the code asking for configuration of the applicationRoot via RPC instead of with the command line flag here: 

https://github.com/OmniSharp/omnisharp-roslyn/blob/60119138e586c52725d9341f3e5c4f624a7276fd/src/OmniSharp.LanguageServerProtocol/LanguageServerHost.cs#L198-L200

**Comment by Nazeehe** [comment]
Interesting. Good thing they have that on their roadmap. I'd imagine making it would require quite a bit of work though. Having the server load a different project and reset all of its internal state correctly will be interesting.

**Comment by snezhniylis** [comment]
On `nvim-lspinstall` side this was [solved](https://github.com/kabouzeid/nvim-lspinstall/commit/1b43f88abf129e19017edb4dbec61e3eb2718bdc) by utilizing `on_new_config` callback.

**Comment by mjlbach** [comment]
Yup, I initially suggested that :) 

https://github.com/neovim/nvim-lspconfig/issues/915#issuecomment-842723532

**Comment by mjlbach** [comment]
You can use on_new_config for this, closing.
