### ISSUE TITLE
LspStart yaml not working

### ISSUE THREAD

**Issue by Chiodood** [neovim/nvim-lspconfig#923]
Using my fork of lsp-install so I can install the yaml ls (https://github.com/Chiodood/nvim-lspinstall)

The ls installs correctly but does not attach to .yml/.yaml files.

Running :LspStart yaml displays the following

`E5108: Error executing lua ...site/pack/packer/start/nvim-lspconfig/lua/lspconfig.lua:29: attempt to index a nil value`

**Comment by mjlbach** [comment]
Do not delete the issue template.
