### ISSUE TITLE
Clang-tidy diagnostics via clangd

### ISSUE THREAD

**Issue by JohannesRuder** [neovim/nvim-lspconfig#925]
Hi all,

thanks for all that great work on neovim lsp. Is it possible to get clang-tidy diagnostics via clangd?

Best regards
Johannes

**Comment by lithammer** [comment]
Refer to our [discourse](https://neovim.discourse.group) for discussion and usage questions. The issue tracker is only for bugs.

With that said. It should generally work out-of-the-box. It does for me at least with this minimal `init.vim`:

```vim
packadd nvim-lspconfig

lua << EOF
local lspconfig = require('lspconfig')
lspconfig.clangd.setup({})
EOF
```
