### ISSUE TITLE
Relative import path "react" not prefixed with

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/nvim-lspconfig#927]
I get an error when using tsserver.

### How to reproduce the problem

1. `create-react-app --template typescript myapp`
2. `cd myapp`
3. `nvim src/index.tsx`

### Screenshot
<img width="1916" alt="スクリーンショット 2021-05-22 12 11 40" src="https://user-images.githubusercontent.com/3197942/119212973-e6b0ce00-baf6-11eb-83e1-9d8365a9771c.png">

**Comment by nabezokodaikon** [comment]
It occurred when it was set at the same time as deno.

**Comment by abenz1267** [comment]
Why did you close this? Did you find a solution? Could you at least post it in here?

**Comment by nabezokodaikon** [comment]
I thought it was a mistake to set it at the same time as deno.
It occurred in the following cases.
```vim
lua require'lspconfig'.denols.setup{}
lua require'lspconfig'.tsserver.setup {}
```

**Comment by abenz1267** [comment]
well, i'm not running tsserver, only denols. i still get those errors.

**Comment by nabezokodaikon** [comment]
The languages are the same and coexistence will be difficult.

**Comment by cjnucette** [comment]
When deno is used in VSCode or nvim with coc, they would disable deno by default and use a local configuration where you should enable deno for the current project (I suppose this disable tsserver). How would you do this with lsp?

**Comment by nabezokodaikon** [comment]
@cjnucette It's provisional, but for example
```lua
lsp.denols.setup{
    root_dir = lsp.util.root_pattern('deps.ts')
}

lsp.tsserver.setup {
    root_dir = lsp.util.root_pattern('package.json')
}
```
or
```lua
function file_exists(name)
    local f = io.open(name, 'r')
    if f ~= nil then io.close(f) return true else return false end
end

if file_exists(os.getenv('PWD')..'/package.json') then
    lsp.tsserver.setup {}
else
    lsp.denols.setup{}
end
```
