### ISSUE TITLE
Trying to use lsp references: Error executing vim.schedule lua callback: ...user/.vim/plugged/nvim-lsputils/util.lua:89: attempt to index local 'var' (a userdata value)

### ISSUE THREAD

**Issue by qazip** [neovim/nvim-lspconfig#928]
I have a keybind to use LSP references and this is the error I am getting:

`Error executing vim.schedule lua callback: ...user/.vim/plugged/nvim-lsputils/util.lua:89: attempt to index local 'var' (a userdata value)`

I have this in my config:
`  buf_set_keymap('n', '<C-e>', '<cmd>lua vim.lsp.buf.references()<CR>', opts)`

This worked perfectly a few days ago. Dunno why it is not working now... Any changes from your side?

**Comment by mjlbach** [comment]
If there was, it would be in core, not lspconfig. Seems like this is a bug internal to nvim-lsputils

**Comment by qazip** [comment]
Ah, sorry about that @mjlbach. It is indeed there and there is already an issue raised: https://github.com/RishabhRD/nvim-lsputils/issues/26
