### ISSUE TITLE
html characters in pyright 

### ISSUE THREAD

**Issue by sujaybokil** [neovim/nvim-lspconfig#936]
Hello, I am using the latest Neovim 0.5.0 dev version with the latest version of nvim-lspconfig plugin at the time of this issue. While performing autocomplete using pyright with neovim lsp + completion.nvim, it renders many nbsp tags inside the completion panel, due to which the attributes of the function are not recognized. Here's an example.

![image](https://user-images.githubusercontent.com/62012185/119371886-73fd4980-bcd4-11eb-95c0-0c38d52189a0.png)

I'm not sure whether this is the right place to raise the issue, and I apologize if it is not. Kindly guide me to the correct place in that case. I have included the lines in my config related to autocompletion also.

![image](https://user-images.githubusercontent.com/62012185/119372355-d8b8a400-bcd4-11eb-8f85-0c9fab44f48d.png)

**Comment by mjlbach** [comment]
Don't delete the issue template.

This problem will not occur (at least not with the severity you've shown it), if you use the minimal config on the latest version of neovim with up to date runtime files. You would have used the minimal config had you followed the issue template. Make sure neovim is up to date, remove plugins like lspsaga that override hover behavior.

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/13316262/119374540-8b095080-bc6e-11eb-87de-2c7c5d8fe69e.png">

**Comment by sujaybokil** [comment]
Heyy, I tried what you said, I used an init.vim file earlier but shifted to init.lua and tried out a minimal installation with nothing but nvim-lspconfig (to make sure no plugin affected it). Checkhealth shows fine for lspconfig. I have both updated Neovim, nvim lsp, but just nothing seems out to be working. If you have any clue, please let me know what the issue could be.

**Comment by sujaybokil** [comment]
Just an update, I tried out "hrsh7th/nvim-compe" plugin for autocompletion instead of "nvim-lua/completion-nvim" that I originally used and it gives the same output as yours, so it was a problem with that so I'll probably post it there. Appreciate the quick replies, thank you.
