### ISSUE TITLE
[Question] Disable every interface interaction

### ISSUE THREAD

**Issue by kaldown** [neovim/nvim-lspconfig#939]
Reading https://github.com/neovim/nvim-lspconfig/issues/662
but how to disable everything?

I want lsp to just be lsp, not to change anything else.
Since interface change is more convenient for me from the other package (CoC)

**Comment by mizlan** [comment]
What in particular do you want to disable? lspconfig is just a tool to help configure language servers that communicate with neovim's lsp client based on a set of rules.

**Comment by kaldown** [comment]
> What in particular do you want to disable? lspconfig is just a tool to help configure language servers that communicate with neovim's lsp client based on a set of rules.

staff like this, from a refered issue:

```
vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
    vim.lsp.diagnostic.on_publish_diagnostics, {
        virtual_text = false
    }
)
```
lspconfig is not only a client, it changes my vim experience by default.
I'd rather disable all, and enable what is neccesarry.
But, again, referring to the issue at the initial post - it looks complicated to do this one by one.

Is there any "global" tumbler?

**Comment by mjlbach** [comment]
lspconfig is not a client. did you read the readme? these are all configuration of the built-in language server client in *neovim/neovim*

All lspconfig does is launch a language server for you, *neovim/neovim* is the one that automatically displays diagnostics.

You should not be using coc.nvim and the built-in client at the same time.

**Comment by MrZhang123** [comment]
for neovim 0.6.0+，use this config can disable diagnostic
```
vim.diagnostic.config({
	underline = false,
	virtual_text = false,
	signs = false,
})
```

for more setting, you can find in [neovim docs](https://neovim.io/doc/user/diagnostic.html)
