### ISSUE TITLE
Feature Request: mint ls 

### ISSUE THREAD

**Issue by jgarte** [neovim/nvim-lspconfig#941]
The language server for [mint](https://www.mint-lang.com/) is built into the language itself.

See here:

https://github.com/mint-lang/mint/tree/df3ac8b3ef81a2f3a5e46ccc09d8a1b3cd16066e/src/ls

and here:

https://spectrum.chat/mint-lang/development/language-server-support~227be091-fb65-40fb-ab60-952be791b28d

**Comment by lithammer** [comment]
- What's the command to start the language server?
- What would be appropriate root markers?
- What's the `filetype`?

**Comment by mjlbach** [comment]
Hi, please don't delete the issue template.

We don't do requests for adding new language servers (it's community contributed). Please look at one of the other PRs for adding a language server and file a PR. Thanks!
