### ISSUE TITLE
Requesting integration of language server for mathematica 

### ISSUE THREAD

**Issue by physicophilic** [neovim/nvim-lspconfig#942]
Hi

There's an LSP for wolfram language here:
https://github.com/kenkangxgwe/lsp-wl

It also works with coc using this plugin: 
https://github.com/voldikss/coc-lsp-wl

I was wondering how difficult it would be to integrate it here? 
If a bit noob friendly instruction can be given I can try this myself just for fun.

**Comment by lithammer** [comment]
It's probably fairly straight forward. The tricky part is that there's no reliable `cmd` you can use you since you need to point it to a local clone of the lsp-wl repo. Though that seems to be true for coc-lsp-wl as well. Maybe something like test (untested)?

```lua
local lspconfig = require "lspconfig"
local configs = require "lspconfig/configs"
local util = require "lspconfig/util"

if not lspconfig.lsp_wl then
  configs.lsp_wl = {
    default_config = {
      cmd = {"wolfram", "-script", "/absolute/path/to/lsp-wl/init.wls"},
      filetypes = {"mma", "wl"},
      root_dir = util.path.dirname,
      settings = {}
    }
  }
end

lspconfig.lsp_wl.setup {
  -- ...
}
```

Note that you need to updated `cmd` with the correct path to the `init.wls` file.

**Comment by mjlbach** [comment]
Hi,  please don't delete the issue template.

We don't do integration requests. It should be easy to file a PR by looking at the other PRs offering language server integration.

**Comment by physicophilic** [comment]
@lithammer  Thank you, I tested and got lsp_wl detected for `mma`,  but it crashed with error 1 - this appears to be an issue with `lsp-wl`. I will try doing the rest myself.

@mjlbach I didn't delete anything. There was an option to choose a blank thread by github. 

> We don't do integration requests. It should be easy to file a PR by looking at the other PRs offering language server integration.

I understand and respect that. Please continue with your priorities.
