### ISSUE TITLE
.git location taken as root instead of Cargo.toml, leads rust-analyzer failed to discover workspace

### ISSUE THREAD

**Issue by comicfans** [neovim/nvim-lspconfig#953]
seems that when .git dir existed in parent dir, lspconfig takes its location as root, and ignore Cargo.toml location , which make rust-analyzer not work.

- `nvim --version`:  NVIM v0.5.0-dev+1357-g192f89ea1
- nvim-lsp version(commit hash): 29ea30f
- What language server (If the problem is related to a specific language server):  rust
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): not tried
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): not tried
- Is the problem isolated to a particular language server: not tried
- Operating system/version: archlinux x86-64

### How to reproduce the problem from neovim startup
using following minimal vimrc
```vim
set nocompatible
call plug#begin('~/.vim/bundle')
"vim-scripts
Plug 'neovim/nvim-lspconfig'
call plug#end()


lua << EOF
vim.lsp.set_log_level(0)

require'lspconfig'.rust_analyzer.setup{
        cmd = {"/home/wangxinyu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer"}
}

EOF
```

create following dir structure:

```bash
mkdir -p $HOME/testdir/another
cd $HOME/testdir/another
cargo new rust
cd $HOME/testdir
nvim another/rust/src/main.rs
```

LspInfo shows:

 1 client(s) attached to this buffer: rust_analyzer

              Client: rust_analyzer (id 1)
                    root:      /home/wangxinyu/testdir/another/rust
                    filetypes: rust
                    cmd:       /home/wangxinyu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer

...

Clients that match the filetype rust:

              Config: rust_analyzer
                    cmd:               /home/wangxinyu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer
                    cmd is executable: True
                    identified root:   /home/wangxinyu/testdir/another/rust
                    custom handlers:
[correct.log](https://github.com/neovim/nvim-lspconfig/files/6573566/correct.log)

but if 
```bash
mkdir $HOME/testdir/.git
cd $HOME/testdir
nvim another/rust/src/main.rs
```

LspInfo shows:
 1 client(s) attached to this buffer: rust_analyzer

              Client: rust_analyzer (id 1)
                    root:      /home/wangxinyu/testdir
                    filetypes: rust
                    cmd:       /home/wangxinyu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer
...
Clients that match the filetype rust:

              Config: rust_analyzer
                    cmd:               /home/wangxinyu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rust-analyzer
                    cmd is executable: True
                    identified root:   /home/wangxinyu/testdir
                    custom handlers:

and nvim error shows 

LSP[rust-analyzer] rust-analyzer failed to discover workspace 

[lsp.log](https://github.com/neovim/nvim-lspconfig/files/6573534/lsp.log)

### Expected behaviour

lspconfig should always take Cargo.yaml location as first priority. no matter if .git dir existed in parent

### Minimal init.vim or init.lua and code sample
already posted
### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.

</details>

### LSP log
already posted

**Comment by mjlbach** [comment]
We actually parse your cargo.toml for the appropriate root directory, it should never fallback IIRC

https://github.com/neovim/nvim-lspconfig/blob/f9785053a4ef4aaa2d0aac958bc09a1a289d2fbf/lua/lspconfig/rust_analyzer.lua#L18-L28

in multi-crate projects we can't just use the cargo.toml (not yaml), as there might be a cargo.toml below the true root of your project (git is more likely to be correct in this case tbh).

Is there no workspace_root attribute when you run `cargo metadata --no-deps --format-version 1`?

**Comment by comicfans** [comment]
I've added some debug lines:

```lua
 local cargo_metadata = vim.fn.system("cargo metadata --no-deps --format-version 1")
       local cargo_root = nil
+     local dir = os.getenv("PWD")
+     vim.notify(dir)
       if vim.v.shell_error == 0 then
         cargo_root = vim.fn.json_decode(cargo_metadata)["workspace_root"]
+        print(cargo_root)
+      else
+        vim.notify("bad")
        end
```

and seems PWD is always the dir when I start neovim (not changed after I typed :cd in neovim), not the dir of opened files. so cargo command always failed and it fallback to git dir.  and if changed fallback logic to take Cargo.toml first, LspInfo report correct dir.

**Comment by mjlbach** [comment]
should be closed by https://github.com/neovim/nvim-lspconfig/pull/954/files

**Comment by comicfans** [comment]
confirm fixed
