### ISSUE TITLE
Solargraph with the config `solargraph.transport = "external"` seems not working

### ISSUE THREAD

**Issue by noefroidevaux** [neovim/nvim-lspconfig#957]
- `nvim --version`:
NVIM v0.5.0-dev+1377-gbecbb7436

- nvim-lsp version(commit hash):
62c0424

- What language server (If the problem is related to a specific language server):
Solargraph

- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
No

- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
No

- Is the problem isolated to a particular language server:
Yes

- Operating system/version:
macOS 11.4

### How to reproduce the problem from neovim startup

Configure solargraph transport to "external" config in `init.vim`. But it's not working.

### Actual behaviour

Adding settings with `solargraph.transport = "external"` to `lspconfig.solargraph.setup` seems not working

### Expected behaviour

The setting `solargraph.transport` of Solargraph should be taken in account.

### Minimal init.vim or init.lua and code sample

```
call plug#begin()
Plug 'neovim/nvim-lspconfig'
call plug#end()

lua << EOF
local lspconfig = require'lspconfig'
lspconfig.solargraph.setup {
  settings = {
    solargraph = {
      transport = "external"
    }
  }
}
EOF
```

### Health check
<details>
<summary>Checkhealth result</summary>
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - ERROR: solargraph: The given command "solargraph" is not executable.
```
</details>

### LSP log
<details>
<summary>Log file</summary>
```
[ START ] 2021-06-05T22:28:32+0200 ] LSP logging initiated
[ INFO ] 2021-06-05T22:31:07+0200 ] ...neovim/HEAD-becbb74_2/share/nvim/runtime/lua/vim/lsp.lua:1213 ]	"exit_handler"	{}
```
</details>

**Comment by mcritchlow** [comment]
You might have to explicitly setup the `externalServer` information as well, if
you haven't already.

Something like (untested):

```lua
lspconfig.solargraph.setup {
	settings = {
		solargraph = {
		transport = "external",
		externalServer = {
			host = "localhost",
			port = 7658
		}
	},
}
```

I'm planning to try integrating solargraph soon, so I'm curious to hear if you get this working.

**Comment by noefroidevaux** [comment]
@mcritchlow Thank you for your message, but I have already tried that. If you try too, please tell me if you have more success than me.

**Comment by lithammer** [comment]
I might misunderstand. But as far as I know, Neovim only supports communicating with language servers via stdio, not sockets.

**Comment by noefroidevaux** [comment]
It's possible :) But in the CONFIG.md (https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#solargraph), there are the documentation about `solargraph.transport`.

**Comment by lithammer** [comment]
Right. But that documentation is automatically generated from https://github.com/castwide/vscode-solargraph/blob/master/package.json and is just a dump of all available options.

**Comment by mjlbach** [comment]
The neovim core client only support stdio connects for now, there is an open issue for TCP support https://github.com/neovim/neovim/issues/11911

**Comment by noefroidevaux** [comment]
Thank you for the explanation @mjlbach !
