### ISSUE TITLE
I want to suppress warning messages. 

### ISSUE THREAD

**Issue by nabezokodaikon** [neovim/nvim-lspconfig#96]
# Problems summary
A warning message is displayed.

## Expected
I want to suppress warning messages.

## Environment Information

 * nvim-lsp version (SHA1): 7a15a52c0a7d735625ac73dc4d8efe70c5e99707
 * deoplete-lsp version (SHA1): 7a8c44f423bc4339c092a759abaad40131d2c98a
 * deoplete version (SHA1): 5be25591770c5abc7214e8899c4d451c479ac2ec

 * OS: Mac

 * neovim/Vim `:version` output: NVIM v0.5.0-316-g8fe0635e7

Plugins and settings
```toml
[[plugins]]	
repo = 'Shougo/deoplete.nvim'	
hook_add = ''' 	
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'rust': '(\.|::|->)\w',
    \})

call deoplete#custom#option('sources', {
    \ 'rust': ['lsp'],
    \})
   
call deoplete#custom#source('_', 'converters', [
    \ 'converter_remove_paren',
    \ 'converter_remove_overlap',
    \ 'matcher_length',
    \ 'converter_truncate_abbr',
    \ 'converter_truncate_info',
    \ 'converter_truncate_menu',
    \ 'converter_auto_delimiter',
    \])

set completeopt-=preview

call deoplete#enable()	
'''

[[plugins]]
repo = 'Shougo/deoplete-lsp'	

[[plugins]]
repo = 'neovim/nvim-lsp'
hook_add = '''
    command! Scratch lua require'lsp'.makeScratch()
'''
```

`.config/nvim/lua/lsp.lua`
```lua
-- 
local api = vim.api
local M = {}
function M.makeScratch()
    require'nvim_lsp'.rls.setup{}
end
return M
```

## How to reproduce the problem from neovim startup

 1. `$ cargo new issue-rust` 
 2. `$ cd issue-rust`
 3. `$ nvim`
 4. `:Scratch`
 5. `:e src/main.rs`
 6. Type appropriately

<img width="602" alt="スクリーンショット 2020-01-18 15 03 51" src="https://user-images.githubusercontent.com/3197942/72662321-2f4f0780-3a29-11ea-86fd-b468d12ca950.png">

**Comment by irevoire** [comment]
Hello, I'm also interested, did you found a solution?

**Comment by nabezokodaikon** [comment]
I don't know for now ...

**Comment by mjlbach** [comment]
If I'm understanding you right, you want to suppress virtual text. Try adding the following code.

```lua
" LSP settings
" log file location: /Users/michael/.local/share/nvim/vim-lsp.log
:lua << EOF
  -- Add nvim-lspconfig plugin
  local on_attach = function(_, bufnr)
    vim.lsp.handlers["textDocument/publishDiagnostics"] = vim.lsp.with(
      vim.lsp.diagnostic.on_publish_diagnostics, {
        -- disable virtual text
        virtual_text = false,

        -- show signs
        signs = true,

        -- delay update diagnostics
        update_in_insert = false,
      }
    )
EOF
```

**Comment by nabezokodaikon** [comment]
it is complete! Thank you!

**Comment by mjlbach** [comment]
Maybe we should add this into the readme, it's a builtin feature now in neovim core, but a short nod to the docs might be handy

**Comment by 00sapo** [comment]
How to disable warnings also in the sign column?

**Comment by mminski** [comment]
let g:lsp_document_code_action_signs_enabled=0
@00sapo @DonjiKong 
dunno if thats right
