### ISSUE TITLE
Sass (*.scss) files get errors as if CSS files

### ISSUE THREAD

**Issue by benfrain** [neovim/nvim-lspconfig#965]
- `nvim --version`: NVIM v0.5.0-dev+1383-g4ce61742c: 
- nvim-lsp version(commit hash): HEAD-4ce6174_2
- What language server (If the problem is related to a specific language server): 

cssls (npm install -g vscode-css-languageserver-bin)

- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): 

no, works fine in VSCode and Sublime Text

- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): N/A
- Is the problem isolated to a particular language server:
- Operating system/version: macOS  11.4

### How to reproduce the problem from neovim startup
Install `npm install -g vscode-css-languageserver-bin`, use standard `require'lspconfig'.cssls.setup{}` in init file, open a sass (scss file) and try adding something like `@use "./required/_variables" as v;` 

### Actual behaviour
You will see a Warning `Unknown at rule @use` for that line.

### Expected behaviour
You should not see a warning

### Minimal init.vim or init.lua and code sample

Used minimal_lua from link. Test file content:

```scss
@use "./required/_variables" as v;

.post-Bio_Title {
    display: flex;
    padding: 1em 0 0;
    margin: 0;
    border-top: 5px double v.$color-blockquote;
}

```

### Health check
<details>
<summary>Checkhealth result</summary>

health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: cssls: configuration checked.

</details>

### LSP log

<details>
<summary>Log file</summary>
[lsp.log](https://github.com/neovim/nvim-lspconfig/files/6634749/lsp.log)
</details>
<img width="1325" alt="image" src="https://user-images.githubusercontent.com/1318466/121603143-3f152480-ca40-11eb-8ca5-79cfad9888a0.png">

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/lsp-cssls-settings/568/4

**Comment by rudotriton** [comment]
That lang server hasn't been updated for years. Try the css lang server from [vscode-langservers-extracted](https://www.npmjs.com/package/vscode-langservers-extracted) instead and also remember to update the `cmd`.

**Comment by mjlbach** [comment]
> That lang server hasn't been updated for years. Try the css lang server from vscode-langservers-extracted instead and also remember to update the cmd.

We should update the instructions to reference these

**Comment by benfrain** [comment]
> That lang server hasn't been updated for years. Try the css lang server from [vscode-langservers-extracted](https://www.npmjs.com/package/vscode-langservers-extracted) instead and also remember to update the `cmd`.

I’m knew to this so could you clarify what the ‘cmd’ should be with the new server?

then I’ll get it installed and tested. 👍🏻

**Comment by rudotriton** [comment]
> I’m knew to this so could you clarify what the ‘cmd’ should be with the new server?
> 
> then I’ll get it installed and tested. 👍🏻

The setup should look something like this:

```lua
lspconfig.cssls.setup({
    cmd = { "vscode-css-language-server", "--stdio" },
})
```

**Comment by benfrain** [comment]
@rudotriton thanks! I’m pleased to report that’s what I thought it would be but glad I checked 👍🏻👍🏻

**Comment by benfrain** [comment]
That seems to be working, thanks.

BTW, if you can confirm the format for passing setting overrides I'm happy to write it up and send a PR for the docs if it helps?

Eg with Sublime it is JSON format, like

```
"scss.lint.idSelector": "warning",
```

How is the equivalent override configured in Lua with this LS?

**Comment by rudotriton** [comment]
I'm guessing something like this could do it:

```lua
lspconfig.cssls.setup({
  cmd = { "vscode-css-language-server", "--stdio" },
  settings = {
    scss = {
      lint = {
        idSelector = "warning",
      },
    },
  },
})

```

**Comment by benfrain** [comment]
@rudotriton that works great, thanks. Will PR shortly

**Comment by mjlbach** [comment]
@benfrain you don't have these issues with the new server right? If so we can close.

**Comment by benfrain** [comment]
Yes, all good now, thanks for the patience. Appreciate all you are doing here

**Comment by thedaviddelta** [comment]
Hello and thanks everyone for your work in this amazing project.
I'm experiencing a similar issue but related to TailwindCSS instead of SASS.
I have both `cssls` and `tailwindcss` plugins installed and actively running, but the `cssls` one reports not to know the `@tailwind` at rule.

![imagen](https://user-images.githubusercontent.com/6679900/204938742-2cf3cf2d-db3e-4364-a77e-1acccfaa002c.png)

I don't know whether this should be responsibility of one of the other plugin, as obviously  `cssls` is reporting an unknown standard rule inside a standard CSS file, but for example in VSCode (where both of them are taken from) the `tailwindcss` plugin extends the CSS language mode for it to understand them.

Thanks again.
Regards, David.

**Comment by tpAtalas** [comment]
@thedaviddelta Add this setting to ignore the message

```lua
settings = {
  scss = {
    lint = {
       unknownAtRules = 'ignore'
    }
  }
}
```

do same thing to `css` and `less`. It will ignore the message.

**Comment by thedaviddelta** [comment]
Thank you!
That seems to ignore the error reported by `cssls`, despite also ignoring everything else. Can work as a temporal solution.
Unluckily, it seems the original VSC server does have a setting to ignore individual properties but not to ignore individual *at rules*.
