### ISSUE TITLE
rename to nvim-lspconfig

### ISSUE THREAD

**Issue by justinmk** [neovim/nvim-lspconfig#97]
Probably should have anticipated this, but people are confused about nvim-lsp (this repo, not Nvim-builtin) vs vim.lsp (Nvim builtin). Although the nvim-lsp README.md makes it clear, it still confuses people in discussions ([example](https://www.reddit.com/r/neovim/comments/eq48cy/anyone_using_nvimlsp/)), and people who are just getting started.

So we should

- rename this repo to ~~nvim-lspconf~~ `nvim-lsp.configs`
- it also makes sense to rename the Lua module: it is confusing that `require'nvim_lsp'` is distinct from `vim.lsp`, since their names are semantically equivalent
    - see https://github.com/neovim/nvim-lsp/issues/97#issuecomment-583717327

I will do so in the next ~week if there are no objections.

cc @norcalli

**Comment by norcalli** [comment]
No objections. I'm curious if github will handle redirection for cloning, though. It's probably worth a test run on a dummy repo.

**Comment by h-michael** [comment]
@norcalli 
It automsticaly redirects.
https://help.github.com/en/github/administering-a-repository/renaming-a-repository

**Comment by teto** [comment]
nvim-lspconf or nvim-lsp-configs since there are several.
The sooner the better.

**Comment by justinmk** [comment]
Changed my mind again: I am thinking:

- repo name: `nvim-lsp.configs` 
- Lua module: `lsp.configs` 
    - and that's where the `configs` singleton lives instead of wherever it lives right now.
- The various configs live in `lua/configs/*.lua`

I didn't look closely, but it seems like there is no reason for `nvim_lsp.lua`  to be a separate module. It should just be the `lsp.configs` module.

**Comment by teto** [comment]
agreed, the split looks a bit artificial and forces to submit changes across the 2 repo. Having really just the configs here would be best.

**Comment by teto** [comment]
@h-michael do you feel like tackling https://github.com/neovim/nvim-lsp/issues/97#issuecomment-583717327 ?

**Comment by h-michael** [comment]
@teto I'll try this this weekend.

**Comment by justinmk** [comment]
updated https://github.com/neovim/nvim-lsp/issues/97#issuecomment-583717327 names to avoid punctuation.
