### ISSUE TITLE
`lspconfig` doesn't play nicely with `ftplugin`

### ISSUE THREAD

**Issue by cbarrete** [neovim/nvim-lspconfig#970]
- `nvim --version`: NVIM v0.5.0-dev+1397-gf3bcdeb0c
- nvim-lsp version(commit hash): 5ef390d90fbd5f311a967ce708550bab30b79baf
- What language server (If the problem is related to a specific language server): N/A
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): N/A
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): N/A
- Is the problem isolated to a particular language server: N/A
- Operating system/version: Debian 11

### How to reproduce the problem from neovim startup

Have the following as `rust.lua` in any `ftplugin` directory:

```lua
require('lspconfig').rust_analyzer.setup({})
```

Then open a rust file in any project (`cargo new lspconfig` to make a new one if needed) and call `:LspInfo`.

### Actual behaviour

No client is attached, unless rust analyzer is setup in *both* `ftplugin` and `after/ftplugin`.

### Expected behaviour

A client is attached with only one call to `setup` (or a similar, separate function if needed).

More generally, it would be nice to have a way of setting up `lspconfig` per filetype in a non-centralized way: it is more idiomatic, requires evaluating less lua at startup and makes splitting a config more natural.

### Minimal init.vim or init.lua and code sample

```lua
vim.api.nvim_call_function('plug#begin', { vim.fn.stdpath('data') .. '/plugged' })
vim.api.nvim_command([[ Plug 'neovim/nvim-lspconfig' ]])
vim.api.nvim_call_function('plug#end', {})
```

### Health check
<details>
<summary>Checkhealth result</summary>
```
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: rust_analyzer: configuration checked.
```
</details>

### LSP log

<details>
<summary>Log file</summary>
```
[ START ] 2021-06-12T14:55:34+0200 ] LSP logging initiated
[ INFO ] 2021-06-12T14:55:43+0200 ] ...c/.local/share/neovim/share/nvim/runtime/lua/vim/lsp.lua:1213 ]  "exit_handler"  {}
```
</details>

**Comment by mjlbach** [comment]
A couple points:

- The only supported way to configure `lspconfig` is by adding it to init.vim/init.lua
- Most people will benefit from having a shared on-attach function, so this way is also more concise
- "requires evaluating less lua at startup" -> the total time for evaluating a setup call across all language servers in the repo was around 1 ms (combined) last time I checked
- multi-file configs are not more idiomatic
- The autocommand needs to be registered before the first BufEnter is called, if you run `:e` on the buffer it should trigger re-attach (and everything should just work)
- You should not be replacing your filetype plugin (unless you really mean to), the correct usage would be putting the `setup` call in after
- If you really want this to work, you can probably add `require'lspconfig'['rust_analyzer'].manager.try_add_wrapper()` in your filetype plugin after the setup call

**Comment by cbarrete** [comment]
Thanks for the detailed reply, I appreciate it.

>The only supported way to configure lspconfig is by adding it to init.vim/init.lua

Yeah, that's my "issue" here.

>Most people will benefit from having a shared on-attach function, so this way is also more concise

Of course, me too, but that's easily shoved into some `lua/lspcommon.lua`.

>"requires evaluating less lua at startup" -> the total time for evaluating a setup call across all language servers in the repo was around 1 ms (combined) last time I checked

Fair enough

>multi-file configs are not more idiomatic

How do you suggest handling different file types differently then, shoving raw autocmds in one init file? `after/ftplugin` exists for a reason and afaik that's precisely it.

>If you really want this to work, you can probably add `require'lspconfig'['rust_analyzer'].manager.try_add_wrapper()` in your filetype plugin after the `setup` call in `after`

Brilliant, that works just fine for me, thanks :)

**Comment by mjlbach** [comment]
> How do you suggest handling different file types differently then, shoving raw autocmds in one init file? after/ftplugin exists for a reason and afaik that's precisely it.

I recommend using on_init/on_attach, since the language server generally will only be started in the filetype that matches the filetypes specified in the setup{} call, but I provided the snippet you needed to use the filetype plugin so I think this point is moot :) 

To give more details as to why it was not working for you, the issue is that the filetype plugin is evaluated after the first BufEnter, so it never triggers the autocommand even though the autocommand is mapped, the snippet I gave you manually invokes a function that attaches the current buffer after the filetype plugin is called, avoiding the issue.
