### ISSUE TITLE
Turning off linter for lspconfig

### ISSUE THREAD

**Issue by astavonin** [neovim/nvim-lspconfig#985]
- `nvim --version`: v0.5.0-dev
- nvim-lspconfig version(commit hash): f81570d
- What language server (If the problem is related to a specific language server): clangd
- Is the problem isolated to a particular language server: clangd
- Operating system/version: Ubuntu 18.04

### How to reproduce the problem from neovim startup

Install `clangd` and generate JSON compilation database. 

### Actual behaviour

`nvim` reports linter warnings

### Expected behaviour

A way to turn linter errors/warnings off. It is important if you already have a lining plugin like `dense-analysis/ale` or just needs to disable linting for specific language.

### Minimal init.vim or init.lua and code sample

```
lua << EOF
require'lspconfig'.clangd.setup{}
EOF
```

**Comment by mjlbach** [comment]
I assume you mean diagnostics off. You can override the diagnostic handler using the handlers key in setup.
```
lua << EOF
require'lspconfig'.clangd.setup{
hanlders = {['textDocument/publishDiagnostics'] = function(...) end  }
}
EOF
```

For future reference, none of the functionality you are inquiring about is in this plugin, it's all implemented in neovim core. Typically usage questions like this belong on our discourse https://neovim.discourse.group/

**Comment by neovim-discourse** [comment]
This issue has been mentioned on **Neovim Discourse**. There might be relevant details there:

https://neovim.discourse.group/t/turning-off-linter-for-lspconfig/624/1
