### ISSUE TITLE
Typescript workspace diagnostics

### ISSUE THREAD

**Issue by kaykhancheckpoint** [neovim/nvim-lspconfig#989]
Hi friends,

I have a typescript project and i want to see a list of all diagnostics. I have the following mapping to do that.

```
nnoremap <space>q :lua vim.lsp.diagnostic.set_loclist({workspace = true})<CR>
```

However this only shows me diagnostic information for the buffers i have open. Is there a way for me to see all the diagnostic messages for every file, without having to open it in a buffer.

```
require'lspconfig'.tsserver.setup{
  on_attach = function(client)
    client.resolved_capabilities.document_formatting = false
  end,
}
```

**Comment by mjlbach** [comment]
As far as I know, this is a limitation in tsserver. You can only get diagnostics for buffers that have been attached to the client.

**Comment by kaykhancheckpoint** [comment]
@mjlbach oh thats a shame, thanks

**Comment by harrysolovay** [comment]
Out of curiosity, does anyone know how VSCode gets around this limitation? Does VSCode automatically open all buffers in a workspace and regularly re-read and filter through their diagnostics?

Seems that workspace-wide diagnostics are essential (otherwise, we're unaware when changes in an open buffer will produce errors in other files). I've been getting around this by regularly running `tsc`, but this of course isn't ideal. It would be wonderful if we could reopen this issue and discuss potential solutions.

**Comment by mjlbach** [comment]
Vscode does not use theia, they use a custom non LSP compliant extension which theia wraps. There's really nothing to get around, the server does not support workspace wide diagnostics without opening the files. The issue could be raised upstream on the theia repo.

**Comment by harrysolovay** [comment]
Thank you for clarifying. I'm unfamiliar with "Theia"––would [this](https://github.com/eclipse-theia/theia) be the correct repo in which to file an issue?

**Comment by mjlbach** [comment]
Ah, we should update the link in CONFIG.md: https://github.com/theia-ide/typescript-language-server is now redirected to https://github.com/typescript-language-server/typescript-language-server

There's already an open issue for the feature you are requesting: https://github.com/typescript-language-server/typescript-language-server/issues/253

**Comment by harrysolovay** [comment]
This is tremendous! Thank you for sharing.

**Comment by mjlbach** [comment]
Ofc :) The tsserver situation frustrates me a bit too as it's a source of a lot of confusion, hoping MS releases the official language server soon, see: 

https://github.com/microsoft/TypeScript/issues/39459
https://github.com/microsoft/TypeScript/pull/45347

**Comment by toto1384** [comment]
Any updates on this?

**Comment by harrysolovay** [comment]
Closed with no message? A bit disappointing :/

**Comment by AlexErrant** [comment]
This plugin serves as a workaround for my typescript monorepo https://github.com/dmmulroy/tsc.nvim

> This Neovim plugin provides an asynchronous interface to run project-wide TypeScript type-checking using the TypeScript compiler (tsc). It displays the type-checking results in a quickfix list and provides visual notifications about the progress and completion of type-checking.

It works via quickfix instead of diagnostics... but it's better than nothing.

**Comment by dimitur2204** [comment]
Any updates on this? 

> This plugin serves as a workaround for my typescript monorepo https://github.com/dmmulroy/tsc.nvim

This is not a workaround since it doesn't list them as diagnostics, it just adds to the qflist as far as I can see. As you say @AlexErrant it is just a workaround.

**Comment by artemave** [comment]
This should do the trick https://github.com/artemave/workspace-diagnostics.nvim
