### ISSUE TITLE
How can I use the suggestions that are given to me by tsserver?

### ISSUE THREAD

**Issue by leanjunio** [neovim/nvim-lspconfig#990]
I'm attempting to auto import here and it's giving it to me as a suggestion but pressing <CR> or <tab> is not actually using the suggestion.

How can I use the Auto import suggestion?

![image](https://user-images.githubusercontent.com/8644699/122663439-7b473400-d168-11eb-99e2-968158787615.png)

**Comment by mjlbach** [comment]
Hi, this seems like a usage question which belongs on our discourse. Thanks!

https://neovim.discourse.group/
