### ISSUE TITLE
Making sense of config.md

### ISSUE THREAD

**Issue by ldelossa** [neovim/nvim-lspconfig#991]
How is one supposed to undersand Config.md ? There  is a mix of a lua statement and then markdown ? Does that markdown syntax play a role or is it only for formating?

**Comment by mjlbach** [comment]
CONFIG.md is autogenerated from the lua files. Lets take ccls for example. 

The documentation embedded in the luafile is first rendered with markdown, which usually includes the installation instructions.

In the documentation, the author chose to include an example fenced codeblock which shows the a subset of the optional list of settings you can pass to the language server.

Finally, there will be a uniform codeblock which includes 

* The require command necessary to setup the language server
* The commands optionally mapped by the language server
* The default values for the language server (cmd, filetypes, etc.)

**Comment by ldelossa** [comment]
Thank you!

**Comment by mjlbach** [comment]
Maybe this will make it easier too: https://github.com/neovim/nvim-lspconfig/pull/992

**Comment by ldelossa** [comment]
@mjlbach I'm having trouble finding the dictionary arguments that ".setup" will expect. 

For instance, I don't see any docs where I knew to use "cmd" and "filetype" dictionary keys, basically just looked at examples until I got it right.

**Comment by mjlbach** [comment]
Yes, we received complaints that lspconfig seemed too "difficult", so I moved a lot of the more technical documentation out of the main readme. setup{} takes all arguments that are passed to lsp.start_client, in addition to several arguments that are lspconfig specific. See here: https://github.com/neovim/nvim-lspconfig/blob/master/ADVANCED_README.md#setup-function

**Comment by ldelossa** [comment]
Thank you! this is the linkage I was missing.  Should be good to go now. Appreciated.

**Comment by mjlbach** [comment]
No worries :) LMK if the formatting changes I just made to CONFIG.md clarified your original question.

**Comment by ldelossa** [comment]
def an improvement.
