### ISSUE TITLE
How to disable diagnostics in newer nvim as remapping "textDocument/publishDiagnostics" is not working anymore

### ISSUE THREAD

**Issue by sevaho** [neovim/nvim-lspconfig#994]
- `nvim --version`: v0.5.0-dev+1432-g5a24284b8
- nvim-lspconfig version(commit hash): newest updated with plugged
- What language server (If the problem is related to a specific language server): pyls
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.): no
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright): no
- Is the problem isolated to a particular language server: no
- Operating system/version: arch linux 5.12.12

I updated my nvim to the latest release at this moment but the current lua code snippet does not work anymore and produces an error (error detected while processing init.vim):

```lua
vim.lsp.callbacks["textDocument/publishDiagnostics"] = function() end
```

I used this to not show any 'annoying' diagnostics.

Anyone know how I can get the same behavior? To ignore the following:

![annoying](https://user-images.githubusercontent.com/10941956/123112985-7b805180-d43e-11eb-8d24-71ec5aec3798.png)

I tried to configure the pyls itself via setup I got this:

```
    require'lspconfig'.pylsp.setup{
        on_attach = on_attach,
        settings = {
            pyls = {
                executable = "WRONG"
            },
            plugins = {
                pylint = {
                    enabled = false,
                }
            }
        }
    }
```

But it does not seem to work, not really sure how to configure https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#pyls screenshot here:

![pyls](https://user-images.githubusercontent.com/10941956/123112989-7c18e800-d43e-11eb-99ac-3041d6630b9f.png)

**Comment by mjlbach** [comment]
Callbacks->handlers
