### ISSUE TITLE
How can I set the "javascript.suggestionActions.enabled" option?

### ISSUE THREAD

**Issue by nawordar** [neovim/nvim-lspconfig#997]
I am trying to disable one annoying feature in typescript-language-server, but the only instructions I can find are for VSCode and coc.vim. I tried adding this option like this:

```lua
lspconfig.typescript.setup {
  on_attach = function(client, bufnr)
  -- ...
  end,
  settings = {
    javascript = {
      suggestionActions = {
        enabled = false,
      },
    },
    typescript = {
      suggestionActions = {
        enabled = false,
      },
    },
  },
}
``` 
…which didn't change anything. Am I doing something wrong?

**Comment by mjlbach** [comment]
coc uses a wrapper around tsserver, we have to use theia, which doesn't expose this option (see https://github.com/theia-ide/typescript-language-server/issues/166#issuecomment-728827433)
