### ISSUE TITLE
Using current config, doesn't launch lsp automatically, minimal works however

### ISSUE THREAD

**Issue by AusCyberman** [neovim/nvim-lspconfig#999]
- `nvim --version`:
![image](https://user-images.githubusercontent.com/12080502/123503999-da8dd280-d699-11eb-8f67-a9200f8eb6ff.png)
- nvim-lspconfig version(commit hash):
48e47b4d26e45977d27c06dc1bc116416ca9276d
- What language server (If the problem is related to a specific language server):
All
- Can you reproduce this behavior on other language server clients (vscode, languageclient-neovim, coc.nvim, etc.):
- N/A
- Can you reproduce this behavior on other language servers offered in the nvim-lspconfig repo? (pyls -> pyright):
Hls, tsserver
- Is the problem isolated to a particular language server:
- Operating system/version:
Nixos unstable with flakes, nixpkgs master
### How to reproduce the problem from neovim startup
Use my configuration [https://github.com/AusCyberman/dotfiles/tree/master/.config/nvim](url)
Open a file
### Actual behaviour
Language server doesnt start untilLspStart
### Expected behaviour
Language server starts automatically

### Health check
<details>
<summary>Checkhealth result</summary>
health#lspconfig#check
========================================================================
## Checking language server protocol configuration
  - INFO: hls: configuration checked.
  - INFO: tsserver: configuration checked.
  - INFO: gopls: configuration checked.
  - INFO: rust_analyzer: configuration checked.
  - ERROR: clangd: The given command "clangd" is not executable.

</details>

### LSP log

<details>
<summary>Log file</summary>
[ START ] 2021-06-26T16:20:19+1000 ] LSP logging initiated
[ INFO ] 2021-06-26T16:20:24+1000 ] ...ovim-unwrapped-master/share/nvim/runtime/lua/vim/lsp.lua:1214 ]	"exit_handler"	{}
</details>

**Comment by mjlbach** [comment]
Unfortunately, I cannot debug your config for you (it's also in fennel). I'd suggest following the minimal example, and bisecting your config, or posting on our discourse.
